### ISSUE TITLE
PMID:33134189 PA2146 Gene Knockout Is Associated With Pseudomonas aeruginosa Pathogenicity in Macrophage and Host Immune Response

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#102]
This is a publication that @JonMWilkes has selected to curate.

Curation link https://canto.phi-base.org/curs/c60773877297f4b1/ro/

**Comment by JonMWilkes** [comment]
I am having difficulty finding where to find and place the 'high-level' annotation such as increased virulence or pathogenicity. Sorry, I know this should be obvious, but I seem to be unable to locate these terms. I can also find no suitable immune modulation or cytokine expression phenotypes. Any suggestions?

**Comment by JonMWilkes** [comment]
I seem to have clocked the increased virulence - sorry about that.

**Comment by CuzickA** [comment]
> I seem to have clocked the increased virulence - sorry about that.

No problem. It should be an Annotation Extension option for 'infective ability'.

**Comment by JonMWilkes** [comment]
The 'autofill' on selecting Q9I1W9 from uniprotkb returns the name Q9I1W9_PSEAE, while the gene is called PA2146, both in the paper and on the UniprotKB page. Is it (a) possible to define the gene name when the Uniprot ID is first entered and/or (b) can this be propagated through the annotations already made for this gene?

**Comment by JonMWilkes** [comment]
I have finished and submitted the revised curation for this paper.

**Comment by CuzickA** [comment]
> The 'autofill' on selecting Q9I1W9 from uniprotkb returns the name Q9I1W9_PSEAE, while the gene is called PA2146, both in the paper and on the UniprotKB page. Is it (a) possible to define the gene name when the Uniprot ID is first entered and/or (b) can this be propagated through the annotations already made for this gene?

Hi @JonMWilkes, thanks for your comment. This is becoming a common problem. Sometimes the UniProt entries have not been annotated with the gene name. When this happens we can contact UniProt via their feedback mechanism and ask them to add in the gene name linked to the publication. I have created some guidelines on how to do this which I can send you by email.

**Comment by CuzickA** [comment]
Checking this session

Fig 1

![image](https://user-images.githubusercontent.com/11753634/173843422-aaa03b38-acd8-4376-9108-6c509046ec8a.png)

edit to
![image](https://user-images.githubusercontent.com/11753634/173843986-d2f28eb8-5936-4c7c-908e-af9b7ad3165b.png)

@JonMWilkes, when you are ready, please go ahead and contact UniProt to update the gene name as discussed.

There is a mechanism to edit the genotype name from the 'Pathogen genotype management page'

![image](https://user-images.githubusercontent.com/11753634/173844372-175417c7-b02c-4fc4-a31f-b6a325dbab8c.png)
Select 'edit details'


![image](https://user-images.githubusercontent.com/11753634/173844549-16af1a86-7501-4ecd-b79d-6fc4d4f712bd.png)
Select 'edit' and then enter the required name in 'allele name'


![image](https://user-images.githubusercontent.com/11753634/173844670-86e5c5e4-dc8e-4a25-9d1a-ac467cad7794.png)
Select 'finish'

This is a temporary fix while waiting for the UniProt name to be updated which can sometimes take a while.

**Comment by CuzickA** [comment]
Note to self
Still to check Fig 2 and 6
Make new PHIPO and PHI-ECO terms

I have made edits to the other annotations but not documented the before and after here due to lack of time.

**Comment by CuzickA** [comment]
Hi @jseager7, I had to edit the metagenotype, and this has not propagated through to the compared to control AE. I have been having to manually edit the AE (top entry edited, lower entry not edited yet). I think we had some discussion on this in the past and I thought it was fixed. Can you help please?

![image](https://user-images.githubusercontent.com/11753634/174560759-c50587f1-d84b-4bb8-9913-35c898668dfa.png)

**Comment by jseager7** [comment]
@CuzickA Seems this is because I forgot to update the code for the main PHI-Canto server. I can do this at any time, but I'll need to take PHI-Canto offline briefly.

**Comment by CuzickA** [comment]
I am inclined to delete these annotations for Fig 6a

![image](https://user-images.githubusercontent.com/11753634/174571741-692a6403-aa47-4b1f-bb3e-96034e8ce4dd.png)

The intent of the expt is to show increased inflammation with the Pa mutant, which is captured in Fig 6 b, c.

If we keep the above annotation we will need terms for 'hemorrhage'
WT 'host hemorrhage with pathogen present'
mutant 'increased host hemorrhage with pathogen'

would these come under 
![image](https://user-images.githubusercontent.com/11753634/174573042-2f309554-9ae2-43b8-8cc9-6039da7009e7.png)


or

![image](https://user-images.githubusercontent.com/11753634/174573128-40f4d360-61f7-4514-b54b-9cc82882dce6.png)


or something else?

@ValWood, please let me know if you think these would be useful annotations and whether it is worth making new PHIPO terms for 'hemorrhage'. Thanks.


_AC edit 05_07_2022. I have now updated these annotations with the new 'hemorrhage' terms.
![image](https://user-images.githubusercontent.com/11753634/177303353-0f299fd0-b755-41ec-b1c1-9047f997246c.png)
_

**Comment by JonMWilkes** [comment]
My use of the Hemorrhage phenotype reports an experimental observation listed in the paper. I agree it relates to the higher level inflammatory responses in this case, but is the pathology of all hemorrhagic responses so linked? (I'm not a pathologist so can't comment on this).

**Comment by ValWood** [comment]
Hemorrhage seems a useful clinical phenotype. However,  there are presumably existing ontologies to use for  these phenotype  (HPO or MP)?.  As you move to annotate a lot of human pathogen interactions you should plug in  a suitable existing ontology  and contribute to that ontology instead of  putting them in PHIPO  (the situation is a bit different than for pathogen and pathogen-host phenotypes where no preexisting resource existed)and share the data with other resources (like Monarch)

**Comment by CuzickA** [comment]
This sounds like a good idea. How would we use these other ontology terms in PHI-Canto? Would they need to be created as PHIPO terms with a cross-ref to the other ontology?

**Comment by ValWood** [comment]
No, you would just use it as an ontology instead of PHIPO. 
You need to decide the scope of the mammalian phenotypes that you want to curate, and find the correct ontology.
The ontologies presented could be different for different species  , so if somebody adds a human identifier, instead of PHIPO you would use  an appropriate ontology like HPO for single species annotations. The important thing is not to extend your ontology unnecessarily to cover terms that are the scope of existing obo foundry ontologies.

**Comment by CuzickA** [comment]
Is it possible in PHI-Canto to load more than one ontology / namespace into the PHI and single species phenotype annotation workflows?

**Comment by JonMWilkes** [comment]
I am starting another A.fumigatus paper in an mammalian infection model and human granulocyte killing assay. Have we made any decisions on the feasibility/desirability of utilising other ontologies for coding and classifying responses and results?

**Comment by CuzickA** [comment]
> Is it possible in PHI-Canto to load more than one ontology / namespace into the PHI and single species phenotype annotation workflows?

@jseager7 do you know if this is possible in PHI-Canto?

**Comment by CuzickA** [comment]
> I am starting another A.fumigatus paper in an mammalian infection model and human granulocyte killing assay. Have we made any decisions on the feasibility/desirability of utilising other ontologies for coding and classifying responses and results?

For now, I suggest using the terms we have in PHIPO and capturing any terms we currently don't have in the 'new term selection' option.

**Comment by CuzickA** [comment]
Hi @JonMWilkes, did you manage to contact UniProt about adding the gene name to their entry? Once this is done, please can you add the UniProt reference to this ticket. Thanks.

**Comment by jseager7** [comment]
> Is it possible in PHI-Canto to load more than one ontology / namespace into the PHI and single species phenotype annotation workflows?

@CuzickA Not that I'm aware of. Canto's configuration suggests that annotation types can only be linked to a single OBO namespace. Without code changes, I think we only have two options:

1. Add a new annotation type for human or mammalian phenotypes and link it to the relevant ontology, or

2. Get all the ontologies we need and patch them so that every term has the namespace we need (e.g. `single_species_phenotype` or `pathogen_host_interaction_phenotype`.

Option 2 is technically less work, but it's a pretty bad hack since we'd be forced to overwrite the namespace properties of the original terms (OBO terms can only have one namespace property). So it also won't work if we need to make the phenotypes available to both single-species and pathogen-host interaction branches, since we'd need more than one namespace per term for that.

Option 1 is more flexible, and should be able to make the phenotypes available for both single-species and multi-species annotations, but it would mean more workflows for the curators to follow. Also, if these phenotypes need all the same annotation extension configuration as existing phenotypes (pathogen phenotypes, host phenotypes, or pathogen-host interaction phenotypes) then I'd need to duplicate the configuration, which adds more maintenance work (though the extension configuration syntax might provide ways to share some configuration rules).

The 'ideal' solution for this problem would be to allow annotation types to link to multiple OBO namespaces, but I have no idea how much work that would involve.

**Comment by jseager7** [comment]
Although, now that I think about it, if we're considering bringing in terms from ontologies that are completely agnostic about pathogens and hosts, why do we need the single-species branch in PHIPO at all?

If we _do_ need to make some distinction between pathogen and host phenotypes even in the single-species branch, then it could be ambiguous to bring in terms that were never designed with that distinction in mind. I'm a bit wary of having the PHI-Canto annotation type name being the only semantic indication of whether the phenotype was expressed by a pathogen or a host.

If we _don't_ need the distinction, then it implies that PHIPO could be reduced to only the pathogen-host interaction phenotypes and that the single-species phenotypes could be cobbled together from other phenotype ontologies (though this would probably require multiple namespaces per annotation type).

**Comment by ValWood** [comment]
I don't think the single-species branch should really be in PHIPO. I think this was done to make ontology editing easier (and was a bit of a step gap). Ideally,  you would have single species phenotypes to use the most relevant ontology depending on the species.  For the fungal pathogens there's no ontology available. There was talk of  checking status of the available plant ontologies, but I think they were not being actively developed when we loked.

**Comment by JonMWilkes** [comment]
![PA2145_UKBreq](https://user-images.githubusercontent.com/7281304/176174267-65fbbcf0-5892-40e4-9fbb-a3eb44e54d34.png)

**Comment by JonMWilkes** [comment]
@CuzickA - I have sent the above correction request to Uniprot - I think they have changed the format since you put together the document you sent me - hope this works.

**Comment by CuzickA** [comment]
Thanks @JonMWilkes 

The confirmation email from UniProt has arrived in the curation inbox. I will move it to the UniProt correspondence folder.

Here is the ticket number
![image](https://user-images.githubusercontent.com/11753634/176175297-836ff194-64b6-43eb-9ec3-37bec6934b4f.png)

**Comment by CuzickA** [comment]
I found these in the Mammalian Phenotype Ontology
![image](https://user-images.githubusercontent.com/11753634/176883622-445c3654-30c5-463c-a2be-8bb0ab8f1999.png)
![image](https://user-images.githubusercontent.com/11753634/176883979-28c53451-a058-4c81-b99a-6bffec7a7528.png)


My thoughts are 
1) that we do not want the organ specific level term as we have already captured 'lung' in the AE.

2) the term 'Hemorrhage' on its own does not give us what we want. We would need to create terms like these

> If we keep the above annotation we will need terms for 'hemorrhage'
WT 'host hemorrhage with pathogen present'
mutant 'increased host hemorrhage with pathogen'

3) Does it seem appropriate to make these new PHIPO terms and use the 'MP' term 'Hemorrhage' as part of the logical definition?

**Comment by ValWood** [comment]
That probably does make sense.

**Comment by CuzickA** [comment]
@ValWood, I'm finding it a bit tricky to choose a PHIPO term here with the normal and abnormal terms

![image](https://user-images.githubusercontent.com/11753634/177310322-b55df3a9-548c-4b92-97b7-a11be47e569b.png)


![image](https://user-images.githubusercontent.com/11753634/177310503-744411fd-da08-453e-a1b8-0521af57bbc7.png)

It is 'normal' for the host cell to undergo morphological change after phagocytosing bacteria as seen with the WT PAO1 bacteria inoculation of host cells. Perhaps this should change  

'abnormal host morphology during pathogen invasion'
to
'alteration of host morphology during pathogen invasion present' ?? or something similar

Also does this higher level term suffice for curation or would it be better to a create a new child term capturing the 'phagocytosis'? 
'alteration of host morphology during pathogen phagocytosis present'

Similar changes for the 'normal' terms. Are these terms indicating that the host is the same as a WT uninoculated host or that the host has changed in response to a WT pathogen in the expected/normal way?

**Comment by CuzickA** [comment]
Fig 2b
![image](https://user-images.githubusercontent.com/11753634/177321903-4f854b8e-0f8e-456b-a336-754eb01afe0f.png)

I'm trying to figure out the 'key' bit of information here. Should this expt be annotated as 
1) 'presence of pathogen growth within host' based on the intracellular bacterial counts in Fig 2b
2) or are we looking at a host immune response with the host cells phagocytosing the bacteria? Do we need to add new terms for phagocytosis?
![image](https://user-images.githubusercontent.com/11753634/177324396-0051bfc5-8300-4f7d-97c6-4919a7443faa.png)

The results section heading is 'PA2146 Deletion Has No Impact on RAW264.7 Phagocytosis' 
and the intro text in this section is 'Phagocytic cells play a central role in eliciting responses to
acute P. aeruginosa infection. Phagocytosis can kill bacterial cells and present antigens to other immune cells (Pryjma et al.,).' 
The text relating to Fig 2b is 'Though, the deletion of PA2146 showed moderate tendency of inhibition
activity against RAW264.7 phagocytosis-mediated killing (Figure 2B, Left panel), there was no statistical significance
between wild type of PAO1 and PAO11PA2146 at 2 to 4 h treatment (Figure 2B, Right panel).'

Which probably favours option 2 above

any thoughts on this @JonMWilkes, @ValWood?

**Comment by CuzickA** [comment]
Once queries above for Fig 2a and 2b are resolved this session will be complete.

**Comment by CuzickA** [comment]
Looking at my query above for Fig 2a, I have made comments in https://github.com/PHI-base/phipo/issues/366 and created NTR: abnormal host morphology during phagocytosis of pathogen in https://github.com/PHI-base/phipo/issues/370

**Comment by CuzickA** [comment]
For Fig 2b
NTR: host immune system phagocytosis of pathogen present

Once NTRs loaded this session can be approved

**Comment by CuzickA** [comment]
NTRs added to session. Session approved. Closing ticket.

**Comment by CuzickA** [comment]
Gene name now updated in UniProt  https://www.uniprot.org/uniprotkb/Q9I1W9/entry

Needs updating in PHI-Canto.

**Comment by jseager7** [comment]
@CuzickA The gene name is updated in the session now:

![image](https://user-images.githubusercontent.com/37659591/203794629-6849e6b0-5221-4856-aa07-c4e3ecf5aa34.png)

It seems Canto needed to be restarted after the gene cache was refreshed in order to update the gene name in the user interface.

However, Canto is showing the entry name (RGVIR_PSEAE) instead of the gene name (PA2146, technically the name of the ordered locus). This is probably just a missing case in Canto's code, so I'll open an issue on the Canto tracker for that.
