### ISSUE TITLE
Automate edits to metagenotype for the AE compared to control

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#105]
@jseager7 I think we discussed this in the past.

I had to manually update 24 entries for #19 
Have just manually updated #61 
and plan to update #66 next

Currently the main changes are where a metagenotype has changed from 'overexpression' to 'not assayed' and also with the update of 'WT product' to 'WT level'.

We currently don't know which of the other approved sessions are affected.
What do you think the best thing to do is here?

**Comment by jseager7** [comment]
I'm closing this issue since it's already covered by https://github.com/pombase/canto/issues/2505. Unfortunately there hasn't been any work on the other issue yet, so I'll raise it again.
