### ISSUE TITLE
Should we approve curation sessions with no genes?

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#112]
(Requested by @CuzickA)

We currently have one publication in PHI-Canto (PMID:35882860) which has been submitted with no annotations due to having 'No gene specific data'. However, it's a bit unclear what we should do with this session now, since it's still pending approval.

If the session is approved, it gets included in the Canto JSON export, and this isn't useful for us since the PHI-base website has no way to display publications without genes (all data is linked to a gene page and we don't have pages for publications like PomBase does).

If the session isn't approved, then it's not clear what its final state should be: it doesn't seem like the publication is automatically categorised as uncuratable, and there doesn't seem to be a triage category explicitly for 'publication with no gene specific data', which suggests that these publications are intended to be handled in some other way.

@ValWood What does PomBase do with publications with no gene-specific data? Are they just included in PomBase as a publication with no annotations, so that nobody else tries to curate the publication a second time?

**Comment by ValWood** [comment]
you could retriage them in 
"Uncuratable publications with a community session" perhaps (if you have this option)

**Comment by CuzickA** [comment]
I have another one of these sessions now PMID:30911085 but don't have Val's suggested triage option "Uncuratable publications with a community session".

This is what we have
![image](https://github.com/PHI-base/curation/assets/11753634/ea4e790c-009e-466d-9cc7-d126e76ecf1e)
![image](https://github.com/PHI-base/curation/assets/11753634/247173eb-fef8-43dd-b755-e0eccdf1e4ee)

**Comment by CuzickA** [comment]
For now, I guess I will move it into 'other'

**Comment by CuzickA** [comment]
This still doesn't seem to move it out of the 'Needs approval' category. @ValWood, how do I do this please?  Am I missing something here??

![image](https://github.com/PHI-base/curation/assets/11753634/f1cf593e-9d6e-46e4-9175-35be8c27f177)

**Comment by ValWood** [comment]
I  "approved" it. I think that's the only way to get it out of approval, but it will no longer be in your "curated" list

**Comment by CuzickA** [comment]
It looks like I do have the option above - I just can't directly triage a publication into it
![image](https://github.com/PHI-base/curation/assets/11753634/cb1f3db8-c8c1-416a-9538-4e7d1726f020)


I approved the session and its now in both
curatable publications
- publications with approved sessions

AND

Uncuratable publications
 - uncuratable publications with a community session


Does that seem correct that is it listed as both curatable and uncuratable?

**Comment by ValWood** [comment]
> Does that seem correct that is it listed as both curatable and uncuratable?

no that seems odd, they should be mutually exclusive.
@kimrutherford  or @jseager7  may be able to advise.

**Comment by kimrutherford** [comment]
> If the session is approved, it gets included in the Canto JSON export, and this isn't useful for us since the PHI-base website has no way to display publications without genes

Will there be a problem with your web site if that publication is included?

> What does PomBase do with publications with no gene-specific data? Are they just included in PomBase as a publication with no annotations, so that nobody else tries to curate the publication a second time?

Yep and if it hasn't been curated, we have a message encouraging community curation: https://www.pombase.org/reference/PMID:33812868

> Does that seem correct that is it listed as both curatable and uncuratable?

Yep, I think it's correct (even if it's a bit unexpected) now that the publication is triaged as "Other":

The "uncuratable publications with a community session" list contains all publications that aren't triaged as "Curatable" or "New" that have a session with a community curator assigned.  It's not triaged as "Curatable" but it has been curated.   Canto doesn't handle that situation well.  It would be clearer if this list was labelled as "publications triaged as uncuratable with a community session".

The "publications with approved sessions" list includes all publications with approved sessions whatever their triage status is.

I hope that helps a bit?

**Comment by ValWood** [comment]
re the message, I don't think this
https://www.pombase.org/reference/PMID:33812868
 is the message we display in this particular situation.
This is when a paper is "curatable" but not yet curated.

IIRC i a paper is triaged as "uncuratable" there is a different message.

**Comment by kimrutherford** [comment]
> IIRC i a paper is triaged as "uncuratable" there is a different message.

True.  Here's an example: https://www.pombase.org/reference/PMID:9760264

**Comment by jseager7** [comment]
> Will there be a problem with your web site if that publication [with no genes] is included?

Probably not. The new version of the PHI-base website is indexed by gene (one webpage per gene), so a publication without any genes presumably won't have any data to show on the website.

I can't guarantee the code that loads the data won't have problems with empty curation sessions (because I didn't write the code), but if it does, I can just use a pre-processing script to remove those sessions from the export before loading.

So it looks like the answer to the original question is **yes**, we should approve sessions with no genes.

**Comment by CuzickA** [comment]
> So it looks like the answer to the original question is yes, we should approve sessions with no genes.

Great, thanks all. I'll close the ticket for now.
