### ISSUE TITLE
PMID:16048935 Specific substitutions in the echinocandin target Fks1p account for reduced susceptibility of rare laboratory and clinical Candida sp. isolates.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#116]
Chemistry publication curated by @martin2urban 

Curation link https://canto.phi-base.org/curs/4d4e524e8dc43ea2

**Comment by CuzickA** [comment]
Checking this session.

Just to note that we decided not to curate the data on the S. cerevisiae Scfks mutations. 
see #115 'Most annotations will be pathogen phenotypes. There may be a lot of overlap with other model organism databases eg https://www.yeastgenome.org/ For PHI-base we want to focus on pathogenic organisms showing a chemistry phenotype. (e.g. not Saccharomyces cerevisiae).'

**Comment by CuzickA** [comment]
Searching UniProt for Ca FKS1p'D88815' from Fig 2 legend 

![image](https://user-images.githubusercontent.com/11753634/205936668-5629ab56-71d2-4248-8134-48f2a6a3be98.png)


gives me this UniProt entry
https://www.uniprot.org/uniprotkb/O13428/entry
which interestingly already has links to caspofungin
![image](https://user-images.githubusercontent.com/11753634/205938819-364fa4cf-0fe9-4444-86bb-869c8f550f76.png)


The curation session currently has this UniProt and the species is listed as 'Pichia kudriavzevii'. This is probably incorrect.
![image](https://user-images.githubusercontent.com/11753634/205937575-6eaac6b1-1ac2-4c67-94c0-774f88188898.png)

**Comment by CuzickA** [comment]
L-733560, is a close structural analog of Caspofungin (CAS; L-743,872; MK-0991) which is a member of
the echinocandin class of antifungal compounds that noncompetitively inhibit 1,3--D-glucan synthase (GS).

'NTR: resistance to echinocandin' may be incorrect as it is a grouping term. Terms should probably be for Caspofungin or L-733560. PHIPO contains 'PHIPO_0000686 resistance to caspofungin'. I need to finish reading paper to decide which Chemistry term to use. If I need to use L-733560 then I wonder whether I could just use Caspofungin and make a comment that it is a close structural analog. There is no CHEBI id for L-733560

This is the current annotation
![image](https://user-images.githubusercontent.com/11753634/205940645-620e756c-da99-4efe-920d-41aa894b4807.png)

**Comment by CuzickA** [comment]
Ca is a diploid organism

Need to create a heterozygous genotype with one wild type allele and one mutant allele
CaFKS1b+ / Cafks1h-1 [S645P amino acid substitution]

This is all a bit confusing. @martin2urban did the authors then disrupt each of these alleles? Please go ahead and add in any extra information here and I'll try and get back to looking at this paper tomorrow.

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/curation/issues/127 regarding selecting the correct UniProt. This could be another example of when different UniProts are used for the same gene from different publications. (Note some of the authors on the two publications are the same).

**Comment by CuzickA** [comment]
Suggest use UniProt [A0A1D8PCT0](https://www.uniprot.org/uniprotkb/A0A1D8PCT0/entry)
which has also been used in https://github.com/PHI-base/curation/issues/127

**Comment by CuzickA** [comment]
Hi @MPiovesana, now we have the diploid mode enabled would you be able to have a go at this session that was started previously please? I will try and use the reassign option and you should get an email invitation.

**Comment by MPiovesana** [comment]
@CuzickA Of course, I would be happy to. I tried locating the curation session on PHI-Canto by searching the PMID, but I can only review the session, as it says it has been submitted for approval. Once it has been open again, I'll work on it.

**Comment by CuzickA** [comment]
> @CuzickA Of course, I would be happy to. I tried locating the curation session on PHI-Canto by searching the PMID, but I can only review the session, as it says it has been submitted for approval. Once it has been open again, I'll work on it.

Thanks @MPiovesana, session now reactivated.

**Comment by MPiovesana** [comment]
@CuzickA I have now read the paper and worked on this curation session. I took into account all of the comments above during the curation process. From my understanding, authors identified a mutant allele of _FKS1_ (which is named _Cafks1h-1_ in the paper) which carries a point mutation leading to the substitution of Serine 645 with a Proline. The laboratory mutant from where this mutation was identified (CAI4-R1) was heterozygous for the mutation (FKS1wt+ / FKS1(S645P)). The authors of the study then recreated this genotype by inserting one copy of the mutant allele in the FKS1 genomic loci of strain T1FOA. This strain is heterozygous for the disruption of FKS1, so its genotype (before transformation) is fks1h::hisG (disrupted allele) / FKS1 (wt allele). The mutant allele introduced by the authors was inserted either in the disrupted FKS1 locus, or in the functional FKS1 wt locus of T1FOA, in both cases resulting in a transformant with a heterozygous genotype: one functional FKS1 allele and one mutant FKS1(S645P) allele. This is very convoluted, but the schematics in Figure 1 help to understand. 

In my opinion, the disruption of one copy of FKS1 in the recipient strain T1FOA might be recorded as background information, but the important thing to be captured here is the heterozygous presence of a wt FKS1 and the mutant allele. As I was not sure how to describe the background of the recipient strain, for now I created a diploid locus by combining a wt FKS1 allele and a mutant FKS1(S645P) allele. This heterozygous genotypes was annotated with "resistance to caspofungin", and I included _+L-733560_ in experimental conditions as well as in the comment section (caspofungin structural analogue). 

Regarding the pathogen-host interaction described in the paper, the experiment is not performed with the transformant line, only with the previously described laboratory mutants (including the one from which FKS1-S645P mutation was identified, CAI4-R1). As this is a spontaneous laboratory mutant, which I presume is derived from wt strain CAI4 (included as control in Table 3), I think we could actually curate the genotype of CAI4-R1, which would be more straightforward than trying to add the information about FKS1 gene disruption in the T1FOA transformants. We could then create and annotate the metagenotype as well. What are your thoughts, @CuzickA ?

I will revisit the session to edit as necessary once we discuss these issues / questions.

**Comment by CuzickA** [comment]
> In my opinion, the disruption of one copy of FKS1 in the recipient strain T1FOA might be recorded as background information, but the important thing to be captured here is the heterozygous presence of a wt FKS1 and the mutant allele. As I was not sure how to describe the background of the recipient strain, for now I created a diploid locus by combining a wt FKS1 allele and a mutant FKS1(S645P) allele. This heterozygous genotypes was annotated with "resistance to caspofungin", and I included +L-733560 in experimental conditions as well as in the comment section (caspofungin structural analogue).

@MPiovesana, thank you for looking into this paper.

So in this case would the background be recorded as 'fks1h::hisG (disrupted allele) / FKS1 (wt allele)', because the mutant FKS1(S645P) allele was transformed into fks1h::hisG (disrupted allele) and the FKS1 (wt allele) was left unchanged?

**Comment by CuzickA** [comment]
> Regarding the pathogen-host interaction described in the paper, the experiment is not performed with the transformant line, only with the previously described laboratory mutants (including the one from which FKS1-S645P mutation was identified, CAI4-R1). As this is a spontaneous laboratory mutant, which I presume is derived from wt strain CAI4 (included as control in Table 3), I think we could actually curate the genotype of CAI4-R1, which would be more straightforward than trying to add the information about FKS1 gene disruption in the T1FOA transformants. We could then create and annotate the metagenotype as well. What are your thoughts, @CuzickA ?

When we curate the PHI phenotype we try to have a (usually WT) control metagenotype and then an altered metagenotype so that we can make the comparison of the phenotypes from both annotations.
In this case would it be possible to use FKS1 from strain CAI4 as the control and then the FKS1-S645P mutation from CAI4-R1 as part of the altered metagenotype? I guess we would still need to use the diploid genotypes for the pathogen.

**Comment by MPiovesana** [comment]
> > In my opinion, the disruption of one copy of FKS1 in the recipient strain T1FOA might be recorded as background information, but the important thing to be captured here is the heterozygous presence of a wt FKS1 and the mutant allele. As I was not sure how to describe the background of the recipient strain, for now I created a diploid locus by combining a wt FKS1 allele and a mutant FKS1(S645P) allele. This heterozygous genotypes was annotated with "resistance to caspofungin", and I included +L-733560 in experimental conditions as well as in the comment section (caspofungin structural analogue).
> 
> @MPiovesana, thank you for looking into this paper.
> 
> So in this case would the background be recorded as 'fks1h::hisG (disrupted allele) / FKS1 (wt allele)', because the mutant FKS1(S645P) allele was transformed into fks1h::hisG (disrupted allele) and the FKS1 (wt allele) was left unchanged?

@CuzickA I think you are correct that the background should be recorded as **'fks1h::hisG (disrupted allele) / FKS1 (wt allele)**', as this is the genotype of the recipient strain used for the transformation experiments. However, from my understanding, the pool of transformants obtained by the authors contained a mixture of genotypes: some with the FKS1(S645P) allele inserted in the fks1h::hisG locus, and some in the FKS1 wt locus. Even in those cases where the mutant FKS1(S645P) was inserted in the wt locus, I understand from the text and the schematic in Fig 1 that the wt allele was not disrupted; it looks like the transgene is inserted next to the locus, rather than replacing it. Hence why authors say that, regardless of which locus the transgene was integrated, the resulting genotype could be considered the same, with one functional copy of FKS1 wt and one of FKS1(S645P). It took me a while to grasp what they were talking about, but the schematics represent it well.

**Comment by MPiovesana** [comment]
> > Regarding the pathogen-host interaction described in the paper, the experiment is not performed with the transformant line, only with the previously described laboratory mutants (including the one from which FKS1-S645P mutation was identified, CAI4-R1). As this is a spontaneous laboratory mutant, which I presume is derived from wt strain CAI4 (included as control in Table 3), I think we could actually curate the genotype of CAI4-R1, which would be more straightforward than trying to add the information about FKS1 gene disruption in the T1FOA transformants. We could then create and annotate the metagenotype as well. What are your thoughts, @CuzickA ?
> 
> When we curate the PHI phenotype we try to have a (usually WT) control metagenotype and then an altered metagenotype so that we can make the comparison of the phenotypes from both annotations. In this case would it be possible to use FKS1 from strain CAI4 as the control and then the FKS1-S645P mutation from CAI4-R1 as part of the altered metagenotype? I guess we would still need to use the diploid genotypes for the pathogen.

@CuzickA Yes, you are correct. I think it would be possible to create a WT metagenotype (CAI4 strain, FKS1+), and the altered metagenotype (CAI-R4 strain, diploid locus FKS1+/FKS1(S645P)). I agree that in this case we would need to create diploid loci to represent the heterozygous genotype of the mutant.

**Comment by CuzickA** [comment]
> @CuzickA I think you are correct that the background should be recorded as 'fks1h::hisG (disrupted allele) / FKS1 (wt allele)', as this is the genotype of the recipient strain used for the transformation experiments. However, from my understanding, the pool of transformants obtained by the authors contained a mixture of genotypes: some with the FKS1(S645P) allele inserted in the fks1h::hisG locus, and some in the FKS1 wt locus. Even in those cases where the mutant FKS1(S645P) was inserted in the wt locus, I understand from the text and the schematic in Fig 1 that the wt allele was not disrupted; it looks like the transgene is inserted next to the locus, rather than replacing it. Hence why authors say that, regardless of which locus the transgene was integrated, the resulting genotype could be considered the same, with one functional copy of FKS1 wt and one of FKS1(S645P). It took me a while to grasp what they were talking about, but the schematics represent it well.

Thanks for clarifying that. Its pretty complicated. So from the point of curation I think the current genotype is informative for the PHI-base users and we don't need to record the additional genotype when the 'where the mutant FKS1(S645P) was inserted in the wt locus'.
It would still be good to add in the background as discussed above.

![image](https://github.com/PHI-base/curation/assets/11753634/277d2c74-ad56-41b9-99b4-e35883ba880a)

**Comment by CuzickA** [comment]
> @CuzickA Yes, you are correct. I think it would be possible to create a WT metagenotype (CAI4 strain, FKS1+), and the altered metagenotype (CAI-R4 strain, diploid locus FKS1+/FKS1(S645P)). I agree that in this case we would need to create diploid loci to represent the heterozygous genotype of the mutant.

Great. Do you think we also need to create a diploid homozygous genotype for the CAI4 strain, FKS1+/ FKS1+ ?

This is one of the decisions we will have to make about the rules for using diploid mode.

**Comment by MPiovesana** [comment]
> > @CuzickA I think you are correct that the background should be recorded as 'fks1h::hisG (disrupted allele) / FKS1 (wt allele)', as this is the genotype of the recipient strain used for the transformation experiments. However, from my understanding, the pool of transformants obtained by the authors contained a mixture of genotypes: some with the FKS1(S645P) allele inserted in the fks1h::hisG locus, and some in the FKS1 wt locus. Even in those cases where the mutant FKS1(S645P) was inserted in the wt locus, I understand from the text and the schematic in Fig 1 that the wt allele was not disrupted; it looks like the transgene is inserted next to the locus, rather than replacing it. Hence why authors say that, regardless of which locus the transgene was integrated, the resulting genotype could be considered the same, with one functional copy of FKS1 wt and one of FKS1(S645P). It took me a while to grasp what they were talking about, but the schematics represent it well.
> 
> Thanks for clarifying that. Its pretty complicated. So from the point of curation I think the current genotype is informative for the PHI-base users and we don't need to record the additional genotype when the 'where the mutant FKS1(S645P) was inserted in the wt locus'. It would still be good to add in the background as discussed above.
> 
> ![image](https://user-images.githubusercontent.com/11753634/253521385-277d2c74-ad56-41b9-99b4-e35883ba880a.png)

@CuzickA Agreed; I don't think the information regarding which locus the transgene was inserted in makes any difference here, so to keep the genotype as simple as possible, I would keep as it is as well, just adding the background info. I will add this now.

**Comment by MPiovesana** [comment]
> > @CuzickA Yes, you are correct. I think it would be possible to create a WT metagenotype (CAI4 strain, FKS1+), and the altered metagenotype (CAI-R4 strain, diploid locus FKS1+/FKS1(S645P)). I agree that in this case we would need to create diploid loci to represent the heterozygous genotype of the mutant.
> 
> Great. Do you think we also need to create a diploid homozygous genotype for the CAI4 strain, FKS1+/ FKS1+ ?
> 
> This is one of the decisions we will have to make about the rules for using diploid mode.

@CuzickA Yes, this is exactly what I was thinking about... generally speaking, I don't think it would be necessary to create the diploid locus for the homozygous FKS1+, but I wonder whether in this case, as it is to compared with a heterozygous diploid locus, it would make more sense to also create a diploid locus. I would think so, to keep comparisons as "uniform" as possible, if it makes sense. What do you think?

**Comment by MPiovesana** [comment]
@CuzickA Background information added.

<img width="481" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/b57a6134-3d1e-4be4-ae51-1d59d27a628b">

**Comment by CuzickA** [comment]
> @CuzickA Yes, this is exactly what I was thinking about... generally speaking, I don't think it would be necessary to create the diploid locus for the homozygous FKS1+, but I wonder whether in this case, as it is to compared with a heterozygous diploid locus, it would make more sense to also create a diploid locus. I would think so, to keep comparisons as "uniform" as possible, if it makes sense. What do you think?

Yes this is what I was thinking. In this case the AE compared to control would be used for the metagenotype annotation and it would be clearer if both the pathogen components of the metagenotype were recorded in diploid mode.

**Comment by MPiovesana** [comment]
> > @CuzickA Yes, this is exactly what I was thinking about... generally speaking, I don't think it would be necessary to create the diploid locus for the homozygous FKS1+, but I wonder whether in this case, as it is to compared with a heterozygous diploid locus, it would make more sense to also create a diploid locus. I would think so, to keep comparisons as "uniform" as possible, if it makes sense. What do you think?
> 
> Yes this is what I was thinking. In this case the AE compared to control would be used for the metagenotype annotation and it would be clearer if both the pathogen components of the metagenotype were recorded in diploid mode.

Agreed, I think this makes sense. Perhaps this can become one of the rules when creating diploid locus genotypes; if a given pathogen genotype is diploid, then all genotypes to which this one will be compared to must also be diploid.

**Comment by CuzickA** [comment]
> Agreed, I think this makes sense. Perhaps this can become one of the rules when creating diploid locus genotypes; if a given pathogen genotype is diploid, then all genotypes to which this one will be compared to must also be diploid.

Sound good. This would be required for metagenotypes. Please could you make a note of this in the FAQ section.

We may need to state that if the pathogen is diploid and all expts within the publication are performed on homozgous genotypes it is not necessary to use the diploid option. In cases where a heterozygous genotype is reported within the publication, then the remaining pathogen genotypes also need to be created in diploid mode. (Actually maybe this is already covered in the FAQ text).

It might get a bit overwhelming if all diploid organisms are curated with diploid genotypes and we would also need to consider the host genotypes.

**Comment by MPiovesana** [comment]
> We may need to state that if the pathogen is diploid and all expts within the publication are performed on homozgous genotypes it is not necessary to use the diploid option. In cases where a heterozygous genotype is reported within the publication, then the remaining pathogen genotypes also need to be created in diploid mode. (Actually maybe this is already covered in the FAQ text).
> 
> It might get a bit overwhelming if all diploid organisms are curated with diploid genotypes and we would also need to consider the host genotypes.

@CuzickA I think this sounds good and it should be straightforward enough for users to understand as well. I don't think this has been covered in the FAQ yet so I will add a note in the text about this.

**Comment by MPiovesana** [comment]
@CuzickA regarding the metagenotypes, I managed to create them as discussed above:

<img width="503" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/102a309a-3c50-4cae-9921-98b88c99e6e9">

I edited the mutant FKS1 allele name to Cafks1h-1, which is the name given by the authors in the paper. I then added FKS1(S645P) in description. Is this ok, or should we avoid using the allele name used by the authors to keep it simpler?

Also, I am not sure how to record this metagenotype annotation. The experiment performed by the authors involved infecting mice with the different C. albicans strains and treating them with caspofungin. As a result authors measured the dose of the antifungal that was necessary to reduce fungal burden in the kidneys of infected mice - higher doses for the caspofungin-resistant strains, as expected (Table 3). Can we record this result? It actually refers to a pathogen phenotype rather than the disease caused in the host, so I am not sure how to best record this...

**Comment by CuzickA** [comment]
Maybe some of these PHIPO terms could be used
![image](https://github.com/PHI-base/curation/assets/11753634/3b8a80e9-6bd6-4f12-a10a-d0e8fc075f5f)

**Comment by CuzickA** [comment]
> I edited the mutant FKS1 allele name to Cafks1h-1, which is the name given by the authors in the paper. I then added FKS1(S645P) in description. Is this ok, or should we avoid using the allele name used by the authors to keep it simpler?

Maybe its better to change 'Cafks1h-1' to 'FKS1' to keep it simpler.

**Comment by MPiovesana** [comment]
> Maybe some of these PHIPO terms could be used ![image](https://user-images.githubusercontent.com/11753634/253577408-3b8a80e9-6bd6-4f12-a10a-d0e8fc075f5f.png)

Unfortunately the authors do not give any information about the actual virulence of the strains, as the result from this experiment is stated as 'Higher doses of caspofungin were required to achieve 90% reduction in kidney burden for each of the mutant strains tested'. So we don't know how much each respective strain actually grew in the host, we just know that higher doses of caspofungin were needed to reduce growth for the resistant isolates compared to the wt.

So perhaps we could use "presence of pathogen growth within host" and add this information in annotation extension? Or comments? I now realise this experiment is actually just another way to test the chemical resistance of these strains, but it is done _in vivo_ rather than _in vitro_...

**Comment by MPiovesana** [comment]
> > I edited the mutant FKS1 allele name to Cafks1h-1, which is the name given by the authors in the paper. I then added FKS1(S645P) in description. Is this ok, or should we avoid using the allele name used by the authors to keep it simpler?
> 
> Maybe its better to change 'Cafks1h-1' to 'FKS1' to keep it simpler.

Done :)

**Comment by CuzickA** [comment]
> > Maybe some of these PHIPO terms could be used ![image](https://user-images.githubusercontent.com/11753634/253577408-3b8a80e9-6bd6-4f12-a10a-d0e8fc075f5f.png)
> 
> Unfortunately the authors do not give any information about the actual virulence of the strains, as the result from this experiment is stated as 'Higher doses of caspofungin were required to achieve 90% reduction in kidney burden for each of the mutant strains tested'. So we don't know how much each respective strain actually grew in the host, we just know that higher doses of caspofungin were needed to reduce growth for the resistant isolates compared to the wt.
> 
> So perhaps we could use "presence of pathogen growth within host" and add this information in annotation extension? Or comments? I now realise this experiment is actually just another way to test the chemical resistance of these strains, but it is done _in vivo_ rather than _in vitro_...

@MPiovesana I wonder if we could compare the pathogen-host interaction expts (both wt and mutant) with and without the chemical? The chemical could be added in the conditions. Unfortunately we can't record the dose of the chemical. The PHIPO terms could be 'presence...' and 'decreased...'. Let me know if you think that could work?

**Comment by MPiovesana** [comment]
> @MPiovesana I wonder if we could compare the pathogen-host interaction expts (both wt and mutant) with and without the chemical? The chemical could be added in the conditions. Unfortunately we can't record the dose of the chemical. The PHIPO terms could be 'presence...' and 'decreased...'. Let me know if you think that could work?

@CuzickA At first I thought this would be possible, but checking the results in the paper again, we do not actually have results for pathogen growth / disease symptoms in the condition without caspofungin... All we have the is the dose of caspofungin that was needed to reduce the pathogen burden in mice kidney for each strain.

**Comment by CuzickA** [comment]
Sounds like it will not be possible to curate a PHI for this paper.

Once the PHI-Canto bug is fixed, I will change the condition '+L-733560' to '+ caspofungin' to be consistent with the PHIPO term.

**Comment by CuzickA** [comment]
AE alteration in archetype N/A no information found

Just waiting to edit condition and session will be ready to approve.

**Comment by CuzickA** [comment]
Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/cfc9d5dd-c195-4af3-acd3-03bdb5153670)

Approving session and closing ticket
