### ISSUE TITLE
PMID: 20305029 Heterologous Expression of Mutated Eburicol 14-Demethylase (CYP51) Proteins of Mycosphaerella graminicola To Assess Effects on Azole Fungicide Sensitivity and Intrinsic Protein Function

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#117]
A chemistry resistance example paper of mutations from field isolates of a pathogen that were functionally validated by heterologous expression in a model species.

Ahead of selecting chemistry papers to curate we wanted to determine whether this type of paper can be curated in PHI-Canto. See also #115 and  #99 

From the abstract
'In this study, we have expressed wild-type and mutated M. graminicola CYP51 (MgCYP51) variants in a Saccharomyces
cerevisiae mutant carrying a doxycycline-regulatable tetO7-CYC promoter controlling native CYP51 expression.'

Looking though the paper all the expts are based on interspecies complementation. There is no Chemistry data for Mg with a lab-based gene alteration in MgCYP51.

Conclusion: This paper cannot currently be curated in PHI-Canto. 

We have interspecies complementation expts listed as an expt type that we currently cannot curate in PHI-Canto. 

@ValWood, please could you just confirm that I am correct in thinking that we can't curate interspecies complementation expts in PHI-Canto?

**Comment by ValWood** [comment]
Yes that is correct. It is still on the to-do list, but not high priority. If you keep a note in the session comments, or a flag on the ticket tracker , hopefully can g. back and quicky add one day

**Comment by CuzickA** [comment]
A few notes to self following on from the heterologous expression / interspecies complementation 'theme' in other types of expts that sound similar but are different (not necessarily chemistry resistance/sensitivity). These may need moving to another issue as will be useful in setting up the curation guidelines for more tricky expts.

1) We can use allele type 'transformant' where a gene from one strain of the pathogen species is being expressed in another strain of the SAME pathogen species. We have an example of pathogen 'transformant' genotype inoculated onto a host in a PHI in https://github.com/PHI-base/curation/issues/22 and also a single species pathogen 'transformant' genotype annotated with a Chemistry phenotype in https://github.com/PHI-base/curation/issues/51.

2) The condition options 'Delivery mechanism:...' describe how the pathogen protein of interest is delivered to the host within a pathogen-host interaction (metagenotype). This could be pathogen spore inoculation, heterologous organism (another pathogen delivers the required pathogen protein to the host), pathogen gene expressed by transgenic host etc.

3) In a Pathogen Host Interaction we can use the condition term 'heterologous species tobacco' to indicate that pathogen and host protein are being expressed in a different host species than the source species of the host protein (which would be part of the metagenotype). Also often accompanied by condition 'delivery mechanism: agrobacterium'. 'https://github.com/PHI-base/curation/issues/55
This may need to be used carefully so that we don't end up with inter species complementation host genotypes. I believe the purpose of this term is more to indicate that a pathogen and host protein combination is being studied in model host organism.

https://github.com/PHI-base/canto-docs/issues/10
