### ISSUE TITLE
PMID: 18779358 Genetic Analysis of Fenhexamid-Resistant Field Isolates of the Phytopathogenic Fungus Botrytis cinerea

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#118]
https://canto.phi-base.org/curs/78fb5c4223c6062b

**Comment by CuzickA** [comment]
Looking for UniProt Id for erg27 in Bc in strain B05.10

I get multiple UniProt ids when search for ‘erg27 Botrytis cinerea’
https://www.uniprot.org/uniprotkb?query=erg27%20Botrytis%20cinerea
![image](https://user-images.githubusercontent.com/11753634/220636944-81f89e01-d81e-4dd0-8b3d-d9cc0c4df1c8.png)

I looked at each of these entries and none were for strain B05.10 (despite being listed as a reference proteome)

It looks like there are 3 Bc/Bf reference proteomes listed 
![image](https://user-images.githubusercontent.com/11753634/220637308-8b4d5b93-8a52-454a-a43f-071b1fb47432.png)

This entry is for one of the other reference proteomes strain T4
https://www.uniprot.org/uniprotkb/Q873W7/entry

(I do not know if this sequence is exactly the same as the strain B05.10 erg27 sequence.)
I will use this strain T4 UniProt id for now and list B05.10 as the strain in the genotypes.

Also no joy in ensemblfungi
![image](https://user-images.githubusercontent.com/11753634/220639381-cd52c430-ab1a-4ab7-a5de-974f8d636c57.png)
![image](https://user-images.githubusercontent.com/11753634/220639576-57b235a6-4ad1-4543-be8f-22fe097ab399.png)

**Comment by CuzickA** [comment]
My query on method used here

As I understand it the plasmid containing a Fenhexamid resistant allele of Botrytis erg27 (from strain 1837 or 223b) is being randomly inserted into the Fenhexamid sensitive strain B05.10. (_AC this is incorrect, its a nonintegrative plasmid -see below_).Rather than being inserted using a gene replacement method. 

I think that I would need to generate the genotypes differently dependent upon the method.

If the strain B05.10 erg27 fenhexamid sensitive allele is present in the genotype and the strain 1837 fenhexamid resistant allele of erg27 is inserted rather than replacing the existing gene then I would class this as a ‘transformant’ allele type.
![image](https://user-images.githubusercontent.com/11753634/221582817-43471dab-c7ab-4597-8405-e5b5de2166e4.png)

If the B05.10 erg27 fenhexamid sensitive allele is replaced by the strain 1837 fenhexamid resistant allele of erg27, I may try and create an amino acid substitution genotype indicating the F412I change found in the resistant allele.
![image](https://user-images.githubusercontent.com/11753634/221582961-4c2c1edd-748d-442f-a509-032464c6b3a1.png)


Discussed this query in meeting with Kim and Nichola, here is the decision

We decided that we will keep the first 3 annotations and delete the 4th annotation. This is because the R allele was expressed on a high replicating plasmid not integrated into genome (see text page 3936) in addition to the S allele being present in the recipient genome. Therefore this would be classed as ‘transformant’ allele as the S allele was NOT replaced by the R allele (genotype in row 4). We decided to draft a slide containing the types of chemistry expt to make it easier moving forward to know which genotypes to create and curate. This could form part of the triage process.

We decided that we were happy to keep the WT control annotations for strain B05.10 and 1837. These would both be ‘normal growth on…’ We need to make the term definitions and guidance clear that in the case of chemistry curation ‘normal’ means equivalent to the WT strain in each case. This could be S or R to Chemistry. We discussed that the PHIPO terms for Chemistry annotations could be flagged up as a different colour on the PHI5 website to make this clear.

So that we don't lose the information that the R allele has an AA substitution F412I we decided to incorporate this into the genotype name of the WT Erg27 1837 genotype. (AC still to do).

**Comment by CuzickA** [comment]
Hi @ValWood I'm finding it a bit tricky to decide how best to create these genotypes.
Wild type Bc strain B05.10 Erg27 is sensitive to fenhexamid
Wild type Bc strain 1837 Erg27 is resistant to fenhexamid
The known AA change between the sensitive and resistant strain is F412I.
The resistant allele from strain 1837 has been transformed into the sensitive strain B05.10 and the phenotype shifts from 'normal growth on fenhexamid' to 'resistance to fenhexamid'.
The difficulty I am having is recording the known AA F412I change as it due to natural variation between the strains rather than lab-based AA substitution method.
I currently have
![image](https://user-images.githubusercontent.com/11753634/222119112-4fd9f832-9f89-4a6b-a31e-97a8a6a7f827.png)

I wonder if the WT genotype for strain 1837 should actually be AA substitution rather than wild type with the AA alteration listed in the genotype name. This option would look like this
![image](https://user-images.githubusercontent.com/11753634/222122081-ba1fdafc-04d2-472e-b06c-0d8b247683cf.png)

**Comment by CuzickA** [comment]
Change of plan. After speaking with Kim H-K today and explaining the difficulty of trying to curate the WT strains we have agreed to no longer do this. Kim had previously requested that the WT be curated with 'normal growth to [chemical]' terms but now understands that it is better not to do this and reserve the 'normal growth to [chemical]' terms for annotations where an altered genotype exhibits the same phenotype as the wild-type. 

Need to update https://github.com/PHI-base/curation/issues/115 with this information. DONE

**Comment by CuzickA** [comment]
Curation session now looks like this

![image](https://user-images.githubusercontent.com/11753634/222177795-fdbf35f6-31e1-4222-b3c5-3e44c88d8006.png)


Hopefully this looks correct now @ValWood

**Comment by ValWood** [comment]
I was going to look tonight. Glad you sorted it.
v

**Comment by CuzickA** [comment]
Added GO terms

![image](https://user-images.githubusercontent.com/11753634/222694408-4df41f62-0095-4188-9006-00cf7029b120.png)
![image](https://user-images.githubusercontent.com/11753634/222694463-cb7b0bc0-67f2-4c6c-99a1-6cdc5b0216a2.png)


Removed all old unused genotypes.

Session now approved.

**Comment by CuzickA** [comment]
The new AE is now available. I have added in the information. I would like Nichola to check it looks correct and then I will re-approve the session.

![image](https://user-images.githubusercontent.com/11753634/224296237-07e5ee44-9388-428d-a6fb-9bed9d2d02ab.png)

**Comment by CuzickA** [comment]
I need to update the 'transformant' genotypes following the new guidance in #157, in this case probably just adding in the background info.

**Comment by CuzickA** [comment]
Now updated 

![image](https://github.com/PHI-base/curation/assets/11753634/b06c0741-0fd4-45c2-ba65-f932890c853d)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F412I; Erg27; BOTRCI 
F412S; Erg27; BOTRCI

Straight forward to find in Nichola's S file in Table S7
![image](https://github.com/PHI-base/curation/assets/11753634/44ab7d10-db04-4edd-8364-1aef07c2a037)

![image](https://github.com/PHI-base/curation/assets/11753634/fa92303f-c877-4f83-9489-c41b3bc48171)
![image](https://github.com/PHI-base/curation/assets/11753634/9100a30e-e128-49eb-af5a-fd81577c4e5a)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
