### ISSUE TITLE
PMID:22045588 Strong resistance to the fungicide fenhexamid entails a fitness cost in Botrytis cinerea, as shown by comparisons of isogenic strains.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#120]
Publication being curated by new biocurator Maiara.

Session link https://canto.phi-base.org/curs/a833b456cd20c3ff

**Comment by CuzickA** [comment]
Same issue trying to find Uniprot id for Erg27 as in #118.

Suggest we use the same UniProt id, so that curations for both articles (some shared authors) are linked on ONE PHI-base 5 page.

**Comment by CuzickA** [comment]
Tagging @MPiovesana, please go ahead and try writing a test comment.

**Comment by MPiovesana** [comment]
Hello @CuzickA , I believe all is working with my GitHub account. Shall we start exchanging comments throughout the curation process here rather than on Google Doc?

**Comment by CuzickA** [comment]
Excellent! 

Yes, lets use this GitHub issue tracker for queries/ comments related to a particular publication. I use one issue tracker ticket per publication.

More general queries and text development for the FAQs etc can still be on the Google Doc :-)

**Comment by MPiovesana** [comment]
I will insert the notes regarding the curation of this paper here, transferring them from Google Doc:
1. PHIPO term to describe metagenotype interaction: I opted for “presence of pathogen-associated host lesions”.

**Comment by MPiovesana** [comment]
2. **Chemical resistance, Table 3**: Annotated with “resistance to fenhexamid” term. 
**AC** Looks good

4. **Mycelial growth, Figure 1:** if we annotate all phenotypes described in this Figure, it would result in 27 annotations (three lines x three temperature conditions x three media compositions). Therefore, I opted for annotating the conditions which the authors describe as most striking: _“Media supplying intermediate levels of nutrients had only a minor impact on the growth of the B05.10ku70ergF412 mutant. The most striking differences were observed on minimal medium at low and high temperatures (11 and 26 ◦C) and on rich medium at moderate and high temperatures (20 and 26 ◦C).” This resulted in 12 annotations using the term “decreased hyphal growth”._ I specified the temperature condition in the Comment section as temperature is automatically converted to “low” or “standard” temperature in the Conditions section.
**AC:** These annotations seem sensible.

**Comment by MPiovesana** [comment]
4. **Sclerotium production, Figure 2**: similarly to Figure 1, if we annotate all phenotypes described in this figure, we would have an additional 27 annotations. I was going to annotate the phenotypes highlighted by the authors on the text (_“In conditions in which the parental wild-type strain produced more than 80 sclerotia per plate (i.e. poor medium at 11 and 20 ◦C, intermediate medium at 20 ◦C and richmedium at 26 ◦C), all B05.10ku70ergF412 mutants produced significantly fewer sclerotia than the parental strain. By contrast, they produced more sclerotia on intermediate medium at 11 and 26 ◦C and on rich medium at 20 ◦C, conditions in which the wild type produced fewer than 20 sclerotia per plate”_). However, I did not find a phenotype term to describe altered sclerotia production, and these annotations are still to be made.
**AC:** I agree. I think we will probably leave these annotations for now as they would require new PHIPO terms and we probably don't need to do really 'deep levels' of curation for the Chemistry papers at the moment. I have added a label to this ticket about maybe need these terms in the future, especially if required to annotate other papers.

**Comment by MPiovesana** [comment]
5. **Conidiation, Figure 3:** the decreased production of conidia was annotated using the terms “normal/decreased number of asexual spores”. No problems encountered here.
**AC:** This looks good. I have also added in the condition '7 dpi' to these annotations. Although the current PHI-ECO term definition states 'pathogen inoculation onto host', I have this ticket open to edit these terms to include pathogen inoculation of media https://github.com/PHI-base/phi-eco/issues/12
![image](https://github.com/PHI-base/curation/assets/11753634/3a63514a-7cf5-45a3-a491-1b69dc93dfcc)


7. **Mycelial growth after freezing, Figure 4**: in this experiment the authors describe the reduced mycelial growth of the mutant lines after freezing and thawing. It should be a straightforward annotation using the “decreased hyphal growth” term, but I could not find anything in the Conditions section to denote the freezing treatment. I could include details in the Comment section, but the rest of the annotation will look identical to the ones for Figure 1. Is there any way to include the freezing in experimental conditions?
**AC**: I agree. I think we will probably leave these annotations for now as they would require new PHI-ECO terms and we probably don't need to do really 'deep levels' of curation for the Chemistry papers at the moment. I have added a label to this ticket about maybe need these terms in the future, especially if required to annotate other papers.

**Comment by MPiovesana** [comment]
7. **Metagenotypes:** annotated with “presence of pathogen-associated host lesions” PHIPO term; unaffected pathogenicity for all three lines compared to control metagenotype.
**AC:** looks good. I added in 2 conditions
![image](https://github.com/PHI-base/curation/assets/11753634/ae466fce-fced-4ff4-b27a-74b2a373be1a)

**Comment by CuzickA** [comment]
Hi @MPiovesana, this session looks good. I have added a few notes above.

I have a query on the expression selected for the Erg27 mutants. [WT level] has been selected - did the authors check that the expression levels of these mutants was the same as the WT? If not, it would probably be better to use [not assayed] for the Erg27 mutants.

**Comment by CuzickA** [comment]
I have also added in the AE alteration_in_archetype.

@MPiovesana this is a new development and I will show you the draft Help documentation about this once its finalised.

**Comment by CuzickA** [comment]
> Hi @MPiovesana, this session looks good. I have added a few notes above.
> 
> I have a query on the expression selected for the Erg27 mutants. [WT level] has been selected - did the authors check that the expression levels of these mutants was the same as the WT? If not, it would probably be better to use [not assayed] for the Erg27 mutants.

This session will be ready to approve once this has been clarified.

**Comment by MPiovesana** [comment]
> Hi @MPiovesana, this session looks good. I have added a few notes above.
> 
> I have a query on the expression selected for the Erg27 mutants. [WT level] has been selected - did the authors check that the expression levels of these mutants was the same as the WT? If not, it would probably be better to use [not assayed] for the Erg27 mutants.

@CuzickA , thanks for the question. The authors did not check the expression levels, but as they mutant copies of the Erg27 genes were inserted in the native locus in the genome, I assumed this could be annotated as WT level, given that it will be under the influence of the native promoter. Is that not correct? Should I only assume WT level when expression levels have been measured (by qPCR, for example)? Apologies if that is the case! We can then go ahead and edit it to [not assayed].

**Comment by MPiovesana** [comment]
> 7. **Metagenotypes:** annotated with “presence of pathogen-associated host lesions” PHIPO term; unaffected pathogenicity for all three lines compared to control metagenotype.
>    **AC:** looks good. I added in 2 conditions
>    ![image](https://user-images.githubusercontent.com/11753634/241166286-ae466fce-fced-4ff4-b27a-74b2a373be1a.png)

Thank you for adding the experimental conditions; I will make sure to add them in future curations of metagenotypes, as required.

**Comment by MPiovesana** [comment]
> I have also added in the AE alteration_in_archetype.
> 
> @MPiovesana this is a new development and I will show you the draft Help documentation about this once its finalised.

@CuzickA , thank you, I was not sure what archetype annotations referred to. Happy to discuss this in a meeting soon.

**Comment by CuzickA** [comment]
> > Hi @MPiovesana, this session looks good. I have added a few notes above.
> > I have a query on the expression selected for the Erg27 mutants. [WT level] has been selected - did the authors check that the expression levels of these mutants was the same as the WT? If not, it would probably be better to use [not assayed] for the Erg27 mutants.
> 
> @CuzickA , thanks for the question. The authors did not check the expression levels, but as they mutant copies of the Erg27 genes were inserted in the native locus in the genome, I assumed this could be annotated as WT level, given that it will be under the influence of the native promoter. Is that not correct? Should I only assume WT level when expression levels have been measured (by qPCR, for example)? Apologies if that is the case! We can then go ahead and edit it to [not assayed].

Hi @ValWood, would you use [WT level] or [not assayed] in this case?

![image](https://github.com/PHI-base/curation/assets/11753634/1510caac-0414-4b0d-b9cd-1c726e1d0e72)

**Comment by CuzickA** [comment]
Hi @ValWood, would you use [WT level] or [not assayed] in the above case?

**Comment by ValWood** [comment]
[not assayed] seems correct.

I should also let you know that in PomBAse we no longer collect the expression as part of the genotype. This is due to :

i) when we did this the phenotypes to a genotype which had WT or "not assayed" would be  displayed separately, and we realized users did not want this.

ii) if the protein level is assayed and found to be changed in the WT, we capture this as a phenotype  (increased transcript level, or increased protein level etc).

So we now only capture knockdown and overexpression

**Comment by CuzickA** [comment]
Thanks @ValWood.

@MPiovesana, Please could you change the expression levels to [not assayed] in the appropriate genotypes.

**Comment by CuzickA** [comment]
> I should also let you know that in PomBAse we no longer collect the expression as part of the genotype. This is due to :

> 
> i) when we did this the phenotypes to a genotype which had WT or "not assayed" would be displayed separately, and we realized users did not want this.
> 
> ii) if the protein level is assayed and found to be changed in the WT, we capture this as a phenotype (increased transcript level, or increased protein level etc).
> 
> So we now only capture knockdown and overexpression


@ValWood This is interesting. I guess we are not currently planning to make similar changes in PHI-Canto. @jseager7 FYI

**Comment by MPiovesana** [comment]
> Thanks @ValWood.
> 
> @MPiovesana, Please could you change the expression levels to [not assayed] in the appropriate genotypes.

@CuzickA This has now been changed in the appropriate genotypes. Can I submit curation for review?

**Comment by CuzickA** [comment]
Thanks @MPiovesana. Yes, please go ahead and submit the curation for review.

**Comment by CuzickA** [comment]
Looks good. I will approve this session once I can login into Admin (currently an ORCID glitch due to server transfer).

**Comment by CuzickA** [comment]
Session now approved. Closing ticket.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F412S; Erg27; BOTRCI
F412I; Erg27; BOTRCI
F412V; Erg27; BOTRCI

Straight forward to find in Nichola's S file in Table S7
![image](https://github.com/PHI-base/curation/assets/11753634/44ab7d10-db04-4edd-8364-1aef07c2a037)

![image](https://github.com/PHI-base/curation/assets/11753634/9100a30e-e128-49eb-af5a-fd81577c4e5a)

![image](https://github.com/PHI-base/curation/assets/11753634/6c6d072b-68a3-442e-92e5-f4de058dc548)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/phipo/issues/424

PHIPO terms created to cover sclerotia/resting structure.
Add to session once loaded into PHI-Canto

**Comment by CuzickA** [comment]
Added
![image](https://github.com/PHI-base/curation/assets/11753634/b2ad2a5c-d9e8-4fc3-af15-2ce6f6596afa)

approved session, closing ticket
