### ISSUE TITLE
PMID:34490974 Directed evolution predicts cytochrome b G37V target site modification as probable adaptive mechanism towards the QiI fungicide fenpicoxamid in Zymoseptoria tritici.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#121]
Publication being curated by new biocurator Maiara.

https://canto.phi-base.org/curs/9da833d2f46ce551

**Comment by CuzickA** [comment]
Tagging @MPiovesana

**Comment by MPiovesana** [comment]
I have attempted curation of this paper and the following notes/questions arose in the process:
1. I have requested the creation of two terms: “resistant to fenpicoxamid” and “normal growth on tolnaftate”; awaiting term creation.

AC: https://github.com/PHI-base/phipo/issues/390
https://github.com/PHI-base/phipo/issues/391

**Comment by MPiovesana** [comment]
2. In addition to creating the phenotype terms, I believe we also need to add “fenpicoxamid” and “tolnaftate” as experimental conditions, so that we can indicate their presence in the growth media;

**AC**:
If a condition is not available in the list you can add it as free text. It will be red. I will then need to make the term in PHI-ECO and load it into PHI-Canto before I can approve the session.
![image](https://github.com/PHI-base/curation/assets/11753634/7288797f-275d-4855-b019-ef76146f557a)


https://github.com/PHI-base/phi-eco/issues/27
https://github.com/PHI-base/phi-eco/issues/28

**MP:** That's great, thank you very much, Alayne. I will bear this in mind for the curation of future papers.

**Comment by MPiovesana** [comment]
3. The authors also supplement media with propyl gallate, an alternative oxidase (AOX) inhibitor, to test whether overexpression of AOXs played a role in the resistance phenotype. I could not find propyl gallate available in the experimental conditions section;

**Comment by MPiovesana** [comment]
4. The authors also test whether the mutations lead to decreased growth in a cell growth assay performed in liquid culture and monitored on a plate reader. I was unsure whether, in this instance, the term “normal hyphal growth” could be used, or whether we need another term to describe the growth of Z. tritici in liquid culture. Are hyphal growth terms only used to describe growth on agar plates, or also liquid cultures?

AC: hyphal growth terms can be used for growth in both agar plates and liquid cultures, so long as the pathogen is growing hyphally. Z. tritici is di-morphic and also has a yeast-like growth. We would need to use the unicellular growth terms in this case. This is a topic that needs to be written up in the FAQ.

**Comment by MPiovesana** [comment]
5. The compound UK-2A, from which fenpicoxamid is derived, was also used in susceptibility assays. I did not annotate these at the moment as UK-2A is not available in experimental conditions, and I believe we would have to create yet another term to describe resistance to it. Perhaps unnecessary to annotate this as it also implies resistance to fenpicoxamid;

AC: I agree

**Comment by MPiovesana** [comment]
6. 
Lastly, I was unsure about the best way to annotate the genotype of fenpicoxamid-resistant strains obtained in the 37-16 background. The 37-16 strain was generated by the authors via lab cross (Table 4), but they do not specify which were the parental strains used to obtain it. As this strain belongs to their lab collection, I manually entered its name (37-16) and added the additional mutation CytB-G143A, which characterises it, in the background field. I had considered adding the G143A mutation as background in the IPO323 strain, but I don’t think it would be the most accurate way of curating the experiment as we are not sure whether IPO323 was one of the parental strains.

AC: I also have queries about this below

**Comment by MPiovesana** [comment]
Additional note: I added "7 days post inoculation" under Experimental conditions following the same rationale used for annotation discussed in issue #120 . However, I could not find a suitable exp condition to add to the annotations of "normal hyphal growth", as those were carried out for 60 hours - and this is not available under exp condition. Is it necessary to add "60 hours post inoculation" as exp condition term?

AC: We could either leave this information unentered or just select a close option e.g. 2 dpi or 3 dpi and make a note in the comments. (60 hours =2.5 days). I could create it as another conditions term but I'm not sure how often it would be used in other annotations.

**Comment by CuzickA** [comment]
Hi @MPiovesana, For Fig 3, I'm looking at the 'sensitive to tolnaftate' annotation and I don't think its correct.

![image](https://github.com/PHI-base/curation/assets/11753634/0520f927-427a-4cda-85de-c8e382898b82)

In the Figure it looks to me as if the IPO323 mutants growth on tolnaftate is the same as the WT IPO323. Both look to be sensitive to tolnaftate. If there is no difference in growth between the WT and mutant then this would be annotated as 'normal growth on tolnaftate'. However, as we are trying to curate the key information from the chemistry publications I don't think these annotations are necessary.

Please could you have another look at this and let me know if you agree?

**Comment by MPiovesana** [comment]
> 

That's great, I will bear that in mind for future curations.

**Comment by CuzickA** [comment]
These genotypes are a bit tricky. We have a mixture of natural strain variation (a known AA change in strain 37-16 compared to a reference strain IPO323) and then the altered AA as part of the expt.

If they were in the same strain we would record this as two AA substitutions within the gene. Currently, the natural strain variation has been captured in the 'background' section. Does this seem like a reasonable thing to do @ValWood? Its tricky as we decided not to curate the WT natural variants.

![image](https://github.com/PHI-base/curation/assets/11753634/8956818a-afa2-4ce3-9671-da73468b1d0b)

**Comment by CuzickA** [comment]
If I was aiming for a level of key minimal information for this paper I think that I would omit the annotations on the above tricky altered natural variant and also the tests on the other chemistries.

If we focused on capturing the key information from the papers title then I would probably only curate

The cytB AA substitution leading to increased resistance to fenpicoxamide.
![image](https://github.com/PHI-base/curation/assets/11753634/8a9a8854-544f-4a65-b1ac-c8409192e110)

and 
![image](https://github.com/PHI-base/curation/assets/11753634/388be594-4ce8-4cde-b186-82a6339b7720)


The other expts are interesting but many of them are controls to rule out other possible methods of resistance.

It's tricky to know how much information to curate, we were thinking on keeping it to a minimum for the chemistry papers.

**Comment by MPiovesana** [comment]
> Hi @MPiovesana, For Fig 3, I'm looking at the 'sensitive to tolnaftate' annotation and I don't think its correct.
> 
> ![image](https://user-images.githubusercontent.com/11753634/243669048-0520f927-427a-4cda-85de-c8e382898b82.png)
> 
> In the Figure it looks to me as if the IPO323 mutants growth on tolnaftate is the same as the WT IPO323. Both look to be sensitive to tolnaftate. If there is no difference in growth between the WT and mutant then this would be annotated as 'normal growth on tolnaftate'. However, as we are trying to curate the key information from the chemistry publications I don't think these annotations are necessary.
> 
> Please could you have another look at this and let me know if you agree?

@CuzickA Agreed, that was an oversight of my part; you are right in that the best annotation for this would be "normal growth on tolnaftate". I am happy to either amend the annotation or delete, as you think best.

**Comment by MPiovesana** [comment]
> If I was aiming for a level of key minimal information for this paper I think that I would omit the annotations on the above tricky altered natural variant and also the tests on the other chemistries.
> 
> If we focused on capturing the key information from the papers title then I would probably only curate
> 
> The cytB AA substitution leading to increased resistance to fenpicoxamide. ![image](https://user-images.githubusercontent.com/11753634/243691039-8a9a8854-544f-4a65-b1ac-c8409192e110.png)
> 
> and ![image](https://user-images.githubusercontent.com/11753634/243691787-388be594-4ce8-4cde-b186-82a6339b7720.png)
> 
> The other expts are interesting but many of them are controls to rule out other possible methods of resistance.
> 
> It's tricky to know how much information to curate, we were thinking on keeping it to a minimum for the chemistry papers.

@CuzickA Thank you for your comments here, it makes sense. I have been annotating all the experiments as it is always easier to then delete them rather than having to go back and add new annotations. I do wonder whether it would be interesting to keep some of the control experiments (testing other chemicals) as it might prevent someone from repeating the experiment. But I also understand the aim to only curate key information. I'd be happy to delete annotations as appropriate.

**Comment by CuzickA** [comment]
> > Hi @MPiovesana, For Fig 3, I'm looking at the 'sensitive to tolnaftate' annotation and I don't think its correct.
> > ![image](https://user-images.githubusercontent.com/11753634/243669048-0520f927-427a-4cda-85de-c8e382898b82.png)
> > In the Figure it looks to me as if the IPO323 mutants growth on tolnaftate is the same as the WT IPO323. Both look to be sensitive to tolnaftate. If there is no difference in growth between the WT and mutant then this would be annotated as 'normal growth on tolnaftate'. However, as we are trying to curate the key information from the chemistry publications I don't think these annotations are necessary.
> > Please could you have another look at this and let me know if you agree?
> 
> @CuzickA Agreed, that was an oversight of my part; you are right in that the best annotation for this would be "normal growth on tolnaftate". I am happy to either amend the annotation or delete, as you think best.

Thanks, I have made the change below and will added the NTR to the PHIPO tracker
![image](https://github.com/PHI-base/curation/assets/11753634/7eb180b4-1ead-467d-981d-ee0da5c1c9b4)

**Comment by CuzickA** [comment]
@MPiovesana, please could you double check if these are correct or really 'normal growth on ...'

![image](https://github.com/PHI-base/curation/assets/11753634/4b9667b8-c73b-41b2-ad5e-822c0453815e)

Then we just need to figure out whether this genotype seems reasonable.
![image](https://github.com/PHI-base/curation/assets/11753634/55f7f646-edae-47ee-aa45-73414be4322f)

**Comment by MPiovesana** [comment]
@CuzickA I have now checked and amended all phenotypes where necessary; as this was the second paper I was curating, I was a little confused with the notion of annotating a sensitive/resistant phenotype as normal growth, but I understand the term characterises the phenotype in comparison to a control strain (non-curated). I believe all annotations are now correct.

**Comment by CuzickA** [comment]
> @CuzickA I have now checked and amended all phenotypes where necessary; as this was the second paper I was curating, I was a little confused with the notion of annotating a sensitive/resistant phenotype as normal growth, but I understand the term characterises the phenotype in comparison to a control strain (non-curated). I believe all annotations are now correct.

Thanks very much. It is a bit tricky and I think the FAQ text will help future curators.

**Comment by ValWood** [comment]
I might be misunderstanding the comments but resistance and sensitivity phenotypes  are children of
[abnormal vegetative cell population growth] (at least in FYPO) 

...compared to the WT control, growth would be increased or decreased in the mutant.
A WT control, or a mutant strain which shows no change,  could be captured as "normal growth on blah",

**Comment by ValWood** [comment]
> If they were in the same strain we would record this as two AA substitutions within the gene. Currently, the natural strain variation has been captured in the 'background' section. Does this seem like a reasonable thing to do @ValWood? Its tricky as we decided not to curate the WT natural variants.

Re, yes so in this case the Cyt-B is WT for this strain even though it has the G143A (is that AA or nt?)
I think you  should record this. Maybe allele comment field is better than background?

**Comment by CuzickA** [comment]
> I might be misunderstanding the comments but resistance and sensitivity phenotypes are children of [abnormal vegetative cell population growth] (at least in FYPO)
> 
> ...compared to the WT control, growth would be increased or decreased in the mutant. A WT control, or a mutant strain which shows no change, could be captured as "normal growth on blah",

Yes, this is correct thanks. We don't curate the WT controls in this case but when a mutant shows no change we use 'normal growth on...'

We plan to write this up and maybe provide a screenshot example for the new FAQ file we are developing to link to our main User help.

**Comment by CuzickA** [comment]
> > If they were in the same strain we would record this as two AA substitutions within the gene. Currently, the natural strain variation has been captured in the 'background' section. Does this seem like a reasonable thing to do @ValWood? Its tricky as we decided not to curate the WT natural variants.
> 
> Re, yes so in this case the Cyt-B is WT for this strain even though it has the G143A (is that AA or nt?) I think you should record this. Maybe allele comment field is better than background?

Good spot, yes nt change in the WT for this strain compared to reference strain IPO323 and then mutated with AA substitution. 

I'm not sure if the allele comment field is displayed in PHI-base 5?

**Comment by ValWood** [comment]
In this case if they are mutating to look like the reference strain, maybe  you don't need to record the difference to some "reference" strain?

- an allele comment might still be useful (like "mutated to resemble reference strain"). Probably this isn't critical-Phi-base might later want to display these variants in some protein viewer in which case the residue present in different strains will be clear. Even now the range of amino acids at a specific  position could be extracted computationally, so maybe it is better not to report the  difference to the reference strain  ( since reference strain is an arbitrary choice).

**Comment by CuzickA** [comment]
> In this case if they are mutating to look like the reference strain, maybe you don't need to record the difference to some "reference" strain?
> 
> * an allele comment might still be useful (like "mutated to resemble reference strain"). Probably this isn't critical-Phi-base might later want to display these variants in some protein viewer in which case the residue present in different strains will be clear. Even now the range of amino acids at a specific  position could be extracted computationally, so maybe it is better not to report the  difference to the reference strain  ( since reference strain is an arbitrary choice).


Sorry its a bit difficult to explain this one!

They are not mutating it to look like the reference strain.

Natural variant strain 37-16 differs to the reference strain IPO323 with a nt substitution G143A in CytB.

AA substitution G37V is then made in both strain 37-16 and IPO323.

We do not curate the WT controls so it is difficult here.

Do we only curate IPO323 CytB G37V or do we also try to curate  37-16 CytB G37V (background G143A compared to IPO323)?

**Comment by MPiovesana** [comment]
@CuzickA and @ValWood thank you very much for your insightful comments and suggestions. Perhaps it would be more straightforward in this instance to only annotate the phenotypes of reference strain IPO323, as we don't have any other information about the background of 37-16 apart from the G143A mutation. It isn't a commonly used reference strain as it was produced in the laboratory by the authors of the study. 

I have also double checked the paper and I believe **G143A** to be an AA substitution, as it is mentioned as being a change in the Qo site of cytochrome b. Furthermore, double mutants are labelled as G37V + G143A, which reinforces the idea of both being aa substitutions (it would be confusing if authors had used aa + nt substitution annotation without indicating it).

**Comment by ValWood** [comment]
>It isn't a commonly used reference strain as it was produced in the laboratory by the authors of the study.

So IPO323 is a lab strain?
In this case what is the "natural isolate"  IPO323 was derived from?

The natural isolate should be the strain recorded, and any mutants added by the lab  previously to the gene of interest would need to be included in the alleles. 

in this case it would be: 
strain name of natural isolate for IPO323/ cob  G37V + G143A

**Comment by CuzickA** [comment]
As I understand it there are two natural isolates
IPO323 (reference strain) which is normally sensitive to fenpicoxamide and sensitive to azoxystrobin (Fig 3)
37-16 (in the text below called strain StrR) which is normally sensitive to fenpicoxamide and resistant to azoxystrobin (Fig 3)

There is a known cytochrome b G143A change in strain 37-16 compared to IPO323. Natural difference between two field isolates.



![image](https://github.com/PHI-base/curation/assets/11753634/b3cc047f-980e-453e-9648-fc004a5ad17d)


In the expt the authors use directed evolution to create cob G37V in both strains IPO323 and 37-16. 

In both cases there is a shift from 'sensitive to fenpicoxamide' to 'resistant to fenpicoxamide'

If we did not know about the cytochrome b G143A change in strain 37-16 compared to IPO323 then we would only record the cob G37V information for each strain and report on the shifted phenotype of sensitive to resistant. 

It seems as if we are trying to compare the natural strains to each other and then also compare each natural strain against the cob G37V directed evolution change.

@MPiovesana, as you have read the paper in more detail, please could you confirm that my summary above is correct?

**Comment by CuzickA** [comment]
Also to note that below could be a good example to use in our FAQ to highlight that 'normal growth on blah' could be either 'sensitive to' or 'resistant to' (we do not curate the WT controls, only whether altered genotypes show normal growth or a shift in Sensitivity or resistance to a chemical).

![image](https://github.com/PHI-base/curation/assets/11753634/63096cb7-c6ce-460e-8225-3ebbfc3f283a)

**Comment by MPiovesana** [comment]
> As I understand it there are two natural isolates IPO323 (reference strain) which is normally sensitive to fenpicoxamide and sensitive to azoxystrobin (Fig 3) 37-16 (in the text below called strain StrR) which is normally sensitive to fenpicoxamide and resistant to azoxystrobin (Fig 3)
> 
> There is a known cytochrome b G143A change in strain 37-16 compared to IPO323. Natural difference between two field isolates.
> 
> ![image](https://user-images.githubusercontent.com/11753634/244035186-b3cc047f-980e-453e-9648-fc004a5ad17d.png)
> 
> In the expt the authors use directed evolution to create cob G37V in both strains IPO323 and 37-16.
> 
> In both cases there is a shift from 'sensitive to fenpicoxamide' to 'resistant to fenpicoxamide'
> 
> If we did not know about the cytochrome b G143A change in strain 37-16 compared to IPO323 then we would only record the cob G37V information for each strain and report on the shifted phenotype of sensitive to resistant.
> 
> It seems as if we are trying to compare the natural strains to each other and then also compare each natural strain against the cob G37V directed evolution change.
> 
> @MPiovesana, as you have read the paper in more detail, please could you confirm that my summary above is correct?

@CuzickA Your summary of the strains used and experiments performed is correct.

**Comment by CuzickA** [comment]
New PHI-ECO and PHIPO terms now added.

I have also added AE alteration_in_archetype.

**Comment by CuzickA** [comment]
I'm still not quite sure of the best way to record 
'There is a known cytochrome b G143A change in strain 37-16 compared to IPO323. Natural difference between two field isolates.'
which has currently been added to the background. I have added a label to this GitHub ticket in case we have other similar examples.
@ValWood, do you think these look reasonable or should the natural strain variation be recorded in the comments (and therefore not visible on PHI-base 5)?

Here is a copy of the annotations

![image](https://github.com/PHI-base/curation/assets/11753634/7ba45e57-5838-403c-9ba0-b548e6dc6a9d)
![image](https://github.com/PHI-base/curation/assets/11753634/768e074b-d62f-487f-ad00-32dae408c43e)
![image](https://github.com/PHI-base/curation/assets/11753634/f4959b68-8bbe-48bc-8a98-2c0bcc57958c)

**Comment by ValWood** [comment]
Hi @CuzickA  I'm not quite sure about this without digging down into the paper since I don't fully understand the relationship between the strain./mutant in the experiment and what it is being compared to. I also don't remember what "alteration_in_archetype" refers to. is that new? I'm happy to go through this with you to see that it makes sense, but I'm completely  snowed this week. maybe we can have a quick call one morning next week?

**Comment by CuzickA** [comment]
This looks like an error (maybe whilst adding new term)
![image](https://github.com/PHI-base/curation/assets/11753634/85560ec2-b362-4b01-acfd-856c3e295144)

Should be 'resistant to..'
Now changed and reapproved
![image](https://github.com/PHI-base/curation/assets/11753634/7af56930-3b08-4364-923b-46e82f364a36)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

G37V; CytB; SEPTTR

Straight forward to find in Nichola's S file in Table S8
![image](https://github.com/PHI-base/curation/assets/11753634/e5d8d9c6-af01-4c23-a703-5aee7c72f350)

![image](https://github.com/PHI-base/curation/assets/11753634/6963a935-c763-45ee-ba21-2ed0ca06ad94)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
