### ISSUE TITLE
PMID: 31860693 A dispensable paralog of succinate dehydrogenase subunit C mediates standing resistance towards a subclass of SDHI fungicides in Zymoseptoria tritici

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#124]
This publication will be curated by our new biocurator @jingluodatacurator.

**Comment by CuzickA** [comment]
Tagging @jingluodatacurator

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I have struggled with this curation session. Please review it and let me know some feedback thanks.

Curation session link: https://canto.phi-base.org/curs/9b40357b9831eb84

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, before I start checking this older curation session, please could you

1) email me your highlighted PDF
2) add a short summary of the expt to this GitHub, including how you found the UniProt ids etc
3) double check the annotations with your new additional curation knowledge and personal curation checklist
4) Please let me know when you've done the above and then I'll check the session. Thanks

**Comment by jingluodatacurator** [comment]
Uniprot ID: A0A4D6Z3P9 ('Zymoseptoria tritici AND altSDHC' were used to search in UniprotKB to locate the ID)

Strains:
IPO323 and IPO94269 were reference field strains.

(Crosses between Z. tritici isolates sensitive (S: IPO323, IPO94269) and resistant (R: 06STD024, 07STGB009) to fluopyram were generated. Mapping populations of 234 and 95 progeny were obtained for crosses IPO323 x 06STD024 and IPO94269 x 07STGB009 respectively.)

IPO323_Flu21: UV mutant of IPO323 carrying the SDHC_A84I mutation;
D024 SDHC1 KO and D024 SDHC3 KO: deletion mutants of either the coreZtSDHC1 (SDHC) or of the alternative-ZtSDHC3 (alt-SDHC) gene in 06STD024 background;

**Comment by jingluodatacurator** [comment]
Summery of expt.:

(Mapping of a genetic factor responsible for fluopyram resistance in 06STD024 and 07STGB009 Z. tritici isolates)
Crosses between Z. tritici isolates sensitive (S: IPO323, IPO94269) and resistant (R: 06STD024, 07STGB009) to fluopyram were generated. Mapping populations of 234 and 95 progeny were obtained for crosses IPO323 x 06STD024 and IPO94269 x 07STGB009 respectively.

_(AC: Comment (24_04_2024): We are not curating the information on crossing or genetic mapping. This is background information from the authors. For curation we are interested in the resulting identified genes)_


(Enzymatic tests reveal distinct sensitivity profiles for SDHC and alt-SDHC SQRs)
Succinate-ubiquinone oxidoreductase (SQR) inhibition assays were performed on mitochondrial extracts from a panel of strains that were (i) either carrying a unique C-subunit encoding gene (ZtSDHC1, ZtSDHC1_A84I or Zt-SDHC3), or (ii) carrying two C-subunit encoding genes ZtSDHC1 and ZtSDHC3 (Table 1).

_(AC: Comment (24_04_2024): I think that it is more appropriate to curate Figure 4 A and B instead of Table 1)_

There may be more to add please advise @CuzickA thanks.

**Comment by jingluodatacurator** [comment]
Genotype creation:

UV mutant of IPO323 carrying the SDHC_A84I mutation, deletion mutants D024 SDHC1 KO and D024 SDHC3 KO have been curated for Fluopyram (sensitive). Please check info added for each genotype are correct @CuzickA thanks.

**Comment by CuzickA** [comment]
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/7bc48e88-7e56-478e-b51f-7e701c558edd)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/debdcdea-b559-4cb5-8116-d07a2d456ffc)
![image](https://github.com/PHI-base/curation/assets/11753634/ac37a419-8b9a-442f-8f45-a406b61b5b14)

![image](https://github.com/PHI-base/curation/assets/11753634/58151f38-e6f5-49df-bcd4-51d6317a1e02)

**Comment by CuzickA** [comment]
From the above text it seems we should be curating the following information from Figure 4A and B

06STD024 is a resistance strain (field isolate)
Deletion of SDHC1 (SDHC) in strain 06STD024 results in phenotype shift from resistant to slightly increased resistance = resistance to fluopyram AE severity: low
Deletion of SDHC3 (alt-SDHC) in strain 06STD024 results in phenotype shift from resistant to sensitive to fluopyram

@jingluodatacurator, what do you think?

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/55af4764-7439-483f-87c4-a240762d74b3)

**Comment by jingluodatacurator** [comment]
> From the above text it seems we should be curating the following information from Figure 4A and B
> 
> 06STD024 is a resistance strain (field isolate) Deletion of SDHC1 in strain 06STD024 results in phenotype shift from resistant to slightly increased resistance = resistance to fluopyram AE severity: low Deletion of SDHC3 in strain 06STD024 results in phenotype shift from resistant to sensitive to fluopyram
> 
> @jingluodatacurator, what do you think?

Yes @CuzickA, I agree thanks.

**Comment by CuzickA** [comment]
IPO323 is a Fluopyram sensitive strain.
Flu21 is an IPO323 strain with a UV mutation in SDHC A84I which results in a phenotype shift from sensitive to resistance to fluopyram (Fig4 A and B above). This can be curated.

The authors then transform IPO323 strain with alt-SDHC_I78A from strain 06STD024. I'm not sure that this can be curated as there will be different UniProts here.

Will need to check which UniProts @jingluodatacurator uses when she curates the 2 deletion mutants above.

**Comment by CuzickA** [comment]
How many UniProt Ids do we need?

A0A4D6Z3P9 seems fine for alt-SDHC (not found in reference strain IPO323)

Do we use the same UniProt id for SDHC from strain IPO323 and 06STD024?

Please could you look into this when you add in the new annotations @jingluodatacurator?

**Comment by jingluodatacurator** [comment]
> How many UniProt Ids do we need?
> 
> A0A4D6Z3P9 seems fine for alt-SDHC (not found in reference strain IPO323)
> 
> Do we use the same UniProt id for SDHC from strain IPO323 and 06STD024?
> 
> Please could you look into this when you add in the new annotations @jingluodatacurator?

Hi @CuzickA, this is partly why I was confused trying to understand the paper. I will take another look into it thanks.

**Comment by CuzickA** [comment]
> > How many UniProt Ids do we need?
> > A0A4D6Z3P9 seems fine for alt-SDHC (not found in reference strain IPO323)
> > Do we use the same UniProt id for SDHC from strain IPO323 and 06STD024?
> > Please could you look into this when you add in the new annotations @jingluodatacurator?
> 
> Hi @CuzickA, this is partly why I was confused trying to understand the paper. I will take another look into it thanks.

Hi @jingluodatacurator In case it helps the standard UniProt id we have used in other sessions for Zt SDHC/3 is F9XH52 which is also mentioned in this Figure legend
![image](https://github.com/PHI-base/curation/assets/11753634/ed0be3e0-dd5a-4ae7-a918-f54301d6f974)

**Comment by jingluodatacurator** [comment]
> From the above text it seems we should be curating the following information from Figure 4A and B
> 
> 06STD024 is a resistance strain (field isolate) Deletion of SDHC1 (SDHC) in strain 06STD024 results in phenotype shift from resistant to slightly increased resistance = resistance to fluopyram AE severity: low Deletion of SDHC3 (alt-SDHC) in strain 06STD024 results in phenotype shift from resistant to sensitive to fluopyram
> 
> @jingluodatacurator, what do you think?

Hi @CuzickA, I think I have finally managed to understand what you pointed out to me above and have added the annotations to the curation session, please check thanks.

<img width="776" alt="image" src="https://github.com/PHI-base/curation/assets/134380010/246be6ef-1919-4eac-acbf-cbf925c7fc6a">

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, thanks for having another go at this one.

In the conditions
![image](https://github.com/PHI-base/curation/assets/11753634/dc7efbe4-d84b-4f57-8545-0b6ac4d05d28)

I don't think the 18 dpi is correct as this seems to be related to Fig 6. Maybe it should be 6 dpi. Please could you double check?
![image](https://github.com/PHI-base/curation/assets/11753634/8a87f4bc-6f58-4be3-a0a1-9d34b7496d60)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, there also seems to be an issue here, as the same UniProt id has been used for two genes.

Please could you have another look at this?

![image](https://github.com/PHI-base/curation/assets/11753634/deef86e8-e995-4e7f-b60f-23d6de2d3f93)

**Comment by CuzickA** [comment]
**Next steps for AC**
1) add new strain _DONE_added strain 14_05_2024_ 37f8f8a
2) try and add AE alteration in archetype_DONE
3) check AE with Nichola

**Comment by CuzickA** [comment]
**AE alteration in archetype**
Zymoseptoria tritici
SDH3(aaA84I)[Not assayed] 'S73I; Sdh3 (SdhC); PYRNTE'

![image](https://github.com/PHI-base/curation/assets/11753634/64b840da-8228-4e8a-88c8-114636db27bb)

![image](https://github.com/PHI-base/curation/assets/11753634/fe43dea8-907e-4fb9-9516-a2fb7997826f)

![image](https://github.com/PHI-base/curation/assets/11753634/6b42dc1a-7e66-453f-be01-4ae661fda176)

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, thanks for having another go at this one.
> 
> In the conditions ![image](https://private-user-images.githubusercontent.com/11753634/329986596-dc7efbe4-d84b-4f57-8545-0b6ac4d05d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDM2NjMsIm5iZiI6MTcxNTY0MzM2MywicGF0aCI6Ii8xMTc1MzYzNC8zMjk5ODY1OTYtZGM3ZWZiZTQtZDg0Yi00ZjU3LTg1NDUtMGI2YWM0ZDA1ZDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIzMzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ODRjY2VhNmIwMDMzZTdlZTJlMGMzODVhYjI4NmVlNmFiYmY3NDg4YzQ3NWMxYmViYjk0YjVlOTdhMTE0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ss2IloIGVK-m9X-0rQublbd-3fd9O7x4PL02K6qO9ew)
> 
> I don't think the 18 dpi is correct as this seems to be related to Fig 6. Maybe it should be 6 dpi. Please could you double check? ![image](https://private-user-images.githubusercontent.com/11753634/329986888-8a87f4bc-6f58-4be3-a0a1-9d34b7496d60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDM2NjMsIm5iZiI6MTcxNTY0MzM2MywicGF0aCI6Ii8xMTc1MzYzNC8zMjk5ODY4ODgtOGE4N2Y0YmMtNmY1OC00YmUzLWEwYTEtOWQzNGI3NDk2ZDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIzMzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzVmOThjMTAxMTFkMTVkYWE2NzQ2YjlmZWVlNTA3Njg5YTZmOTNiOGUwYzlkYTJlZjk1NzBkYjhmZDYxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xaq2C3tCQf8uZBN4eKXYnoR4qN2nmCzs_DWkagts6Gs)

Hi @CuzickA, conditions have been corrected thanks.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I spoke with Nichola Hawkins this morning and asked her about the UniProt ids for these genes.

She confirmed that the same UniProt id should be used for IPO323 SDHC as the core SDHC gene in the strain 06STD024.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, I spoke with Nichola Hawkins this morning and asked her about the UniProt ids for these genes.
> 
> She confirmed that the same UniProt id should be used for IPO323 SDHC as the core SDHC gene in the strain 06STD024.

Hi @CuzickA, thank you for the info. I have made some changes so it looks like this..
<img width="737" alt="image" src="https://github.com/PHI-base/curation/assets/134380010/a7b534f3-d70f-4c36-aee8-69782249cca9">
Please check and let me know what you think, as I have been going back and forward and got a little confused myself.

**Comment by CuzickA** [comment]
My notes from above 

> 06STD024 is a resistance strain (field isolate)
Deletion of SDHC1 (SDHC) in strain 06STD024 results in phenotype shift from resistant to slightly increased resistance = resistance to fluopyram AE severity: low
Deletion of SDHC3 (alt-SDHC) in strain 06STD024 results in phenotype shift from resistant to sensitive to fluopyram

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, thanks for making the edits. The UniProt ids look correct now.

I am going to make some changes to tidy up the genotype names and add in AE low severity.
Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/ba07ad5a-c937-4a36-b228-9832302739ed)

**Comment by CuzickA** [comment]
Just need to check AE with Nichola and then session will be ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
