### ISSUE TITLE
PMID: 26092798 A gene locus for targeted ectopic gene integration in Zymoseptoria tritici

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#126]
https://canto.phi-base.org/curs/e40c988f4b5a00fb

**Comment by MPiovesana** [comment]
Carboxin resistance conferred by the single point mutation (H267L) in sdhb gene of Z. tritici is used as a selection marker in this paper. No problems annotating mutation and chemical resistance phenotype.

**Comment by MPiovesana** [comment]
Q1: Uniprot ID O42772 was used; I checked and the protein sequence and length match the ones shown in the paper, however, the protein is not named sdhb/sd1/Ip on Uniprot, but SDH2. This is a curated entry on Uniprot. I believe this is just a nomenclature issue, as the paper describing the carboxin resistance phenotype caused by the point mutation in sdhb is referenced under the "Publications" section in Uniprot.

**Comment by MPiovesana** [comment]
Q2: I was tempted to annotate the pathogen-host interaction assay described by the authors, but I realised that the strains used for this experiment are not the ones generated in this study, but strains obtained from other groups (papers referenced in text). So I only added the chemical resistance annotation. Would it be worth checking the other papers for potential curation?

**Comment by MPiovesana** [comment]
GO annotation for SDH2: I would like to annotate the GO Molecular Function term associated with the SDH2 gene, however, as the function is inferred based on similarity according to Uniprot, I faced the same issue as encountered during a demo curation that no evidence code was suitable for annotation. Code TAS is not available in drop down list.

AC: See below

**Comment by MPiovesana** [comment]
Q3: Experimental conditions; I annotated the conditions used by authors to confirm the carboxin resistance of individual colonies first obtained on Czapek Dox agar plates supplemented with carboxin. These colonies were then transferred to YPD agar plates with timentin, cefotaxime, and carboxin, and cultured for 3-4 days at 18 degrees. This is the set of conditions that I entered under experimental conditions (agar plates, rich medium, low temperature, + carboxin, +cefotaxime). Timentin was not available as exp condition; so added manually.

AC: see below

**Comment by MPiovesana** [comment]
Q4: Figure; as the carboxin resistance is used in this paper as a selection marker only, there is no Figure / Table associated with the phenotype (as remarked by @CuzickA in her notes on the Google doc file). Therefore, I referenced the article text in Materials and Methods and Results where the carboxin resistance conferred by the point mutation is mentioned.

**Comment by MPiovesana** [comment]
Exp condition "4 dpi" used here to indicate that pathogen was inoculated to media and allowed to grow for 4 days; similar reasoning as used for @CuzickA in the curation of PMID 22045588 (issue #120).

**Comment by MPiovesana** [comment]
@CuzickA Additional question: as I screened potential papers for curation, it occurred to me that it would be good if we could include in the genotype annotation whether a transgene is inserted by homologous recombination (eg gene replacement strategy) or using a different approach which leads to insertion in a random, unknown genome locus. I say this so that the presence or absence of the original wt copy of the gene is clear to the database user. At the moment, I have included this information in the Comments section; however, should we include this as background? For example, we could annotate the genotype as Z. tritici (IPO323) (background delta-sdhb) sdhb(aa267L), to indicate the deletion of the endogenous copy of sdhb and the introduction of the mutant allele (if not deletion, perhaps we can come up with a way to annotate the gene replacement). Otherwise, I am afraid that users might confuse this genotype annotation with the generation of a transgenic line which harbours both the mutant and the wt alleles of the gene.

**Comment by CuzickA** [comment]
> @CuzickA Additional question: as I screened potential papers for curation, it occurred to me that it would be good if we could include in the genotype annotation whether a transgene is inserted by homologous recombination (eg gene replacement strategy) or using a different approach which leads to insertion in a random, unknown genome locus. I say this so that the presence or absence of the original wt copy of the gene is clear to the database user. At the moment, I have included this information in the Comments section; however, should we include this as background? For example, we could annotate the genotype as Z. tritici (IPO323) (background delta-sdhb) sdhb(aa267L), to indicate the deletion of the endogenous copy of sdhb and the introduction of the mutant allele (if not deletion, perhaps we can come up with a way to annotate the gene replacement). Otherwise, I am afraid that users might confuse this genotype annotation with the generation of a transgenic line which harbours both the mutant and the wt alleles of the gene.

Yes, this can be tricky and hopefully the summary of typical chemistry expts will help make this clearer and maybe a FAQ to provide some screenshots.

I don't think we want to do this

> should we include this as background? For example, we could annotate the genotype as Z. tritici (IPO323) (background delta-sdhb) sdhb(aa267L), to indicate the deletion of the endogenous copy of sdhb and the introduction of the mutant allele 

In this case I think I would add GFP as background. 
For the purpose of the phenotype annotations I don't think the exact method of pathogen gene alteration needs to be recorded, what we are really aiming for in the genotype is recording the change that took place in the pathogen gene rather than the method of this alteration.

In cases where the endogenous gene is still present (or naturally absent) and a gene from another strain is added via an integrative plasmid we can use 'transformant' and add the endogenous gene info to the genotype name.

**Comment by MPiovesana** [comment]
@CuzickA Thank you very much for your comments and for clarifying this. It would be good to add this to FAQ as you mentioned.

**Comment by CuzickA** [comment]
I think we only need the 

> Q3: Experimental conditions; I annotated the conditions used by authors to confirm the carboxin resistance of individual colonies first obtained on Czapek Dox agar plates supplemented with carboxin. These colonies were then transferred to YPD agar plates with timentin, cefotaxime, and carboxin, and cultured for 3-4 days at 18 degrees. This is the set of conditions that I entered under experimental conditions (agar plates, rich medium, low temperature, + carboxin, +cefotaxime). Timentin was not available as exp condition; so added manually.

I think we only need +carboxin in the conditions here
![image](https://github.com/PHI-base/curation/assets/11753634/49fd46c4-6882-4792-b727-c43bfdc42b42)

![image](https://github.com/PHI-base/curation/assets/11753634/655430a4-42ee-4fd6-9947-0e5837768fe2)


![image](https://github.com/PHI-base/curation/assets/11753634/46d5ad16-32d7-41a0-befe-621fa5187e1f)

**Comment by CuzickA** [comment]
> GO annotation for SDH2: I would like to annotate the GO Molecular Function term associated with the SDH2 gene, however, as the function is inferred based on similarity according to Uniprot, I faced the same issue as encountered during a demo curation that no evidence code was suitable for annotation. Code TAS is not available in drop down list.

Which GO term were you planning on adding? I can add it for you with TAS via the Admin option

**Comment by MPiovesana** [comment]
> > GO annotation for SDH2: I would like to annotate the GO Molecular Function term associated with the SDH2 gene, however, as the function is inferred based on similarity according to Uniprot, I faced the same issue as encountered during a demo curation that no evidence code was suitable for annotation. Code TAS is not available in drop down list.
> 
> Which GO term were you planning on adding? I can add it for you with TAS via the Admin option

**Molecular Function:** succinate dehydrogenase (ubiquinone) activity

**Comment by MPiovesana** [comment]
> I think we only need the
> 
> > Q3: Experimental conditions; I annotated the conditions used by authors to confirm the carboxin resistance of individual colonies first obtained on Czapek Dox agar plates supplemented with carboxin. These colonies were then transferred to YPD agar plates with timentin, cefotaxime, and carboxin, and cultured for 3-4 days at 18 degrees. This is the set of conditions that I entered under experimental conditions (agar plates, rich medium, low temperature, + carboxin, +cefotaxime). Timentin was not available as exp condition; so added manually.
> 
> I think we only need +carboxin in the conditions here ![image](https://user-images.githubusercontent.com/11753634/246448354-49fd46c4-6882-4792-b727-c43bfdc42b42.png)
> 
> ![image](https://user-images.githubusercontent.com/11753634/246448634-655430a4-42ee-4fd6-9947-0e5837768fe2.png)
> 
> ![image](https://user-images.githubusercontent.com/11753634/246449325-46d5ad16-32d7-41a0-befe-621fa5187e1f.png)

That's great, I can edit the expt conditions to only include +carboxin. Would you recommend that I usually keep them as concise as possible? I have been trying to add information regarding medium, temperature, days post inoculation etc in the papers I have been curating. However, I'd be happy to edit and keep minimal info only if preferred.

**Comment by CuzickA** [comment]
> Q2: I was tempted to annotate the pathogen-host interaction assay described by the authors, but I realised that the strains used for this experiment are not the ones generated in this study, but strains obtained from other groups (papers referenced in text). So I only added the chemical resistance annotation. Would it be worth checking the other papers for potential curation?

I agree this doesn't look straight forward. The authors say 'carboxin resistant strains' but don't clearly say whether this resistance is due to the sdhb aaH267L or something else.

**Comment by CuzickA** [comment]
Session now approved, closing ticket.

**Comment by CuzickA** [comment]
Oh just remembered we may want to add a GO term.

**Comment by MPiovesana** [comment]
> Oh just remembered we may want to add a GO term.

@CuzickA the GO term to be added would be **Molecular Function**: succinate dehydrogenase (ubiquinone) activity

**Comment by CuzickA** [comment]
> > Oh just remembered we may want to add a GO term.
> 
> @CuzickA the GO term to be added would be **Molecular Function**: succinate dehydrogenase (ubiquinone) activity

Just added thanks

**Comment by CuzickA** [comment]
Session now approved. Closing ticket.

**Comment by CuzickA** [comment]
I think I need to add AE_alteration in archetype to this session

**Comment by CuzickA** [comment]
Added AE_alteration in archetype
![image](https://github.com/PHI-base/curation/assets/11753634/78348032-7d24-4c55-b11a-f088b210207f)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

H277L; SdhB; PYRNTE

Nichola's S file in Table S4
![image](https://github.com/PHI-base/curation/assets/11753634/3f9795c4-3493-4783-96b2-e7667bbfc625)

![image](https://github.com/PHI-base/curation/assets/11753634/e87fd258-0e82-40e3-be5b-daa280a1d69f)

Mair et al 2016 I don't see H277L in SEPTTR (Zt) listed here?
![image](https://github.com/PHI-base/curation/assets/11753634/30b7e9a5-a5a2-4c2e-ae6d-c11070ce435c)

From our FAQ file on how to use this AE
![image](https://github.com/PHI-base/curation/assets/11753634/c1eded77-3e64-4537-8a16-871d20655aec)


**Question to follow up with Nichola**
Is this entry correct? H277L; SdhB; PYRNTE
As I understand it, Nichola' S file Table S4 indicates that Zt is the archetype species but the Mair et al Table 5 indicates it is Pyrenophora teres f. sp. teres.

**Comment by CuzickA** [comment]
H277L; SdhB; PYRNTE this is correct
Error in STable 4 species heading should not be Zt it should be Pyrenophora teres.

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
