### ISSUE TITLE
PMID: 16723566 Assessing resistance to the echinocandin antifungal drug caspofungin in Candida albicans by profiling mutations in FKS1

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#127]
https://canto.phi-base.org/curs/44d53be865d82f20

**Comment by MPiovesana** [comment]
Uniprot ID: The authors say in M&M that they used two sequences to design the primers and molecular beacon probes used in the study; "Two DNA sequences reported for FKS1 were used for design of FKS1 molecular beacons and primers: GenBank
accession number AF027295 and Candida albicans genome database (http://genolist.pasteur.fr/CandidaDB/) accession number CA2043". When I searched Uniprot using the GenBank accession number, the search returns entry O13383; however, when checking the protein sequence associated with this entry, only a fragment of the FKS1 protein is reported (690 aa). When searching the Candida albicans genome database (link provided by authors does not work, I accessed it on candidagenome.org), I found the full lenght sequence of FKS1 (1897 aa). I then searched Uniprot again using the terms "FKS1 Candida albicans", and a number of entries were returned; the first of which (A0A1D8PCT0) corresponding to the full 1897 aa sequence and derived from the reference proteome of Candida albicans (strain SC5314 / ATCC MYA-2876) (Yeast) (SC5314 / ATCC MYA-2876). Other entries referring to a protein of the same length can also be found (see image below), and are connected to other reference proteomes. This first entry refers to strain SC5314, which is one of the strains used in this study. However, they also use strain M70, which does not seem to be tied to this reference proteome, nor the ones associated with the other entries, as far as I could see. I will go ahead and use ID A0A1D8PCT0 for now, just so that I can start the curation, but we can discuss and change this later as appropriate.

![image](https://github.com/PHI-base/curation/assets/134392805/404b44e8-90e9-40e7-be69-08749253a077)

**Comment by MPiovesana** [comment]
Strain M70: added manually as not available in Phi-CANTO.

**Comment by MPiovesana** [comment]
No problems encountered with the annotation of chemical resistance phenotypes; all genotypes were associated with resistance to caspofungin, micafungin, and anidulafungin. No Figure or Table display chemical resistance results, it is only described in the text (page 2060, paragraph "Isolation of spontaneous caspofungin-resistant C. albicans mutants"). Genotypes of isolates are found in Table 3.
_PS: see comment below regarding annotation of caspofungin-only phenotypes, as it is the focus of the paper; micafungin and anidulafungin annotations can be deleted if preferred._

**Comment by MPiovesana** [comment]
Homozygous and heterozygous isolates for the mutant alleles identified are reported to be resistant to caspofungin; I included this information in each respective Comments section. This way we can have one annotation per mutant genotype, rather than having to add two (one for heterozygous and one for homozygous genotype). However, would it be possible to annotate the homozygous/heterozygous status of the genotype otherwise?

**Comment by MPiovesana** [comment]
**Additional:** I curated all the chemical resistance annotations derived from this paper, including all isolates derived from both parental strains, and their respective resistance to all antifungals tested. However, the focus of the paper is on caspofungin, and we could limit annotations to this chemical if desired to limit the number of annotations.

AC: I've left the annotations in as they were already done.

**Comment by CuzickA** [comment]
> Strain M70: added manually as not available in Phi-CANTO.

Hi @jseager7, what's our protocol for adding a new strain? Should I request it on a tracker? I'm not sure if PHI-Canto will let me approve a session with a manually added strain. I'll try this soon.
![image](https://github.com/PHI-base/curation/assets/11753634/25585a6f-deab-402b-bbeb-2a5ae1950a8e)

**Comment by CuzickA** [comment]
> Uniprot ID: The authors say in M&M that they used two sequences to design the primers and molecular beacon probes used in the study; "Two DNA sequences reported for FKS1 were used for design of FKS1 molecular beacons and primers: GenBank accession number AF027295 and Candida albicans genome database (http://genolist.pasteur.fr/CandidaDB/) accession number CA2043". When I searched Uniprot using the GenBank accession number, the search returns entry O13383; however, when checking the protein sequence associated with this entry, only a fragment of the FKS1 protein is reported (690 aa). When searching the Candida albicans genome database (link provided by authors does not work, I accessed it on candidagenome.org), I found the full lenght sequence of FKS1 (1897 aa). I then searched Uniprot again using the terms "FKS1 Candida albicans", and a number of entries were returned; the first of which (A0A1D8PCT0) corresponding to the full 1897 aa sequence and derived from the reference proteome of Candida albicans (strain SC5314 / ATCC MYA-2876) (Yeast) (SC5314 / ATCC MYA-2876). Other entries referring to a protein of the same length can also be found (see image below), and are connected to other reference proteomes. This first entry refers to strain SC5314, which is one of the strains used in this study. However, they also use strain M70, which does not seem to be tied to this reference proteome, nor the ones associated with the other entries, as far as I could see. I will go ahead and use ID A0A1D8PCT0 for now, just so that I can start the curation, but we can discuss and change this later as appropriate.
> 
> ![image](https://user-images.githubusercontent.com/134392805/242565727-404b44e8-90e9-40e7-be69-08749253a077.png)

This seems like a logical UniProt id to use. I have noted (and linked to ticket) that a different UniProt id was used in a related paper where curation has been paused for now.

**Comment by CuzickA** [comment]
> > Strain M70: added manually as not available in Phi-CANTO.
> 
> Hi @jseager7, what's our protocol for adding a new strain? Should I request it on a tracker? I'm not sure if PHI-Canto will let me approve a session with a manually added strain. I'll try this soon. ![image](https://user-images.githubusercontent.com/11753634/247505689-25585a6f-deab-402b-bbeb-2a5ae1950a8e.png)

I was able to approve the session with a manually added strain.

**Comment by CuzickA** [comment]
> Homozygous and heterozygous isolates for the mutant alleles identified are reported to be resistant to caspofungin; I included this information in each respective Comments section. This way we can have one annotation per mutant genotype, rather than having to add two (one for heterozygous and one for homozygous genotype). However, would it be possible to annotate the homozygous/heterozygous status of the genotype otherwise?

Thanks for noting this information in the comments. I think there was some discussion in the past about being able to create homozygous or heterozygous genotypes for diploid organisms. @ValWood do you know any more about this?

**Comment by jseager7** [comment]
> what's our protocol for adding a new strain? Should I request it on a tracker?

Strain requests should be done on a tracker, but – since there are now strain lists on both [PHI-base/data](https://github.com/PHI-base/data/tree/master/strains) repository and the (private) PHI-base/config repository – I'm not sure where we should make strain requests in future.

I think [the PHI-base/data tracker](https://github.com/PHI-base/data/issues) will probably be the better option for now, since it's a public repository (meaning community curators can make strain requests if needed), and also because the versions of the strain lists there include additional information (like database cross-references), so it makes more sense to derive the PHI-Canto strain lists from the strain lists on PHI-base/data.

**Comment by ValWood** [comment]
> Thanks for noting this information in the comments. I think there was some discussion in the past about being able to create homozygous or heterozygous genotypes for diploid organisms. @ValWood do you know any more about this?

Yes, you should be able to do this in genotype management if it is enabled.

**Comment by CuzickA** [comment]
> > Uniprot ID: The authors say in M&M that they used two sequences to design the primers and molecular beacon probes used in the study; "Two DNA sequences reported for FKS1 were used for design of FKS1 molecular beacons and primers: GenBank accession number AF027295 and Candida albicans genome database (http://genolist.pasteur.fr/CandidaDB/) accession number CA2043". When I searched Uniprot using the GenBank accession number, the search returns entry O13383; however, when checking the protein sequence associated with this entry, only a fragment of the FKS1 protein is reported (690 aa). When searching the Candida albicans genome database (link provided by authors does not work, I accessed it on candidagenome.org), I found the full lenght sequence of FKS1 (1897 aa). I then searched Uniprot again using the terms "FKS1 Candida albicans", and a number of entries were returned; the first of which (A0A1D8PCT0) corresponding to the full 1897 aa sequence and derived from the reference proteome of Candida albicans (strain SC5314 / ATCC MYA-2876) (Yeast) (SC5314 / ATCC MYA-2876). Other entries referring to a protein of the same length can also be found (see image below), and are connected to other reference proteomes. This first entry refers to strain SC5314, which is one of the strains used in this study. However, they also use strain M70, which does not seem to be tied to this reference proteome, nor the ones associated with the other entries, as far as I could see. I will go ahead and use ID A0A1D8PCT0 for now, just so that I can start the curation, but we can discuss and change this later as appropriate.
> > ![image](https://user-images.githubusercontent.com/134392805/242565727-404b44e8-90e9-40e7-be69-08749253a077.png)
> 
> This seems like a logical UniProt id to use. I have noted (and linked to ticket) that a different UniProt id was used in a related paper where curation has been paused for now.

Regarding the UniProt ID, I was just checking https://github.com/PHI-base/curation/issues/141
and in the publication the authors (some of the same in both publications) use 
![image](https://github.com/PHI-base/curation/assets/11753634/bf475cbb-42f4-4082-8b0f-b6a2fa8f1b60)

Searching UniProt for XM_716336 also gives [A0A1D8PCT0](https://www.uniprot.org/uniprotkb/A0A1D8PCT0/entry)
![image](https://github.com/PHI-base/curation/assets/11753634/faa57639-1208-48a6-b911-1614dbf6091d)

**Comment by CuzickA** [comment]
> > Thanks for noting this information in the comments. I think there was some discussion in the past about being able to create homozygous or heterozygous genotypes for diploid organisms. @ValWood do you know any more about this?
> 
> Yes, you should be able to do this in genotype management if it is enabled.

Thanks, I don't see this option in genotype management. @jseager7 do you know if it is enabled in PHI-Canto?

**Comment by CuzickA** [comment]
> Strain requests should be done on a tracker, but – since there are now strain lists on both [PHI-base/data](https://github.com/PHI-base/data/tree/master/strains) repository and the (private) PHI-base/config repository – I'm not sure where we should make strain requests in future.

> I think [the PHI-base/data tracker](https://github.com/PHI-base/data/issues) will probably be the better option for now, since it's a public repository (meaning community curators can make strain requests if needed), and also because the versions of the strain lists there include additional information (like database cross-references), so it makes more sense to derive the PHI-Canto strain lists from the strain lists on PHI-base/data.

Thanks @jseager7, I've added the ticket to the tracker https://github.com/PHI-base/data/issues/21

**Comment by jseager7** [comment]
> Thanks, I don't see this option in genotype management. @jseager7 do you know if it is enabled in PHI-Canto?

It's not enabled at the moment, but enabling it is a very simple change. Do you need it enabled for this session or future sessions?

**Comment by CuzickA** [comment]
> > Thanks, I don't see this option in genotype management. @jseager7 do you know if it is enabled in PHI-Canto?
> 
> It's not enabled at the moment, but enabling it is a very simple change. Do you need it enabled for this session or future sessions?

Yes please, it could be useful to have it enabled for this session and then @MPiovesana can try it out for us :-)

**Comment by CuzickA** [comment]
Hi @MPiovesana, I have reactivated this session so you can try out the 'diploid mode' once its been enabled.

@jseager7, please could you make a comment in this ticket once the 'diploid mode' has been enabled in PHI-Canto?

**Comment by jseager7** [comment]
@CuzickA @MPiovesana Diploid mode should be enabled on PHI-Canto now. To create a diploid locus, go to the Pathogen genotype management page, select the checkbox next to a single-locus genotype, then press the 'Create diploid locus' button.

![image](https://github.com/PHI-base/curation/assets/37659591/76180abb-bca1-4945-9ce5-f3f57822f2f1)

**Comment by MPiovesana** [comment]
> @CuzickA @MPiovesana Diploid mode should be enabled on PHI-Canto now. To create a diploid locus, go to the Pathogen genotype management page, select the checkbox next to a single-locus genotype, then press the 'Create diploid locus' button.
> 
> ![image](https://user-images.githubusercontent.com/37659591/250825863-76180abb-bca1-4945-9ce5-f3f57822f2f1.png)

@jseager7 Thank you very much for the update. I have now tested the "Create diploid locus" function with success. @CuzickA for those genotypes which only homozygous mutants were isolated by the authors (as indicated in the comment section of each genotype), I created homozygous diploid locus and transferred all genotype annotations. For those genotypes which both heterozygous and homozygous mutants were isolated, this would mean doubling the number of genotypes and annotations (as I could created homozygous and heterozygous alleles). Should I do so?

**Comment by CuzickA** [comment]
> For those genotypes which both heterozygous and homozygous mutants were isolated, this would mean doubling the number of genotypes and annotations (as I could created homozygous and heterozygous alleles). Should I do so?

@MPiovesana, I think we would also need these if we are using diploid mode. @ValWood, in this case would you curate both the heterozygous and homozygous mutants?

**Comment by ValWood** [comment]
Probably you want to. We don't need to very much- pombe has a largely haploid lifestyle it mates and then usually goes straight back to haploid  (although we do have examples,  mainly for studying meiotic genes pombe, or specific haploinsufficiency experiments)

**Comment by MPiovesana** [comment]
> > For those genotypes which both heterozygous and homozygous mutants were isolated, this would mean doubling the number of genotypes and annotations (as I could created homozygous and heterozygous alleles). Should I do so?
> 
> @MPiovesana, I think we would also need these if we are using diploid mode. @ValWood, in this case would you curate both the heterozygous and homozygous mutants?

@CuzickA That's great, I will go ahead and create these heterozygous and homozygous genotypes now.

**Comment by MPiovesana** [comment]
@CuzickA All heterozygous and homozygous genotypes have now been created and annotations have been accordingly transferred. I deleted the haploid genotypes and kept only the diploid genotypes in genotype management page for simplicity purposes. I believe the session should be ready to be approved soon.

**Comment by CuzickA** [comment]
Thanks @MPiovesana, session now approved.

I'm planning on opening a ticket on the curation tracker so that we can document when to use 'diploid mode' and also add this into our FAQ document.

**Comment by MPiovesana** [comment]
> Thanks @MPiovesana, session now approved.
> 
> I'm planning on opening a ticket on the curation tracker so that we can document when to use 'diploid mode' and also add this into our FAQ document.

@CuzickA I think that is a great idea. I think the diploid mode might cause some confusion with users as people might think it is always necessary to record whether genotypes are homozygous or heterozygous, but I think it makes more sense in specific situations, such as this paper, or when there is a clear difference between homozygous/heterozygous genotypes. We can add screenshot examples to the FAQ as well.

**Comment by CuzickA** [comment]
no archetype information found
