### ISSUE TITLE
PMID: 23226235 Discovery of a HapE mutation that causes azole resistance in Aspergillus fumigatus through whole genome sequencing and sexual crossing

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#128]

**Comment by MPiovesana** [comment]
In this paper, authors investigate the azole susceptibility of four clinical isolates, two of which are azole susceptible and two which are resistant. Following whole genome sequencing, several mutations are identified in the resistant isolates in comparison to the susceptible strains. By observing the co-segregation of these mutations with the azole resistant phenotype in the progeny of genetic crosses, authors identify a point mutation in the **_HapE_** gene as being responsible for the acquired resistance to azole.

The sequence of the _HapE_ gene is checked to ensure that a single point mutation is present, leading to the aa substitution **P88L**. Authors perform gene replacement experiments by inserting the mutant _HapE_ allele in the recipient strain **akuB ku80**, and confirm that this mutant allele is capable of inducing resistance to azole antifungals. Although the natural variation of the clinical isolates cannot be curated in PHI-Canto, the gene replacement experiments are suitable for curation.

**Comment by MPiovesana** [comment]
@CuzickA Question: does the above constitute a case of "inter-strain" complementation which, similarly to interspecies complementation, cannot be curated?

**Comment by MPiovesana** [comment]
> @CuzickA Question: does the above constitute a case of "inter-strain" complementation which, similarly to interspecies complementation, cannot be curated?

**MP:** Issue resolved following discussion; when an allele from a strain is introduced in another strain from the same species, genotypes can be curated as **transformant**. Information about the strain from which the mutant allele is derived can be recorded in the allele name, when possible. In the case of clinical isolates (such as in this study), where strains are unknown, the mutant allele can reflect the mutation harboured by the gene.

**Comment by MPiovesana** [comment]
**Uniprot ID:** By searching Uniprot for an _A. fumigatus_ reference proteome (UP000002530), a single entry for the _HapE_ protein is identified (**Q4WDM9**). 

**Strain:** _A. fumigatus_ strain **akuB ku80** was selected as it is used as the recipient strain for homologous gene replacement experiment.

**Comment by MPiovesana** [comment]
**Genotype creation**: following the recently discussed guidelines for naming transformant alleles, the following pathogen genotype was created to reflect the replacement of the endogenous _HapE_ gene with a mutant allele in **akuBKU80**:

**HapE transformant(Isolate3-HapE(P88L)** [Not assayed]: introduction of the _HapE_ allele _HapE(P88L)_ from clinical isolate 3  (no strain name provided other than Isolate 3).

The deletion of the endogenous copy of HapE during the gene replacement approach was recorded as HapEΔ in background.

**Comment by MPiovesana** [comment]
**Genotype annotation:** the pathogen genotype was annotated with the terms **resistance to itraconazole**, **resistance to voriconazole**, and **resistance to posaconazole** (as per results in Table 7).

**Comment by MPiovesana** [comment]
@CuzickA the curation of this paper has been revisited and now completed pending review (https://canto.phi-base.org/curs/7f9cae597c7ce0a5/feature/genotype/view/1). This paper can be used in FAQ and user help text as an example of when authors employ genetic crosses to establish a link between a mutant allele and the chemical resistance phenotype.

**Comment by MPiovesana** [comment]
Transformant name updated according to recent discussion (#157).

**Comment by CuzickA** [comment]
Session looks fine. AE alteration in archetype is N/A.

Approving session and closing ticket.
