### ISSUE TITLE
PMID: 12135574 An osmosensing histidine kinase mediates dicarboximide fungicide resistance in Botryotinia fuckeliana (Botrytis cinerea)

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#129]
https://canto.phi-base.org/curs/704f19f6849d102f

**Comment by MPiovesana** [comment]
@CuzickA This paper poses an interesting case for curation. The Materials and Methods and Results sections are not very thorough, and it required a lot of reading back and forth to identify which are the mutant strains generated in the laboratory (derived from B. fuckeliana wt strain A1) and how the mapping of Bos1/Daf1 is performed.

 In summary, authors induce **dicarboximide** resistance in _B. fuckeliana_ strain A1, and isolate 12 mutant lines (named M(xx), where x is a number; isolate names found in Table 3 but not mentioned anywhere in text). These new mutants are then crossed to a field isolate (REB658-1) which is known to be sensitive to both benzimidazole and dicarboximide (Table 3). The authors do not mention this anywhere in the paper, but they must also have tested the resistance of the M(xx) mutants to benzimidazole, as in Table 3 they state the phenotype of the parental lines to both benzimidazole and dicarboximide. These crosses are used to analyse the segregation of the dicarboximide resistance phenotype, and to map the mutation locus. 

Once the authors identify that the gene **Bos1** (synonym to **Daf1**) is the source of the chemical resistance phenotype, the gene is fully sequenced and point mutations are identified for three of the strains generated from the M(xx) x REB658-1 crosses (Table 6; REB890-18, REB896-15, REB900-17). Thus, I believe we can curate the genotype/phenotype of these lines as we know one of the parental strains are mutants derived from wt A1, and the other parental strain did not contribute to the resistance phenotype, as it was sensitive to dicarboximide. Does it make sense?

**Comment by MPiovesana** [comment]
**Question:** how best to annotate this? I am not sure we can annotate the genetic cross background as one of the parental strains was a field isolate, but could we add this as background information? Eg strain A1 (cross with REB658-1). Or, can we "ignore" the genetic cross information for the genotype annotation, given the REB658-1 parental genotype does not impact the chemical resistance? We could then annotate the genotype as aa substitution in strain A1, and add info about genetic cross in Comments. 

_**Update, 21st June**: After revisiting this paper, I believe we would be able to annotate the genotype of the parental, mutant strains (laboratory-generated) and their respective mutations, as the genetic crosses were only used to confirm that a single locus was responsible for the chemical resistance phenotype. In this case, the progeny of the genetic crosses are not the genotype of interest, just a tool to confirm the co-segregation of mutant allele and phenotype. Does it make sense?_

**Comment by MPiovesana** [comment]
Accession number provided in Table 2 (AF435964) used to locate Uniprot ID of Bos1 protein: Q8X215.

**Comment by MPiovesana** [comment]
Paper also provides phenotypical information about conidial production, radial growth, and osmosensitivity, which could also be annotated.

**Comment by MPiovesana** [comment]
@CuzickA As mentioned in ticket #144, this is the other paper where curation of _Bos1_ mutations was attempted. In light of my comments above, I have revisited this paper to decide whether we can curate it in PHI-Canto or not. Despite the genetic crosses performed by the authors being employed as a strategy to identify the mutant locus which co-segregates with the chemical resistance phenotype, the authors perform _Bos1_ sequence analysis on the progeny of the genetic crosses, rather than on the parental, laboratory-generated mutants which I thought we could potentially curate. We know the mutant alleles of _Bos1_ harboured by the progeny of the genetic crosses are derived from the spontaneous mutant parent, but as those were not sequenced themselves, I am not sure we can curate these genotypes. What are your thoughts?

**Comment by CuzickA** [comment]
It sound like this paper is uncuratable based on the comments above.
