### ISSUE TITLE
preventing authors from curating viruses in PHI-Canto?

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#13]
PHI-base does not curate viral pathogens. Are we going to continue to not curate viruses?
We may need some text to notify authors/journals not to curate these publications.
What do you think @martin2urban @kehammond ?

**Comment by KEHammond** [comment]
Dear Alayne,

We will not be curating viruses. There are other databases that do this. Also the mechanisms are  not generic with the other types of pathogens.

Best regards,
Kim

**Comment by CuzickA** [comment]
Thanks @KEHammond that is what I thought. We can continue to select MC curatable papers using the current literature search string (which does not include viruses) but we may need to notify the journals and any additional community curators that we will be not be curating viruses.

**Comment by CuzickA** [comment]
closing for now
