### ISSUE TITLE
PMID: 12604551 A point mutation in the 14alpha-sterol demethylase gene cyp51A contributes to itraconazole resistance in Aspergillus fumigatus

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#130]
https://canto.phi-base.org/curs/1ce053ff9b1dbeab

**Comment by MPiovesana** [comment]
**Uniprot ID:** one entry resulting from search for cyp51A and Aspergillus fumigatus. No issues.

**Comment by MPiovesana** [comment]
**Strain:** WT strain CM-237 is used as recipient for gene replacement and expression of mutant cyp51A allele in the study. I could locate a strain named "237" in PHI-Canto, but not CM-237. I tried searching online but I don't believe 237 and CM-237 are synonyms, so I added the strain name manually. Should we request it to be added to PHI-Canto list of A. fumigatus strains?

**Comment by MPiovesana** [comment]
**Experimental conditions:** added 2 days post-inoculation to indicate length of antifungal susceptibility tests. Same as discussed in other tickets - need for new experimental condition reflecting inoculation of fungus to medium, not host.

AC: https://github.com/PHI-base/phi-eco/issues/12

**Comment by MPiovesana** [comment]
The mutant lines which display resistance to itraconazole also show increased susceptibility to fluconazole (FCZ) and ketoconazole (KTZ) (Table1; fourfold reduction in MIC compared to WT CM-237 strain); however, this is not described by the authors as sensitivity to FCZ and KTZ, but simply as increased susceptibility, given that the WT strain itself might be considered sensitive if compared to other isolates. Therefore, I have suggested **new terms**, which I believe might be useful if applied to other chemicals as well. Rather than only having "resistant to x" and "sensitive to x", I think it can be useful to add terms such as **"increased resistance to x"** and **"increased susceptibility to x"**.

**Comment by MPiovesana** [comment]
Needs adding GO term annotations.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
> Needs adding GO term annotations.

@MPiovesana Did you have a GO term in mind? Is this another case of needing it entered in Admin mode with evidence code of TAS?

**Comment by MPiovesana** [comment]
> > Needs adding GO term annotations.
> 
> @MPiovesana Did you have a GO term in mind? Is this another case of needing it entered in Admin mode with evidence code of TAS?

@CuzickA Actually, I am not sure whether it is necessary to add the GO annotations here. This is a protein that is cited in several papers, and perhaps it is not necessary to annotate its GO terms in every curation session. When looking on Uniprot, the function of this protein has been described by several publications, but I was unsure whether I should check them individually to identify the experiments performed to assign these functions. When would you recommend is best to add GO annotations, and when is it not necessary?

**Comment by CuzickA** [comment]
> > > Needs adding GO term annotations.
> > 
> > 
> > @MPiovesana Did you have a GO term in mind? Is this another case of needing it entered in Admin mode with evidence code of TAS?
> 
> @CuzickA Actually, I am not sure whether it is necessary to add the GO annotations here. This is a protein that is cited in several papers, and perhaps it is not necessary to annotate its GO terms in every curation session. When looking on Uniprot, the function of this protein has been described by several publications, but I was unsure whether I should check them individually to identify the experiments performed to assign these functions. When would you recommend is best to add GO annotations, and when is it not necessary?

@MPiovesana, I agree it sounds like we don't need to add GO annotations here, especially if they have already been annotated in UniProt. I think we only really want to add GO annotations when expt in the publication show the normal function of the gene product and occasionally if there is a strong statement in the text made by the author (TAS). This is another topic for the FAQ :-)

**Comment by CuzickA** [comment]
Session approved. Closing ticket.

**Comment by CuzickA** [comment]
I think I need to add AE_alteration in archetype to this session.

**Comment by CuzickA** [comment]
I need to follow up with Nichola about selecting the correct AE_alteration in archetype here.

From Nichola's S file
![image](https://github.com/PHI-base/curation/assets/11753634/67b8d19b-2352-4cb2-b135-da45b22b086c)

I don't think it would make sense to use cyp51b from Zt as the annotation is for cyp51a from Af which is listed in FRAST.

In Mair et al 2016 publication
![image](https://github.com/PHI-base/curation/assets/11753634/a6429f73-13d8-463c-bcde-338ff962bb41)

I think the correct alteration in archetype is therefore
G54E; Cyp51A; ASPEFU


![image](https://github.com/PHI-base/curation/assets/11753634/73262648-27c9-4946-a317-4e0bfb73cd42)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

G54E; Cyp51A; ASPEFU

**Questions for Nichola**
1) is this correct 'G54E; Cyp51A; ASPEFU'. I could not find info on Cyp51A in your S file. I found the above information from Table 2 in Mair et al 2016.

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
