### ISSUE TITLE
PMID: 8641470 Site-directed mutagenesis of Saccharomyces cerevisiae beta-tubulin: Interaction between residue 167 and benzimidazole compounds.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#131]
https://canto.phi-base.org/curs/1fcb305c3abf40f4

**Comment by MPiovesana** [comment]
**Genotype annotation:** authors replace endogenous copy of beta-tubulin with mutant copy containing point mutation F167Y (TUB2 (aaF167Y)).

**Comment by MPiovesana** [comment]
**Phenotype annotation:** I have suggested the addition of new terms to best describe the phenotypes observed for mutant lines (increased sensitivity to benomyl and normal sensitivity to thiabendazole). As this seems to be a requirement for several papers, perhaps we can discuss how to annotate these phenotypes without the need to include new terms (eg use term "increased sensitivity to chemical", do not pick a child term, and specify which chemical in Comments section). 

**AC** We need the term 'normal growth on thiabendazole'
We would use 'sensitive to benomyl' which is a child of 'increased sensitivity to chemical' and means that the mutant line is more sensitive to the chemical then the WT line.

![image](https://github.com/PHI-base/curation/assets/11753634/09c495da-86cd-43db-bc32-120006ff4b45)

remove NTR and leave as 'Sensitive to benomyl'
![image](https://github.com/PHI-base/curation/assets/11753634/efa877c0-3df3-4fa4-a3c1-c9d5d9b25349)

**Comment by MPiovesana** [comment]
Similarly, the chemical **"nocodazole"** is present in Experimental conditions, but not as a phenotype term.

**Comment by MPiovesana** [comment]
**Cell growth phenotype annotation:** authors report that mutation leads to an increased cell division time (reduced rate of cell division) of S. cerevisiae, assessed by counting cells. I looked up several phenotype terms and could not identify one to use here. Phenotype still to be annotated.

AC I have added below annotation
![image](https://github.com/PHI-base/curation/assets/11753634/1c371a56-4800-4b12-81f8-10727c15826f)

**Comment by CuzickA** [comment]
Query on AE alteration in archetype to follow up with Nichola
Currently AE not added, can it be added here? What is the archetype?

Nichola's S file Tubulin table
![image](https://github.com/PHI-base/curation/assets/11753634/d53d7a5e-1021-4017-b99d-55e15eb1a753)

Mair et al 2016
![image](https://github.com/PHI-base/curation/assets/11753634/b0799578-5b83-479e-8a10-e670c434e456)

**Comment by CuzickA** [comment]
I have added AE alteration in archetype
F167Y; TUB2 (β-tubulin); ASPEND

**Comment by CuzickA** [comment]
New terms added. Session approved.
Keeping ticket open as still have a question about AE alteration in archetype to follow up with Nichola

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F167Y; TUB2 (β-tubulin); ASPEND

![image](https://github.com/PHI-base/curation/assets/11753634/db8eaaef-0c8c-4f09-b57a-48b3b5321c02)
EPPO code not listed in Mair table 4 above

**Questions for Nichola**
I'm not quite sure what to do with this one. Please check.

Nichola is happy with F167Y; TUB2 (β-tubulin); ASPEND

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
