### ISSUE TITLE
PMID: 15215099 Extra copies of the Aspergillus fumigatus squalene epoxidase gene confer resistance to terbinafine: genetic approach to studying gene dose-dependent resistance to antifungals in A. fumigatus

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#132]
https://canto.phi-base.org/curs/21fc6c377c5de85b

**Comment by MPiovesana** [comment]
No problem locating Uniprot ID (Q6QNB5; same as used in previous entries in PHI-base as entries are listed in Uniprot page). 

**AC:** see comment below. This Uniprot ID needs to be changed.

**Comment by MPiovesana** [comment]
In this paper, authors identify ERG1 as the gene responsible for inducing resistance to terbinafine (TRB) in A. fumigatus strains transformed with a multicopy non-integrating DNA library. The authors then validate this conclusion by introducing extra copies of ERG1 in strain AF293.1 and comparing its sensitivity to antifungals to the untransformed strain. 

Thus, the genotype to be annotated here is the presence of **extra copies of WT ERG1 gene in strain AF293.1 of A. fumigatus**. As we agreed to only use allele type 'transformant' when the transgene is derived from a different strain, I have selected the option "**other**" when annotating this genotype, as I could not find any other option that seemed suitable. I name the allele **ERG1ox** and added **AF293.1-ERG1** in allele description. As the transgene is inserted in random genomic loci, I selected **ectopic** as expression levels.

I also added the information that the AF293.1 strain has a pyrG- background, which is relevant for the selection of transformants.

**Comment by MPiovesana** [comment]
The main phenotype annotation refers to the increased resistance to TRB, which has been added. I have also annotated the normal growth displayed by the transformed strain on amphotericin B, itraconazole, and voriconazole. However, as the paper focuses on TRB, we can potentially delete these annotations if appropriate.

**Comment by MPiovesana** [comment]
> No problem locating Uniprot ID (Q6QNB5; same as used in previous entries in PHI-base as entries are listed in Uniprot page).

Upon curation of PMID 16801438 (ticket #137), I noticed that **ergA** and **erg1** are both names used to describe the same gene in A. fumigatus (squalene epoxidase). Despite the Uniprot ID mentioned above (Q6QNB5) having been used previously in other PHI-base curation sessions, I believe the ID used for the curation described in ticket #137 would be the best option going forward, as it is the curated entry for **erg1** (**E9R5G2**). 

The issue here was that authors reference GenBank accession number (AY532916) in the paper, which is linked to entry Q6QNB5; however, this entry refers to a protein sequence of 405 aa, which does not match the 481 aa sequence used for aa alignments as shown in Fig 2 of the paper. Curated entry E9R5G2, on the other hand, displays the full 481 aa sequence. Thus, I suggest updating Uniprot ID here to the curated entry E9R5G2 as used in ticket #137, and standardise the use of this ID for papers describing phenotypes associated with erg1/ergA of A. fumigatus.

**Comment by MPiovesana** [comment]
**UPDATE 14th July**: comments here edited to reflect changes in genotype creation (originally created transformant allele, which was changed after recent considerations about the use of this allele type).

**Comment by CuzickA** [comment]
> > No problem locating Uniprot ID (Q6QNB5; same as used in previous entries in PHI-base as entries are listed in Uniprot page).
> 
> Upon curation of PMID 16801438 (ticket #137), I noticed that **ergA** and **erg1** are both names used to describe the same gene in A. fumigatus (squalene epoxidase). Despite the Uniprot ID mentioned above (Q6QNB5) having been used previously in other PHI-base curation sessions, I believe the ID used for the curation described in ticket #137 would be the best option going forward, as it is the curated entry for **erg1** (**E9R5G2**).
> 
> The issue here was that authors reference GenBank accession number (AY532916) in the paper, which is linked to entry Q6QNB5; however, this entry refers to a protein sequence of 405 aa, which does not match the 481 aa sequence used for aa alignments as shown in Fig 2 of the paper. Curated entry E9R5G2, on the other hand, displays the full 481 aa sequence. Thus, I suggest updating Uniprot ID here to the curated entry E9R5G2 as used in ticket #137, and standardise the use of this ID for papers describing phenotypes associated with erg1/ergA of A. fumigatus.

**AC:** I agree that the uniprot id in this session needs to be updated to E9R5G2 which is a reviewed entry and found by searching for 'erg1 Aspergillus fumigatus' https://www.uniprot.org/uniprotkb/E9R5G2/entry

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/428161f1-0d27-4704-b6d9-755910869299)

This seems to be another example of when it would be nice to be able to use both 'ectopic' and 'overexpression'. However, we can only use one of these and I think that 'overexpression' is the most relevant. I have created a new label to flag this up.

I think the genotypes here need to change following similar expt in https://github.com/PHI-base/curation/issues/51

**Comment by CuzickA** [comment]
1) I have updated the UniProt ID
2) Created a new genotype

Next, once genotype editing bug resolved
3) I will move the annotations over to the new genotype (annotations look fine).

AE alteration in archetype is N/A to this session.

**Comment by CuzickA** [comment]
I have now moved the annotations over to the new genotype.

Just waiting for two new PHIPO terms to load into PHI-Canto to update the annotations. 
![image](https://github.com/PHI-base/curation/assets/11753634/145320e8-55dd-4f05-8a3e-28e4f61372ea)

**Comment by CuzickA** [comment]
PHIPO terms now added, session approved, closing ticket.
