### ISSUE TITLE
PMID:15345450 Implications of amino acid substitutions in GyrA at position 83 in terms of oxolinic acid resistance in field isolates of Burkholderia glumae, a causal agent of bacterial seedling rot and grain rot of rice

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#133]

**Comment by MPiovesana** [comment]
**Uniprot ID**: Using the gene name (GyrA) and the species name (Burkholderia glumae), a number of Uniprot IDs are suggested. Multiple entries seem to already be linked to PHI-base, all for the curation of the same paper (the same I am currently trying to curate). See example below for the first entry displayed in the Uniprot search results:

![image](https://github.com/PHI-base/curation/assets/134392805/86e95b18-13b2-4b88-b501-bf1e083f2350)


I am redirected to the page below when I click on the PHI-base link:


![image](https://github.com/PHI-base/curation/assets/134392805/b0f8141f-c60e-450a-9dbc-8a1bbe5d0694)

When I try the other Uniprot IDs, they also show a link to PHI-base under "Phenotypes and Variants", which are linked to the same annotations.  @CuzickA how is it possible that multiple entries are coming up as linked to the same curation? Can we identify which Uniprot ID was used by the curator at the time?

**Comment by MPiovesana** [comment]
**Avoiding duplication:** can PHI-Canto access the PMIDs of the papers which have already been curated in PHI-base? I ask this as I wasn't prompted by PHI-Canto that this would be a duplicated curation when starting the new session, and I wonder if this would be possible in order to allow duplicated curations.

**Comment by MPiovesana** [comment]
**Curation of this paper is paused until Uniprot ID and duplication issues resolved**

**Comment by CuzickA** [comment]
> **Avoiding duplication:** can PHI-Canto access the PMIDs of the papers which have already been curated in PHI-base? I ask this as I wasn't prompted by PHI-Canto that this would be a duplicated curation when starting the new session, and I wonder if this would be possible in order to allow duplicated curations.

PHI-Canto should prevent duplication of PMIDs that have been curated in PHI-Canto. 

Current entries in PHI-base 4 (online) have been curated using the Excel spreadsheet method. We are currently creating a pipeline to migrate the PHI-base 4 data (curated using Excel spreadsheet) onto our new gene-centric version PHI-base 5. Once this has been completed PHI-base 5 will contain the PHI-base 4 data and the newly curated PHI-Canto data.

In cases where a publication has been curated in both PHI-base 4 using the Excel spreadsheet method and using PHI-Canto then we plan to only display the PHI-Canto curated data in PHI-base 5.

**Comment by CuzickA** [comment]
> **Uniprot ID**: Using the gene name (GyrA) and the species name (Burkholderia glumae), a number of Uniprot IDs are suggested. Multiple entries seem to already be linked to PHI-base, all for the curation of the same paper (the same I am currently trying to curate). See example below for the first entry displayed in the Uniprot search results:
> 
> ![image](https://user-images.githubusercontent.com/134392805/244057870-86e95b18-13b2-4b88-b501-bf1e083f2350.png)
> 
> I am redirected to the page below when I click on the PHI-base link:
> 
> ![image](https://user-images.githubusercontent.com/134392805/244058145-b0f8141f-c60e-450a-9dbc-8a1bbe5d0694.png)
> 
> When I try the other Uniprot IDs, they also show a link to PHI-base under "Phenotypes and Variants", which are linked to the same annotations. @CuzickA how is it possible that multiple entries are coming up as linked to the same curation? Can we identify which Uniprot ID was used by the curator at the time?

Do you mean that in PHI-base 4 different UniProt ids have been used for GyrA curation from different publications? If so then this is a known problem we have with curators often selecting strain-specific UniProt id rather than the UniProt id from the species reference proteome. Please let me know if I have answered your question here or if I have misunderstood the issue?

**Comment by MPiovesana** [comment]
> > **Uniprot ID**: Using the gene name (GyrA) and the species name (Burkholderia glumae), a number of Uniprot IDs are suggested. Multiple entries seem to already be linked to PHI-base, all for the curation of the same paper (the same I am currently trying to curate). See example below for the first entry displayed in the Uniprot search results:
> > ![image](https://user-images.githubusercontent.com/134392805/244057870-86e95b18-13b2-4b88-b501-bf1e083f2350.png)
> > I am redirected to the page below when I click on the PHI-base link:
> > ![image](https://user-images.githubusercontent.com/134392805/244058145-b0f8141f-c60e-450a-9dbc-8a1bbe5d0694.png)
> > When I try the other Uniprot IDs, they also show a link to PHI-base under "Phenotypes and Variants", which are linked to the same annotations. @CuzickA how is it possible that multiple entries are coming up as linked to the same curation? Can we identify which Uniprot ID was used by the curator at the time?
> 
> Do you mean that in PHI-base 4 different UniProt ids have been used for GyrA curation from different publications? If so then this is a known problem we have with curators often selecting strain-specific UniProt id rather than the UniProt id from the species reference proteome. Please let me know if I have answered your question here or if I have misunderstood the issue?

@CuzickA All of the annotations refer to the same publication, and every time I open a different Uniprot ID, it takes me to the same PHI-base link, as if multiple IDs had been used to curate the same paper. Could the same paper have been curated more than once in PHI-base 4? Or alternatively, could more than one Uniprot ID be linked to the same curation session?

**Comment by CuzickA** [comment]
One reference proteome for Bg in strain BGR1

![image](https://github.com/PHI-base/curation/assets/11753634/41ae9c57-aaca-40d9-800a-f1ea02634273)

![image](https://github.com/PHI-base/curation/assets/11753634/e8072dd2-5be1-4523-b703-6b4cbebb34f3)

Suggest using UniProt C5ACM6

**Comment by CuzickA** [comment]
> > > **Uniprot ID**: Using the gene name (GyrA) and the species name (Burkholderia glumae), a number of Uniprot IDs are suggested. Multiple entries seem to already be linked to PHI-base, all for the curation of the same paper (the same I am currently trying to curate). See example below for the first entry displayed in the Uniprot search results:
> > > ![image](https://user-images.githubusercontent.com/134392805/244057870-86e95b18-13b2-4b88-b501-bf1e083f2350.png)
> > > I am redirected to the page below when I click on the PHI-base link:
> > > ![image](https://user-images.githubusercontent.com/134392805/244058145-b0f8141f-c60e-450a-9dbc-8a1bbe5d0694.png)
> > > When I try the other Uniprot IDs, they also show a link to PHI-base under "Phenotypes and Variants", which are linked to the same annotations. @CuzickA how is it possible that multiple entries are coming up as linked to the same curation? Can we identify which Uniprot ID was used by the curator at the time?
> > 
> > 
> > Do you mean that in PHI-base 4 different UniProt ids have been used for GyrA curation from different publications? If so then this is a known problem we have with curators often selecting strain-specific UniProt id rather than the UniProt id from the species reference proteome. Please let me know if I have answered your question here or if I have misunderstood the issue?
> 
> @CuzickA All of the annotations refer to the same publication, and every time I open a different Uniprot ID, it takes me to the same PHI-base link, as if multiple IDs had been used to curate the same paper. Could the same paper have been curated more than once in PHI-base 4? Or alternatively, could more than one Uniprot ID be linked to the same curation session?

> could more than one Uniprot ID be linked to the same curation session?

 Yes, I think that is what has happened here.

There may have been different strains used in the paper and the PHI-base 4 curater may have added a strain-specific UniProt for each strain whilst curating using the Excel curation method . In PHI-Canto, we select the UniProt ID from the UniProt designated reference proteome strain and add the strain detail for the genotype using the select strain option.

**Comment by MPiovesana** [comment]
@CuzickA Thank you very much for your comments. I will proceed with the curation of this paper using the Uniprot ID suggested by you above.

**Comment by MPiovesana** [comment]
**Genotype annotations**: the point mutations leading to the substitution of Ser83 with an Arg or Ile or introduced in the _gyrA_ of the wild type reference strain Pg-10. Authors further confirm the importance of this site for OA resistance by mutating strains Pg-7 and Pg-15, which are naturally resistant to this chemical, by replacing the Arg and Ile on position 83 with a Ser, to recreate the Pg-10 wild type allele. I believe these are all the genotypes we will be able to curate from this paper. OA susceptibility assay results are displayed in Table 5.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Link to curation session https://canto.phi-base.org/curs/f18b686e57ffe5a8

**Comment by CuzickA** [comment]
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/724c5553-4589-468b-b9ba-259989f27208)

**Comment by CuzickA** [comment]
This is another bacterial pathogen that has snuck in. I will continue to check the session for display in PHI-base5 but it will not be included in fungicide resistance manuscript.

**Comment by CuzickA** [comment]
Annotations look fine.
No need to add strains to the strain list.
No need for AE alteration in archetype as a bacterial pathogen target site.

Session approved.

Closing ticket.
