### ISSUE TITLE
Can we curate genetic crosses?

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#134]
Ticket dedicated to the discussion of the curation of genotypes derived from genetic crosses.

**Comment by MPiovesana** [comment]
In some papers, a known wt / reference strain is crossed to a clinical / environmental strain of unknown background to introduce natural variation into the wt background. In such cases, the progeny often displays an altered chemical resistance phenotype associated with a point mutation derived from the natural isolate. Can such genotypes be curated in PHI-Canto?

**Comment by MPiovesana** [comment]
A case example is found in ticket #129 .

**Comment by CuzickA** [comment]
Closing ticket as no further discussion for now.
