### ISSUE TITLE
PMID: 12543662 Mutations in Aspergillus fumigatus resulting in reduced susceptibility to posaconazole appear to be restricted to a single amino acid in the cytochrome P450 14alpha-demethylase

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#135]
Curation by @MPiovesana 
https://canto.phi-base.org/curs/b6da8569a501db3e

**Comment by MPiovesana** [comment]
No problem identifying Uniprot ID; cyp51A gene of Aspergillus fumigatus (Q4WNT5).

**Comment by MPiovesana** [comment]
**NOTE: THESE NAMES HAVE BEEN MODIFIED AFTER DISCUSSION IN TICKET #157; SEE LATEST COMMENT BELOW!**

In this paper, **CYP51A** alleles are amplified from a wt (ND158) and two mutant (MS6 and R7-1) strains of _Aspergillus fumigatus_, and cloned under the control of the constitutive _gpdA_ promoter from _Aspergillus nidulans_ in an integrative plasmid. A modified ND158 strain of _A. fumigatus_ (harbouring a small deletion in _pyrG_ locus to allow for auxotrophic selection) is then transformed with plasmids. Important to note that endogenous _CYP51A_ is **NOT** replaced in recipient strain. As mutant alleles are derived from strains other than the recipient, and the plasmids are integrated ectopically in the genome, I have chosen **"transformant**" to describe these genotypes. 

I have added the small disruption in pyrG locus as background info (pyrG-) to all genotypes, and I have named the alleles as follows:

**gpdA::CYP51Awt(CYP51A-aaG54)** --> for mutant harbouring wt plasmid-encoded cyp51A

**gpdA::MS6-CYP51A(CYP51A-aaG54R)** --> for mutant harbouring CYP51A-aaG54R derived from strain MS6;

**gpdA::R7-1-CYP51A(CYP51A-aaG54W)** --> for mutant harbouring CYP51A-aaG54W derived from strain R7-1.

Must I add something else to the allele description to indicate the presence of the endogenous wt copy of _CYP51A_?

**Comment by MPiovesana** [comment]
Authors quantify expression levels of _CYP51A_ in all mutant lines (Fig 2), and observe increased expression; however, given that this increased expression is a result of the introduction of extra copies of the gene in the transformant lines, I selected **"ectopic"** as expression level. Is that correct?

**AC:** I think 'ectopic' is correct here, as it seems that the altered phenotype is due to the AA substitution in Cyp51A rather than overexpression of the gene.

**Comment by MPiovesana** [comment]
Phenotype annotation is quite straightforward (Table 2); with **"normal growth on posaconazole"** and **"resistant to posaconazole"** terms used for respective genotypes.

**Comment by MPiovesana** [comment]
@CuzickA Another example for discussion - allele type **"transformant".**

**Comment by MPiovesana** [comment]
> **gpdA::CYP51Awt(CYP51A-aaG54)** --> for mutant harbouring wt plasmid-encoded cyp51A
> 
> **gpdA::MS6-CYP51A(CYP51A-aaG54R)** --> for mutant harbouring CYP51A-aaG54R derived from strain MS6;
> 
> **gpdA::R7-1-CYP51A(CYP51A-aaG54W)** --> for mutant harbouring CYP51A-aaG54W derived from strain R7-1.

Genotypes names modified according to recent discussion of transformant allele type:

**CYP51A transformant(ND158-CYP51A(G54))**[Ectopic] 

**CYP51A transformant(MS6-CYP51A(G54R))**[Ectopic]

**CYP51A transformant(R7-1-CYP51A(G54W))**[Ectopic]

Disruption in pyrG locus and presence of endogenous CYP51A gene were recorded as background info (-pyrG / endogenous CYP51A present)

**Comment by CuzickA** [comment]
Maybe it is better to create genotypes and annotations based on the spontaneous mutations in Cyp51A identified by culturing pathogen with posaconazole. Only one AA change was identified within the Cyp51A gene compared to the WT (Table 1 data). 
However, as it is is possible that other spontaneous mutations have occurred throughout the genotype, maybe it is also worth recording the transformant genotypes as well, which confirm that this AA change in Cyp51A is responsible for the phenotype (Table 2 data).

**Comment by CuzickA** [comment]
I have added the following annotations to capture the spontaneous mutant data in Table 1.

![image](https://github.com/PHI-base/curation/assets/11753634/a84288ca-2741-435f-b412-d7d037ad00cc)

**Comment by CuzickA** [comment]
Current transformant genotype annotations
![image](https://github.com/PHI-base/curation/assets/11753634/62edc510-9967-411b-b666-5075da81c327)

These seem okay, but I will delete the top one as this is really a control and behaves in the same way as the untransformed WT in Table 2

Now looks like this

![image](https://github.com/PHI-base/curation/assets/11753634/ee23cfde-d848-45a9-99dd-4fe36f45b9b8)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

G54R; Cyp51A; ASPEFU
G54W; Cyp51A; ASPEFU

**Questions for Nichola**

Are these correct? I could not find info on Cyp51A in your S file. I found the above information from Table 2 in Mair et al 2016.


![image](https://github.com/PHI-base/curation/assets/11753634/52c5ff7a-78f9-48b9-ba3c-663e61490689)

Session will be approved after archetype check. Closing ticket.

**Comment by CuzickA** [comment]
G54R; Cyp51A; ASPEFU
G54W; Cyp51A; ASPEFU

This is correct

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
