### ISSUE TITLE
PMID: 17371828 A new Aspergillus fumigatus resistance mechanism conferring in vitro cross-resistance to azole antifungals involves a combination of cyp51A alterations

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#136]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/0d6067bd3e39f914

**Comment by MPiovesana** [comment]
**UPDATE: THESE NAMES HAVE BEEN EDITED AFTER RECENT DISCUSSION IN TICKET #157 ABOUT TRANSFORMANT ALLELE TYPE NAMING! SEE LATEST COMMENT BELOW.**

In this paper, authors generate several mutant lines using a gene replacement strategy: 

Strains "**TR**": the endogenous promoter of the **cyp51A** gene of _A. fumigatus_ was replaced with a _cyp51A_ promoter cloned from azole-resistant strains containing two 34bp tandem repeat regions;
Strains "**L98H**": the coding sequence of _cyp51A_ was replaced with a sequence harbouring a point mutation corresponding to the aa substitution L98H. 
Strains "**TRL98H**": both the promoter containing tandem repeats and the gene sequence harbouring the point mutation are inserted replacing the endogenous sequences. 
Strains CM-237 and akuBKU80 are used as recipient for gene replacement.

The following genotypes were created, all with assigned "transformant" allele type given that the mutant promoter and gene were amplified from strain CM2627 and inserted into strains CM-237 and akuBKU80:

**(CM2627-CYP51Aprom)::CYP51Awt (CYP51Aprom(2x34bp tandem repeats)**: strains where mutant promoter was introduced.

**(CM2627-CYP51Aprom)::(CM2627-CYP51A) (CYP51Aprom(2x34bp tandem repeats)+CYP51A-aaL98H)**: strains where both mutant promoter and gene were introduced.

**CYP51Awtprom::(CM2627-CYP51A) (CYP51A-aaL98H)**: strains where only mutant gene was introduced.

Authors measured mRNA levels of CYP51A in all strains, and **Overexpression** and **WT level** were assigned to each genotype as appropriate.

**Comment by MPiovesana** [comment]
Authors test the susceptibility of the laboratory-generated lines to four different azole antifungals; I have annotated their phenotypes to two of them so far (itraconazole and voriconazole), as phenotypes are the same to all azoles tested.

**Comment by MPiovesana** [comment]
Authors test the expression levels of cyp51A gene in transformant lines (Table 3), and establish the gene is overexpressed to varying extents in all lines. Hence, overexpression was chosen to describe all genotypes.

**Comment by MPiovesana** [comment]
Curation completed pending discussion/review.

**Comment by MPiovesana** [comment]
@CuzickA Yet another paper where allele type "**transformant**" can be used. A mutant promoter and gene sequences derived from an azole-resistant strain are introduced by homologous recombination in an azole-sensitive strain. If we consider the resulting genotype alone, we could classify genotypes with amino acid substitution and nucleotide insertion, as a point mutation and tandem repeat insertions are present in the mutant alleles. However, if we consider the origin of the mutant alleles, I guess they are better classified as transformants. What are your thoughts?

**Comment by MPiovesana** [comment]
> In this paper, authors generate several mutant lines using a gene replacement strategy:
> 
> Strains "**TR**": the endogenous promoter of the **cyp51A** gene of _A. fumigatus_ was replaced with a _cyp51A_ promoter cloned from azole-resistant strains containing two 34bp tandem repeat regions; Strains "**L98H**": the coding sequence of _cyp51A_ was replaced with a sequence harbouring a point mutation corresponding to the aa substitution L98H. Strains "**TRL98H**": both the promoter containing tandem repeats and the gene sequence harbouring the point mutation are inserted replacing the endogenous sequences. Strains CM-237 and akuBKU80 are used as recipient for gene replacement.
> 
> The following genotypes were created, all with assigned "transformant" allele type given that the mutant promoter and gene were amplified from strain CM2627 and inserted into strains CM-237 and akuBKU80:

**CYP51Aprom transformant(CM2627-CYP51Aprom(2x34bp tandem repeat))** = strains transformed with CYP51A promoter from strain CM2627

**CYP51Aprom::CYP51A transformant(CM2627-CYP51Aprom(2x34bp tandem repeat)::CM2627-CYP51A(L98H))** = strains transformed with CYP51A promoter and gene sequence from strain CM2627

**CYP51A transformant(CM2627-CYP51A(L98H))** = strains transformed with CYP51A gene from strain CM2627.

Deletion of endogenous CYP51A prom and gene were recorded in background section.

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/c1af6c23-746f-4a50-880c-437e8e5dba36)
![image](https://github.com/PHI-base/curation/assets/11753634/bb3799d9-f518-493d-b6ff-a89d33d70153)

**Comment by CuzickA** [comment]
A. fumigatus azole-susceptible control strain CM237 (and akuBKU80)
A. fumigatus azole-resistant clinical strain CM2627, Cyp51A was found to contain a L98H AA substitution and a 2x34bp tandem repeat insert in the promoter compared to Cyp51A in strain CM237.

> Strains "TR": the endogenous promoter of the cyp51A gene of A. fumigatus was replaced with a cyp51A promoter cloned from azole-resistant strains containing two 34bp tandem repeat regions;
Strains "L98H": the coding sequence of cyp51A was replaced with a sequence harbouring a point mutation corresponding to the aa substitution L98H.
Strains "TRL98H": both the promoter containing tandem repeats and the gene sequence harbouring the point mutation are inserted replacing the endogenous sequences.
Strains CM-237 and akuBKU80 are used as recipient for gene replacement.

**Comment by CuzickA** [comment]
> @CuzickA Yet another paper where allele type "**transformant**" can be used. A mutant promoter and gene sequences derived from an azole-resistant strain are introduced by homologous recombination in an azole-sensitive strain. If we consider the resulting genotype alone, we could classify genotypes with amino acid substitution and nucleotide insertion, as a point mutation and tandem repeat insertions are present in the mutant alleles. However, if we consider the origin of the mutant alleles, I guess they are better classified as transformants. What are your thoughts?

This is a tricky one as multiple methods could be used to record these genotypes. I would like to simplify the current genotypes if possible as they are quite long and complex (current annotation screenshot above).

I am inclined not to use 'transformant' allele type here as it seems more like gene / promoter replacement. As far as is reported, the only changes in the replacements are the L98H AA substitution and a 2x34bp tandem repeat insert in the promoter. Therefore, in theory we could record this as i) a transformant as a region of sequence comes from another strain or ii) we could just highlight the differences made by the gene / promoter replacement in the altered genotype. I think I prefer option ii. I will try and make the changes and see if they make sense.

**Comment by CuzickA** [comment]
This is what I come up with so far (I've not deleted original entries yet)
![image](https://github.com/PHI-base/curation/assets/11753634/0e23a00e-9d8d-4a92-80dc-637825223239)
![image](https://github.com/PHI-base/curation/assets/11753634/a0ef879b-93d3-40b3-886c-f9feeb2298a5)

**Comment by CuzickA** [comment]
Next time
1) have a final check through. I think the akuBKU80 normal growth annotations need changing to resistance with severity low  to follow up in table 4 and discussion text. _DONE Left as normal growth to reflect author statement 'did not correspond to an azole-resistant phenotype'24_04_2024_
2) delete any unwanted annotations and genotypes _DONE 24_04_2024_
3) See if I can add AE alteration in archetype

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/curation/issues/152 for eg of promoter transformant.

**Comment by CuzickA** [comment]
Look like a typo in Table 4
![image](https://github.com/PHI-base/curation/assets/11753634/28242fd3-2019-4bdb-8d61-c1ca0d896c81)

I think the 88 should be 98 to match info in figure legend
![image](https://github.com/PHI-base/curation/assets/11753634/643160ca-8aa9-41ba-8615-1dc97a035817)

**Comment by CuzickA** [comment]
After further thought I now favour the transformant genotypes that Maiara has used.

**Comment by CuzickA** [comment]
Simplify
CYP51Apromoter::CYP51A transformant(CM2627-CYP51Apromoter(2x34bp tandem repeat)::CM2627-CYP51A(L98H))[Overexpression]

to


CYP51A transformant(CM2627-CYP51Apromoter(2x34bp tandem repeat) and CM2627-CYP51A(L98H))[Overexpression]

**Comment by CuzickA** [comment]
Annotations now look like this

![image](https://github.com/PHI-base/curation/assets/11753634/b9400349-98d2-436e-81ac-75d04a6cae7f)
![image](https://github.com/PHI-base/curation/assets/11753634/a4bdc429-2cf5-4d69-812f-fd4461f3cec5)

**Comment by CuzickA** [comment]
**Next**
1) See if I can add AE alteration in archetype

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Aspergillus fumigatus
CYP51A transformant(CM2627-CYP51Apromoter(2x34bp tandem repeat) and CM2627-CYP51A(L98H))[Overexpression]
'L98H; Cyp51A; ASPEFU'
CYP51A transformant(CM2627-CYP51A(L98H))[WT level]
'L98H; Cyp51A; ASPEFU'
Info not in Nichola' S file.

Mair et al 2016
![image](https://github.com/PHI-base/curation/assets/11753634/8b48b11b-4beb-496e-8463-2f4604411858)

![image](https://github.com/PHI-base/curation/assets/11753634/d848cd41-4628-448c-9a0b-7ff7f6274b11)

![image](https://github.com/PHI-base/curation/assets/11753634/1ecb48ed-eb77-41f4-b2c2-43917e2415d3)

**Comment by CuzickA** [comment]
**Next**

1) Check AE alteration in archetype with Nichola.

Then session ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
