### ISSUE TITLE
PMID: 16801438 A Phe389Leu substitution in ergA confers terbinafine resistance in Aspergillus fumigatus

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#137]
Paper curated by @MPiovesana 
https://canto.phi-base.org/curs/6b98cb8ecdf4aa5f
**See latest comment for updated info on genotype creation!**

**Comment by MPiovesana** [comment]
**Uniprot ID:** The authors provide three GenBank accession numbers ('A nucleotide sequence with 73% sequence similarity to ErgA was obtained from the A. fumigatus genome database (GenBank accession no. EAL91820, AY619002.1, and AY532916'). The first one seems to be the best option as it is the curated entry for the squalene epoxidase of A. fumigatus erg1. The second accession number does not return any entries on Uniprot, and the third one returns a non-curated entry. Thus, I opted for Uniprot ID associated with GenBank entry EAL91820, which is E9R5G2.

**AC**: search uniprot with 'EAL91820' gives swiss-prot reviewed entry https://www.uniprot.org/uniprotkb/E9R5G2/entry

**Comment by MPiovesana** [comment]
**Genotype annotation**: As the mutant allele of ErgA was ectopically expressed in A. fumigatus strain ATCC 13073, I selected "transformant" to annotate the altered genotype  and described allele as "AfErgA-F389L". The rest of the annotation was very straightforward (resistant to terbinafine, usual experimental conditions selected for a broth microdilution test).

**Comment by MPiovesana** [comment]
**Question**: Authors mention that "Plasmid pRG47 also contains a silent SacII site mutation within the ergA gene fragment to facilitate rapid identification of transformants"; the site of this silent mutation is not provided. Is it necessary to mention this in the comment section of the genotype annotation, perhaps?

AC: for now I have not added this as we don't have the site of this silent mutation.

**Comment by MPiovesana** [comment]
Curation complete pending review.

**Comment by MPiovesana** [comment]
**Note:** @CuzickA Here is another example where we can discuss the use of the allele type **transformant**. The authors introduce a point mutation in the _ErgA_ gene of _A. fumigatus_, but they do not specify from which strain the gene was originally amplified from. The mutant alleles are then transformed into A. fumigatus cells for ectopic expression (transgene is inserted randomly in the genome, multiple copies, whilst the endogenous wt copy is still present). I though transformant was a good option here, as we don't know the origin of the transgene, and due to the nature of the transformation.

**Comment by MPiovesana** [comment]
> **Genotype annotation**: The mutant allele of _ErgA_ was engineered by site directed in vitro mutagenesis of the wild type _ErgA_ of _A. fumigatus_ (no information about which strain the gene used for mutagenesis was obtained from). The mutant allele was ectopically expressed in _A. fumigatus_ strain ATCC 13073, and allele type "transformant" was chosen to annotate the altered genotype (_ErgA-F389L_ (transformant)) The rest of the annotation was very straightforward (resistant to terbinafine, usual experimental conditions selected for a broth microdilution test).

As no information is given about the strain from which the ErgA allele is originally cloned from, I maintained the choice of using allele type transformant here, in case it was from a strain other than the recipient one. I updated the allele name according to the agreed convention, so the pathogen genotype is recorded as:

**_ErgA transformant (ErgA(F389L))[Ectopic]_**

Strain name is omitted as we do not have this information.

**Comment by MPiovesana** [comment]
**UPDATED**
After revisiting this session and reading the paper again, I believe allele type transformant is not the best option to curate this genotype. Authors clone the wild type ergA gene and introduce a point mutation by in vitro mutagenesis. The mutant allele is then introduced into a wild type strains, and the resulting genotypes display chemical resistance phenotypes. Despite the authors not mentioning which wild type strain was used for the amplification of the wt ergA gene, I think it can be assumed from the text that it was the same strain used as a recipient for the transformation, and therefore, I think allele type amino acid substitution would be the best option here. Thus, the genotype below was created:

**ErgA-F389L(aaF389L)[Not assayed]**

As authors state 'DNA analysis revealed the ergA gene to be ectopically integrated into the TRBR-Ec (TRB-resistant ectopic) strain, indicating that expression of the ectopic mutant gene was dominant over the wild-type allele' I selected ectopic for expression level. The presence of the endogenous wt ErgA gene was recorded in background.

**Comment by CuzickA** [comment]
The A. nidulans expts were not curated in this session because they were reported in a different publication and the focus of this study is A. fumigatus.

**Comment by CuzickA** [comment]
This annotation looks fine
![image](https://github.com/PHI-base/curation/assets/11753634/715ece8a-7a0e-4c57-baf4-9178eb209004)

**Comment by CuzickA** [comment]
Need to add new strain 'ATCC 13073' for A. fumigatus to pathogen strain list.

**Comment by CuzickA** [comment]
AE alteration_in_archetype N/A as no information available for this target site.

**Comment by CuzickA** [comment]
Approving session. (still need to add strain).
