### ISSUE TITLE
PMID: 22536383 Mutagenesis and Functional Studies with Succinate Dehydrogenase Inhibitors in the Wheat Pathogen Mycosphaerella graminicola.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#138]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/23b2e894f5a371bf

**Comment by MPiovesana** [comment]
Rather extensive paper including generation of UV-irradiation mutants, ectopic transformants and homologous recombinants. After reading and analysing the whole paper, I believe the most straightforward experiment to be curated is the one displayed on Figure 6 (analysis of the susceptibility of homologous recombinants to four carboxamide antifungals).

**Comment by MPiovesana** [comment]
Mutant alleles of three genes of Mycosphaerella graminicola (Z. tritici); no GenBank accession number is provided by the authors in the paper, but a quick search on Uniprot using gene and species name returned:

**SDHB** = O42772; unique and curated entry for this gene, no ambiguity  _**(AC 27_03_2024 corrected swiss-prot reviewed entry used in other sessions)_**
**SDHC** = F9XH52; non-curated, but unique entry for the whole sequence of SDHC/3 **(_AC UniProt search for 'sdh3 Zymoseptoria tritici gives F9XH52 for strain IPO323, this is different than uniprot used in https://github.com/PHI-base/curation/issues/207 - consider that these should be the same)_**
**SDHD** = three entries for correct gene, all non-curated. I used the first entry (G4XX47) for the time being (note: no entry returned when searching for SDHD + M. graminicola, only when using SDHD + Z. tritici). _**(AC still to check this one - should the search be SDH4 ([F9X9V6](https://www.uniprot.org/uniprotkb/F9X9V6/entry))or SDHD?)**_ Yes, use F9X9V6. See BLAST results below. Now changed to F9X9V6.

Important to check whether Uniprot IDs used for SDHC and SDHD are the best ones to use here.
AC - Summary of uniprot ids used
'SdhB/2' O42772
'SdhC/3' F9XH52
'SdhD/4' F9X9V6

**Comment by MPiovesana** [comment]
**Genotype annotations:** To keep annotations to a minimum, I have curated the genotypes of the homologous recombinant strains described in Figure 6. I have not included so far the genotypes of the transformant strains carrying ectopic copies of the mutant alleles, as their phenotypes are the same of the HR lines, but to a lesser degree (as seen in Figure 5, for example). As gene replacement by homologous recombination was used, I annotated all genotypes as _"amino acid substitution"_ **(CHANGED LATER TO TRANSFORMANT ALLELE TYPE; SEE LATEST COMMENT BELOW)**. Only those genotypes where an altered phenotype was present (resistance to antifungal) was annotated; those which resulted in normal growth compared to the wt strain were not annotated at the moment. A total of 21 genotype annotations resulted from curation of Figure 6.

**Comment by MPiovesana** [comment]
**Metagenotype annotations:** Homologous recombinant strains were also used for pathogen-host interaction experiment. All HR strains induced an increased extent of pathogen-related necrosis on host leaves, displayed as percentage of leaf area necrosis (Figure 8). Thus, I selected the term _"increased extent of pathogen-associated host lesions_" to annotate these metagenotypes, and the following annotation extensions:

**infects_tissue** leaf
**interaction_outcome** disease present
**infective_ability** increased virulence

As quantification of leaf area affected by necrosis was performed, I chose _"Macroscopic observation (quantitative observation)"_ under Evidence code.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by MPiovesana** [comment]
**Note:** @CuzickA another example for discussion regarding the use of the transformant allele type. Upon revisiting this paper, it is implied in Materials and Methods that authors amplify the mutant alleles of the SDH genes from the mutants they obtained with a mutagenesis experiment. These mutant alleles are then inserted into the genome of the wild type strain via homologous recombination, so that the resulting genotype differs to the wild type only by a single point mutation. Thus, I classified these as "amino acid substitution". However, if we consider the origin of the alleles introduced (mutant strains), should we consider these "transformants"?

**Comment by MPiovesana** [comment]
> **Note:** @CuzickA another example for discussion regarding the use of the transformant allele type. Upon revisiting this paper, it is implied in Materials and Methods that authors amplify the mutant alleles of the SDH genes from the mutants they obtained with a mutagenesis experiment. These mutant alleles are then inserted into the genome of the wild type strain via homologous recombination, so that the resulting genotype differs to the wild type only by a single point mutation. Thus, I classified these as "amino acid substitution". However, if we consider the origin of the alleles introduced (mutant strains), should we consider these "transformants"?

As mentioned in the comment above, we have now agreed that genotypes derived from the introduction of a mutant allele from a given strain into another strain are to be classified as _transformants_. Thus, I have updated this curation session so the genotypes of the HR lines are recorded with a transformant allele type. Even though we know which mutant allele was introduced in each transformant, authors do not provide the name of the strain from which each allele was cloned from (as several of strains harbouring the same mutations were isolated in the mutagenesis screen). For this reason, I selected a representative strain among the ones harbouring the mutation of interest for each genotype (Table 4) for the purpose of allele description. 

Example allele:

**SDHB transformant(Cbx56-SDHB(R265P))[Not assayed]**

Information about deletion of the endogenous copy during gene replacement was recorded in background.

**Comment by CuzickA** [comment]
Still checking uniprots -see comment above

**Comment by CuzickA** [comment]
Looking for correct uniprot for sdhD/4

Blasted '[F9X9V6](https://www.uniprot.org/uniprotkb/F9X9V6/entry)' in uniprot and get 100% match with G4XX47

https://www.uniprot.org/blast/uniprotkb/ncbiblast-R20240416-142424-0603-77715112-p1m/overview
![image](https://github.com/PHI-base/curation/assets/11753634/fe470b13-10b4-4561-894e-8210ad2f29ce)

Use F9X9V6 as sequence from strain IPO323 (reference).

**Comment by CuzickA** [comment]
Uniprot ids in summary

'SdhB/2'  O42772
'SdhC/3'  F9XH52
'SdhD/4'  F9X9V6

**Comment by CuzickA** [comment]
I have checked the Fig 6 Pathogen phenotype annotations.

**Next**
1) Check Fig 8 PHI phenotype annotations _DONE 17_04_2024 look fine_
2) Add a disease annotation _DONE_
3) Try to add in AE alteration in archetype _DONE 17_04_2024_

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/b07f211d-02ee-405f-9062-b2d3b78b765c)

**Comment by CuzickA** [comment]
**AE alteration in archetype**

expt pathogen species _Zymoseptoria tritici_

SDHB transformant(Cbx56-SDHB(R265P))[Not assayed] **'R275P; SdhB; PYRNTE'**

From Nichola's S file
![image](https://github.com/PHI-base/curation/assets/11753634/1df15eb7-1f99-4946-b0fc-70997ac0bc21)
![image](https://github.com/PHI-base/curation/assets/11753634/8d09faff-dbb2-47e3-80c2-d89cdfc773df)
![image](https://github.com/PHI-base/curation/assets/11753634/03e514f8-3c5f-484d-b535-e58db772c8d4)


SDHB transformant(Cbx1-SDHB(I269V))[Not assayed] **'I279V; SdhB; PYRNTE'**

![image](https://github.com/PHI-base/curation/assets/11753634/d36ffe80-412e-4bbe-bf01-61a960dc9918)
![image](https://github.com/PHI-base/curation/assets/11753634/33f16bf5-20d6-4157-917c-eb0f63e12866)


SDHB transformant(Cbx28-SDHB(H267Y))[Not assayed] **'H277Y; SdhB; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/0613384e-8a1d-42b3-8b5c-81b8ad880c40)
![image](https://github.com/PHI-base/curation/assets/11753634/42f468fc-8221-40e3-b67b-4d7c32918eb7)


SDHB transformant(Cbx29-SDHB(H267L))[Not assayed] **'H277L; SdhB; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/ec6dec15-64e6-4a6b-9e09-8bb640924800)
![image](https://github.com/PHI-base/curation/assets/11753634/c8ea2f82-8a6a-4baf-8f79-8103a290cbbe)


SDHC transformant(Flu1-SDHC(S83G))[Not assayed] **'S72G; SdhC; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/fffc4c8a-2f28-4c7b-9a46-a7b772808939)
![image](https://github.com/PHI-base/curation/assets/11753634/733c4676-6f32-4867-b58f-a8d74aa096e4)


SDHC transformant(Flu4-SDHC(A84V))[Not assayed] **'A73V; SdhC; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/5abec305-380d-4a3c-98b0-515c4de64088)
![image](https://github.com/PHI-base/curation/assets/11753634/edd0a768-debb-4efc-b324-5be64293fd7d)


SDHC transformant(Izm7-SDHC(N86K))[Not assayed] **'N75K; SdhC; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/0639172d-0b40-479f-a8e9-40ca10b35817)
![image](https://github.com/PHI-base/curation/assets/11753634/89f8111a-9bb6-46ed-967d-43997bfeb737)


SDHC transformant(Izm1-SDHC(H152R))[Not assayed] **'H141R; SdhC; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/67577dac-e9e1-4cfb-984d-0ca8fc8b79f3)
![image](https://github.com/PHI-base/curation/assets/11753634/9ff8ee5f-92b7-4934-bd8a-5d272aee5412)


SDHD transformant(Cbx67-SDHD(D129G))[Not assayed] **'D145G; SdhD; PYRNTE'**
![image](https://github.com/PHI-base/curation/assets/11753634/fbd6c604-284d-4f71-952f-30a568ee4d0b)
![image](https://github.com/PHI-base/curation/assets/11753634/f246d042-dbad-4bfe-896b-5ca5ca01c91e)

**Comment by CuzickA** [comment]
Next steps for session
1) check AE with Nichola

Then session will be ready to approve

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
