### ISSUE TITLE
PMID: 9871122 A single amino-acid substitution in the iron-sulphur protein subunit of succinate dehydrogenase determines resistance to carboxin in Mycosphaerella graminicola

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#139]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/582d4c8ef63edb43

**Comment by MPiovesana** [comment]
**Uniprot ID**: GenBank accession number provided in the paper, no issues locating Uniprot ID (O42772).

AC: authors provide AF042062

**Comment by MPiovesana** [comment]
**Strain**: authors mention the use of a wild type strain of M. graminicola, but nowhere in the text they mention the name of this strain. Therefore, I have selected "Unknown strain" when curating this paper.

AC: I agree. Text from methods  ' A field isolate of M. graminicola,
obtained from Tom Hunter (IACR-Long Ashton Research
Station), was used throughout.'

**Comment by MPiovesana** [comment]
**UPDATED 14TH JULY ACCORDING TO NEW GUIDANCE FOR NAMING OF ALLELE TYPE TRANSFORMANT** 
**Genotype annotation**: the mutant SDH2 allele was amplified from a Cbx-resistant strain and inserted into the wt strain, and therefore **transformant** was selected to annotate this genotype:

**SDH2 transformant(Cbx02-SDH2(H267Y))** = H267Y indicating point mutation, and Cbx02 indicating the origin of the mutant allele (strain Cbx02). Presence of endogenous SDH2 gene was recorded in background.

Straightforward phenotype annotation as carboxin resistance is only reported phenotype (Figure 3c).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
This session looks fine. 

Can I add AE alteration in archetype?

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Zymoseptoria tritici
SDH2 transformant(Cbx02-SDH2(H267Y))[Ectopic] 'H277Y; Sdh2 (SdhB); PYRNTE'

From Nichola's S file
![image](https://github.com/PHI-base/curation/assets/11753634/61a7d5ea-5312-4b8d-a89e-63bdd9bbcd25)
![image](https://github.com/PHI-base/curation/assets/11753634/745b9acc-0d08-415a-8842-472b6ea55177)


From Mair et al 2016
![image](https://github.com/PHI-base/curation/assets/11753634/e4810f7f-c8e8-4a84-97dc-56476b924fa0)
![image](https://github.com/PHI-base/curation/assets/11753634/a2b08f7f-d4af-4982-9c2b-3a44429ca7eb)



![image](https://github.com/PHI-base/curation/assets/11753634/03319c45-0045-4236-ae17-68fb010af3b7)

**Comment by CuzickA** [comment]
Need to check AE with Nichola. Then session will be ready to approve.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
