### ISSUE TITLE
PMID:15215142 Substitutions at methionine 220 in the 14alpha-sterol demethylase (Cyp51A) of Aspergillus fumigatus are responsible for resistance in vitro to azole antifungal drugs.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#140]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/6b96165af86b6fa7

**Comment by jingluodatacurator** [comment]
Have not added in any comments in the phenotype annotation sections, unsure what to include.

**Comment by jingluodatacurator** [comment]
Apart from phenotype annotation comments, curation completed pending review.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, before I start checking this older curation session, please could you

1) email me your highlighted PDF
2) add a short summary of the expt to this GitHub, including how you found the UniProt ids etc
3) double check the annotations with your new additional curation knowledge and personal curation checklist
4) Please let me know when you've done the above and then I'll check the session. Thanks

**Comment by jingluodatacurator** [comment]
Summary of expt. :

Sequence analysis of cyp51A revealed a number of point mutations. The five ITC-resistant strains (CM-1252, CM-1245, CM-2158, CM-2159, and CM-2164) each had a single nucleotide substitution in codon 220 (encodes methionine), resulting in the introduction of valine, lysine, or threonine (Table 1).

The cyp51A alleles from strains CM-1252, CM-2159, and CM-2164 were PCR amplified, and each was individually electroporated into the wild-type A. fumigatus strain CM-237. Electroporation was carried out; transformants were selected on medium containing ITC as described previously. ITC-resistant transformants appeared after 2 to 7 days of incubation. The transformants were labelled with a “T” followed by a roman numeral (Table 1). The numbers of ITC-resistant transformants obtained using the cyp51A genes from strains CM-2159, CM-1252, and CM-2164
were four (T-III, T-VI, T-VII and T-XI), one (T-XII), and one (T-XXII), respectively. All six appeared to have incorporated the mutated cyp51A allele. With the exception of the original mutation at codon 220, none of the transformants had any other mutations in either cyp51A or cyp51B. In general, the transformants exhibited susceptibility profiles similar to those of the original clinical isolates (Table 1).

**Comment by jingluodatacurator** [comment]
Uniprot IDs: author provided GenBank AAK73659 and AAK73660 for cyp51A and cyp51B respectively, and they were used in Uniprot to find IDs Q9P8R0, Q96W81.

Strains: CM-237 is sensitive to azole drugs and was used for replacement mutation expt.

**Comment by jingluodatacurator** [comment]
Genotype creation:

cyp51A(aaM220V), cyp51A(aaM220K), cyp51A(aaM220T) genotypes have been created.

T-III, T-VI, T-VII, T-XI, T-XII and T-XXII have been curated for itraconazole:
T-III, T-VI, T-VII, T-XI are related to cyp51A(aaM220K);
T-XII is related to cyp51A(aaM220V);
T-XXII is related to cyp51A(aaM220T).

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks.

https://canto.phi-base.org/curs/6b96165af86b6fa7

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/799a207a-7647-4e73-ae10-32a3193fed99)

**Comment by CuzickA** [comment]
> Uniprot IDs: author provided GenBank AAK73659 and AAK73660 for cyp51A and cyp51B respectively, and they were used in Uniprot to find IDs Q9P8R0, Q96W81.

AC checking UniProt
It is true that the author provided GenBank AAK73659 for Af Cyp51A which pulls up UniProt id Q9P8R0. However, this is an unreviewed entry https://www.uniprot.org/uniprotkb/Q9P8R0/entry.

We have curated Af Cyp51A in other publications/sessions and have used the UniProt Swiss-Prot reviewed entry https://www.uniprot.org/uniprotkb/Q4WNT5/entry

Therefore I think the UniProt id needs changing to Q4WNT5.

Currently there are no annotations in this session to Cyp51B.

**Comment by CuzickA** [comment]
I still need to check the genotype further but it doesn't look like these are nt substitutions. They should be AA substitutions.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please can you 
1) change the UniProt id as suggested above
2) re-make the genotypes following the information highlighted in blue
![image](https://github.com/PHI-base/curation/assets/11753634/99ea56da-d3f5-41f1-8e7c-aa1ab5911f3d)

**Comment by CuzickA** [comment]
> Genotype creation:
> 
> T-III, T-VI, T-VII, T-XII, T-XII and T-XXII have been curated for itraconazole.

Hi @jingluodatacurator, when you record the '**Genotype creation**', please can you add in the actual genotypes added into PHI-Canto? These can then be linked to the mutant line names you have recorded here. This makes the checking of the session more straight forward.

**Comment by CuzickA** [comment]
> Uniprot IDs: author provided GenBank AAK73659 and AAK73660 for cyp51A and cyp51B respectively, and they were used in Uniprot to find IDs Q9P8R0, Q96W81.
> 
> Strains: CM-237 was used for replacement mutation expt.

@jingluodatacurator, likewise here when making a note of the strain 'CM-237' please could you add whether this is sensitive or resistant to the chemical. This makes it more straight forward to check the sessions.

**Comment by CuzickA** [comment]
I have added a GO MF annotation
![image](https://github.com/PHI-base/curation/assets/11753634/d0a36170-ef84-4032-9d7d-e17e4edddec0)

**AC next steps**
1) Check JL's edits suggested above
2) Once we have the correct genotypes, try and add in AE alteration in archetype

(It looks like the key annotations have been made -just need some edits. No further expt to curate in this paper)
(no need for new strain or PHIPO terms)

**Comment by jingluodatacurator** [comment]
> I have added a GO MF annotation ![image](https://private-user-images.githubusercontent.com/11753634/310435022-d0a36170-ef84-4032-9d7d-e17e4edddec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTc4NzQsIm5iZiI6MTcwOTcxNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8zMTA0MzUwMjItZDBhMzYxNzAtZWY4NC00MDMyLTlkN2QtZTE3ZTRlZGRkZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA5MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NGU1ZTZhY2IzZDZhYzI1NmNhN2ViNWFkYmU3MjhhZmYxNDc2YTBjZjJhMGE3YTBlNWZjMzUxYmM5ZjhhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Thx548C2MIhMKfpxejTi3ZVGqJPx7gHqprX4ULC5JYo)
> 
> **AC next steps**
> 
> 1. Check JL's edits suggested above
> 2. Once we have the correct genotypes, try and add in AE alteration in archetype
> 
> (It looks like the key annotations have been made -just need some edits. No further expt to curate in this paper) (no need for new strain or PHIPO terms)

Hi @CuzickA, all comments have been responded and edits have been done to curation and notes for GitHub above, please check thanks.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, the only changes to this sessions that I can see is the changed UniProt id
![image](https://github.com/PHI-base/curation/assets/11753634/9ab68ba3-1a7b-4ac9-be90-796eaa7a2d50)

**Comment by CuzickA** [comment]
> > Genotype creation:
> > T-III, T-VI, T-VII, T-XII, T-XII and T-XXII have been curated for itraconazole.
> 
> Hi @jingluodatacurator, when you record the '**Genotype creation**', please can you add in the actual genotypes added into PHI-Canto? These can then be linked to the mutant line names you have recorded here. This makes the checking of the session more straight forward.

@jingluodatacurator, please add the requested information into this comment.

**Comment by CuzickA** [comment]
> > Uniprot IDs: author provided GenBank AAK73659 and AAK73660 for cyp51A and cyp51B respectively, and they were used in Uniprot to find IDs Q9P8R0, Q96W81.
> > Strains: CM-237 was used for replacement mutation expt.
> 
> @jingluodatacurator, likewise here when making a note of the strain 'CM-237' please could you add whether this is sensitive or resistant to the chemical. This makes it more straight forward to check the sessions.

@jingluodatacurator, please add the requested information into this comment.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, the only changes to this sessions that I can see is the changed UniProt id ![image](https://private-user-images.githubusercontent.com/11753634/310507344-9ab68ba3-1a7b-4ac9-be90-796eaa7a2d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzA1NDksIm5iZiI6MTcwOTczMDI0OSwicGF0aCI6Ii8xMTc1MzYzNC8zMTA1MDczNDQtOWFiNjhiYTMtMWE3Yi00YWM5LWJlOTAtNzk2ZWFhN2EyZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOGFiMmIwNjFjNzRmMWM0ZDFhODU1OWE5N2U5YWNjN2M0NTFlODdlMjJjMWFkY2E5M2FlZDBiNmQwM2QxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-8-VhTK58tPmsDNyto1AOzZbSgY1ezjNOHZch_2hmO4)

Hi @CuzickA, that's rather strange. I have made changes in genotypes from nt substitutions to aa substitutions.

**Comment by jingluodatacurator** [comment]
> > > Genotype creation:
> > > T-III, T-VI, T-VII, T-XII, T-XII and T-XXII have been curated for itraconazole.
> > 
> > 
> > Hi @jingluodatacurator, when you record the '**Genotype creation**', please can you add in the actual genotypes added into PHI-Canto? These can then be linked to the mutant line names you have recorded here. This makes the checking of the session more straight forward.
> 
> @jingluodatacurator, please add the requested information into this comment.

Hi @CuzickA, I have updated this in my original comment at the top.

**Comment by jingluodatacurator** [comment]
> > > Uniprot IDs: author provided GenBank AAK73659 and AAK73660 for cyp51A and cyp51B respectively, and they were used in Uniprot to find IDs Q9P8R0, Q96W81.
> > > Strains: CM-237 was used for replacement mutation expt.
> > 
> > 
> > @jingluodatacurator, likewise here when making a note of the strain 'CM-237' please could you add whether this is sensitive or resistant to the chemical. This makes it more straight forward to check the sessions.
> 
> @jingluodatacurator, please add the requested information into this comment.

Hi @CuzickA, likewise, I have updated this in my original comment at the top.

**Comment by CuzickA** [comment]
Thanks, missed those updates as the ticket is getting long.

**Comment by CuzickA** [comment]
> Hi @CuzickA, that's rather strange. I have made changes in genotypes from nt substitutions to aa substitutions.



These genotypes are still incorrect @jingluodatacurator 

![image](https://github.com/PHI-base/curation/assets/11753634/a70f512d-ba74-4f6d-95d5-2464e98bd04d)

It looks as though you have changed the allele type from nt to AA and not updated the nt symbols to AA residue symbols as highlighted in blue in the comment above.

**Comment by CuzickA** [comment]
> Genotype creation:

cyp51A(aaA220G), cyp51A(aaT220A), cyp51A(aaT220C) genotypes have been created.
T-III, T-VI, T-VII, T-XII, T-XII and T-XXII have been curated for itraconazole.

@jingluodatacurator, this comment will also need updating above please when you change the genotypes. Also can you note which PHI-Canto genotypes 'T-III, T-VI, T-VII, T-XII, T-XII and T-XXII' relate to please. This will make it easier to understand the curation for checking and if we need to go back to it. Thanks.

**Comment by jingluodatacurator** [comment]
> > Hi @CuzickA, that's rather strange. I have made changes in genotypes from nt substitutions to aa substitutions.
> 
> These genotypes are still incorrect @jingluodatacurator
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/310510271-a70f512d-ba74-4f6d-95d5-2464e98bd04d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzE1MDksIm5iZiI6MTcwOTczMTIwOSwicGF0aCI6Ii8xMTc1MzYzNC8zMTA1MTAyNzEtYTcwZjUxMmQtYmE3NC00ZjZkLTk1ZDUtMjQ2NGU5OGJkMDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDljYThkMzc1OTllNjM3ODcyZDBmYTY5NDM4MjM5YmJlNmRjMzIyMDBmMTlkZTEyZDAwMjIyZTM1ZTZhOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2eIL-blM06c_0io3DuOzai2PmQ8Uph0hWbbPY5HeKvI)
> 
> It looks as though you have changed the allele type from nt to AA and not updated the nt symbols to AA residue symbols as highlighted in blue in the comment above.

Hi @CuzickA, I got confused but have now corrected them thanks.

**Comment by jingluodatacurator** [comment]
> > Genotype creation:
> 
> cyp51A(aaA220G), cyp51A(aaT220A), cyp51A(aaT220C) genotypes have been created. T-III, T-VI, T-VII, T-XII, T-XII and T-XXII have been curated for itraconazole.
> 
> @jingluodatacurator, this comment will also need updating above please when you change the genotypes. Also can you note which PHI-Canto genotypes 'T-III, T-VI, T-VII, T-XII, T-XII and T-XXII' relate to please. This will make it easier to understand the curation for checking and if we need to go back to it. Thanks.

Hi @CuzickA, I have updated the original comment again at the top thanks.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/3a84de71-f0d5-4c8f-87d3-b00849b3b705)

looks good, thanks @jingluodatacurator 

**AC next steps**

1) Try and add in AE alteration in archetype

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Info not listed in Nichola's S file but it is in Mair et al 2016

![image](https://github.com/PHI-base/curation/assets/11753634/d2e39df7-5749-432b-8f3a-31f996227a10)
![image](https://github.com/PHI-base/curation/assets/11753634/e1fb716f-7ef0-4087-8ed8-f26bc8e9afa5)


cyp51A(aaM220V) 'M220V; Cyp51A; ASPEFU'
cyp51A(aaM220K) 'M220K; Cyp51A; ASPEFU'
cyp51A(aaM220T) 'M220T; Cyp51A; ASPEFU'

AE added below

![image](https://github.com/PHI-base/curation/assets/11753634/1230a182-e155-4833-b29c-e660880e1e29)

**Comment by CuzickA** [comment]
**AC next steps**

1) check AE alteration in archetype with Nichola

Then session will be ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
