### ISSUE TITLE
PMID:18443110 A naturally occurring proline-to-alanine amino acid change in Fks1p in Candida parapsilosis, Candida orthopsilosis, and Candida metapsilosis accounts for reduced echinocandin susceptibility.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#141]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/6c83025cb4d29f2a

**Comment by jingluodatacurator** [comment]
Curation completed pending review.
Please double check expression level, conditions and comment.

**Comment by CuzickA** [comment]
We cannot curate the natural sequence variation within FKS1 of Candida parapsilosis, Candida orthopsilosis, and Candida metapsilosis.

We can only curate the section of data using Saccharomyces cerevisiae 
![image](https://github.com/PHI-base/curation/assets/11753634/6db95d7c-f69e-46f5-8e7e-ff33ad741ee2)

**Comment by CuzickA** [comment]
Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/291fa1aa-88df-4f59-870f-7165732e0cb0)

![image](https://github.com/PHI-base/curation/assets/11753634/45398a93-b3d0-4cf7-99eb-500aa348bf4c)

**Comment by CuzickA** [comment]
@MPiovesana, when you have a minute please could you have a look at the method in the publication for creating the Sc FKS1 P647A genotype. It is a 2-step method and I think it is essentially a partial gene replacement incorporating the P647A change. In which case the current genotype above with the partial deletion and AA substitution would not be correct. Its a shame that there is no image in the publication to describe it.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, similar to the last session I checked in https://github.com/PHI-base/curation/issues/145 the curation needs to be split out into separate annotations rather than being grouped together.

Here are the changes I have made to the above annotation, please let me know if they make sense to you or if they require further explanation

![image](https://github.com/PHI-base/curation/assets/11753634/f6fe455f-4cbd-4f9e-8d32-9465f917dc16)

**Comment by CuzickA** [comment]
Once we have resolved the genotype query I will also change the expression level to not assayed.

**Comment by MPiovesana** [comment]
> @MPiovesana, when you have a minute please could you have a look at the method in the publication for creating the Sc FKS1 P647A genotype. It is a 2-step method and I think it is essentially a partial gene replacement incorporating the P647A change. In which case the current genotype above with the partial deletion and AA substitution would not be correct. Its a shame that there is no image in the publication to describe it.

@CuzickA I have just checked the Materials and Method and the Results sections of the paper, and indeed the 2-step method (deletion followed by homologous recombination) results in a partial gene replacement, where the only difference between the wild type and the mutant alleles is the presence of the **P647A** mutation. So I believe this genotype can be annotated as an **amino acid substitution**, and the deletion can be omitted as it was only a step in the gene replacement technique employed by the authors.

**Comment by CuzickA** [comment]
Thanks @MPiovesana 

Genotype now updated to
![image](https://github.com/PHI-base/curation/assets/11753634/9efa8f1c-0a30-47a7-a35e-28014fb7cac8)

Annotations now look like this
![image](https://github.com/PHI-base/curation/assets/11753634/73f05e82-1452-4d42-a272-e87e48c99354)

**Comment by CuzickA** [comment]
Session now approved. I will leave this ticket open until @jingluodatacurator has had a chance to look at the comments and then I will close it.

**Comment by CuzickA** [comment]
no archetype information found
