### ISSUE TITLE
PMID: 32569396 Mutations at sterol 14α-demethylases (CYP51A&B) confer the DMI resistance in Colletotrichum gloeosporioides from grape.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#142]
Curation by @MPiovesana.
https://canto.phi-base.org/curs/b3eb3692dd4684de

**Comment by MPiovesana** [comment]
Rather extensive paper where authors describe the generation of single deleted and complemented lines of Cyp51A/B in C. gloeosporioides. Deleted lines are generated by deleting Cyp51A or Cyp51B in a wild type strain named JS67 (strain name added manually to PHI-Canto). Then, the deleted lines are used as recipient for the insertion of mutant alleles of Cyp51A and B, respectively, harbouring multiple point mutations (Table 3). Mutant alleles were cloned from field strains displaying low or moderate resistance to azole fungicides. I have decided, for the time being, to curate only the phenotypes associated with the single deleted genotypes, as the complemented lines include mutant alleles harbouring up to seven point mutations + mutation at stop codon leading to the addition of extra aa to the protein. Authors do not test which of the point mutations is responsible for the chemical resistance/susceptibility phenotypes later shown to be associated with these alleles, so I think we can discuss whether it would make sense to annotate them too.

**AC:** Seems reasonable to focus on the gene deletion lines rather than multiple point mutations which may or may not be responsible for the phenotypes.

**Comment by MPiovesana** [comment]
**Uniprot ID**: accession numbers for Cyp51A and B of C. gloeosporioides are provided in Materials and Methods; associated with Uniprot IDs L2FQR9 and L2FD62.

**AC:** UniProt has multiple reference proteomes for  this species
![image](https://github.com/PHI-base/curation/assets/11753634/6b486169-6126-4316-80c1-0e7f447dc15d)

The currently selected strains are for strain Nara gc5. I cannot find any reviewed uniprot entries for Cyp51A and B of C. gloeosporioides, so I think we will stick with the currently selected Uniprots ids based on the information provided in the M&M.
![image](https://github.com/PHI-base/curation/assets/11753634/1ef962e3-4c04-46a2-a1f8-81737b77bd7d)
CYP51A https://www.uniprot.org/uniprotkb/L2FQR9/entry
CYP51B https://www.uniprot.org/uniprotkb/L2FD62/entry

**Comment by MPiovesana** [comment]
**Single mutant genotype annotations:** No problems annotating single genotypes. I chose 3 out of 6 antifungals tested (Table 4) so the number of annotations would not be too big. However, I would be happy to include all annotations if appropriate. 

AC: see below

**Comment by MPiovesana** [comment]
**Metagenotype annotations**: authors also test the virulence of mutant lines by infecting tomato and mango (Figure 4b and 4d). I created metagenotypes (including the wt Cyp51A and Cyp51B alleles) to curate this experiment. PHIPO term "presence of pathogen-associated host lesions" was chosen to describe the presence of necrotic lesions on infected fruit. As lesion diameter was measured 7 days post-inoculation, "macroscopic observation - quantitative observation" was chosen under Evidence Code.

**Comment by MPiovesana** [comment]
**Fungal growth**: authors mention that single deletions also affect fungal growth on plates, and reference Figure 4 and Table S4. However, Figure 4 only shows data relative to lesion diameter upon pathogen inoculation on host, and I could not find these results in any other of the main figures. As Table S4 is in Supplemental material, I wondered whether we should curate this information or not, given that we are trying to curate only main results. For now, I did not annotate fungal growth for the single genotypes.

**AC:** see below. I think we will include the info for Table S4. I think the authors refer to Fig 4 in the results text but mean Fig 3 with no chemical added.

**Comment by MPiovesana** [comment]
Curation completed pending review; might need to add more annotations for other antifungal compounds and complemented lines (up for discussion).

**Comment by CuzickA** [comment]
> **Single mutant genotype annotations:** No problems annotating single genotypes. I chose 3 out of 6 antifungals tested (Table 4) so the number of annotations would not be too big. However, I would be happy to include all annotations if appropriate.

I will add in the additional 3 antifungals once a bug is fixed in PHI-Canto. The planned annotations are
CYP51AΔ sensitive to Triadimefon
CYP51AΔ resistance to Tebuconazole
CYP51AΔ sensitive to Prothioconazole
CYP51BΔ resistance to Triadimefon
CYP51BΔ resistance to Tebuconazole
CYP51BΔ sensitive to Prothioconazole

PHIPO NTR: sensitive to Prothioconazole
PHI-ECO NTR: + Prothioconazole
Prothioconazole already added to our anti-infective list

**Comment by CuzickA** [comment]
> Fungal growth: authors mention that single deletions also affect fungal growth on plates, and reference Figure 4 and Table S4. However, Figure 4 only shows data relative to lesion diameter upon pathogen inoculation on host, and I could not find these results in any other of the main figures. As Table S4 is in Supplemental material, I wondered whether we should curate this information or not, given that we are trying to curate only main results. For now, I did not annotate fungal growth for the single genotypes.

I want to make the following annotations once the bug in PHI-Canto is fixed. I currently cannot make new annotations.

![image](https://github.com/PHI-base/curation/assets/11753634/00f69e8e-45d9-43cf-a22e-b13a50dff2dc)
Comment text to copy and paste 'Deletion of CgCYP51A led to attenuated growth on PDA medium,
whereas disruption of CgCYP51B caused enhanced growth on the
same condition (Fig. 4; Table S4). (I think this should be Fig 3. with 0 chemical added).'

The same for 
CYP51BΔ increased hyphal growth

**Comment by CuzickA** [comment]
So in summary, still to do for this session once bugs fixed and ontology terms available

1) add in 6 annotations for additional antifungals as noted above.
2) add 2 annotations for decreased/increased hyphal growth.
3) decide whether to create the new PHIPO and PHI-ECO terms using script developed by @jseager7 or create terms as before (manually in protege and PHI-ECO term creator).

AE alteration in archetype N/A as genotypes contain full gene deletion

**Comment by CuzickA** [comment]
I have now done points 1 and 2
1. add in 6 annotations for additional antifungals as noted above.
2. add 2 annotations for decreased/increased hyphal growth.

@jseager7, do you have a preference on the method of generating the new PHIPO and PHI-ECO terms for point 3 above?

**Comment by jseager7** [comment]
@CuzickA For any chemical terms required for PHIPO and PHI-ECO I'd recommend putting them in the ticket at https://github.com/PHI-base/phipo/issues/419.

In future, assuming the term names follow the usual pattern (resistance/sensitivity/normal for PHIPO and '+ chemical' for PHI-ECO) all I need is the name of the chemical, so there's no need to even write the term names.

**Comment by CuzickA** [comment]
> @CuzickA For any chemical terms required for PHIPO and PHI-ECO I'd recommend putting them in the ticket at [PHI-base/phipo#419](https://github.com/PHI-base/phipo/issues/419).
> 
> In future, assuming the term names follow the usual pattern (resistance/sensitivity/normal for PHIPO and '+ chemical' for PHI-ECO) all I need is the name of the chemical, so there's no need to even write the term names.

That's great, thanks @jseager7. This will no doubt save me a lot of time :-)

**Comment by CuzickA** [comment]
New terms now added, session approved, closing ticket.
