### ISSUE TITLE
PMID: 27799210 Screening and Characterization of a Non-cyp51A Mutation in an Aspergillus fumigatus cox10 Strain Conferring Azole Resistance

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#143]
Curation by @MPiovesana 
https://canto.phi-base.org/curs/d2c4a7ceed32cff8

**Comment by MPiovesana** [comment]
**GENOTYPES EDITED AFTER DISCUSSION ABOUT TRANSFORMANT ALLELE TYPES; SEE LATEST COMMENT FOR UPDATE!**

In this paper, authors observe that the deletion of the **_algA_** gene leads to an increased frequency of spontaneous mutations associated with azole resistance in _Aspergillus fumigatus_. Among several resistant mutants identified in the delta-_algA_ background, two are selected for whole genome sequencing analysis. Despite the presence of multiple SNPs in both mutants, the only difference between the two is that one carries a single point mutation in a gene homologous to **_cox10_** from yeast, therefore named _Afcox10_ in the paper, and the other carries a SNP in **_cyp51A_**. To confirm whether these SNPs are responsible for the increased resistance to itraconazole in an algA-independent way, the wild strain A1160 was transformed with the respective mutant alleles. It is not clear whether a gene replacement strategy was used, but it is implied given that the authors clone the flanking regions as well as the ORF of _Afcox10_ and _cyp51A_ during the cloning procedures. Thus, I identified three genotypes for curation:

**_algAΔ_** - deletion of algA in wild type background
**_Afcox10(aaR243Q)_** - introduction of mutant allele of Afcox10 in wild type background; cox10Δ added in background to reflect gene replacement;
**_cyp51A(aaF219L)_** - introduction of mutant allele of cyp51A in wild type background; cyp51AΔ added in background to reflect gene replacement.

Throughout the text, authors reference two wild type strains, A1160 and A1160c. By carefully reading the Materials and Methods section, figure legend and Results, it is apparent that strain A1160c was used as recipient for all transformation experiments. Thus,  have selected this strain for curation.

**Comment by MPiovesana** [comment]
**Uniprot ID**: accession numbers are provided for _algA_ and _Afcox10_, and _cyp51A_ is readily found with a quick search on Uniprot as well. No issues locating IDs.

**Comment by MPiovesana** [comment]
**Genotype annotations:** annotations were straightforward; phenotype of _algAΔ_ genotype is found in Figure 1a-b, and phenotypes of transformed strains is found in Figure 5. Other figures of the paper refer to spontaneous mutants generated on plates by the exposure of _algAΔ_ to azoles; these mutants, however, contain several mutations across their genome, and not all were fully sequenced. Therefore, I think the annotation of the above-mentioned strains is sufficient.

**Comment by MPiovesana** [comment]
**PHIPO terms**: new terms were suggested:
normal growth on itraconazole
normal growth on caspofungin
normal growth on terbinafine
normal growth on bifonazole

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by MPiovesana** [comment]
> Thus, I identified three genotypes for curation:
> 
> **_algAΔ_** - deletion of algA in wild type background **_Afcox10(aaR243Q)_** - introduction of mutant allele of Afcox10 in wild type background **_cyp51A(aaF219L)_** - introduction of mutant allele of cyp51A in wild type background
> 

The wild type strain A1160C is transformed with the mutant alleles derived from strains W004 and W601. Thus, this falls under the definition of transformant allele type. I edited the genotypes in this curation session to be recorded as:

**cox10 transformant (W004-cox10(R243Q))** = mutant _cox10_ allele from strain W004 introduced in wt strain;

**cyp51A transformant (W601-cyp51A(F219L))** =  mutant _cyp51A_ allele from strain W601 introduced in wt strain.

Although not completely clear in Materials and Methods, I believe the mutant alleles were introduced using a gene replacement by homologous recombination strategy, as the 5' and 3' regions of the genes were also amplified during the cloning steps. Thus, I recorded the deletion of the endogenous _cox10_ and _cyp51A_ genes in the background section.

**Comment by CuzickA** [comment]
We could also curate the info in Fig 4.
algAdelta strains selected on chemistry for spontaneous mutants leading to increased resistance. Strain W004 with cox10 R243Q and strain W601 Cyp51 F219L.

This may have been omitted in preference of curating the transformant genotypes with intact algA in fig 5 indicating chemistry R phenotype is algA independent.

**Comment by CuzickA** [comment]
Current transformant annotations seem fine. (Above Fig 4 does not seem to be required).

**Comment by CuzickA** [comment]
No need to add new strain.

**Next**
1) Need new PHIPO terms.
2) Can I add AE for Cyp51?
3) Any GO annotations?

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/ef3ee2c2-460d-4c8d-ac8f-098550c1b6d5)

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Aspergillus fumigatus (this is also the archetype species)
cyp51A transformant(W601-cyp51A(F219L))[Not assayed]   'F219L; Cyp51A; ASPEFU'

No info in Nichola's S file.
In Mair et al 2016

![image](https://github.com/PHI-base/curation/assets/11753634/1f0ee64e-1c03-47ca-9e90-87d0001d044a)
![image](https://github.com/PHI-base/curation/assets/11753634/89889fbc-e31e-49ad-90a2-6b15ec58f3a8)

![image](https://github.com/PHI-base/curation/assets/11753634/e0c36a96-0dba-4390-9c91-2c5e1e2ad8ea)

**Comment by CuzickA** [comment]
**Next**
1) add new PHIPO terms _NOW DONE_
2) Check AE alteration in archetype with Nichola

Then ready to approve.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
