### ISSUE TITLE
PMID: 22912706 Functional and structural comparison of pyrrolnitrin- and iprodione-induced modifications in the class III histidine-kinase Bos1 of Botrytis cinerea

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#144]
Curated by @MPiovesana 

https://canto.phi-base.org/curs/af7a3166d6769237

**Comment by MPiovesana** [comment]
In this paper authors induce resistance to pyrrolnitrin and iprodione in five parental strains of **_B. cinerea_**, and proceed to sequence the **_bos1_** gene to identify mutations potentially associated with the chemical resistance phenotypes. Identified mutations are then introduced in wild type strain B05.10 by homologous recombination and gene replacement, and the susceptibility of transformant lines to antifungals is tested. As per Table 3, there are 8 mutant genotypes to be annotated.

**Comment by MPiovesana** [comment]
**Uniprot ID query:** authors do not provide a GenBank accession number for _bos1_, and several are returned upon search on Uniprot with the terms _"bos1"_ and _"Botrytis cinerea"_. However, a paper previously curated by me also described an altered genotype with the _bos1_ gene (GitHub ticket #129), and I used the same ID as used then (Q8X215; which was indicated by the authors of that paper).

**Comment by MPiovesana** [comment]
**Genotype annotations**: all genotypes were annotated according to the results displayed in Table 3. Although the authors do not mention it explicitly in the text, I believe the phenotype of the recipient wild type strain B05.10 is sensitivity to all antifungals tested (as it is usually the case). I have only annotated the phenotypes described for **pyrrolnitrin** and **iprodione**, as these are the ones named in the title of the paper; furthermore, two antifungals were used to test susceptibility to phenylpyrroles, but I don't believe these are the main focus of the paper. I also did not find a way to annotate the osmosensitivity of the transformant strains, as I could not find an appropriate PHIPO term. Would it be interesting to annotate this phenotype too?

**Comment by MPiovesana** [comment]
**PHIPO terms suggested**: 
normal growth on pyrrolnitrin
resistance to pyrrolnitrin

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Current annotations look good

![image](https://github.com/PHI-base/curation/assets/11753634/58f47024-4aac-4cd4-aad4-6e8d4103f49e)
![image](https://github.com/PHI-base/curation/assets/11753634/8a288d03-a817-49c8-bc3b-1cd539f593d6)
![image](https://github.com/PHI-base/curation/assets/11753634/e95753c2-a37e-445e-9050-f6a6739b418b)
![image](https://github.com/PHI-base/curation/assets/11753634/3cb7a809-a525-4b48-9542-e137a6cca7d1)

**Comment by CuzickA** [comment]
> Uniprot ID query: authors do not provide a GenBank accession number for bos1, and several are returned upon search on Uniprot with the terms "bos1" and "Botrytis cinerea". However, a paper previously curated by me also described an altered genotype with the bos1 gene (GitHub ticket https://github.com/PHI-base/curation/issues/129), and I used the same ID as used then (Q8X215; which was indicated by the authors of that paper).

Hmm... this is another tricky UniProt issue.

I think that ideally we want the UniProt Id associated with the reference proteome strain B05.10. When I search UniProt for 'bos1 strain B05.10' I get the following entries

![image](https://github.com/PHI-base/curation/assets/11753634/c13d1c07-b6c5-43e9-9502-fb6d199a1aa4)


Maybe '[A0A384J5Y1](https://www.uniprot.org/uniprotkb/A0A384J5Y1/entry)' is the best entry to use. (Same AA length as Q8X215). I don't know which strain was used for Q8X215.

**Comment by CuzickA** [comment]
> I also did not find a way to annotate the osmosensitivity of the transformant strains, as I could not find an appropriate PHIPO term. Would it be interesting to annotate this phenotype too?

I think we can annotate these phenotypes.

I will need to create new PHIPO terms based on the FYPO terms
resistance to osmotic stress FYPO_0000851
sensitive to osmotic stress FYPO_0000270

I would place these in the PHIPO stress phenotype branch
![image](https://github.com/PHI-base/curation/assets/11753634/3da337ce-6464-45c8-95c8-599670ccbed6)

From the paper
![image](https://github.com/PHI-base/curation/assets/11753634/6f5211ee-8353-4f98-b8bc-d18518facd46)
@ValWood, do you also think it would be worth adding the FYPO terms for 
resistance to salt stress FYPO_0000852
sensitive to salt stress FYPO_0000271

or just make the appropriate annotations and add either 'NaCl' or 'Sorbitol' to the conditions?

**Comment by MPiovesana** [comment]
> > Uniprot ID query: authors do not provide a GenBank accession number for bos1, and several are returned upon search on Uniprot with the terms "bos1" and "Botrytis cinerea". However, a paper previously curated by me also described an altered genotype with the bos1 gene (GitHub ticket #129), and I used the same ID as used then (Q8X215; which was indicated by the authors of that paper).
> 
> Hmm... this is another tricky UniProt issue.
> 
> I think that ideally we want the UniProt Id associated with the reference proteome strain B05.10. When I search UniProt for 'bos1 strain B05.10' I get the following entries
> 
> ![image](https://user-images.githubusercontent.com/11753634/249131678-c13d1c07-b6c5-43e9-9502-fb6d199a1aa4.png)
> 
> Maybe '[A0A384J5Y1](https://www.uniprot.org/uniprotkb/A0A384J5Y1/entry)' is the best entry to use. (Same AA length as Q8X215). I don't know which strain was used for Q8X215.

@CuzickA that's great, I am happy to update the curation session with the suggested Uniprot ID. Shall I do it now or wait until new PHIPO terms are added?

**Comment by CuzickA** [comment]
Hi @MPiovesana, I've reactivated this session. Please could you have a go at making the osmotic stress annotations and add in the NTR resistance/sensitive to osmotic stress as required. Please note that unlike the chemical phenotypes we don't curate 'normal ...'.

**Comment by CuzickA** [comment]
> > > Uniprot ID query: authors do not provide a GenBank accession number for bos1, and several are returned upon search on Uniprot with the terms "bos1" and "Botrytis cinerea". However, a paper previously curated by me also described an altered genotype with the bos1 gene (GitHub ticket #129), and I used the same ID as used then (Q8X215; which was indicated by the authors of that paper).
> > 
> > 
> > Hmm... this is another tricky UniProt issue.
> > I think that ideally we want the UniProt Id associated with the reference proteome strain B05.10. When I search UniProt for 'bos1 strain B05.10' I get the following entries
> > ![image](https://user-images.githubusercontent.com/11753634/249131678-c13d1c07-b6c5-43e9-9502-fb6d199a1aa4.png)
> > Maybe '[A0A384J5Y1](https://www.uniprot.org/uniprotkb/A0A384J5Y1/entry)' is the best entry to use. (Same AA length as Q8X215). I don't know which strain was used for Q8X215.
> 
> @CuzickA that's great, I am happy to update the curation session with the suggested Uniprot ID. Shall I do it now or wait until new PHIPO terms are added?

You can do it now if you like as I've finished with this session for now :-). Do you think it also makes sense to update the other Bos1 curated publication that you were working on? Did they also use strain B05.10?

**Comment by MPiovesana** [comment]
> > > > Uniprot ID query: authors do not provide a GenBank accession number for bos1, and several are returned upon search on Uniprot with the terms "bos1" and "Botrytis cinerea". However, a paper previously curated by me also described an altered genotype with the bos1 gene (GitHub ticket #129), and I used the same ID as used then (Q8X215; which was indicated by the authors of that paper).
> > > 
> > > 
> > > Hmm... this is another tricky UniProt issue.
> > > I think that ideally we want the UniProt Id associated with the reference proteome strain B05.10. When I search UniProt for 'bos1 strain B05.10' I get the following entries
> > > ![image](https://user-images.githubusercontent.com/11753634/249131678-c13d1c07-b6c5-43e9-9502-fb6d199a1aa4.png)
> > > Maybe '[A0A384J5Y1](https://www.uniprot.org/uniprotkb/A0A384J5Y1/entry)' is the best entry to use. (Same AA length as Q8X215). I don't know which strain was used for Q8X215.
> > 
> > 
> > @CuzickA that's great, I am happy to update the curation session with the suggested Uniprot ID. Shall I do it now or wait until new PHIPO terms are added?
> 
> You can do it now if you like as I've finished with this session for now :-). Do you think it also makes sense to update the other Bos1 curated publication that you were working on? Did they also use strain B05.10?

@CuzickA That's great, I will update the Uniprot ID first and then attempt annotation of the osmotic stress phenotypes. Regarding the other Bos1 paper, I have just finished revisiting its curation session as it was left incomplete (due to genetic crosses question), and I have concluded we we are likely not able to curate it. That other paper is discussed in ticket #129 and I will update it with comments now.

**Comment by ValWood** [comment]
We have sensitive/resistance to salt stress, and sensitive/resistance to non-ionic stresses (like sorbitol, manitol etc).

So far, all of the genes annotated to sensitive to non-ionic stress are also annotated to sensitive to salt stress, so there may not be so much difference in the sensitivity profile.

It's difficult to call when to go more specific, as we don't know what the data will show over time. If in doubt I usually add. If it turns out not to be a useful split terms can always be merged later. In this case, the  difference might not be worth capturing

**Comment by MPiovesana** [comment]
@CuzickA The curation session has now been updated with the suggested Uniprot ID for the _bos1_ gene, and all genotypes have been accordingly linked to the correct ID. I also added the osmotic stress annotations by suggesting the new PHIPO terms **resistance to osmotic stress** and **sensitive to osmotic stress** as child terms of **resistance to stress** / **sensitive to stress**.

Despite mentioning that plates were supplemented with either sorbitol or NaCl, the authors do not specify which compound was used in each experiment, and therefore, I did not add these to the experimental conditions so far. Would it be better to omit them completely, or add both _+sorbitol_ and _+NaCl_? I think the latter would be misleading as it would imply both compounds were added at the same time to the growth medium, which is not the case. Thus, I have included the information regarding the addition of sorbitol and NaCl in the Comment section of genotype annotation for now.

**Comment by CuzickA** [comment]
> We have sensitive/resistance to salt stress, and sensitive/resistance to non-ionic stresses (like sorbitol, manitol etc).
> 
> So far, all of the genes annotated to sensitive to non-ionic stress are also annotated to sensitive to salt stress, so there may not be so much difference in the sensitivity profile.
> 
> It's difficult to call when to go more specific, as we don't know what the data will show over time. If in doubt I usually add. If it turns out not to be a useful split terms can always be merged later. In this case, the difference might not be worth capturing

Thanks @ValWood , I'll add the suggested terms.

**Comment by CuzickA** [comment]
> Despite mentioning that plates were supplemented with either sorbitol or NaCl, the authors do not specify which compound was used in each experiment, and therefore, I did not add these to the experimental conditions so far. Would it be better to omit them completely, or add both +sorbitol and +NaCl? I think the latter would be misleading as it would imply both compounds were added at the same time to the growth medium, which is not the case. Thus, I have included the information regarding the addition of sorbitol and NaCl in the Comment section of genotype annotation for now.

Maybe the authors grouped both the sorbitol or NaCl expt results together in table 3. Perhaps the same phenotypes were seen for each of the altered genotypes with each of these separate treatments. I'll also create the sensitive/resistance to salt stress, and sensitive/resistance to non-ionic stresses (like sorbitol, manitol etc) PHIPO terms. We can spilt the current annotations out and annotate with these terms.

**Comment by MPiovesana** [comment]
> > Despite mentioning that plates were supplemented with either sorbitol or NaCl, the authors do not specify which compound was used in each experiment, and therefore, I did not add these to the experimental conditions so far. Would it be better to omit them completely, or add both +sorbitol and +NaCl? I think the latter would be misleading as it would imply both compounds were added at the same time to the growth medium, which is not the case. Thus, I have included the information regarding the addition of sorbitol and NaCl in the Comment section of genotype annotation for now.
> 
> Maybe the authors grouped both the sorbitol or NaCl expt results together in table 3. Perhaps the same phenotypes were seen for each of the altered genotypes with each of these separate treatments. I'll also create the sensitive/resistance to salt stress, and sensitive/resistance to non-ionic stresses (like sorbitol, manitol etc) PHIPO terms. We can spilt the current annotations out and annotate with these terms.

I believe the authors did group the results in Table 3, but I could not find individual results for NaCl or sorbitol nowhere else in the paper. For this reason, I am not sure we can identify which ones were performed with one compound or the other to subsequently split the annotations with resistance to salt stress/non-ionic stress.

**Comment by CuzickA** [comment]
Hi @ValWood, I couldn't find a term for 'resistance to non-ionic stress' in FYPO.

**Comment by ValWood** [comment]
I think we only have sensitive to non-ionic stress right now. We haven't required resistance to non-ionic stress.

**Comment by CuzickA** [comment]
Question to Nichola 

I have a question about when to use the AE ‘alteration in archetype’.
 
Can we use it for annotations with fungicides that are NOT in the initial Chemical group of fungicide identified in your Supplementary file ‘Predictability of fungicide resistance’?
 
Eg for PMID:22912706, Fillinger et al., 2012 ‘Functional and structural comparison of pyrrolnitrin- and iprodione-induced modifications in the class III histidine-kinase Bos1 of Botrytis cinerea.’
 
As I understand it, Iprodione (in FRAC 2022 list) is a dicarboximide and pyrrolnitrin (not in FRAC 2022 list) is a phenylpyrrole. In your Supplementary file the information for Bos 1 is in this table ‘Table S5. Reported target-site mutations in Os1 associated with resistance to dicarboximide fungicides’. 
 
Do you think the annotations below are correct and useful to PHI-base users? 
In this case the Bc bos1 I365S AA substitution leads to increased resistance to iprodione but does not alter growth on pyrrolnitrin. The AE alteration in archetype does not capture the information that the bos1 I365S AA substitution was originally identified as being associated with resistance to dicarboximide fungicides. In the future the new automated AE for FRAC code group will help the user identify this ‘chemical group’ information, but in the case of pyrrolnitrin, it is not listed in the FRAC 2022 list so there will be no automated AE FRAC code entry for code 12 indicating that it is a phenylpyrrole. Do you think that the AE alteration in archetype should be removed from the pyrrolnitrin entry or is it still useful information in case of any examples of cross-resistance to different fungicides (in future curation sessions)?

![image](https://github.com/PHI-base/curation/assets/11753634/95b3320f-8224-4076-8050-61f60cab97f2)


Answer from Nichola

'The Archetype is for the gene rather than the fungicide, so I think we should use the AE field whenever the alteration is in that gene even if it is affecting sensitivity to different chemicals.'

**Comment by CuzickA** [comment]
Updated the AEs to include the author given name and FRAST name in brackets
eg
![image](https://github.com/PHI-base/curation/assets/11753634/144d1588-a4b2-40e6-8225-889a004f86c6)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

I365S; Bos1 (OS-1); BOTRCI
I365S, V239F; Bos1 (OS-1); BOTRCI
G278D; Bos1 (OS-1); BOTRCI
G415D; Bos1 (OS-1); BOTRCI
A493T; Bos1 (OS-1); BOTRCI
I365S, T581P; Bos1 (OS-1); BOTRCI
I365S, E529A; Bos1 (OS-1); BOTRCI
I365S, M427T; Bos1 (OS-1); BOTRCI

Straight forward to find in Nichola's S file in Table S5
![image](https://github.com/PHI-base/curation/assets/11753634/241659dc-4acf-4fd5-b163-625a45603076)
![image](https://github.com/PHI-base/curation/assets/11753634/e17bf4a9-d190-4ab2-9313-50dd1e0a44d1)
![image](https://github.com/PHI-base/curation/assets/11753634/0c908ccb-35ff-4605-9c18-2b75632ac51e)
![image](https://github.com/PHI-base/curation/assets/11753634/63d6e4c4-c579-4042-82ab-381f8af42da5)
![image](https://github.com/PHI-base/curation/assets/11753634/8fd81201-6065-4253-a932-384a431ed8e8)
![image](https://github.com/PHI-base/curation/assets/11753634/d1063655-e540-483c-8849-6b38b90fab4a)
![image](https://github.com/PHI-base/curation/assets/11753634/d98375ae-456b-4e41-a9c8-4f032d3b287a)
![image](https://github.com/PHI-base/curation/assets/11753634/cccdb18b-6aa9-437b-a5b5-379d644e5ee4)
![image](https://github.com/PHI-base/curation/assets/11753634/ed3b9187-6c48-4b3c-9b79-bd980763bb99)
![image](https://github.com/PHI-base/curation/assets/11753634/5a417ec7-dc1d-4321-88c2-37e54f19e09f)

**Questions for Nichola**
Is it alright to record double mutants? eg I365S, V239F; Bos1 (OS-1); BOTRCI
Is it sensible to use the author's target-site name as the main name and then the FRAST name in brackets? eg I365S; Bos1 (OS-1); BOTRCI

**Comment by CuzickA** [comment]
Is it alright to record double mutants? eg I365S, V239F; Bos1 (OS-1); BOTRCI 
YES

Is it sensible to use the author's target-site name as the main name and then the FRAST name in brackets? eg I365S; Bos1 (OS-1); BOTRCI
YES

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
