### ISSUE TITLE
PMID: 25758923 Functional analysis of the Fusarium graminearum phosphatome

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#146]
Curated by @MPiovesana.

https://canto.phi-base.org/curs/17124e4e388efe19

**Comment by MPiovesana** [comment]
The focus of this paper is to assess the phenotypes of mutant strains generated by deleting the phosphatases of _Fusarium graminearum_ in the wild type PH-1 background. Among the phenotypes assessed, the susceptibility of deletion strains to fungicides (FK506, carbendazim and JS399-19) is tested; however, these results are only presented in supporting material (Table S2). Of 71 deletion mutants analysed, only two displayed an altered phenotype to a fungicide treatment (**FG10302** and **FG09532**, which displayed sensitivity to FK506 (also known as tacrolimus). Therefore, I decided to only annotate the phenotypes associated with the FG10302delta and FG09532delta.

**Comment by MPiovesana** [comment]
**Uniprot IDs**: After identifying the reference proteome UP000070720 of _F. graminearum_ on Uniprot, I searched for FG10302 and FG09532. The following Uniprot IDs were returned with this search:
FG09532 = I1RYS3
FG10302 = I1S0R5

**Comment by MPiovesana** [comment]
**Curation of antifungal susceptibility phenotypes**: the sensitivity of deletion lines FG09532Δ and FG10302Δ to the antifungal tacrolimus was recorded with a new suggested PHIPO term (**sensitive to tacrolimus (FK506)**). I also recorded their normal growth on carbendazim with the new suggested term "**normal growth on carbendazim**". I could not locate the common name of the third antifungal tested (JS399-19); thus, I have not annotated the phenotypes associated with this compound (both lines display normal growth). Would it be relevant to add these annotations as well?

**Comment by MPiovesana** [comment]
**Other phenotypes**: I also curated other phenotypes associated with these single altered genotypes, including their reduced mycelial growth ("_decreased hyphal growth_"), reduced conidium production ("_decreased number of asexual spores_"), and altered production of DON (new suggested terms "_increased production of deoxynivalenol (DON)_" and "_abolished production of deoxynivalenol (DON)_").

**AC:** See below for DON

**Comment by MPiovesana** [comment]
**Metagenotype annotations**: the authors also test the pathogenicity of these deletion lines by infecting flowering wheat heads with conidial suspensions. I recorded the wt metagenotype control ("_presence of pathogen-associated host lesions_") and the altered metagenotypes ("_decreased extent of pathogen-associated host lesions_"). I am not sure if these are the best terms to describe the disease caused by _F. graminearum_ on wheat heads, but after searching the list of PHIPO terms, these seemed appropriate. 

The wheat cultivar used for this experiment is not provided by the authors, so I selected "unknown strain". Authors mention the assay was performed as described by Jiang et al, 2011, where I found details of experimental conditions; should I also consider the wheat cultivar used in this reference?

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by MPiovesana** [comment]
**NOTE**: throughout the text, typo instances are present where mutant strain FG0**95**32Δ is referenced as FG0**59**32 instead. Careful when reading text to avoid confusion.

**Comment by CuzickA** [comment]
I think these DON annotations need to move from pathogen phenotypes to PHI phenotypes as the pathogen was inoculated onto wheat kernels

![image](https://github.com/PHI-base/curation/assets/11753634/ccd56381-8b2e-4476-b426-5fc3e48be1b3)

Now changed to 
![image](https://github.com/PHI-base/curation/assets/11753634/1cd7b153-4020-4f67-ab82-064c79ec5415)

**Comment by CuzickA** [comment]
Session  now checked and edits made

AE alteration in archetype N/A as gene deletion study

Needs
1) PHIPO terms (added to PHIPO ticket)
2) PHI-ECO term (added to PHI-ECO term creator)

And then it will be ready to approve.

**Comment by CuzickA** [comment]
Hi @jseager7, I have a question about the PHI4 -> PHI5 data migration relating to this publication.

What happens when a publication is curated in both PHI4 and then a subset of the data is also curated in PHI-Canto? Which data will be displayed in PHI5?

**Comment by jseager7** [comment]
@CuzickA Currently the PHI-Canto curation supersedes all curation from PHI-base 4 for a publication. It may be technically possible to merge the curation, but this would have to be done on a case-by-case basis since it presumably won't be appropriate in all cases.

**Comment by CuzickA** [comment]
> @CuzickA Currently the PHI-Canto curation supersedes all curation from PHI-base 4 for a publication. It may be technically possible to merge the curation, but this would have to be done on a case-by-case basis since it presumably won't be appropriate in all cases.

Thanks @jseager7, it might be worth keeping a note in your transfer files that this publication may require a curated data merge.

**Comment by CuzickA** [comment]
PHIPO term added.

Session approved, closing ticket.

**Comment by CuzickA** [comment]
Added disease annotation

![image](https://github.com/PHI-base/curation/assets/11753634/7f931ac3-6fb1-4ec0-96f3-984a3da88e35)
