### ISSUE TITLE
PMID: 26220356 Mutation of G234 amino acid residue in candida albicans drug-resistance-related protein Rta2p is associated with fluconazole resistance and dihydrosphingosine transport

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#147]
Curated by @MPiovesana

**Comment by MPiovesana** [comment]
**Uniprot ID**: When searching Uniprot ID for "_RTA2_" and "_Candida albicans_", three entries are returned. The first two are reviewed entries, but they do not correspond to the RTA2 protein. The third entry, which is not reviewed, corresponds to the correct protein (confirmed by correct name and protein size; predicted 50.9 kDa as mentioned in the article). ID **Q59Q40** chosen.

**Comment by MPiovesana** [comment]
**UPDATED ON 17TH JULY FOLLOWING DISCUSSION OF ALLELE TYPES**:

**Genotype creation and annotations**: In this paper, authors test the effect of point mutations of conserved amino acids in the transmembrane domains of Rta2p by transforming mutant alleles into _Candida albicans_. The strain used as recipient for transformations is named **JXM101** (Table 1), which is reference strain RM1000 harbouring the deletion of both alleles of Rta2. Strain JXM101 is transformed with empty vector and a wild type copy of Rta2, and resulting strains are used as controls. Remaining mutant strains were generated as displayed in Table 1. 

I was slightly confused when deciding which strain to consider as control (the one to which other strains would be compared in order to choose a phenotype term). Despite being the recipient strain, JXM101 (untransformed) is not included in the antifungal assays (Table 2), which means it cannot be considered a control as we do not know its phenotypes. I then decided to pick **P-RTA2** (reconstituted JXM101 expressing a wild type copy of Rta2) as a control. For genotype annotations, I selected strains **M3** and **M10**, which are the ones on which authors focus the most along the paper, and which are used for _in vivo_ infection assays (Figure 2). 

Despite not mentioned by the authors, it can be inferred from the text that the WT sequence of _Rta2_ is amplified from a WT strain (probably RM1000) and point mutations are introduced by site directed _in vitro_ mutagenesis. Regardless of which WT strain was used for the amplification of the Rta2 gene, I believe allele type _amino acid substitution_ is the best option here, as this is **not** a case of alleles cloned from mutant strains being introduced into a WT recipient. As we do not know where in the genome alleles were inserted, **"ectopic"** was selected as expression level. The following genotypes were created:

**Rta2+ [Ectopic] (background rta2Δ)** = reconstituted JXM101 strain expressing wild type copy of Rta2
**Rta2-G158E(aaG158E)  [Ectopic] (background rta2Δ)** = JXM101 strain expressing mutant Rta2-G158E allele
**Rta2-G234S(aaG234S) [Ectopic] (background rta2Δ)** = JXM101 strain expressing mutant Rta2-G234S allele

Both altered single genotypes were annotated as _"sensitive to fluconazole"_, according to results displayed in Table 2. I only added one annotation per genotype, despite two experimental conditions (with and without CaCl2) being described in Table 2, as mutant strains display the same sensitivity phenotype compared to the control strain in both conditions.

**NOTE**: Single "wild type" control (reconstituted JXM101 strain) was only added to allow subsequent control metagenotype annotation.

**Comment by MPiovesana** [comment]
**Metagenotype annotations**: Authors tested the pathogenicity of mutant strains in comparison with reconstituted JXM101  using an _in vivo_ model of candidemia. Infected mice were treated with mock (NaCl) or fluconazole to assess the efficacy of the antifungal treatment to the disease caused by different strains. No differences were observed in the overall survival of infected mice without FLC treatment (Figure 2a); however, FLC treatment led to an increased survival of mice infected with strain M10 (Rta2-G234S) (Figure 2b). Thus, metagenotypes were annotated as follows:

**Rta2+ [Ectopic] + wild type Mus musculus** = PHIPO term "_survival of host organism with pathogen_"; **interaction_outcome** disease present (with and without fluconazole)

**Rta2-G158E(aaG158E) [Ectopic] + wild type Mus musculus** = PHIPO term "_survival of host organism with pathogen_"; **interaction_outcome** disease present; **infective_ability** unaffected pathogenicity (with and without fluconazole)

**Rta2-G234S(aaG234S) [Ectopic] + wild type Mus musculus** = PHIPO term "_survival of host organism with pathogen_"; **interaction_outcome** disease present; **infective_ability** unaffected pathogenicity (without fluconazole) **AND** **infective_ability** reduced virulence (+ fluconazole)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Link to session https://canto.phi-base.org/curs/bda2c91480dda17a

**Comment by CuzickA** [comment]
No new strains to add.

**Comment by CuzickA** [comment]
Next: I need to think about what the pathogen wild type control is and what to compare the mutant with - see Maiara's comments above.

**Comment by CuzickA** [comment]
> Next: I need to think about what the pathogen wild type control is and what to compare the mutant with - see Maiara's comments above.

I agree with Maiara's comments above and which control strains to use.

![image](https://github.com/PHI-base/curation/assets/11753634/2ab5033e-9b44-4d75-84f0-3ef02550a90e)

AE alteration in archetype is N/A as target not on FRAST list

**Comment by CuzickA** [comment]
PHI phenotypes look ok. Made a couple of edits, added 30dpi, added AE penetrance to 2 annotations WT and mutant showing reduced virulence, changed evidence from 'other' to 'Macroscopic observation (quantitative observation)' as this is a count of how many mice live and die.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/e07f4c8f-6e89-4519-a7e6-96227862ecd8)

Added a disease annotation

**Comment by CuzickA** [comment]
Session complete.

Approved and closing ticket.
