### ISSUE TITLE
PMID24119086: Site-directed mutagenesis of the P225, N230 and H272 residues of succinate dehydrogenase subunit B from Botrytis cinerea highlights different roles in enzyme activity and inhibitor binding

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#149]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/7d1ebc9d6607072a

**Comment by jingluodatacurator** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, before I start checking this older curation session, please could you
1) email me your highlighted PDF
2) add a short summary of the expt to this GitHub, including how you found the UniProt ids etc
3) double check the annotations with your new additional curation knowledge and personal curation checklist

Please let me know when you've done the above and then I'll check the session. Thanks

**Comment by jingluodatacurator** [comment]
Summary of expt.:

We confirmed, by site-directed mutagenesis of the sdhB gene, that each of the mutations identified in field strains conferred resistance to boscalid in B. cinerea, and in some cases cross-resistance to other SDHIs (fluopyram, carboxin). Enzyme inhibition studies showed that the studied modifications (SdhB_P225T/L/F, N230I, H272Y/R/L) affected the inhibition of SDH activity by SDHIs, directly contributing to resistance. Our results confirm the importance of H272, P225 and N230 for carboxamide binding.

Modifications of P225 and N230 conferred resistance to the four carboxamides tested (boscalid, fluopyram, carboxin, bixafen). Modifications of H272 had differential effects on the susceptibility of SDH to SDHIs. SdhBH272L,
affected susceptibility to all SDHIs, SdhBH272R conferred resistance to all SDHIs tested except fluopyram, and SdhBH272Y conferred fluopyram hypersensitivity.

(sdhB site-directed mutagenesis)
The sdhB mutations (Table S1) identified by (Leroux et al., 2010) and the sdhBP225F mutation (Stammler et al.,
2007) were introduced individually into the boscalid sensitive B05.10 strain by the gene replacement strategy
described in the Experimental procedures. Briefly, the B05.10 sensitive recipient strain was transformed with the replacement cassette described in Fig. 1A. Two independent transformants were tested per sdhB allele for all experiments. The sdhBwt allele was introduced to serve as control and is referred to here as the wild type (WT).

(All identified sdhB mutations confer resistance to at least one class of SDHIs)
We determined EC50 values and the corresponding resistance factor (RF = EC50 mutant/EC50 WT) for each mutant strain, for representative SDHI molecules from three chemical families: boscalid for pyridine carboxamides, fluopyram for pyridinyle-ethyl-benzamides and carboxin for oxathiin carboxamides (Fig. 1E). The data are summarized in Table 1. In conclusion, all the sdhB mutations identified in natural resistant strains confer resistance to boscalid. Some also confer various degrees of resistance to other SDHIs, such as carboxin and fluopyram. The RFs calculated for the gene replacement mutants (Table 1) were of a similar order of magnitude to those calculated for field mutants (Table 1; Leroux et al., 2010). Our results, thus, indicate that the resistance levels and patterns of field strains can be accounted for fully by these sdhB mutations.

**Comment by jingluodatacurator** [comment]
Uniprot ID: GenBank accession number AY726618 was provided by the author, which was used to locate the ID Q3ZMH5 from Uniprot.

Strains: the wild-type strain B05.10 (boscalid sensitive) was used as the recipient strain for ~transformation~ gene replacement expt with a sdhb construct containing site-directed mutations observed in boscalid-resistant field strains.
(AC has updated this comment)

**Comment by jingluodatacurator** [comment]
Genotype creation:

P225F, P225L, P225T, N230I, H272L have been curated for Boscalid, Fluopyram, Carboxin, Bixafen;
H272R has been curated for Boscalid, Carboxin, Bixafen;
H272Y has been curated for Boscalid, Carboxin, Bixafen, Fluopyram (for hypersensitivity).

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks

https://canto.phi-base.org/curs/7d1ebc9d6607072a

**Comment by CuzickA** [comment]
@jingluodatacurator, phenotype annotations look good thanks.

**Comment by CuzickA** [comment]
I have added a GO MF annotation
![image](https://github.com/PHI-base/curation/assets/11753634/515502b5-3838-4ec3-b80d-f0d9dd1115b7)

**Comment by CuzickA** [comment]
**AC next steps**
1) try and add AE alteration in archetype

**Comment by CuzickA** [comment]
**AE alteration in  archetype**

From Nicola's table
![image](https://github.com/PHI-base/curation/assets/11753634/5b6639c2-3e11-46af-a9b0-1db4825d307a)
![image](https://github.com/PHI-base/curation/assets/11753634/71da5287-dd70-42e2-ad69-bfd598480f00)


Botrytis cinerea
sdhB(P225F)[Not assayed] 'P230F; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/5dc697e3-d610-425c-a974-4e65b8a7c4da)

sdhB(P225L)[Not assayed] 'P230L; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/bd8af395-0b71-49bd-8713-30f163ddf953)


sdhB(P225T)[Not assayed] 'P230T; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/7f45e27e-314e-4885-aecd-179000a17db7)


sdhB(N230I)[Not assayed] 'N235I; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/508d2baf-255c-482d-ae0b-ad94aacef73b)


sdhB(H272L)[Not assayed] 'H277L; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/a9cf952a-85e6-455c-99bb-a971d51c29d3)

sdhB(H272R)[Not assayed] 'H277R; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/77f4afe9-2d14-4ed0-8ee2-a079abeab1ef)


sdhB(H272Y)[Not assayed] 'H277Y; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/8a24c04b-3a85-4e34-9030-e06a07da2e71)

**Comment by CuzickA** [comment]
Next steps

1) check AE alteration in archetype with Nicola

Then session ready to approve

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
