### ISSUE TITLE
PMID: 20019793 Fungicide-driven evolution and molecular basis of multidrug resistance in field populations of the grey mould fungus Botrytis cinerea

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#150]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/95bccb684864c7d6

**Comment by MPiovesana** [comment]
In this paper, authors investigate the molecular basis of the multidrug resistance phenotypes displayed by _Botrytis cinerea_ strains named **MDR1**, **MDR2** and **MDR3**. Upon identifying that these phenotypes are associated with the overexpression of drug efflux pumps _atrB_ and _mfsM2_, authors generate deletion and overexpression/ectopic lines to confirm the involvement of these genes in drug resistance. Authors also identify _mrr1_ as a transcriptional regulator responsible for promoting expression of atrB in MDR1 and MDR3. The genotypes of deletion/ox/transformant mutants were annotated in PHI-Canto (https://canto.phi-base.org/curs/95bccb684864c7d6#).

**Comment by MPiovesana** [comment]
**Uniprot IDs**: IDs were found as follows:
_atrB_: search Uniprot with gene and species name returned 4 entries, 2 of which for the _atrB_ gene. I identified entry **Q9UW03** as having been previously used for curation in PHI-base, in addition to being linked to strain B05.10 which is used as a reference in this study. I therefore selected this ID for this curation session.

_mfsM2_: authors provide an accession number (BofuT4_P024110.1) which could be used in ENSEMBL to locate ID CCD50602. When searching Uniprot with the ENSEMBL code, entry **G2YFQ4** was retrieved and selected for curation;

AC: I searched genbank for 'BofuT4_P024110.1' and got https://www.ncbi.nlm.nih.gov/nuccore/325974234 and then did' find' for 'BofuT4_P024110.1'

![image](https://github.com/PHI-base/curation/assets/11753634/a0f0d18b-eaef-433b-8d4e-9d5cd300ca1f)

'BofuT4_P024110.1' is old locus tag, new locus tag is 'BofuT4P13000012001' and associated uniprot G2YFQ4.


_mrr1_: similar to the process described for _mfsM2_, accession number BofuT4_P063510.1 provided by the authors was used to retrieve the ENSEMBL code for this gene, then used for the Uniprot search. ID **G2XSW8** was selected for curation.

AC: https://www.ncbi.nlm.nih.gov/nuccore/325974170
![image](https://github.com/PHI-base/curation/assets/11753634/601e381a-bfa2-49f0-b894-9cf7ce9c4334)
uniprot G2XSW8

**Comment by MPiovesana** [comment]
**Strains**: strains MDR1, MDR2 and B05.Hyg-3 were added manually as the recipient strains for transformations.

**Comment by MPiovesana** [comment]
**Genotypes**: 

**atrBΔ**: deletion of _atrB_ in MDR1 background (strain D06.5-16 chosen as representative, results displayed in Fig. 6);

**mrr1Δ**: deletion of _mrr1_ in MDR1 background (strain D06.5-16 chosen as representative, results displayed in Fig. 6);

**mfsM2Δ**: deletion of _mfsM2_ in MDR2 background (strain D06.7-27 according to materials and methods).

**mfsM2+[Ectopic]**: _other_ allele where _mfsM2_ is expressed under the control of the oliC promoter in B05.Hyg-3 background (to replicate overexpression of _mfsM2_ observed in MDR2); authors do not explain from which strain mfsM2 sequence was amplified from, but I think it can be assumed that it was from B05.Hyg-3 as this is the WT strain used in the study. Thus, the genotype here must reflect the ectopic expression of extra copies of mfsM2. _Endogenous mfsM2 present_ added in background.

AC- changing ectopic to overexpression.

**mrr1 transformant (D06.7-27-mrr1(V575M))[Overexpression]**: transformant allele where the mutant _mrr1_ obtained from a MDR1 strain D06.7-27 (harbouring V575M mutation) is overexpressed in the B05.Hyg-3 background (to replicate MDR1 background). _Endogenous mrr1 present_ added in background.

**Comment by MPiovesana** [comment]
**Genotype annotations**:

Given that the authors test the strains susceptibilities to several fungicides, I have limited the annotations to two fungicides per genotype to restrict the number of annotations. This way, representative annotations were made which describe the overall phenotype observed for each strain to various fungicides. New child terms **"sensitive/resistant to cyprodinil"** were suggested.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Added strains de57d94

**Comment by CuzickA** [comment]
Added GO MF annotations

![image](https://github.com/PHI-base/curation/assets/11753634/3dc85f64-ca94-48d3-a595-bba2305cd6ee)

**Comment by CuzickA** [comment]
AE alteration in archetype is N/A

This session is just waiting for new PHIPO and PHI-ECO terms and will then be ready to approve.

**Comment by CuzickA** [comment]
Added terms. Approved session. Closing ticket.
