### ISSUE TITLE
PMID: 2946938 Cloning and characterization of the gene for beta-tubulin from a benomyl-resistant mutant of Neurospora crassa and its use as a dominant selectable marker

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#151]
Curated by @MPiovesana.
https://canto.phi-base.org/curs/2d1c70d066ad8703

**Comment by MPiovesana** [comment]
Straightforward curation of short paper describing the cloning of a mutant allele of _β-tubulin_ from _Neurospora crassa_ associated with benomyl resistance. A lambda clone containing the mutated _β-tubulin_ (point mutation leading to aa substitution of Phenylalanine 167 with a Tyrosine) was introduced in the benomyl-sensitive strain 43a, and resistant transformants were selected on agar plates. Experiment is described on text only (page 2455), no figure.

**Comment by MPiovesana** [comment]
**Uniprot ID**: search with gene and species name returned several entries, the first of which (**P05220**) a reviewed entry for the correct protein (447 aa). This ID was selected for this curation session.

AC: also same uniprot used in https://github.com/PHI-base/curation/issues/174

**Comment by MPiovesana** [comment]
**Genotype**: strain 43a was added manually. A **transformant** allele was created, the _β-tubulin_ gene from resistant strain Bml511(r)a was inserted in strain 43a for ectopic expression. Allele was described as **βtub transformant (Bml511(r)a-βtub(F167Y))** to represent origin of allele and mutation. **Ectopic** was selected to describe expression level. **Endogenous βtub present** was added to background.

**Comment by MPiovesana** [comment]
**Genotype annotation**: PHIPO term **resistance to benomyl** was selected to annotate the mutant genotype. Text on page 2455 was referred to in annotation.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Approved, closing ticket

**Comment by CuzickA** [comment]
Also added AE alteration in archetype
![image](https://github.com/PHI-base/curation/assets/11753634/11e76870-13f2-4a65-aac6-ee9b549370d9)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F167Y; β-tubulin; ASPEND

Straight forward to find in Nichola's S file in Table S1
![image](https://github.com/PHI-base/curation/assets/11753634/ba9b2283-82dc-4202-a5b6-54f3eaa14db1)
![image](https://github.com/PHI-base/curation/assets/11753634/fbcdcb57-0445-4b90-a714-38c6d7b3f63f)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
