### ISSUE TITLE
PMID: 10919801 Tandem Repeat of a Transcriptional Enhancer Upstream of the Sterol 14α-Demethylase Gene (CYP51) in Penicillium digitatum

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#152]
Curated by @MPiovesana.
https://canto.phi-base.org/curs/1e8f09364def576c#

**Comment by MPiovesana** [comment]
In this papers authors identify a tandem repeat in the promoter region of the _CYP51_ gene of DMI-resistant strains of _Penicillium digitatum_. This tandem repeat includes five copies of a 126 bp sequence, which is present as a single copy in the promoter of DMI-sensitive strains, such as **PD5**. Authors test whether the expression of extra copies of the _CYP51prom::CYP51_ amplified from both PD5 and a DMI-resistant strain (LC2) is capable of inducing increased resistance to fungicides when introduced in PD5 cells.

**Comment by MPiovesana** [comment]
**Uniprot ID:** accession number AB030178 provided by the authors is used to locate the _CYP51_ from PD5 in Uniprot (as PD5 is the reference and recipient strain). ID **Q9P340** is located and selected for curation session.

**Comment by MPiovesana** [comment]
**UPDATED FOLLOWING TRANSFORMANT ALLELE DISCUSSIONS:**

**Genotypes and annotations:**
Genotypes were created as described:
**CYP51prom::CYP51+ [Ectopic]**: expression of _CYP51prom::CYP51_ from PD5 in PD5 cells; allele type _other_ was selected as transformant is not suitable here (origin of the sequence same as recipient strain);

**CYP51prom::CYP51 transformant (LC2-CYP51prom(5x126bp tandem repeat)::CYP51) [Ectopic]**: expression of _CYP51prom::CYP51_ from LC2 in PD5 cells; 126 bp tandem repeats in promoter included in allele description. 

I considered choosing Ectopic as expression level to describe the expression of the extra copies of the gene; however, authors quantify expression levels of _CYP51_ and observe a slight increase for _CYP51prom::CYP51+_ and a more significant increase for lines expression _CYP51prom::CYP51 transformant_, so I believe **overexpression** is appropriate here. **Endogenous CYP51 present** was added to background.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by MPiovesana** [comment]
Genotypes were annotated with terms:
**resistance to fenarimol**
**resistance to triflumizole** (suggested)
**resistance to bitertanol** (suggested)
**resistance to pyrifenox** (suggested)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by MPiovesana** [comment]
**Note**: @CuzickA here is an example of a paper where I would use allele type "transformant" to describe a genotype where a promoter::gene sequence is introduced into the same strain from where it was amplified (PD5-CYP51prom::CYP51 introduced in PD5 cells). The transformation results in extra copies of the sequence in the genome (not gene replacement). I am not sure which other allele type we would use here otherwise. This can be a good example for discussion.

**Comment by CuzickA** [comment]
Genotypes
![image](https://github.com/PHI-base/curation/assets/11753634/b49e8a58-97cf-4479-8275-fa192deaf550)


Changed to 


![image](https://github.com/PHI-base/curation/assets/11753634/75abc60b-1dd7-4404-9f0b-8b983e21ad53)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

**Questions for Nichola**

I'm not sure about adding the AE alteration in archetype here, need to follow up with Nichola.

I could use
Non-coding region; Cyp51A; ASPEFU
or
Non-coding region; Cyp51B; SEPTTR

It is unclear as Penicillium digitatum gene is 'Cyp51'.
The alteration in the promoter can be captured using 'Non-coding region'

**Comment by CuzickA** [comment]
New terms added, session approved. leaving ticket open as need to follow up with Nichola about adding the AE alteration in archetype here (see comment above).

**Comment by CuzickA** [comment]
Use FRAST to determine if Cyp51A or B

**Comment by CuzickA** [comment]
From the publication
'Nucleotide sequence accession numbers. The sequences of PdCYP51 from
PD5 and LC2 are available under GenBank accession numbers AB030178 and
AB030179, respectively.'

Look up AB030178 in Genbank gives https://www.ncbi.nlm.nih.gov/nuccore/AB030178

Created AA FASTA file in notepad.

Tried to use FRAST option for 'automatic' input to see whether PdCYP51 closer to Cyp51 A or B. However, FRAST didn't work. No results were shown. Double checked method using info from https://github.com/PHI-base/curation/issues/51 and this example did work.

 We still don't know whether to use Cyp51A or Cyp51B.

**Comment by CuzickA** [comment]
After discussion with Nichola
1) Paper https://academic.oup.com/g3journal/article/12/11/jkac249/6709346 states that Pd has Cyp51A and Cyp51B.
2) Find genbank ids for Pd Cyp51A and Cyp51B in this paper and obtain AA sequences
3) For each, do Blast2seq to compare against Cyp51 in curated publication. As same species, expect either Cyp51A or B to have 100% match to curated publication Cyp51.

**Comment by CuzickA** [comment]
Supplementary Table 2 from https://academic.oup.com/g3journal/article/12/11/jkac249/6709346 PMID: 36130263

![image](https://github.com/PHI-base/curation/assets/11753634/0ba9d3b2-f114-4b42-bac6-d77f96f93822)
![image](https://github.com/PHI-base/curation/assets/11753634/8d2f0d62-dfdc-480e-b5e9-064704163cf8)

Pd Cyp51A XP_014532172.1 https://www.ncbi.nlm.nih.gov/protein/XP_014532172.1
Pd Cyp51B XP_014538931.1 https://www.ncbi.nlm.nih.gov/protein/XP_014538931.1

**Comment by CuzickA** [comment]
**Blast2seq**
https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&PROGRAM=blastp&BLAST_PROGRAMS=blastp&PAGE_TYPE=BlastSearch&BLAST_SPEC=blast2seq

Compare 
1) 'PdCyp51 PMID 10919801' with 'PdCyp51A PMID 36130263'
2) 'PdCyp51 PMID 10919801' with 'PdCyp51B PMID 36130263'

![image](https://github.com/PHI-base/curation/assets/11753634/41684f38-ce72-4a9d-8f2c-de0db6610d63)

1)
Enter 
'PdCyp51 PMID 10919801' AA FASTA file (copy and paste) in 'Enter query sequence' and 'PdCyp51A PMID 36130263' AA FASTA file (copy and paste) in 'Enter Subject Sequence'.  No change to any settings, hit 'BLAST'
![image](https://github.com/PHI-base/curation/assets/11753634/1f98b04c-3806-407e-88b0-62b75b194c44)

![image](https://github.com/PHI-base/curation/assets/11753634/48b2ec45-b130-4cee-8099-c38a65af8096)
![image](https://github.com/PHI-base/curation/assets/11753634/fc38ad1a-c62a-4cf3-9979-c6a21a6567ab)


2)

Enter
'PdCyp51 PMID 10919801' AA FASTA file (copy and paste) in 'Enter query sequence' and 'PdCyp51B PMID 36130263' AA FASTA file (copy and paste) in 'Enter Subject Sequence'. No change to any settings, hit 'BLAST'


![image](https://github.com/PHI-base/curation/assets/11753634/f9b8677f-0fd9-4bfd-9952-bfe64b647cd8)
![image](https://github.com/PHI-base/curation/assets/11753634/a090ea0b-5bbd-4268-89c9-7dd485d3b034)
![image](https://github.com/PHI-base/curation/assets/11753634/5418446a-ef1f-47b8-b336-bebfba828dfb)

**Conclusion**

PdCyp51 from PMID 10919801 is PdCyp51A

**Comment by CuzickA** [comment]
No need for FRAST as genotype has an alteration in the promoter which can be captured using 'Non-coding region'

Two genotypes
CYP51+[Overexpression]
CYP51 transformant(LC2-CYP51promoter(5x126bp tandem repeat)::CYP51)[Overexpression]

AE added to both
'Non-coding region; Cyp51 (Cyp51A); ASPEFU'

**Next steps**
1) Check AE with Nichola
2) Then session ready for approval

**Comment by CuzickA** [comment]
AE checked by Nichola - looks fine.

Approving session and closing ticket.
