### ISSUE TITLE
PMID: 12612806 Characterization of spontaneous mutants of Magnaporthe grisea expressing stable resistance to the Qo-inhibiting fungicide azoxystrobin

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#153]
Curated by @MPiovesana.
https://canto.phi-base.org/curs/0f7eed243059bf18

**Comment by MPiovesana** [comment]
Straightforward paper where authors generate spontaneous laboratory mutants of _Magnaporthe grisea_ resistant to azoxystrobin. Mutants are derived from WT strain 4091-5-8, and mutations on the target gene _cytochrome b_ are identified (G143A and G143S). Authors also compare conidial production (results not shown) and stability of the resistance phenotype by testing the germination of spores derived from necrotic lesions following infection of barley leaves (Table 2). Results relevant for curation (resistance to antifungal) are shown in Table 1. Mutant M-145 (inhibited alternative oxidase) is used as a control.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors provide GenBank accession number for _cytb_ of _M. grisea_ (X87999) which was used to identify Uniprot ID (Q36504).

**Comment by MPiovesana** [comment]
**Genotype creation and annotation:**
Pathogen genotypes were created by selecting **amino acid substitution** and expression level **Not assayed** as follows:
**cytb(aaG143A)**
**cytb(aaG143S)**

A single annotation was created for each genotype based on the chemical resistance phenotype displayed:
**PHIPO term:** resistance to azoxystrobin
**Evidence code:** cell growth assay
**Conditions:** agar plates, standard temperature, 6 days post inoculation, +azoxystrobin

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
> Uniprot ID: authors provide GenBank accession number for cytb of M. grisea (X87999) which was used to identify Uniprot ID (Q36504).


I'm a bit confused with the pathogen species name here.

The UniProt id Q36504 is for Pyricularia grisea (Magnaporthe grisea)

However in NCBITaxon for the WT strain 4091-5-8, the species is Pyricularia oryzae (Magnaporthe oryzae)(https://www.uniprot.org/taxonomy/318829)
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=318829
![image](https://github.com/PHI-base/curation/assets/11753634/143341c2-643e-4926-ac5e-47df5cf0f8fc)

rather than this option
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=148305
![image](https://github.com/PHI-base/curation/assets/11753634/73bd4e5a-7399-4a17-a32f-481cb1f7d048)

**Comment by CuzickA** [comment]
It may be better to use a UniProt id identified by searching for 'cytb Pyricularia oryzae'. Several non-reviewed entries are available - first entry is '[A0A089QDC9](https://www.uniprot.org/uniprotkb/A0A089QDC9/entry)'
![image](https://github.com/PHI-base/curation/assets/11753634/41e7ed15-9309-47fb-a948-969100db6305)

Not changed UniProt yet. Will continue checking session first.

**Comment by CuzickA** [comment]
pathogen phenotype annotations look fine

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/9375baac-f83d-4a45-86ee-00cbbba7206a)

Might need to add new strain to the strain list - unless this strain does not below with the pathogen species here (see above uniprot query)

**Comment by CuzickA** [comment]
strain name linked to Mo on strain list
![image](https://github.com/PHI-base/curation/assets/11753634/76c84b7f-ace0-4496-8a91-397b2ca7627b)

**Comment by CuzickA** [comment]
This has provided more evidence in favour of changing the uniprot id to cytB Mo

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/6c936e4a-0ce8-48f3-b903-69fada86a23c)

I have now swapped over the UniProt so that we have the correct species name for cytb. The strain is already available.

I have remade the genotype and transferred the annotations

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Info not in Nichola's S file or in Mair et al 2016 (for Mo, several entries for G143A, archetype species is Zymoseptoria tritici)

Need to try FRAST


Magnaporthe oryzae
cytb(aaG143A)[Not assayed]
cytb(aaG143S)[Not assayed]

**Comment by CuzickA** [comment]
Using AA FASTA from UniProt entry https://www.uniprot.org/uniprotkb/A0A089QDC9/entry

alignment against cytb Zymoseptoria tritici

![image](https://github.com/PHI-base/curation/assets/11753634/7ebddb48-9db9-415b-a9a8-e37b4e31fd83)

Magnaporthe oryzae
cytb(aaG143A)[Not assayed] 'G143A; CytB; SEPTTR'
cytb(aaG143S)[Not assayed] 'G143S; CytB; SEPTTR'

![image](https://github.com/PHI-base/curation/assets/11753634/660d9512-1c07-4b88-b521-b6cb19cac2c5)

**Comment by CuzickA** [comment]
**Next steps**

1) check AE alteration in archetype with Nichola

Then session will be ready to approve

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
