### ISSUE TITLE
PMID:11418514 Resistance to itraconazole in Aspergillus nidulans and Aspergillus fumigatus is conferred by extra copies of the A. nidulans P-450 14alpha-demethylase gene, pdmA.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#154]
Curated by @MPiovesana
https://canto.phi-base.org/curs/bf15e81bf1ab6473

**Comment by MPiovesana** [comment]
In this paper, the wild type strain GR5 of _Aspergillus nidulans_ is transformed with an _A. nidulans_ genomic library (autonomous non-integrating plasmid library created with genomic DNA from strain R153; strain origin is not mentioned in the paper, but in the reference where library creation is described - Osherov and May, 2000) with the aim to identify ORFs which confer resistance to the antifungal itraconazole. Itraconazole-resistant transformants were found to carry multiple copies of a plasmid harbouring the P-450 14-alpha demethylase gene _pdmA_, and plasmid eviction was associated with loss of antifungal resistance.

**Comment by MPiovesana** [comment]
**Uniprot ID:** the Uniprot ID of _pdmA_ of _A. nidulans_ (**Q9P462**) was identified by searching UniprotKB with the GenBank accession number provided in the text (AF266481).

**Comment by MPiovesana** [comment]
**Genotypes and annotations:**
A **transformant** allele was created and named **pdmA transformant (R153-pdmA)**, to indicate the expression of the pdmA gene derived from strain R153 in the transformed strain. "Ectopic" was selected under Expression level. **Endogenous pdmA present** was added in background (confirmed by Southern blot experiment in Fig 3).

AC- I think 'overexpression' is better than 'ectopic' in this case. I have changed genotypes.
Text from abstract
![Uploading image.png…]()

**Comment by MPiovesana** [comment]
PHIPO term **"normal growth on amphotericin B"** was suggested". Terms **"resistance to itraconazole"** and **"resistance to fluconazole"** were also used to annotate this genotype, all according to the results presented in Table (table is not numbered, but it is the only table in the paper so can be easily located).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
I need to add new strain 'GR5' to Aspergillus nidulans in pathogen species list

Now done ec03253

**Comment by CuzickA** [comment]
Pathogen phenotype annotations look fine

**Comment by CuzickA** [comment]
Added GO MF
![image](https://github.com/PHI-base/curation/assets/11753634/12fae249-2a53-4a62-99a1-c6afa5ae6745)

**Comment by CuzickA** [comment]
AE alteration in archetype is N/A as PdmA is not a FRAST listed target site (maybe could be similar to cyp51??) and no sequence difference was recorded in the genotype.

Session approved

Closing ticket
