### ISSUE TITLE
PMID:15917566 Targeted gene disruption of the 14-alpha sterol demethylase (cyp51A) in Aspergillus fumigatus and its role in azole drug susceptibility.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#155]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/677cbb5161c74ea6

**Comment by MPiovesana** [comment]
The _cyp51A_ gene of _Aspergillus fumigatus_ strain CM-237 was disrupted by a _hygromycin B_ resistance cassette (Figure 1), generating mutant CM-A8. Two clinical isolates of _A. fumigatus_ were also subjected to the gene disruption protocol. The disruption mutant displayed increased susceptibility to azole fungicides, notably **fluconazole** and **ketoconazole** given that the wild type parental strain is intrinsically resistant to both chemicals. The mutation does not affect the pathogenicity of _A. fumigatus_ when infecting mice (Figure 2).

**Comment by MPiovesana** [comment]
**Uniprot ID:** _cyp51A_ of _A. fumigatus_ was readily identified in UniprotKB; ID **Q4WNT5** has also been used previously in other curation sessions.

**Comment by MPiovesana** [comment]
**Genotype creation and annotations:**
To curate the disruption of the _cyp51A_ gene, strain CM-237 was selected and a disruption allele was created, named **cyp51A-(gene disruption)**. Expression levels was selected as **Not assayed**.

With regards to genotype annotations, the terms **sensitive to fluconazole** and **sensitive to ketoconazole** were used. Authors also test the susceptibility of wt and mutant strains to other fungicides; however, as the wt strain is not intrinsically resistant to those, in contrast to FLC and KTC, the differences in susceptibility between wt and mutant are much smaller for the other compounds, and I believe they do not need to be annotated.

**Comment by MPiovesana** [comment]
Authors also disrupt the _cyp51A_ gene of two clinical isolates, and observe similar effects on the susceptibility of these to FLC and KTC. However, as these are not references strains, I thought it would unnecessary to annotate their genotypes. Is that ok?

**Comment by MPiovesana** [comment]
**Metagenotype creation and annotation:**
Two metagenotypes were created in order to curate the infection assay described in the paper:

_cyp51A+_[WT level] and wild type _Mus musculus_ (Unknown strain)
_cyp51A-(gene disruption)_[Not assayed] and wild type _Mus musculus_ (Unknown strain)

Both the control and altered metagenotypes were annotated with the PHIPO term **death of host organism with pathogen**, and **delivery mechanism: pathogen spore inoculation** was selected under Conditions. The altered metagenotype was also annotated with extensions **compared_to_control** and **infective_ability unaffected pathogenicity**, while both metagenotypes were annotated with extension **interaction_outcome disease present**.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Hi @ValWood, I don't think I have curated many 'disruption' genotypes before. I can find an example with a t-dna insertion in https://github.com/PHI-base/curation/issues/24 where the genotype looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/8159b0c6-20b2-475e-89f0-1278fb2edd31)


Currently, in this chemistry paper the disruption genotype is
![image](https://github.com/PHI-base/curation/assets/11753634/60451e60-9eda-4887-9e00-f90d52e6470e)


Do you think that it would be better modeled as
'Cyp51A::HPH cassette (disruption) not assayed'?

![image](https://github.com/PHI-base/curation/assets/11753634/d3f2209e-b4e6-4872-b367-3172cfd22db6)

**Comment by ValWood** [comment]
That makes sense,
Val

**Comment by CuzickA** [comment]
Genotype now updated
![image](https://github.com/PHI-base/curation/assets/11753634/4b8e94bc-2cd4-4e2c-8c17-ddecf0211ddd)

**Comment by CuzickA** [comment]
Session now likes this

![image](https://github.com/PHI-base/curation/assets/11753634/43c64b3d-71b0-41e7-b753-7be4ebe5aee6)

AE alteration in archetype is N/A.

Approving session and closing ticket.
