### ISSUE TITLE
When to use transformant allele?

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#157]
Ticket to discuss use of "transformant" allele type.

**Comment by MPiovesana** [comment]
A question has been discussed repeatedly by the chemistry curation team regarding the use of the allele type "**transformant**". Currently, allele types have been assigned following the reasoning below:

**1.** When a mutant allele is created by modifying the wild type copy of a gene with site-directed in vitro mutagenesis, for example, and subsequently introduced in the _same strain_ where the original wild type gene was amplified from: 

    If the gene is introduced via _gene replacement/homologous recombination_, therefore, replacing the wild type allele in its native genomic locus = allele type is based on mutation type; for example, an allele with a point mutation is assigned "_amino acid substitution_", an allele with a deletion is assigned "_deletion_", and so on. Resulting genotype is the **same** of the parental recipient strain with the sole exception of mutation introduced.

    If the gene is introduced in the recipient strain **NOT** by homologous recombination, and is either _inserted randomly in the genome_ or expressed from a _non-integrative plasmid_ = allele type "**transformant**" is assigned. Resulting genotype is **NOT** the same of the parental recipient strain as endogenous wild type gene is present (unless previously disrupted/deleted) and transgene is inserted in an often unknown/random location in the genome, or from a non-integrative plasmid maintained with selection pressure (eg antibiotics).

2. When an altered genotype is created by inserting an allele from _strain A_ into _strain B_: we are inclined to always designate such genotypes with allele type "**transformant**", as the allele being introduced is derived from a different strain, rather than from the recipient strain. Does this make sense? Should "transformant" be selected regardless of the transformation strategy used by authors (homologous recombination, traditional genetic transformation, etc)? 

I guess the main question here is: _on what grounds should we decide whether an allele is of the "transformant" type?_ Is it based on the transformation strategy or the origin of the gene being inserted in the recipient strain?

@ValWood I have been discussing this issue with @CuzickA and we would really appreciate your insights and input.

**Comment by MPiovesana** [comment]
A question has been discussed repeatedly by the chemistry curation team regarding the use of the allele type "**transformant**". Currently, allele types have been assigned following the reasoning below:

**1.** When a mutant allele is created by modifying the wild type copy of a gene with site-directed in vitro mutagenesis, for example, and subsequently introduced in the _same strain_ where the original wild type gene was amplified from: 

**1.1** If the gene is introduced via _gene replacement/homologous recombination_, therefore, replacing the wild type allele in its native genomic locus: allele type is based on mutation type; for example, an allele with a point mutation is assigned "_amino acid substitution_", an allele with a deletion is assigned "_deletion_", and so on. Resulting genotype is the **same** of the parental recipient strain with the sole exception of mutation introduced.

**1.2** If the gene is introduced in the recipient strain **NOT** by homologous recombination, and is either _inserted randomly in the genome_ or expressed from a _non-integrative plasmid_ : allele type "**transformant**" is assigned. Resulting genotype is **NOT** the same of the parental recipient strain as endogenous wild type gene is present (unless previously disrupted/deleted) and transgene is inserted in an often unknown/random location in the genome, or from a non-integrative plasmid maintained with selection pressure (eg antibiotics).

**2.** When an altered genotype is created by inserting an allele from _strain A_ into _strain B_: we are inclined to always designate such genotypes with allele type "**transformant**", as the allele being introduced is derived from a different strain, rather than from the recipient strain. Does this make sense? Should "transformant" be selected regardless of the transformation strategy used by authors (homologous recombination, traditional genetic transformation, etc)? 

I guess the main question here is: _on what grounds should we decide whether an allele is of the "transformant" type?_ Is it based on the transformation strategy or the origin of the gene being inserted in the recipient strain?

@ValWood I have been discussing this issue with @CuzickA and we would really appreciate your insights and input.

**Comment by ValWood** [comment]
I'm not sure about this one, because 'transformant" is not something we use  at PomBase.
So I think you just need to decide this based on  how you  expect the data to be interpreted/displayed and make sure that the definitions are inclusive enough to encompass.
My feeling is that probably you introduced this to capture origin (which seems important)  rather than method/strategy but I'm not sure?

**Comment by MPiovesana** [comment]
> I'm not sure about this one, because 'transformant" is not something we use at PomBase. So I think you just need to decide this based on how you expect the data to be interpreted/displayed and make sure that the definitions are inclusive enough to encompass. My feeling is that probably you introduced this to capture origin (which seems important) rather than method/strategy but I'm not sure?

@ValWood Thank you very much for your insights. I think a combination of origin of the transgene and where it is inserted in the genome (if at all) have been used so far when choosing to use the "transformant" allele type, but I wonder whether this will be too complicated and not intuitive for first time community curators. 

@CuzickA Would it be the case to establish that whenever a genotype was achieved via genetic transformation (regardless of the technique used) we should classify it as "transformant"? In this case, only those genotypes generated by other strategies, such as mutagenesis (UV-irradiation) or directed evolution would be assigned with other allele types, such as insertion, deletion, aa substitution, etc. Perhaps this would be more intuitive for users and easier to interpret. What are your thoughts?

**Comment by CuzickA** [comment]
Here are 3 approved curation sessions which I have tagged with the label 'eg allele type 'transformant'
https://github.com/PHI-base/curation/issues/22
https://github.com/PHI-base/curation/issues/51
https://github.com/PHI-base/curation/issues/118

**Comment by CuzickA** [comment]
In https://github.com/PHI-base/curation/issues/22 https://canto.phi-base.org/curs/bd02fdb6831712ca/ro/

In the Gene for gene annotations we have this
![image](https://github.com/PHI-base/curation/assets/11753634/045dda85-7de5-4884-b142-4b8f31618cc5)

In the second annotation we have indicated that the pathogen P. nodorum strain Sn79-1087 does not naturally contain an endogenous copy of Tox 1. This is a WT control metagenotype, note we don't curate WT controls for single species phenotypes (pathogen chemistry curation).
In the first annotation we have indicated that the WT Tox 1 gene from P. nodorum strain SN15 has been transformed into the strain Sn79-1087 which does not naturally contain an endogenous copy of Tox 1.

**Comment by CuzickA** [comment]
> My feeling is that probably you introduced this to capture origin (which seems important) rather than method/strategy but I'm not sure?

Yes, I think we did.

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/51 https://canto.phi-base.org/curs/92ed9bf55f48e444/ro/

In this case we used transformant to indicate that a WT gene from strain NRRL3357 was transformed into strain 3357-5
![image](https://github.com/PHI-base/curation/assets/11753634/76b47efa-2c17-498f-aaa3-0c079d490319)

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/118 https://canto.phi-base.org/curs/78fb5c4223c6062b/ro/
Here we have erg27 from strain 1837 transformed into strain B05.10. I can't remember whether the AA substitutions in the erg 27 strain 1837 are due to natural strain differences or were lab-generated - I would need to go back to the paper and double-check.

![image](https://github.com/PHI-base/curation/assets/11753634/a817e469-b334-4168-9290-fc611d25016f)

**Comment by MPiovesana** [comment]
@CuzickA Thank you so much for showing us these examples. As all three of them capture an allele from one strain being introduced in another strain, I think again we go back to the notion that the **origin** of the allele determines that these are classified as **transformant**, which is a straightforward guideline that should be easily understood by users. 

I think the only remaining question is: in those cases when an allele from a given strain is amplified, mutagenised and re-introduced into the _same_ strain, is there any instance when we would classify it as transformant? We have been using other allele types to describe those instances when genes are inserted via homologous recombination, and I think the grey area is for those cases when genome integration happens randomly or not at all (plasmid-based expression). I think once we clarify this, we can finalise FAQs regarding the creation of alleles and genotypes.

**Comment by ValWood** [comment]
For these we would not record as transformants at PomBase (because we don't have such a concept), but if this is the mutated endogenous sequence at another site I don't think you would want to call it a transformant for your purposes.  If the integration is not at the endogenous locus, AND the endogenous copy is not removed you would want to include the endogenous copy which is still present in the genotype. You can capture expression level separately if the genes is known to be overexpressed on a plasmid.

I'm not quite sure what options you have, I tried to check but PHI-Canto is not accessible via my bookmark http://canto.phi-base.org/

**Comment by CuzickA** [comment]
> I'm not quite sure what options you have, I tried to check but PHI-Canto is not accessible via my bookmark http://canto.phi-base.org/

Thats strange, the link work for me

**Comment by ValWood** [comment]
I get:

HOLDING PAGE
You have reached an unconfigured WEB site on the Rothamsted Research WEB server.
Maybe the site you are trying to reach is still being setup or there is a problem with the server.
Please email [rres.helpdesk@rothamsted.ac.uk](mailto:rres.helpdesk@rothamsted.ac.uk) for further information

**Comment by CuzickA** [comment]
Ok, thanks. I'll let @jseager7 know about this. We recently moved PHI-Canto from Hetnzer to a Rothamsted server. I can access PHI-Canto using my RRes laptop logged into to RRes account. When I try and access PHI-Canto from my phone I get the same message as you @ValWood.

**Comment by CuzickA** [comment]
> @CuzickA Thank you so much for showing us these examples. As all three of them capture an allele from one strain being introduced in another strain, I think again we go back to the notion that the origin of the allele determines that these are classified as transformant, which is a straightforward guideline that should be easily understood by users.

Yes, this sounds correct.

> I think the only remaining question is: in those cases when an allele from a given strain is amplified, mutagenised and re-introduced into the same strain, is there any instance when we would classify it as transformant? 

I would not record these as transformants as the alteration is happening within the SAME strain.

> We have been using other allele types to describe those instances when genes are inserted via homologous recombination, and I think the grey area is for those cases when genome integration happens randomly or not at all (plasmid-based expression). I think once we clarify this, we can finalise FAQs regarding the creation of alleles and genotypes.

Could the new option for 'ectopic expression' be used in these cases?

**Comment by MPiovesana** [comment]
> > We have been using other allele types to describe those instances when genes are inserted via homologous recombination, and I think the grey area is for those cases when genome integration happens randomly or not at all (plasmid-based expression). I think once we clarify this, we can finalise FAQs regarding the creation of alleles and genotypes.
> 
> Could the new option for 'ectopic expression' be used in these cases?

@CuzickA I think that is a good option. So in summary, the origin of the mutant allele is a key factor in determining allele type, rather than transformation strategy. I will start updating the FAQ text accordingly.

**Comment by ValWood** [comment]
>So in summary, the origin of the mutant allele is a key factor in determining allele type, rather than transformation strategy. I will start updating the FAQ text accordingly.

This sounds right!

**Comment by jseager7** [comment]
> I tried to check but PHI-Canto is not accessible via my bookmark

@ValWood I think the error might be because your URL is trying to connect using an unsecured HTTP connection. If you change the URL to start with HTTPS it should work:

https://canto.phi-base.org/

It seems some browsers (Google Chrome, probably) don't have this problem – I assume they must be automatically changing all HTTP connections to HTTPS behind the scenes, and only falling back to HTTP if HTTPS is not available. I seem to remember noticing this problem on another browser though. I'll try to get our IT department to fix this.

**Comment by CuzickA** [comment]
I think we need to standardise the naming/description of the 'transformant' alleles.

![image](https://github.com/PHI-base/curation/assets/11753634/c29ec86b-c9f5-4881-a268-d4911afb50a9)

Should the above examples be changed

1) 
![image](https://github.com/PHI-base/curation/assets/11753634/fc194e6a-0212-45d5-a87b-af5f4a4828be)
Currently (we may have used 'other' here before we had 'transformant')
![image](https://github.com/PHI-base/curation/assets/11753634/fe64072f-991a-43ce-a804-c643e634c4d5)
Should this change to 
![image](https://github.com/PHI-base/curation/assets/11753634/7ffd474c-b5a3-4988-b4ea-9f67226037f8)

**Comment by CuzickA** [comment]
2. WT gene present and additional copies of gene from another strain added.
Currently using allele type 'wild type'
![image](https://github.com/PHI-base/curation/assets/11753634/31bcfc63-ebba-4248-9008-62534f70476c)
![image](https://github.com/PHI-base/curation/assets/11753634/ca663cfe-e144-44d9-a86a-1e445d84e352)


Should this change to
![image](https://github.com/PHI-base/curation/assets/11753634/94419acb-2fd6-4415-895e-7983373980a2)
![image](https://github.com/PHI-base/curation/assets/11753634/07e05c4f-cbf6-41ff-9e32-8db9dfb8e7e7)

**Comment by CuzickA** [comment]
3. This example looks ok to me
![image](https://github.com/PHI-base/curation/assets/11753634/6d3ed52b-605b-4bd5-bb5c-ad77b7cbf2f4)

WT Erg 27 from strain B05.10 (sensitive to chemical) is present with addition of WT Erg 27 from strain 1837 (resistant to chemical) and known AA change between the two strains recorded.

**Comment by CuzickA** [comment]
@ValWood and @MPiovesana, please can you have a look at the suggestions in 1. and 2. above for standardising the naming/description of the 'transformant' alleles.

I will need this information to move forward and check other sessions using 'transformant' allele type such as https://github.com/PHI-base/curation/issues/174

**Comment by CuzickA** [comment]
Also, in example 1 above, Tox1 in naturally absent in the strain Sn79-1087.

![image](https://github.com/PHI-base/curation/assets/11753634/fe057341-e5da-4c63-8d90-b88cc28aac82)

Will this need to be recorded differently if an expt involves deleting a gene in one strain and transforming in the gene from another strain? In this case would we need to create a multiallele genotype for deletion and transformation?

**Comment by ValWood** [comment]
We don't use transformants  but these are some  things you will need to consider.
1. It isn't clear to me why you call the locus WT even when it is transformed ( shouldn't the name make it clear that this is a transformant? Remember that "allele names" should be unique, so this could cause you problems later). 
2. You probably also need to make it clear what happened to the WT locus if it was present (was it deleted?) i.e. no endogenous copy could be interpreted as endogenous copy was deleted (although I guess this could be recorded in the background). I suppose as long  as you are consistent and  it is well documented this is fine.
3. Would it make more sense to describe  transformant  strain,gene(allele) 

I'm not very knowledgable about this but as long as you are consistent and have captured the information your users would require to interpret the experiment it should be OK

**Comment by CuzickA** [comment]
Thanks for your comments @ValWood 

> It isn't clear to me why you call the locus WT even when it is transformed ( shouldn't the name make it clear that this is a transformant? Remember that "allele names" should be unique, so this could cause you problems later).

I'm sorry I'm not quite sure of the meaning of this comment. Are you saying that the name should not be 'gene +'? How do we indicate whether the endogenous gene is present?

> You probably also need to make it clear what happened to the WT locus if it was present (was it deleted?) i.e. no endogenous copy could be interpreted as endogenous copy was deleted (although I guess this could be recorded in the background). I suppose as long as you are consistent and it is well documented this is fine.

Yes, this is one of the issues. Do you think we should record the following in the background
endogenous gene X present
endogenous gene X deleted
endogenous gene X absent

> Would it make more sense to describe transformant strain,gene(allele)

yes, I think this would be useful and then the allele could be recorded (in free text) as wild type or AAsub etc. 
We might need to change the guidance text in PHI-Canto for this
![image](https://github.com/PHI-base/curation/assets/11753634/52594522-e904-4f80-9508-88a7325e9082)

**Comment by MPiovesana** [comment]
> @ValWood and @MPiovesana, please can you have a look at the suggestions in 1. and 2. above for standardising the naming/description of the 'transformant' alleles.
> 
> I will need this information to move forward and check other sessions using 'transformant' allele type such as #174

@CuzickA I agree, I am still quite confused about naming transformant alleles. I think your notes in 1 and 2 make sense to me, particularly changing from WT to transformant in the case of a strain harbouring endogenous wt copies of a gene + extra copies. I have used allele type 'transformant' in several curation sessions recently, and I believe we might have to edit allele names and description once we agree on a standardised procedure. Should we write a short step-by-step to be included in FAQ?

**Comment by MPiovesana** [comment]
> Also, in example 1 above, Tox1 in naturally absent in the strain Sn79-1087.
> 
> ![image](https://user-images.githubusercontent.com/11753634/252950047-fe057341-e5da-4c63-8d90-b88cc28aac82.png)
> 
> Will this need to be recorded differently if an expt involves deleting a gene in one strain and transforming in the gene from another strain? In this case would we need to create a multiallele genotype for deletion and transformation?

@CuzickA couldn't the deletion be recorded as background? I think it makes sense and it could be a more straightforward way to record these genotypes rather than multiallele. What do you think?

**Comment by CuzickA** [comment]
Example 2. above
Perhaps this should change to
![image](https://github.com/PHI-base/curation/assets/11753634/050d53c5-b1eb-4eb6-83f2-9aed6e694523)

**Comment by CuzickA** [comment]
Example 1 above
Could change to
![image](https://github.com/PHI-base/curation/assets/11753634/75d52536-33b2-42d3-818e-183750c884e0)

Note: 'endogenous 'gene' absent' used here as naturally absent in this strain. If deleted by researchers we could use 'endogenous 'gene' deleted'

**Comment by CuzickA** [comment]
Example 3 above
Could change to
![image](https://github.com/PHI-base/curation/assets/11753634/cd501347-f7b9-4073-9cb5-1f5497a9a3e9)

**Comment by CuzickA** [comment]
@MPiovesana and @ValWood do these suggestions for the 3 examples above seem reasonable?

If we use 'gene (name) transformant' as the 'gene name' rather than WT gene does that make more sense?

**Comment by CuzickA** [comment]
> Example 2. above Perhaps this should change to ![image](https://user-images.githubusercontent.com/11753634/252981887-050d53c5-b1eb-4eb6-83f2-9aed6e694523.png)

Actually, maybe we should not record 'wild type' as an allele in the below
'transformant strain,gene(allele)'

The problem here is that the gene may be WT for the donor strain which is naturally different than the recipient strain. In some cases we know the natural strain variation between the strains and can report it and it other cases we do not know it. But in both of these cases the donor strain would be WT for its natural strain. This is the same problem we have faced in the past and discussed using natural variant or engineered variant tags for.

**Comment by ValWood** [comment]
Since transformant alleles are typed "transformant" do you need to repeat the text "transformant" in the description?

**Comment by MPiovesana** [comment]
> @MPiovesana and @ValWood do these suggestions for the 3 examples above seem reasonable?
> 
> If we use 'gene (name) transformant' as the 'gene name' rather than WT gene does that make more sense?

@CuzickA I do think it makes more sense than using the WT (gene name +) notation for allele name. Should we always record the status of the endogenous copy of the gene (absent, deleted, present) in background?

**Comment by CuzickA** [comment]
> Since transformant alleles are typed "transformant" do you need to repeat the text "transformant" in the description?

Removing 'transformed' from the description would look like this
![image](https://github.com/PHI-base/curation/assets/11753634/fd331587-b9cd-45b8-800f-93e4a6917ad7)

**Comment by CuzickA** [comment]
Do we need to change the guidance text for the allele description here?
![image](https://github.com/PHI-base/curation/assets/11753634/33f2b26e-d289-4854-b12a-0cae2e5ffcfe)

**Comment by CuzickA** [comment]
> @CuzickA I do think it makes more sense than using the WT (gene name +) notation for allele name. Should we always record the status of the endogenous copy of the gene (absent, deleted, present) in background?

@MPiovesana, yes I think we do for the 'transformant' alleles.

I'm wondering whether we would also need to do this for any of the other allele types as well??

**Comment by CuzickA** [comment]
> Do we need to change the guidance text for the allele description here? ![image](https://user-images.githubusercontent.com/11753634/252993681-33f2b26e-d289-4854-b12a-0cae2e5ffcfe.png)

@ValWood, should PHI-Canto automatically add the 'gene name' and 'transformant' to the gene name section in a similar manner to the wildtype '+' or deletion 'delta' signs being added automatically upon allele type selection?

**Comment by MPiovesana** [comment]
> > @CuzickA I do think it makes more sense than using the WT (gene name +) notation for allele name. Should we always record the status of the endogenous copy of the gene (absent, deleted, present) in background?
> 
> @MPiovesana, yes I think we do for the 'transformant' alleles.
> 
> I'm wondering whether we would also need to do this for any of the other allele types as well??

@CuzickA I was thinking about this, and I think the answer would be yes, otherwise it might be confusing to add this background info for transformant alleles only. This information is also useful for those genotypes where extra copies of a gene derived from one strain are introduced into the same strain (therefore, not 'transformant'), with the resulting genotype including endogenous and ectopic copies of the gene, for example.

**Comment by ValWood** [comment]
> should PHI-Canto automatically add the 'gene name' and 'transformant' to the gene name section in a similar manner to the wildtype '+' or deletion 'delta' signs being added automatically upon allele type selection?

I guess that would make sense.  No point to type it if it can be automated.

**Comment by ValWood** [comment]
>@MPiovesana, yes I think we do for the 'transformant' alleles.
I'm wondering whether we would also need to do this for any of the other allele types as well??

At Pombase, our default assumption is that if an allele is engineered it is the endogenous copy. We only record if the endogenous copy is not removed.

**Comment by CuzickA** [comment]
> > should PHI-Canto automatically add the 'gene name' and 'transformant' to the gene name section in a similar manner to the wildtype '+' or deletion 'delta' signs being added automatically upon allele type selection?
> 
> I guess that would make sense. No point to type it if it can be automated.

@jseager7, would it be possible to automate this in PHI-Canto?

**Comment by jseager7** [comment]
> @jseager7, would it be possible to automate this in PHI-Canto?

It should be, though I don't know how at the moment. I'll look into this.

How should the name be formatted? Just the gene name, followed by a space, followed by 'transformant'?

**Comment by CuzickA** [comment]
> It should be, though I don't know how at the moment. I'll look into this.

Thanks @jseager7 

> How should the name be formatted? Just the gene name, followed by a space, followed by 'transformant'?

Yes, I think that sounds correct.

**Comment by CuzickA** [comment]
@MPiovesana I think the next steps here are
1) please add the label 'eg allele type transformant' to the GitHub tickets for sessions you have curated using this allele type.
2) edit the transformant genotypes in these sessions so that they follow the standard format
allele name: gene name transformant
allele description: strain-gene (allele -if known AA change, but not wildtype)
background: endogenous gene X present, endogenous gene X deleted, endogenous gene X absent

Based on @ValWood comment above, is it useful to have the background options 'endogenous gene X deleted', 'endogenous gene X absent' or is this making too much curation work?
'endogenous gene X absent' is really useful to indicate that the gene was naturally absent from the strain.
'endogenous gene X deleted' makes it really clear that the gene was deleted for the purpose of the expt. but this could also be assumed based on Val's comment above.

@ValWood and @MPiovesana, please let me know what you think?

**Comment by CuzickA** [comment]
@jseager7 I just wanted to double check with you whether the 'background' is displayed in both the single species genotypes and metagenotypes on the new PHI-base 5 interface? I'm finding it hard to track down examples on the beta PHI5 website.

**Comment by ValWood** [comment]
if it is deleted just put gene_namedelta in the background.

**Comment by CuzickA** [comment]
@ValWood so the background options would be
endogenous gene_name present
endogenous gene_name absent
gene_namedelta

**Comment by MPiovesana** [comment]
> @MPiovesana I think the next steps here are
> 
> 1. please add the label 'eg allele type transformant' to the GitHub tickets for sessions you have curated using this allele type.
> 2. edit the transformant genotypes in these sessions so that they follow the standard format
>    allele name: gene name transformant
>    allele description: strain-gene-allele(if known AA change, but not wildtype)
>    background: endogenous gene X present, endogenous gene X deleted, endogenous gene X absent

@CuzickA That's great, I will update all curation sessions with transformant allele types accordingly and add the label to GitHub tickets. I think these guidelines are clear and straightforward, and I think background information is not too much added work and solves the problem of recording what happened to the endogenous gene. I think the background info could also be adopted for other allele types, as we currently do not record this info anywhere other than in the comment section occasionally.

**Comment by jseager7** [comment]
> @jseager7 I just wanted to double check with you whether the 'background' is displayed in both the single species genotypes and metagenotypes on the new PHI-base 5 interface? I'm finding it hard to track down examples on the beta PHI5 website.

It probably isn't. Again, something to discuss at the next meeting.

**Comment by jseager7** [comment]
Transformant allele names should be automatically filled in on the main PHI-Canto server now. Feel free to let me know if you notice any problems.

**Comment by CuzickA** [comment]
I have updated the genotypes in 
https://github.com/PHI-base/curation/issues/51
https://github.com/PHI-base/curation/issues/118

Still to do 
https://github.com/PHI-base/curation/issues/22

**Comment by CuzickA** [comment]
Just updated genotypes in https://github.com/PHI-base/curation/issues/22

Closing ticket
