### ISSUE TITLE
PMID: 11600353 In vitro and in vivo effects of 14alpha-demethylase (ERG11) depletion in Candida glabrata.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#158]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/8abc3eda3c67a543

**Comment by MPiovesana** [comment]
In this papers, authors investigate the effects of reduced levels of expression of the _Erg11_ gene of _Candida glabrata_ by generating mutant strains in which the endogenous promoter of the _Erg11_ was replaced with regulatable promoters. In these mutants, expression of _Erg11_ could be repressed with the application of doxycycline (DOX). Three mutants with three different promoters are generated, and _Erg11_ expression levels with and without DOX application are assessed. Authors observed growth defects as a result of the depletion of _Erg11_ expression, as well as increased resistance to the antifungal fluconazole.

**Comment by MPiovesana** [comment]
**Uniprot ID:** only one reference proteome is available for _Candida glabrata_ on Uniprot (UP000002428), and a single entry for _Erg11_ can be retrieved (**P50859**) when searching this proteome.

**Comment by MPiovesana** [comment]
**Strain:** authors say they use strain ACG4 as a recipient for transformation; according to table 1, this strain is derived from reference strain ATCC 2001. However, all assays include strain ATCC 2001, and not ACG4, as experimental wild type control. For this reason, I manually added ATCC 2001 as strain in this curation session. Is this ok?

**Comment by MPiovesana** [comment]
**Genotype creation:** this is where I have a few questions on how to best create these genotypes. I believe "**transformant**" might be a good option, as an exogenous promoter is used to replace the endogenous _Erg11_ promoter in the mutant strains; however, we do not the origin of the 97/98/99t promoters.

Alleles were named as the following example: 

**97tprom transformant (97tprom(DOX-repressible promoter)::endogenous ERG11**" = transformation of 97/98/99t promoter in the endogenous locus of _ERG11_. 'DOX-repressible promoter' was added in allele description to clarify the function of the promoter, and 'endogenous _ERG11_' was added to indicate the genomic loci where the promoter was inserted. 'ERG11promΔ' was added in background to indicate the replacement of the endogenous promoter.

When it comes to expression level, I chose "**knockdown**" as the closest option to describe the reduced levels of _Erg11_ expression upon application of DOX, but I believe "depletion" or "knockout" would be more appropriate here. This is also only true when DOX is applied; without DOX application, the mutant lines show varying levels of _Erg11_ expression, ranging from knockdown to overexpression (Figure 1B). However, as the focus of the paper is on the effect of _Erg11_ depletion, I believe we should focus on curating the genotypes under the application of DOX.

Is this correct? Should we add details about the origin of the 97/98/99t promoters (we do not have these, but could search the literature)?

**Comment by MPiovesana** [comment]
**Genotype annotation:**
The defective growth of the transformant strains upon DOX treatment was annotated with the PHIPO term "**decreased unicellular population growth**". 

Another set of annotations recorded the increased resistance to fluconazole displayed by all mutant strains when grown in medium supplement with DOX and fluconazole compared to the wild type strain. This is based on results displayed in Figure 5 and Table 4, although I believe an error is present in the table, with presence of DOX being mislabelled. I cross checked text, figure and tables a few times, and the table would only make sense if "Yes" and "No" for the presence of DOX were mistakenly interchanged. All three genotypes were annotated with PHIPO term "**resistance to fluconazole**".

**Comment by MPiovesana** [comment]
Curation completed pending review; genotypes might have to be edited to record promoter replacement.

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/5d644809-738a-4450-a3aa-87f5bab47ffa)

**Comment by CuzickA** [comment]
I think I would combine the three annotations for the 97t, 98t and 99t into one genotype and thus into one annotation per phenotype.

I don't think 'transformant' is the best allele type to use here. Based on the curation session with a Dex inducible promoter 
https://github.com/PHI-base/curation/issues/42

I would change the top 3 genotypes to the 4th genotype in the table
![image](https://github.com/PHI-base/curation/assets/11753634/a50fe598-c77c-4b8f-9e43-a3b62e8c5ebc)

Hi @ValWood, does this seem reasonable to you? I might need to write up some notes in the FAQ document about creating genotypes for inducible/repressible promoters and making annotations capturing the inducer/repressor in the conditions.

Is it worth recording the 'ERG11promΔ' in the background?

**Comment by CuzickA** [comment]
Annotations to "decreased unicellular population growth" and "resistance to fluconazole" are fine. 
Waiting for a bug fix and then I will transfer the annotations to the new genotype suggested above (dependent on any feedback for this new genotype)

**Comment by CuzickA** [comment]
Not possible to add AE alteration in archetype as genotype has altered promoter not coding region.

**Comment by ValWood** [comment]
I think it's useful to record t
he promoter for OEX, but  we don't usually bother for knockdown.
I agree if the phenotypes are equivalent I would just record the knockdown phenotype once.

**Comment by CuzickA** [comment]
> I think it's useful to record t he promoter for OEX, but we don't usually bother for knockdown. I agree if the phenotypes are equivalent I would just record the knockdown phenotype once.

Thanks @ValWood, so do you think its reasonable to record a DOX repressible promoter with WT ERG11 in the genotype like this and then add '+ doxycycline' in the conditions?
![image](https://github.com/PHI-base/curation/assets/11753634/b802babd-b10c-42bd-b5a9-b5d850410b62)

**Comment by ValWood** [comment]
I think so, we have been doing similar actually sometimes....

**Comment by CuzickA** [comment]
Edits made, now looks like this

![image](https://github.com/PHI-base/curation/assets/11753634/569b276d-5681-47e2-beff-0b9b25a71032)

Approving session and closing ticket
