### ISSUE TITLE
PMID: 12019099 An Enterococcus faecalis ABC homologue (Lsa) is required for the resistance of this species to clindamycin and quinupristin-dalfopristin.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#159]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/d23a6ae0158f6c78

**Comment by MPiovesana** [comment]
This paper investigates the role of the _lsa_ gene of _Enterococcus faecalis_ in this species' intrinsic resistance to antifungals including clindamycin (CLI), quinupristin-dalforpristin (Q-D) and dalfopristin (DAL). To do so, authors study a mutant of _E. faecalis_ strain OG1RF where the _lsa_ gene has been disrupted, which exhibits sensitivity to CLI, Q-D and DAL. The disruption mutant is complemented with a wild type copy of the _lsa_ gene, and antifungal resistance is restored to wild type levels. As we do not curate complementation experiments of this type in PHI-Canto, I annotated the genotype of the disruption mutant only.

**Comment by MPiovesana** [comment]
**Uniprot ID:** an accession number is not provided by the authors of the paper, so I tried to retrieve the Uniprot ID with a gene name and species search, without success. I then performed a BLAST on Uniprot using part of the _lsa_ protein sequence provided in Figure 1, and Uniprot ID Q830Q4 was retrieved. However, this ID refers to the _lsa_ gene of strains other than OG1RF, which is the recipient strain for gene disruption used in this study. I then searched the "Similar proteins" section of this entry for proteins with 100% similarity, and located ID **A0A855UHH5** which is associated with several strains of _E. faecalis_, including OG1RF. This ID was selected for the curation session.

**AC 02_02_2024 update: UniProt changed see comment below.**

**Comment by MPiovesana** [comment]
**Genotype creation:** a single altered genotype was created with a "**disruption**" allele type. The allele was named _lsa-(gene disruption)_ to indicate the absence of a functional _lsa_ product. Expression levels are not measured by the authors, although they mention that the disruption of the genomic locus was confirmed by hybridization of digested genomic DNA from wild type and mutant strains. I guess this allele could theoretically be classified as null, but I wasn't sure whether I could select this option as expression levels per se were not measured. Thus, I selected **Not assayed** for now.

**Comment by MPiovesana** [comment]
**Genotype annotation:** The genotype was annotated with three PHIPO terms according to results displayed in Table 2:
_sensitive to clindamycin_
_sensitive to quinupristin-dalfopristin_
_sensitive to dalfopristin_ (suggested)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Note quinupristin-dalfopristin is a combination of two chemicals -antibiotic!

https://en.wikipedia.org/wiki/Quinupristin/dalfopristin

'Enterococcus faecalis' is a bacteria and not a fungus! 

Note: this paper was identified for curation by MP.

I will finish checking this session for approval as already curated but will need to omit this (and any other 'Enterococcus faecalis' curation sessions from the 'fungicide resistance' manuscript that is planned.

All of these are antibiotics and have not currently been added to the anti-infective list. To date we have been focusing on antifungals but there are a few antibiotics listed. **Still to decide whether to add these??**
clindamycin
quinupristin-dalfopristin
quinupristin
dalfopristin

**Comment by CuzickA** [comment]
I am going to change the UniProt id from 'A0A855UHH5' to 'Q7WT47'

https://www.uniprot.org/uniprotkb/Q7WT47/entry which was used for https://github.com/PHI-base/curation/issues/205

**Comment by CuzickA** [comment]
Current annotations with edits
![image](https://github.com/PHI-base/curation/assets/11753634/45f51fa0-5617-476f-b47e-8c1097f0c281)

**Comment by CuzickA** [comment]
Changed UniProt id and corrected the disruption genotype to make it more consistent with the naming of other disruption mutants.

Now looks like this

![image](https://github.com/PHI-base/curation/assets/11753634/1ce18fe4-687f-40c8-8587-9bc3560653fe)

**Comment by CuzickA** [comment]
**Next steps**
1) waiting for PHIPO and PHI-ECO terms then ready for approval.

**Comment by CuzickA** [comment]
PHIPO and PHI-ECO terms now added.

Session approved.

Closing ticket.
