### ISSUE TITLE
how best to create an allele with a deletion and amino acid substitution

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#16]
Note to myself about how best to do this

A partial deletion allele has already been created using allele type 'partial deletion, amino acid' 
eg

![image](https://user-images.githubusercontent.com/11753634/52269529-3d019f00-2936-11e9-861f-61a81241331e.png)

 
A second genotype was then created where amino acids were substituted
if I use the allele type 'partial deletion and amino acid change' 

![image](https://user-images.githubusercontent.com/11753634/52269578-602c4e80-2936-11e9-86a9-5d52f87b5df8.png)

resulting genotypes
![image](https://user-images.githubusercontent.com/11753634/52269606-733f1e80-2936-11e9-853b-fea2b6a718d7.png)

**Comment by CuzickA** [comment]
I think is correct. Just wanted to document, so now closing.

**Comment by ValWood** [comment]
yes, you got it!
