### ISSUE TITLE
PMID: 9758830 A novel ATP-binding cassette transporter involved in multidrug resistance in the phytopathogenic fungus Penicillium digitatum

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#160]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/6b22874f745e874d#

**Comment by MPiovesana** [comment]
Straightforward paper where the role of the _PMR1_ gene of _Penicillium digitatum_ in antifungal resistance was explored by gene disruption in a DMI-resistant strain. Strain LC2 (isolated from the surface of lemons) has a multidrug resistance phenotype, which was abolished with the disruption of _PMR1_.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors provide a GenBank accession number for _PMR1_ (AB010442) which was used to retrieve the Uniprot ID used in the curation session (**O74637**).

**Comment by MPiovesana** [comment]
**Strain:** strain LC2 was manually entered.

**Genotype creation:** a disruption allele named _PMR1-_ (gene disruption) was created, and the expression level "**Null**" was selected as _PMR1_ transcript was undetectable (Northern blot, Figure 4) in the disruption line.

**Comment by MPiovesana** [comment]
**Genotype annotation:** the genotype was annotated with four PHIPO terms:
_sensitive to fenarimol_
_sensitive to triflumizole_ (suggested)
_sensitive to bitertanol_ (suggested)
_sensitive to pyrifenox_ (suggested)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/408fa4e4-3057-4dd4-a418-844a4d662002)

**Comment by CuzickA** [comment]
Small edit to genotype

![image](https://github.com/PHI-base/curation/assets/11753634/a1cf9927-fbff-478d-9fc9-0c3f86351abd)

**Comment by CuzickA** [comment]
PHIPO and PHI-ECO terms already available
now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/ab22e384-0532-4a4d-b053-3a45c4a6f803)

**Comment by CuzickA** [comment]
Add new strain 5e762bc

**Comment by CuzickA** [comment]
AE alteration in archetype N/A as NTSR and disruption

Session approved

Closing ticket
