### ISSUE TITLE
PMID: 23629718 Molecular mechanisms of drug resistance in clinical Candida species isolated from Tunisian hospitals

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#161]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/1d956c6785fd3798

**Comment by MPiovesana** [comment]
This is quite a long paper which describes the antifungal susceptibility phenotypes of several clinical isolates and laboratory-generated strains of _Candida albicans_ and _Candida tropicalis_. In brief, a fluconazole-resistant clinical isolate (JEY355) of _C. albicans_ was found to carry a mutant allele of _MRR1_ (MRR1-V877F). To test the link between azole resistance and this mutant allele, authors generated a deleted _MRR1_ line (_MRR1Δ_), followed by the introduction of the mutant allele in the deleted background. 
Similarly, an azole-resistant isolate of _C. tropicalis_ was found to carry mutant alleles of _ERG3_ (aaS258F) and _ERG11_ (44aa deletion + D275V). These alleles were introduced in the genomic loci of _ERG3_ and _ERG11_, respectively, in a wild type strain DSY140 (derived from ATCC 750). Single and double mutant lines were generated.
The antifungal susceptibility of the resulting lines was tested (Table 3, Figure 3), and results were curated. I focused on annotations of susceptibility to azoles (fluconazole and voriconazole), amphotericin B, and brefeldin A, which seem to be the most relevant ones from the paper.

**Comment by MPiovesana** [comment]
**Uniprot IDs:**
_C. albicans_:
Reference proteome UP000000559 includes strain SC5314, used in this paper, and was used to search for MRR1 protein. A single entry was found and used for the curation session (**Q5A4G2**).

AC - this reviewed entry looks fine https://www.uniprot.org/uniprotkb/Q5A4G2/entry

_C. tropicalis_:
Authors provide a GenBank accession number but I believe those were for the deposition of the mutant allele sequences; plus, it only refers to _erg11_ when searching it on Uniprot. Furthermore, finding these IDs was a little trickier as the reference proteome suggested by Uniprot for _C. tropicalis_ does not include reference strain ATCC 750 used in this study. So by doing a normal search on Uniprot with gene and species name, the following entries were retrieved:
_ERG3_: **N0A5G3**; organism is linked to strain ATCC 750. First entry returned on search. However, another entry of same length is also shown (N0A3T1). 

Ac - this is an unreviewed entry https://www.uniprot.org/uniprotkb/N0A5G3/entry

_ERG11_: **P14263**; single reviewed entry for this gene, linked to strain ATCC 750.

AC - this reviewed entry looks fine https://www.uniprot.org/uniprotkb/P14263/entry

IDs might need revising.

**Comment by MPiovesana** [comment]
**Strains:**
_C. albicans_: SC5314 was selected.
_C. tropicalis_: I searched for strain ATCC 750, from which recipient strain DSY140 is derived. PHI-Canto suggested strain 1909 as a synonym to ATCC 750, so I selected it. Is this ok?

**Comment by MPiovesana** [comment]
**Genotypes creation:** as all genotypes (except for MRR1 deletion) were created by introducing a mutant allele of a clinical isolate into a wild type recipient strain, they were classified as **transformant** alleles.

_C. albicans_:
**MRR1Δ**: deletion of MRR1  (AC - DSY4278)

**MRR1 transformant (JEY355-MRR1(V877F))**: introduction of mutant allele of MRR1 derived from strain JEY355 in strain SC5314 harbouring MRR1 deletion (MRR1Δ was added in background).

_C. tropicalis_:
**ERG11 transformant(JEY162-ERG11(824-955bpΔ + D275V)**: introduction of mutant allele of ERG11 derived from strain JEY162 in genomic loci of wild type ERG11; mutant allele carries a deletion (bp 824 to 955) and mutation leading to aa substitution (D275V). ERG11Δ was added in background.

**ERG3 transformant(JEY162-ERG3(S258F)**: introduction of mutant allele of ERG3 derived from strain JEY162 in genomic loci of wild type ERG3; ERG3Δ added in background.

**ERG11 transformant(JEY162-ERG11(824-955bpΔ + D275V) + ERG3 transformant(JEY162-ERG3(S258F)**: multilocus genotype describing the introduction of both mutant alleles derived from strain JEY162.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotypes were annotated accordingly with the following PHIPO terms:
_normal growth on fluconazole_ (suggested)
_normal growth on voriconazole_
_normal growth on brefeldin A_ (suggested)
_resistance to fluconazole_
_resistance to brefeldin A_

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Added 'MDR1' for Candida albicans

https://www.uniprot.org/uniprotkb/Q5ABU7/entry swiss-prot reviewed entry.

I want to make a GO MF annotation to indicate that MRR1 regulates MDR1 expression

![image](https://github.com/PHI-base/curation/assets/11753634/2be0d9fb-e3e3-4664-bab5-18b6fd1f0729)

**Comment by CuzickA** [comment]
Hi @ValWood, do you think the above GO MF annotations are reasonable?

**Comment by ValWood** [comment]
Looks good!
v

**Comment by CuzickA** [comment]
Thanks @ValWood

**Comment by CuzickA** [comment]
Pathogen phenotype annotations look fine.

Considered trying to add AE alteration in archetype for Ct ERG11/CYP51B but decided against it.
There was no archetype information in Nichola's S file or the Mair et al 2026 paper for Candida tropicalis. It may have been possible to use FRAST but this would not be straight forward as its not clear where to get the sequence for 'JEY162-ERG11(824-955bpΔ + D275V)' to do a FRAST alignment against CYP51B and how to cope with the 132nt deletion. Therefore, AE not added.

**Next steps for this session**
1) wait for PHIPO terms to be loaded into PHI-Canto

Then session ready for approval.

**Comment by CuzickA** [comment]
Terms now added. Session approved. Closing ticket.
