### ISSUE TITLE
PMID: 24903410 Protein kinase FgSch9 serves as a mediator of the target of rapamycin and high osmolarity glycerol pathways and regulates multiple stress responses and secondary metabolism in Fusarium graminearum.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#162]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/2d2e1c30cceb7aab

**Comment by MPiovesana** [comment]
In this paper, authors generate a deletion line of the protein kinase _FgSch9_ of _Fusarium graminearum_ in the wild type background PH-1. The role of this protein kinase in stress responses, including antifungal susceptibility, is explored. As _FgSch9_ is known to interact with _HOG1_, a _HOG1_ deletion mutant, as well as a double mutant (_FgSch9Δ/Hog1Δ_) are also generated and tested under stress conditions. Several aspects of fungal development are also assessed to evaluate the presence of fitness penalties caused by the gene deletion.

**Comment by MPiovesana** [comment]
**Uniprot IDs:** An accession number provided by the authors (FGSG_00472) is used to identify the Uniprot ID of _FgSch9_ in the reference proteome of _F. graminearum_ in Uniprot. Entry **I1RAE5** is retrieved. By searching the same reference proteome and performing a gene name search, the entry for _HOG1_ is also identified (**P0C431**).

**Comment by MPiovesana** [comment]
**Genotype creation:** allele type deletion was used for all genotypes created:

**FgSch9Δ**: deletion of _FgSch9_ in PH-1
**HOG1Δ**: deletion of _HOG1_ in PH-1
**FgSch9Δ HOG1Δ**: multi locus genotype, double mutant

**FgSch9+[WT level]**: created for control metagenotype

**Comment by MPiovesana** [comment]
**Genotype annotations:** a number of annotations were created to characterise the phenotypes described in the paper. These are:

decreased hyphal growth
decreased rate of asexual spore germination
short germ tube
decreased production of deoxynivalenol (DON) (suggested)
sensitive to osmotic stress
resistance to fludioxonil
sensitive to hydrogen peroxide
sensitive to congo red
sensitive to sodium dodecyl sulfate
sensitive to rapamycin

**Comment by MPiovesana** [comment]
**Metagenotype annotation:** the decreased virulence of the _FgSch9Δ_ mutant was also recorded with a metagenotype annotation (_decreased extent of pathogen-associated host lesions_).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Checked Fig 1 annotations and added one

![image](https://github.com/PHI-base/curation/assets/11753634/1424d197-7073-42d3-a027-a29def096b67)

**Comment by CuzickA** [comment]
Add GO CC annotation

![image](https://github.com/PHI-base/curation/assets/11753634/15e1a101-dd8d-4dbb-9c58-5d279b58cc31)

**Comment by CuzickA** [comment]
PHI phenotype look good

Changing this pathogen phenotype to a PHI phenotype
![image](https://github.com/PHI-base/curation/assets/11753634/46ea0c75-bbbb-4b38-ab16-fb289b9a3b49)

now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/97ca243c-f5f5-4a12-bd85-c175a35e9904)


Added disease annotation
![image](https://github.com/PHI-base/curation/assets/11753634/ee826ca1-135b-4429-9860-774e9152a161)

**Comment by CuzickA** [comment]
changed 
'sensitive to osmotic stress' to 'sensitive to salt stress'
'sensitive to hydrogen peroxide' to 'sensitive to oxidative stress'
'sensitive to sodium dodecyl sulfate' to 'sensitive to cell wall stress'

**Comment by CuzickA** [comment]
No new strains to add.

AE alteration in archetype N/A

**Next step**
1) create PHIPO term

Then session ready for approval

**Comment by CuzickA** [comment]
PHIPO term created. Wait for overnight loading into PHI-Canto.

**Comment by CuzickA** [comment]
PHIPO term added. Session approved. Closing ticket.
