### ISSUE TITLE
PMID: 30874562 A phosphorylated transcription factor regulates sterol biosynthesis in Fusarium graminearum

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#163]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/286abaf17e490111

**Comment by MPiovesana** [comment]
Extensive paper with generation of several mutant genotypes and numerous experiments performed. In this paper authors report the identification of the transcription factor **_FgSR_** of _Fusarium graminearum_ which regulates sterol biosynthesis. As such, deletion and mutations of _FgSR_ affect the susceptibility of _F. graminearum_ to sterol biosynthesis inhibitor (SBI) fungicides, such as tebuconazole. In this study, authors generate a deletion line of _FgSR_ (_FgSRΔ_), as well as of interacting partners and other proteins which participate in the same signalling cascade as _FgSR_ (_Ssk2, Pbs2, Hog1, Arp9_). Authors also generate phospho-inactive and phosphomimic mutants of _FgSR_, as well as lines where the zinc finger (ZF) and middle linker (ML) domains of _FgSR_ have been deleted. The susceptibility of all mutant lines to fungicides is tested. Finally, the virulence and DON production of _FgSRΔ_ infecting wheat plants are also assessed.

**Comment by MPiovesana** [comment]
**Uniprot IDs:**
_FgSR_: the gene code FGSG_01176 provided in the paper was used to locate the Uniprot ID (**I1RC73**) corresponding to _FgSR_.

_FgSsk2_: the ref proteome of _F. graminearum_ (UP000070720) was searched with the gene name _Ssk2_, returning ID **I1RA81**.

_FgPbs2_:  the ref proteome was searched with the gene name _Pbs2_, returning ID **I1RWL6**.

_FgHog1_: the ref proteome was searched with the gene name _Hog1_, returning ID **P0C431**.

_FgArp9_: the ref proteome was searched with the gene name _Arp9_, returning ID **A0A098DZN5**.

**Comment by MPiovesana** [comment]
**Strains:**
_F. graminearum_: PH-1
Wheat: cv Jimai22

**Comment by MPiovesana** [comment]
**Genotype creation:**
Deletion alleles were created for all genes, generating the following genotypes:
FgSRΔ
FgSSK2Δ
FgHOG1Δ
FgPBS2Δ
FgARP9Δ

The phospho-inactive and phospho-mimic genotypes, where five phosphorylation sites were replaced with alanine or aspartic acid residues, respectively, were created by combining the _FgSRΔ_ and **amino acid substitution** alleles (multi locus genotypes), as the mutant alleles were introduced in the _FgSRΔ_ mutant background:
**FgSRΔ + FgSR-C-5A (aaT82A S92A S102A T217A S305A)** = phospho-inactive
**FgSRΔ + FgSR-C-5D (aaT82D S92D S102D T217D S305D)** = phosphomimic 

Similarly, to create the partially deleted alleles where the zinc finger domain and the middle linker region of the _FgSR_ protein were deleted, **partial deletion, amino acid** alleles were combined with _FgSRΔ_:
**FgSRΔ + FgSRΔML(53-130)** = middle linker deletion
**FgSRΔ + FgSRΔZF(9-52)** = zinc finger deletion

Expression level = ectopic was selected for all multi-locus genotypes.

**Comment by MPiovesana** [comment]
**Genotype annotations:** several annotations were made to curate this publication. These include the antifungal sensitivity phenotype of the deletion and mutant lines to tebuconazole, as well as the sensitivity of FgSRΔ to a number of other fungicides. The following PHIPO terms were used:
_sensitive to tebuconazole_
_normal growth on tebuconazole_ (suggested)
_sensitive to triadimefon_
_normal growth on iprodione_ (suggested)
_normal growth on fludioxonil_ (suggested)
_sensitive to naftifine_
_sensitive to terbinafine_
_sensitive to fluvastatin_ (suggested)
_sensitive to lovastatin_ (suggested)
_sensitive to spiroxamine_
_sensitive to tridemorph_
_sensitive to prochloraz_

Metagenotype annotations included:
_presence of pathogen-associated host lesions_ (control and altered metagenotypes)
_pathogen deoxynivalenol within host present_ (control)
_decreased level of deoxynivalenol within host_ (altered)

**Comment by MPiovesana** [comment]
I believe the most important genotypes and phenotypes were recorded in this curation session. Additional experiments mentioned in the Supplemental material could be included, but are not as relevant to the main focus of the paper. 

Curation completed pending review.

**Comment by CuzickA** [comment]
PHI phenotypes look fine 

Added disease annotation
![image](https://github.com/PHI-base/curation/assets/11753634/5d400a1b-e590-463d-bf1c-e9a807512e56)

**Comment by CuzickA** [comment]
Added GO CC annotation

![image](https://github.com/PHI-base/curation/assets/11753634/b6195ea7-74ec-443c-ac78-3b1a6b8dcbac)

**Comment by CuzickA** [comment]
Also added GO MF

![image](https://github.com/PHI-base/curation/assets/11753634/409bee8d-dc8b-4284-aab1-11c780b2b1de)

**Comment by CuzickA** [comment]
> The phospho-inactive and phospho-mimic genotypes, where five phosphorylation sites were replaced with alanine or aspartic acid residues, respectively, were created by combining the FgSRΔ and amino acid substitution alleles (multi locus genotypes), as the mutant alleles were introduced in the FgSRΔ mutant background:
> FgSRΔ + FgSR-C-5A (aaT82A S92A S102A T217A S305A) = phospho-inactive
> FgSRΔ + FgSR-C-5D (aaT82D S92D S102D T217D S305D) = phosphomimic


I think that the FgSRΔ should just be recorded in the background rather than as part of a multi-locus allele.

![image](https://github.com/PHI-base/curation/assets/11753634/2516c247-5e9e-4ace-8b8a-c8f4f34d8bb3)

change to

![image](https://github.com/PHI-base/curation/assets/11753634/d5d85441-893d-46fd-9133-5ccd56e9fcd9)


![image](https://github.com/PHI-base/curation/assets/11753634/46b68ffb-ea33-497a-9c8b-2eaa94926154)

change to

![image](https://github.com/PHI-base/curation/assets/11753634/c86b585a-3c84-41e6-a234-f0681a6e0cce)

**Comment by CuzickA** [comment]
> Similarly, to create the partially deleted alleles where the zinc finger domain and the middle linker region of the FgSR protein were deleted, partial deletion, amino acid alleles were combined with FgSRΔ:
> FgSRΔ + FgSRΔML(53-130) = middle linker deletion
> FgSRΔ + FgSRΔZF(9-52) = zinc finger deletion

Also moved SRdelta into background for these genotypes

![image](https://github.com/PHI-base/curation/assets/11753634/711a498f-f266-4e92-9569-3ef67af85918)

changed to

![image](https://github.com/PHI-base/curation/assets/11753634/800da55f-fc4e-41f6-b4d0-8b917b7d850e)

**Comment by CuzickA** [comment]
I am removing these annotations as the chemicals are statins.

![image](https://github.com/PHI-base/curation/assets/11753634/6ece19d6-465a-483e-8c14-6458e9bb98e4)

**Comment by CuzickA** [comment]
Added protein modification annotation

![image](https://github.com/PHI-base/curation/assets/11753634/f6358b6d-9f20-424d-8a5b-45fe1397db24)

**Comment by CuzickA** [comment]
Added reviewed UniProt entry 'I1RJR2' for Fg CYP51A

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/41396d3d-748b-4c17-af34-5a1d0d0d6d7c)

In summary,

I have annotated 
Protein modification 'SR' is phosphorylated by 'Hog1'
GO BP CYP51A is involved in sterol biosynthesis
GO MF SR is a TF and binds to cis element in CYP51A (and other) promotor

Main pathogen phenotypes
SRdelta (results in reduced transcription of CYP51A) readout increased sensitivity to anti-fungal SBI chemical tebuconazole

![image](https://github.com/PHI-base/curation/assets/11753634/976092e0-e164-4416-b80d-2cb65ca76353)

![image](https://github.com/PHI-base/curation/assets/11753634/cf166189-00fc-4526-ba41-60e300404301)

![image](https://github.com/PHI-base/curation/assets/11753634/9402a7d2-8898-44bd-8518-e20d6eeec91f)



Hi @ValWood, I'm a bit rusty on GO annotations. Please could you do a sanity check on these?

**Comment by CuzickA** [comment]
**Next steps**
1) add new PHIPO term
2) see if GO annotations seem ok

No alterations are made to the chemical target sites of the CYP51 genes in this session so it is not relevant to add in the AE alteration in archetype.

After 1 and 2 above have been done then this session will be ready to approve.

**Comment by ValWood** [comment]
This looks good. Could CYP51A be  to the child "ergosterol biosynthesis" ?

I think you could also add "regulation of ergosterol biosynthesis" to the transcription factor.

**Comment by CuzickA** [comment]
Thanks @ValWood, how about this?

![image](https://github.com/PHI-base/curation/assets/11753634/9a67d18f-fa50-426a-bea3-153126675188)

**Comment by ValWood** [comment]
Great but the CYP51A is part of the pathway, so that doesn't need to be "regulation of" that would be just  to "ergosterol  biosynthetic process"

**Comment by CuzickA** [comment]
Thanks @ValWood

Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/de3fbd8f-d5c2-45cd-90cf-929e93240d9d)

**Comment by CuzickA** [comment]
Session just waiting for new PHIPO term and then it will be ready to approve.

**Comment by ValWood** [comment]
yes, looks good!

**Comment by CuzickA** [comment]
PHIPO term added. Session approved. Closing ticket.
