### ISSUE TITLE
PMID: 20447272 Mandipropamid targets the cellulose synthase-like PiCesA3 to inhibit cell wall biosynthesis in the oomycete plant pathogen, Phytophthora infestans

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#164]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/3b9ce06197c605df

**Comment by MPiovesana** [comment]
In this paper, authors generate mutants of _Phytophthora infestans_ via EMS mutagenesis. Two mutants, named Tmut3 and Tmut7, display increased resistance fungicides, and are found to carry point mutations in the _CesA3_ gene. The _Tmut3-CesA3_ mutant allele is introduced in _P. infestans_ to confirm the association between this mutation and increased resistance to fungicides.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors provide the GenBank accession number ABP96904 for _PiCesA3_, which was used to locate Uniprot ID **A5A5Z5**.

**Strain**: _P. infestans_ strain T30-4 was used for mutagenesis experiment, and isolate 88069 was recipient for genetic transformation.

**Comment by MPiovesana** [comment]
**Genotype creation:**
I decided to curate all genotypes described in this experiment, including both mutants obtained via mutagenesis, as well as the transformants. Genotypes were created as shown below:

**CesA3(aaG1105V)[Overexpression]** = EMS-generated mutant carrying Tmut3 mutation (CesA3-G1105V); gene expression analysis revealed this allele is slightly overexpressed compared to _CesA3_ expression levels in wt strain;

**CesA3(aaG1105A)[Knockdown]** = EMS-generated mutant carrying Tmut7 mutation (CesA3-G1105A); gene expression analysis revealed this allele is slightly repressed compared to _CesA3_ expression levels in wt strain;

**Tmut3-CesA3(Tmut3-CesA3aaG1105V)[Ectopic]** = transformant carrying the _CesA3_ allele from mutant Tmut3 in strain 88069; ectopic expression. _Endogenous CesA3 present_ was added to background.

**Comment by MPiovesana** [comment]
**Genotype annotation:**
The following PHIPO terms were assigned to genotypes:
_resistance to mandripropamid_ (suggested)
_normal hyphal growth_
_decreased rate of hyphae formation_
_resistance to dimethomorph_ (suggested)
_resistance to iprovalicarb_ (suggested)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
I am changing the transformant genotype slightly

from
![image](https://github.com/PHI-base/curation/assets/11753634/5bc9f7aa-ae39-49eb-b86e-f2041be1ef71)


to
![image](https://github.com/PHI-base/curation/assets/11753634/a4ff9ad4-0cf8-4f56-9da3-80f182af7fb1)


This is to make it clearer that Tmut3 is a mutation of strain T30-4.

**Comment by CuzickA** [comment]
Need to add '88069' to Phytophthora infestans strain list.

**Comment by CuzickA** [comment]
**AE alteration in archetype**

CesA3(aaG1105V)[Overexpression] 
'G1105V; CesA3; PHYTIN'

![image](https://github.com/PHI-base/curation/assets/11753634/b9e5d534-8e28-4a14-b55b-f0756461fc2c)



CesA3(aaG1105A)[Knockdown]
'G1105A; CesA3; PHYTIN'

![image](https://github.com/PHI-base/curation/assets/11753634/006a4a7e-27d2-4bac-b08a-535df0a83863)



![image](https://github.com/PHI-base/curation/assets/11753634/c0a75d71-4198-4640-9a25-c6849e440c49)
![image](https://github.com/PHI-base/curation/assets/11753634/d2e91e32-b5ed-4433-ab4d-2d86fe4c63e5)

**Comment by CuzickA** [comment]
**Next steps**
1) Connect new PHIPO and PHI-terms when available _DONE 31_01_2024_
2) add new strain DONE 31_01_2024 b97a12e
3) ask Nichola to check AE alteration in archetype

Then session will be ready to approve.

**Comment by CuzickA** [comment]
**Next steps**

1) ask Nichola to check AE alteration in archetype

Then session will be ready to approve.

**Comment by CuzickA** [comment]
Nichola has checked AE, looks fine.

Approving session and closing ticket.
