### ISSUE TITLE
PMID: 1423716 A single amino-acid change in the iron-sulphur protein subunit of succinate dehydrogenase confers resistance to carboxin in Ustilago maydis

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#165]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/534af7fad99f50d0

**Comment by MPiovesana** [comment]
Short paper where authors identify mutations in the _SDH2_ gene (Ip subunit of succinate dehydrogenase) of carboxin-resistant and -sensitive strains of _Ustilago maydis_. By comparing the _Ip_ alleles, authors identify a single amino acid substitution between the two, which is the presence of a histidine at position 253* of the Cbx-sensitive allele, and a leucine at the same position in the Cbx-resistant allele. Authors generated the Ip-Leu253 allele by site-directed mutagenesis of the Cbx-sensitive allele, which was transformed into the sensitive strain. Cbx-resistant transformants were identified, confirming that the His253Leu substitution confers resistance to this fungicide.

**NOTE**: typo in figure 3 identifies the His/Leu residue position as 257, when the correct numbering is **253**. The correct information is found at the text (last paragraph), which agrees with the numbering of the protein sequence deposited on Uniprot.

**Comment by MPiovesana** [comment]
**Uniprot ID:** by searching _SDH2 Ustilago maydis_ on Uniprot, a single entry is retrieved (**P32420**); the protein sequence associated with this entry corresponds with the one shown in the article.

**Comment by MPiovesana** [comment]
**Strain:** Cbx-sensitive strain IMI103761 was used as recipient for genetic transformation.

**Comment by MPiovesana** [comment]
**Genotype creation:** the _SDH2_ (_Ip_) allele from the recipient strain was used as template for the introduction of the mutation leading to the His253Leu substitution, and therefore, an allele type **amino acid substitution** was chosen when creating this genotype. Expression levels were not tested, but from the text we can infer that the mutant allele was introduced to be randomly integrated into the genome (no mention of homologous recombination/gene replacement); for this reason, **Ectopic** was selected. **Endogenous SDH2 present** was added to background.

**Comment by MPiovesana** [comment]
**Genotype annotation:** single annotation with PHIPO term "resistance to carboxin". Generation of carboxin-resistant transformants is only mentioned in the text (no figures/tables).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Single annotation looks fine

**Next steps**

1) add new strain to strain list _DONE 13_02_2024 ab13338_
2) try to add AE alteration in archetype _DONE 13_02_2024_

**Comment by CuzickA** [comment]
**AE alteration in archetype**

SDH2(aaH253L)[Ectopic] 'H277L; Sdh2 (SdhB); PYRNTE'

Issue with residue position, authors state 257 and 253 as noted above by Maiara. The correct numbering is 253. (see below for my FRAST alignments)

It looks at though both Nichola and the Mair et al group have used the incorrect residue position 257.


Nichola's table
![image](https://github.com/PHI-base/curation/assets/11753634/9f1369c5-0845-4836-9999-dfd260197112)

![image](https://github.com/PHI-base/curation/assets/11753634/f69fb5fc-53a8-48a9-a9ec-542a55683c67)


Mair et al 2016

![image](https://github.com/PHI-base/curation/assets/11753634/c8b23b1f-0c03-44ac-ba30-314abb709f3c)
![image](https://github.com/PHI-base/curation/assets/11753634/8274c66f-43ec-4e6a-972f-60db30079207)

Used FASTA AA sequence for reviewed https://www.uniprot.org/uniprotkb/P32420/entry
(Note Sdh2 = SdhB)

![image](https://github.com/PHI-base/curation/assets/11753634/bb2cf534-08be-4821-958a-f8a8c7f655c8)
![image](https://github.com/PHI-base/curation/assets/11753634/adad45ea-412d-4960-906f-0170804948ba)

This looks correct. 
There may have been an error in Nicola and Mair tables.

![image](https://github.com/PHI-base/curation/assets/11753634/dd3347ac-bf23-4598-a5c2-6de15f474eb5)

**Comment by CuzickA** [comment]
**Next steps**

1) check AE alteration in archetype with Nichola.

Then session will be ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
