### ISSUE TITLE
PMID:26596626 M233I Mutation in the β-Tubulin of Botrytis cinerea Confers Resistance to Zoxamide

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#166]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/48d1af1a77911425

**Comment by MPiovesana** [comment]
Spontaneous zoxamide-resistant mutants were generated in laboratory from a zoxamide-sensitive strain (NJ11). These mutants were phenotypically characterised (mycelial growth, sporulation, virulence) and their cross-resistance to several fungicides was also assessed. The zoxamide-resistant mutants were found to harbour a point mutation in _B-tubulin_ gene leading to the substitution of methionine with an isoleucine on position 233.

**Comment by MPiovesana** [comment]
**Uniprot ID:** GenBank accession number provided by the authors (U27198) was used to locate the Uniprot ID for this curation session (**P53373**).

**Comment by MPiovesana** [comment]
**Strain:** I manually entered strain _NJ11_, which was used as parental for the generation of spontaneous mutants in laboratory conditions. However, as this is a field isolate, should Unknown strain be selected instead?

AC: NJ11 is correct

**Comment by MPiovesana** [comment]
**Genotype creation:** a single allele was created to record the genotype of the zoxamide-resistant mutants generated in this study. The allele type **amino acid substitution** was selected and allele _tubA(aaM233I)_ was recorded.

**Comment by MPiovesana** [comment]
**Genotype annotations:** several PHIPO terms related to chemical resistance were assigned to this genotype:
resistance to zoxamide (suggested)
normal growth on carbendazim (suggested)
normal growth on thiram (suggested)
normal growth on procymidone (suggested)
normal growth on azoxystrobin (suggested)
normal growth on myclobutanil (suggested)
normal growth on iprodione (suggested)
normal growth on prochloraz (suggested)
normal growth on tebuconazole (suggested)
normal growth on fluazinam (suggested)
normal growth on pyrimethanil (suggested)
decreased rate of hyphae formation
asexual spores absent

A metagenotype between the mutant allele and tomato cv BeiBei was created to record the reduced virulence of the mutant; a control metagenotype (wt tubA + tomato) was also created and annotated for comparison.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Changing this annotation from 'normal...' to 'resistance...' See table 5 and text on page 8
![image](https://github.com/PHI-base/curation/assets/11753634/2767671f-3cc9-41f6-b1aa-2de315512c12)

was
![image](https://github.com/PHI-base/curation/assets/11753634/8f6cdf20-ede4-4659-aa54-36e44e7f508b)

now
![image](https://github.com/PHI-base/curation/assets/11753634/4178fc46-942c-4b28-937a-767f85b2c7c6)

**Comment by CuzickA** [comment]
I could not find any information to add **AE alteration in archetype**

**Comment by CuzickA** [comment]
New terms added, Approved, closing ticket

**Comment by CuzickA** [comment]
Try to look up archetype info on FRAST

**Comment by CuzickA** [comment]
From publication
'Based on the sequence U27198.1 published
in GenBank, three pairs of primers were designed for amplification of the full-length β-tubulin gene in
B. cinerea '

Look up Genbank entry https://www.ncbi.nlm.nih.gov/nuccore/U27198.1
Create AA FASTA file in notepad and save.
(22_09_2023) Enter sequence in FRAST against 'beta-tubulin'

![image](https://github.com/PHI-base/curation/assets/11753634/83736122-ee77-4df2-b807-b42492a6d0d7)

Codon 233 in the sequence index is 'M' which aligns with codon 233 'M' in the beta-tubulin archetype sequence.

Bc tubA(aaM233I)[Not assayed] 'M233I; TubA/BenA (β-tubulin); ASPEND'

Note: TubA and BenA are synonyms
https://www.uniprot.org/uniprotkb/P53373/entry
![image](https://github.com/PHI-base/curation/assets/11753634/3ef33ad2-8c89-4e80-a1a4-7221aa3483e0)

Uniprot uses 'tubA' as the primary name and so the genotypes have been created with this name. The Genbank entry for the author listed sequence in https://www.ncbi.nlm.nih.gov/nuccore/U27198.1 is 'benA'.

Not quite sure how to proceed here, so for now suggest record information like this 'M233I; TubA/BenA (β-tubulin); ASPEND'

Added AE to session.
Saved FRAST MAFFT output in notepad and saved session in FRAST
![image](https://github.com/PHI-base/curation/assets/11753634/8479a07c-4c58-454a-872f-2112938a9b97)

**Comment by CuzickA** [comment]
Next step
Check FRAST alignment info with Nichola and best naming convention for 'TubA/BenA (β-tubulin)'

**Comment by CuzickA** [comment]
Agreed to use 'M233I; TubA/BenA (β-tubulin); ASPEND'

**Comment by CuzickA** [comment]
Nichola has checked archetype AE.

Approving session and closing ticket.
