### ISSUE TITLE
PMID:27242773 C239S Mutation in the β-Tubulin of Phytophthora sojae Confers Resistance to Zoxamide

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#167]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/cbee79c9ba230adf

**Comment by MPiovesana** [comment]
Spontaneous zoxamide-resistant mutants of _Phytophthora sojae_ were isolated in this study from parental strain PsJMS2. Mutants were phenotypically characterised and found to carry a point mutation in the _β-Tubulin_ gene, leading to amino acid substitution C239S. The mutation was back-transformed into wild type strain P6497 and transformants exhibited zoxamide-resistant, as expected. The genotype of the mutant and transformant were curated in this session; this is to allow the creation and comparison of the metagenotype composed of the mutant pathogen genotype compared to the WT PsJMS2 control.

**Comment by MPiovesana** [comment]
**Uniprot ID:** after identifying the reference proteome for _P. sojae_ on Uniprot, a gene name search retrieved ID **G4ZQS2** for the _β-Tubulin_ gene.

**Strains:** strains PsJMS2 and P6497 were added to curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** 
The genotype of the spontaneous mutants derived from strain PsJMS2 was recorded as below:
**βTub(aaC239S)[Not assayed]** = to indicate the aa substitution in the βTub gene.

The genotype of the transformants obtained from strain P6497 was recorded as below:
**βTub transformant(RZ11-1-βTub(C239S))[Ectopic]** = to indicate the introduction of the βTub gene from mutant strain RZ11-1, which harbours the C239S mutation. Expression was selected as ectopic. _Endogenous βTub present_ was added to background.

**Comment by MPiovesana** [comment]
**Genotype annotations:**
The PsJMS2 genotype was annotated with the following terms:
resistance to zoxamide (suggested)
normal number of asexual spores
normal asexual spore germination frequency
normal growth on chlorothalonil (suggested)
normal growth on azoxystrobin (suggested)
normal growth on cymoxanil (suggested)
normal growth on metalaxyl (suggested)
normal growth on flumorph (suggested)

**Comment by MPiovesana** [comment]
**Metagenotype creation:** a metagenotype was created including the mutant allele in the PsJMS2 background and _G. max_ (cv Williams). As the three isolated mutants with the same genotype showed varying levels of infectivity, I selected the PHIPO term "presence of pathogen-associated host lesions" for both control and altered metagenotype, and added **has_severity** variable severity as an annotation extension for the altered metagenotype.
AC I also added infective ability 'reduced virulence' as shown by 2 of the 3 mutant lines.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Phytophthora sojae is an oomycete, rather than a fungus, so may need flagging up in the table of curated papers.

**Comment by CuzickA** [comment]
I couldn't find archetype info for B-tubulin P sojae in Nichola's S file or the Mair et al 2016 publication.

**Comment by CuzickA** [comment]
New terms added, session approved, closing ticket.

**Comment by CuzickA** [comment]
Try and and look up archetype info in FRAST

**Comment by CuzickA** [comment]
I could not find a Gene id in the publication.

Is it ok to do this search in Genbank 'B-tubulin Phytophthora sojae' and use this entry (there was only one) https://www.ncbi.nlm.nih.gov/nuccore/829497727
Generated AA FASTA file in notepad and saved.
FRAST alignment (22_09_2023)

![image](https://github.com/PHI-base/curation/assets/11753634/1868bb62-4486-4272-b8e6-3114af7dc09b)

**NOTE (18_10_2023) This residue number alignment is not correct- see comment below after discussion with Nichola.**
~Codon~ **Residue** 239 in the sequence index is 'S' which aligns with with archetype index ~codon~ **residue** 352 but a different wildtype AA 'A' in the Cyp51A archetype sequence.
Ps βTub(aaC239S)[Not assayed] '352S; β-tubulin; ASPEND'

Saved mafft in notepad and session in FRAST
![image](https://github.com/PHI-base/curation/assets/11753634/c20670c8-f7d8-4f20-aef9-af8050dd2105)

**Comment by CuzickA** [comment]
Next step
Check this with Nichola. If this looks ok then add to the curation session.

**Comment by CuzickA** [comment]
After discussion with Nichola

Above is incorrect due to a partial genbank seq causing a tricky alignment. 

In the above Residue 239 in the sequence index is 'S' which is the mutated AA residue C239S. This does not make sense. Either the input sequence represents the mutant sequence or the alignment is incorrect.

From the publication
![image](https://github.com/PHI-base/curation/assets/11753634/4c23d280-fe62-4622-bcb7-2e769fade915)

If we try and match up AA by eye we can see that the above AE suggestion is incorrect. Instead of looking at the input sequence at 239 we need to look at the archetype sequence at 239. This then corresponds with the input sequence of 126. Note: the residue position in the AE relates to the archetype seq and not the input seq and thus would be 239 and not 126. The sequences align as expected with 'C' being located at 239/126. (Went back to past saved FRAST alignment to make this screenshot.)

![image](https://github.com/PHI-base/curation/assets/11753634/8a006920-2fd8-46e6-bd1d-ff06c72d15d7)



Therefore change AE to
'C239S; β-tubulin; ASPEND'

**Comment by CuzickA** [comment]
Added AE alteration in archetype.

Approved session. Closing ticket.
