### ISSUE TITLE
PMID:19900007 Mutations in a beta-tubulin confer resistance of Gibberella zeae to benzimidazole fungicides

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#168]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/61b19e1cc3d55d37

**Comment by MPiovesana** [comment]
Natural isolates of _Gibberella zeae_ with susceptible or moderate/high resistance to carbendazim are described in this paper. The sequence of the _β-tubulin_ gene of these strains was analysed and point mutations were identified. Deletion and complementation lines were generated to confirm the link between _β-tubulin_ alleles and chemical resistance phenotypes. 
**NOTE**: I think the curation of this paper is a little tricky as ideally we would need to add 3 Uniprot IDs, one for the β-tubulin sequence of each mutant. Below I explained my rationale for the curation so far, but perhaps it needs to be discussedl.

**Comment by MPiovesana** [comment]
**Uniprot ID:** searching the reference proteome of _G. zeae_ in Uniprot, entry **Q4HZS8** was retrieved for _β-tubulin_.

**Strains:** strains 2021 (sensitive), R9 (moderately resistant) and JT04 (highly resistant) were added to this curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** deletion lines of all three strains were recorded as _βTubΔ_. The complementation lines were recorded as transformant alleles with _βTubΔ_ as background:

**βTub transformant(R9-βTub(F167Y))**: βTub from strain R9 harbouring aaF167Y (inserted in 2021)

**βTub transformant(JT04-βTub(G73R Q198L))**: βTub from strain JT04 harbouring aaG73A Q198L (inserted in 2021)

**βTub transformant(2021-βTub(Y167F))**: βTub from strain 2021 harbouring aaY167F (inserted in R9)

**βTub tranformant(2021-βTub(R73G L198Q)**: βTub from strain 2021 harbouring aaR73G L198Q (inserted in JT04)

Transformant alleles were assigned **ectopic** expression level.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotypes were annotated with PHIPO terms "sensitive / resistance to carbendazim" as appropriate.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
> NOTE: I think the curation of this paper is a little tricky as ideally we would need to add 3 Uniprot IDs, one for the β-tubulin sequence of each mutant. Below I explained my rationale for the curation so far, but perhaps it needs to be discussedl.

I think this UniProt query relates to the fact that we cannot curate the natural sequence variation in the following

> Strains: strains 2021 (sensitive), R9 (moderately resistant) and JT04 (highly resistant)

and the reference UniProt sequence may also be different. 

This is an issue we are aware of. In the future we may try to enable an option in PHI-Canto to load individual sequences, but this is not possible at the moment.


![image](https://github.com/PHI-base/curation/assets/11753634/993acfd4-30f1-48d0-8ebd-6be55c37e891)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/3c3699ed-61d3-4cd6-aa24-337416f887bb)

I think there may be an issue with the AA alterations here

In the Table

![image](https://github.com/PHI-base/curation/assets/11753634/2e815a14-4a91-48e1-9211-a27494dc4b9d)

It looks like the changes between strain 2021 and JT04 should be Q73R, E198L . @MPiovesana please could you double check this for me? Or have I misread something?

**Comment by MPiovesana** [comment]
> It looks like the changes between strain 2021 and JT04 should be Q73R, E198L . @MPiovesana please could you double check this for me? Or have I misread something?

@CuzickA Yes indeed, I can see now that I made a mistake with the one-letter code for these residues, apologies for that! Depending on the direction of the genetic transfer (2021 to JT04 or JT04 to 2021), the alleles should read:

βTub transformant(JT04-βTub(**Q73R** **E198L**)): βTub from strain JT04 harbouring aaQ73A E198L (inserted in 2021)

βTub tranformant(2021-βTub(**R73Q** **L198E**): βTub from strain 2021 harbouring aaR73Q L198E (inserted in JT04)

**Comment by CuzickA** [comment]
Thanks for double checking @MPiovesana. I'll make the changes as I check the session :-)

**Comment by MPiovesana** [comment]
@CuzickA thank you very much and apologies for the confusion again!

**Comment by CuzickA** [comment]
Now looks like this

![image](https://github.com/PHI-base/curation/assets/11753634/a1db7164-37b2-4f13-b17e-d5178fdb2a5b)

Note: AE alteration to archetype only add to the annotations where the direction of change is a shift towards resistance.

Approving session and closing ticket

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F167Y; β-tubulin; ASPEND
Q73R, E198L; β-tubulin; ASPEND

Straight forward to find in Nichola's S file in Table S1
![image](https://github.com/PHI-base/curation/assets/11753634/ba9b2283-82dc-4202-a5b6-54f3eaa14db1)
![image](https://github.com/PHI-base/curation/assets/11753634/7e7bbd0d-02c2-43dc-a698-9246fba5f9ef)
![image](https://github.com/PHI-base/curation/assets/11753634/309afaa8-d922-44a1-9687-9fd03626be3e)
![image](https://github.com/PHI-base/curation/assets/11753634/9751532a-13bb-42ea-bc3a-edec861d7a72)

**Question**
Same question about double mutants as in https://github.com/PHI-base/curation/issues/144

**Comment by CuzickA** [comment]
Same question about double mutants as in https://github.com/PHI-base/curation/issues/144 This is ok

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
