### ISSUE TITLE
List of publications for PHI-canto training videos

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#17]
@kehammond has suggested we make training tutorials to cover the main paper types

**Receptor decoys** (PMID:30220500) Suppression of Plant Immunity by Fungal Chitinase-like Effectors. #18 

**R-Avr interactions** (PMID:20601497) Activation of an Arabidopsis resistance protein is specified by the in planta association of its leucine-rich repeat domain with the cognate oomycete effector. #19 

**Secondary metabolite clusters required for pathogen virulence** (PMID:30459352) Phosphopantetheinyl transferase (Ppt)-mediated biosynthesis of lysine, but not siderophores or DHN melanin, is required for virulence of Zymoseptoria tritici on wheat. #23 

**Early acting virulence proteins** (PMID: 29020037) A conserved fungal glycosyltransferase facilitates pathogenesis of plants by enabling hyphal growth on solid surfaces. #24 

**1st host targets of pathogen effectors** (PMID:26822079) A Phytophthora infestans RXLR effector targets plant PP1c isoforms that promote late blight disease. #21 

**fungal toxins required for virulence on plants** (PMID:22241993) The cysteine rich necrotrophic effector SnTox1 produced by Stagonospora nodorum triggers susceptibility of wheat lines harboring Snn1. #22 

**bacteria-human interaction** (PMID:28715477) The RhlR quorum-sensing receptor controls Pseudomonas aeruginosa pathogenesis and biofilm development independently of its canonical homoserine lactone autoinducer. #34 

**fungal-human interaction/novel antifungal target** ( PMID:28720735) A Nonredundant Phosphopantetheinyl Transferase, PptA, Is a Novel Antifungal Target That Directs Secondary Metabolite, Siderophore, and Lysine Biosynthesis in Aspergillus fumigatus and Is Critical for Pathogenicity. #36 

I have also already started looking at phenotypes for 
PMID:30603875 FgPEX4 is involved in development, pathogenicity, and cell wall integrity in Fusarium 
graminearum.  Which would also be likely classed as **Early acting virulence proteins** #25

**Comment by CuzickA** [comment]
@CuzickA and @ValWood plan to curate each paper in PHI-canto together. 

We will identify new terms required to add to phipo, expt evidence and conditions. Once these terms have been created they can be made available in PHI-Canto for use in updating our annotations.
We will also see if the existing GO terms are suitable and request updates or new terms as required.

Once we have the basic terms in place for curating a given paper, we can remove the entry from PHI-Canto and re-enter the paper whilst taking screenshots or video capture for the training tutorial.

A separate issue will be made for each paper to track the progress, link the curation session, cross-ref additional issues on other trackers and record general queries.

**Comment by ValWood** [comment]
@pgaudet is interested for GO. 
@CuzickA  we can chat about this soon.

**Comment by CuzickA** [comment]
#51 session now approved and ticket closed. This session will be turned into a 'Chemistry' curation training video. 
PMID:22314539 The T788G mutation in the cyp51C gene confers voriconazole resistance in Aspergillus flavus causing aspergillosis.

**Comment by CuzickA** [comment]
Trial paper curations published in PHI-Canto article. Closing ticket.
