### ISSUE TITLE
PMID:24913566 Molecular mechanism of resistance of Fusarium fujikuroi to benzimidazole fungicides.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#170]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/57500a0e921e0d10#

**Comment by MPiovesana** [comment]
In this paper three wild type strains of _Fusarium fujikuroi_ are characterised based on their sensitivity to the fungicide carbendazim (MBC). Authors sequence the _β2Tub_ gene of these strains, and identify mutations present in the sensitive (YC3), moderately resistant (YCA) and highly resistant (YC4201) strains. Deletion lines of _β2Tub_ are generated and phenotypically characterised. Complementation lines are also generated by re-introducing the _β2Tub_ gene in each respective background. The genotypes of the deletion lines were curated in this session.

**Comment by MPiovesana** [comment]
**Uniprot IDs:** authors provide the GenBank accession numbers for the _β2Tub_ sequence of all three strains, which were used to retrieve respective Uniprot IDs:

KF771181 = **W5RZY1** (_β2Tub_ of sensitive strain YC3)
KF771182 = **W5RYV3** (_β2Tub_ of moderate resistant strain YCA)
KF771183 = **W5RZ16** (_β2Tub_ of highly resistant strain YC4201)

By using all three IDs in the curation session, it was possible to create individual deletion lines to record the phenotypes of all mutants described in the study.

AC: see comment below about needing to use one reference proteome uniprot id.

**Comment by MPiovesana** [comment]
**Strains:** strains YC3, YCA and YC4201 were manually added to the session.

**Comment by MPiovesana** [comment]
**Genotype creation:** deletion lines of _β2Tub_ were created for all three strains, and a description of aa residues on positions of interest (codons 198 and 200) were added in brackets in the allele name. Codon 235 is also described in Table 1, but mutations in this codon are synonymous and, therefore, do not lead to aa change.
Wild type alleles for all three strains were also created for metagenotype purposes.


AC: genotypes changed to use reference proteome uniprot. In the case of the deletion mutants the natural variation of aa residues were removed as this gene id deleted.
![image](https://github.com/PHI-base/curation/assets/11753634/ff03e0b6-74f8-47a0-9b71-27501aa73c94)
changed to
![Uploading image.png…]()

**Comment by MPiovesana** [comment]
**Genotype annotations:** the following PHIPO terms were used:
sensitive to carbendazim
decreased rate of hyphae formation
decreased number of asexual spores

**Comment by MPiovesana** [comment]
**Metagenotypes:** metagenotypes were created including wt and deletion alleles of _β2Tub_ and tomato (_S. lycopersicum_ in PHI-Canto; referred to as _Lycopersicon esculentum_ in the paper. Both names refer to the same species to the best of my knowledge) cv. Kaisa. Control metagenotypes were assigned PHIPO term presence of _pathogen-associated host lesions_, and deletion metagenotypes with _decreased extent of pathogen-associated host lesions_.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
> **Uniprot IDs:** authors provide the GenBank accession numbers for the _β2Tub_ sequence of all three strains, which were used to retrieve respective Uniprot IDs:
> 
> KF771181 = **W5RZY1** (_β2Tub_ of sensitive strain YC3) KF771182 = **W5RYV3** (_β2Tub_ of moderate resistant strain YCA) KF771183 = **W5RZ16** (_β2Tub_ of highly resistant strain YC4201)
> 
> By using all three IDs in the curation session, it was possible to create individual deletion lines to record the phenotypes of all mutants described in the study.

We will need to use the same 'reference proteome' UniProt id for all the annotations in this session so that they are available on one PHI5 gene page. 

Sessions annotating the same gene use P53374 https://www.uniprot.org/uniprotkb/P53374/entry
see https://github.com/PHI-base/curation/issues/195 and https://github.com/PHI-base/curation/issues/194

I will update the UniProt id in the session.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/bf2e8f78-909e-4400-b308-559beb47a886)
![image](https://github.com/PHI-base/curation/assets/11753634/120438ad-e17a-4538-ac9b-af9af0cd30f2)
![image](https://github.com/PHI-base/curation/assets/11753634/5720f19d-2a1e-4a46-bb6d-3a49338fe025)

![image](https://github.com/PHI-base/curation/assets/11753634/981b8134-58cc-4f38-96bc-ba9e62c465ae)
![image](https://github.com/PHI-base/curation/assets/11753634/52bd4023-b4ca-4ed5-981d-bc17d1a080ac)
![image](https://github.com/PHI-base/curation/assets/11753634/90f01b41-ba56-4a72-bae7-aba40b45eb83)
![image](https://github.com/PHI-base/curation/assets/11753634/cd313e49-22c0-4db8-887d-749de12e037b)

**Comment by CuzickA** [comment]
Updated pathogen phenotypes
![image](https://github.com/PHI-base/curation/assets/11753634/14448df8-047d-4ebf-b858-93ec3fac3871)
![image](https://github.com/PHI-base/curation/assets/11753634/1ad95dbc-39f6-49b5-8795-8512d4dd496d)

N/A AE alteration in archetype as deletion mutants

**Comment by CuzickA** [comment]
PHI phenotypes chnaged to
![image](https://github.com/PHI-base/curation/assets/11753634/78c220e6-662c-427f-b5ba-3227972a9784)
![image](https://github.com/PHI-base/curation/assets/11753634/ff427ee6-cb0a-43c4-8ce2-d4dcac31fae4)


Note: known aa due to natural variation recorded in background for the pathogen WT component of metagenotypes.

**Comment by CuzickA** [comment]
Genotypes and metagenotypes now look like this

![image](https://github.com/PHI-base/curation/assets/11753634/ed10aafd-81a4-45a0-b620-a5f1ca13d57f)


![image](https://github.com/PHI-base/curation/assets/11753634/327488aa-8c1d-4179-ae66-1322a4817f53)

![image](https://github.com/PHI-base/curation/assets/11753634/ff9053f4-aa64-455a-b916-c379a7320ad3)

**Comment by CuzickA** [comment]
No 'disease name' annotation as from paper text
'The main species causing rice bakanae in China is F. fujikuroi.'

however, in this expt F. fujikuroi is inoculated onto tomato.

**Comment by CuzickA** [comment]
Session approved, closing ticket
