### ISSUE TITLE
PMID:15504870 In vitro evolution of itraconazole resistance in Aspergillus fumigatus involves multiple mechanisms of resistance

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#171]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/7700f6fcef8b7f8e

**Comment by MPiovesana** [comment]
In this paper, authors generate itraconazole-resistant mutants by directed evolution of the wild type strain CEA17 of _Aspergillus fumigatus_. A number of mutants are isolated, which are found to harbour several point mutations in the _CYP51A_ and _CYP51B_ genes. Authors perform a gene replacement experiment to confirm the involvement of _CYP51A_ mutations in itraconazole resistant, and find that only two of the mutations (N22D and M220I) chance the susceptibility of CEA17 to the fungicide. This result is only mentioned in the text followed by (data not shown). As only two of these mutations were confirmed to be involved with the chemical resistance phenotype, I decided to only curate these two alleles as transformants in the CEA17 background.

**Comment by MPiovesana** [comment]
**Uniprot ID:** _CYP51A_ of _A. fumigatus_ was promptly identified in Uniprot (**Q4WNT5**).

**Strain**: CEA17 was selected.

**Comment by MPiovesana** [comment]
**Genotype creation:** the following genotypes were created:

**cyp51A transformant(H10-1-50A-cyp51A(N22D))** = transformant allele; _cyp51A_ allele from strain H10-1-50A harbouring N22D mutation;

**cyp51A transformant(H10-2-50A-cyp51A(M220I))** = transformant allele; _cyp51A_ allele from strain H10-2-50A harbouring M220I mutation

Cyp51Adelta was added to the background of both genotypes.

**Comment by MPiovesana** [comment]
**Genotype annotation:** both genotypes were annotated with PHIPO term _resistance to itraconazole_. No other phenotypical characteristic for the transformant lines is described in the study.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

N22D; Cyp51A; ASPEFU
M220I; Cyp51A; ASPEFU

**Questions for Nichola**

Are these correct? I could not find info on Cyp51A in your S file. I found the above information from Table 2 in Mair et al 2016.

![image](https://github.com/PHI-base/curation/assets/11753634/bf6ba8f7-d4bc-4270-bb80-7c615700214d)
![image](https://github.com/PHI-base/curation/assets/11753634/5ff5615e-2ff9-431b-8eca-8b61eb3ea36c)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/979c935d-d573-4ce3-b911-317492e3820e)

Approving session once AE checked. Closing ticket.

**Comment by CuzickA** [comment]
Are these correct? I could not find info on Cyp51A in your S file. I found the above information from Table 2 in Mair et al 2016.
YES this is correct

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
