### ISSUE TITLE
PMID:25385095 Contribution of Clinically Derived Mutations in ERG11 to Azole Resistance in Candida albicans

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#172]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/62cb96b3dd46d2d0

**Comment by MPiovesana** [comment]
Clinical isolates of _Candida albicans_ which display resistance to itraconazole are characterised in this paper. They are found to carry several mutations in the _ERG11_ gene, and the mutant alleles are introduced in the wild type susceptible strain SC5314 by gene replacement. The susceptibility of transformants to itraconazole is described.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a name search on Uniprot (_ERG11 Candida albicans_) returned the entry **P10613**.

AC: This is a Swiss-Prot reviewed entry https://www.uniprot.org/uniprotkb/P10613/entry

**Comment by MPiovesana** [comment]
**Genotype creation:** allele type _amino acid substitution(s)_ was used to create the genotypes of the transformants described in this study. All of the mutant genotypes described in Figure 2 were created.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotypes were annotated with the most relevant phenotypes as described by the authors on page 453, referencing Figure 2. Curation of additional phenotypes would be possible ("normal growth on..."), but as authors focused on the increased resistance to fluconazole, I believe the current curations reflect the main findings of the paper.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Candida albicans is a diploid organism. All curated mutants in this session are homozygous and therefore it is not necessary to use 'diploid mode'. We cannot currently display 'diploid genotypes' in PHI5.

**Comment by CuzickA** [comment]
Adding AE alteration in archetype
Query - which cyp51a or cyp51b paralogue to map single copy erg11/cyp51 to?
Could not find Candida albicans listed in Nichola's S files.
In Mair et al 2016, I have found this information in Table 3 Cyp51B.
ERG11(aaG464S)
![image](https://github.com/PHI-base/curation/assets/11753634/997b0deb-e6af-4e7b-aee9-58de8322a904)
![image](https://github.com/PHI-base/curation/assets/11753634/3570b35f-2f5d-43c7-8b61-a9a7f91d6d36)
Therefore I believe the AE would be
G476; Cyp51B; SEPTTR  (I'm not sure why there is not an AA listed after the residue number in the Mair et al table). 

_update to G476S; ERG11 (Cyp51B); SEPTTR_

**Comment by CuzickA** [comment]
1) ERG11(aaG450E) nothing in Mair Table 3 **_Maybe G462E; ERG11 (Cyp51B); SEPTTR from FRAST below._**

2) ERG11(aaF449V) **AC: add this as aa461V (NH codon info useful, different wildtype, to follow up in manuscript)** _'461V; ERG11 (Cyp51B); SEPTTR'_
![image](https://github.com/PHI-base/curation/assets/11753634/526fb956-22cc-4b5a-9543-1ef2fe2b44fe)
I have not added this as the change is F->V not F->S

3) ERG11(aaG448E) nothing in Mair Table 3 **_Maybe 'G460E; ERG11 (Cyp51B); SEPTTR' from FRAST below._**

4) ERG11(aaD446E) nothing in Mair Table 3 **_Maybe D458E; ERG11 (Cyp51B); SEPTTR from FRAST below_**

5) ERG11(aaS405F)
![image](https://github.com/PHI-base/curation/assets/11753634/fd4ccb54-1cc8-445b-82b6-92831adc7c17)
Therefore I believe the AE would be
A410T; Cyp51B; SEPTTR **_Actually I think this should be ' 410F; ERG11 (Cyp51B); SEPTTR' -TO CHECK_** note different than Wt

6) ERG11(aaF145L) nothing in Mair Table 3 _**Maybe 'F150L; ERG11 (Cyp51B); SEPTTR' from FRAST below.**_ _-but we don't know Wt AA_ **-we do now, look at lower FRAST screenshot**

7) ERG11(aaK143R)
![image](https://github.com/PHI-base/curation/assets/11753634/85bae6b6-2371-4e67-ae61-2f2ee0bc4d74)
I have not added this as the change is K->R not K->E
**Add K148E; Cyp51B; SEPTTR** _**Actually I think this should be ' K148E; ERG11 (Cyp51B); SEPTTR'**_ -TO CHECK Note: no mutation found yet at this codon position in the archetype species Zt
8) ERG11(aaY132F)
![image](https://github.com/PHI-base/curation/assets/11753634/26515285-6122-4bfa-bb36-88ce49790383)
Therefore I believe the AE would be
Y137F; ERG11 (Cyp51B); SEPTTR

**Comment by CuzickA** [comment]
Need to check AE alteration in archetype with Nichola.
For now session approved and closing ticket.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

Y137F; ERG11 (Cyp51B); SEPTTR
A410T; Cyp51B; SEPTTR _(update to 410F; ERG11 (Cyp51B); SEPTTR)_
G476; Cyp51B; SEPTTR _(update to G476S; ERG11 (Cyp51B); SEPTTR)_

**Questions for Nichola**
1) Which cyp51a or cyp51b paralogue to map single copy erg11/cyp51 to? What about naming within the AE, should we maybe use 'Erg11 (Cyp51B)' following comment in https://github.com/PHI-base/curation/issues/144
_AC: single copy cyp51 is classed as cyp51B. 'Erg11 (Cyp51B)' -YES_
2) Could not find Candida albicans listed in Nichola's S files. Is it okay to use the above info. from the Mair et al 2016 paper?
_YES, additional AA alterations not found in S file or Mair paper can be looked up on FRAST. (Nichola will try and get this to work)_
3) Is this correct? G476; Cyp51B; SEPTTR (I'm not sure why there is not an AA listed after the residue number in the Mair et al table).
_A second AA is not listed in this case as a mutation has not been identified in the archetype species at this codon position yet. Following our criteria we will add in the equivalent residue alteration as observed in the primary species being annotated ie G476S; Cyp51B; SEPTTR_

**Comment by CuzickA** [comment]
single copy cyp51 is classed as cyp51B

**Comment by CuzickA** [comment]
to follow up, some changes required and Nichola to do FRAST alignments

**Comment by CuzickA** [comment]
To checked further with Nichola
1) C. albicans ERG11(aaK143R)[Not assayed] K148R; ERG11 (Cyp51B); SEPTTR from Mair Table 3 see comment above.
2) C. albicans ERG11(aaS405F)[Not assayed] 410F; ERG11 (Cyp51B); SEPTTR from Mair Table 3 see comment above.
3) C. albicans ERG11(aaF145L)[Not assayed] **F**150L; ERG11 (Cyp51B); SEPTTR from FRAST below. (point 6 above) - can't see Wt AA at position 150 in the archetype screenshot below. (See FRAST below)
4) C. albicans ERG11(aaD446E)[Not assayed] D458E; ERG11 (Cyp51B); SEPTTR from FRAST below. (point 4 above)
5) C. albicans ERG11(aaG448E)[Not assayed] G460E; ERG11 (Cyp51B); SEPTTR from FRAST below. (point 3 above)
6) C. albicans ERG11(aaG450E)[Not assayed] G462E; ERG11 (Cyp51B); SEPTTR from FRAST below. (point 1 above)

Note: 3-6 FRAST derived AEs have not been added to curation session yet.

**Comment by CuzickA** [comment]
Screenshot from Nichola's email, looking up the information in FRAST
![image](https://github.com/PHI-base/curation/assets/11753634/6281878b-667a-480e-83d3-25882f2dd161)

**Comment by CuzickA** [comment]
Trying FRAST myself 19_09_2023

From paper 'C. albicans sequence (GenBank accession no. XM_711668)' **AC: See below 22_09_2023**
UniProt search gives https://www.uniprot.org/uniprotkb?query=XM_711668
Download AA FASTA sequence
Select input 'reference' and 'Cyp51B' and 'next'
![image](https://github.com/PHI-base/curation/assets/11753634/4b23eb28-4df1-4bd8-a6a0-cd5a3af0926a)

Copy and paste in AA FASTA file and select 'next'
![image](https://github.com/PHI-base/curation/assets/11753634/01f6e9d7-f05f-43e0-8e5f-100b4f9ff345)

'alignment' 'view output'
![image](https://github.com/PHI-base/curation/assets/11753634/fccf70cc-d3ae-45fa-a3a9-dc5fc5b396fe)

![image](https://github.com/PHI-base/curation/assets/11753634/013b7371-d6ba-4b82-bc42-671b4c61a40d)
 
Missing info, now captured in this screenshot for codon 145/150
C. albicans ERG11(aaF145L)[Not assayed] F150L; ERG11 (Cyp51B); SEPTTR
It looks as though the 'F' is correct.

**Comment by CuzickA** [comment]
Logged into account via Goggle
![image](https://github.com/PHI-base/curation/assets/11753634/70ca5ed8-1d61-4395-9a55-5a8bd1e58a4f)

Under 'Sessions'
![image](https://github.com/PHI-base/curation/assets/11753634/47520d03-32fd-4652-8107-67dd44f04ef1)

**Comment by CuzickA** [comment]
Nichola says AE's look correct

**Comment by CuzickA** [comment]
See #51 for update on generating AA FASTA file from Genbank instead of UniProt as I have done above.

From paper 'C. albicans sequence (GenBank accession no. XM_711668)'
https://www.ncbi.nlm.nih.gov/nuccore/XM_711668
Generated 'notepad' file with AA sequence under a FASTA heading and saved this.

Double check the four FRAST alignments _All look correct

C. albicans ERG11(aaF145L)[Not assayed] F150L; ERG11 (Cyp51B); SEPTTR
![image](https://github.com/PHI-base/curation/assets/11753634/a0fff679-3076-4663-8393-f228abcd89ff)

C. albicans ERG11(aaD446E)[Not assayed] D458E; ERG11 (Cyp51B); SEPTTR
C. albicans ERG11(aaG448E)[Not assayed] G460E; ERG11 (Cyp51B); SEPTTR
C. albicans ERG11(aaG450E)[Not assayed] G462E; ERG11 (Cyp51B); SEPTTR
![image](https://github.com/PHI-base/curation/assets/11753634/72dd1053-f836-4e81-b023-d49b6818dfd0)

Downloaded MAFFT file into Notepad and saved search in FRAST
![image](https://github.com/PHI-base/curation/assets/11753634/c6ab7259-6be1-4e7b-939d-3588e565cb6a)
![image](https://github.com/PHI-base/curation/assets/11753634/0d1ca053-21f0-4de2-b189-9f7310c20785)

**Comment by CuzickA** [comment]
Single mutant AEs now added

![image](https://github.com/PHI-base/curation/assets/11753634/b8aaf307-4356-4c92-8bcb-be154aac8459)
![image](https://github.com/PHI-base/curation/assets/11753634/9f09a8d5-5753-44be-89d5-fa431b789390)

**Comment by CuzickA** [comment]
Double mutants

ERG11(aaY132F K143R)[Not assayed] 'Y137F, K148R; ERG11 (Cyp51B); SEPTTR'
ERG11(aaY132F F145L)[Not assayed] 'Y137F, F150L; ERG11 (Cyp51B); SEPTTR'
ERG11(aaG307S G450E)[Not assayed] 'XXXX, G462E; ERG11 (Cyp51B); SEPTTR'
ERG11(aaK143R E266D)[Not assayed] 'K148R, XXXX; ERG11 (Cyp51B); SEPTTR'
ERG11(aaI483V G450E)[Not assayed]  'XXXX, G462E; ERG11 (Cyp51B); SEPTTR'
ERG11(aaM258L G464S)[Not assayed] 'XXXX, G476S; ERG11 (Cyp51B); SEPTTR'
ERG11(aaD278N G464S)[Not assayed] 'XXXX, G476S; ERG11 (Cyp51B); SEPTTR'
ERG11(aaE266D G464S)[Not assayed] 'XXXX, G476S; ERG11 (Cyp51B); SEPTTR'
ERG11(aaF145L E266D)[Not assayed] 'F150L, XXXX; ERG11 (Cyp51B); SEPTTR'

Looks like a few more to look up
Ca ERG11(aaG307S)
Ca ERG11(aaE266D)
Ca ERG11(aaI483V)
Ca ERG11(aaM258L)
Ca ERG11(aaD278N)

**Comment by CuzickA** [comment]
Ca ERG11(aaG307S) Not in Mair et al Table 3
![image](https://github.com/PHI-base/curation/assets/11753634/c13ab096-07ee-46a3-81af-ed1c2e8a9a84)

Codon 307 in the sequence index is 'G' which aligns with archetype index codon 311 but a different wildtype AA 'A' in the Cyp51B archetype sequence.
use '311S; ERG11 (Cyp51B); SEPTTR', no first AA listed as Wts different.

Therefore for 
ERG11(aaG307S G450E)[Not assayed] '311S, G462E; ERG11 (Cyp51B); SEPTTR'

**Comment by CuzickA** [comment]
Ca ERG11(aaE266D) Not in Mair et al Table 3
![image](https://github.com/PHI-base/curation/assets/11753634/64fca15b-54ba-4e65-83c6-deee1ee70efc)

Codon 266 in the sequence index is 'E' which aligns with archetype index codon 271 with same wildtype AA 'E' in the Cyp51B archetype sequence.
use 'E271D; ERG11 (Cyp51B); SEPTTR'

Therefore for
ERG11(aaK143R E266D)[Not assayed] 'K148R, E271D; ERG11 (Cyp51B); SEPTTR'
ERG11(aaE266D G464S)[Not assayed] 'E271D, G476S; ERG11 (Cyp51B); SEPTTR'
ERG11(aaF145L E266D)[Not assayed] 'F150L, E271D; ERG11 (Cyp51B); SEPTTR'

**Comment by CuzickA** [comment]
Ca ERG11(aaI483V) Not in Mair et al Table 3
![image](https://github.com/PHI-base/curation/assets/11753634/2c77e6f5-6353-4e9d-8200-02c9b2172ec1)

Codon 483 in the sequence index is 'I' which aligns with archetype index codon 495 with same wildtype AA 'I' in the Cyp51B archetype sequence.
use 'I495V; ERG11 (Cyp51B); SEPTTR'

ERG11(aaI483V G450E)[Not assayed] 'I495V, G462E; ERG11 (Cyp51B); SEPTTR'

**Comment by CuzickA** [comment]
Ca ERG11(aaM258L) Not in Mair et al Table 3

![image](https://github.com/PHI-base/curation/assets/11753634/41391753-215b-4ed2-a2d3-5766137663a2)

Codon 258 in the sequence index is 'M' which aligns with archetype index codon 263 with same wildtype AA 'M' in the Cyp51B archetype sequence.
use 'M263L; ERG11 (Cyp51B); SEPTTR'

ERG11(aaM258L G464S)[Not assayed] 'M263L, G476S; ERG11 (Cyp51B); SEPTTR'

**Comment by CuzickA** [comment]
Ca ERG11(aaD278N) Not in Mair et al Table 3

![image](https://github.com/PHI-base/curation/assets/11753634/e3d560e2-a498-4505-be32-a8747ee9b5cc)

Codon 278 in the sequence index is 'D' which aligns with archetype index codon 283 but a different wildtype AA 'H' in the Cyp51B archetype sequence.
use '283N; ERG11 (Cyp51B); SEPTTR'


ERG11(aaD278N G464S)[Not assayed] '283N, G476S; ERG11 (Cyp51B); SEPTTR'

**Comment by CuzickA** [comment]
Double mutant AEs now added
![image](https://github.com/PHI-base/curation/assets/11753634/50284c87-cf51-42e0-9284-545d114943f5)
![image](https://github.com/PHI-base/curation/assets/11753634/9cb8cc75-951c-401d-beb1-691ebb7edd01)

Next Step
Ask Nichola to check these new FRAST alignments generated for the double mutants. The earlier set of single mutants have already been checked and look fine. After checking this session with be ready for approval.

**Comment by CuzickA** [comment]
Nichola has now checked the archetype info for the second batch of mutants required for the double mutant AEs. All looks fine.

Approving session and closing ticket.
