### ISSUE TITLE
PMID:18992352 Identification of three mutant loci conferring carboxin-resistance and development of a novel transformation system in Aspergillus oryzae

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#173]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/61788103954a4a98

**Comment by MPiovesana** [comment]
Carboxin-resistant mutants were generated in this study by irradiating the wild type strain RIB40 of _Aspergillus oryzae_ with UV light, followed by culturing in carboxin-amended growth medium. Mutations in the _sdhB_, _sdhC_ and _sdhD_ genes of the carboxin-resistant mutants were identified, and transformation of the mutant alleles into the wild type strain conferred carboxin resistance to the transformants. The genotypes of the transformants were recorded in this curation session.

**Comment by MPiovesana** [comment]
**Uniprot ID:** the authors provide accession numbers for _sdhB_ (AO090010000505) and _sdhC_ (AO090020000596), which were used to retrieve the following entries on Uniprot:

_sdhB_ = **Q2TWM0**
_sdhC_ = **Q2U3V9**

These entries are linked to the reference proteome for _A. oryzae_ strain RIB40 (UP000006564).

Authors say they could not locate an annotated _sdhD_ sequence of _A. oryzae_, but they found an EST for the putative gene (AoEST2786). I tried accessing the website referenced in the text without success, and this accession number did not return any entry on Uniprot. Gene name searches browsing the reference proteome were also unfruitful as I could not locate the _sdhD_ protein. However, authors provide an accession number for the mutant _sdhD_ allele _(AB449815)_ in Table 1, which returned entry B6F1B3 on Uniprot; by searching the similar proteins to this one (90% identity), entry **A0A1S9DUG1** is retrieved, which is linked to a second _A. oryzae_ reference proteome (UP000190312), this one associated with strain BCC705. As I could not locate an ID for _sdhD_ in the RIB40 ref proteome, I am using this ID for now in the curation session. I will flag this issue to be discussed as we might need to find an alternative ID linked to the correct strain before approving the session.

**Comment by MPiovesana** [comment]
**Genotype creation:** allele type **transformant** was selected to create the genotype of the RIB40 strain transformed with mutant copies of _sdhB/C/D_ genes. The amino acid substitution encoded by each mutant allele was recorded in allele description, and the strain from which the mutant allele was amplified from was recorded in the allele name.

**Comment by MPiovesana** [comment]
**Genotype annotation:** all genotypes were annotated with _resistance to carboxin_.

**Comment by MPiovesana** [comment]
**NOTE**: Due to difference reference proteomes being used, PHI-Canto identified _Aspergillus oryzae_ and _Aspergillus oryzae (strain ATCC 42149 / RIB40)_ as different organisms. This does not pose an issue for curation, but we might want to find appropriate IDs belonging to the same ref proteome for all three genes to avoid this.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Genotype and phenotype annotations look fine.

New strain will need adding.

Next to check UniProt ids.

**Comment by CuzickA** [comment]
Two reference proteomes

![image](https://github.com/PHI-base/curation/assets/11753634/6e42c1a5-1823-4cbe-9c07-3b50bb1c091b)

**Comment by CuzickA** [comment]
Query for sdhD

I searched uniprot for mutant accession id (Table 1) AB449815 and found uniprot B6F1B3. I blasted 'B6F1B3' in Uniprot and selected the entries for 'Aspergillus oryzae'

![image](https://github.com/PHI-base/curation/assets/11753634/311cc8fe-1d48-4efd-abf0-7db8b80d5660)

https://www.uniprot.org/uniprotkb/A0A1S9DUG1/entry is linked to a second A. oryzae reference proteome (UP000190312)

My findings are the same as Maiara's above.

**Comment by CuzickA** [comment]
Hi @jseager7, I am checking this session and had a couple of queries

1) This session has 'Existing annotations' for GO MF. They look correct but I'm not sure where they have come from?
![image](https://github.com/PHI-base/curation/assets/11753634/d2638922-3f91-45c8-a9be-9742b16ddc4e)

2) The three genes curated in this session belong to the same species. However, two genes were found in 'strain ATCC 42149 / RIB 40' and one gene was found in another strain. Is this how we would expect the display to look here or should the strain level species name be mapped up to the species name and thus all genes would be displayed under a single pathogen name?
![image](https://github.com/PHI-base/curation/assets/11753634/141ecfcf-acb7-4d17-97ea-41fe20490898)

**Comment by CuzickA** [comment]
**Next steps**

1) add new strain - currently it looks like this will have to be added to _two species_??? 'Aspergillus oryzae' and 'Aspergillus oryzae (strain ATCC 42149 / RIB 40)'. See what the outcome is on above query.
2) try and add AE alteration in archetype _DONE 14_02_2024_

**Comment by CuzickA** [comment]
**AE alteration in archetype**

sdhB transformant(CR9-sdhB(H249L))[Ectopic] 'H277L; SdhB; PYRNTE'

![image](https://github.com/PHI-base/curation/assets/11753634/1c8e94dd-8ebb-4a5b-8bd6-7a9bd5617cb4)


sdhC transformant(CR6-sdhC(T90I))[Ectopic] 'T78I; SdhC; PYRNTE'

![image](https://github.com/PHI-base/curation/assets/11753634/ff554f8d-a12d-4b27-881c-3ae59d660c7f)



sdhD transformant(CR7-sdhD(D124E))[Ectopic] ?? different than below in Nichola's table


Nichola's table
![image](https://github.com/PHI-base/curation/assets/11753634/c77ea569-ddc6-408a-ad1f-bfc6403f56c8)
![image](https://github.com/PHI-base/curation/assets/11753634/46732540-05f5-451f-819b-81e332e8df8a)
![image](https://github.com/PHI-base/curation/assets/11753634/9b3206b6-3ddc-4580-b460-76fad60dfa6d)



Aspergillus oryzae is not listed in Table 10 EPPO codes in Mair et al 2016

![image](https://github.com/PHI-base/curation/assets/11753634/6a10421e-ca19-45f7-a2cb-90f367b77a5d)

archetype species has D124E, but info above in Nichola's table suggested this would be at archetype residue 140

Will need to try FRAST for Ao sdhD(D124E) for further information.

**Comment by jseager7** [comment]
@CuzickA

> This session has 'Existing annotations' for GO MF. They look correct but I'm not sure where they have come from?

Have you checked if they exist in another database like QuickGO? According to a comment here: https://github.com/pombase/canto/issues/2277#issuecomment-620913104 it seems like that's where Canto defaults to loading the annotations from.

> The three genes curated in this session belong to the same species. However, two genes were found in 'strain ATCC 42149 / RIB 40' and one gene was found in another strain. Is this how we would expect the display to look here or should the strain level species name be mapped up to the species name and thus all genes would be displayed under a single pathogen name?

I'm not sure about this one. Can you share the UniProtKB accession numbers for the genes in question?

**Comment by CuzickA** [comment]
Ao sdhD

Generate FASTA file from https://www.uniprot.org/uniprotkb/A0A1S9DUG1/entry (note this may not be the best uniprot -discussion above)

![image](https://github.com/PHI-base/curation/assets/11753634/e2705ba8-97fe-4e8d-9a21-102d99369d9d)

FRAST alignment gives input sequence 'D' at residue 124 and equivalent 'D' at residue 145 in archetype. This is conflicting with Nichola's table. Also note archetype seq residue 140 is 'E' as recorded in Nichola's table, but this would suggest the input seq would be equivalent residue 119 instead of 124???

Possible options (not added yet)
sdhD transformant(CR7-sdhD(D124E))[Ectopic] '140E; SdhD; PYRNTE' Nichola's table ??
sdhD transformant(CR7-sdhD(D124E))[Ectopic] 'D145E; SdhD; PYRNTE' FRAST


To follow up with Nichola

**Comment by CuzickA** [comment]
Hi @jseager7, 

> I'm not sure about this one. Can you share the UniProtKB accession numbers for the genes in question?

![image](https://github.com/PHI-base/curation/assets/11753634/8bfae14b-cb99-464e-a8a2-fc1f1163b979)
 UniProt = A0A1S9DUG1

![image](https://github.com/PHI-base/curation/assets/11753634/cb7d45ee-e64d-4ab6-b145-ae080a3d763c)
UniProt = Q2TWM0 and Q2U3V9

**Comment by jseager7** [comment]
@CuzickA I think this is because the taxonomy ID for accessions Q2TWM0 and Q2U3V9 isn't in our strain-to-species mapping file, meaning we have no rules to remap from the strain-level ID 510516 to the species level ID 5062. It's easy for me to fix this though. I'll open an issue on our private config tracker.

**Comment by CuzickA** [comment]
@jseager7 

> This session has 'Existing annotations' for GO MF. They look correct but I'm not sure where they have come from?
> 
> Have you checked if they exist in another database like QuickGO? According to a comment here: https://github.com/pombase/canto/issues/2277#issuecomment-620913104 it seems like that's where Canto defaults to loading the annotations from.

It looks like the GO annotations have been made by other resources. For some reason I was only expecting them to show up as existing annotations if they had been curated in PHI-Canto - eg from another paper. Do you know what the rule is for these? Which existing GO annotations do we pick up and display?

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q2TWM0

**Comment by jseager7** [comment]
> Do you know what the rule is for these? Which existing GO annotations do we pick up and display?

As far as I know it's just QuickGO. We just use the same configuration as PomBase's Canto for this, so you'll have to ask the PomBase team for more details. I'm also not sure whether annotations made in PHI-Canto show up in this section until they're submitted to the GO Annotation Database via our GAF file (and I haven't exported that in a while).

**Comment by CuzickA** [comment]
**Next steps for this session**
1) Wait until strain to species mapping has been done for Ao. Then add new strain 'RIB40' to the singularly listed pathogen species.
2) Ask Nichola to check the AE alteration in archetype and address question for SdhD.

Then session will be ready to approve.

**Comment by jseager7** [comment]
> Wait until strain to species mapping has been done for Ao.

@CuzickA I've configured the strain to species mapping for _Aspergillus oryzae_ but the change isn't reflected in the user interface yet, and only one of the UniProtKB IDs (Q2TWM0) has been been remapped correctly. The other (Q2U3V9) is still showing as _Aspergillus oryzae_ (strain ATCC 42149 / RIB 40).

I don't think the strain to species mapping works properly when the genes have already been added to the session. I tried clearing the gene cache in PHI-Canto but that only worked for one of the genes. I'll have to raise this as an issue on the Canto tracker.

**Comment by CuzickA** [comment]
> > Wait until strain to species mapping has been done for Ao.
> 
> @CuzickA I've configured the strain to species mapping for _Aspergillus oryzae_ but the change isn't reflected in the user interface yet, and only one of the UniProtKB IDs (Q2TWM0) has been been remapped correctly. The other (Q2U3V9) is still showing as _Aspergillus oryzae_ (strain ATCC 42149 / RIB 40).
> 
> I don't think the strain to species mapping works properly when the genes have already been added to the session. I tried clearing the gene cache in PHI-Canto but that only worked for one of the genes. I'll have to raise this as an issue on the Canto tracker.

Thanks for looking into this @jseager7. Do I need to remove the annotations/genotypes/genes for the two genes in question and then re-add the UniProt ids and re-create genotypes and annotations?

**Comment by jseager7** [comment]
> Thanks for looking into this @jseager7. Do I need to remove the annotations/genotypes/genes for the two genes in question and then re-add the UniProt ids and re-create genotypes and annotations?

I'm not sure if that will solve the problem. Even if the UniProt ID is added in a new curation session there are still bugs with the species name for that UniProt ID. Sorry I haven't had time to open an issue about this on the Canto tracker yet; I'll get to that as soon as I can.

**Comment by CuzickA** [comment]
Hi @jseager7, I just wondered whether there had been any progress on this strain to species mapping issue?
![image](https://github.com/PHI-base/curation/assets/11753634/63d477ae-0e42-46c9-a83b-e349a845ce6a)

**Comment by jseager7** [comment]
@CuzickA No progress yet, sorry. It's still on my radar but I was planning to work on the chemistry annotation extensions and replacing the remaining UniProtKB accession numbers (see [here](https://github.com/PHI-base/curation/issues/207#issuecomment-2059148247)) before this. If you feel this is more important than either of those tasks, please let me know.

**Comment by CuzickA** [comment]
@jseager7, no problem. Thanks for the update.

**Comment by jseager7** [comment]
@CuzickA I've finally fixed the strain to species mapping issue in this curation session.

![image](https://github.com/PHI-base/curation/assets/37659591/857f718d-ad9c-4855-9214-c32e57a7a45e)

There's a script available for Canto now that can update all curation sessions to match the configuration in the strain-to-species mapping file, so it should be much quicker to solve this problem if it happens anywhere else.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype. (Note: I have not added the AE for 'sdhD transformant(CR7-sdhD(D124E))[Ectopic]' due to queries above).

Closing ticket.
