### ISSUE TITLE
PMID:1388107 A single amino-acid substitution in the beta-tubulin gene of Neurospora confers both carbendazim resistance and diethofencarb sensitivity

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#174]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/f0c90e54bdfafd10

**Comment by MPiovesana** [comment]
Two mutants (F914 and F939) of _Neurospora crassa_ displaying resistance to carbendazim (MBC) and sensitivity to diethofencarb were isolated in this study after UV irradiation of the wild type strain 74-OR31-14a. A mutation in the β-tubulin gene of these mutants were identified, causing the substitution of Glu at position 198 with a Gly residue. When the wild type strain was transformed with the β-tubulin allele from mutant F914, transformants displayed resistance to MBC and sensitivity to diethofencarb, confirming that this allele confers negatively correlated cross resistance to these fungicides.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene and species name search on Uniprot returned entry P05220 for the _β-tubulin_  of _N. crassa_.

**Strain:** authors mention in Materials and Methods that strain 74-OR31-14a was used for mutagenesis, and strain C1-T10-37A was used for back-crosses with the isolated mutants; however, there is no mention of which wild type strain was used as recipient for transformation experiments. As 74-OR31-14a was used for mutagenesis and, therefore, can be considered the wild type parental strain in this study, I selected it for this curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** an allele type transformant was created to record the genotype of the transformants generated in the study. Allele name **F914-βTub** and description **(βTub-aaE198G)** were used to indicate that the _βTub_ allele of mutant strain F914 harbouring aaE198G mutation was introduced in the wild type strain. **Ectopic** was selected as expression level.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotype was annotated with PHIPO terms _resistance to carbendazim_ and _sensitive to diethofencarb_.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
I have started checking this session but currently cannot access the PDF so only have access to the abstract and curation comments above.

![image](https://github.com/PHI-base/curation/assets/11753634/22f29d62-030e-424e-8516-23befd6d01f7)


@MPiovesana, I think the transformant genotypes might need editing here based on the discussions in #157 

![image](https://github.com/PHI-base/curation/assets/11753634/080f2b1b-370c-4fa7-a107-244b11c521a5)

I think the strain needs to move out of the name and into the description
βTub+ (transformed F194 βTub-aaE198G)
I guess we would use 'βTub+' here if the endogenous gene is still present.

**Comment by MPiovesana** [comment]
> I think the strain needs to move out of the name and into the description βTub+ (transformed F194 βTub-aaE198G) I guess we would use 'βTub+' here if the endogenous gene is still present.

@CuzickA Thank you for checking this. I was not sure what the guidelines were to name transformant alleles, so it will be good to agree on a standardised way according to our discussion in ticket #157 . Once we agree on the best strategy to name these alleles, I will go over the other curation sessions where it has been used recently to edit names to save you the work of having to edit all of them.
I am just slightly confused about naming the allele 'gene name'+ in this case, as to me it seems to imply only the wild type copy is present... My first instinct as a curator would be to add some info about the allele in the name section as well. Does it make sense?

**Comment by CuzickA** [comment]
> I am just slightly confused about naming the allele 'gene name'+ in this case, as to me it seems to imply only the wild type copy is present... My first instinct as a curator would be to add some info about the allele in the name section as well. Does it make sense?

Yes, I see what you mean. Maybe this is similar to the comment that @ValWood made in the other ticket #157.

**Comment by CuzickA** [comment]
Instead of 
βTub+ (transformed F194 βTub-aaE198G)

how about
βTub transformant (transformed F194 βTub-aaE198G)

We could record that the endogenous gene was still present in the background.

**Comment by MPiovesana** [comment]
> Instead of βTub+ (transformed F194 βTub-aaE198G)
> 
> how about βTub transformant (transformed F194 βTub-aaE198G)
> 
> We could record that the endogenous gene was still present in the background.

@CuzickA I think the suggested name makes more sense, the user can understand that this is a transformant line from the allele name and description. And we could add βTub+ as background info as you said. Should I make the changes?

**Comment by CuzickA** [comment]
> > Instead of βTub+ (transformed F194 βTub-aaE198G)
> > how about βTub transformant (transformed F194 βTub-aaE198G)
> > We could record that the endogenous gene was still present in the background.
> 
> @CuzickA I think the suggested name makes more sense, the user can understand that this is a transformant line from the allele name and description. And we could add βTub+ as background info as you said. Should I make the changes?

Sounds good. I have made a few suggestions for review in ticket #157. We should make sure we consistently use the same language to document the information in the background. Once we have decided on this we can write it up in the FAQs as you suggested :-)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/414df534-ca23-4fa0-9682-95bb2524aea8)


Approving session and closing ticket.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

E198G; β-tubulin; ASPEND

Straight forward to find in Nichola's S file in Table S1
![image](https://github.com/PHI-base/curation/assets/11753634/7b48f729-9e8c-441a-aec2-b4de7f94855a)
![image](https://github.com/PHI-base/curation/assets/11753634/3af489da-7262-48b6-9938-2631418b9a0c)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
