### ISSUE TITLE
PMID:27558019 Development of a novel strategy for fungal transformation based on a mutant locus conferring carboxin-resistance in Magnaporthe oryzae

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#175]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/e19bd7df7425b419

**Comment by MPiovesana** [comment]
In this paper, authors develop a transformation strategy for _Magnaporthe oryzae_ using the carboxin resistance conferred by a mutant allele of _Mosdi1_ gene (succinate dehydrogenase) as a selection marker. To test whether a point mutation previously described in the literature in other fungal species could confer carboxin resistance in _M. oryzae_, authors replace the endogenous wild type copy of _Mosdi1_ from wild type strain Guy11 with a mutant allele harbouring the H245L mutation. The resulting mutant is resistant to carboxin. Authors then proceed to develop a transformation strategy where gene replacement of _Mosdi1_ and introduction of a transgene adjacent to the _Mosdi1_ locus take place simultaneously, which is proven to work. After careful reading through the whole paper, I believe the only genotype and phenotype of interest for curation in PHI-Canto is that of the Guy11-derived gene replacement mutant showing resistance to carboxin.

**Comment by MPiovesana** [comment]
**Uniprot ID:** using the accession number provided by the authors (XP_003718958), Uniprot ID **G4NE45** was retrieved.

**Strain:** wild type strain Guy11 was selected.

**Comment by MPiovesana** [comment]
**Genotype creation:** an _amino acid substitution_ allele type was created to record the H245L mutation in _Mosdi1_ which confers resistance to carboxin. _Mosdi1Δ_ added to background to reflect gene replacement.

**Comment by MPiovesana** [comment]
**Genotype annotation:** genotype was annotated with PHIPO term **resistance to carboxin**.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Annotation looks fine.


![image](https://github.com/PHI-base/curation/assets/11753634/e67abcd4-b44e-442a-8097-e2c3a8abbe0b)


**Next**
Can I add Sdh archetype info for this annotation?

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Magnaporthe oryzae Mosdi1(aaH245L)[Not assayed]

Could not find an entry in Nichola S file or Mair et al.

Try FRAST

**Comment by CuzickA** [comment]
https://www.ncbi.nlm.nih.gov/protein/XP_003718958

**Comment by CuzickA** [comment]
In FRAST not sure whether to align to SdhB , C or D.

The automatic search for Blast N is not providing any information.

Need to follow up with Nichola.

**Comment by CuzickA** [comment]
Nichola also could not get the automatic search for Blast N in FRAST to provide any information.

Nichola did a protein-protein blast in genbank gives 100% match of sdi1 = sdhB

To do
1) repeat the blast search and document
2) FRAST align sdi1 with SdhB archetype

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/73574c70-692a-4d5a-8a83-06619c9de0a4)

**Comment by CuzickA** [comment]
Next 
FRAST align sdi1 with SdhB archetype

Magnaporthe oryzae Mosdi1(aaH245L)[Not assayed]

**Comment by CuzickA** [comment]
Magnaporthe oryzae Mosdi1(aaH245L)[Not assayed]

Confirm above sequence snip for Mosdi1 contains 'H' at position 245.

![image](https://github.com/PHI-base/curation/assets/11753634/3a1a0127-2f26-40d2-ae11-033e974fc0d8)
 Input sequence 245 aligns with archetype sequence at position 277

Therefore,
Magnaporthe oryzae Mosdi1(aaH245L)[Not assayed] would be 'H277L; Sdi1 (SdhB); PYRNTE'

![image](https://github.com/PHI-base/curation/assets/11753634/d7432561-c64e-4791-8d52-e93481810a62)

**Comment by CuzickA** [comment]
**Next step**

1) Check AE with Nichola

Then session will be ready for approval.

**Comment by CuzickA** [comment]
Checked AE with Nichola. Looks fine.

Approving session and closing ticket.
