### ISSUE TITLE
PMID:2257633 Identification of an amino acid substitution in the benA, beta-tubulin gene of Aspergillus nidulans that confers thiabendazole resistance and benomyl supersensitivity

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#176]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/1c6883fef59a7aaf

**Comment by MPiovesana** [comment]
In this paper, authors describe a new strategy to clone _benA_ (_β-tubulin_) mutant alleles of _Aspergillus nidulans_ using a marker-rescue technique. The mutant alleles _benA16_ and _benA19_ are known to confer supersensitivity to benomyl. Upon cloning the benA(A165V) alleles from mutant strains, the authors introduce them into strain G191 (benA+), with the resulting transformants displaying an intermediate sensitivity phenotype between sensitive and resistant strains.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene (beta tubulin) and species name (_Aspergillus nidulans_) search returned entry P10653 for the _benA_ gene of _A. nidulans_.

**Strain:** strain G191 was manually added to the curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** I curated the genotype of the transformants obtained by introducing the _benA16/19_ mutant alleles in strain G191. As the plasmids used for transformation lead to the integration of the _benA_ mutant allele in the endogenous _benA_ locus, the resulting transformants seemingly carry three copies of the _benA_ gene: the two endogenous _benA_ wild type copies (_Endogenous benA present_ added in background), and one mutant copy of the _benA_ mutant allele (authors mention in the text that most transformants only carry one integrated copy of the mutant allele in the _benA_ locus). I initially thought this could be recorded as a diploid, heterozygous locus, but I do not think this would work here as the locus where transgene integration occurs carries both a wt and a mutant copy of the gene, while the other locus remains unchanged. Thus, I created a transformant allele type as below:

**benA transformant(BEN17-benA(A165V)) [Not assayed]**: indicating the transformation of the mutant _benA_ allele from strain BEN17 (one of the strains described in the paper picked as representative, as authors do not specify which strain was used as template to clone gene) in recipient strain. _Endogenous benA present_ was added in background.

AC: BEN17 is supersensitive to benomyl

**Comment by MPiovesana** [comment]
**Genotype annotation:** the transformants carrying the wt benA and the BEN17-benA(A165V) alleles exhibit an intermediate sensitivity phenotype to benomyl compared to homozygous strains (Figure 3). As the recipient strain G191 is a benA+ strain, I considered its phenotype as a control. Thus, I assigned the mutant genotype with PHIPO term _sensitive to benomyl_, and added annotation extension **has_severity** medium to record the intermediate phenotype observed.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Looks good
![image](https://github.com/PHI-base/curation/assets/11753634/c30b7a6b-f22d-4c93-833e-5ea2fc59921e)

Approving session

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

A165V; BenA (β-tubulin); ASPEND

Straight forward to find in Nichola's S file in Table S1

![image](https://github.com/PHI-base/curation/assets/11753634/5414864d-af37-4c79-a815-ed63b5144a4b)
![image](https://github.com/PHI-base/curation/assets/11753634/014d80ed-c9ba-471d-8d44-e3636fb0f450)

**Question**
Are we happy with target-site name, see https://github.com/PHI-base/curation/issues/144
Yes, this follows our guidance in the FAQs

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
