### ISSUE TITLE
PMID:11036010 Genetic analysis of azole resistance in the Darlington strain of Candida albicans

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#177]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/8d279073acae6de3

**Comment by MPiovesana** [comment]
Mutations in the _ERG11_ gene of the azole-resistant _Candida albicans_ strain Darlington were identified in this study, causing the amino acid substitutions Y132H and I471T. This mutant allele was cloned and introduced in the wild type recipient strain CAI4, and a transformant line heterozygous for the _ERG11_ gene replacement was identified. This line (transformant 12) carrying one wt and one mutant allele of _ERG11_ displayed increased resistance to fluconazole compared to the parental strain CAI4.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene (_ERG11_) and species name (_Candida albicans_) search returned entry P10613.

**AC 13_02_2024** UniProt looks good. Also used in https://github.com/PHI-base/curation/issues/172


**Strain:** strain CAI4 was selected as the recipient strain for transformation. _(sensitive strain)_

**Comment by MPiovesana** [comment]
**Genotype creation:** a transformant allele type was created named _ERG11 transformant(Darlington-ERG11(Y132H I471T))_ in the CAI4 background. A wild type allele _ERG11+_ was also created. Both alleles were combined in a heterozygous diploid genotype to represent the genotype of the CAI4 transformant isolated in this study.

**Comment by MPiovesana** [comment]
**Genotype annotation:** PHIPO term _resistance to fluconazole_ was assigned to the heterozygous diploid genotype.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Annotation looks fine.

**AE alteration in archetype**

ERG11+[WT level] / ERG11 transformant(Darlington-ERG11(Y132H I471T))[Not assayed]
'Y137H, I483T; ERG11 (Cyp51B); SEPTTR'

Could not find Candida albicans listed in Nichola's S files.

In Mair et al 2016
![image](https://github.com/PHI-base/curation/assets/11753634/5cd11a4f-c6f9-4433-afc7-1ccfd72c6304)
![image](https://github.com/PHI-base/curation/assets/11753634/8d498c5c-d8a2-4d11-884d-c48af11ce158)
![image](https://github.com/PHI-base/curation/assets/11753634/3ce05895-7b9d-49ad-a0c3-43ea50cf488a)

![image](https://github.com/PHI-base/curation/assets/11753634/cd8133a5-0ecb-41d4-b80d-6e7b863e0998)

**Comment by CuzickA** [comment]
**Next step**

1) Check AE alteration in archetype with Nichola.
2) Also to double check that this is 'Cyp51B', authors call gene ERG11/Cyp51A1. ERG 11 uniprot is same as in https://github.com/PHI-base/curation/issues/172 where we decided that ERG 11 = Cyp51B

Then session ready to approve.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
