### ISSUE TITLE
PMID: 30686221 Genotypes and Characteristics of Phenamacril-Resistant Mutants in Fusarium asiaticum

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#178]
Curated by @MPiovesana

**Comment by MPiovesana** [comment]
In this study, authors induce phenamacril-resistant mutants of _Fusarium asiaticum_ in laboratory conditions. Out of 239 mutants obtained, 82 were randomly selected for characterisation. Mutations in the _myosin5_ gene of the mutant lines are identified in comparison with the wild type _myosin5_ sequence from strain 2021 (Table 1). Phenotypical analysis of some of the mutant lines is also performed.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene (_myosin5_) and species (_Fusarium asiaticum_) name search does not return any entries on Uniprot, and I also could not locate an appropriate reference proteome for _F. asiaticum_. In the paper authors provide accession number FGSG 01410 for myosin5 in Materials and Methods, but this returns entry A0A098D3M4 which is annotated as myosin1 of _F. graminearum_. Hence, I was not able to locate an appropriate ID to curate this paper so far. How to proceed in this case?

**Comment by MPiovesana** [comment]
Curation paused in the meantime.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, Maiara was unable to track down a gene id for looking up the uniprot for 'myosin5' in 'Fusarium asiaticum'. I will email you her highlighted PDF. When you have a few minutes please could you email the authors and ask them for a gene or uniprot id? (Please copy me into the email) Thank you :-).

**Comment by jingluodatacurator** [comment]
@CuzickA, email sent to M. Zhou at mgzhou@njau.edu.cn to request for a gene or uniprot id, has cc you in.

**Comment by CuzickA** [comment]
@jingluodatacurator, I am going to close this ticket for now. If you hear back from the author with a gene id then we can reopen it for curation.
