### ISSUE TITLE
PMID: 27199944 Resistance Assessment for Oxathiapiprolin in Phytophthora capsici and the Detection of a Point Mutation (G769W) in PcORP1 that Confers Resistance

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#179]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/386cbbeaee53cdda

**Comment by MPiovesana** [comment]
In this paper authors isolated spontaneous oxathiapiprolin-resistant mutants of _Phytophthora capsici_ from two parental wild type strains, LP3 and HNJZ10. The mutants were phenotypically characterised and found to carry two separate heterozygous point mutations in the oxysterol binding protein _PcORP1_ (G769W for LP3 mutants and G700V for HNJZ10 mutants). The PcORP1-G769W allele of mutant LP3-M was cloned and transformed into oxathiapiprolin-sensitive wild type isolate BYA5, and transformants exhibited increased resistance to the fungicide as expected.

**Comment by MPiovesana** [comment]
**Uniprot ID:** Unfortunately I could not locate an appropriate Uniprot ID for this curation session so far. A gene and species name search did not return any entry, and there is no reference proteome for _Phytophthora capsici_ currently in the UniprotKB database. I tried performing a BLAST with the protein sequence displayed in Figure 3 of the paper, but matches returned belong to other _Phytophthora_ species. I then tried to locate the ORP1 protein in the _P. capsici_ genome database by using the protein ID provided by the authors in the text (564296 (PHYCAscaffold_14:545241–548188)), and I located the following link:
https://mycocosm.jgi.doe.gov/cgi-bin/dispGeneModel?db=Phyca11&id=564296
It corresponds to the correct protein (protein length matches description in the paper), however, I do not think this protein is currently deposited in Uniprot. How could we proceed here?

**Comment by MPiovesana** [comment]
If a Uniprot ID is located, the rest of the curation should be relatively straightforward. I believe we have a choice to curate the genotype of the mutants derived from strain LP3 and HNJZ10 (generated by exposure to oxathiapiprolin) or the BYA5 transformant, transformed with the LP3-M-PcORP1. A more thorough phenotypical characterisation was performed for the spontaneous mutants, including evaluation of mycelial growth at different temperatures, analysis of virulence and cross-resistance to other fungicides. However, the phenotypes of these were quite variable (not all mutant displayed the same growth, sporulation, etc), which is likely due to the presence of other background mutations that affect their phenotype, but this could potentially be captured with an annotation extension **has_severity** variable.

**Comment by MPiovesana** [comment]
Curation paused for the time being until Uniprot ID issue resolved.

**Comment by CuzickA** [comment]
I have also been trying to locate a UniProt id.

https://mycocosm.jgi.doe.gov/cgi-bin/dispGeneModel?db=Phyca11&id=564296
Following this link there is an option for 'NCBI Blastp'
![image](https://github.com/PHI-base/curation/assets/11753634/6335d8f6-57c1-4019-8e2b-1b3f267933a0)



I selected this option

I think the top entry for Pc is a good candidate to take forward.
ALso author text '957' AA length
![image](https://github.com/PHI-base/curation/assets/11753634/67cb3f88-8aa1-4ff8-ab3f-92a47808118c)


![image](https://github.com/PHI-base/curation/assets/11753634/9946f3fc-67be-4a25-b7a3-16678410bef8)
![image](https://github.com/PHI-base/curation/assets/11753634/d38e012f-f786-4eb9-b8ff-a07cc27bbdab)

![image](https://github.com/PHI-base/curation/assets/11753634/6063960a-7f39-4767-94e9-1427606c135c)



Search ' KAG1704536.1'  in genbank
https://www.ncbi.nlm.nih.gov/protein/KAG1704536.1


Search ' KAG1704536.1'  in UniProt no entries.

**Comment by CuzickA** [comment]
I took the FASTA file for KAG1704536.1 and blasted in UniProt. There were no entries for Phytophthora capsici.
![image](https://github.com/PHI-base/curation/assets/11753634/90589092-7a10-441d-b93e-383762db0192)

Does UniProt have a proteome for Ps? This suggests no.
![image](https://github.com/PHI-base/curation/assets/11753634/687e71c1-39ff-4bdc-8ecb-c3265fc63281)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, as you will see from above we have not been able to find a UniProt id.

Please could you email the authors (copy me in) and request the UniProt id for the gene 'PcORP1' in species Phytophthora
capsici? I will email you the PDF. Thanks.

**Comment by CuzickA** [comment]
Jing sent email to author yesterday.

**Comment by CuzickA** [comment]
Author response email thread below - in summary, the gene is not in UniProt so we cannot curate this paper.

![image](https://github.com/PHI-base/curation/assets/11753634/ff6dbcec-4d98-4640-a0d3-511af83712b0)
![image](https://github.com/PHI-base/curation/assets/11753634/64051fcd-5a6f-49f2-9c9c-831fc20c2cc4)
![image](https://github.com/PHI-base/curation/assets/11753634/af5d5dfe-d3a5-451a-955b-9a300fc25ca7)
![image](https://github.com/PHI-base/curation/assets/11753634/301dc8ae-6e17-421a-8690-524424938ad0)
![image](https://github.com/PHI-base/curation/assets/11753634/74006233-adc2-4659-a0fe-9521ec14ebb8)


Closing ticket for now.
