### ISSUE TITLE
PMID:30220500 Suppression of Plant Immunity by Fungal Chitinase-like Effectors.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#18]
Link to curation session
http://canto.phi-base.org/curs/3b2c44b436098af1

Link to NTR on GO tracker
Question about PAMP binding (receptor decy activity)
https://github.com/geneontology/go-ontology/issues/16857

**Comment by CuzickA** [comment]
Please check when you have time @ValWood 
Note, unable to find MpChi uniprot from ref proteome, have used alternative uniprot. #35

**Comment by ValWood** [comment]
mailed the authors  about:

 
I am working with PHI-base http://www.phi-base.org/ to set up a new curaton system for pathogen host interactions.

We are using your paper as an example. However I can't disambiguate these 2 entries:

"Remarkably, the MpChi or- tholog in M. roreri (MR05413) has canonical residues in its catalytic site and is enzymatically active (Figures 3A, 3B, and 3D). However, a paralog gene in M. roreri (MrChi), which is highly expressed during the biotrophic interaction of M. roreri and ca- cao (Figure 3C), encodes a GH18 with an independent substi- tution in one of the aspartates of the catalytic motif (D135N; Figure 3B). This substitution results in reduced enzymatic activ- ity (Figure 3D)."

I have been unable to detect MR05413 in any of the public databases. We use Uniprot identifiers and it should be possible to identify all submitted  sequences for complete proteoms  in Uniprot

The proteome appears to be present:
https://www.uniprot.org/uniprot/?query=organism%3A%22Moniliophthora+roreri+%5B221103%5D%22&sort=score

But i have only found

Chi WG66_9206 https://www.uniprot.org/uniprot/?query=+organism%3A%22Moniliophthora+roreri+%5B221103%5D%22+chi&sort=score Many thanks if you can help


response:
 You are right - it seems that the M. roreri genome assembly that is publicly available does not use the MRXXXXX ID format. My apologies.
I am pasting the sequencing that you are looking for below.
You will find it at NCBI under the accession ESK93128.1
Please, let me know if this is helpful.
Thanks!
Paulo

>MR05413
ATGTTCACTCTTTTATCTTCTGCGACTGCTCTGCTCGCACTCTCCTCTGC
CTTGTCGGAGGCACAAGCCCGATGCGCACCGAAGAATTATCCTGTCAAGA
AGCCTGACGGGGGTCACAACCACACATCCAAGTTCATAGCAAAGGGATAC
TATGCCGGCTGGAACTCTGACGACTTCAAACCAGAGAACGTTAGCTGGTC
CAAGTATACACACCTGACGTATGCCTTCGGTATTCCGACAAATACAGCAA
ACTTCGACATCAGTTTGAATGGTTCCAACCCTGAATCCCTTGATCCATTT
GTTAGCGCTGCTCACGAGCATGGCGTGGAAGTCTCCCTTTCCATTGGTGG
ATGGACAGGATCCCGCTTCTTCTCCTATGCAGTTGGTTCCGAGCAGAATC
GTACTGCATTTGTCAAGACGCTAGTCGATTTTGCCGTTGCACACAAGTTG
GACGGTCTGGACATGGATTGGGAGTACCCCTTCCGTCAAGGACTGGGATG
CAATGCATTGAACCCCAATGACACGTCCAACCTTCTGCTGTTCCTCCAAG
AATTCCGCCGAGACCCCGTTGGCGCTAATCTCACCTTGAGTGCCGCTGGC
AGTCTCGCAGTCTGGAACGATTTCACTGGCAACCCTTCGACCAACGTTTC
TGGCTTTGCAGACGTCTTTGATCACTTCGTGATCATGAACTACGATGTCT
GGGGAAGCTGGAGTGAGACCGTCGGCCCCAACGCCCCCTTGAACGATACT
TGCGCTGCCCCTGCTCAACAACAAGGATCCGCTATTTCGTCTGTCAACAA
GTGGACGCAGGCCGGTATGCCACTCGAGAAGATTGTGCTCGGCGTTGGTG
CATACGCGCACTCATTCAGTGTTAACAAGACCAACGCATACGTCAACGGG
ACCAAAGAACTCGCTGCTTACCCGCCCTTCAACAAGGACATCCATCCCAA
GGGTGATAAGTGGGATGACCCCGAGGGTGCCGTTGACTTTTGTGGTGTTA
CTAACCATGCCGGTGGTATTTTCACCTTCTGGGGTTTGATTGAGCATGGT
TACCTCAACGAGGATGGATCTCCCAAGGCGCCTTACCGCTTCGATAACTG
CAGCCGAACTGCCTATGCATACGATGAGAAGGAGCAGGTCATGGTCTCGT
TTGATGATGCGCAGGCTTTCAAAGACAAGGGCGCGTGGATCAAGGAGAAA
GGTTTGGCTGGATTCTCAGTGTGGAACGCTGGTAGCGATCACAAGGACAT
TCTTTTGGATGCTATTCGCAGTGGTGCTGGATTGTCAAAGTAG

**Comment by ValWood** [comment]
uniprot has 2 100% matches:

TR:A0A0W0EUL3_9AGAR | Putative chitinase OS=Moniliophthora roreri OX=221103 GN=WG66_19681 


2 | TR:V2X214_MONRO | Glycoside hydrolase family 18 protein OS=Moniliophthora roreri (strain MCA 2997) OX=1381753 GN=Moror_8851

**Comment by ValWood** [comment]
I will use TR:V2X214_MONRO

**Comment by ValWood** [comment]
correction, I used
A0A0W0EUL3 which appears to be the reference strain and is the same genome as the "chi" paralog used  already

**Comment by ValWood** [comment]
The naming here is a bit confusing.

However, a paralog gene in M. roreri (MrChi), which is highly expressed during the biotrophic interaction of M. roreri and cacao (Figure 3C), encodes a GH18 with an independent substitution in one of the aspartates of the catalytic motif (D135N; Figure 3B). This substitution results in reduced enzymatic activity (Figure 3D)

So the entry that is the  ortholog of  MpCHi "receptor decoy" is not the receptor decoy in 
Mr.

The Mr decoy seems to be A0A0W0EUL3 (which the authors call MrChi in the paper, and use the genome version with the systematic ID MR05413 (these names not in any  UniPRot entries)

The MP Chi ortholog in M.r is already named  "MrChi"   in Uniprot (sensibly) so, there will be 2 genes with the same name - this will need to be disambiguated at some point.

So, the decoy is A0A0W0EUL3, I will switch the annotation over to this entry, and I won't name the alleles.

@marcfeuermann  will probably be useful info for uniprot

**Comment by CuzickA** [comment]
I have reannotated this session. It seems like we can annotate so much more now that the tool has improved.

1) I could not add disease as there were no host assays performed on natural host 'Theobroma cacao'
2) Also couldn't add AE disease interaction absent/ present or AE infective ability as not relevant
3) I have renamed alleles based on notes above from Val  - hopefully they are clear __to check_
4) I have moved the assays in tobacco cells out of pathogen section and into metagenotype section.
5) Control metagenotypes and AE compared to control added where relevant


6) There are some comments about NTRs and making edits to existing terms __to discuss_
7) I need to make a new condition + PTI inducer chitin' __to do_
8) There is a query on NV. Should AA substitution in Mr paralogue D135N be recorded?? It is compared to a 'typical' GH18 sequence Figure 3B. __to discuss_
"a paralog gene in M. roreri (MrChi), which is highly
expressed during the biotrophic interaction of M. roreri and cacao (Figure 3C), encodes a GH18 with an independent substitution in one of the aspartates of the catalytic motif (D135N;
Figure 3B)."
9) we need an 'effector-mediated blah' GO term to get the high level 'effector' tag. See comment in annotation.

@ValWood Please could you check through this one for me so that we can get it ready for approval

**Comment by ValWood** [comment]
> chitinase Q Can we add 'reduced' somehow? Maybe by an AE??

There isn't a way with GO to say anything about the activity level. If we wanted to do this we would need a way to catpture activity rates. We can only say whether the enzyme has the activity or not right now. 
Maybe add this to the notes in the submission in case it is possible in the future.

**Comment by ValWood** [comment]
for this one, I think all of your term suggestions make sense.
For the "decreased chitinase activity", NV I think you will need to add a 'compared to' extension to interpret, but otherwise, all looks good.

I agreed about the GO terms and I changed them, and opened a ticket about the term which was previously used, it seemed  that  the term we originally used should have been an effector-mediated term:
https://github.com/geneontology/go-ontology/issues/21161
We might want to move back down to
effector-mediated suppression of pattern-triggered immunity if  GO:0052034 is renamed as suggested?

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/112131895-f0cf5280-8bc1-11eb-9f18-c4bc2f12dd32.png)
![image](https://user-images.githubusercontent.com/11753634/112132037-13fa0200-8bc2-11eb-9030-599055678263.png)

@ValWood do you think i should just add exact synonym 'chitinase activity absent' to the term 'abolished chitinase activity'
Def: A single species molecular function phenotype in which a chitinase activity is absent.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/112133720-e2823600-8bc3-11eb-8207-75de4cccbae1.png)

Hi @ValWood we can't use the compared to AE in the single genotypes. Also this is a WT gene so maybe we can't say 'decreased'.

**Comment by ValWood** [comment]
They say "results in reduced enzymatic activity" so they must compare it to another strain?
We should be able to use "compared to"  on single species genotypes too, I think?

**Comment by CuzickA** [comment]
I think they are comparing it (paralogue) to the orthologue M. roreri MR05413, which we haven't curated a pathogen phenotype for as it is a control (only curate controls for metagenotype). Perhaps the annotation should be removed and we just use the GO MF annotations (where we cannot specify 'reduced activity' as discussed above).

paper text
"we identified 17 GH18-encoding genes in the M. perniciosa
genome (isolate CP02), with MpChi being the only one with
substitutions in the catalytic glutamate (Figure S4A). We next
searched for GH18-encoding genes in M. roreri [28], a sister
species that causes FPR in cacao. Remarkably, the MpChi ortholog in M. roreri (MR05413) has canonical residues in its catalytic site and is enzymatically active (Figures 3A, 3B, and 3D).
However, a paralog gene in M. roreri (MrChi), which is highly
expressed during the biotrophic interaction of M. roreri and cacao (Figure 3C), encodes a GH18 with an independent substitution in one of the aspartates of the catalytic motif (D135N;
Figure 3B). This substitution results in reduced enzymatic activity (Figure 3D)."

**Comment by ValWood** [comment]
It would be good to curate M. roreri MR05413 too. However I can't locate this in UniProt. It might be a good example of the  problem of choosing one assembly over another but not keeping the systematic names of the archived strain. 
However, no need to wait for this to put the session through. It's just an added extra, not mandatory...

**Comment by CuzickA** [comment]
I am going to delete this PHIPO WT annotation in favour of the GO annotation
![image](https://user-images.githubusercontent.com/11753634/112288045-de6a1d00-8c84-11eb-8fa4-d7880e1c5669.png)
![image](https://user-images.githubusercontent.com/11753634/112288541-5b959200-8c85-11eb-9126-02355daf68d3.png)

The orthologue gene in M. roreri (MR05413) id WG66_19681 is also captured by GO
![image](https://user-images.githubusercontent.com/11753634/112288669-7cf67e00-8c85-11eb-85ab-ce612729d849.png)

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/112311973-32353000-8c9e-11eb-9e4c-3c69c2471881.png)
![image](https://user-images.githubusercontent.com/11753634/112312034-411be280-8c9e-11eb-9341-d934eb3fe992.png)
 Swapping 'abolished pathogen suppression of host PAMP-triggered immunity' over to 'effector-mediated suppression of host PAMP-triggered immunity absent' for these annotations as they have not performed MAPK signaling expt. The former term is under a signaling parent 'pathogen modulation of host immune system signaling pathway phenotype'.
See ticket https://github.com/PHI-base/phipo/issues/251 for query on some of the PTI terms in PHIPO.


![image](https://user-images.githubusercontent.com/11753634/112312642-ec2c9c00-8c9e-11eb-8433-ad2f3d00f78a.png)
![image](https://user-images.githubusercontent.com/11753634/112312709-00709900-8c9f-11eb-840e-dbee33a328d0.png)

**Comment by CuzickA** [comment]
New PHIPO terms added, approving session and closing ticket.

@ValWood we can discuss the PTI terms in ticket https://github.com/PHI-base/phipo/issues/251
