### ISSUE TITLE
PMID:12709346 Multiple resistance mechanisms among Aspergillus fumigatus mutants with high-level resistance to itraconazole.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#180]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/19bec1e8b7ca6406

**Comment by MPiovesana** [comment]
The authors of this paper generate itraconazole-resistant mutants derived from a wild type strain of _Aspergillus fumigatus_ in laboratory conditions. Among the mutants generated, a few of them are found to carry point mutations in the target gene _cyp51A_, as shown in Table 1. Other mutants are found to overexpress novel drug efflux pumps described in the paper. For the purpose of curation in PHI-Canto, I believe the amino acid substitution genotypes can be curated, as we know the mutation associated with the resistance phenotype. I am not sure we can curate the other mutants (the ones not harbouring point mutations), as we do not know the mechanism via which overexpression of the drug efflux pumps is achieved (promoter mutation? mutation in regulatory gene?). So for now, I have curated the three point mutation alleles described in the paper.

**Comment by MPiovesana** [comment]
**Uniprot ID:** no problems locating the ID of _cyp51A_ of _A. fumigatus_ (Q4WNT5).

**AC:** reviewed entry :-) https://www.uniprot.org/uniprotkb/Q4WNT5/entry

**Comment by MPiovesana** [comment]
**Strain:** wt strain H11-20 was used for the UV-irradiation mutagenesis experiment.

**Comment by MPiovesana** [comment]
**Genotype creation:** three genotypes harbouring amino acid substitution allele types were created to record the three point mutations identified in _cyp51A_: G54E/K/R. All alleles were assigned with expression level Not assayed, as levels of _cyp51A_ were not measured in the study (only of the drug efflux pumps).

**Comment by MPiovesana** [comment]
**Genotype annotation:** all three pathogen genotypes were annotated with PHIPO term _resistance to itraconazole_.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
**AE alteration in archetype**

G54E; Cyp51A; ASPEFU
G54K; Cyp51A; ASPEFU
G54R; Cyp51A; ASPEFU

No entry found in Nichola's S files STable 2

Information found in Mair et al 2016 Table 2
![image](https://github.com/PHI-base/curation/assets/11753634/ef52a7bf-4f8a-41fb-966f-482d0d0d839e)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/8bfe242b-f302-40f5-a394-8c67ed588119)

Will approve session once AE alteration in archetype checked.
Closing ticket.

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
