### ISSUE TITLE
Which genotypes to curate?

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#181]
Often times papers describing chemical resistance phenotypes report the generation of resistant isolates via mutagenesis or directed evolution approaches. These mutants are usually characterised and mutations responsible for the resistance phenotype are often identified, and the identified mutant allele is sometimes transformed into a wild type strain to confirm the relationship between mutation and chemical resistance. In these instances, should **both** genotypes be recorded (the genotypes of the isolates derived from the mutagenesis and transformation experiments)? Or, as both genotypes are virtually the same (in terms of the mutation they harbour), should only one of them be annotated? So far, I have given preference to curate the genotype of the transformant isolates, as these have a "cleaner" background (no other background mutations that would also have been induced during the mutagenesis procedure). However, it might be of interest whether it is important the genotypes generated by both methods, rather than just one.  
@CuzickA what are your thoughts on this? I think it is worth discussing and adding guidance on the FAQ document, as community users might face the same question.

**Comment by CuzickA** [comment]
Hi @MPiovesana, has this been covered in the FAQ now? If so we can close this ticket.

**Comment by MPiovesana** [comment]
> Hi @MPiovesana, has this been covered in the FAQ now? If so we can close this ticket.

@CuzickA Yes, I believe it has :) I will close the ticket.
