### ISSUE TITLE
PMID:23431382 Resistance to the novel fungicide pyrimorph in Phytophthora capsici: risk assessment and detection of point mutations in CesA3 that confer resistance.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#182]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/9b479a3af502709e

**Comment by MPiovesana** [comment]
In this paper, authors investigate the sensitivity of field isolates of _Phytophthora capsici_ to the fungicide pyrimorph. Spontaneous mutants are generated in laboratory conditions from four wild type parental strains, and mutants are phenotypically characterised. A point mutation in the _CesA3_ gene of highly resistant mutants is identified in comparison to the sequence of the wild type parental lines. As mutants derived from all four parental wild type strains display very similar phenotypes and the same genotype, a representative genotype was created in PHI-Canto.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors provide the GenBank accession number for the _PcCesA3_ gene, which retrieved Uniprot ID **H6U2P7**.

**Strain:** wild type strain Hd3 was manually inserted in curation session.

**Host**: bell pepper (_Capsicum anuum_ cv. Tedaqiemen) was added to curation session.

**AC:**  I need to add both the pathogen and host strains to the strain lists.

**Comment by MPiovesana** [comment]
**Genotype creation:** an amino acid substitution allele was created to represent the genotype of the pyrimorph-resistant mutants derived from wild type strain Hd3. 

**Genotype annotations:** the following PHIPO terms were assigned to this genotype:
_resistance to pyrimorph_ (suggested)
_decreased number of asexual spores_

Other fitness parameters were also investigated with less consistent phenotypes observed among mutants and were therefore not curated.

**Comment by MPiovesana** [comment]
**Metagenotype creation:** metagenotypes were created including the WT and mutant CesA3 genotypes and the host bell pepper. The control metagenotype was annotated with PHIPO term "presence of pathogen-associated host lesions", whereas altered genotype was assigned "decreased extent of pathogen-associated host lesions", according to results on Table 4.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Pathogen phenotypes look fine
![image](https://github.com/PHI-base/curation/assets/11753634/1a2438d5-b0ca-4c68-aec8-dfb713bb86da)

~Note: AE alteration in archetype is N/A as CesA3 is not listed as a FRAST target site~ yes it is!

**Comment by CuzickA** [comment]
PHI phenotypes look fine
![image](https://github.com/PHI-base/curation/assets/11753634/792f40e7-fb51-49e8-890e-a71ec38b1331)

**Comment by CuzickA** [comment]
Next
1) Add pathogen and host strain to strain list (Done 10_10_2023)
2) Create PHI-ECO term
3) Create PHIPO terms

This session is checked and once the above are done will be ready to approve.

**Comment by CuzickA** [comment]
Above now done, session approved, closing ticket.

**Comment by CuzickA** [comment]
Correction, I have seen archetype information in Nichola's S Table 6 for Ces3A.

Reopening ticket and unapproving session to add archetype info.

**Comment by CuzickA** [comment]
**AE alteration_in_archetype**

Phytophthora capsici CesA3(aaQ1077K)[Not assayed]


From Nicola's S Table 6
![image](https://github.com/PHI-base/curation/assets/11753634/a5ac9546-c8cb-4eb5-930c-db69b43860fd)

I believe the AE would be 'Q1077K; Ces3A; PHYTIN'

from Maier et al EPPO list
![image](https://github.com/PHI-base/curation/assets/11753634/2a68483f-3136-4386-8b15-e4d71f1bb1b3)

**Comment by CuzickA** [comment]
AE alteration_in_archetype now added and needs checking by Nichola.

**Comment by CuzickA** [comment]
AE alteration_in_archetype checked by Nichola.

Session approved, closing ticket.

**Comment by CuzickA** [comment]
Spotted typo in AE alteration_in_archetype

was
Q1077K; Ces**3A**; PHYTIN

now changed to
Q1077K; Ces**A3**; PHYTIN


![image](https://github.com/PHI-base/curation/assets/11753634/09e09e37-0232-48df-ae57-0df3890b496b)
