### ISSUE TITLE
PMID8307980: Molecular Cloning and Expression of the Saccharomyces cerevisiae  STSl Gene Product  A YEAST ABC TRANSPORTER CONFERRING MYCOTOXIN RESISTANCE

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#183]
curated by @jingluodatacurator

https://canto.phi-base.org/curs/2e8c56d3b55f4354

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I am not sure if YKKB-13 delta sts1 +(pYSTS1) conferring significant increased resistance to cycloheximide from Table 1 should be curated?
I have understood that overexpression of sts1 gene conferred increased resistance to cycloheximide.

**Comment by CuzickA** [comment]
Is it also possible to curate the 'sporidesmin' phenotypes?

**Comment by CuzickA** [comment]
Just to note that this is an example of a paper reporting on homozygous and heterozygous diploid genotypes. We can't currently display the diploid genotypes in PHI-base 5 so if possible in this case it would be useful to only report on the homozygous genotypes.


![image](https://github.com/PHI-base/curation/assets/11753634/0524b274-5f86-4ca0-81a7-dc18c965e432)

Looks like we are reporting on the isogenic haploid strains YKKB-13 and YKKA-7 (different mating types, which we will ignore for now) derived from YKKD-1 (which is a heterozgyous diploid) derived from YPH501.

Makes it a bit tricky to choose the genotype strain. Currently selected YPH501.

![image](https://github.com/PHI-base/curation/assets/11753634/292e7ba9-2bf6-45bf-8b39-c21decce1ae2)

**Comment by CuzickA** [comment]
> Hi @CuzickA, I am not sure if YKKB-13 delta sts1 +(pYSTS1) conferring significant increased resistance to cycloheximide from Table 1 should be curated? I have understood that overexpression of sts1 gene conferred increased resistance to cycloheximide.

Hi @jingluodatacurator, yes I think this could be curated and also the 'sporidesmin' phenotypes.

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I have curated deletion genotype for both chemicals cycloheximide and sporidesmin, I have curated overexpression genotype with deletion background for both chemicals as well. 
Could you please check the allele type for overexpression genotype? I have discussed this with @MPiovesana  and we decided to choose 'other' rather than 'transformant'.

**Comment by CuzickA** [comment]
> Hi @CuzickA, I have curated deletion genotype for both chemicals cycloheximide and sporidesmin, I have curated overexpression genotype with deletion background for both chemicals as well. Could you please check the allele type for overexpression genotype? I have discussed this with @MPiovesana and we decided to choose 'other' rather than 'transformant'.

This sounds good.

In the case of overexpression genotype, typically these can be created using 'wild type +' and then the expression level recorded as overexpression. Would this make sense in the case of this expt?

**Comment by CuzickA** [comment]
Hmm... maybe we can't select both 'overexpression' and 'ectopic' expression at the same time.

**Comment by MPiovesana** [comment]
> > Hi @CuzickA, I have curated deletion genotype for both chemicals cycloheximide and sporidesmin, I have curated overexpression genotype with deletion background for both chemicals as well. Could you please check the allele type for overexpression genotype? I have discussed this with @MPiovesana and we decided to choose 'other' rather than 'transformant'.
> 
> This sounds good.
> 
> In the case of overexpression genotype, typically these can be created using 'wild type +' and then the expression level recorded as overexpression. Would this make sense in the case of this expt?

@CuzickA I have been meaning to ask you about this, as I am not sure always sure how to record this type of genotype. In this particular paper, the authors have deleted the endogenous STS1 gene and then transformed the deletion line with a multicopy plasmid harbouring the WT copy of STS1, so that the resulting line overexpresses STS1. The authors do not clarify the origin of the STS1 gene present in the plasmid, but as it is WT, I think we can assume this is not a case for allele type 'transformant'. As this is a line obtained by genetic transformation, should we still select allele type 'wild type'? And with regards to expression level, the authors mention the plasmid is multi copy, so I believe the transgene is not integrated into the genome - hence why I thought 'ectopic' would be more appropriate. What are your thoughts?

**Comment by CuzickA** [comment]
This is tricky. I believe that the PomBase team are developing a method to indicate the promoters used but this is not ready yet.

In this case I think I would go for the most informative piece of information and record the additional information in the comment so that it could maybe be curated in the future.

For this expt is it more important to indicate that the STS1 gene is overexpressed leading to a phenotype or that it is ectopically expressed? Probably that it is overexpressed.

Please let me know what you think?

**Comment by MPiovesana** [comment]
@CuzickA Agreed, I think it is more important to curate that it has been overexpressed. So in this case we could create a wild type allele type with overexpression expression level. I will need to screen some of my previous curation sections as I encountered similar cases in other papers. 
However, quick question: in this case, I also though perhaps this expt could not be curated in PHI-Canto as it can be considered a control experiment (deletion of the endogenous gene followed by complementation). As this is an overexpression expt, however, is it acceptable to curate it?

**Comment by CuzickA** [comment]
> However, quick question: in this case, I also though perhaps this expt could not be curated in PHI-Canto as it can be considered a control experiment (deletion of the endogenous gene followed by complementation). As this is an overexpression expt, however, is it acceptable to curate it?

Yes, I would curate it as it is an overexpression expt.

**Comment by CuzickA** [comment]
@jingluodatacurator, Please could you add 'sporidesmin' to the excel anti-infectives list and email me the updated copy

**Comment by MPiovesana** [comment]
> > However, quick question: in this case, I also though perhaps this expt could not be curated in PHI-Canto as it can be considered a control experiment (deletion of the endogenous gene followed by complementation). As this is an overexpression expt, however, is it acceptable to curate it?
> 
> Yes, I would curate it as it is an overexpression expt.

@jingluodatacurator I think based on our discussion the genotype must be edited to be a "wild type" allele with "overexpression" selected as expression level :)

**Comment by CuzickA** [comment]
> > However, quick question: in this case, I also though perhaps this expt could not be curated in PHI-Canto as it can be considered a control experiment (deletion of the endogenous gene followed by complementation). As this is an overexpression expt, however, is it acceptable to curate it?
> 
> Yes, I would curate it as it is an overexpression expt.

@MPiovesana, maybe we need to make a note about this in the FAQ section about not curating complementation controls

**Comment by CuzickA** [comment]
> @jingluodatacurator, Please could you add 'sporidesmin' to the excel anti-infectives list and email me the updated copy

Hi @jingluodatacurator, thanks for adding this to the list. Is sporidesmin actually an anti-infective? I see its listed as a mycotoxin. I'm wondering whether it really belongs on the list. What do you think?

**Comment by jingluodatacurator** [comment]
> > @jingluodatacurator, Please could you add 'sporidesmin' to the excel anti-infectives list and email me the updated copy
> 
> Hi @jingluodatacurator, thanks for adding this to the list. Is sporidesmin actually an anti-infective? I see its listed as a mycotoxin. I'm wondering whether it really belongs on the list. What do you think?

I was wondering the same actually. I don't think it belongs to the list as it is not an anti-infective. Let me know if you agree, so I can remove it thanks.

**Comment by CuzickA** [comment]
Yes, please go ahead and remove it thanks @jingluodatacurator

**Comment by CuzickA** [comment]
Note to self - need to check whether we really want the 'sporidesmin' annotations and NTRs.

**Comment by CuzickA** [comment]
I think that for now we will omit the 'sporidesmin' annotations and NTRs as 'sporidesmin' is listed as a mycotoxin. We will keep the cycloheximide annotations as this is an anti-infective.
![image](https://github.com/PHI-base/curation/assets/11753634/811ce662-77be-4d60-b427-e488b7999944)

Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/aeb4aa40-5f7f-4bb6-ad07-81e737c86b7e)

**Comment by CuzickA** [comment]
AE alteration in archetype N/A

Session now approved, closing ticket.
