### ISSUE TITLE
PMID:22897872 In vitro–in vivo correlation of voriconazole resistance due to G448S mutation (cyp51A gene) in Aspergillus fumigatus

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#184]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/e62975095a0dec9d

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I'm not sure about the curated VRC-F33 transformant gene (Table 1), please check.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I can't find an accessible PDF for this paper. Please could you send me your copy so that I can check the session?

**Comment by CuzickA** [comment]
Tagging @jingluodatacurator

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, I can't find an accessible PDF for this paper. Please could you send me your copy so that I can check the session?

Hi @CuzickA, I believe this is the one:

file:///C:/Users/luoj/Desktop/In%20vitro%E2%80%93in%20vivo%20correlation%20of%20voriconazole%20resistance%20due%20to%20G448S%20mutation.pdf

**Comment by CuzickA** [comment]
> > Hi @jingluodatacurator, I can't find an accessible PDF for this paper. Please could you send me your copy so that I can check the session?
> 
> Hi @CuzickA, I believe this is the one:
> 
> file:///C:/Users/luoj/Desktop/In%20vitro%E2%80%93in%20vivo%20correlation%20of%20voriconazole%20resistance%20due%20to%20G448S%20mutation.pdf

Hi @jingluodatacurator, I couldn't access this file. Please could you email me the PDF? Many thanks.

**Comment by CuzickA** [comment]
The Uniprot Q4WNT5 has been used in other curated sessions and is a Swiss-Prot reviewed entry https://www.uniprot.org/uniprotkb/Q4WNT5/entry

**Comment by CuzickA** [comment]
Text from Publication

'A. fumigatus W73355, F55064, and H27063 were obtained from
ATCC and used as VRC-susceptible parent isolates (MIC 0.125–0.25
mg/L).'

'VRC-resistant isolates were selected from the 3 VRC-susceptible
(VRC-S) strains in the laboratory by a 2-step process by exposure
to progressively higher concentrations of VRC (0.5 to 16 mg/L).'

'Laboratory-selected VRC-R isolates of A. fumigatus (n = 6) had
MICs in the range of 2–8 mg/L. Sequencing of the complete
transcriptional unit of cyp51A gene from all 6 isolates revealed a
G448S mutation presumably involving the heme-binding region. On
further MIC testing using other triazoles, we found that G448S
mutation conferred high-level resistance to VRC but not to ITC or POS
(Table 1).'

Corresponds to these annotations
![image](https://github.com/PHI-base/curation/assets/11753634/5a87df08-e893-4308-a3dd-22dca6f2fcae)


This annotations look good @jingluodatacurator, just need to add '+ voriconazole' to the conditions to align with the PHIPO term 'resistance to voriconazole'.
![image](https://github.com/PHI-base/curation/assets/11753634/438d15b9-6424-44f2-89a0-fd600e3576fe)

**Comment by CuzickA** [comment]
Next
1) look at 'VRC-F33 transformant gene (Table 1)' - is this a transformant or gene replacement? (Done 04_10_2023, see below)
2) Add new strains (04_10_2023 added to https://github.com/PHI-base/data/issues/39)
3) Add AE alteration in archetype (Done 04_10_2023, info below)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I'm reopening this ticket as I still need to do the things in the comment above under 'Next'. I usually don't close a ticket until the curation session is fully complete and I have approved it for display in PHI-base.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, I'm reopening this ticket as I still need to do the things in the comment above under 'Next'. I usually don't close a ticket until the curation session is fully complete and I have approved it for display in PHI-base.

Thanks @CuzickA, it might have been an accident sorry.

**Comment by CuzickA** [comment]
Adding AE alteration in archetype

Aspergillus fumigatus
cyp51A(aaG448S)[Not assayed]  'G448S; Cyp51A; ASPEFU'

Info not found in Nichola's S file. Straight forward t find in Mair et al Table 2

![image](https://github.com/PHI-base/curation/assets/11753634/f92a81ae-7b56-4e09-b67c-c1c44f9ea432)
![image](https://github.com/PHI-base/curation/assets/11753634/f94277ae-9735-474d-a821-2644037bef71)

**Comment by CuzickA** [comment]
Working on 

> look at 'VRC-F33 transformant gene (Table 1)' - is this a transformant or just gene replacement?

![image](https://github.com/PHI-base/curation/assets/11753634/fbe39160-13e8-4a3e-a308-b4b27240bbdb)

Strain F55064 is VRC - S (Cyp51 A assume G at residue number 448)
Strain F33 is VRC - R and contains Cyp51A AA alteration 'G448S'
Cyp51A 'G448S' from strain F33 is transformed into strain F55064 (replacing the endogenous copy)
Therefore,  as the origin of the transgene is from another strain, I believe that this would be allele type 'transformant'.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, for this annotation I have made the following changes
1) Made changes to the pathogen genotype
a) Following the guidance for 'transformant' in the FAQ under heading 'How to use the allele type 'transformant'.
b) Adding in the background 'cyp51Adelta' as the mutant cyp51A from strain F33 replaced the wild type cyp51A from strain F55064.

2) Added the chemical  to the conditions
3) Added a comment from the publication text

![image](https://github.com/PHI-base/curation/assets/11753634/a3d7ea6a-fe73-48eb-aae5-32ec4c87afeb)
![image](https://github.com/PHI-base/curation/assets/11753634/e3cad71d-d961-40bc-8ef9-f25f91a645ca)

**Comment by CuzickA** [comment]
Session annotations now fully checked.

AE alteration in archetype needs checking by Nichola and then session ready for approval.

**Comment by CuzickA** [comment]
AE alteration in archetype checked by Nichola.

Approving session and closing ticket.
