### ISSUE TITLE
PMID:21077124 Localisation of the benzimidazole fungicide binding site of Gibberella zeae β2-tubulin studied by site-directed mutagenesis.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#185]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/3e64d02478d528b4

**Comment by MPiovesana** [comment]
In this paper, authors generate mutants of _Gibberella zeae_ (_Fusarium graminearum_) carrying mutant alleles of the _β2-tubulin_ gene. The mutant alleles are generated by site-directed in vitro mutagenesis of the WT _β2-tubulin_ allele from strain 2021, and are introduced in strain DN83, which is strain 2021 harbouring the deletion of _β2-tubulin_. All mutant lines display increased resistance to benzimidazole fungicides and not fitness penalties. Interestingly, the deletion of _β2-tubulin_ (strain DN83) led to a reduction in virulence.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene and species name search retrieved ID Q4HZS8.

**Strain:** strain 2021 was selected for this curation session, as it is the recipient strain for transformation experiments following the deletion of the endogenous wild type _β2-tubulin_ gene. Authors name this strain DN83, but the only difference between this and 2021 is the deletion of _β2-tubulin_. So here I suggest using 2021 as recipient as recording _β2tubΔ_ as background.

**Host:** wheat cv. Yangmai 49 was added to the curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** as the mutant alleles were generated by in vitro mutagenesis of the wt _β2-tubulin_ of strain 2021 (which is also the recipient strain), **amino acid substitution** alleles were created to record these genotypes. The deletion of the endogenous _β2-tubulin_ was recorded as _β2tubΔ_ in background. The mutant genotype β2tubΔ was also created as authors describe the phenotypes of this line. As authors show that expression of the mutant alleles is similar to that of the WT in the parental strain (RT-PCR in Fig 2), I selected 'wild type product level' under expression levels. 

**Genotype annotations:** the following PHIPO terms were used
_resistance to carbendazim_ (AE low, medium and high used according to the text)
_sensitive to carbendazim_

Authors also test the resistance of mutant lines to other benzimidazole fungicides (benomyl, thiabendazole and thiophanate-methyl), with similar results. I was not sure if it was necessary to add all these annotations, as all mutant genotypes are resistant to all fungicides and I thought it could become repetitive. So only carbendazim phenotypes recorded so far.

AC: comment added 'Similar results were obtained with the other benzimidazoles, benomyl, thiabendazole and thiophanate-methyl'

**Comment by MPiovesana** [comment]
**Metagenotype creation:** metagenotypes were created including the WT (2021), β2tubΔ and β2tub mutant genotypes + wheat were created. 

**Metagenotype annotation:** the control wild type and mutant metagenotypes (except for _β2tubΔ_) were annotated with term "presence of pathogen-associated host lesions", as mutant lines displayed unaffected pathogenicity (recorded as annotation extension). The metagenotype composed of the _β2tubΔ_ and wheat plants was annotated with "decreased extent of pathogen-associated host lesions", as this line displayed significantly reduced virulence (also recorded as AE).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Note: same UniProt Q4HZS8 used in this session as in https://github.com/PHI-base/curation/issues/168 :-)

**Comment by CuzickA** [comment]
Session checked and looks good.

Needs one new PHI-ECO term for '16dpi'

**Comment by CuzickA** [comment]
Now approved.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

F167Y; β-tubulin; ASPEND
E198Q; β-tubulin; ASPEND (also see Mair et al Table 4 below)
F200Y; β-tubulin; ASPEND

Straight forward to find in Nichola's S file in Table S1

![image](https://github.com/PHI-base/curation/assets/11753634/4ca910cd-bcac-43f7-8ef7-c37b6952aa25)
![image](https://github.com/PHI-base/curation/assets/11753634/8cfbbc1d-7364-497d-852b-aebfced63cc2)
![image](https://github.com/PHI-base/curation/assets/11753634/83bcb542-eabe-4ef0-bdbd-9b21555066c6)
![image](https://github.com/PHI-base/curation/assets/11753634/66e3fcd9-81fd-47c5-b0b8-8986e8db8933)

**Comment by CuzickA** [comment]
Could not find information in S file for following but found in Mair paper

β2tub-Y50C(aaY50C)[WT level]    'Y50C; β-tubulin; ASPEND'
In Mair et al paper
![image](https://github.com/PHI-base/curation/assets/11753634/787897be-5e0f-4538-ac1f-8da976031cdb)


β2tub-E198K(aaE198K)[WT level]    'E198K; β-tubulin; ASPEND'
![image](https://github.com/PHI-base/curation/assets/11753634/77e99e84-d5fb-49a9-a472-ab0c657fc8b9)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
