### ISSUE TITLE
PMID:30686204 Molecular and Biochemical Characterization of Laboratory and Field Mutants of Botrytis cinerea Resistant to Fludioxonil

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#186]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/0603f5b854b64f55

**Comment by MPiovesana** [comment]
This study reports the generation of laboratory mutants of _Botrytis cinerea_ which display resistance to the fungicide fludioxonil. The mutants are phenotypically characterised (mycelial growth, sporulation, virulence, etc) and the sequence of the _Bos1_ gene revealed point mutations, duplication and premature stop codons in the four highly-resistant mutants isolated by the authors.

**Comment by MPiovesana** [comment]
**Uniprot ID:** in the paper authors indicate gene ID BC1G_00374 for the _Bos1_ gene of _Botrytis cinerea_ (Broad Institute _B. cinerea_ Genome Database). Searching NCBI with this gene ID, we retrieve this page (https://www.ncbi.nlm.nih.gov/gene/?term=BC1G_00374), the locus tag BCIN_01g06260 is provided. Searching Uniprot with this locus tag, two Uniprot IDs are retrieved:

<img width="735" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/45cbba2a-2b48-45d9-a657-34917939fc83">

In the paper, authors mention that the predicted Bos1 protein has 1310 amino acids, but neither of these entries correspond to this length (one is 1315 and the other is 1311 aa long). I selected the first ID for now to allow the next steps of curation, but I believe this needs to be checked as I am not sure this is the best ID for this session.

**AC (04_12_2023):** Session https://github.com/PHI-base/curation/issues/144 also used A0A384J5Y1. We will stick with this for now.

**Comment by MPiovesana** [comment]
**Strains:** wild type strains from which resistant mutants were derived were manually added to the session.

**Host:** as pathogenicity assays were performed, host species strawberry was added. No information on cultivar is provided by the authors, so 'Unknown strain' was selected. Pathogenicity assays are also performed in tomato, with similar results obtained. As this curation session has 4 altered pathogen genotypes, considering the 4 respective wild type genotypes, this results in 8 metagenotypes per host species. So I decided to only record the results obtained in strawberry as representative of the virulence phenotype of these strains.

**Comment by MPiovesana** [comment]
**Genotype creation:** genotypes were created according to the mutation type harboured by each mutant line, as described below:

**Bos1-Q846stop** = allele type _nonsense mutation_ for the replacement of Q846 with a stop codon in strain Nj5-10.

**Bos1-E253D** = allele type _amino acid substitution_ for the E253D mutation in strain Bt3-4.

**Bos1-(55bp duplication + 838stop)** = allele type _amino acid insertion and substitution_ for the duplication of 55 bp resulting in a stop codon at position 838 in strain Bt6-4.

**Bos1-G415D** = allele type _amino acid substitution_ for the G415D mutation in strain Yc-6.

**Comment by MPiovesana** [comment]
**Genotype annotations:** the following PHIPO terms were used:
resistance to fludioxonil
resistance to procymidone (suggested)
resistance to iprodione
decreased number of asexual spores

**Comment by MPiovesana** [comment]
**Metagenotype creation and annotation:** WT (control) and mutant metagenotypes were created with host species strawberry. The WT metagenotypes were annotated with PHIPO term "presence of pathogen-associated host lesions", and altered metagenotypes were assigned the term "decreased extent of pathogen-associated host lesions". Annotation extensions (AE) were used to describe the presence of the disease, the reduced virulence of the mutant genotypes, and comparisons between metagenotypes.

**Comment by MPiovesana** [comment]
**NOTE**: authors also report on the sensitivity to osmotic stress displayed by the resistant genotypes compared to the parental lines. However, as several conditions are testes (NaCl, KCl, glucose, sorbitol, CaCl, MgCl2), this would result in a large number of annotations (considering all four mutant genotypes). I did not curate these so far, but they could be included in the future (results shown in Figure 1).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Need to add new Botrytis cinerea strains to PHI-Canto strain list. These are the wild type S field strains which are parents to the spontaneous R lab mutants
Nj5-10
Bt3-4
Bt6-4
Yc-6

**Comment by CuzickA** [comment]
Pathogen phenotypes checked and look good.

**Next**
1) try to add AE alteration in archetype _AC 06_12_2023 added for 2/4 genotypes. needs checking by Nichola._
2) check PHI phenotypes _AC 06_12_2023_DONE_

**Comment by CuzickA** [comment]
**AE alteration in archetype**
Bc is the archetype species for Bos1/Os-1

Bos1(Q846stop)[Not assayed] Not listed in Nichola's file or Mair et al 2016 - **TO ADD 'Q846stop; Bos1 (OS-1); BOTRCI'**
Bos1(aaE253D)[Not assayed] Listed in Nichola's file ' E253D; Bos1 (OS-1); BOTRCI'
Bos1(aa55bp duplication + 838stop)[Not assayed] Not listed in Nichola's file or Mair et al 2016 - ** duplication causing frameshift and stop (disruption)** **TO ADD 'frameshift indel 835, 838stop Bos1 (OS-1); BOTRCI'**
Bos1(aaG415D)[Not assayed] Listed in Nichola's file 'G415D; Bos1 (OS-1); BOTRCI'

![image](https://github.com/PHI-base/curation/assets/11753634/521d743d-f63a-49f1-a8ba-7286737f507d)
![image](https://github.com/PHI-base/curation/assets/11753634/42fa226f-d267-48ce-9421-62aa3132bda4)
![image](https://github.com/PHI-base/curation/assets/11753634/f653269e-58d9-4921-80f1-f3408bb9147a)

**Comment by CuzickA** [comment]
PHI Phenotypes look fine.

**Comment by CuzickA** [comment]
**Next steps**
1) Add new strains to PHI-Canto
Botrytis cinerea
Nj5-10
Bt3-4
Bt6-4
Yc-6

_Done 11_12_2023 strains added fe050f8_

2) Check AE alteration in archetype with Nichola.
3) Then session is ready for approval

**Comment by CuzickA** [comment]
Checked AEs with Nichola

Bos1(Q846stop)[Not assayed] 'Q846stop; Bos1 (OS-1); BOTRCI'

Added
![image](https://github.com/PHI-base/curation/assets/11753634/229bc95e-e827-4996-9b01-e432857cfba3)

**Comment by CuzickA** [comment]
From paper
![image](https://github.com/PHI-base/curation/assets/11753634/97254b3a-2a65-43df-8754-a2f2babb0eab)

Changing genotype from
Bos1(aa55bp duplication + 838stop)[Not assayed] 
to
Bos1(aa18.3 (55bp) duplication 835 + 838stop)[Not assayed]

We are reporting on a mix of bp and aa. PHI-Canto allele type selected is referring to aa, and automatically adds 'aa' before the '55bp'. This was unclear in the original genotype. Therefore 55/3 = 18.3 aa.

**Comment by CuzickA** [comment]
Bos1(aa18.3 (55bp) duplication 835 + 838stop)[Not assayed]

Added AE 'frameshift indel 835, 838stop Bos1 (OS-1); BOTRCI'

![image](https://github.com/PHI-base/curation/assets/11753634/15a00b81-d8c4-4d48-a421-e4ea7ed94db3)

**Comment by CuzickA** [comment]
Session now approved, closing ticket.

**Comment by CuzickA** [comment]
Made edit from 'frameshift' to 'Frameshift' and reapproved
![image](https://github.com/PHI-base/curation/assets/11753634/3b3f3a79-267c-4d44-9026-5ec9ae48731f)
