### ISSUE TITLE
PMID:22155829 Identification of a Cryptococcus neoformans cytochrome P450 lanosterol 14α-demethylase (Erg11) residue critical for differential susceptibility between fluconazole/voriconazole and itraconazole/posaconazole

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#187]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/dbfd816d79641ac0

**Comment by MPiovesana** [comment]
In this papers authors identify a mutant allele of the _ERG11_ gene of _Cryptococcus neoformans_ that confers high levels of resistance to azoles. The wild type _ERG11_ allele of the reference strain H99 was replaced with the mutant allele from clinical isolate MRL862, carrying 5 point mutations. Authors also manipulated the MRL862 allele to remove some of the point mutations, and identified a single one (Y145F) as being responsible for the azole resistance phenotype.

**AC:** The strain TES9 derived from MRL862 contained the single mutation (Y145F) responsible for the phenotypes. It is a bit hard to know whether the transformant strain name should be MRL862 or TES9. For now I have left it as it is which is MRL862 (ERG11 transformant(MRL862-ERG11(Y145F))[Not assayed]). MRL862 contains 4 point mutations in ERG11 that do not affect the phenotype and one (Y145F), which is recorded within the genotype, that does change the phenotype.

**Comment by MPiovesana** [comment]
**Uniprot ID:** the GenBank accession number of _ERG11_ from recipient strain H99 was provided by the authors (JQ044790) and was used to retrieve ID Q870D1 from Uniprot.

**Strain:** strain H99 was added to curation session as the recipient for transformation experiments.

**Comment by MPiovesana** [comment]
**Genotype creation:** an allele type transformant was created to record the genotype of the H99 strain transformed with the modified _ERG11_ allele from MRL862 harbouring the Y145F mutation. The deletion of the endogenous ERG11 was recorded in background.

**Genotype annotation:** genotype was annotated with the following PHIPO terms:
resistance to fluconazole
resistance to voriconazole
sensitive to itraconazole
sensitive to posaconazole

**Comment by MPiovesana** [comment]
**NOTE:** authors also test the susceptibility of the _C. neoformans_ strains in vivo in infected mice. All strains cause 100% mortality with our without FLC treatment, but mice survived longer when infected parental H99 or H99 transformed with _ERG11-Y145F_ allele. Not sure whether this is relevant for curation, but could be discussed.

**AC:** Looks like this might be a bit tricky to curate so will probably leave it out for now. The graphs in Fig 3 and 4 are comparing treatment or lack of treatment within the PHI for each pathogen strain/mutation rather than WT ERG11 vs ERG11-Y145F. Comparing Fig 3A (H99) and D (TES9) and also Fig4A (H99) and D (TES9) untreated, there doesn't seem to be a big difference in mouse survival between WT ERG11 (H99) vs ERG11-Y145F (TES9).

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Adding AE alteration in archetype
Query - which cyp51a or cyp51b paralogue to map single copy erg11/cyp51 to?
Could not find Cryptococcus neoformans/Filobasidiella neoformans listed in Nichola's S files.
In Mair et al 2016, I have found this information
![image](https://github.com/PHI-base/curation/assets/11753634/6df1ef4e-df26-46c8-a1e7-4e4b5634309d)
(nothing of note in table 2 for cyp51a)
EPPO code FILBNF is for Filobasidiella neoformans
https://gd.eppo.int/taxon/FILBNF

Therefore I believe the AE would be
Y137F; ERG11 (Cyp51B); SEPTTR

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/0bb189eb-baa6-42a8-995d-79984bdc6074)

Approving session and closing ticket.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

Y137F; ERG11 (Cyp51B); SEPTTR

**Questions for Nichola**
1) Which cyp51a or cyp51b paralogue, same question as #172 
**AC:** Cyp51B
2) Could not find Cryptococcus neoformans/Filobasidiella neoformans listed in Nichola's S files. Is it okay to use the above info. from the Mair et al 2016 paper? Please check 'Y137F; ERG11 (Cyp51B); SEPTTR' 
This is correct.

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
