### ISSUE TITLE
PMID:27415408 Homozygous and heterozygous point mutations in succinate dehydrogenase subunits b, c and d of Rhizoctonia cerealis conferring resistance to thifluzamide.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#188]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/a60cdca499c697ac

**Comment by MPiovesana** [comment]
Paper describing the generation of thifluzamide-resistant mutants of _Rhizoctonia cerealis_ by UV-irradiation of wild type strains R1404, R1406 and R1410. Mutants are obtained which harbour point mutations in the target genes _SdhB/C/D_, and phenotypical characterisation is performed.

**Comment by MPiovesana** [comment]
**Uniprot IDs:** authors provide GenBank accession numbers for SdhB/C/D genes of _Rhizoctonia cerealis_, which were used to retrieve Uniprot IDs (indicated below). In Uniprot, entries are deposited as proteins of _Ceratobasidium cereale_ (the teleomorph of _Rhizoctonia cerealis_).

_SdhB_ = KU299049 - A0A173DSZ5
_SdhC_ =  KU299050 - A0A173DSZ3
_SdhD_ = KU299051 - A0A173DT05

**Strains:** strains R1404, R1406 and R1410 were manually added to the curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** allele type _amino acid substitution_ was used to create all mutant pathogen genotypes. Point mutations were recorded against each respective strain. Some mutations were present in more than one strain; to avoid several 'repeated' genotypes and annotations, each mutation was recorded once in a representative strain. As most of the mutants were heterozygous for the mutant alleles, I created diploid locus for all genotypes. 

NOTE: @CuzickA I noticed that when a curation session contains more than one strain and a diploid locus is created, a random strain is automatically selected for the diploid locus, regardless of the one which had been selected during the creation of the haploid locus. Thus, I had to manually edit the strain in each diploid locus after their creation to ensure they were correct. Could be interesting to add this into the FAQ text.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotypes were annotated with terms:
resistance to thifluzamide (suggested)
resistance to boscalid
resistance to bixafen (suggested)
resistance to penflufen (suggested)
sensitive to flutolanil (suggested)
normal growth on flutolanil (suggested)

Annotation extensions were used to classify the level of resistance as **low** or **medium** according to the text.

**Comment by MPiovesana** [comment]
**NOTE:** The paper also reports on the mycelial growth and virulence of mutants; however, there is variability among mutants derived from the same parental strain and harbouring the same mutation, which makes annotation not so robust (although annotation extension **has_severity** _variable severity_ could be used). However, the main focus of the paper is on the resistance to fungicides, which already yielded 30 annotations.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Next - check genotype and phenotype annotations - Table 2 and 3

**Comment by CuzickA** [comment]
Genotype and phenotype annotations look good. 

Added in the new PHIPO and PHI-ECO terms.

**Next steps**
1) add new strains_ added species 79869f1 and strains 70789f1
2) try and add AE alteration in archetype

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Species 'Ceratobasidium cereale' not listed in Nichola's Table S4 or Mair et al 2016 Table of EPPO codes.

Looks like I'll have to try FRAST.

Generated AA FASTA files from Genbank entries
SdhB = KU299049 https://www.ncbi.nlm.nih.gov/nuccore/KU299049
SdhC = KU299050 https://www.ncbi.nlm.nih.gov/nuccore/KU299050
SdhD = KU299051 https://www.ncbi.nlm.nih.gov/nuccore/KU299051

SdhB+[WT level] / SdhB(aaH246Y)[Not assayed] 'H277Y; SdhB; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/fceb72c6-58cf-492c-947b-c1bfc00f759d)
![image](https://github.com/PHI-base/curation/assets/11753634/14a6f3ef-5b78-4c36-873c-51325d202580)


SdhC(aaH139Y)[Not assayed] / SdhC(aaH139Y)[Not assayed] 'H134Y; SdhC; PYRNTE'
SdhC+[WT level] / SdhC(aaH139Y)[Not assayed] 'H134Y; SdhC; PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/19f66dc0-d127-4705-849f-37d3c949b830)
![image](https://github.com/PHI-base/curation/assets/11753634/187be733-c0f3-4300-8033-3e2e7c193325)
![image](https://github.com/PHI-base/curation/assets/11753634/00489f8c-0851-4ba2-baac-3808ef065a3b)


SdhD+[WT level] / SdhD(aaH116Y)[Not assayed] 'H134Y; SdhD; PYRNTE'

SdhD+[WT level] / SdhD(aaH116Y, L129I)[Not assayed] 'H134Y, 147I; SdhD; PYRNTE'

**Check with Nichola if this alignment is good enough? L129I -> 147I**

SdhD+[WT level] / SdhD(aaH116D, H118Y)[Not assayed] 'H134D, H136Y; SdhD; PYRNTE'

![image](https://github.com/PHI-base/curation/assets/11753634/537db0fb-0938-41d4-89f6-c9bba8ab3094)

![image](https://github.com/PHI-base/curation/assets/11753634/62d924e7-9d5a-4a8e-8231-0238a105304e)
![image](https://github.com/PHI-base/curation/assets/11753634/a9935280-091c-47aa-91ce-6fa2742ef7b5)
![image](https://github.com/PHI-base/curation/assets/11753634/d9e22439-af47-44fa-bb3d-566441a58146)

**Comment by CuzickA** [comment]
**Next steps**

1) Check AE alteration in archetype with Nichola.

Then session ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.
Closing ticket.
