### ISSUE TITLE
PMID:29274114 The Y137H mutation in the cytochrome P450 FgCYP51B protein confers reduced sensitivity to tebuconazole in Fusarium graminearum

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#189]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/22d1497fce182de4

**Comment by jingluodatacurator** [comment]
Curation completed and pending review.

**Comment by CuzickA** [comment]
Authors generate tebuconazole-resistant mutants of Fusarium graminearum in this study from wild type strain PH-1.

Selected UniProt id seems sensible https://www.uniprot.org/uniprotkb/I1RBR4/entry

**Genotype creation:**
A Cyp51B gene deletion mutant was created
A site directed mutation and gene replacement strategy was used to create Cyp51B aaY137H

**Genotype annotation:**
Fg PHI-1 Cyp51Bdelta - normal growth on tebuconazole
Fg PHI-1 Cyp51B aaY137H - resistance to tebuconazole

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/a07107bf-e7f2-4c4d-a5db-9321b3e77e5c)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, a couple of points to note here
1) We do not curate the pathogen phenotype controls so I will delete the middle annotation.
2) In the first annotation I will change the 'sensitive to tebuconazole' to 'normal growth on tebuconazole' as the text in the publication states 
'_No significant differences (P >0.05) were observed in the EC50 value of the PH-1 strain compared to that of the ΔB2 strain._'

'Normal growth...' indicates that there is no change in growth between the WT and mutant. Normal growth could be either sensitive or resistance. For PHI-Canto Pathogen phenotypes, we are comparing the altered genotype to the unaltered control genotype (which is not actually curated - see point 1 above). This can be a bit confusing. Please read through the text covering this in the FAQ questions file and we can discuss it if needed :-).

**Comment by CuzickA** [comment]
Now looks like this, with relevant publication text added to comment

![image](https://github.com/PHI-base/curation/assets/11753634/bd9e08cf-7d41-4d49-9a0c-ca3fb4b085bf)

**Comment by CuzickA** [comment]
AE alteration archetype added. (Not listed under Fg in Nichola's S table - need to double check it is correct)

![image](https://github.com/PHI-base/curation/assets/11753634/07dd097f-cb14-48d6-901a-54a82ad7ff50)

**Comment by CuzickA** [comment]
Session approved.
Leaving ticket open so that Jing can read through my comments and so that I can follow up with Nichola about the AE.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

Fusarium graminearum CYP51B(aaY137H)[Not assayed] 'Y137H; Cyp51B; SEPTTR'

**Questions for Nichola**
1) is this correct 'Y137H; Cyp51B; SEPTTR'. I could not find relevant info for Fg on Cyp51B in your S file. I also couldn't find it in Table 3 Mair et al 2016. This AE may need deleting.


![image](https://github.com/PHI-base/curation/assets/11753634/c739bf79-e2c4-4348-8064-5d03114b82fa)

**Comment by CuzickA** [comment]
Nichola said that this publication did not fit the criteria for her S file and so was not included. Her criteria required that the mutation had been found in a field isolate and this lab only reports on lab-base site-directed mutagenesis.

Need to try FRAST for this as not mentioned in other two publications or possibly find extra detail on equivalent codon alignments to archetype Zt or other species in publication.

**Comment by CuzickA** [comment]
From the discussion

![image](https://github.com/PHI-base/curation/assets/11753634/2b67d414-9c39-48c0-9b8b-4c1a413eb903)

Can we assume that Fg Cyp51B mutation Y137H aligns with that in Villosiclava virens?

**Answer: Discussion with Nichola Yes we can 18_10_2023**

See https://github.com/PHI-base/curation/issues/191 Where this AE was added 'Y137H; Cyp51 (Cyp51B); SEPTTR' from Nichola's S file 
![image](https://github.com/PHI-base/curation/assets/11753634/0f3ecca8-4730-467c-9c0d-f788da54a407)



Next: try FRAST, need to find a Fg cyp51B genbank id

**Comment by CuzickA** [comment]
Search genbank
https://www.ncbi.nlm.nih.gov/nuccore/?term=cyp51b+Fusarium+graminearum

![image](https://github.com/PHI-base/curation/assets/11753634/19282909-2fd7-4c1f-9714-e5bed0e2004e)

There are multiple entries and I'm not sure which entry I would use for FRAST.

**Comment by CuzickA** [comment]
To follow up further with Nichola.

**Comment by CuzickA** [comment]
Nichola said 'Y137H; Cyp51B; SEPTTR' is fine.

Approving session and closing ticket.
