### ISSUE TITLE
PMID:35056581 Double Mutations in Succinate Dehydrogenase Are Involved in SDHI Resistance in Corynespora cassiicola

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#190]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/20d4a666c4271c22

**Comment by MPiovesana** [comment]
In this paper, double mutants of _Corynespora cassiicola_ are generated by gene replacement of the endogenous wt _SdhB_ gene of _SdhD_ mutants. The single _SdhD_ mutants were obtained in a previous study, and they are derived from wild type strain SD1. The focus of this paper is on the chemical resistance phenotype and fitness parameters of the double mutants.

**Comment by MPiovesana** [comment]
**Uniprot ID:** a gene and species name search on Uniprot returned several entries for both _SdhB_ and _SdhD_. I could not find any information in the text that could help identify the correct entry (accession number, sequence length, etc). When searching for a reference proteome of _C. cassiicola_, the only one available in Uniprot does not correspond to the correct strain. So, I picked the first entry for each gene to allow the curation of the paper, although I believe these are also not linked to strain SD1. I believe these IDs need to be checked and potentially amended in the curation session.

_SdhB_ = A0A2P1AAZ2
_SdhD_ = D5MTG5

**AC** (29_09_2023): Seems reasonable.

**Comment by MPiovesana** [comment]
**Strain:** I manually added the wild type strain **SD1** to this curation session, as this was the original strain from which single _SdhD_ mutants were derived from.

**Comment by MPiovesana** [comment]
**Genotype creation:** as in this study the _SdhD_ mutants were used as recipient for the gene replacement transformation experiment, I considered adding the _SdhD_ mutant alleles as background; however, I think it makes more sense to record these as multi-locus genotypes, as the investigation of the combined effect of the _SdhB_ and _SdhD_ mutant alleles is the goal of this study. Furthermore, the _SdhB_ mutant alleles were generated by in vitro mutagenesis of the WT_ SdhB_ gene, and therefore the resulting genotypes are best recorded as amino acid substitution rather than transformant in PHI-Canto. Thus, I created single mutant alleles for both _SdhB_ and _SdhD_, which were later combined into multi locus genotypes. The deletion of the endogenous _SdhB/D_ genes was recorded as '_SdhBΔ SdhDΔ_'.

**AC** (29_09_2023): I agree.

**NOTE**: authors measure the expression levels of _SdhA/B/C/D_ genes in the double mutants (Figure 5). The _SdhB_ gene was the only one which showed overexpression in some of the double mutants, and this expression level was recorded accordingly in the multi locus genotypes. The _SdhD_ allele displayed WT product level expression in all double mutants. Expression levels were recorded in multi locus genotypes (as these were the only ones to be annotated).

**Comment by MPiovesana** [comment]
**Genotype annotation:** numerous genotypes annotations were added to record the phenotypes of the double mutants described in this study. The antifungal resistance profile of the mutants was recorded for carboxin and boscalid as representative chemicals; these are also the two chemicals that authors focus mostly on in the text.
**AC** (02_10_2023): This seems reasonable. Additional annotations could be made here in the future if required.

Fitness parameters (sporulation, conidia germination, mycelial growth) were only recorded in those instances where a significant difference was observed compared to the WT strain, and those which were mentioned in the text by the authors. The sensitivity of the mutants to osmotic stress was not recorded as this would result in a large number of annotations, as several compounds were tested (glucose, NaCl, KCl). 
**AC** (02_10_2023): Added 2 annotations as main findings in text reported by authors. (Further annotations could be added in the future if required).
![image](https://github.com/PHI-base/curation/assets/11753634/2f60b24e-82dd-4715-83cc-975e367fbcd7)




The following PHIPO terms were used:

resistance to carboxin
resistance to boscalid (+AE has_severity medium/high)
decreased rate of asexual spore germination
decreased number of asexual spores
increased number of asexual spores
decreased rate of hyphae formation (recorded for different temperatures - low, standard, high)

**Comment by MPiovesana** [comment]
**Metagenotype creation:** a control _SdhB+ SdhD+_ genotype was created to compose a control metagenotype for the pathogenicity assay experiment. Only two mutant metagenotypes were recorded (the only ones to show a significant difference to the control). The wild type metagenotype was assigned the PHIPO term "presence of pathogen-associated host lesions", and the mutant metagenotypes "decreased extent of pathogen-associated host lesions".

**Comment by MPiovesana** [comment]
As this paper reports on numerous fitness phenotypes (mainly shown in Figure 4), additional annotations could be recorded. I tried to record the most important ones in this curation session. 

Curation completed pending review.

**Comment by CuzickA** [comment]
Current annotations for Table 1 checked (note: all double mutants).
![image](https://github.com/PHI-base/curation/assets/11753634/d73bf820-b789-4a57-b083-bd14542ed02e)
![image](https://github.com/PHI-base/curation/assets/11753634/50f5c15c-4500-48c2-8202-993b0054bbed)
![image](https://github.com/PHI-base/curation/assets/11753634/f44cbe1c-8575-4f96-9b79-efafc18da63e)


Still need to think about
1) Should the single mutation genotypes also be curated? 
AC: Probably not as the focus of the paper is on the double mutants as reported above by Maiara.
2) How best to add AE alteration_in_archetype to double mutants?
AC: After discussion with JS, we decided that it would be best to add these as separate AEs. He will remove the cardinality 1 for this AE so that it can be used numerous times. The logic behind doing this is 'I'd lean towards multiple (separate) AEs, because when (or if) we move to using controlled vocabulary for this extension rather than plain text, it's going to be far less complicated if only one combination can be entered for each extension.'

**Comment by CuzickA** [comment]
Need need PHI-ECO term for '6 hpi'

**Comment by CuzickA** [comment]
**AE alteration_in_archetype** (single mutation look up info below)

Corynespora cassiicola 
SdhB-I280V(aaI280V)[Overexpression] 'I279V; SdhB; PYRNTE'
SdhD-D95E(aaD95E)[WT level] 'D124E; SdhD; PYRNTE'

SdhB-H278R(aaH278R)[Overexpression] 'H277R; SdhB; PYRNTE'
SdhD-D95E(aaD95E)[WT level] 'D124E; SdhD; PYRNTE'

SdhB-H278Y(aaH278Y)[WT level] 'H277Y; SdhB; PYRNTE'
SdhD-D95E(aaD95E)[WT level] 'D124E; SdhD; PYRNTE'

SdhB-I280V(aaI280V)[Overexpression] 'I279V; SdhB; PYRNTE'
SdhD-G109V(aaG109V)[WT level] 'G138V; SdhD; PYRNTE'


SdhB-H278R(aaH278R)[Overexpression] 'H277R; SdhB; PYRNTE'
SdhD-G109V(aaG109V)[WT level] 'G138V; SdhD; PYRNTE'

SdhB-H278Y(aaH278Y)[WT level] 'H277Y; SdhB; PYRNTE'
SdhD-G109V(aaG109V)[WT level]  'G138V; SdhD; PYRNTE'

SdhB-I280V(aaI280V)[WT level] 'I279V; SdhB; PYRNTE'
SdhD-H105R(aaH105R)[WT level] 'H142R; SdhD; PYRNTE'

**Comment by CuzickA** [comment]
Single mutations in SdhB for look up
SdhB-I280V(aaI280V) 'I279V; SdhB; PYRNTE'
SdhB-H278R(aaH278R) 'H277R; SdhB; PYRNTE'
SdhB-H278Y(aaH278Y) 'H277Y; SdhB; PYRNTE'

Straight forward to look up in Nichola's S Table 4

![image](https://github.com/PHI-base/curation/assets/11753634/37d46142-cb83-407b-8745-1e476be239e8)

![image](https://github.com/PHI-base/curation/assets/11753634/c1536326-63bb-4dc1-855a-717af3ded4f4)

**Comment by CuzickA** [comment]
Single mutations in SdhD for look up
SdhD-D95E(aaD95E) 'D124E; SdhD; PYRNTE'
SdhD-G109V(aaG109V) 'G138V; SdhD; PYRNTE'
SdhD-H105R(aaH105R) 'H142R; SdhD; PYRNTE'

Straight forward to look up in Nichola's S Table 4

![image](https://github.com/PHI-base/curation/assets/11753634/7f961b37-2ea8-416b-83b4-214f6fe3c122)
![image](https://github.com/PHI-base/curation/assets/11753634/eb29029f-43dc-4192-a92e-0ed712754842)

**Comment by CuzickA** [comment]
Next steps after config updates o/n
1) Add PHI-ECO term (AC: should be ready to add in on 04_10_2023) (Done 4_10_2023)
2) Add AE severity_high (AC: should be ready to add in on 04_10_2023) (Done 4_10_2023)
3) Add AE alteration in archetype (Done 03_10_2023)

4) AE will then need checking by Nichola
5) After 1-4, then session will be ready for approval.

**Comment by CuzickA** [comment]
Added AE alteration in archetype, one entry per target site within multilocus genotype
eg
![image](https://github.com/PHI-base/curation/assets/11753634/a35808c7-c535-4c93-950b-c77db33d82ef)

**Comment by CuzickA** [comment]
Session just needs AE checking by Nichola and will then be ready for approval.

**Comment by CuzickA** [comment]
AE alteration in archetype checked by Nichola.

Approving session and closing ticket.
