### ISSUE TITLE
PMID:25441450 A new point mutation in the iron-sulfur subunit of succinate dehydrogenase confers resistance to boscalid in Sclerotinia sclerotiorum.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#192]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/18d9e451b097de27

**Comment by MPiovesana** [comment]
Authors test whether a point mutation identified in laboratory-generated mutants of _Sclerotinia sclerotiorum_ is responsible for a phenotype of increased resistance to fungicides. The _SdhB-A11V_ allele from mutant strain JK19R1 was introduced by gene replacement in the wild type strain JK19. Two resulting transformants displayed increased resistance to boscalid, carboxin and fluopyram. Hyphal growth and sclerotial production were also assessed compared to the recipient strain.

**Comment by MPiovesana** [comment]
**Uniprot ID:** authors provide gene ID SS1G_04384 for the _SdhB_ gene of _S. sclerotiorum_, which was used to retrieve ID **A7EGE3** from Uniprot.

**Strain:** strain JK19 was manually added to the curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** a transformant allele type was created to record the introduction of the mutant allele derived from strain JK19R1 in strain JK19. The deletion of the endogenous _SdhB_ gene was recorded in background.
Note: authors also replace the mutant with the wild type allele of _SdhB_, but as it consists basically of a control complementation experiment (removal of mutant allele to restore wt genotype), I thought it was not necessary to curate it.

**Comment by MPiovesana** [comment]
**Genotype annotation:** PHIPO terms below were used:

resistance to boscalid
resistance to carboxin
resistance to fluopyram (suggested)
normal hyphal growth
normal sclerotia production (suggested)

Authors also report that mutants do not display altered phenotypes to osmotic stress (NaCl and glucose) compared to the parental strain; perhaps a new PHIPO term (normal sensitivity/resistance to osmotic stress?) could be suggested.

AC: I think for now we will not create 'normal' terms for osmotic stress. I think that the 'normal growth on chemical X' terms were a special case for the fungicide phenotype curation.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Added **AE alteration_in_archetype**


Sclerotinia sclerotiorum SdhB transformant(JK19R1-SdhB(A11V))[Not assayed]

'A11V; SdhB; PYRNTE'

FRAST SdhB/C/D           Pyrenophora teres f.sp. teres  	PYRNTE


Straight forward to find in Nichola's S file in Table S4 (Note error in heading Zt should be PYRNTE'
![image](https://github.com/PHI-base/curation/assets/11753634/5926949c-540f-4ebf-92ba-2e68d911662f)
![image](https://github.com/PHI-base/curation/assets/11753634/bca0c755-dcc6-49a4-8de5-709a276c3722)

**Comment by CuzickA** [comment]
Current session
![image](https://github.com/PHI-base/curation/assets/11753634/183bb1b0-c7ee-474b-84d7-a425809f5fb0)

**Next steps**
1) Add in new PHIPO and PHI-ECO terms
2) Follow up on 'Sclerotia' term with Martin
3) Ask Nichola to check AE

**Comment by CuzickA** [comment]
**Next steps**

1. Add in new PHIPO and PHI-ECO terms **_DONE**
2. Follow up on 'Sclerotia' term with Martin **_ongoing**
3. Ask Nichola to check AE

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/phipo/issues/424

PHIPO terms created to cover sclerotia/resting structure.
Add to session once loaded into PHI-Canto

**Comment by CuzickA** [comment]
AE archetype checked by Nichola and looks fine. 

Added resting structure/sclerotia annotation
![image](https://github.com/PHI-base/curation/assets/11753634/1d251960-48ca-4af0-a5b6-acab23000f6b)

Approving session and closing ticket.
