### ISSUE TITLE
PMID:30732567 Molecular characterization of carbendazim resistance of Fusarium species complex that causes sugarcane pokkah boeng disease

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#194]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/8c52e5b463d36d1b

**Comment by MPiovesana** [comment]
Laboratory-induced mutants of _Fusarium_ spp display increased resistance to the fungicide carbendazim. One of the mutants is derived from wild type strain SJ51 (_Fusarium verticillioides_) and carries a point mutation in one of the _β-tubulin_ genes (FVER_09254). A second mutant is derived from wild type strain HC30 (_Fusarium proliferatum_), and also carries a point mutation in a _β-tubulin_ gene (FPRO_07779). The fitness and pathogenicity of the mutant lines are analysed.

**Comment by MPiovesana** [comment]
**Uniprot ID:** although the authors provide gene IDs for the β-tubulin genes of _F. verticillioides_ and _F. proliferatum_, these do not return any ID when used to search Uniprot. I also searched NCBI with these, and although the search returns gene entries, I could link those to Uniprot entries. Thus, I used the protein sequences displayed in Additional File 3, Figure S1 (amino acid alignments) to perform BLAST searches in Uniprot. With this search, the following IDs were retrieved:

_β-tubulin Fusarium verticillioides_ = **W7M0I3**

_β-tubulin Fusarium proliferatum_ = **P53374** (this one was trickier as no result for _Fusarium proliferatum_ was returned. After a google search I found that _F. proliferatum_ is also known as _Giberella fujikuroi_, and thus this ID was selected. The length and the sequence of the protein match the one used in this study).
AC: Also used in https://github.com/PHI-base/curation/issues/195 :-)

**Comment by MPiovesana** [comment]
**Strains:** strains HC30 (_F. proliferatum/fujikuroi_) and SJ51 (_F. verticillioides_) were manually added to the session.

AC: Now added in PHI-Canto

**Comment by MPiovesana** [comment]
**Genotype creation:** _amino acid substitution_ allele types were created to represent the genotypes of the laboratory-induced mutants. 

**Genotype annotations:** the chemical resistance, temperature sensitivity and pathogenicity of the mutant isolates were recorded with the following PHIPO terms:

_resistance to carbendazim_
_normal growth on carbendazim_ (suggested; could not find higher level term 'chemical phenotype' to suggest child term, so I made suggestion to 'increased sensitivity to chemical'. Term used to record the normal growth of HC30-derived mutant on carbendazim in low temperature, in contrast to standard and high temperatures)
_normal hyphal growth_

**Metagenoype annotations:** the control and mutant metagenotypes composed of _Fusarium_ spp pathogens and sugarcane (host) were recorded with PHIPO term 'presence of pathogen-associated host lesions'. The unaffected virulence of the mutant lines were highlighted with annotation extensions.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
Session checked and all looks fine. Just waiting for a new PHIPO term.

**Comment by CuzickA** [comment]
No alteration in archetype info found in Nichola's S file.

**Comment by CuzickA** [comment]
Try FRAST

**Comment by CuzickA** [comment]
β-tubulin Fusarium verticillioides /moniliformis FVER_09254

β-tubulin Fusarium fujikuroi / proliferatum FPRO_07779

Searching Genbank, cannot find obvious gene sequences.

AA sequence available in Additional file 3 but not in a copy and pasteable format. 
![image](https://github.com/PHI-base/curation/assets/11753634/6af5226e-9e6b-4173-a30e-c3ad8c15fff6)


I'm not sure how to proceed with looking up the archetype AE information for this one.

**Comment by CuzickA** [comment]
After discussion with Nichola
1)gene id prefixes incorrect in paper FVER->FVEG and FPRO->FPRN.
2) Look up FVEG_09254 and FPRN_07779 in genbank to obtain AA seqs
3)Try to align in FRAST and using info in paper above from additional file 3.

**Comment by CuzickA** [comment]
FVEG_09254 https://www.ncbi.nlm.nih.gov/nuccore/XM_018898235.1
FPRN_07779 https://www.ncbi.nlm.nih.gov/nuccore/XM_031234126.1

**Comment by CuzickA** [comment]
FVEG_09254 https://www.ncbi.nlm.nih.gov/nuccore/XM_018898235.1
Very bad / non-alignment in FRAST with beta-tubulin (alignment (?) not saved in FRAST). Unable to find AA sequence match of FASTA file with Additional file seq above.

Not sure how to proceed.

Actually looking at beta-tubulin archetype sequence at position 134 there is 'Q' which matches the Q134 in Fusarium verticillioides /moniliformis strain SJ51 (also Fusarium fujikuroi / proliferatum strains HC30 and HC30M) above. 
![image](https://github.com/PHI-base/curation/assets/11753634/dd702f69-ee7d-4628-aac2-3424d5857715)

Perhaps we could use this AE for 
βtub-Q134L(aaQ134L)[Not assayed] 'Q134L; β-tubulin; ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/71a0a966-679b-45b7-a467-e35f16b3c37b)

**Comment by CuzickA** [comment]
FPRN_07779 https://www.ncbi.nlm.nih.gov/nuccore/XM_031234126.1



Similar poor alignment issue as above.
![image](https://github.com/PHI-base/curation/assets/11753634/bd1911ec-d104-4b8c-95a9-ac6db5781fab)


looking at beta-tubulin archetype sequence at position 351 there is 'S' which matches the S351 in Fusarium verticillioides /moniliformis strain SJ51 and SJ51M above.

However Fusarium fujikuroi / proliferatum strain HC30 has T351and HC30M has I351. Therefore Ff/Fp beta-tubulin differs from the archetype beta-tubulin sequence at position 351.

Perhaps we could use this AE for
βtub-Q134L(aaQ134L)[Not assayed] '351I; β-tubulin; ASPEND'
We would leave the first AA blank as this differed from the archetype.

![image](https://github.com/PHI-base/curation/assets/11753634/d35ab109-798a-4d63-a077-39dbee63429e)


To check this with Nichola.

**Comment by CuzickA** [comment]
**Next steps**
1) check AE with Nichola

Then session will be ready for approval.

**Comment by CuzickA** [comment]
Discussed poor alignment with Nichola. I have given her the sequence ids and she will look into this one.

**Comment by CuzickA** [comment]
I have decided to delete the AE alteration in archetype for now as this session is going to be approved without Nichola checking the AE. 
Approving session.
Closing ticket.
