### ISSUE TITLE
PMID:8702300 Isolation of a beta-tubulin gene from Fusarium moniliforme that confers cold-sensitive benomyl resistance

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#195]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/446d4f792646ef99

**Comment by MPiovesana** [comment]
A benomyl-resistant mutant of _Fusarium moniliforme_ was isolated from a UV-irradiation mutagenesis experiment with wild type strain A102. The fungicide target gene _β-tubulin_ was cloned and sequences derived from the mutant and wild type strains were compared. A single mutation (Y50N) was identified. The benomyl resistance of the mutant strain was shown to be abolished at lower temperatures (15 degrees).

**Comment by MPiovesana** [comment]
**Uniprot ID:** the WT _β-tubulin_ gene of _F. moniliforme_ was deposited in GenBank with accession number U27303, which was used to retrieve ID **P53374** in Uniprot.

**Strain:** wild type strain A102 (used for the UV mutagenesis experiment) was added to the session.

**Comment by MPiovesana** [comment]
**Genotype creation:** an _amino acid substitution_ allele type was created to record the point mutation in the _β-tubulin_ gene. Not assayed was selected as expression level (authors perform a Northern blot but they do not compare expression between WT and mutant strain).

**Comment by MPiovesana** [comment]
**Genotype annotations:** authors mention resistance to benomyl in the text, but the active compound added to growth media is MBC, which is carbendazim. Although benomyl is metabolised into carbendazim and, therefore, they could be considered synonymous, I thought the most accurate way to curate this experiment would be to add +carbendazim to experimental conditions, and use the PHIPO term 'resistance to carbendazim'. Thus, the following annotations were made:

resistance to carbendazim
normal growth on carbendazim (suggested)

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
> **Genotype annotations:** authors mention resistance to benomyl in the text, but the active compound added to growth media is MBC, which is carbendazim. Although benomyl is metabolised into carbendazim and, therefore, they could be considered synonymous, I thought the most accurate way to curate this experiment would be to add +carbendazim to experimental conditions, and use the PHIPO term 'resistance to carbendazim'. Thus, the following annotations were made:
> 
> resistance to carbendazim normal growth on carbendazim (suggested)

This is tricky. I am going to change the annotations from carbendazim to benomyl as this is mentioned in the title and reported on by the authors. I will add a note to the comments that methyl-2-benzimidazole
carbamate (MBC), the active ingredient of benomyl was added to the medium (and that methyl-2-benzimidazole
carbamate = Carbendazim.)

**Comment by MPiovesana** [comment]
@CuzickA thank you for checking this. I was really in two minds about the best way to record this - if using the name of the compound which was actually added to the media or the more 'resistance to benomyl' term. I do agree that it makes more sense to go with the term used by the authors. Thanks for editing it!

**Comment by CuzickA** [comment]
This one is checked and just needs a new PHIPO term.
![image](https://github.com/PHI-base/curation/assets/11753634/4f64866e-bc44-415a-ba27-83aa34ddc62c)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/e380e614-d550-4612-a44a-57ee42a8d08a)

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

Y50N; TUB2 (β-tubulin); ASPEND

Straight forward to find in Nichola's S file in Table S1

![image](https://github.com/PHI-base/curation/assets/11753634/5deb0a01-cdcb-4434-9059-40698b6b4d65)
![image](https://github.com/PHI-base/curation/assets/11753634/171606b0-9ace-4435-a143-479c44a279d7)

**Comment by CuzickA** [comment]
updated genotype

![image](https://github.com/PHI-base/curation/assets/11753634/2d7702a5-f383-4775-a239-590d0f46bffd)

**Comment by CuzickA** [comment]
AE alteration_in _archetype checked by Nichola. Session now approved.
