### ISSUE TITLE
PMID:29933982 Resistance risk assessment of Fusarium oxysporum f. sp. melonis against phenamacril, a myosin inhibitor.

### ISSUE THREAD

**Issue by MPiovesana** [PHI-base/curation#196]
Curated by @MPiovesana 
https://canto.phi-base.org/curs/543da1f17a17a6d3

**Comment by MPiovesana** [comment]
Authors generate phenamacril-resistant mutants of _Fusarium oxysporum_ f. sp. _melonis_ in this study from wild type strain fo. Some of the mutants are found to carry a point mutation in the _myosin5_ gene, while a single mutant carried a mutation in the _β2-tubulin_ gene. Mutants are phenotypically characterised, and their pathogenicity against tomato is also tested.

**Comment by MPiovesana** [comment]
**Uniprot ID:** it was not straightforward to locate an appropriate ID for this curation session. 

_myosin5_: authors provide a gene ID for _myosin5_ in the text (FOXG_11035); however, this ID is associated with a gene from _Fusarium oxysporum_ f. sp. _lycopersici_ rather than _F. oxysporum_ f. sp. _melonis_ (the species used in the study). To complicate matters further, three proteins are associated with this ID in Uniprot, all three with different protein lengths:

<img width="727" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/0ff5bd87-628e-45d6-a0f6-c2c905ea5855">
<img width="722" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/e33cf5af-7e4a-4854-a876-1850c25721c6">

I could not find anywhere in the text a mention to the length of the protein investigated in this study, and so I randomly opened the first entry, A0A0J9WQK8. I then looked up the 'Similar proteins' section, where a protein from _F. oxysporum_ f. sp. _melonis_ is listed as having 100% identity:

<img width="697" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/7a5b9f02-f665-40d8-85a2-dc3752545f38">

Thus, I selected ID **X0BNP7** to represent this protein in this curation session as it seemed like a good option given its homology to the protein from Fox f. sp. _lycopersici_.

**AC Update: 22_01_2024 I think this UniProt is incorrect. See below.**

**Comment by MPiovesana** [comment]
**Uniprot ID (continued):** 

_β2-tubulin_: the gene ID provided by the authors in the text for the _β2-tubulin_ gene (spelled _β2-tublin_ in the paper; ID=FOXG_02339) is associated with one entry in Uniprot:

<img width="729" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/9e263c50-fddd-4992-8b74-4333efbb840f">

When searching the 'Similar proteins' section, a protein with 100% identity from Fox f. sp. melonis is found:

<img width="695" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/914ff56b-b73e-4573-a58b-ce8ca9156d36">

Thus, ID **X0B7Q3** was added to the session.

**Comment by MPiovesana** [comment]
**Strain:** wild type strain fo was manually added to the curation session.

**Comment by MPiovesana** [comment]
**Genotype creation:** as the mutants were obtained by exposure to fungicide amended plates (no genetic transformation involved), amino acid substitution alleles were created to represent the genotypes of the fo-derived mutants described in the study. The following genotypes were created:

myosin5-S175L(aaS175L)
β2tub-A52G(aaA52G)

Mutants fo-2 and fo-3 carried the mutation in the _myosin5_ gene, while mutant fo-4 carried both the mutation in _myosin5_ and _β2tub_. Thus, a multilocus genotype was created to record the genotype of the fo-4 mutant. Mutants fo-1 and fo-5 did not carry any mutation in either of the genes investigated, so their genotypes were not recorded in this curation session.

**Comment by MPiovesana** [comment]
**Genotype annotations:** genotypes were annotated with chemical resistance and fitness terms where appropriate:

resistance to phenamacril (suggested)
decreased hyphal growth
increased hyphal growth
normal number of asexual spores
increased number of asexual spores
sensitive to salt stress
sensitive to sodium dodecyl sulfate (SDS) (suggested)
sensitive to congo red
sensitive to paraquat (suggested; I think perhaps the terms ' sensitive/resistance to oxidative stress' could also be created, and chemical compound responsible for causing ox stress can be added to expt conditions)

**Comment by MPiovesana** [comment]
**Metagenotype creation:** control and mutant metagenotypes were created to record the pathogenicity assay performed in the study. Results displayed in Table 3 show that the lesions induced by mutants fo-2 and fo-3 (myosin5 mutants) did not differ significantly from those of the parental strain fo, despite causing larger lesions on average. The same is true for the double mutant fo-4. The text referring to these results is confusing as the authors say  "the resistant isolates produced significantly smaller lesions compared with the parental isolates (p = 0.05) (Table 3)", even though the lesion area for the parental strain is the smaller of all tested isolates.

<img width="326" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/f194e33e-1b41-46e9-8e4d-05ff5bd6cb0f">

Thus, I guided my annotations according to the numbers and statistical significance showed on the Table rather than on the text. All metagenotypes were annotated with the term 'presence of pathogen-associated host lesions', and the unaffected pathogenicity of the mutant lines was recorded with annotation extensions.


**AC 22_01_2024. Yes this is confusing! In the abstract the text says**
'Compared with the parental isolate, four of the five phenamacril-resistant mutants
showed **enhanced** biological fitness in sporulation and **virulence**, but not in sensitivity to various stresses
(oxidative and osmotic pressure, cell membrane and wall inhibitor).

I think this should be increased virulence - see below for edits.

**Comment by MPiovesana** [comment]
Curation completed pending review.

**Comment by CuzickA** [comment]
New strain 'fo' needs adding to the _Fusarium oxysporum_ strain list.

**Comment by CuzickA** [comment]
Pathogen genotypes look fine.

Just puzzling the UniProt Id for myosin-5 _F. oxysporum f. sp. melonis_
I think that the author provided id 'FOXG_11035' may be a typo as the associated gene name  '4-amino-5-hydroxymethyl-2-methylpyrimidine phosphate synthase' does not sound like 'myosin-5'.

When I do a Google search for 'FOXG_11035' I also pull up this https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6638928/ , no mention of myosin but one mention of FOXG_11035
![image](https://github.com/PHI-base/curation/assets/11753634/3993afdf-9024-44ea-ad7b-1e436f7f261b)

In #200, #201 and #178 it seems as if UniProt names 'Myosin-5' as 'Myosin-1'. Seems to be a trend.

Therefore if search 'myosin-1 Fusarium oxysporum f. sp. melonis' in UniProt get this

![image](https://github.com/PHI-base/curation/assets/11753634/52e3e9ea-6a51-4bb5-b47b-68af86d1a22c)

Not sure which of the two UniProts is correct- they have the same gene name.
Maybe choose the entry with the longer sequence  [X0B2H1](https://www.uniprot.org/uniprotkb/X0B2H1/entry) to move forward with.
Still need to add this to the session.

**Comment by CuzickA** [comment]
I believe X0B2H1 is correct.

looking at #201  the Fo (different f. sp and strain) UniProt selected was https://www.uniprot.org/uniprotkb/W9HIW0/entry which is also 1228 AA in length. I did a clustralW aligment (EBI) with W9HIW0 and X0B2H1 sequences and there is good alignment.

**Comment by CuzickA** [comment]
I have added X0B2H1 (FOMG_00587) for myosin-5/1 Fo f sp melonis to the session.

All genotypes and annotations containing incorrect UniProt id X0BNP7 (FOMG_00267) need replacing with X0B2H1 (FOMG_00587).

This is something that James is going to try and automate with Kim R.

We think that the issue of changing UniProt ids after genotype annotations have been made, may be relatively common for community curators that have difficulty in finding the correct UniProt Id.

**Comment by CuzickA** [comment]
Further evidence pointing to 'myosin-5' and 'myosin-1' being synonyms found in this articles Introduction text

![image](https://github.com/PHI-base/curation/assets/11753634/e4a650dd-7760-4109-b2c7-e9c2995ee406)

**Comment by CuzickA** [comment]
These genotypes and annotations look fine - just need UniProt change in future
![image](https://github.com/PHI-base/curation/assets/11753634/bdecd401-13af-4264-a8fd-bbdf65690265)

**Comment by CuzickA** [comment]
These genotypes and annotations look fine - just need UniProt change in future
![image](https://github.com/PHI-base/curation/assets/11753634/bdecd401-13af-4264-a8fd-bbdf65690265)

**Comment by CuzickA** [comment]
These multi-locus genotypes and annotations look fine - just need UniProt change in future
![image](https://github.com/PHI-base/curation/assets/11753634/bbb6db2b-e7b7-43f4-918f-4d96b55cd3b2)

**Comment by CuzickA** [comment]
Current annotations 
![image](https://github.com/PHI-base/curation/assets/11753634/a7232232-5f04-4fd6-a8f0-c1adaa6aa933)

![image](https://github.com/PHI-base/curation/assets/11753634/82f30fc6-f53e-448b-8e72-973810047c3e)


Suggested changes

![image](https://github.com/PHI-base/curation/assets/11753634/8f1e4882-01aa-476f-bf3b-35766c42e70c)

**Comment by CuzickA** [comment]
Current PHI phenotypes
![image](https://github.com/PHI-base/curation/assets/11753634/27192e08-7782-4200-a722-ddf4511bc7e9)

I think these should both be increased extent of lesions and increased virulence

![image](https://github.com/PHI-base/curation/assets/11753634/abcf6cb3-0cd0-43f8-bef4-e9662f6caae4)

**Comment by CuzickA** [comment]
**Next steps for this ticket**
1) UniProt id change over (JS and KR) _AC has done this manually 24_01_2024_
2) Add new strain _DONE 23_01_2024 e852092_
3) New PHIPO terms - dependent upon outcome on queries in PHIPO tickets _Terms added in Protege 23_01_2024_
4) Add 'paraquat' to PHI-ECO _Added to term creator sheet 23_01_2023_
5) Use FRAST to see if I can add AE alteration in archetype. _DONE 23_01_2024_
6) ask Nichola to check AE alteration in archetype.

Genotypes and annotations all checked.

**Comment by CuzickA** [comment]
**AE alteration in archetype**

myosin5(aaS175L)[Not assayed] Myosin 5 not in Nichola's S file or a table in Mair et al 2016. Need to use FRAST.

 β2tub-A52G(aaA52G)[Not assayed] I could not find this information in Nichola's Table S1 or Mair at al Table 4, so will need to use FRAST.


I will use the UniProt ids to generate the FASTA files as I don't have a correct genbank id to use.
X0B7Q3 for beta-tubulin
X0B2H1 for myosin-5/1

**Comment by CuzickA** [comment]
Also need beta tubulin UniProt id to change from X0B7Q3 (FOMG_04681) to X0B7Q3 (FOMG_04681)

**Comment by CuzickA** [comment]
β2tub-A52G(aaA52G)[Not assayed]
'52G; β-tubulin; ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/d3906e07-f0b9-4240-a799-d04bd436bd52)

Multi-locus genotype so 2 separate AEs added
myosin5(aaS175L)[Not assayed] 'S175L; Myosin-5; GIBBZE'
β2tub-A52G(aaA52G)[Not assayed] '52G; β-tubulin; ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/66bfd267-dd71-4897-ba0f-533fc1530e32)

**Comment by CuzickA** [comment]
myosin5(aaS175L)[Not assayed]
'S175L; Myosin-5; GIBBZE'

![image](https://github.com/PHI-base/curation/assets/11753634/66e65d74-ab48-4fd1-968d-4e178fe96463)

![image](https://github.com/PHI-base/curation/assets/11753634/d80c0051-6d18-47b2-b8e7-288b282f53be)

**Comment by CuzickA** [comment]
**Next steps for this ticket**

1) UniProt id change over (JS and KR) _AC now done manually 24_01_2024_
2) Hook up new PHIPO and PHI-ECO terms once loaded into PHI-Canto _DONE for PHIPO terms 24_01_2024 PHI-ECO doesnt seem to have loaded into PHI-Canto yet??_
![image](https://github.com/PHI-base/curation/assets/11753634/34997e38-371b-4045-a77a-e0762f9c2ce2)

3) Ask Nichola to check AE alteration in archetype.

Genotypes and annotations all checked.

**Comment by CuzickA** [comment]
I have decided to do the UniProt id swap over manually

> All genotypes and annotations containing incorrect UniProt id X0BNP7 (FOMG_00267) need replacing with X0B2H1 (FOMG_00587).

All changes now made
pathogen single and multi-locus genotypes
metagenotypes (single and multi-locus pathogen) and AE compared to control

Old genotypes and incorrect UniProt id now deleted.

**Comment by CuzickA** [comment]
**Next steps**
1) check PHI-ECO term loads overnight now _DONE 29_01_2024_
2) ask Nichola to check alteration in archetype AE
3) Session with then be ready to approve.

**Comment by CuzickA** [comment]
**Next steps**
1) ask Nichola to check alteration in archetype AE
2) Session with then be ready to approve.

**Comment by CuzickA** [comment]
Nichola checked AE and it is fine.

Approving session and closing ticket.
