### ISSUE TITLE
PMID:12519188 Identification and characterization of a Cryptococcus neoformans ATP binding cassette (ABC) transporter-encoding gene, CnAFR1, involved in the resistance to fluconazole.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#198]
https://canto.phi-base.org/curs/eba8868426ff6fa8

**Comment by CuzickA** [comment]
Notes from Jing

Uniprot ID: Q8X0Z3
Strain: BPY22 (CnAFR1 gene)
The main expt for curation: Two matched strains of C. neoformans serotype D, BPY22 and BPY22.17, were used in this study.
See Experimental Procedures sections ‘Disruption of CnAFR1’ and ‘Reintroduction of the CnAFR1 gene in the cnafr1 strain’.

Completed and pending review

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, Please could you email me your highlighted PDF for this curation session?

**Comment by CuzickA** [comment]
From publication
'gene we named as CnAFR1 (GenBank accession number AJ428201).'

UniProt [Q8X0Z3](https://www.uniprot.org/uniprotkb/Q8X0Z3/entry)

Looks correct.

**Comment by CuzickA** [comment]
**Expt summary**

azole susceptible strain BPY22 was exposed to fluconazole -> azole resistant strain BPY22.17
gene responsible for this was CnAFR1
Gene CnAFR1 in strain BPY22.17 had enhanced expression compared to Gene CnAFR1 in strain BPY22
Unfortunately I can't find any sequence information in the article indicating how the gene or promoter region has been changed in the azole resistant strain leading to increased expression. Can you see this information anywhere @jingluodatacurator?

The CnAFR1 in azole resistant strain BPY22.17 was then disrupted, resulting in no detectable transcripts and increase sensitivity to fluconazole compared to the parental line BPY22.17. (Fig 4).

Tricky to know what to compare here.
BPY22 vs BPY22.17 (increased expression of CnAFR1)
BPY22.17 vs BPY22.17 CnAFR1disruption.

**Comment by CuzickA** [comment]
Current annotation

![image](https://github.com/PHI-base/curation/assets/11753634/e30940c6-2078-4cb1-a724-c66352e6f5ae)

**Comment by CuzickA** [comment]
> **Expt summary**
> 
> azole susceptible strain BPY22 was exposed to fluconazole -> azole resistant strain BPY22.17 gene responsible for this was CnAFR1 Gene CnAFR1 in strain BPY22.17 had enhanced expression compared to Gene CnAFR1 in strain BPY22 Unfortunately I can't find any sequence information in the article indicating how the gene or promoter region has been changed in the azole resistant strain leading to increased expression. Can you see this information anywhere @jingluodatacurator?
> 
> The CnAFR1 in azole resistant strain BPY22.17 was then disrupted, resulting in no detectable transcripts and increase sensitivity to fluconazole compared to the parental line BPY22.17. (Fig 4).
> 
> Tricky to know what to compare here. BPY22 vs BPY22.17 (increased expression of CnAFR1) BPY22.17 vs BPY22.17 CnAFR1disruption.

Hi @jingluodatacurator, what are your thoughts on what we should curate here?

**Comment by jingluodatacurator** [comment]
Summary of expt.:

(Exposure of BPY22 to fluconazole in vitro)
Fifty colonies of the fluconazole-susceptible strain BPY22 were inoculated in 2 ml of YEPD liquid medium containing fluconazole at a concentration of 0.5 µg ml−1. After incubation for 48 h at 30°C under constant agitation (240 r.p.m.), an aliquot of broth culture (20 µl) was transferred into 2 ml fresh medium containing 0.5 µg of fluconazole ml−1, and incubated for 48 h at 30°C. Each colony was subcultured twice in YEPD liquid medium containing 1, 5, 10, 15, 20, 25, 50 or 100 µg of fluconazole ml−1, and the cells were incubated as described above. Colonies that grew at the highest concentration of fluconazole (100 µg ml−1) were considered to be putative fluconazole-resistant
derivatives and subcultured on fluconazole-free YEPD agar and incubated for 48 h at 30°C. These colonies were
tested for their susceptibility to fluconazole, as described below. Colonies that exhibited high MIC values were subcultured for at least 20 passages onto fluconazole free YEPD agar, to assess the stability of the resistance phenotype. After each subculture, antifungal drug susceptibility testing was performed (see below).

(Drug susceptibility testing)
Briefly, 104 cells ml−1 were inoculated into YNB broth in a microtitre plate and incubated at 35°C for 48–72 h. Endpoint readings were recorded with an automatic plate reader (Bio-Rad, Hercules, CA) and MICs were defined as
the first concentration of drug determining a 80% growth inhibition compared to the control growth. Antibiotic medium 3 broth (Difco) was used for susceptibility testing to amphotericin B (Rex et al., 2001). All tests were performed at least five times on separate occasions. Additionally, MICs were determined using RPMI as a medium according to the NCCLS M27-A guidelines. Results were similar to those obtained with the modified NCCLS method.

(Disruption of CnAFR1)
To construct a plasmid for CnAFR1 gene disruption, a fragment of 230 bp was removed from CnAFR1 coding region by digestion of the pCnAFR1gen with NheI and BstEII restriction enzymes (Fig. 4A). This fragment was replaced by the 2150 bp Act:Hyg cassette from pCnTelHyg plasmid (Cox et al., 1996), that was amplified using PCR to add NheI and BstEII sites to the two ends. This knockout construct was linearized by digestion with XbaI and used to transform the BPY22.17 resistant strain, using biolistic delivery of DNA as described (Casadevall and Perfect, 1998). The transformants grown on a selective medium containing hygromycin B were screened for disruption of the native CnAFR1 using PCR and primers (ko1, 5′-GCTACCTCCGATTACAATGT-3′ and ko2 5′-GTTGATCCTAGAGAATTCAT-3′) adjacent to the insertion of the marker gene (Fig. 4A). Putative cnafr1 strains were then screened by Southern blot analysis using the DIG-labelled probe C1H9 and the mutant with a single insertion on Southern analysis was designed strain cnafr1.

(Reintroduction of the CnAFR1 gene in the cnafr1 strain)
(NOT for curation as it was a complementation control experiment)
The genomic BamHI CnAFR1 fragment, isolated from BPY22.17 strain, was ligated into the BamHI site of the plasmid pGMC300 derived from pGMC200 (McDade and Cox, 2001), conferring resistance to the antibiotic nourseothricin. This plasmid was used to transform strain cnafr1 using biolistic delivery. Transformants were selected on YEPD agar containing nourseothricin and screened by PCR with primers ko1 and ko2 described above. Six of the 16 selected transformants displayed two amplicons, corresponding to the disrupted native gene and the introduced CnAFR1 (Fig. 3C). The presence of the reintroduced gene was confirmed by Southern and Northern blot analyses (Fig. 3D). The six strains were tested for antifungal drug susceptibility. One of these strains having fluconazole MIC of 64 µg ml−1 was chosen for further study, and was designated Rec 15.

**Comment by jingluodatacurator** [comment]
Uniprot IDs: GenBank accession number was provided by the author AJ428201, which was used to locate the ID Q8X0Z3.

Strains: BPY22 was the wild type fluconazole susceptible strain used for mutation expt. BPY22.17 was the fluconazole resistant strain derived from BPY22 by exposure to the drug.

**Comment by jingluodatacurator** [comment]
Genotype creation:

BPY22.17, CnAFR1 have been curated for fluconazole.

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks

https://canto.phi-base.org/curs/eba8868426ff6fa8

**Comment by CuzickA** [comment]
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/395d3523-8251-4ef3-9d76-7a13ddea59ac)

**Comment by CuzickA** [comment]
Figure 4 A

![image](https://github.com/PHI-base/curation/assets/11753634/d20519e3-618c-428f-a8f0-861ac8dedfc9)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,

This annotation looks like a 'Complementation control experiment' which we do not curate.

Here is the text from our 'Draft Chemistry curation FAQ and tips' file

![image](https://github.com/PHI-base/curation/assets/11753634/0d43becd-35fa-43d8-accc-7c566d012713)


![image](https://github.com/PHI-base/curation/assets/11753634/b2e04c23-242a-4af0-a1f2-bc1ef51a9879)

> (Reintroduction of the CnAFR1 gene in the cnafr1 strain)
> The genomic BamHI CnAFR1 fragment, isolated from BPY22.17 strain, was ligated into the BamHI site of the plasmid pGMC300 derived from pGMC200 (McDade and Cox, 2001), conferring resistance to the antibiotic nourseothricin. This plasmid was used to transform strain cnafr1 using biolistic delivery. Transformants were selected on YEPD agar containing nourseothricin and screened by PCR with primers ko1 and ko2 described above. Six of the 16 selected
> transformants displayed two amplicons, corresponding to the disrupted native gene and the introduced CnAFR1 (Fig. 3C). The presence of the reintroduced gene was confirmed by Southern and Northern blot analyses (Fig. 3D). The six strains were tested for antifungal drug susceptibility. One of these strains having fluconazole MIC of 64 µg ml−1 was chosen for further study, and was designated Rec 15.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,

I don't understand this annotation, the genotype has the strain name. Please can you check this?

![image](https://github.com/PHI-base/curation/assets/11753634/38ab43ea-c56b-4ddf-b932-0c1baf00bcc5)

**Comment by CuzickA** [comment]
Looking at Table 4A and my notes from above (copied below), @jingluodatacurator please could you further explain these annotations?
Is the first annotation representing 'BPY22.17 vs BPY22.17 CnAFR1disruption' and the second annotation representing 'BPY22 vs BPY22.17 (increased expression of CnAFR1)'?

![image](https://github.com/PHI-base/curation/assets/11753634/e4256a25-7c2c-4dab-b38e-bfd7c35a62ca)


> Expt summary
> 
> azole susceptible strain BPY22 was exposed to fluconazole -> azole resistant strain BPY22.17
> gene responsible for this was CnAFR1
> Gene CnAFR1 in strain BPY22.17 had enhanced expression compared to Gene CnAFR1 in strain BPY22
> Unfortunately I can't find any sequence information in the article indicating how the gene or promoter region has been changed in the azole resistant strain leading to increased expression. Can you see this information anywhere @jingluodatacurator?
> 
> The CnAFR1 in azole resistant strain BPY22.17 was then disrupted, resulting in no detectable transcripts and increase sensitivity to fluconazole compared to the parental line BPY22.17. (Fig 4).
> 
> Tricky to know what to compare here.
> BPY22 vs BPY22.17 (increased expression of CnAFR1)
> BPY22.17 vs BPY22.17 CnAFR1disruption.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/3bc15219-755e-4c4a-8313-30cba474341e)

Hi @jingluodatacurator, for some reason GitHub would let me reply to your comment above so I have snipped it into this one.


Two of these genotypes are incorrect as the **genotype needs to contain the name of the gene CnAFR1**. Please could you make a note of this in your curation checklist. Thanks.
![image](https://github.com/PHI-base/curation/assets/11753634/41caf053-cd05-4ded-9861-bd16dd78d1e9)

**Comment by CuzickA** [comment]
Next steps for @jingluodatacurator 
1) Please read through and respond to my comments
2) Remove unneeded annotation
3) Make edits to remaining annotations to fit the expts reported on.
4) Label the 'disruption' mutant in the standard way as discussed previously in other sessions.
5) Add any required notes on 'genotype creation' to your personal curation checklist.

**Comment by jingluodatacurator** [comment]
> Next steps for @jingluodatacurator
> 
> 1. Please read through and respond to my comments
> 2. Remove unneeded annotation
> 3. Make edits to remaining annotations to fit the expts reported on.
> 4. Label the 'disruption' mutant in the standard way as discussed previously in other sessions.
> 5. Add any required notes on 'genotype creation' to your personal curation checklist.

Hi @CuzickA, I believe I have completed steps 1, 2, 3 above please check thanks. I'm not sure about 4, could you please send me a link to a previous session as reference? 5 - will add notes on 'genotype creation' to my personal curation checklist.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, here are links to two sessions you have curated in the past that contain 'disruption' mutant genotypes.
#202 and #204 
Perhaps you could add this information to your person curation checklist.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, here are links to two sessions you have curated in the past that contain 'disruption' mutant genotypes. #202 and #204 Perhaps you could add this information to your person curation checklist.

Hi @CuzickA, I have labelled the disruption mutant in the standard way discussed from before and added related notes in my personal curation checklist under creating genotypes.

**Comment by CuzickA** [comment]
> > Hi @jingluodatacurator, here are links to two sessions you have curated in the past that contain 'disruption' mutant genotypes. #202 and #204 Perhaps you could add this information to your person curation checklist.
> 
> Hi @CuzickA, I have labelled the disruption mutant in the standard way discussed from before and added related notes in my personal curation checklist under creating genotypes.

Hi @jingluodatacurator, thanks for having a go at this. It is nearly correct. Just some small changes to make
Current disruption genotype
![image](https://github.com/PHI-base/curation/assets/11753634/b3827118-2b7d-4ea1-8386-1786cfda431c)

disruption genotype from example ticket https://github.com/PHI-base/curation/issues/202
![image](https://github.com/PHI-base/curation/assets/11753634/450616f1-edfb-47ee-bc22-a120a65fb86c)



Please have another go.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,

do you think this should be overexpression?
![image](https://github.com/PHI-base/curation/assets/11753634/e580e800-a59d-4745-8da4-9a0cecda46d2)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I have also noticed a 'chemical' missing from the conditions. Please check this as you run through your personal curation checklist.

I think we also need to double check the conditions. Are they the same or different for each?
![image](https://github.com/PHI-base/curation/assets/11753634/bf1c2089-a900-4cdd-bf59-0266fdf3b1e0)

**Comment by jingluodatacurator** [comment]
> > > Hi @jingluodatacurator, here are links to two sessions you have curated in the past that contain 'disruption' mutant genotypes. #202 and #204 Perhaps you could add this information to your person curation checklist.
> > 
> > 
> > Hi @CuzickA, I have labelled the disruption mutant in the standard way discussed from before and added related notes in my personal curation checklist under creating genotypes.
> 
> Hi @jingluodatacurator, thanks for having a go at this. It is nearly correct. Just some small changes to make Current disruption genotype ![image](https://private-user-images.githubusercontent.com/11753634/313642142-b3827118-2b7d-4ea1-8386-1786cfda431c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDkzNjQsIm5iZiI6MTcxMDg0OTA2NCwicGF0aCI6Ii8xMTc1MzYzNC8zMTM2NDIxNDItYjM4MjcxMTgtMmI3ZC00ZWExLTgzODYtMTc4NmNmZGE0MzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDExNTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjU0ZjIxZTEzNWZjODA3NGEyNWIyZDY1YjRjM2QwOWJmMDAzZTI1YWQyZGExYjY0ZmU0NjBkMjdjOTVlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDL3e7T9tatpmhPYeTyxfZ7crfK0R_VozVtxmXe-y-o)
> 
> disruption genotype from example ticket #202 ![image](https://private-user-images.githubusercontent.com/11753634/313642050-450616f1-edfb-47ee-bc22-a120a65fb86c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDkzNjQsIm5iZiI6MTcxMDg0OTA2NCwicGF0aCI6Ii8xMTc1MzYzNC8zMTM2NDIwNTAtNDUwNjE2ZjEtZWRmYi00N2VlLWJjMjItYTEyMGE2NWZiODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDExNTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Y2JiNGZiNjkwNmFhMjA0YzVlMzYyNGZkZjhkY2I1ZjBjZDZlYjRjN2Q5YjM2MGFhZGEzMmU1MjYwYTE2MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HPgwTR8iJ-jt2qCD8Q5yPy8ufBAp9U4SwkvThiwQVkE)
> 
> Please have another go.

Hi @CuzickA, change has been made and notes on creating disruption mutants been recorded in Jing's personal curation checklist.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator,
> 
> do you think this should be overexpression? ![image](https://private-user-images.githubusercontent.com/11753634/313643956-e580e800-a59d-4745-8da4-9a0cecda46d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTI5MDksIm5iZiI6MTcxMDg1MjYwOSwicGF0aCI6Ii8xMTc1MzYzNC8zMTM2NDM5NTYtZTU4MGU4MDAtYTU5ZC00NzQ1LThkYTQtOWEwY2VjZGE0NmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEyNTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZmRlNzA4ZWI3ZjIyNzMwNjg3MzM4NzIxZDkwZmJjNTQ3ODBlZmI0ODczNDgxYzhjNjkzZmJiYmFkYWMxNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tnylxQ0g2vl0pUduNWApVuBSKMh4ZmQ5YcL5cOeUlzU)

Hi @CuzickA, yes I agree and change has been made thanks.

**Comment by CuzickA** [comment]
Thanks @jingluodatacurator, 

what about this question from above 

> 'I think we also need to double check the conditions. Are they the same or different for each?'

![image](https://github.com/PHI-base/curation/assets/11753634/4c8106e9-dfcf-474b-8c16-4ca556bd796b)


Should they be the same or should they be different?

**Comment by CuzickA** [comment]
Note to self: I need to add new strains to list

**Comment by jingluodatacurator** [comment]
> Thanks @jingluodatacurator,
> 
> what about this question from above
> 
> > 'I think we also need to double check the conditions. Are they the same or different for each?'
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/314117429-4c8106e9-dfcf-474b-8c16-4ca556bd796b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTMwNjcsIm5iZiI6MTcxMDg5Mjc2NywicGF0aCI6Ii8xMTc1MzYzNC8zMTQxMTc0MjktNGM4MTA2ZTktZGZjZi00NzRiLThjMTYtNGNhNTU2YmQ3OTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDIzNTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2UzOWFiOTE3NGU0ZTM4ZGVlNzk3NWU3YWM5YzM5OThiNTJiNTIxZTE1YjU0OGRhNzY1Y2ZjZjVlNWNhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wlr0mApqVRMl4ic8WvCV-41LitF4t46d6L6rPSRVQ2U)
> 
> Should they be the same or should they be different?

Hi @CuzickA, they should be the same and I have made the corrections thanks.

**Comment by CuzickA** [comment]
This was a tricky one.
Annotations  seem ok now
![image](https://github.com/PHI-base/curation/assets/11753634/57d1928b-770d-43bc-b660-e38b6cecb0c6)

**Comment by CuzickA** [comment]
Added strains to list f005440

**Comment by CuzickA** [comment]
Session now approved. Closing ticket.
