### ISSUE TITLE
PMID:11057448 Characterization of laboratory mutants of Venturia inaequalis resistant to the strobilurin-related fungicide kresoxim-methyl.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#199]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/ed8a3d1341fc9e64

Copy of Jing's note from Google Doc (currently no GitHub access)

Uniprot id: O48334
Strain: KNH-6-95

The main expt for curation: mutants 1-6 were derived from the isolate KNH-6-95 through UV mutagenesis (KNH-6-95 is a wild-type isolate described previously, Olaya et al. 1998). The cytochrome b sequence of the mutant determined after one round of mycelial cultivation in liquid culture under selective conditions was distinguished by an amino acid exchange of glycine to alanine at position 143, as indicated by a clearly distinguished GGT to GCT point mutation at the corresponding position. A G143A exchange is likely to confer a decreased binding of strobilurin-related inhibitors to their cytochrome b target site. 

curation completed and pending review

**Comment by CuzickA** [comment]
Authors provided Genbank id AF047029
Straight forward UniProt reviewed entry https://www.uniprot.org/uniprotkb/O48334/entry

**Comment by CuzickA** [comment]
Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/5e253900-4620-480e-a3b6-102393ed0b8a)

**Comment by CuzickA** [comment]
Two types of resistant mutants generated
![image](https://github.com/PHI-base/curation/assets/11753634/d6b95ade-e50d-4377-832e-31c5a1c2798a)

We will not curate the mutants described first in
![image](https://github.com/PHI-base/curation/assets/11753634/7633d252-7cac-4216-b503-2a53d95a5a31)
(Table 1) because no sequence changes in CytB target site were found.
![image](https://github.com/PHI-base/curation/assets/11753634/420d79c8-ad95-4aea-bb77-34d423d5183c)


Instead we will curate the mutant selected for Kresoxim-methyl resistance in the presence of alternative oxidase inhibitor, where a sequence alteration G143A was found. (Fig1 and resistance info in this text).
![image](https://github.com/PHI-base/curation/assets/11753634/03ac8641-1479-4c06-b028-9c8f9af7bfa3)

**Comment by jingluodatacurator** [comment]
Agreed.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I'm just removing the 'approved' label you added as I have not quite finished checking this session. I use the 'approved' label once the session is complete and 'approved' in PHI-Canto for eventual display in PHI-base 5.

**Comment by CuzickA** [comment]
Some edits made to annotation. @jingluodatacurator, please could you have a look through these and see if you agree.
1) I have added a comment
2) Removed 'Table 1' as this provides data for the first type of mutant (see above) which we are not curating. Added 'text p150'.
3) In the conditions, removed 'uv' as this was the method of mutant generation and not the condition in which the resulting mutant was tested in. Added 'liquid culture' and '10 dpi'. 
![image](https://github.com/PHI-base/curation/assets/11753634/fe830b24-38cf-4fe2-aedd-132757bd2aa9)
4) Also in conditions, added '+ kresoxim-methyl' to mirror the PHIPO term annotation. (Note: new conditions can be entered and will be visualised as red text until we create the new ontology term in PHI-ECO and load this into PHI-Canto for use in curation).

Current annotation now looks like this (note: having an issue with the PHIPO term display https://github.com/PHI-base/phipo/issues/419)
![image](https://github.com/PHI-base/curation/assets/11753634/726bd574-0817-4947-b8c8-2f097ebb41e7)

**Comment by CuzickA** [comment]
Note to self: I'm not sure whether 'SHAM' / 'alternative oxidase inhibitor' should also be added to conditions. I have not added it yet. Instead I have added a GitHub label to group 'Cyt B target site' sessions to see if 'SHAM' / 'alternative oxidase inhibitor' is commonly used in these expts.

**Comment by CuzickA** [comment]
**AE alteration_in_archetype**

Information not found in Nichola's S file.
Found in Mair et al Table 1

Venturia inaequalis cytochrome b(aaG143A)[Not assayed] 'G143A; CytB; SEPTTR'

Venturia inaequalis = VENTIN EPPO code

![image](https://github.com/PHI-base/curation/assets/11753634/661c98ef-c963-4821-a2fb-d006822ceeee)

**Comment by CuzickA** [comment]
Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/3c9bf345-99d0-4e6b-af73-7ed0f218b1a5)

**Next steps**
1) resolve PHIPO term display issue
2) check AE with Nichola

**Comment by CuzickA** [comment]
PHIPO term is displaying correctly now
![image](https://github.com/PHI-base/curation/assets/11753634/36cf042f-debd-4f9b-993b-edba7aad5a3c)


**Next**
1. Check AE with Nichola
2. After this session will be ready to approve

**Comment by CuzickA** [comment]
AE alteration_in_archetype checked by Nichola and looks fine.

Approving session and closing ticket.
