### ISSUE TITLE
Add controlled vocabs for subset of pathogen spore info

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#2]
Please add controlled vocabs eg 'reduced'/ 'increased' etc. to columns 'veg_spores', 'sexual_spores', 'in vitro_growth', and 'spore_germination' as per author guidelines to the currently entered numerical values for entries 
PHI:5589 to PHI:5692
PubMed 25299517

**Comment by CuzickA** [comment]
in preparation for version 4.4

**Comment by martin2urban** [comment]
All records corrected  and ontology terms applied.
