### ISSUE TITLE
Making additional Chemical information available in future PHI5 display

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#20]
During a 'chemistry' discussion with @martin2urban we wondered how to capture and display additional chemical information eg FRAC code/mode of action in the future when we move to PHI-canto curation and gene-centric PHI5 display pages.

PHI-Canto will capture a phenotype eg 'increased resistance to cyproconazole'. 
(There will be a CHEBI:ID behind the cyproconazole making up the logical definition, will this CHEBI:ID be displayed in PHI5?)

Currently in PHI4 we capture additional information on the chemistry in a separate tab as below

![image](https://user-images.githubusercontent.com/11753634/53643180-55aa5f80-3c2b-11e9-9b89-4f329f9cf426.png)

It appears there is a missing link connecting CHEBI and FRAC codes. Our latest Chemical spreadsheet captures some of this information.

Perhaps we could display this information post-PHI-Canto curation, in a PHI5 parsing step. Maybe we could have a pop up on the PHI5 results display so that when the chemical name from the phenotype is clicked it could linkout to our chemical spreadsheet FRAC/MOA information.

Alternatively, perhaps a FRAC code could be added as an annotation extension to a single organism chemistry phenotype.

**Comment by ValWood** [comment]
I wouldn't do this via an extension, because it's an automatable task. This info could be extracted  by a pipeline .

**Comment by CuzickA** [comment]
@martin2urban we should discuss whether we still want to do this and include the CHEBI id in the PHI5 gene-centric display mock-ups.

**Comment by CuzickA** [comment]
I think @jseager7 has automated the info for the AE and this task is done. Closing ticket.
