### ISSUE TITLE
PMID:25648042 Whole-genome sequencing reveals that mutations in myosin-5 confer resistance to the fungicide phenamacril in Fusarium graminearum

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#200]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/fc2f904bb33877a5

**Comment by jingluodatacurator** [comment]
Notes:

Uniprot id: I1RII8 (?, needs checking)
Strain: PH-1, 2021 (??, needs checking)
The main expt for curation: To further test whether the mutations in myosin-5 confer resistance to phenamacril, we replaced the myosin-5 locus between sensitive and resistant strains by homologous double exchange. Firstly, the myosin-5 loci of resistant strains Y2021A, B, C, D, and F were introduced individually into the sensitive strain 2021 by gene replacement. Secondly, the myosin-5 of the sensitive strain 2021 and the resistant strain Y2021F were introduced individually into resistant strain Y2021A, whose resistance level differed from that of Y2021F.
Y2021D was moderately resistant (EC50542), while YP-1 and Y2021F were highly resistant (EC50 5146 and 149), which indicated that the mutation at codon 786 is not the primary mutation resulting in phenamacril resistant and may not even affect phenamacril resistance (Table 2). Y2021A, B, and C were highly resistant (EC50 .200)

**Comment by jingluodatacurator** [comment]
Completed and pending review.

**Comment by CuzickA** [comment]
Added updated phenamacril PHIPO and PHI-ECO terms to current annotations.

**Comment by CuzickA** [comment]
UniProt ID
Ideally we would use the UniProt id for myosin-5 for the reference proteome strain PH-1 of Fg.

@jingluodatacurator, how did find this Uniprot id? https://www.uniprot.org/uniprotkb/I1RII8/entry


I just blasted the FASTA AA sequence from the FRAST site entry for Myosin-5 archetype sp Fg (according to Nichola) and got 100% match with https://www.uniprot.org/uniprotkb/I1RCT2/entry

This is the same UniProt Id that I find by searching uniprot for 'FGSG_01410' as provided by authors. Unfortunately it is in UniParc and may not be possible to use in curation.
https://www.uniprot.org/uniprotkb/I1RCT2/entry

**Comment by jingluodatacurator** [comment]
> UniProt ID Ideally we would use the UniProt id for myosin-5 for the reference proteome strain PH-1 of Fg.
> 
> @jingluodatacurator, how did find this Uniprot id? https://www.uniprot.org/uniprotkb/I1RII8/entry
> 
> I just blasted the FASTA AA sequence from the FRAST site entry for Myosin-5 archetype sp Fg (according to Nichola) and got 100% match with https://www.uniprot.org/uniprotkb/I1RCT2/entry
> 
> This is the same UniProt Id that I find by searching uniprot for 'FGSG_01410' as provided by authors. Unfortunately it is in UniParc and may not be possible to use in curation. https://www.uniprot.org/uniprotkb/I1RCT2/entry

@CuzickA, I'm not quite sure how I got the Uniprot id now. Can we talk this through in our next meeting please?

**Comment by CuzickA** [comment]
We discussed this and decided that @jingluodatacurator would add the UniProt id I1RCT2 and transfer the annotations. Please let me know when this is done and I will continue checking the session.

**Comment by jingluodatacurator** [comment]
> We discussed this and decided that @jingluodatacurator would add the UniProt id I1RCT2 and transfer the annotations. Please let me know when this is done and I will continue checking the session.

@CuzickA, I somehow couldn't figure out how to use the trick you mentioned yesterday to mend the curation easily. I meant to ask you on teams earlier about it, sorry.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,
In summary,
1) add new UniProt id
2) go to pathogen genotype management and create genotypes (see note below)
3) go to the phenotype annotation and select edit (or maybe 'transfer' - this one is new to me) and change the genotype from old to new in the dropdown menu.
![image](https://github.com/PHI-base/curation/assets/11753634/9033aae9-e2b8-4111-99a2-834b3a947509)
4) once all changes have been made, any old annotations, genotypes and uniprot ids can be deleted.

Also just to note that the gene name within the genotype above should not be '2021' as this is the pathogen strain. Maybe change it to 'mysosin-5' when you remake the genotypes with the new uniprot id.

**Comment by jingluodatacurator** [comment]
@CuzickA, new genotypes have been created and phenotype annotations have been transferred successfully. Please check thanks.
https://canto.phi-base.org/curs/fc2f904bb33877a5

**Comment by CuzickA** [comment]
Current annotations for review
![image](https://github.com/PHI-base/curation/assets/11753634/fd903273-cab7-4a07-ba04-1e2a64afe9b9)

**Comment by CuzickA** [comment]
I think that the strain should be '2021' (instead of PH-1) which is the wild type phenamacril sensitive strain.

@jingluodatacurator, the reference strain 'PH-1' is used as the UniProt identifier for the overall PHI-base gene results pages. The experimental strain '2021' is included in the genotype information.

I will continue checking this after a meeting this morning.

**Comment by CuzickA** [comment]
The phenamacril-resistant strain YP-1, was generated from phenamacril-sensitive strain PH-1 by phenamacril treatment.

In gene myosin-5 YP-1 had a leucine at codon 217 instead of serine as found in parental strain PHI-1.

Genotype and phenotype annotation would be
Fg strain PH-1 Mysosin-5 (aaS217L) [not assayed] resistance to phenamacril (Table 3)

We may need to add this as a new annotation.

Now added
![image](https://github.com/PHI-base/curation/assets/11753634/b4b3abea-0083-4b30-a590-34f32b432554)

**Comment by CuzickA** [comment]
The phenamacril-resistant strains Y2021A, B, C, D, and F were generated from phenamacril-sensitive strain 2021 by phenamacril treatment.
Mysosin-5 mutations were found by sequence analysis.
Genotype and phenotype annotation would be
Fg strain 2021 Mysosin-5 (aaS217P) [not assayed] resistance to phenamacril (Table 3) **Y2021A**
Fg strain 2021 Mysosin-5 (aaK216E) [not assayed] resistance to phenamacril (Table 3) **Y2021B**
Fg strain 2021 Mysosin-5 (aaE420G, M786V) [not assayed] resistance to phenamacril (Table 3) **Y2021C**
Fg strain 2021 Mysosin-5 (aaS418R, M786V) [not assayed] resistance to phenamacril (Table 3) **Y2021D**
Fg strain 2021 Mysosin-5 (aaS217L, M786V) [not assayed] resistance to phenamacril (Table 3) **Y2021F**

These correspond to current annotations in screenshot above. The strain of the genotype needs to change from PH-1 to 2021.

I have now made these edits
![image](https://github.com/PHI-base/curation/assets/11753634/bbe2a93e-f646-4ae9-8841-fdc5b672cde4)

![image](https://github.com/PHI-base/curation/assets/11753634/c1b67cae-34ca-4d2d-a7e8-d7482fbdc863)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please could you double check the changes that I have made above and see if you agree.

It looks like we could also make 'pathogen only phenotype' annotations (without chemistry) for the resistant strains Y2021B and Y2021F
![image](https://github.com/PHI-base/curation/assets/11753634/66cf7e6d-df87-449f-8227-d29cef63c1e1)
![image](https://github.com/PHI-base/curation/assets/11753634/ecaab228-74ee-437f-8bb0-84537887d448)

There are also some gene replacement expts which would be curated using the allele type 'transformant'. Do you think it is worth curating these?
![image](https://github.com/PHI-base/curation/assets/11753634/e8201ec8-c3a9-4deb-88e1-a8624ce7d5a6)

**Comment by CuzickA** [comment]
I have now deleted the unused genotypes and old UniProt id.

**Next steps for session**
1) @jingluodatacurator to review my edits.
2) @jingluodatacurator shall we add in additional annotations noted above?
3) AC to try and in AE alteration in archetype info. Now DONE below.
4) AC to check AE alteration in archetype with Nichola.

**Comment by CuzickA** [comment]
**AE alteration in archetype**

No information in Nichola's S file or the Mair et al 2016 for Mysosin.

Mysosin-5 is listed in FRAST. Therefore I will need to identify the FASTA file for 
Fg strain PH-1 Mysosin-5 (aaS217L) and look up the corresponding residue position for the alterations at 217  in the resistance strain YP-1.

Maybe also look up the alterations between 2021 and resistant mutants. Assume mysosin-5 sequence is the same for PH-1 and 2021. FGSG_01410 uniprot [I1RCT2](https://www.uniprot.org/uniprotkb/I1RCT2/entry) is from strain PH-1.

Only myosin-5 (FGSG_01410) exhibited point
mutations in all five resistant mutants compared with the
phenamacril-sensitive strain 2021. Nucleotide changes occurred at
positions 216, 217, 418, 420, or 786 in the predicted deduced amino
acid sequence of the myosin-5 gene (Fig. 1a and Table 2).
Phenamacril-sensitive strains PH-1 and 2021 had a lysine at
position 216, a serine at positions 217 and 418, a glutamic acid at
position 420, and a methionine at position 786.

**Comment by CuzickA** [comment]
https://www.ncbi.nlm.nih.gov/nuccore/XM_011318906.1

![image](https://github.com/PHI-base/curation/assets/11753634/7b0e9de7-7771-44a8-b52e-b420d45d626b)

Residue 217 in the sequence index is 'S' which aligns with codon 217 'S' in the Myosin-5 archetype sequence Fg or GIBBZE as documented by Nichola in our draft help file for using this AE.

Myosin-5 (aaS217L)[Not assayed] 'S217L; Myosin-5; GIBBZE'


![image](https://github.com/PHI-base/curation/assets/11753634/5733d8ab-5bec-4bfe-a7e7-5f45a915a631)

**Comment by CuzickA** [comment]
Assume Mysosin-5 sequence for strain 2021 is the same as strain PH-1.

Fg strain 2021 Mysosin-5 (aaS217P) [not assayed] resistance to phenamacril (Table 3) Y2021A
![image](https://github.com/PHI-base/curation/assets/11753634/d2fc2f56-1ffa-4e5c-849b-7144fb5393de)

Residue 217 in the sequence index is 'S' which aligns with codon 217 'S' in the Myosin-5 archetype sequence Fg or GIBBZE. 
Myosin-5 (aaS217P)[Not assayed] 'S217P; Myosin-5; GIBBZE'

![image](https://github.com/PHI-base/curation/assets/11753634/34da0686-444f-4723-916e-c708667fba2d)

**Comment by CuzickA** [comment]
Fg strain 2021 Mysosin-5 (aaK216E) [not assayed] resistance to phenamacril (Table 3) Y2021B

![image](https://github.com/PHI-base/curation/assets/11753634/2a9d744e-97bc-468e-84a0-9034ce880da1)

Residue 216 in the sequence index is 'K' which aligns with codon 216 'K' in the Myosin-5 archetype sequence Fg or GIBBZE.
Myosin-5 (aaK216E)[Not assayed] 'K216E; Myosin-5; GIBBZE'
![image](https://github.com/PHI-base/curation/assets/11753634/3b565163-becf-4fd5-a364-50f3ec93446f)

**Comment by CuzickA** [comment]
Fg strain 2021 Mysosin-5 (aaE420G, M786V) [not assayed] resistance to phenamacril (Table 3) Y2021C

![image](https://github.com/PHI-base/curation/assets/11753634/6de6afd6-6a46-4647-886c-505a6332baed)

Residue 420 in the sequence index is 'E' which aligns with codon 420 'E' in the Myosin-5 archetype sequence Fg or GIBBZE.
Myosin-5 (aaE420G)[Not assayed] 'E420G; Myosin-5; GIBBZE'

![image](https://github.com/PHI-base/curation/assets/11753634/312d52ce-74cb-4055-9c3f-a32b88cf263c)

Residue 786 in the sequence index is 'M' which aligns with codon 786 'M' in the Myosin-5 archetype sequence Fg or GIBBZE.
Myosin-5 (M786V)[Not assayed] 'M786V; Myosin-5; GIBBZE'

Therefore

E420G, M786V; Myosin-5; GIBBZE

![image](https://github.com/PHI-base/curation/assets/11753634/842ac84c-f3ad-4ade-a37e-ecbc850cad04)

**Comment by CuzickA** [comment]
Fg strain 2021 Mysosin-5 (aaS418R, M786V) [not assayed] resistance to phenamacril (Table 3) Y2021D
![image](https://github.com/PHI-base/curation/assets/11753634/b1ee7399-8da9-471b-a139-a95d27eca68d)

Residue 418 in the sequence index is 'S' which aligns with codon 418 'S' in the Myosin-5 archetype sequence Fg or GIBBZE.
Myosin-5 (S418R)[Not assayed] 'S418R; Myosin-5; GIBBZE'

![image](https://github.com/PHI-base/curation/assets/11753634/441d4320-0718-4f2e-a404-2e5036a24c01)

Residue 786 in the sequence index is 'M' which aligns with codon 786 'M' in the Myosin-5 archetype sequence Fg or GIBBZE.
Myosin-5 (M786V)[Not assayed] 'M786V; Myosin-5; GIBBZE'

Therefore

S418R, M786V; Myosin-5; GIBBZE

![image](https://github.com/PHI-base/curation/assets/11753634/ea708473-30bc-40a9-b371-fb063914e1d0)


Fg strain 2021 Mysosin-5 (aaS217L, M786V) [not assayed] resistance to phenamacril (Table 3) Y2021F

Therefore

S217L, M786V; Myosin-5; GIBBZE
![image](https://github.com/PHI-base/curation/assets/11753634/e16c853b-eca7-4e4d-b60c-86dc269685b0)

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, please could you double check the changes that I have made above and see if you agree.
> 
> It looks like we could also make 'pathogen only phenotype' annotations (without chemistry) for the resistant strains Y2021B and Y2021F ![image](https://private-user-images.githubusercontent.com/11753634/289559980-66cf7e6d-df87-449f-8227-d29cef63c1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NTk5ODAtNjZjZjdlNmQtZGY4Ny00NDlmLTgyMjctZDI5Y2VmNjNjMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjc1OTVmOTg3MTUxOGMxZWQyZmQ0YTIzZTFlMDg4MWZkZGUxZTQ3NTI3NTdiMGQzMTQwOWFiMTFjNzQ1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnWhlFVx9R2G8K0sq0WCD5YVgtWbjRRRzy4jocHcuZs) ![image](https://private-user-images.githubusercontent.com/11753634/289560069-ecaab228-74ee-437f-8bb0-84537887d448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NjAwNjktZWNhYWIyMjgtNzRlZS00MzdmLThiYjAtODQ1Mzc4ODdkNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTgxOGM5MTVkZGVkMWU2YzQxYmUzM2VmZTQ3ZDlkY2I1ZTcyNWYzMmUxZGUyYjEzOTVmYzk4OGMxNDlkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdcQNNhb_YyHtjVz7IpUmiCRv8gKQRw9q2cmqC7ByTY)
> 
> There are also some gene replacement expts which would be curated using the allele type 'transformant'. Do you think it is worth curating these? ![image](https://private-user-images.githubusercontent.com/11753634/289560692-e8201ec8-c3a9-4deb-88e1-a8624ce7d5a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NjA2OTItZTgyMDFlYzgtYzNhOS00ZGViLTg4ZTEtYTg2MjRjZTdkNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjI1Nzg1Y2I1NDAyOTk2YTg5NmM3YjllNmIyNTcxYmExMzQ4ZjNkYzkwZDk3MjRiOTViNTczODVhMTBmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQGE59RBlG_5IEQMl6-aHrul_OSboCl0J-nOpUew8-0)

Hi @CuzickA, I'm not sure about the above two additional annotations. We could have a chat about it in our meeting next week please.

**Comment by jingluodatacurator** [comment]
> > Hi @jingluodatacurator, please could you double check the changes that I have made above and see if you agree.
> > It looks like we could also make 'pathogen only phenotype' annotations (without chemistry) for the resistant strains Y2021B and Y2021F ![image](https://private-user-images.githubusercontent.com/11753634/289559980-66cf7e6d-df87-449f-8227-d29cef63c1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NTk5ODAtNjZjZjdlNmQtZGY4Ny00NDlmLTgyMjctZDI5Y2VmNjNjMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjc1OTVmOTg3MTUxOGMxZWQyZmQ0YTIzZTFlMDg4MWZkZGUxZTQ3NTI3NTdiMGQzMTQwOWFiMTFjNzQ1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnWhlFVx9R2G8K0sq0WCD5YVgtWbjRRRzy4jocHcuZs) ![image](https://private-user-images.githubusercontent.com/11753634/289560069-ecaab228-74ee-437f-8bb0-84537887d448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NjAwNjktZWNhYWIyMjgtNzRlZS00MzdmLThiYjAtODQ1Mzc4ODdkNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTgxOGM5MTVkZGVkMWU2YzQxYmUzM2VmZTQ3ZDlkY2I1ZTcyNWYzMmUxZGUyYjEzOTVmYzk4OGMxNDlkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdcQNNhb_YyHtjVz7IpUmiCRv8gKQRw9q2cmqC7ByTY)
> > There are also some gene replacement expts which would be curated using the allele type 'transformant'. Do you think it is worth curating these? ![image](https://private-user-images.githubusercontent.com/11753634/289560692-e8201ec8-c3a9-4deb-88e1-a8624ce7d5a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTE0OTUsIm5iZiI6MTcwMjM5MTE5NSwicGF0aCI6Ii8xMTc1MzYzNC8yODk1NjA2OTItZTgyMDFlYzgtYzNhOS00ZGViLTg4ZTEtYTg2MjRjZTdkNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZjI1Nzg1Y2I1NDAyOTk2YTg5NmM3YjllNmIyNTcxYmExMzQ4ZjNkYzkwZDk3MjRiOTViNTczODVhMTBmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQGE59RBlG_5IEQMl6-aHrul_OSboCl0J-nOpUew8-0)
> 
> Hi @CuzickA, I'm not sure about the above two additional annotations. We could have a chat about it in our meeting next week please.

Hi @CuzickA, I have added pathogen only phenotype annotations, please check.
And we have discussed that transformant genotype annotations are not needed in this publication.

**Comment by CuzickA** [comment]
New annotations
![image](https://github.com/PHI-base/curation/assets/11753634/db77031a-cde1-4b5d-bcd0-05406797ae51)

@jingluodatacurator, was the chemical '+ phenamacril' added in these expts or are these phenotypes observed without the chemical?

**Comment by jingluodatacurator** [comment]
> New annotations ![image](https://private-user-images.githubusercontent.com/11753634/291611390-db77031a-cde1-4b5d-bcd0-05406797ae51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTYxODgsIm5iZiI6MTcwMjk5NTg4OCwicGF0aCI6Ii8xMTc1MzYzNC8yOTE2MTEzOTAtZGI3NzAzMWEtY2RlMS00YjVkLWJjZDAtMDU0MDY3OTdhZTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE0MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2UyMGVhNmU0ZjA4ZTIxYWE2MjNjNzM4NWVmNDQzMzAyMjI4MGJmODFhNzExNTZjZDNjNmQ4N2FhYzlkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mOG0YajaDztoaA7nZAp_T0XCjS_Ey4ZPnLJXSl7D4DI)
> 
> @jingluodatacurator, was the chemical '+ phenamacril' added in these expts or are these phenotypes observed without the chemical?

@CuzickA, these expts were done without the chemical I have double checked, annotations were mended thanks.

**Comment by CuzickA** [comment]
Great thanks @jingluodatacurator, All annotations now look good
![image](https://github.com/PHI-base/curation/assets/11753634/a7e19040-8d71-48b6-939e-29a383b360ec)


**Next steps for session prior to approval**
AC to check AE alteration in archetype with Nichola.

**Comment by CuzickA** [comment]
AE alteration in archetype checked by Nichola. Looks fine.

Approving session and closing ticket.
