### ISSUE TITLE
PMID:29933981 FoMyo5 motor domain substitutions (Val151 to Ala and Ser418 to Thr) cause natural resistance to fungicide phenamacril in Fusarium oxysporum

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#201]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/4f88d97a6049733d

**Comment by jingluodatacurator** [comment]
Notes:

Uniprot id: A0A0J9VL03 (https://www.uniprot.org/uniprotkb/A0A0J9VL03/entry) or W9HIW0 (https://www.uniprot.org/uniprotkb/W9HIW0/entry)? Needs checking.
Strain: Fo32931, Fo47, Fol4287
The main expt for curation: To further test whether the substitutions in FoMyo5 and the lacking 44 amino acids confer resistance to phenamacril, we replaced the FoMyo5 locus between strain Fo32931 and resistant strains Fo47 and Fol4287 by homologous three exchange. First, the FoMyo5 loci of sensitive strain Fo32931 and moderately resistant strain Fol4287 were introduced individually into the low resistant strain Fo47 by gene replacement [17]. Next, the FoMyo5 of the low resistant strain Fo47 was introduced into sensitive strain Fo32931. Briefly, the recipient strains were transformed with the split replacement cassette described in Fig. 4. The gene replacement events were validated in the selected transformants by PCR and sequencing (Table 4). 
The susceptibility of the generated FoMyo5 mutants to phenamacril was assessed based on colony morphology on a series of PDA plates amended with phenamacril at 1, 2, 4, and 8 μg/mL and incubated at 28 °C for 3 days. These results indicated that mutants transformed with a copy of the sensitive fragment exhibited sensitivity, and mutants transformed with a copy of resistant fragments exhibited resistance to phenamacril (Table 4). As shown in Fig. 5, 32,931-47-17, which had been transformed with the FoMyo5 locus of strain Fo32931, could not grow as well as the recipient strain Fo47. In contrast, 32,931-47-15 and 32,931-47-18 were ectopic mutants and showed the similar resistance to Fo47. In addition, 47-32931-4 and Fol4287-47-10, which had been transformed with the FoMyo5 loci of Fo47 and Fol4287 respectively, showed low and moderate resistance to phenamacril (Fig. 5). Our results indicate that the susceptibility levels can be fully accounted for by substitutions in the FoMyo5 gene.

**Comment by jingluodatacurator** [comment]
Completed and pending review.

**Comment by CuzickA** [comment]
Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/8b779b0f-afec-4e28-9867-3ba443f29d96)

First set of edits for creating new PHI-ECO and PHIPO terms
1) add chemical to conditions
![image](https://github.com/PHI-base/curation/assets/11753634/ca2417e2-80c6-47c5-98b4-15a55cfaa1f6)


**AC edit:** I am now deleting this annotation in favour of the annotations below to  the genotypes with 'transformant' allele types.

**Comment by CuzickA** [comment]
I think that the genotypes for the annotations in this publication need to be allele type 'transformant' as genes from different Fo strains (sensitive or resistant to phenamacril) are being replaced within the expts.



![image](https://github.com/PHI-base/curation/assets/11753634/9f9ec804-8076-4198-adc5-2c4703094329)
![image](https://github.com/PHI-base/curation/assets/11753634/cd33c8e3-5792-43ce-b11f-ee60544d7376)

**Comment by CuzickA** [comment]
Wild type strains (not curated) info from Table 4
Fo32931 FoMyo5 sensitive to phenamacril (human pathogenic-strain)
Fo47 FoMyo5 low resistance to phenamacril (plant pathogenic-strain)
Fol4287 FoMyo5 moderate resistance to phenamacril (plant pathogenic-strain)

![image](https://github.com/PHI-base/curation/assets/11753634/d5d58663-88bd-4288-aae2-1d483ca95886)


Next to figure out which UniProt id to use to start creating the transformant genotypes.

**UniProt id**
It is a bit tricky to know which UniProt ID to use. I suggest we use the UniProt id associated with 'Fo32931 FoMyo5 sensitive to phenamacril (human pathogenic-strain)' as the title of the article indicates that mutations in the other strains Fo47 and Fo4287 lead to resistance to phenamacril.

In the text 
![image](https://github.com/PHI-base/curation/assets/11753634/00cfa4c9-c43f-4687-9e8e-cf2a4df8dea9)
 
Looked up 'EWY80136.1' in UniProt and got https://www.uniprot.org/uniprotkb/W9HIW0/entry

Note: the protein name in the UniProt entry is 'Myosin -1' and not 'Myosin 5' as described by the authors. Mysosin 1 and 5 are different members of the myosin superfamily see https://www.mechanobio.info/cytoskeleton-dynamics/what-are-motor-proteins/what-is-myosin/ . Perhaps there is a naming issue in UniProt. We will use this UniProt ID for now as it is linked with the Genbank accession no. reported in the publication.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/2d83ec07-cc70-4f32-95db-ecb27e4d015d)



**47–32,931-4**
recipient strain is 32931, transformed with Myo5 from donor strain 47

Annotation

![image](https://github.com/PHI-base/curation/assets/11753634/3cfe2c39-4ee3-4082-9818-785ddc701b7c)

**Comment by CuzickA** [comment]
**32,931–47-17**
recipient strain is 47, transformed with Myo5 from donor strain 32931

Annotation
![image](https://github.com/PHI-base/curation/assets/11753634/a80c15ac-3751-47b8-96a4-32b78c93c39e)

**Comment by CuzickA** [comment]
**Fol4287–47-10**
recipient strain is 47, transformed with Myo5 from donor strain 4287

Annotation
![image](https://github.com/PHI-base/curation/assets/11753634/f8143320-9e5e-489c-81b3-81eb28169a13)

**Comment by CuzickA** [comment]
Next for this session
1) AC to add new strains '47' and '32931' once full computer access is restored
2) AC to check if I can add AE alteration in archetype information
3) AC to add in new PHIPO and PHI-ECO terms _DONE 22_11_2023_
4) @jingluodatacurator, please look through my comments about about creating 'transformant' allele genotypes for this curation session. There are some further notes about this in the Google file 'Draft Chemistry curation FAQ and tips' under the heading 'How to use the allele type 'transformant'.' We can talk this though when we next meet if you have any queries.

**Comment by CuzickA** [comment]
AE alteration in archetype

No information in Nichola's S file or the Mair et al 2016 for Mysosin.

Mysosin-5 is listed in FRAST. Therefore I will need to identify the FASTA file for FoMyo5 strain 32931, and look up the corresponding residue position for the alterations at 151 and 418 seen in the resistance strain 47.

**Comment by jingluodatacurator** [comment]
> Next for this session
> 
> 1. AC to add new strains '47' and '32931' once full computer access is restored
> 2. AC to check if I can add AE alteration in archetype information
> 3. AC to add in new PHIPO and PHI-ECO terms _DONE 22_11_2023_
> 4. @jingluodatacurator, please look through my comments about about creating 'transformant' allele genotypes for this curation session. There are some further notes about this in the Google file 'Draft Chemistry curation FAQ and tips' under the heading 'How to use the allele type 'transformant'.' We can talk this though when we next meet if you have any queries.

@CuzickA, I can't managed to understand your edits fully, it would be great to talk it through in our meeting next Tuesday thanks.

**Comment by jingluodatacurator** [comment]
> > Next for this session
> > 
> > 1. AC to add new strains '47' and '32931' once full computer access is restored
> > 2. AC to check if I can add AE alteration in archetype information
> > 3. AC to add in new PHIPO and PHI-ECO terms _DONE 22_11_2023_
> > 4. @jingluodatacurator, please look through my comments about about creating 'transformant' allele genotypes for this curation session. There are some further notes about this in the Google file 'Draft Chemistry curation FAQ and tips' under the heading 'How to use the allele type 'transformant'.' We can talk this though when we next meet if you have any queries.
> 
> @CuzickA, I can't managed to understand your edits fully, it would be great to talk it through in our meeting next Tuesday thanks.

@CuzickA, I now have understood you edits after reading through MP's notes on 'How to use the allele type transformant', thanks for the guidance.

**Comment by CuzickA** [comment]
**Next steps for this session**
1) AC to look archetype info using _FRAST_DONE 12_12_2023_
2) AC to add new strains to PHI-Canto _DONE d65e58e strains added 11_12_2023_

**Comment by CuzickA** [comment]
**AE alteration in archetype** 

Using FRAST

Fo32931 FoMyo5 sensitive to phenamacril (human pathogenic-strain)

Looked up EWY80136.1 (from publication, snip above) in Genbank to create FASTA file for FRAST https://www.ncbi.nlm.nih.gov/protein/EWY80136.1

FRAST reference align with Myosin-5 archetype species is Fg see #200 

Myo5 transformant(47-Myo5 (V151A, S418T))[Not assayed]

![image](https://github.com/PHI-base/curation/assets/11753634/6268bf5e-96bc-4e66-a82e-eb9290c61d37)
![image](https://github.com/PHI-base/curation/assets/11753634/faf62851-d1f2-49f5-b398-02243ce03338)

Residue 151 in the sequence index is 'V' which aligns with codon 151 'V' in the Myosin-5 archetype sequence Fg or GIBBZE.
'V151A; Myosin-5; GIBBZE'
Residue 418 in the sequence index is 'S' which aligns with codon 418 'S' in the Myosin-5 archetype sequence Fg or GIBBZE.
'S418T; Myosin-5; GIBBZE'

Therefore,
Myo5 transformant(47-Myo5 (V151A, S418T))[Not assayed] would be ''V151A, S418T; Myosin-5; GIBBZE'

![image](https://github.com/PHI-base/curation/assets/11753634/1150c1b9-444b-4e1c-85be-43363b1d597d)




Myo5 transformant(32931-Myo5 (A151V, T418S))[Not assayed]
I don't this this is applicable for the AE alteration in archetype. In this case the mutant causes a shift from resistance to sensitive to phenamacril.


Myo5 transformant(4287-Myo5 (1-44 partial aa deletion))[Not assayed]
There is a shift from low resistance to increased resistance. I don't know if this partial aa deletion is applicable for the AE alteration in archetype. To check with Nichola.

**?? 'del1-44; Myosin-5; GIBBZE' ?? Not added to the session yet.** **-THIS IS OK, ADD TO SESSION**

(Fo47 FoMyo5 low resistance to phenamacril (plant pathogenic-strain)
Fol4287 FoMyo5 moderate resistance to phenamacril (plant pathogenic-strain)
recipient strain is 47, transformed with Myo5 from donor strain 4287)

**Comment by CuzickA** [comment]
**Next steps for this session**
1) ask Nichola to check AE
2) session then ready for approval

**Comment by CuzickA** [comment]
Nichola checked AEs.

I have added 'del1-44; Myosin-5; GIBBZE'
Myo5 transformant(4287-Myo5 (1-44 partial aa deletion))[Not assayed]
![image](https://github.com/PHI-base/curation/assets/11753634/3afe0b81-e81c-42b7-afce-805d799eb9ca)

**Comment by CuzickA** [comment]
Session approved, closing ticket.

**Comment by CuzickA** [comment]
Confirmation that the 1-44 AA align in Fo Myosin against archetype Fg Myosin

![image](https://github.com/PHI-base/curation/assets/11753634/8cd3ca47-fc4a-4e3f-b11e-fb47e30af295)
![image](https://github.com/PHI-base/curation/assets/11753634/adb62aff-ae22-4647-8df9-53537ecaf705)

**Comment by CuzickA** [comment]
Made edit from 'del' to 'Del' and reapproved

![image](https://github.com/PHI-base/curation/assets/11753634/bd104952-740a-4980-8d02-6b9e8d2aece0)
