### ISSUE TITLE
PMID:11310744 The ABC Transporter BcatrB Affects the Sensitivity of Botrytis cinerea to the Phytoalexin Resveratrol and the Fungicide Fenpiclonil

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#203]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/6a7b64a655a148da

Notes:
Uniprot ID: Q9UW03
Strains: SAS56, B05.10
Main expt. for curation: see Results 'Replacement of BcatrB ' section and Materials and Methods 'Construction of the gene-replacement vector' section.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please could you email me your highlighted PDF

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please could you email me your highlighted PDF

**Comment by CuzickA** [comment]
Uniprot ID looks fine https://www.uniprot.org/uniprotkb?query=Q9UW03
1,439 AA as stated in publication 'BcatrB encodes a 1,439 amino acid protein with homology
to ABC transporters of other fungi'

**Comment by CuzickA** [comment]
Expt Bc strain used was B05.10
 gene replacement mutant = gene deletion
![image](https://github.com/PHI-base/curation/assets/11753634/3c74dc5d-c6f5-47d9-9a0f-a350867cdc19)

**Comment by CuzickA** [comment]
Curation focus is on chemicals mentioned in title/abstract of publication 'Phytoalexin Resveratrol' and 'Fungicide Fenpiclonil'. Other chemicals tested in publication but not annotated at this stage.

Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/156ff717-f693-4cdd-91ed-3e230925ebfd)

Small edits 
1) Change Figure 4 to Table 3
2) Add in a comment, relevant copy and pasted text from the publication

![image](https://github.com/PHI-base/curation/assets/11753634/ecdb4a12-94ae-4323-8334-034049ec561c)

@jingluodatacurator, please have a look at these small edits to see if you agree.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, with your new knowledge of how to make pathogen-host interaction (PHI) phenotype annotations, please could you have a go at curating the virulence assays in this publication

From Results section
![image](https://github.com/PHI-base/curation/assets/11753634/ef5be423-68d3-4533-a56a-7041193829a3)
![image](https://github.com/PHI-base/curation/assets/11753634/aae5f8bb-90c2-491c-9128-f0096fdd675b)

From Materials and Methods section
![image](https://github.com/PHI-base/curation/assets/11753634/5fbc07ea-f8ed-4686-a550-813dcc11c3ab)
![image](https://github.com/PHI-base/curation/assets/11753634/9afaafaa-c36c-4b15-b2ff-ed83fd1a11f0)

**Comment by CuzickA** [comment]
Note to self

Next steps for this session
1) needs new PHIPO and PHI-ECO terms _DONE 22_11_2023_
2) Jing to add in PHI phenotypes, AC to check them.
3) AE alteration in archetype is N/A as NTSR
4) Once 1) and 2) have been completed then the session will be ready to approve.

**Comment by CuzickA** [comment]
Also added a GO MF annotation
![image](https://github.com/PHI-base/curation/assets/11753634/745e6ded-b072-46d3-9e47-b68ea76a4a16)

**Comment by jingluodatacurator** [comment]
> Curation focus is on chemicals mentioned in title/abstract of publication 'Phytoalexin Resveratrol' and 'Fungicide Fenpiclonil'. Other chemicals tested in publication but not annotated at this stage.
> 
> Current annotation ![image](https://user-images.githubusercontent.com/11753634/284532235-156ff717-f693-4cdd-91ed-3e230925ebfd.png)
> 
> Small edits
> 
> 1. Change Figure 4 to Table 3
> 2. Add in a comment, relevant copy and pasted text from the publication
> 
> ![image](https://user-images.githubusercontent.com/11753634/284534681-ecdb4a12-94ae-4323-8334-034049ec561c.png)
> 
> @jingluodatacurator, please have a look at these small edits to see if you agree.

@CuzickA, I agree with your edits thanks.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, with your new knowledge of how to make pathogen-host interaction (PHI) phenotype annotations, please could you have a go at curating the virulence assays in this publication
> 
> From Results section ![image](https://user-images.githubusercontent.com/11753634/284536421-ef5be423-68d3-4533-a56a-7041193829a3.png) ![image](https://user-images.githubusercontent.com/11753634/284536576-aae5f8bb-90c2-491c-9128-f0096fdd675b.png)
> 
> From Materials and Methods section ![image](https://user-images.githubusercontent.com/11753634/284536803-5fbc07ea-f8ed-4686-a550-813dcc11c3ab.png) ![image](https://user-images.githubusercontent.com/11753634/284536944-9afaafaa-c36c-4b15-b2ff-ed83fd1a11f0.png)

@CuzickA, I had a go adding PHI phenotype, please check. I have a feeling I have missed something..

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, this is a good start on the PHI phenotype

![image](https://github.com/PHI-base/curation/assets/11753634/62049822-97df-41de-b321-5fa268bb9377)

Here is some feedback so you can go back to the session and make some changes
1) We need the wild type control metagenotype as discussed before in recent tickets. This would be wild type B. cinerea atrB on wild type V. vinifera. The AEs can then be updated for 'compared to control' and 'infective ability'.
2) The host strain will not be the same as the pathogen strain (in this case B05.10). If the authors have not mentioned the strain/cultivar of the grapevine then you can use strain 'unknown'.
3) I would annotate with a PHIPO term for 'lesions' as described by the authors in Table 4.
4) The evidence code 'cell growth assay' is only really used for pathogen only expt eg where a pathogen is grown in vitro on an agar plate. I think this needs changing.
5) For the conditions we do not need the 'B5 medium' as this was how the pathogen was prepared. We only want to use one time point per annotation. Choose the time point that the authors describe or which shows the biggest change in phenotype. If different phenotypes are shown at different time points then we can make additional annotations.


Please let me know how you get on and if you have any questions.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, this is a good start on the PHI phenotype
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/286201978-62049822-97df-41de-b321-5fa268bb9377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzc5ODksIm5iZiI6MTcwMTE3NzY4OSwicGF0aCI6Ii8xMTc1MzYzNC8yODYyMDE5NzgtNjIwNDk4MjItOTdkZi00MWRlLWIzMjEtNWZhMjY4YmI5Mzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEzMjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNTg2YzI1YzFjODk0YmJhZDQyMWNhYTYxODEyYzY0MzBkYTUxM2Y0YTk2ODA4MTc0OTcyY2VjZmViNjRmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lpdM0har2WSXQ_PiAJjXEXuAiFMpTggFLsFdEzs2qKk)
> 
> Here is some feedback so you can go back to the session and make some changes
> 
> 1. We need the wild type control metagenotype as discussed before in recent tickets. This would be wild type B. cinerea atrB on wild type V. vinifera. The AEs can then be updated for 'compared to control' and 'infective ability'.
> 2. The host strain will not be the same as the pathogen strain (in this case B05.10). If the authors have not mentioned the strain/cultivar of the grapevine then you can use strain 'unknown'.
> 3. I would annotate with a PHIPO term for 'lesions' as described by the authors in Table 4.
> 4. The evidence code 'cell growth assay' is only really used for pathogen only expt eg where a pathogen is grown in vitro on an agar plate. I think this needs changing.
> 5. For the conditions we do not need the 'B5 medium' as this was how the pathogen was prepared. We only want to use one time point per annotation. Choose the time point that the authors describe or which shows the biggest change in phenotype. If different phenotypes are shown at different time points then we can make additional annotations.
> 
> Please let me know how you get on and if you have any questions.

@CuzickA, all points taken and actioned with your help, many thanks.

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/d42e9d57-8014-4086-8cc4-bf1ac4e2a94d)

Session now approved, closing ticket.
