### ISSUE TITLE
PMID:17107817 MgMfs1, a major facilitator superfamily transporter from the fungal  wheat pathogen Mycosphaerella graminicola, is a strong protectant  against natural toxic compounds and fungicides

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#204]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/49a9994d2b20ee03

Notes:
Uniprot ID: F9XG71
Strains: IPO323
Main expt. for curation: see Materials and Methods 2.4 & 2.5, and Results 3.3.

**Comment by CuzickA** [comment]
Checking UniProt - looks fine
_'The nucleotide sequence of MgMfs1 is available at GenBank with Accession No. DQ6619111.'_

Nothing found in UniProt or Genbank when search for 'DQ6619111'

search UniProt for 'MgMfs1' gives three entries. The entry for Zt reference IPO323 has correctly been selected  https://www.uniprot.org/uniprotkb/F9XG71/entry
![image](https://github.com/PHI-base/curation/assets/11753634/33211e1a-fd98-44ef-917a-5536b417cebf)

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/437ffe6c-fc3e-477a-9ebd-b2f665e47752)

**Comment by CuzickA** [comment]
Feedback for @jingluodatacurator 
1) Please change the genotype to MgMfs1::Hyg cassette (disruption) to be consistent with disruption genotype naming as discussed previously in ticket https://github.com/PHI-base/curation/issues/202
2) Update the phenotypes - I think these should both be 'sensitive to'
![image](https://github.com/PHI-base/curation/assets/11753634/744701d8-00ec-4253-a542-6a2f810c8e85)
![image](https://github.com/PHI-base/curation/assets/11753634/0ca3fda8-0764-4937-8006-a4f133547f81)

![image](https://github.com/PHI-base/curation/assets/11753634/f69c5207-8b5a-48fe-bb6c-c240a017e977)


3) As discussed in https://github.com/PHI-base/curation/issues/207 Please check and update the conditions so that they contain the chemical and the conditions used within the phenotype expt rather than the generation of the mutations. 
![image](https://github.com/PHI-base/curation/assets/11753634/635af079-6237-440e-9e0c-2104eda038d9)
![image](https://github.com/PHI-base/curation/assets/11753634/52280ac9-67b0-4439-8686-980eb3ee6c70)

4) I think PHI phenotype annotations could be made please
![image](https://github.com/PHI-base/curation/assets/11753634/0dfd6427-0c5d-4d76-a10e-1f08542b16e8)
![image](https://github.com/PHI-base/curation/assets/11753634/f5f401da-10e4-461a-9503-e9063f03cfc3)
![image](https://github.com/PHI-base/curation/assets/11753634/60e691fe-7315-4ecf-b3cc-313de0809632)
![image](https://github.com/PHI-base/curation/assets/11753634/eb102eaa-6b76-4004-9be5-4ff0869b42e1)

Thanks @jingluodatacurator, please let me know how you get on and if you have any queries.

**Comment by CuzickA** [comment]
I think that adding the AE alteration in archetype is N/A as NTSR, MFS transporter.

**Comment by jingluodatacurator** [comment]
> Feedback for @jingluodatacurator
> 
> 1. Please change the genotype to MgMfs1::Hyg cassette (disruption) to be consistent with disruption genotype naming as discussed previously in ticket [PMID:17379549 MgAtr7, a new type of ABC transporter from Mycosphaerella  graminicola involved in iron homeostasis #202](https://github.com/PHI-base/curation/issues/202)
> 2. Update the phenotypes - I think these should both be 'sensitive to'
>    ![image](https://private-user-images.githubusercontent.com/11753634/298061350-744701d8-00ec-4253-a542-6a2f810c8e85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwNjEzNTAtNzQ0NzAxZDgtMDBlYy00MjUzLWE1NDItNmEyZjgxMGM4ZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OGRhYTQ2MDMzODlkNGNjZTU2ZWQ5ZTY3ZGY4ZDZhNjAzNWFkYzRlNzlkZDAzZDk4NDNkZGMxNzBjZGRjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxP39ZXk8PUNdL5sE4RYVfwmSU9lmT0WnF_T84bWb2w)
>    ![image](https://private-user-images.githubusercontent.com/11753634/298061531-0ca3fda8-0764-4937-8006-a4f133547f81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwNjE1MzEtMGNhM2ZkYTgtMDc2NC00OTM3LTgwMDYtYTRmMTMzNTQ3ZjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMGMwMTY0M2UwMDVmNWJkNTY4NWU3OGZkNTczNmNhMDczNjVkMDMzODkyNTE1OWUwODQyZDRjYTA0MzYwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zhYNZL4fp5CO5sfU4r817ImLqGh2xXAvYALRLW7I2Pg)
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/298091359-f69c5207-8b5a-48fe-bb6c-c240a017e977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwOTEzNTktZjY5YzUyMDctOGI1YS00OGZlLWJiNmMtYzI0MGEwMTdlOTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0M2NjNWE4ZmU5N2VkYWM0Mjg3OTQ4MzVkNTU2NmRjYWNmMGY5OTRlODRiNjc3ZjI5NzExMmM0YjRlZjBlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHFewDzr_NEhtWnfck7Xccup5X_gKH06Iwr66OwdA2I)
> 
> 3. As discussed in [PMID:21933337 Risk assessment studies on succinate dehydrogenase inhibitors, the new weapons in the battle to control Septoria leaf blotch in wheat #207](https://github.com/PHI-base/curation/issues/207) Please check and update the conditions so that they contain the chemical and the conditions used within the phenotype expt rather than the generation of the mutations.
>    ![image](https://private-user-images.githubusercontent.com/11753634/298062931-635af079-6237-440e-9e0c-2104eda038d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwNjI5MzEtNjM1YWYwNzktNjIzNy00NDBlLTllMGMtMjEwNGVkYTAzOGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDIwMjZhNzkzY2E5MTQ5ZWFjY2E4YjQyZGQ4MDQ2NzgwNDYyM2Q1YWJkMWNmNTNiMzlhNDdmOTlmNTRhOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.09KI8TaeELnbFOEQWRYgBWXyIJ_mBiP9OzwKJOcTuCQ)
>    ![image](https://private-user-images.githubusercontent.com/11753634/298063000-52280ac9-67b0-4439-8686-980eb3ee6c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwNjMwMDAtNTIyODBhYzktNjdiMC00NDM5LTg2ODYtOTgwZWIzZWU2YzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMmFhMDllZTQyN2U1YWU2NDdhYWIxZjFjNjllZGJlN2EzZjgwN2E0MDIzNGFlY2Q5NmViMjBkZjlkMjA2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZxCdfJfU8MA0tJ5-UgzvS6mYSwe-gyPv31YAHrcC_bs)
> 4. I think PHI phenotype annotations could be made please
>    ![image](https://private-user-images.githubusercontent.com/11753634/298090071-0dfd6427-0c5d-4d76-a10e-1f08542b16e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwOTAwNzEtMGRmZDY0MjctMGM1ZC00ZDc2LWExMGUtMWYwODU0MmIxNmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiM2Q3YzU2Nzg4NWMyNDQ4Y2ZhZTAyZjM2ZjhjMjk4YTlhZTk0ZjNhYjI4YzRlY2FmYjY2YjMyMGNkYTI3YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2qxF2km8HiCfPTd-JcOidotYrNVHV_iAWrI4KZ9KNO4)
>    ![image](https://private-user-images.githubusercontent.com/11753634/298090188-f5f401da-10e4-461a-9503-e9063f03cfc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwOTAxODgtZjVmNDAxZGEtMTBlNC00NjFhLTk1MDMtZTkwNjNmMDNjZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMGY3MDZhNjExMjM4ZjY1MTI4YjMxNWNhYzljYzBhNTg3Y2MzZDYzODY4OGJkYWViMDhlNzcxMjIyZTg5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2VCUdei_xVuAHAxMNxfs8yDSWlWUYwch_BkzoIWwni0)
>    ![image](https://private-user-images.githubusercontent.com/11753634/298090304-60e691fe-7315-4ecf-b3cc-313de0809632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwOTAzMDQtNjBlNjkxZmUtNzMxNS00ZWNmLWIzY2MtMzEzZGUwODA5NjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2M2E4OWRmODUyNzhkOTFhYzBlOWUzMjhjMWViMjNkYWYwMzAwOGQ5OGE2NjYyNTJkNTM1M2I4OTYwYzhkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t13FRy04zDZYrKhNXWtm-FKLPPXg_gueu6IyqWzgXcM)
>    ![image](https://private-user-images.githubusercontent.com/11753634/298090490-eb102eaa-6b76-4004-9be5-4ff0869b42e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzc4NzQsIm5iZiI6MTcwNjEzNzU3NCwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwOTA0OTAtZWIxMDJlYWEtNmI3Ni00MDA0LTliZTUtNGZmMDg2OWI0MmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNWJkYzI5ZDBlYjdiYWFlNTJhYjNjMDUwOTYwNWJiNmZlZmU2Mzg1MzBkNWMzMWExN2E1ZTU3OGFiYjA1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyfJACCeKb6UPeneUsji0WJoayPZIzg-lZUIOIh0tvk)
> 
> Thanks @jingluodatacurator, please let me know how you get on and if you have any queries.

Hi @CuzickA, I have made the updates as below:

1. changed the genotype to MgMfs1::Hyg cassette (disruption) to be consistent with disruption genotype naming.
2. updated the phenotypes of mutants to be 'sensitive to'.
3. updated conditions and figures according to experiments.
4. PHI phenotype annotations have been created.

Please check them and let me know any corrections to be made or further actions to be done, thanks.

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I have a question regarding the expression of mutant genotype. According to the text in text page 385, section 3.6. Expression of MgMfs1 in disruptants (again, I tried snip tool to copy and paste image of the text but it didn't work. I have contacted James to help me solving this hopefully soon!). Would the expression level be Not assayed or Knockdown in this case? Thanks.

**Comment by CuzickA** [comment]
> Hi @CuzickA, I have a question regarding the expression of mutant genotype. According to the text in text page 385, section 3.6. Expression of MgMfs1 in disruptants (again, I tried snip tool to copy and paste image of the text but it didn't work. I have contacted James to help me solving this hopefully soon!). Would the expression level be Not assayed or Knockdown in this case? Thanks.

Hi @jingluodatacurator, good spot. Yes, I think you use expression level knockdown.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,
Feedback on 1. The disruption genotype is very close but still not quite right.
In the example in #202 it looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/dabddf0e-a1c5-409f-98e1-3ab95efda5ed)
![image](https://github.com/PHI-base/curation/assets/11753634/1974f5c9-0d80-49e2-9439-dd330c33cb08)


We currently have 
![image](https://github.com/PHI-base/curation/assets/11753634/bae8ed36-8518-4608-a0b9-278ac4d0c183)

The extra information that has been added to the description needs to be added into the gene name section please
![image](https://github.com/PHI-base/curation/assets/11753634/8d206222-03df-4462-b22d-49c7411fa3e7)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, 
Feedback on 2 and 3
![image](https://github.com/PHI-base/curation/assets/11753634/784325af-9616-4859-bbb4-318329775577)
2. sensitive to... phenotype annotations look good. 
We do not curate the wild type controls for the pathogen only phenotype annotations, we only curate them for the pathogen host interaction (metagenotypes) phenotypes. We have a note of this from Maiara, in the Google FAQ document 'Draft Chemistry curation FAQ and tips' under 'Information not to curate in PHI-Canto for Chemistry curation' 'Pathogen phenotype controls.'

3. conditions and figures look good

**Comment by CuzickA** [comment]
Hi @jingluodatacurator,
Feedback on 5

PHI phenotypes look pretty good. Just a few things to change please
a) the AEs have been added to the Wild type control metagenotype instead of the pathogen mutant metagenotype.

b) The condition 'rich media' is not really used for PHI phenotypes it really applies more to the pathogen only phenotypes. Instead the condition 'delivery mechanism: pathogen inoculation' would be better here.

![image](https://github.com/PHI-base/curation/assets/11753634/f5f8d131-622a-4424-9ef3-ccabec5b8340)

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, our internet has been really slow this morning, but all points above have been updated and corrected. Please check thanks.
https://canto.phi-base.org/curs/49a9994d2b20ee03

**Comment by CuzickA** [comment]
1 and 2. Looks good

![image](https://github.com/PHI-base/curation/assets/11753634/bcedd15e-0482-4769-8558-621cf545fea5)

**Comment by CuzickA** [comment]
5. looks good

![image](https://github.com/PHI-base/curation/assets/11753634/ea0a5d9a-20ab-4405-8c03-b288c9125f6d)

**Comment by CuzickA** [comment]
I think that adding the AE alteration in archetype is N/A as NTSR, MFS transporter.

Session now approved.

Closing ticket.
