### ISSUE TITLE
PMID:12821484 Nonsense Mutations in the lsa-Like Gene in Enterococcus faecalis Isolates Susceptible to Lincosamides and Streptogramins A

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#205]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/144c8f8625c95e5e

Uniprot ID: Q7WT47
Strains: V583, ATCC29212
Main expt. for curaion: see section 'Selection of revertant mutants' and Table 1

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please could you email me your highlighted PDF of this paper so that I can check the session. Thanks.

**Comment by CuzickA** [comment]
Checking UniProt id - looks fine
Text 
![image](https://github.com/PHI-base/curation/assets/11753634/3e2c3baa-84e9-4b50-a38c-9c037902d8c5)

Search UniProt for AY225127 gives https://www.uniprot.org/uniprotkb/Q7WT47/entry

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/6a6afbd3-6d92-4873-95bd-3c09b28aed98)

**Comment by CuzickA** [comment]
**Expt information**

**Some background info** 
__'The lsa gene confers intrinsic resistance to lincosamides and streptogramins A in Enterococcus faecalis,
probably by active efflux.'_

_'The lsa-like genes of two clinical isolates of E. faecalis susceptible to lincosamides and
dalfopristin contained mutations that produced premature termination codons.'__ These isolates were called UCN32 and UCN33.

The lsa gene was sequenced in the two susceptible isolates UCN32 and UCN33 and sequence was compared to two intrinsically resistant isolates V583 and ATCC 29212 (reference). This is what was found...


_'In E. faecalis UCN32,
in addition to a few substitutions, deletion of an adenine was
detected at position 618 (base relative to ATG), which generated
a stop codon four nucleotides downstream. In E. faecalis
UCN33, a G-T mutation at position 987 produced a stop
codon.'_ 

Note: this on its own can't be curated as it is just comparing isolates without an element of 'lab-engineering' to give us a clear control wt/parental strain for comparison. However, the following revertant expt can be curated.

**Expt for curation**

_'Revertant mutants were
obtained by selection on agar plates containing clindamycin.'_

_'Selection of revertant mutants. Approximately 108 cells of
E. faecalis UCN32 and E. faecalis UCN33 were spread onto
brain heart infusion agar plates containing 20 g of clindamycin/
ml and were incubated for 24 h at 37°C. Resistant mutants
were obtained at frequencies approximately equal to 106.
Three mutants derived from each parental strain were selected
and were further studied. All displayed an LSA phenotype
(coresistance to clindamycin, lincomycin, and dalfopristin)
(Table 1). lsa sequence analysis in the three mutants,
UCN32-1, UCN32-2, and UCN32-3, derived from E. faecalis
UCN32 showed an insertion of an adenine in place of the
deletion in the parent strain, which restored a sequence iden-tical to that of E. faecalis V583. In the mutants from E. faecalis
UCN33, the stop codon (TAA) was changed to a glutamic acid
codon (GAA) in mutant UCN33-1 or to a glutamine codon
(CAA) in mutants UCN33-2 and UCN33-3. There were no
differences between the MICs of lincosamides and dalfopristin
for mutants (Table 1).'_

**Comment by CuzickA** [comment]
**Parental strain UCN32 susceptible clinical isolate**
**Revertant mutants UCN32-1, UCN32-2, and UCN32-3** all _'showed an insertion of an adenine in place of the
deletion in the parent strain, which restored a sequence identical to that of E. faecalis V583.'_
Therefore genotype would be
1) E. faecalis (strain UCN32) nucleotide insertion of adenine (A) at 618 (was deleted in parent UCN32, now inserted in revertant mutant)
phenotype would be shift of susceptible to **resistant**


**Parental strain UCN33 susceptible clinical isolate**
**Revertant mutant UCN33-1** _'the stop codon (TAA) was changed to a glutamic acid codon (GAA) in mutant UCN33-1'_ _'In E. faecalis UCN33, a G-T mutation at position 987 produced a stop codon.'_ Therefore in parent UCN33 thymine (T) was present at 987 and changed to guanine (G) in the revertant.
**Revertant mutants UCN32-2, and UCN32-3** _'or to a glutamine codon (CAA) in mutants UCN33-2 and UCN33-3.'_ Therefore in parent UCN33 thymine (T) was present at 987 and changed to cytosine (C) in the revertants.
Therefore genotypes would be

2) E. faecalis (strain UCN33) nucleotide substitution of thymine (T) at 987 for guanine (G) 
3) E. faecalis (strain UCN33) nucleotide substitution of thymine (T) at 987 for cytosine (C)

phenotypes would be shift of susceptible to **resistant**

**Comment by CuzickA** [comment]
**Next steps**
1) @jingluodatacurator, please could you read through my notes on my understanding of the expt in this paper and see you agree.
2) @jingluodatacurator, the genotypes will need remaking please. Note that in this case the paper reports on 'nucleotide' changes rather than 'amino acid' changes.
3) AC I think that adding the AE alteration in archetype is N/A as NTSR,  the authors state 'The Lsa protein shows similarities
to members of a superfamily of transport-related proteins known as **ABC transporters**.' and 'The lsa gene confers intrinsic resistance to lincosamides and streptogramins A in Enterococcus faecalis, probably by **active efflux.'**

**Comment by CuzickA** [comment]
Note to self: I might need to add new strains to PHI-Canto.

**Comment by jingluodatacurator** [comment]
> **Next steps**
> 
> 1. @jingluodatacurator, please could you read through my notes on my understanding of the expt in this paper and see you agree.
> 2. @jingluodatacurator, the genotypes will need remaking please. Note that in this case the paper reports on 'nucleotide' changes rather than 'amino acid' changes.
> 3. AC I think that adding the AE alteration in archetype is N/A as NTSR,  the authors state 'The Lsa protein shows similarities
>    to members of a superfamily of transport-related proteins known as **ABC transporters**.' and 'The lsa gene confers intrinsic resistance to lincosamides and streptogramins A in Enterococcus faecalis, probably by **active efflux.'**

Hi @CuzickA, can we discuss points 1 & 2 in our meeting tomorrow for some further guidance please thanks.

**Comment by jingluodatacurator** [comment]
> **Next steps**
> 
> 1. @jingluodatacurator, please could you read through my notes on my understanding of the expt in this paper and see you agree.
> 2. @jingluodatacurator, the genotypes will need remaking please. Note that in this case the paper reports on 'nucleotide' changes rather than 'amino acid' changes.
> 3. AC I think that adding the AE alteration in archetype is N/A as NTSR,  the authors state 'The Lsa protein shows similarities
>    to members of a superfamily of transport-related proteins known as **ABC transporters**.' and 'The lsa gene confers intrinsic resistance to lincosamides and streptogramins A in Enterococcus faecalis, probably by **active efflux.'**

Hi @CuzickA, thanks for the feedback. I have gone through the paper again and summarized key steps of expt., and agree with your notes above. I have amended the genotypes. Please let me know any further actions thanks.

**Comment by CuzickA** [comment]
Copy of updated annotations for checking
![image](https://github.com/PHI-base/curation/assets/11753634/38f6503e-a1c6-42f9-a599-6f68fde6670e)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, In your updated annotation, I don't see the 3 genotypes described in my comment above. Please could you check? Thanks

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, In your updated annotation, I don't see the 3 genotypes described in my comment above. Please could you check? Thanks

Hi @CuzickA, I have double checked, in the updated curation above, one genotype is nucleotide insertion lsa(618-A) and the other two genotypes are nucleotide substitutions lsa(ntT987G, T987C). Maybe I have misunderstood something here? I'd like to talk it through in our meeting tomorrow please.

**Comment by CuzickA** [comment]
> > Hi @jingluodatacurator, In your updated annotation, I don't see the 3 genotypes described in my comment above. Please could you check? Thanks
> 
> Hi @CuzickA, I have double checked, in the updated curation above, one genotype is nucleotide insertion lsa(618-A) and the other two genotypes are nucleotide substitutions lsa(ntT987G, T987C). Maybe I have misunderstood something here? I'd like to talk it through in our meeting tomorrow please.

Hi @jingluodatacurator, '_two genotypes are nucleotide substitutions lsa(ntT987G, T987C)_' 
This should be **two separate genotypes**, **currently it is one genotype** with the nt at the same position 987 changing from T to either G or C.

Also the genotype strains need changing as outlined in the 3 suggested genotypes described in the comment above.

**Comment by jingluodatacurator** [comment]
> > > Hi @jingluodatacurator, In your updated annotation, I don't see the 3 genotypes described in my comment above. Please could you check? Thanks
> > 
> > 
> > Hi @CuzickA, I have double checked, in the updated curation above, one genotype is nucleotide insertion lsa(618-A) and the other two genotypes are nucleotide substitutions lsa(ntT987G, T987C). Maybe I have misunderstood something here? I'd like to talk it through in our meeting tomorrow please.
> 
> Hi @jingluodatacurator, '_two genotypes are nucleotide substitutions lsa(ntT987G, T987C)_' This should be **two separate genotypes**, **currently it is one genotype** with the nt at the same position 987 changing from T to either G or C.
> 
> Also the genotype strains need changing as outlined in the 3 suggested genotypes described in the comment above.

Hi @CuzickA, I have updated genotypes as well as genotype strains. Please check thanks.

https://canto.phi-base.org/curs/144c8f8625c95e5e

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/b2c4cb72-146e-4e43-90c0-51d88a97e2a2)

Looks good @jingluodatacurator

**Comment by CuzickA** [comment]
**Next steps**
1) AC to add new strains 'UCN32' and 'UCN33' to Enterococcus faecalis strain list DONE 31_01_2024 b97a12e
2) Alteration in archetype N/A as NTSR

**Comment by CuzickA** [comment]
Session approved, closing ticket.

**Comment by CuzickA** [comment]
This is a bacterial species and not a fungal species - also see https://github.com/PHI-base/curation/issues/159

Note: this paper was identified for curation by MP.
