### ISSUE TITLE
PMID:30727143 Baseline Sensitivity of Monilinia fructicola from China to the DMI Fungicide  SYP-Z048 and Analysis of DMI-Resistant Mutants 

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#206]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/374b149aa1776aac (this session will need to be deleted)

Link with correct PMID https://canto.phi-base.org/curs/93b1e80c305cc8da

Uniprot No.:D0VVD6
Strains: MBJA8, MSB11, MPA18
Main expt. for curation: see in Materials and Methods 'Generation of SYP-Z048-resistant mutants' section.

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, the paper doesn't allow editing unfortunately.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I'm looking to see if there is an alternative name for 'SYP-Z048   (5-(4-chlorophenyl)-2,3-di-methyl-3-(pyridine-3)-oxazoline)  '

It looks like 'pyrisoxazole' could be a synonym
![image](https://github.com/PHI-base/curation/assets/11753634/e733880d-760f-4b7b-badc-411de4cfdcf4)

![image](https://github.com/PHI-base/curation/assets/11753634/b36c94f3-aeea-452a-9c32-2497a88c57f1)

Do you agree that this chemical is 'pyrisoxazole'?

(Note: pyrisoxazole is on the FRAC list and already added to our anti-infective list).

**Comment by CuzickA** [comment]
**Mutant generation by UV irradiation.**
'Mutants of M. fructicola were not selected spontaneously in the laboratory on YGA medium amended with SYP-Z048 in this study. The fungus had to be exposed to UV irradiation in order to gener-ate  SYP-Z048-resistant  mutants.  '

It is not clear to me from the paper which parental strains generated which UV mutants. I think we will have to choose a representative wild type S strain and a R mutant. Several S and R strains had Y136F respectively so hopefully this will rule out complications of any other UV mutations in the background outside of the Cyp51 target.

**Comment by CuzickA** [comment]
Current annotation
![image](https://github.com/PHI-base/curation/assets/11753634/5215fc41-c9b7-4416-af68-f924c4032d9d)

I think we need to change the strain here to 'MPA18 ' to represent the S wildtype isolate in Table 4. For some reason strain 'MBJA8' is not mentioned in Table 4, just in earlier Tables.
![image](https://github.com/PHI-base/curation/assets/11753634/04370e69-9988-4092-90ce-db9aacb83495)

@jingluodatacurator, please could you read my comments above and see if you agree. If you do, please could you add the strain 'MPA18' instead of 'MBJA8'

**Comment by CuzickA** [comment]
**Added AE alteration_in_archetype**

M. fructicola CYP51(aaY136F)[Not assayed]

Y137F; Cyp51 (Cyp51B); SEPTTR

Straight forward to find in Nichola's S file in Table S2

![image](https://github.com/PHI-base/curation/assets/11753634/a4e640c2-ba03-460c-88cd-3a0fe3a156bf)
![image](https://github.com/PHI-base/curation/assets/11753634/8e71aa17-1d90-40c8-a7b2-82af546f3cf3)

**Comment by CuzickA** [comment]
**Next steps**
1) @jingluodatacurator to check AC's notes on chemical name. _now DONE and agreed_
2) @jingluodatacurator to check AC's comments and change strain name if in agreement. _DONE 12_12_2023_
3) AC to add new PHIPO and PHI-ECO terms. _now DONE 05_12_2023_
4) AC to check final edits (points 1-3). DONE 12_12_2023
5) AC to check AE alteration in archetype with Nichola.
6) @jingluodatacurator recreate the session using the correct PMID (see comment below 12_12_2023). DONE 12_12_2023

Then session will be ready for approval.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, I'm looking to see if there is an alternative name for 'SYP-Z048 (5-(4-chlorophenyl)-2,3-di-methyl-3-(pyridine-3)-oxazoline) '
> 
> It looks like 'pyrisoxazole' could be a synonym ![image](https://private-user-images.githubusercontent.com/11753634/287696141-e733880d-760f-4b7b-badc-411de4cfdcf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDYwMTgsIm5iZiI6MTcwMjA0NTcxOCwicGF0aCI6Ii8xMTc1MzYzNC8yODc2OTYxNDEtZTczMzg4MGQtNzYwZi00YjdiLWJhZGMtNDExZGU0Y2ZkY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE0MjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZDVhNDJiYTA2N2I4NWZkMjU5NGE4NzM4ZTJiMzc4OThiNjY0MTExZDI0NjZlMzY3NzljNGRiMjY2N2M0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gQGQtosG2TaombXCuYT1x5xndEq6rE5fNqF21rbar2k)
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/287696348-b36c94f3-aeea-452a-9c32-2497a88c57f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDYwMTgsIm5iZiI6MTcwMjA0NTcxOCwicGF0aCI6Ii8xMTc1MzYzNC8yODc2OTYzNDgtYjM2Yzk0ZjMtYWVlYS00NTJhLTljMzItMjQ5N2E4OGM1N2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE0MjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwOTQwNzE2ZmZkZjFlZDg1ODRmOTg2ZDJkMmUyMWU2MGNjOWJiMTFjNTdkZGJlYWViNWYwNzc3MzQ0OGU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_aelRh8aRQT2PhqllptI3iRtVesTrVqCf5IiLMkOy4)
> 
> Do you agree that this chemical is 'pyrisoxazole'?
> 
> (Note: pyrisoxazole is on the FRAC list and already added to our anti-infective list).

@CuzickA, yes it looks correct to me.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, I have just noticed that the PMID and title entered here for curation does not match the title of the paper that we are curating.



![image](https://github.com/PHI-base/curation/assets/11753634/6b684b3f-6dd4-4b13-ae72-10081037ccb3)

I have just looked up the correct PMID for this article and it is PMID: 30727143 not PMID:30717143.

Please could you start a new curation session with the correct PMID and enter the curated information. Unfortunately there is no shortcut for this but at least there is only one annotation :-). (Once this is done, I will then ask James to delete the incorrect PMID:30717143 session from PHI-Canto.)


![image](https://github.com/PHI-base/curation/assets/11753634/49fafe72-95f2-49f0-a951-4a8288f0657f)


Here is the UniProt D0VVD6 and if you agree with my comments above you can amend the strain in the genotype from 'MBJA8' to 'MPA18'.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, I have just noticed that the PMID and title entered here for curation does not match the title of the paper that we are curating.
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/289823224-6b684b3f-6dd4-4b13-ae72-10081037ccb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzk2NzAsIm5iZiI6MTcwMjM3OTM3MCwicGF0aCI6Ii8xMTc1MzYzNC8yODk4MjMyMjQtNmI2ODRiM2YtNmRkNC00YjEzLWFlNzItMTAwODEwMzdjY2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDExMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOWZlNjA5YTRlYWU5MDdhNGI5YWE3ZDJmYmU0YzkzNDcwMTg3MzU1MTcyYTI0YjUzMGNiODgxNDA1ZWVjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2s_wzhhWgElwv2dOfhTsiYth1TTQGsWRbIWrdVM2Dqg)
> 
> I have just looked up the correct PMID for this article and it is PMID: 30727143 not PMID:30717143.
> 
> Please could you start a new curation session with the correct PMID and enter the curated information. Unfortunately there is no shortcut for this but at least there is only one annotation :-). (Once this is done, I will then ask James to delete the incorrect PMID:30717143 session from PHI-Canto.)
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/289828727-49fafe72-95f2-49f0-a951-4a8288f0657f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzk2NzAsIm5iZiI6MTcwMjM3OTM3MCwicGF0aCI6Ii8xMTc1MzYzNC8yODk4Mjg3MjctNDlmYWZlNzItOTVmMi00OWYwLWE5NTEtNGE4Mjg4ZjA2NTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDExMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMDkxZTI3NWMxNmNhOGU2ODY4YmVmMzBiNDkwYjE0MmEzZTMwNGRhZGQ2MTFmNmFmYjQ3YTQ1Nzk2ZGRkY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PR5B6A0Sw94zJtG4B6lTmk_ZnxMCOSpJKXYOroHcHcs)
> 
> Here is the UniProt D0VVD6 and if you agree with my comments above you can amend the strain in the genotype from 'MBJA8' to 'MPA18'.

Hi @CuzickA, thanks so much for spotting the mistake (I was wondering why I couldn't find the curation session in my curation list).

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I have created the new session with annotations, please check.

https://canto.phi-base.org/curs/93b1e80c305cc8da

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, thank you for doing this. I have just made a couple of changes to match the original entry.

![image](https://github.com/PHI-base/curation/assets/11753634/445b2f67-573b-4af1-8b15-f04f2049248b)

**Comment by CuzickA** [comment]
**Next steps**

1) AC to check AE alteration in archetype with Nichola.

Then session will be ready for approval.

2) AC to add Monilinia fructicola strain 'MPA18' to strain list. _DONE 08_01_2024_
3) AC to ask James to delete incorrect PMID/session  PMID:30717143 / https://canto.phi-base.org/curs/374b149aa1776aac

**Comment by CuzickA** [comment]
Hi @jseager7, please could you delete this incorrectly added PMID/session from PHI-Canto?


> AC to ask James to delete incorrect PMID/session PMID:30717143 / https://canto.phi-base.org/curs/374b149aa1776aac

**Comment by jseager7** [comment]
> Hi jseager7, please could you delete this incorrectly added PMID/session from PHI-Canto?

Sure, I'll try to get this done this week.

**Comment by jseager7** [comment]
PMID:30717143 and its curation session (374b149aa1776aac) have been removed from PHI-Canto now.

**Comment by CuzickA** [comment]
AE alteration in archetype checked by Nichola and looks fine.

Approving session and closing ticket.
