### ISSUE TITLE
PMID:22906850 Effect of DMI-resistance mechanisms on cross-resistance patterns, fitness parameters and aflatoxin production in Aspergillus parasiticus Speare

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#208]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/9c3254c570ce9eb4

**Comment by jingluodatacurator** [comment]
Notes:

Uniprot id: J9XNG1, from accession number given (JX312359) in Fig. 2 text.
Strains: ATCC 15517
Main expt. for curation: 
(2.3) A suspension of 108 conidia ml-1 conidia of the wild-type strain
of A. parasiticus, obtained from 10 to 15-day-old slant cultures, was
exposed to ultraviolet irradiation (TUV Philips, 15 W, 254 nm) for
4 min, which resulted in 92% lethality. After irradiation they were
kept for 30 min in the dark to minimize photorepair of radiation
damage, and then placed on CZA agar medium amended with
25 lg ml-1 flusilazole, and incubated at 30 oC for 20 days, to enable resistant colonies to appear.
(3.1) From this initial screening a representative sample of
twelve mutant strains, three from R1 and nine from R2 phenotype,
where chosen for further studies.
The R1 mutant strains were moderate resistant
to flusilazole, with a resistance factor (Rf) based on EC50 values
ranging from 25 to 30. On the contrary, the R2 phenotypic class
included mutants with a low to moderate level of resistance (Rf:
10–12, based on EC50s) to flusilazole (Table 2).

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, are you still working on this session or is it ready for checking please?

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, are you still working on this session or is it ready for checking please?

Hi @CuzickA, I believe my initial curation has been completed for review please, thanks.

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/5a430324-a611-4e2e-8ba4-38500efaf955)

**Comment by CuzickA** [comment]
**Checking UniProt**

> Uniprot id: J9XNG1, from accession number given (JX312359) in Fig. 2 text.

This is incorrect as this accession number (JX312359) is for mdr gene NOT Cyp51A or Cyp51B. (Cyp51A has been curated in the screenshot above)
![image](https://github.com/PHI-base/curation/assets/11753634/a9844e7d-923d-4820-b932-a2983ef800e3)

Text on p798 just below Fig2 provides gene ids for Cyp51A and Cyp51B
![image](https://github.com/PHI-base/curation/assets/11753634/1f583cc6-e294-457a-9279-a63b184d51b8)

Looking up 'JX312357' in UniProt gives 

https://www.uniprot.org/uniprotkb/J9XQH7/entry

Hi @jingluodatacurator, please change the incorrect Cyp51A uniprot id to J9XQH7

**Comment by CuzickA** [comment]
**Checking strain**

> Strains: ATCC 15517

Strains listed in the annotations above are 'ZB1' and 'ZG8'.

These do not match with 'Strains: ATCC 15517' in the notes section above.

Hi @jingluodatacurator, please could you check this and write up a couple of notes here to summarise the expt.

**Comment by CuzickA** [comment]
There is genotype expression data available

It looks as though the expression level of WT Cyp51A vs Cyp51A with G54W mutation could be classed as expression 'wild type product level' as all close to '1' rather than 'not assayed'.

![image](https://github.com/PHI-base/curation/assets/11753634/41e493d2-f7d9-46e5-b463-25e19cb08f85)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please check that the conditions reflect the info in '2.4. In vitro fungitoxicity bioassays' rather than in '2.3. Mutation induction'. (This has been noted in your personal curation checklist 'On adding annotations of figures and conditions: they should reflect the phenotype expt rather than the creation of the mutants.')

**Comment by CuzickA** [comment]
**Next steps**
1) @jingluodatacurator, please look through and address comments above. DONE
2) AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.
3) AC try and add in AE alteration archetype info DONE 09_02_2024
4) AC decide whether new strains need adding to list. DONE 09_02_2024

**Comment by jingluodatacurator** [comment]
Summary of expt. :

(2.3. Mutation induction)
A suspension of 108 conidia ml-1 conidia of the wild-type strain of A. parasiticus, obtained from 10 to 15-day-old slant cultures, was exposed to ultraviolet irradiation (TUV Philips, 15 W, 254 nm) for 4 min, which resulted in 92%
lethality. After irradiation they were kept for 30 min in the dark to minimize photorepair of radiation damage, and then placed on CZA agar medium amended with 25 lg ml-1 flusilazole, and incubated at 30 C for 20 days, to enableresistant colonies to appear. The selected resistant isolates were maintained on CZA agar slants containing 5 lg ml-1 flusilazole, the minimal inhibitory concentration (MIC) for the wild-type parent strains of A. parasiticus.

(2.4. In vitro fungitoxicity bioassays)
The fungicide sensitivity of the wild-type and mutant strains was assessed by inoculating CZA medium plates with 2mm mycelial plugs cut from CZA medium on which conidia of A. parasiticus had been allowed to germinate, after overnight incubation at 30 C. The fungicides were added aseptically to sterilized growth medium from stock solutions, prior to inoculation. In all cases, the final amount of solvent never exceeded 1% (v/v) in treated and control samples. At least six concentrations with three replicas for each fungicide were used to obtain the respective fungitoxicity curves. Control plates without fungicide received an equivalent amount of solvent. The effect of the fungicide on radial growth was determined by measuring the diameter of mycelial colonies after incubation for 8 days at 30 C in the dark. The EC50 and the EC90 values were determined from dose–response curves after probit analysis.

**Comment by jingluodatacurator** [comment]
Uniprot ID: J9XQH7
Author has provided provided Cyp51A (JX312357) and Cyp51B (JX312358), only JX312357 was used to find the ID J9XQH7 for Cyp51A as analysis of deduced amino acid sequence of cyp51B showed that no mutations were associated with DMI resistance.

Strains: wild type strain ATCC15517 was used for UV mutagenesis expt.

**Comment by jingluodatacurator** [comment]
Genotype creation:

ZG11, ZG8, ZB1 have been curated for all three fungicides flusilazole, tebuconazole, imazalil. 
I'm not sure about the allele type for ZG11, @CuzickA please check thanks.

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks.

https://canto.phi-base.org/curs/9c3254c570ce9eb4

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, genotypes, phenotypes and conditions look good :-)

**Comment by CuzickA** [comment]
Add new pathogen species 1350924
Add new strain d621790

Next step for AC
1) add new PHIPO and PHI-ECO terms _DONE 13_02_2024_
2) check AE archetype with Nichola

**Comment by CuzickA** [comment]
**AE alteration in archetype**

From Nichola's Table S2
![image](https://github.com/PHI-base/curation/assets/11753634/33301e53-c483-45e6-b359-1507a9b99168)

cyp51A(aaG54W)[WT level] 'G70W; Cyp51A; ASPEFU'

![image](https://github.com/PHI-base/curation/assets/11753634/f6724701-ab9b-4f44-9b2b-b22de50f62ea)

**Comment by CuzickA** [comment]
**Next step**

> AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.

@jingluodatacurator, did you see anything else we could curate from Table 3?

![image](https://github.com/PHI-base/curation/assets/11753634/0bee976e-2238-4fb1-a4a8-d70be8f2a52d)

**Comment by jingluodatacurator** [comment]
> **Next step**
> 
> > AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.
> 
> @jingluodatacurator, did you see anything else we could curate from Table 3?
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/308107106-0bee976e-2238-4fb1-a4a8-d70be8f2a52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjczMzYsIm5iZiI6MTcwOTAyNzAzNiwicGF0aCI6Ii8xMTc1MzYzNC8zMDgxMDcxMDYtMGJlZTk3NmUtMjIzOC00ZmIxLWE0YTgtZDcwYmU4ZjJhNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjFiNzk5YzJkYTMwMTllNTYwNzE5MWU0ODRmYzI4NDMyMGU5YTAwYmNmZmJkMDA3YTA2ZGM5ZWM3MDQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzgMbkWSGmhmYCETueL917xGUA6wMWuMK8EuAY0iiTc)

Hi @CuzickA, I can not find the host species/gene in the paper in order to curate sporulation and germination data, could you help me out on this please thanks.

**Comment by CuzickA** [comment]
> > **Next step**
> > > AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.
> > 
> > 
> > @jingluodatacurator, did you see anything else we could curate from Table 3?
> > ![image](https://private-user-images.githubusercontent.com/11753634/308107106-0bee976e-2238-4fb1-a4a8-d70be8f2a52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjczMzYsIm5iZiI6MTcwOTAyNzAzNiwicGF0aCI6Ii8xMTc1MzYzNC8zMDgxMDcxMDYtMGJlZTk3NmUtMjIzOC00ZmIxLWE0YTgtZDcwYmU4ZjJhNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjFiNzk5YzJkYTMwMTllNTYwNzE5MWU0ODRmYzI4NDMyMGU5YTAwYmNmZmJkMDA3YTA2ZGM5ZWM3MDQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzgMbkWSGmhmYCETueL917xGUA6wMWuMK8EuAY0iiTc)
> 
> Hi @CuzickA, I can not find the host species/gene in the paper in order to curate sporulation and germination data, could you help me out on this please thanks.

Hi @jingluodatacurator, these look like pathogen only phenotypes. See info in '2.5. Determination of ecological fitness parameters and aflatoxin production'. We are not currently curating the aflatoxin production expt. - although maybe we could also try and do this.

**Comment by jingluodatacurator** [comment]
> > > **Next step**
> > > > AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.
> > > 
> > > 
> > > @jingluodatacurator, did you see anything else we could curate from Table 3?
> > > ![image](https://private-user-images.githubusercontent.com/11753634/308107106-0bee976e-2238-4fb1-a4a8-d70be8f2a52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjczMzYsIm5iZiI6MTcwOTAyNzAzNiwicGF0aCI6Ii8xMTc1MzYzNC8zMDgxMDcxMDYtMGJlZTk3NmUtMjIzOC00ZmIxLWE0YTgtZDcwYmU4ZjJhNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjFiNzk5YzJkYTMwMTllNTYwNzE5MWU0ODRmYzI4NDMyMGU5YTAwYmNmZmJkMDA3YTA2ZGM5ZWM3MDQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzgMbkWSGmhmYCETueL917xGUA6wMWuMK8EuAY0iiTc)
> > 
> > 
> > Hi @CuzickA, I can not find the host species/gene in the paper in order to curate sporulation and germination data, could you help me out on this please thanks.
> 
> Hi @jingluodatacurator, these look like pathogen only phenotypes. See info in '2.5. Determination of ecological fitness parameters and aflatoxin production'. We are not currently curating the aflatoxin production expt. - although maybe we could also try and do this.

Ok @CuzickA, so what's your suggestion here for further action, thanks.

**Comment by CuzickA** [comment]
> > > > **Next step**
> > > > > AC and JL, Once step 1 has been completed, consider whether we can curate any of the 'fitness' expts in Table 3.
> > > > 
> > > > 
> > > > @jingluodatacurator, did you see anything else we could curate from Table 3?
> > > > ![image](https://private-user-images.githubusercontent.com/11753634/308107106-0bee976e-2238-4fb1-a4a8-d70be8f2a52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjczMzYsIm5iZiI6MTcwOTAyNzAzNiwicGF0aCI6Ii8xMTc1MzYzNC8zMDgxMDcxMDYtMGJlZTk3NmUtMjIzOC00ZmIxLWE0YTgtZDcwYmU4ZjJhNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjFiNzk5YzJkYTMwMTllNTYwNzE5MWU0ODRmYzI4NDMyMGU5YTAwYmNmZmJkMDA3YTA2ZGM5ZWM3MDQzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzgMbkWSGmhmYCETueL917xGUA6wMWuMK8EuAY0iiTc)
> > > 
> > > 
> > > Hi @CuzickA, I can not find the host species/gene in the paper in order to curate sporulation and germination data, could you help me out on this please thanks.
> > 
> > 
> > Hi @jingluodatacurator, these look like pathogen only phenotypes. See info in '2.5. Determination of ecological fitness parameters and aflatoxin production'. We are not currently curating the aflatoxin production expt. - although maybe we could also try and do this.
> 
> Ok @CuzickA, so what's your suggestion here for further action, thanks.

Hi @jingluodatacurator, I'm suggesting you curate the sporulation and germination data as pathogen only phenotypes if these expts were done without a host.

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, I have curated pathogen only phenotypes for sporulation and germination data (I have tried my best!), however am not sure if they are correct, please check thanks.

**Comment by CuzickA** [comment]
Note to self

strain ZG11 corresponds to genotype cyp51A+[Overexpression]

Strains ZG8 and ZB1 correspond to genotype cyp51A(aaG54W)[WT level]

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/8c7155fc-2a16-4b67-9e46-bf70b44e0137)

Text from paper 'Comparison of sporulation and spore germination between
DMI-resistant mutants and the wild-type parent strain of A. parasiticus
showed that with the exception of ZG11 isolate, these fitness
parameters were significantly reduced in all other mutant strains
tested (Table 3).'

Hi @jingluodatacurator, good job on having a go with these and finding some of the 'spore' PHIPO terms. Looking at the text and Table 3 it might be that these annotations have been made to the wrong genotype. Please could you have another look?

**Comment by CuzickA** [comment]
A note about which PHIPO term to use for @jingluodatacurator 

For 'reduced asexual sporulation' I think you could use 'decreased number of asexual spores'.



![image](https://github.com/PHI-base/curation/assets/11753634/a1d6ceda-ce45-4137-8da1-b0d1b2d6db99)


If you look at the Table 3, they state they count the number of asexual spores/conidia

![image](https://github.com/PHI-base/curation/assets/11753634/2aa33b9c-1448-42c0-bb5d-200b0040976c)
![image](https://github.com/PHI-base/curation/assets/11753634/8f3a7d7d-ecc4-4ee7-ac9e-c9d1f3371cc1)

**Comment by jingluodatacurator** [comment]
Hi @CuzickA, have made amendments to your suggestions above, thanks.

**Comment by CuzickA** [comment]
Thanks @jingluodatacurator,

looks good, please could you add back in the missing conditions?

![image](https://github.com/PHI-base/curation/assets/11753634/3775caf5-d268-4a02-a99e-9b98a36fec5b)

**Comment by CuzickA** [comment]
**Next steps**

I think we have curated the main phenotypes now for this paper.

1) The missing conditions need adding to above by JL
2) AC to check AE alteration in archetype with Nichola

Then session will be ready to approve.

**Comment by jingluodatacurator** [comment]
> Thanks @jingluodatacurator,
> 
> looks good, please could you add back in the missing conditions?
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/308552583-3775caf5-d268-4a02-a99e-9b98a36fec5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjUyNjQsIm5iZiI6MTcwOTEyNDk2NCwicGF0aCI6Ii8xMTc1MzYzNC8zMDg1NTI1ODMtMzc3NWNhZjUtZDI2OC00YTAyLWE5OWUtOWI5OGEzNmZlYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEyNTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTkzNDdmNmM0YmU0ODkwZGMzY2ZmMmRkMDU4NDEzYjA3NWYwMTE3NmQ1YzE2N2MwOWU5Yzk4MTFkNDc0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8XH1x2wMGcsan0-7igyNA5aWqwOBfVntlW3VdOSiQTU)

Hi @CuzickA, missing conditions have been added, thanks.

**Comment by CuzickA** [comment]
Good job @jingluodatacurator, thanks

![image](https://github.com/PHI-base/curation/assets/11753634/5a5e43f4-34c7-46f8-91b4-494e731ea983)

**Comment by CuzickA** [comment]
**Next steps**

1) AC to check AE alteration in archetype with Nichola

Then session will be ready to approve.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
