### ISSUE TITLE
PMID:1423663 Amino Acid Alterations in the benA  (p-Tubulin) Gene of Aspergillus nidulans  That Confer Benomyl Resistance

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#210]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/b96445376007e166

**Comment by jingluodatacurator** [comment]
Notes:

Uniprot ID: P10653 (https://www.uniprot.org/uniprotkb?query=Aspergillus+nidulans+AND+benA)
Strains: G191
The main expt. for curation: in Results 'As Table I shows, in 11 cases the resistance mutation in beta-tubulin was a tyrosine for histidine substitution at aa 6. In one case resistance was caused by a leucine for 
histidine substitution at aa 6. In four cases resistance was 
caused by mutations at aa 198. In two cases the glutamic 
acid at aa 198 was changed to aspartic acid, in one case 
it was changed to glutamine, and in one case it was 
changed to lysine. In two cases aa 200 was changed from 
phenylalanine to tyrosine.'

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, please could you email me your highlighted PDF of this paper so that I can check the session. Thanks.

**Comment by CuzickA** [comment]
Uniprot ID: P10653 looks good.

**Comment by CuzickA** [comment]
Looking at first annotation
![image](https://github.com/PHI-base/curation/assets/11753634/c87e1287-c8c9-44ee-aeac-3376f737d519)

~Genotypes look good.~ _AC 19_01_2024 after further checking it looks as if most of the genotypes have the incorrect amino acid symbols. These needs updating - see comment below._

Might be missing 1 genotype from the text and Table 1

![image](https://github.com/PHI-base/curation/assets/11753634/e44e5a57-9e62-4af7-80ae-f93fb8815195)


Phenotypes annotations look good.
All annotations are missing the chemical in the conditions.






@jingluodatacurator, please could you follow up on whether an extra genotype need adding and also add in the chemical to the conditions. Thanks

**Comment by jingluodatacurator** [comment]
> Looking at first annotation ![image](https://private-user-images.githubusercontent.com/11753634/297428387-c87e1287-c8c9-44ee-aeac-3376f737d519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYyMzEsIm5iZiI6MTcwNTUwNTkzMSwicGF0aCI6Ii8xMTc1MzYzNC8yOTc0MjgzODctYzg3ZTEyODctYzhjOS00NGVlLWFlYWMtMzM3NmY3MzdkNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOTU5YzZjOGU2MDEyOGM0YWJjNThhY2E5Y2QwODIwMGIyOGJhN2FhMmJkOGJhNmQxM2M0MTZiYWFhYWM3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.231lNYLvBw6M57oxgV0IwYlyBfxSzDRvHC462MoXvek)
> 
> Genotypes look good.
> 
> Might be missing 1 genotype from the text and Table 1
> 
> ![image](https://private-user-images.githubusercontent.com/11753634/297432053-e44e5a57-9e62-4af7-80ae-f93fb8815195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYyMzEsIm5iZiI6MTcwNTUwNTkzMSwicGF0aCI6Ii8xMTc1MzYzNC8yOTc0MzIwNTMtZTQ0ZTVhNTctOWU2Mi00YWY3LTgwYWUtZjkzZmI4ODE1MTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1Mzg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTlkN2Y3MTAzYThkOGQ1YmMwNzI0MzU4YzgxNTQzMmJiZTU0MmMzODgwOGEzMzU3YjUyYWRlNGMwMTNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDvSfZ3DFuJ5b0tLD12f4bcmElUyOZryXOswv7JudV8)
> 
> Phenotypes annotations look good. All annotations are missing the chemical in the conditions.
> 
> @jingluodatacurator, please could you follow up on whether an extra genotype need adding and also add in the chemical to the conditions. Thanks

Thanks @CuzickA for the feedback. The reason that I did not include in the genotype Glu->Gln 198 yet is that I was unsure G198G would be the correct term for allele descriptioin?

**Comment by CuzickA** [comment]
Thanks @jingluodatacurator for adding in the chemical to the conditions.

For the amino acid symbols I usually just do a web search to look up the symbols and abbreviations
eg
![image](https://github.com/PHI-base/curation/assets/11753634/255fc3fb-fc93-4b21-b74a-10c62b665d0d)

The symbol for Gln is Q.
The symbol for Glu is E and not G. 
The symbol for Tyr is Y and not T.
The symbol for Asp is D and not A.
The symbol for Lys is K and not L.
The symbol for Phe is F and not P.

It looks like most of the genotypes have the incorrect amino acid symbols. @jingluodatacurator, please can you update these?

**Comment by CuzickA** [comment]
**Next steps**
1) @jingluodatacurator to correct genotype and add missing genotype. DONE
2) AC to try and add AE alteration in archetype. DONE
3) AC add new strain 'G191' to An DONE f397aa6
4) AC to ask Nichola to check AE alteration in archetype

**Comment by jingluodatacurator** [comment]
> Thanks @jingluodatacurator for adding in the chemical to the conditions.
> 
> For the amino acid symbols I usually just do a web search to look up the symbols and abbreviations eg ![image](https://private-user-images.githubusercontent.com/11753634/298006091-255fc3fb-fc93-4b21-b74a-10c62b665d0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjMxNTUsIm5iZiI6MTcwNTkyMjg1NSwicGF0aCI6Ii8xMTc1MzYzNC8yOTgwMDYwOTEtMjU1ZmMzZmItZmM5My00YjIxLWI3NGEtMTBjNjJiNjY1ZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDExMjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZDc1MGZhYjFiYTllMzA5ODBmMDRjZTEzYzQ3NzBmZGRjODYzMTk4ZTMzNGUxNTkxMzRkNTMyMTdhMjNmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.haSf0Zxcb4ws-J8bKqV6qe-WgHrQSOnmX5DI11d5aXI)
> 
> The symbol for Gln is Q. The symbol for Glu is E and not G. The symbol for Tyr is Y and not T. The symbol for Asp is D and not A. The symbol for Lys is K and not L. The symbol for Phe is F and not P.
> 
> It looks like most of the genotypes have the incorrect amino acid symbols. @jingluodatacurator, please can you update these?

Hi @CuzickA, I have added the missing genotype and its annotations. Thanks for the info on symbols and abbreviations, I have updated all thanks.

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, your updates look good thanks.

Here is the link to the AA abbreviations I screenshotted above in case you want to add it to your favourites bar
https://www.freepik.com/premium-vector/threeletter-oneletter-symbols-amino-acids_50302949.htm

**Comment by CuzickA** [comment]
**AE alteration in archetype**

benA(aaH6Y)[Not assayed] 'H6Y; benA (β-tubulin); ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/720960aa-2dc1-43d0-94ef-28770e323fe4)
![image](https://github.com/PHI-base/curation/assets/11753634/918dabc7-ba06-48a9-b2b7-3848cfb15e83)

![image](https://github.com/PHI-base/curation/assets/11753634/da09a086-65e9-4aa6-9d3e-e415e848e9b4)



benA(aaH6L)[Not assayed] 'H6L; benA (β-tubulin); ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/758e2509-b14a-4430-9df6-2169a79635d1)

![image](https://github.com/PHI-base/curation/assets/11753634/5a259cc8-c85c-4510-9b26-c334f5736b35)


benA(aaE198D)[Not assayed] 'E198D; benA (β-tubulin); ASPEND'

![image](https://github.com/PHI-base/curation/assets/11753634/a2561674-1f28-4446-bb2c-f908c24ee0e7)

![image](https://github.com/PHI-base/curation/assets/11753634/4e1c957a-1379-4113-b5ec-ae1b66949f26)


benA(aaE198K)[Not assayed] 'E198K; benA (β-tubulin); ASPEND'
![image](https://github.com/PHI-base/curation/assets/11753634/129851d1-4acf-4ac7-97ab-ad1dbb19e013)
![image](https://github.com/PHI-base/curation/assets/11753634/55ff8b27-cb3d-48ac-b084-380f38f2c993)


benA(aaE198Q)[Not assayed] 'E198Q; benA (β-tubulin); ASPEND'
![image](https://github.com/PHI-base/curation/assets/11753634/3e7d7ca3-52c2-4371-93d6-67671bf9fefa)

![image](https://github.com/PHI-base/curation/assets/11753634/4a5f3162-595b-48e8-b3dd-06dbea9eba73)

benA(aaF200Y)[Not assayed]  'F200Y; benA (β-tubulin); ASPEND'
![image](https://github.com/PHI-base/curation/assets/11753634/7553d6f3-2235-470f-8a23-54c93e5f8ba9)
![image](https://github.com/PHI-base/curation/assets/11753634/0626a003-00a2-4e56-80f3-c6256310f8a3)

**Comment by CuzickA** [comment]
**Next steps**

1) AC to ask Nichola to check AE alteration in archetype
2) Session will be ready to approve

**Comment by CuzickA** [comment]
Nichola has checked the AE and looks fine.

Approving session and closing ticket.
