### ISSUE TITLE
PMID:22848705 Assessing the Risk That Phytophthora melonis Can Develop a Point Mutation (V1109L) in CesA3 Conferring Resistance to Carboxylic Acid Amide Fungicides

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#211]
Curated by @jingluodatacurator

https://canto.phi-base.org/curs/513a675c2dfb1857

Hi @CuzickA, I'm having trouble to find the Uniprot ID. I have typed in the search box in Uniprot 'Phytophthora Melonis AND CesA3' but nothing came up.

**Comment by jingluodatacurator** [comment]
[Lei Chen et al. 2012 PMID22848705.pdf](https://github.com/PHI-base/curation/files/14058637/Lei.Chen.et.al.2012.PMID22848705.pdf)

**Comment by CuzickA** [comment]
Hi @jingluodatacurator, unfortunately I can't find a UniProt id for this one either. Perhaps you could email the authors.

**Comment by jingluodatacurator** [comment]
> Hi @jingluodatacurator, unfortunately I can't find a UniProt id for this one either. Perhaps you could email the authors.

Hi @CuzickA, I believe I have emailed the author a while ago but have had no reply. Do you think it's worth to give another try?

**Comment by CuzickA** [comment]
> > Hi @jingluodatacurator, unfortunately I can't find a UniProt id for this one either. Perhaps you could email the authors.
> 
> Hi @CuzickA, I believe I have emailed the author a while ago but have had no reply. Do you think it's worth to give another try?

Hi @jingluodatacurator, please could you note in the ticket when you email the authors so we can keep track. Do you still have a copy of the sent email? It may be worth another try.

**Comment by CuzickA** [comment]
Email was sent to author on 15 November 2023 by @jingluodatacurator. We have had no response.

@jingluodatacurator Please make a note in the chemistry curation papers spreadsheet that we cannot curate this paper as we cannot find a UniProt id.

Please let me know when you have done this and I'll close this ticket for now as uncuratable. Thank you.

**Comment by jingluodatacurator** [comment]
> Email was sent to author on 15 November 2023 by @jingluodatacurator. We have had no response.
> 
> @jingluodatacurator Please make a note in the chemistry curation papers spreadsheet that we cannot curate this paper as we cannot find a UniProt id.
> 
> Please let me know when you have done this and I'll close this ticket for now as uncuratable. Thank you.

Hi @CuzickA, note has been made in the chemistry curation papers spreadsheet thanks.
