### ISSUE TITLE
PMID18775650: Molecular characterisation of cyp51A and cyp51B genes coding for P450 14alpha-lanosterol demethylases A (CYP51Ap) and B (CYP51Bp) from voriconazole-resistant laboratory isolates of Aspergillus flavus

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#212]
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/c2c86c6be23c622b

**Comment by jingluodatacurator** [comment]
Summary of expt. : 

(2.1. Selection and in vitro susceptibility testing of VCZ-resistant isolates)
Aspergillus flavus X26728 highly susceptible to various antifungal drugs was used. Approximately 1 × 106 conidia per plate were spread on SDA containing 0.5 micro g/mL VCZ and the plates were incubated at 35 ◦C for 4–6 days in plastic bags to maintain moisture. Colonies growing on these plates were screened for their susceptibility to VCZ using 96-well microtitre plates. Seventeen colonies that grew in the presence of 4 micro g/mL VCZ in liquid culture (frequency ca. 0.5 × 10−8) were selected and further tested for their in vitro susceptibility to various antifungal drugs. The MICs of antifungal drugs for the VCZ-susceptible parent X26728 and VCZ-resistant A. flavus isolates were determined by the broth dilution method recommended by the Clinical and Laboratory Standards Institute.

(Results 3.1. Characterisation of cyp51A and CYP51B genes)
Alignment of the deduced amino acid sequences of CYP51Ap and CYP51Bp from ten VCZ-resistant isolates with that of the drug-susceptible parent X26728 showed variation in six of the ten isolates. Changes in CYP51Ap were noted
at K197N (isolates Afl-VCZ6 and Afl-VCZ46), Y132N + T469S (isolate Afl-VCZ114) and K197N + D282E + M288L (isolate Afl-VCZ45). Similarly, in CYP51Bp amino acid changes were noted at positions H399P + D411N (isolate Afl-VCZ40) and T454P + T486P (isolate Afl-VCZ112) (Table 1; Fig. 4). These data suggest that drug target modification may play an important role in VCZ resistance in A. flavus. The lack of any amino acid changes in four of the ten isolates implies that other mechanism(s), e.g. efflux, might also be involved.

**Comment by jingluodatacurator** [comment]
Uniprot ID: author provided cyp51A GenBank No. AAIH01000692.1 and cyp51B GenBank No. AAIH01001161.1, however both couldn't locate any IDs. So key words 'Aspergillus Flavus AND cyp51' were used instead to find the IDs B8N2C8 (cyp51A) and B8NFL5 (cyp51B).

Strains: X26728 (parent strain) was used for spontaneous mutation expt.

**Comment by jingluodatacurator** [comment]
Genotype creation: 

Afl-VCZ6, Afl-VCZ40, Afl-VCZ45, Afl-VCZ112, Afl-VCZ114 have been curated for VCZ. I'm not sure about Afl-VCZ 46, as it looks to me the same as Afl-VCZ6?!

**Comment by jingluodatacurator** [comment]
Curation completed pending review by @CuzickA thanks.

**Comment by CuzickA** [comment]
UniProt ids look good. Both Swiss-prot reviewed entries.

**Comment by CuzickA** [comment]
Aspergillus flavus X26728 clinical strain sensitive to voriconazole. Spontaneous mutants were resistant to voriconazole,  mutations were found in the Cyp51A and Cyp51B genes.

**Comment by CuzickA** [comment]
Current annotations
![image](https://github.com/PHI-base/curation/assets/11753634/f19bf6dc-8d91-47c3-af1d-7f0bfb494667)

**Comment by CuzickA** [comment]
> Genotype creation:
> 
> Afl-VCZ6, Afl-VCZ40, Afl-VCZ45, Afl-VCZ112, Afl-VCZ114 have been curated for VCZ. I'm not sure about Afl-VCZ 46, as it looks to me the same as Afl-VCZ6?!

Yes, Afl-VCZ6 and Afl-VCZ6 have the same mutation K197N

![image](https://github.com/PHI-base/curation/assets/11753634/10fc4e85-cbd5-4688-b50a-a29820b4d8e7)
![image](https://github.com/PHI-base/curation/assets/11753634/128501c9-111d-474c-8cf1-4a54f0445750)

**Comment by CuzickA** [comment]
Genotypes and phenotype look correct.

Will continue checking tomorrow - next conditions, fig and comment. Then add strain and AE alteration in archetype.

**Comment by CuzickA** [comment]
Evidence and conditions look fine.

@jingluodatacurator, for the Figure, I don't think we need to add 'Figure 4' showing the sequence alignments as this is more to do with the genotype than the expt of testing the mutant on voricanazole plates Table 1.

I have now deleted 'Figure 4'

**Comment by CuzickA** [comment]
Good job on this one @jingluodatacurator 

Next steps for AC
1) add strain 'X26728' to Aspergillus flavus strain lists DONE 9e24ecc
2) Try and add AE alteration in archetype

**Comment by CuzickA** [comment]
**AE alteration in archetype**

Aspergillus flavus information not available in Nichola's Table S2.

EPPO code from Mair et al 2016
![image](https://github.com/PHI-base/curation/assets/11753634/8f9b95b9-04ef-41a2-83de-76effca6851f)

**Comment by CuzickA** [comment]
Cyp51A archetype species is Aspergillus fumigatus 'ASPEFU'

A. flavus cyp51A(aaK197N)[Not assayed] 'K133N; Cyp51A; ASPEFU'

![image](https://github.com/PHI-base/curation/assets/11753634/dae7d532-ad4a-4c44-a5ef-6861805b788f)
![image](https://github.com/PHI-base/curation/assets/11753634/334102fa-8c54-4631-b972-b56aaead0907)
![image](https://github.com/PHI-base/curation/assets/11753634/bbfdfa84-fede-487b-8079-254a92b91117)




cyp51A(aaK197N, D282E, M288L)[Not assayed] 'K133N, D280E, M286L; Cyp51A; ASPEFU'

![image](https://github.com/PHI-base/curation/assets/11753634/31243b73-0788-496e-a659-64bb64b1c337)
![image](https://github.com/PHI-base/curation/assets/11753634/690cc332-7be5-4153-baea-c1d6123524cf)




cyp51A(aaY132N, T469S)[Not assayed] 'Y68N, T470S; Cyp51A; ASPEFU'
![image](https://github.com/PHI-base/curation/assets/11753634/ef1bbeb7-2a26-454b-93ea-05b9bebd6ade)
![image](https://github.com/PHI-base/curation/assets/11753634/bfb98ac8-82db-409b-91bb-1288448f6ea2)

![image](https://github.com/PHI-base/curation/assets/11753634/3e59ec15-1914-4313-b73e-b778a6b3faf9)

**Comment by CuzickA** [comment]
Cyp51B archetype species is Zymoseptoria tritici 'SEPTTR'

A. flavus cyp51B(aaH399P, D411N)[Not assayed] 'H430P, 453N; Cyp51B; SEPTTR'
![image](https://github.com/PHI-base/curation/assets/11753634/c70632f0-f711-43bd-91cf-7e0b964bacc7)
![image](https://github.com/PHI-base/curation/assets/11753634/9e22afe0-e36f-4ce4-b7b7-972677f31669)
![image](https://github.com/PHI-base/curation/assets/11753634/51158ffd-a158-4f5a-b18a-34b34ca4c9e8)



cyp51B(aaT454P, T486P)[Not assayed]  'T496P, **XXXX**; Cyp51B; SEPTTR'

![image](https://github.com/PHI-base/curation/assets/11753634/ccc445f1-ddc0-4f8a-b8a9-fd6a7807e99d)


T486P not listed, will need to use FRAST

**Comment by CuzickA** [comment]
Use Cyp51B UniProt id for FASTA file https://www.uniprot.org/uniprotkb/B8NFL5/entry

![image](https://github.com/PHI-base/curation/assets/11753634/b7987ad8-8966-4b65-96f6-a7328e002a13)

T486P Could be 'T538P' BUT wildtype AA is 'E' not 'T'. Is there an alignment error?


Check with T454P -> T496P This also does not align with the wild type AA or the residue number indicated in Mair et al
![image](https://github.com/PHI-base/curation/assets/11753634/f1631521-d96c-473c-a92a-67f9f1eeea49)

I think this suggests that there is a problem with the uniprot sequence??

I will not add the AE for cyp51B(aaT454P, T486P)[Not assayed] 'T496P, XXXX; Cyp51B; SEPTTR'

**Comment by CuzickA** [comment]
Next steps

Check AE alteration in archetype with Nichola.

Then session will be ready for approval.

**Comment by CuzickA** [comment]
Session approved without Nichola checking AE alteration in archetype.

Closing ticket.
