### ISSUE TITLE
PMID:36928713 The mitotic exit mediated by small GTPase Tem1 is essential for the pathogenicity of Fusarium graminearum.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#213]
Journal club paper, curated by Victoria Armer in the WPT.

Link https://canto.phi-base.org/curs/a0b9d1d7b275010e

**Comment by CuzickA** [comment]
Checking UniProt Id.
Authors provide 'FGSG_17139', search UniProt with this and get no results.

Search with 'tem1 fusarium graminearum' and get 3 results https://www.uniprot.org/uniprotkb?query=tem1+fusarium+graminearum
One of which is https://www.uniprot.org/uniprotkb/I1RXB5/entry 
This was selected by the curator.

**Comment by CuzickA** [comment]
Current annotations (focus on tem1 deletion mutant)
![image](https://github.com/PHI-base/curation/assets/11753634/92323c0a-ddf8-400a-a01e-2bc2631c53a9)
![image](https://github.com/PHI-base/curation/assets/11753634/1c989a28-698a-4984-878b-229a3f1b3a19)

**Comment by CuzickA** [comment]
Editing pathogen genotype to use the gene name given by the authors 'FgTem1' rather than the name used by Uniprot
![image](https://github.com/PHI-base/curation/assets/11753634/f6e5d25b-0ad9-4bcc-ae91-060158b3a79d)
![image](https://github.com/PHI-base/curation/assets/11753634/b274dbd1-616a-47e1-91a4-85ab924c101f)

changed to

![image](https://github.com/PHI-base/curation/assets/11753634/4c6bd311-b0a5-4998-99b8-f7e18cdc7091)

**Comment by CuzickA** [comment]
Edited the PHI phenotypes to include WT control metagenotype and appropriate AEs
![image](https://github.com/PHI-base/curation/assets/11753634/2740b9d2-5b7c-44f2-8a6c-560df76a14c0)

Also currently querying whether the PHIPO terms ‘abolished pathogen tissue to tissue migration within host’ and ‘presence of pathogen tissue to tissue migration within host’ would be more appropriate.

**Comment by CuzickA** [comment]
Next, need to check the GO annotations and Pathogen phenotype annotation.

**Comment by CuzickA** [comment]
My Email questions and responses from Victoria Armer

1)	Please could you tell me how you found the UniProt id?

(VA) I found the Uniprot ID by searching the gene name listed in Fungi DB first to convert it from FGSG to FGRAMPH1 to the new gene name. I actually hadn’t realised at first that to pull up the correct gene in Uniprot I had to change it from FGRAMPH1_01**G**28219 to FGRAMPH1_01**T**28219 (i.e., the transcript rather than the gene), so it might be worth making a note of this! An example picture of where the Uniprot ID is may also help for those that aren’t familiar. 


2) I have made an edit to the genotype name so that we use the FgTem1 name used by the authors rather than the UniProt name. (images provided) I did this by directly editing the allele name. I believe you entered FgTem1 as a new synonym but unfortunately that is not displayed. Do you think that we need clearer guidance on editing the allele name within the genotype?

(VA) I also think some clearer guidance on changing the name to the common one would help, as I thought I had changed this! 

3) I was looking at the Fig 1 Pathogen-host interaction annotation and have made a couple of changes. Good job on creating a metagenotype.
The changes I have made are adding in a wild type metagenotype control and corresponding annotation. We only do this for metagenotypes and not for the pathogen only genotypes. 
In the annotation extensions for the mutant metagenotype, we can then add the wild type metagenotype as the ‘compared to control’ as well as the high-level term ‘reduced virulence’. I also added the tissue type to both annotations. The annotations now look like this (images provided in email)

(VA) I also found that the metagenotype label was hard to find down on the bottom left – is there a reason it is down there and not in the drop-down list after host/ pathogen?

4) In 3) above I wonder if the PHIPO terms ‘abolished pathogen tissue to tissue migration within host’ and ‘presence of pathogen tissue to tissue migration within host’ would be more appropriate? Please let me know if you agree.

(VA) Thank you for amending the PHIPO terms, yes I agree your suggestions are better!  I wasn’t sure what to put – I had initially started with reduced virulence for the pathogen but realised this wasn’t an option! A link to a list of all the options might be ideal if there isn’t one already so I can pick the most appropriate, rather than guessing what there is.

**Comment by CuzickA** [comment]
I have now updated the PHI phenotype with my suggested terms

![image](https://github.com/PHI-base/curation/assets/11753634/6a4273af-3e59-4c8c-9426-4b01a63676b3)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/9597d1f7-32a0-4b23-814d-77b6e822524f)

![image](https://github.com/PHI-base/curation/assets/11753634/05509291-e8ed-4068-9ffb-ab123d59d8f9)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/4337e28f-0a92-4ead-a1f0-82bc1166cc01)

Looks like we need a NTR: increased number of septum in asexual spore

For Fig 2A


![image](https://github.com/PHI-base/curation/assets/11753634/c80c5cfd-2fd6-43c9-afcc-62ed8fbbf193)
I added NTR and text from a paper into comment. We can drill down and capture more phenotype data here.

We will also need to enable AE has severity : low for the parent grouping terms.

**Comment by CuzickA** [comment]
Also maybe NTR: increased number of nuclei in asexual spore

For Fig 2C

![image](https://github.com/PHI-base/curation/assets/11753634/a2d63f13-6c9d-439b-9e72-18cd4181edeb)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/619df289-3d90-4d4b-b6e4-b24ecba68395)

Also maybe NTR: increased number of nuclei in filament

For Fig 2B

Leave this one for now.

**Comment by CuzickA** [comment]
I have added 'Disease name' annotation to the wild type control metagenotype

![image](https://github.com/PHI-base/curation/assets/11753634/e7c82110-a002-486f-af9c-05fc61f17040)

**Comment by CuzickA** [comment]
Annotations could also be made for this
![image](https://github.com/PHI-base/curation/assets/11753634/c8fd0ae3-79e5-4a06-9dd7-186e27c1d11c)


'The phenotypic assessment
results showed a slight reduction in the vegetative growths of the ΔFgtem1 strains relative to
the wild type and the ΔFgtem1-C strain (Fig 1A and 1B). Furthermore, there was a slight
reduction in the number of conidia produced by the ΔFgtem1 mutant compared to the PH-1
and ΔFgtem1-C strains (Fig 1C).'

I will reactivate the session invite Victoria to make further annotations here

**Comment by CuzickA** [comment]
Currently not curated as in S files
Text from discussion 'Sexual reproduction and DON production were not altered in the ΔFgtem1 mutant.'

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/d8099ab2-7a3d-44af-9d9b-345f0155f5b6)

I think these look ok for now. In the future when the other proteins (bub2 and bfa1) are added to the session there may be more annotations to make about GAPS (GTPase-activating proteins or GTPase-accelerating proteins (GAPs))
![image](https://github.com/PHI-base/curation/assets/11753634/79e4825b-77f3-470e-9cf8-c5148585cfe2)
![image](https://github.com/PHI-base/curation/assets/11753634/df35ffa4-7f8b-4a98-a0cb-d6fbcf587eb7)

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/19ea4b10-41bb-4088-a715-431a4551201e)

I was a bit unsure of this one as I didn't expect this GO term to be a cellular component. I usually associate CC annotations with microscopically protein location data rather than protein-protein interaction data as in this case. Upon looking it up, it is indeed a cellular component term https://www.ebi.ac.uk/QuickGO/term/GO:1990334

So I guess it is fine.

The physical interaction annotations could be added in the future once the other 2 proteins bub2 and bfa1 have been added to the session for curation.

**Comment by CuzickA** [comment]
I was about to make GO CC to 'spindle pole body' 

![image](https://github.com/PHI-base/curation/assets/11753634/1757fd81-821b-499b-a037-2458e6a5f65e)

and saw that this was a parent term of 
![image](https://github.com/PHI-base/curation/assets/11753634/2f7fe14d-36e2-4937-8caa-69684f2c6ec7)

So all looks good. I am just going to add Fig 2F

![image](https://github.com/PHI-base/curation/assets/11753634/0146b46a-c1a7-445e-ac68-1b9a6823c996)

**Comment by CuzickA** [comment]
Next steps for this session

1) make 2 NTRs__done 03_08_2024, waiting for loading into PHI-Canto_ DONE
2) request JS to enable AE severity for these NTRs DONE
3) feedback to Victoria _-email sent 21_05_2024_
How to make NTRs
Disease annotation
Reactivated session for in vitro veg growth and conidia expt Fig1
4) note for future, when Bfa1 and Bub2 are entered for curation, further GO annotations and Physical interaction annotations can be made.

**Comment by jseager7** [comment]
I've added the has_severity extension to 'abnormal asexual spore morphology' (PHIPO:0000127) which is the parent term of the new terms, and made a PHIPO release containing the new terms.

**Comment by CuzickA** [comment]
Terms and AE added. 

Approving session and closing ticket.

Ticket can be re-opened in the future if further annotations are planned.
