### ISSUE TITLE
PMID:22241993 The cysteine rich necrotrophic effector SnTox1 produced by Stagonospora nodorum triggers susceptibility of wheat lines harboring Snn1. 

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#22]
Link to curation session
http://canto.phi-base.org/curs/bd02fdb6831712ca

Stagonospora nodorum is a necrotrophic fungal pathogen producing host selective toxins/necrotrophic effectors.

In virulent/susceptible interaction pathogen SnTox1 interacts with host susceptibility target Wheat Snn1 to promote host necrosis (host programmed cell death, necrotrophs feed on dead matter) and disease. This is effector-triggered susceptibility (in contrast to effector-triggered immunity PCD/HR against biotrophs).

In an avirulent/resistant interaction there is no necrosis/disease.

Links to GO tickets
https://github.com/geneontology/go-ontology/issues/17243

**Comment by CuzickA** [comment]
Difficult to know which UniProt id to use for wheat host gene Snn1 (no gene id given in paper). 
Search in UniProt for 'snn1 wheat' gives below
![image](https://user-images.githubusercontent.com/11753634/56739124-ec942380-6765-11e9-8e3f-22be97b8a169.png)
All entries are unreviewed. Wheat is hexaploid -are these different entries from different genomes (to investigate?). For now I am just using the top entry.

**Comment by CuzickA** [comment]
phipo NTR link https://github.com/PHI-base/phipo/issues/50

**Comment by ValWood** [comment]
the solution to the missing entry can be used to complete this ticket
https://github.com/PHI-base/curation/issues/14

I suspect the only way is to get the author to submit to  retrospectively submit the public databases (or confirm the ID). It's odd that they can publish a paper withouut an accession number though so it might also be worth contacting the journal to tighten up their policy here.

There is a "reference  proteome" for what though so we should use the reference proteome entry maybe. But oddly I don't find anything  at all when I search uniprot for snn1?
How did you locate the 4 above?

**Comment by ValWood** [comment]
OK found them. They are all the same length it is possible they are idenitcal in sequence. I think the one you selected will be OK, because its an older ID.  It makes sense to select the oldest entry as I think this is the one that the others will merge into.

**Comment by ValWood** [comment]
Damn it they are different.  There are 3/5 with a  V->I 43 and R-G 347

**Comment by CuzickA** [comment]
I have chosen the top uniprot id W5AB81 as it maps out to EnsemblPlants with the latest wheat gene id.
![image](https://user-images.githubusercontent.com/11753634/57130846-cc321d80-6d92-11e9-9f36-7f8ad84cb662.png)
I have chatted this through with Mike HK who works with wheat.
I was concerned that we had the correct homeologue uniprot id as wheat has genomes A, B and D. It looks like we do in this case as the gene is located on Chr1 B genome which corresponds to the host genotype CS 1BS-18 (Snn1 deletion) that I was curating.

**Comment by ValWood** [comment]
I notice text says CS 1BS-18 and CS ems237 are nearly identical to CS, but harbor mutations at the Snn1 locus, resulting in insensitivity to SnTox1.

so presumably the exact genotype is known? Currently reported a "unknown"

**Comment by ValWood** [comment]
It worries my slightly to describe the phenotype as "normal pathogen host interaction phenotype"

I see though, that  you are requestiion a more specific term

normal absence of host necrosis with pathogen.

Remind me why does it need to be described as "normal" (which is context dependent)

why not just "absence of  host necrosis with pathogen"?

**Comment by CuzickA** [comment]
@ValWood Looking through the annotations I have made for this paper I realise that I still have an unresolved query that we haven't discussed yet.
When recording a wild type control metagenotype for a wt pathogen gene (Tox1) and a wt host gene (Snn1) is it better to specify both of these as wt alleles eg 1
![image](https://user-images.githubusercontent.com/11753634/57696165-0e3b4900-7648-11e9-915b-0b471af9521c.png)

or just the pathogen gene (Tox1) as wt and the host species as no gene selected?
eg 2
![image](https://user-images.githubusercontent.com/11753634/57696243-362aac80-7648-11e9-8ace-bf470f04e4bb.png)

I think eg 1 is more informative as it indicates the host gene of interest in the study. Maybe we only use eg 2 when there are no specified host genes in the expt? We would have to make this clear to other curators.

**Comment by CuzickA** [comment]
Under metagenotype management I have 2 entries for pathogen genotypes which appear to be the same Tox1+(presence unknown) strain Sn79-1087. One of these has a GFP tag entered in the background which is not visible on this page. This a bit confusing and may also make it difficult to select the correct pathogen allele for the metagenotype. Should background be visible as a pop up?
![image](https://user-images.githubusercontent.com/11753634/57696974-0f6d7580-764a-11e9-8388-e107835b1ec3.png)

**Comment by ValWood** [comment]
For PomBase these show in an additional column. Does this need activating?

![backgrouund](https://user-images.githubusercontent.com/7359272/57709565-35ebda80-7663-11e9-88c9-be02cb718308.jpg)

**Comment by ValWood** [comment]
> I think eg 1 is more informative as it indicates the host gene of interest in the study

I agree.

**Comment by kimrutherford** [comment]
> For PomBase these show in an additional column. Does this need activating?

On the genotype management page the background column will be shown if any genotypes have a background.  It looks like that's not the case on the metagenotype page.  I've made an issue about it: https://github.com/pombase/canto/issues/1873

**Comment by CuzickA** [comment]
@ValWood a necrotrophic effector paper for checking.

There may be some host defense gene expression data that could be annotated in Fig 10 which I haven't done yet.

**Comment by ValWood** [comment]
Actions still to complete for this session
 - [ ] https://www.uniprot.org/uniprot/A9JX75
has a name/product update been requested?
When we do this we should  let them know  that we are doing the GO curation too.

- [ ] submit to Pfam/panther A BlastP search of the NCBI non-redundant database with the SnTox1 protein sequence as a query led to the identification of three putative proteins with unknown functions, one from S. nodorum (SNOG_06487) and two from P. tritici-repentis (PTRT_04748 and PTRT_03544) with similarities of 38%, 56%, and 43%, respectively. The conserved amino acids between SnTox1 and these proteins were mostly distributed in the predicted signal sequence and the N-terminal region of the mature protein (Figure S3)......
Amino acid alignment with manual adjustment indicated that SnTox1 contained local similarity with cysteine-rich Cladosporium fulvum Avr4-like fungal effectors (Figure 3A) from Cercospora beticola, Mycosphaerella fijiensis [42] and two ascomycete human pathogens, Microsporum gypseum and Geomyces pannorum (this study). These conserved motifs were identified within the chitin-binding domain (ChtBD) including the C-terminal conserved chitin-binding (CB) motif (Figure 3A)....was more similar to those of plant-specific ChtBDs (ChtBD1, or CBM18 superfamily, pfam00187) than to Avr4 proteins, which are related to invertebrate ChtBDs (ChBD2, or the CBM14 superfamily, pfam01607) .....consistent with strong diversifying selection. The 11 protein isoforms involve amino acid changes at eight positions within SnTox1; however, all cysteine residues remain unchanged across all isoforms (Figure 2D).

(I may have already done ths?)

**Comment by ValWood** [comment]
Tox1+(transformant, no endogenous copy)[Unknown]

is now
Tox1-(transformant, no endogenous copy)[Unknown]

if ther is no endogenous copy we should use "-" notation instead of +
I don't know why I did not think of this before. I remember we were racking our brains how to do these. I think there was way to much to think about back then ;)

**Comment by ValWood** [comment]
I don't see a difference between row 1 and row 4 here:

<img width="1234" alt="Screenshot 2019-10-23 at 08 51 46" src="https://user-images.githubusercontent.com/7359272/67370396-79cbff80-f572-11e9-8bc0-8bdf7b6f7516.png">

for 2 experiments showing the same thing we should just capture once and add figure 5 a/b

makes the curation easier to consume.

Plaase confirm.

**Comment by ValWood** [comment]
I'm sure they are the same thing. I will merge.

**Comment by ValWood** [comment]
I'm struggling with the
 loss of virulence of gain of pathogenicity mutant
why don't we just use "loss of pathogenicty" for this? I can't remember?

Also can we have a ticket wit the names and definitions of all of the infective ability terms(I think they are somewhere on the tracker but a list on the curation tracker would . be useful)

**Comment by ValWood** [comment]
This is because we are comparing to 

Sn2000-Tox1ASn79+SnTox1A3(transformant, no endogenous copy)[Not assayed]Parastagonospora nodorum (Sn79-1087) | Snn1+[Wild type product level]Triticum aestivum (Chinese Spring)
-- | --



rather than the WT contriol.

but this isn't implicit from the annotation.

This really makes me think we definitey need to implement

https://github.com/PHI-base/curation/issues/19
I now think we really need to have an additional field for the loss or gain of function phenotypes. We need to capture which genotype we are comparing to otherwise it is too difficult to understand the annotation (sigh). We can chat about this on our next group call?

I have beed adding the  [allele]  compared to in the sessions I have been checking. Mostly it is the [WT/WT]

I know the the MPO do something similar to this.

**Comment by CuzickA** [comment]
help #172822 Just emailed uniprot about adding Tox1 as gene name.

>  https://www.uniprot.org/uniprot/A9JX75
has a name/product update been requested?

**Comment by CuzickA** [comment]
> for 2 experiments showing the same thing we should just capture once and add figure 5 a/b

The authors did the expts slightly differently in Fig 5a and b.
In 5a they used pathogen culture filtrates infiltrated into the leaf, whereas in 5b they inoculated pathogen spores onto the leaf. I think the main difference here is that the infiltration forces the Tox1 protein (or other proteins in the filtrate if Tox1-) into the leaf (with some damage where the infiltration syringe head pushes against the leaf) and the spore inoculation enables the pathogen spore to germinate on the leaf surface, enter the leaf normally (eg maybe through the stomata??) and deliver Tox1 in the normal manner.

The authors also describe the phenotypes a bit differently. culture filtrates causing or not causing necrosis and spore inoculations causing or not causing disease (lesions).

I'm not sure if they should be combined or kept separate?

**Comment by CuzickA** [comment]
help #172822 uniprot request done

Hi Alayne,

Thank you for your request. Entry A9JX75 is still found in the TrEMBL section of UniProtKB. TrEMBL is the automatically annotated section that is not reviewed, and the information found in this entry stems from the original submission to the EMBL database. Following your suggestion I've updated this entry. When updating entries from TrEMBL, we do complete updates, not only adding a name or experimental data from a specific article, this is why it might take some time. Please find attached an internal version of the updated entry. The modifications will be publicly available at the UniProt release around the 11-DEC-2019 (Release 2019_11).

I realized that there are several other Toxins (ToxA and Tox2-6) encoded by  this fungus. I will check if the corresponding genes have been identified to update those entries as well.

This UniProt ID corresponds to strain SN15 / ATCC MYA-4574 / FGSC 10173 which is indeed to the Reference proteome. The entry contains the "reference proteome" Keyword, the UniProt taxonomic code PHANO, as well as the ORFName corresponding to the whole genome sequence (in this case SNOG_20078).

If you have any further comments, suggestions or questions regarding the annotation, please do not hesitate to contact me.

Best regards,
Marc

**Comment by ValWood** [comment]
I checked this one. Looks good. As we discussed it's a LOT of annotation.
These will take a long time to curate and check.

So we need to figure which curation is of most use to the users.

**Comment by ValWood** [comment]
I wouldn't use this one as an example....

**Comment by CuzickA** [comment]
@ValWood does this need follow up?
![image](https://user-images.githubusercontent.com/11753634/85133998-ae907380-b233-11ea-83e7-fb220eb63cf9.png)

**Comment by CuzickA** [comment]
2 pathogen delivery methods used here
- pathogen spore inoculation 
- infiltration of culture filtrate
![image](https://user-images.githubusercontent.com/11753634/85136395-78ed8980-b237-11ea-87d7-8d2c6bcc78e5.png)
Need to think about conditions. Fig 5 a and b annotations have been combined to reduce the number of overall annotations, however different delivery mechanisms have been used.

**Comment by CuzickA** [comment]
We decided that Fig 5a (culture infiltration) and b (conidia inoculation) needed to be made as separate annotations each with their corresponding condition.
A new condition term was made 'culture infiltration delivery system'.
![image](https://user-images.githubusercontent.com/11753634/85556218-8b443a80-b61e-11ea-9e93-9f0b44150ee2.png)

**Comment by CuzickA** [comment]
Recording these annotation queries and answers here so that I can delete from the session.

query should infective ability/gene-for-gene info be recorded for the 'culture infiltration expt' or just the 'pathogen spore inoculation expt'? YES record for both

'host resistance absent' might need a synonym 'host susceptibility present' -YES make a ticket and do this (also for other host terms AE infective ability terms).  https://github.com/PHI-base/phipo/issues/263

**Comment by CuzickA** [comment]
Added new information for AEs
gene-for-gene interaction compatible or incompatible
infective ability for pathogen (pathogenicity present/absent etc) and host (resistance present/absent etc)

Above may need further consideration.
Session needs 'compared to X'
Closing ticket and approving session for now.

**Comment by CuzickA** [comment]
AE 'Compared to control' now added and session re-approved

**Comment by ValWood** [comment]
is this correct?

<img width="968" alt="Screen Shot 2020-07-31 at 17 12 04" src="https://user-images.githubusercontent.com/7359272/89054701-2a143300-d351-11ea-94fe-ace90b97776a.png">


~should this be compatible?~  gain of pathogenicity look wrong?

**Comment by CuzickA** [comment]
> gain of pathogenicity look wrong?

I used this because the 'raw ingredients' of the pathogen genotype component reflect a 'gain of pathogenicity' the pathogen was pathogenicity absent->addition of pathogenicity gene.

The overall outcome of the individual components of the metagenotype (pathogen genotype and host genotype) are captured in the 'gene-for-gene interaction' AE either compatible/susceptible or incompatible/resistant.

Its a bit tricky to explain! I was trying to separate the individual genotype component 'infective ability potential' from the overall outcome.

**Comment by ValWood** [comment]
yes I  think this still isn't clear. I'm still getting confused between 'potential" and "outcome"

**Comment by ValWood** [comment]
Are all terms related to "infective ability'  only used in one context or the other?

**Comment by CuzickA** [comment]
This session needs updating by
-adding fig info to Fig column
-adding 'nv' or 'ev', 'WT-ref' or 'WT-other' for both pathogen and host genotypes to comment box
-checking new gene-for-gene AE infective ability term usage

Reference strains
![image](https://user-images.githubusercontent.com/11753634/95331341-c6067180-08a1-11eb-9401-9818e672a631.png)
![image](https://user-images.githubusercontent.com/11753634/95331556-1382de80-08a2-11eb-9481-2125a29af1e2.png)

**Comment by CuzickA** [comment]
Above changes made.
Next: check with VW and KHK that new AE terms make sense for inverse gene-for-gene (necrotrophic effector)

**Comment by CuzickA** [comment]
Whilst think about the new g-f-g compound term development I have just added new control annotations for Fig 12 and Fig 14 where expt comparing normal light vs continuous dark. 
I have flagged up queries about g-f-g extension use in these annotations. eg use of 'gain of functional effector' may be incorrect as comparison is between the same metagenotype with or without light and 'functional effector present' may be better. Needs further thought.

Also to note there may be other control annotations to make still in this session.

**Comment by CuzickA** [comment]
Added this 'qualitative RNA level' to check
![image](https://user-images.githubusercontent.com/11753634/101186207-acd43400-364a-11eb-83d9-cd5750560ace.png)

**Comment by CuzickA** [comment]
Updated gene-for-gene AE now added and waiting for review.

**Comment by CuzickA** [comment]
I have added new inverse GfG AE for necrotrophic effector

- waiting for two more inverse GfG NTRs

@ValWood please could you check though session
particularly Expt 10 where I have tried to capture RNA level information both as WT RNA level and as PHIPO annotations
and also whether the tricky annotations where the metagenotypes are the same but the condition is different eg light/dark resulting in a different phenotype
Thanks

**Comment by CuzickA** [comment]
I have manually transferred AE GfG to AE inverse GfG
and update the new assayed_using AE

Still need one more NTR AE inverse GfG 'incompatible interaction, compromised recognizable pathogen necrotrophic effector, host susceptibility locus present'

**Comment by CuzickA** [comment]
Added final NTR AE inverse GfG 'incompatible interaction, compromised recognizable pathogen necrotrophic effector, host susceptibility locus present'

Session ready for checking and queries

> particularly Expt 10 where I have tried to capture RNA level information both as WT RNA level and as PHIPO annotations
and also whether the tricky annotations where the metagenotypes are the same but the condition is different eg light/dark resulting in a different phenotype

**Comment by CuzickA** [comment]
Manually removed AE causes_disease and added disease name curation type
Note: lot of synonyms for this disease - I will make a note on the PHIDO tracker see https://github.com/PHI-base/phido/issues/3
![image](https://user-images.githubusercontent.com/11753634/107657077-b5fe0480-6c7c-11eb-90f9-d01b8fe085ed.png)

**Comment by CuzickA** [comment]
RNA level curation now looks like this

![image](https://user-images.githubusercontent.com/11753634/110932752-cc52bb00-8323-11eb-839f-9185be7a0f21.png)
![image](https://user-images.githubusercontent.com/11753634/110932821-e42a3f00-8323-11eb-8778-14d23fa8787e.png)

**Comment by CuzickA** [comment]
Session now approved

Awaiting feedback from Kim H-K on how to annotate when condition responsible for phenotype.

**Comment by CuzickA** [comment]
Copy of email sent to Kim H-K today just for reference

Dear Kim,
I have been reviewing the inverse Gene for Gene curation sessions.
1)	There are two sessions here for you to review please
https://canto.phi-base.org/curs/bd02fdb6831712ca/ro/ Tox1 / Snn1 2012
https://canto.phi-base.org/curs/6ddeb3a009b5a0e5/ro/ Tox1 / Snn1 2016
2)	I have a question about usage of AE inverse GfG here where the ‘condition’ is responsible for the change in phenotype 
The WT metagenotypes are both the same. 
Under normal light exposure (top annotation of 1st screen shot) the interaction is compatible and in continuous dark (bottom annotation of 1st screen shot) the interaction is incompatible. In the latter case what do you think the correct AE inverse GfG would be? It doesn’t really make sense as it is with incompatible, present, present.
 
![image](https://user-images.githubusercontent.com/11753634/110938659-1b9ce980-832c-11eb-9231-018c4e9fac5c.png)

Also an issue for altered pathogen genotype within metagenotype
 
![image](https://user-images.githubusercontent.com/11753634/110938703-2d7e8c80-832c-11eb-96e0-af5ce388f83c.png)

And for Fig 14 looking at penetration phenotype in light/ dark condition

 
![image](https://user-images.githubusercontent.com/11753634/110938729-37a08b00-832c-11eb-8e35-557d8c50ee22.png)

and for Fig 8 looking at adding condition + dithiothreitol and changing temp.
 
![image](https://user-images.githubusercontent.com/11753634/110938743-3d966c00-832c-11eb-9438-6508213e035a.png)

3)	I have attached the most recent version of the Help documentation for the GfG curation. The first section is for biotrophs and the second for necrotrophs.

Please let me know what you think once you have had time to review my earlier biotroph GfG emails and this necrotroph inverse GfG email. 

Have a nice weekend
Best wishes,
Alayne

**Comment by ValWood** [comment]
Looks good.

**Comment by CuzickA** [comment]
After discussion with Kim H-K on 25March2021 regarding my email query above we decided that we could not use a standard (inverse) gene-for-gene AE when the condition altered the outcome (eg heat, light, chemical). The only available options need to be logically correct for a (inverse) gene-for-gene interaction. Therefore the two options we came up with were
1) do not use an (inverse) gene-for-gene interaction - leave field empty, or
2) have a generic AE term available in both inverse GfG and GfG  such as 'metagenotype outcome overcome by external condition'

Let's discuss this today @ValWood

**Comment by CuzickA** [comment]
@ValWood agrees with option 2.

**Comment by CuzickA** [comment]
was
![image](https://user-images.githubusercontent.com/11753634/112839383-0fd45580-9096-11eb-8afc-706955c14693.png)
 remove current AE for 2nd and 4th annotation above with condition 'dark'. Obsolete these PHIPO_EXT terms as they are logically incorrect. (incompatible interaction, recognizable pathogen necrotrophic effector present, host susceptibility locus present AND incompatible interaction, gain of recognizable pathogen necrotrophic effector, host susceptibility locus present)


now (waiting for NTR)
![image](https://user-images.githubusercontent.com/11753634/112840501-51b1cb80-9097-11eb-9db5-e6b41004a420.png)

was
![image](https://user-images.githubusercontent.com/11753634/112841563-8a05d980-9098-11eb-810d-dc0ee0bd62c9.png)
remove current AE for 2nd annotation with condition 'dark'

now (waiting for NTR)
![image](https://user-images.githubusercontent.com/11753634/112841877-ebc64380-9098-11eb-9929-f7f2d4371803.png)

was
![image](https://user-images.githubusercontent.com/11753634/112842739-c84fc880-9099-11eb-9317-1d9458642626.png)
remove current AE for 2nd and 4th annotation with conditions causing shift

now (waiting for NTR)
![image](https://user-images.githubusercontent.com/11753634/112843357-65aafc80-909a-11eb-9ec7-e2bd3413d882.png)

**Comment by CuzickA** [comment]
Add new AE term 'metagenotype outcome overcome by external condition' after Easter

**Comment by CuzickA** [comment]
Added new AE term 'metagenotype outcome overcome by external condition'

Approved session and closing ticket

**Comment by CuzickA** [comment]
Following up query on incorrect term 
inverse_gene_for_gene compatible interaction, compromised recognizable pathogen necrotrophic effector, host susceptibility locus present

Copy of email sent to Kim H-K
![image](https://user-images.githubusercontent.com/11753634/167806739-8d665167-609b-4820-8b3c-bd25401bc8b5.png)
![image](https://user-images.githubusercontent.com/11753634/167806830-ed60124d-d219-4652-9f8f-2d611ca925cd.png)


Kim H-K agrees with my proposed change.

annotation now updated to
![image](https://user-images.githubusercontent.com/11753634/167807173-538ee7b7-3db3-4e4e-9358-2541a0ed1605.png)

The PHIPO_EXT term will be obsoleted
inverse_gene_for_gene compatible interaction, compromised recognizable pathogen necrotrophic effector, host susceptibility locus present

**Comment by CuzickA** [comment]
I need to update the 'transformant' genotypes following the new guidance in #157

**Comment by CuzickA** [comment]
Session now 'unapproved' until  'transformant' genotypes updated.

**Comment by CuzickA** [comment]
'transformant' genotypes updated. Session approved. Closing ticket.
