### ISSUE TITLE
PMID: 29020037 A conserved fungal glycosyltransferase facilitates pathogenesis of plants by enabling hyphal growth on solid surfaces.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#24]
Link to curation session
http://canto.phi-base.org/curs/8149debd202f2e6e

**Comment by CuzickA** [comment]
How best to capture allele information for pathogen Z. tritici mutant '23-170'  a T-DNA insertion within GT2 gene?
@ValWood Does this seem reasonable?

![image](https://user-images.githubusercontent.com/11753634/58960811-d08d9400-879f-11e9-8930-16964e721ecb.png)

**Comment by ValWood** [comment]
Yes that looks good. Disruption is the important point, we don't worry so much about standarddizing

yeast uses

yfg1::ymg1+ (where ymg = your marker gene)

syntax
Is this not used in pathogens. If different syntax is used we can configure the prompts accordingly.

**Comment by CuzickA** [comment]
Thanks @ValWood 
I have come across that problem with UniProt not having a helpful 'gene name'.
When making a quick deletion the allele is automatically called 'F9WWD1_ZYMTIdelta'
![image](https://user-images.githubusercontent.com/11753634/59019652-5cef9380-8840-11e9-949c-fb9b39f79246.png)
Do I need to go into the edit details options and manually overide this to rename allele to 'GT2delta'?

The same issue for the F.gram GT2 deletion
![image](https://user-images.githubusercontent.com/11753634/59019815-9e803e80-8840-11e9-93ed-441b87dd9ed4.png)

**Comment by ValWood** [comment]
yes, I think we can over-ride that, but we need to check with @kimrutherford 

Did you report the name update to UniProt also?

**Comment by CuzickA** [comment]
[help #167090] [uuw] UniProtKB entry update request
Name update request sent to UniProt

**Comment by CuzickA** [comment]
Another session to add to the checking list thanks @ValWood

**Comment by CuzickA** [comment]
UniProt help #167090 still waiting on this from the beginning of June. Sent a reminder email today.

**Comment by CuzickA** [comment]
Marc has now done this

> I've updated both entries with experimental data and names from PMID: 
29020037

> However, the modifications will only  be publicly available at the UniProt release around the 11-DEC-2019 (Release 2019_11).

**Comment by ValWood** [comment]
~This one is fine.
I'm not sure about
GO:0075201 | formation of symbiont penetration hypha for entry into host
for GO, might be a little indirect. We can discuss, I'm not sure which EXP you are using. 
_penetration hypha formation now related synonym_~


I'm also not sure about you query re pathogenicity/vs  virulence. This still confuses me
Maybe ask Kim about this one?
_Difficult as both are used for same expt in fig 1 and 2. we have reported both outcomes._

(I left these annotation unchecked)

**Comment by CuzickA** [comment]
Still left to do for this session
1) DONE_UniProt gene names still not updated when checked on 18_12_19. When these updates are released at UniProt will they automatically be visible in PHI-Canto? _They do not update automatically 14_01_2020_ Now done
2) DONE_consider idea of grouping media into rich, minimal or water #63 _still to be done for media in PHI-ECO_ _done 20_01_2020_
3) are new 'decreased size of colony' terms clear enough for filamentous growth vs yeast-like? _add back child for 'decreased filamentous'_
4) DONE_a couple of queries within the curation session to discuss _note different phenotypes seen for Zt GT t-dna mutant in Fig 1 and 2, resulting in reduced virulence and loss of path._
5) DONE_identify key expts for Tier 1 training video _Fig1H and Fig1Q/R_

**Comment by CuzickA** [comment]
> I'm not sure about
GO:0075201 | formation of symbiont penetration hypha for entry into host
for GO, might be a little indirect. We can discuss, I'm not sure which EXP you are using.

Fig. 1 O and P, surface growth on leaf
Here is the associated text. Let me know what you think @ValWood 
'These data suggested that the mutation(s) present in 23–170 rendered it incapable of normally extending hyphae when in contact with a solid surface. Significantly, this phenotype was supported by wheat leaf infection data. In contrast to the WT strain which could rapidly elaborate hyphal filaments on the surfaces of wheat leaves (Fig 1O) and subsequently cause full disease (Fig 1Q), the 23–170 mutant displayed no clear hyphal growth on leaf surfaces (Fig 1P). This resulted in a dramatic loss of disease causing ability (Fig 1R). '

**Comment by ValWood** [comment]
This does sound OK, although I'm struggling to see the difference between this term and

GO:0075061    JSON
invasive hyphal growth
Biological Process

Definition (GO:0075061 GONUTS page)
The assembly by the symbiont of a threadlike, tubular structure, which may contain multiple nuclei and may or may not be divided internally by septa or cross-walls, for the purpose of invasive growth within its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

(I will ask GO about that)

**Comment by CuzickA** [comment]
I think 'GO:0075201 formation of symbiont penetration hypha for entry into host' is for the formation of the host surface hyphae penetrating the stomata whereas 'GO:0075061invasive hyphal growth' is the hyphal growth within the host after it has penetrated the stomata.

**Comment by CuzickA** [comment]
Gene name updates now made in UniProt

![image](https://user-images.githubusercontent.com/11753634/72342871-6fc72200-36c5-11ea-963e-11fb70c66d5b.png)
![image](https://user-images.githubusercontent.com/11753634/72342916-8a010000-36c5-11ea-982c-a99821860ae3.png)

**Comment by CuzickA** [comment]
These recently update gene names have not automatically updated in PHI-Canto.
Do we have a fix for this rather than trying to make the changes manually? @jseager7 
https://github.com/pombase/canto/issues/2107

**Comment by jseager7** [comment]
I've tried running the script to clear the gene cache on the main server, but it doesn't seem to have had any visible effect yet. I'll check back later, but it's possible that the script doesn't affect submitted sessions, or it just doesn't work at all at the moment.

**Comment by CuzickA** [comment]
> I've tried running the script to clear the gene cache on the main server, but it doesn't seem to have had any visible effect yet. I'll check back later, but it's possible that the script doesn't affect submitted sessions, or it just doesn't work at all at the moment.

This worked, it just took some time to be visible in PHI-Canto.

**Comment by ValWood** [comment]
GO:0075201 | formation of symbiont penetration hypha for entry into host
is now
GO:0075201    penetration hypha formation

-- | --
symbiont penetration hypha formation for entry into host | related
formation of symbiont penetration hypha for entry into host | related

I will ask if this term should be related to "GO:0075061  invasive hyphal growth"

But the annotation is OK

**Comment by ValWood** [comment]
![ppat 1006672 s006 (1)](https://user-images.githubusercontent.com/7359272/75672351-7fe89000-5c78-11ea-8e5c-9bad1d62e43f.png)

**Comment by ValWood** [comment]
Penetration of cellophane membranes by F. graminearum strains. Fungal spores were plated and grown for 2 d at 22°C on top of cellophane membrane on the surface of PDA plates (images labelled “Before”). The cellophane with the fungal colonies was removed and plates were incubated for an additional two days to determine whether fungal growth occurred on the plates, indicating penetration of the cellophane disk (images labelled “After”). The ΔFgMAP1 mutant strain was used as a control strain shown previously to be defective in cellophane and plant penetration [64].

_added FgGT2 deletion invitro penetration assay annotation_

**Comment by CuzickA** [comment]
To do -add back 'decreased size of filamentous colony' as child of 'decreased size of colony'

**Comment by ValWood** [comment]
See 
https://github.com/geneontology/go-ontology/issues/19013
for discussion on invasive growth

**Comment by CuzickA** [comment]
> To do -add back 'decreased size of filamentous colony' as child of 'decreased size of colony'

Now done.

This would be a good video training example using annotations
![image](https://user-images.githubusercontent.com/11753634/76320279-5e228500-62d8-11ea-83bd-1598d5d4c8c9.png)
![image](https://user-images.githubusercontent.com/11753634/76320321-6c70a100-62d8-11ea-889c-6f24bfcabf17.png)

maybe also
![image](https://user-images.githubusercontent.com/11753634/76422867-d010d200-639d-11ea-8081-4a926dd7e5a4.png)



I wanted to approve this session but PHI-Canto will not allow me to do this as there are 'conditions' that are not yet in PHI-ECO.

**Comment by CuzickA** [comment]
changed temp conditions to those currently in PHI-ECO
16C to low temp
25C to standard temp

added dpi terms to PHI-ECO waiting for these to load into PHI-Canto

**Comment by CuzickA** [comment]
Conditions updated.
Session now approved.

**Comment by CuzickA** [comment]
Reopening as need to
1) add AE disease outcome
2) add WT control metagenotype annotations

**Comment by CuzickA** [comment]
I have now added 1) and 2) to the session. It would be good to review this with @ValWood 

For now I have only added the AE disease outcome to the WT control metagenotype annotations. I'm not sure about adding it to the altered metagenotypes - to discuss.

https://github.com/PHI-base/curation/issues/81

**Comment by CuzickA** [comment]
Closing for now. Discussion about where to use AE disease outcome can take place in ticket #81

**Comment by CuzickA** [comment]
Check and reannotate new hyphal growth/unicellular growth terms as required.
this session is required for lab meeting slides, demo and publication table.

**Comment by CuzickA** [comment]
Updates to session made. 
@ValWood please could you have a quick look through the session again now that we have restructured our unicellular and hyphal growth terms

**Comment by CuzickA** [comment]
Lab meeting live Demo plan
Use ZtGT2-19 (deletion) instead of t-dna insertion as easier to make for live demo and host phenotype clearer Fig2E.
![image](https://user-images.githubusercontent.com/11753634/101478783-1dc86400-3949-11eb-8a3a-b3933289d29b.png)
pathogen phenotype
![image](https://user-images.githubusercontent.com/11753634/101477354-04beb380-3947-11eb-82d4-8dd1237879bc.png)

control metagenotype
![image](https://user-images.githubusercontent.com/11753634/101478521-b6aaaf80-3948-11eb-99be-765b90778ad2.png)
altered metagenotype (minus comment)
![image](https://user-images.githubusercontent.com/11753634/101478609-d80b9b80-3948-11eb-8a87-9a131662b8c5.png)




GO at end, cannot use the GO MF term annotation for this paper as evidence is TAS which is Admin only
![image](https://user-images.githubusercontent.com/11753634/101476685-0c318d00-3946-11eb-8240-5356a2836781.png)

**Comment by ValWood** [comment]
I think this looks great. 
Curation of similar papers will make it clearer whether we have sufficient comments to make it clear why the terms are represented slightly differently. Although I think this will be largely hidden from users. Reading through this the term labels read closely to what I think users will search for, so I think this is all good.
v

**Comment by CuzickA** [comment]
> I think this looks great.
> Curation of similar papers will make it clearer whether we have sufficient comments to make it clear why the terms are represented slightly differently. Although I think this will be largely hidden from users. Reading through this the term labels read closely to what I think users will search for, so I think this is all good.
> v

Great news! Thanks for checking it again @ValWood :-)

**Comment by CuzickA** [comment]
Manually remove AE causes-disease and added new disease name curation type
![image](https://user-images.githubusercontent.com/11753634/107754235-19d60b00-6d19-11eb-8fb7-5578c27ae3f4.png)

**Comment by CuzickA** [comment]
I was just looking at this session for mocking up a curation example and noticed the discrepancies in the deletion mutant alleles.

![image](https://user-images.githubusercontent.com/11753634/204804619-6446c5b7-7599-4746-9bc0-4a117972dd60.png)

I was thinking that the genotype Zt ΔGT2-19(deletion) should just be named GT2delta and noticed that there are some formatting differences between this and the FgGT2delta genotype. The Delta is is a different position and the 'deletion' is shown in brackets. I'm guessing there was some flux in PHI-Canto at this time. @jseager7 any ideas?

Now that I've spotted it it should probably be corrected. Unfortunately this means that the screenshots in the S materials of the PHI-Canto manuscript would not correspond to these changes.

**Comment by jseager7** [comment]
> The Delta is is a different position and the 'deletion' is shown in brackets. I'm guessing there was some flux in PHI-Canto at this time.

PHI-Canto automatically appends the delta character to the gene name from the UniProtKB accession when you make a deletion allele (assuming you don't specify your own name). I've checked the session on my local copy and it looks like the GT2-19 allele has a name manually specified:

![image](https://user-images.githubusercontent.com/37659591/204807285-6b9a07d8-5567-4785-be09-628f9443f96b.png)

This is probably because an automatically generated name wouldn't have included the "-19" suffix.

> Unfortunately this means that the screenshots in the S materials of the PHI-Canto manuscript would not correspond to these changes.

I don't think that's a problem unless ΔGT2-19 is somehow inaccurate (meaning a different type of deletion from ΔGT2).

**Comment by CuzickA** [comment]
Thanks. 

I'm going to rename Zt ΔGT2-19(deletion) to GT2Δ. The '-19' is not required within the genotype name. This change will make the genotype names more consistent with those for Fg GT2Δ . 

![image](https://user-images.githubusercontent.com/11753634/204819126-04fd5c97-8e8c-45d9-8408-f52cfc6b62f3.png)


![image](https://user-images.githubusercontent.com/11753634/204818323-ed68cf46-5e09-4590-9100-2096e51190d6.png)

now changed to

![image](https://user-images.githubusercontent.com/11753634/204818580-c688e207-aab2-4415-9c89-9f543b426e18.png)

Session reapproved, closing ticket.
