### ISSUE TITLE
PMID:30603875 FgPEX4 is involved in development, pathogenicity, and cell wall integrity in Fusarium graminearum.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#25]
Session curation link
http://canto.phi-base.org/curs/a77305b830d58e05

The overall PHIPO slim term for deltaPEX4 is 'reduced virulence'

**Comment by CuzickA** [comment]
How best to capture a 'defect in cell wall integrity' in a pathogen only expt (single species branch) for Fig. 6c 
![image](https://user-images.githubusercontent.com/11753634/57779620-5331af00-771e-11e9-99ad-2262ab7303ec.png)

Wt and PEX4 mutant fungal hyphae grown on a plate were treated with lysozyme and driselase. After 30 mins most of the mutant cell walls were digested releasing abundant protoplasts, few protoplasts were seen in the wt.

**Comment by CuzickA** [comment]
Also need to think about 'increased accumulation of reactive oxygen species (ROS)' in pathogen only expt for Fig8c.
![image](https://user-images.githubusercontent.com/11753634/57780434-28e0f100-7720-11e9-8832-f5432a424638.png)

**Comment by ValWood** [comment]
we use cell lysis for this

cell lysis (FYPO:0002488)
Definition | Parents
-- | --
An inviable phenotype in which a cell lyses, i.e. the plasma membrane ruptures and cytoplasm is lost. Note that in fission yeast cell lysis, the integrity of the cell wall is also compromised.



but is the above experiment actually a phenotype, or is it just a way to produce protoplasts?

**Comment by ValWood** [comment]
tag

**Comment by ValWood** [comment]
define with
https://www.ebi.ac.uk/QuickGO/term/GO:0071554

**Comment by CuzickA** [comment]
Just going back to this curation session and re-curating metagenotypes with new AE 'infective ability'. 

This involves removing 'reduced virulence' from the main annotation, adding it to the AE, and then selecting a main phenotype term to describe what is seen to indicate that there is reduced virulence.

Currently I have
1)
The corn silk expt which is fairly straight forward as the authors have measured lesion length
![image](https://user-images.githubusercontent.com/11753634/62452688-9b360000-b768-11e9-9c7c-db4088f2e4d9.png)


![image](https://user-images.githubusercontent.com/11753634/62452415-092df780-b768-11e9-85a4-9b5162decb9c.png)



2)
However, for the wheat ear expt it is slightly less clear as to which 'observable phenotype' to use to indicate 'reduced virulence'. 

The pathogen is inoculated into one spiklet in the wheat ear and the disease spread through the ear is recorded. This is a common expt. so I think it is worth spending some time on selecting/creating the correct terms here. The current available term I've selected below 'decreased size of pathogen-associated host lesion' doesn't seem quite right.


![image](https://user-images.githubusercontent.com/11753634/62453170-ab021400-b769-11e9-8989-5fa2004e383b.png)

![image](https://user-images.githubusercontent.com/11753634/62453122-958cea00-b769-11e9-964f-46e644ad222e.png)

The authors mention the 'spread of typical scab symptoms'. 
These symptoms could be recorded as either 'bleaching' or 'necrosis' or perhaps we need to add a more general term under 'disease symptoms'? We currently don't have a phenotype term to describe 'spread of disease symptoms in the host (wheat ear) from the point of inoculation'. 

![image](https://user-images.githubusercontent.com/11753634/62453682-bace2800-b76a-11e9-837b-241a4546d325.png)

Although we do have 
![image](https://user-images.githubusercontent.com/11753634/62454626-983d0e80-b76c-11e9-8e61-3ceffcfa78cd.png)
![image](https://user-images.githubusercontent.com/11753634/62454656-a723c100-b76c-11e9-8691-41c4e51fe2f5.png)

But this also doesn't seem quite right as there may be disease symptoms seen ahead of the pathogen location.

@martin2urban @kehammond @ValWood I would appreciate any thoughts on this thanks

**Comment by CuzickA** [comment]
After today's call, Val and I have decided create a new term for 
'decreased extent of pathogen-associated lesions'
and make it a parent of decreased number.... and decreased size....
![image](https://user-images.githubusercontent.com/11753634/62464285-1822a300-b784-11e9-8057-24297a856682.png)

Same for 'increased'.

**Comment by CuzickA** [comment]
@ValWood Please could you review this session when you have time.

I still need to add NTR: 'decreased extent of pathogen-associated lesions' to phipo.

**Comment by ValWood** [comment]
I checked this one,.

My only query is

PHIPO:0000079 | normal sexual sporulation | Sexual sporulation assay | carrot medium, agar plates | vw: how can sporulation be normal based on the other phenotypes? is something missing here? | Fig S3
-- | -- | -- | -- | -- | --

I didn't check the SUPP data as this was the only supp annotation. I can look into this later.

**Comment by ValWood** [comment]
Maybe this should be normal spore morphology?
Sporulation is affected ...?

**Comment by CuzickA** [comment]
I've had another look at this thanks. and both annotations aren't quite right
![image](https://user-images.githubusercontent.com/11753634/68297427-cf35ff80-008e-11ea-84a8-c327e72743b8.png)
Top annotation should probably be
NTR:decreased number of sexual sporulation structures (or something similar) 
parent 'abnormal asexual reproductive structure development' Need NTR: for sexual here
paper text states 'less perithecium formation' (GO:0106154 perithecium formation)

Lower annotation
paper text 'normal ascospores' (normal sexual spores)
![image](https://user-images.githubusercontent.com/11753634/68297738-96e2f100-008f-11ea-8cba-0d4bf3517cd7.png)
Not sure which of the existing phipo terms to use here?
normal sexual spore morphology
normal number of sexual spores
sexual spores present

**Comment by ValWood** [comment]
I thought they referring to the spores looking normal, so I think I would go with "spore morphology"

**Comment by CuzickA** [comment]
Still to do for this curation session
1) request gene name PEX4 to be added to UniProt entry I1RRW0 (found from author FGSG_06857, not possible to find using ref proteome instructions) _request sent 03_12_19_
2) DONE decide on reduced number of conditions, can the media be grouped a complete or minimal etc _still to update media in PHI-ECO_
3)DONE update PHIPO colony size terms and decreased population growth on X carbon source when available _done 04_12_19_
4) DONE @ValWood how to curate reduced phosphorylation level of Mgv1 in deltaPEX4 mutant (Fig 6d) (also to check added GO term for Mgv1) _annotation made 04_12_19_
5) note: disease name AE not entered for Fg on corn or rice
6) note: example of metagenotype where AE infective ability is not entered.
7) choose key expt for training video

**Comment by CuzickA** [comment]
[help #177217] [uuw] UniProtKB/TrEMBL I1RRW0 entry update request
Subject:
"[uuw] UniProtKB/TrEMBL I1RRW0 entry update request"

Message:
Please add PEX4 as the gene name.

Please see literature PMID:30603875

Thank you,

The PHI-base curation team (email: curation@phi-base.org)

(The PHI-base/PHI-Canto curation team)

**Comment by ValWood** [comment]
We should have terms for 
decreased protein phosphorylation assayed_using mgv1
(follow FYPO for term def and position)

**Comment by CuzickA** [comment]
Great thanks, waiting for assayed_using to be added https://github.com/PHI-base/config/issues/30.
_Done_

**Comment by CuzickA** [comment]
Dear Alayne,

Thank you for your request. Entry I1RRW0 is still found in the TrEMBL section of UniProtKB. TrEMBL is the automatically annotated section that is not reviewed, and the information found in this entry stems from the original submission to the EMBL database. Following your suggestion I've updated this entry by adding the name (PEX4)  but also the experimental data from PMID:30603875. The modifications will be publicly available at the UniProt release around the 29-JAN-2020 (Release 2020_01).

Best regards,
Marc Feuermann

**Comment by CuzickA** [comment]
Just a few new conditions to discuss and create and a couple of annotations to double check with @ValWood

**Comment by CuzickA** [comment]
All done, session approved, closing ticket.

**Comment by CuzickA** [comment]
edit to 'size term' see https://github.com/PHI-base/phipo/issues/206
![image](https://user-images.githubusercontent.com/11753634/99077663-0352d300-25b5-11eb-90b8-b59ef05997b8.png)
to
![image](https://user-images.githubusercontent.com/11753634/99077748-21b8ce80-25b5-11eb-9784-2de4520f2f47.png)
future will see 'decreased aerial height of filamentous colony affecting colony shape' needing to change to 'decreased filament length' NOT DONE YET




![image](https://user-images.githubusercontent.com/11753634/99078057-a0ae0700-25b5-11eb-99f4-857a7d5726d4.png)
to
![image](https://user-images.githubusercontent.com/11753634/99078296-16b26e00-25b6-11eb-870b-162293bb9d22.png)

Query
how to indicate decreased here? add annotation for 'decreased filament length' although this is not mentioned? Again paper describes 'growth' and we have 'sensitive to blah' which is under population growth. To follow up with @ValWood

**Comment by CuzickA** [comment]
Added
1) AE disease outcome, control metagenotype, AE compared to control where relevant
2) Added RNA level and PHIPO annotation for Table 1

Approving session and closing ticket

Just to note @jseager7 There was no AE for assayed_using for the term 'pathogen RNA within host present' or 'decreased level of pathogen RNA within host' so I had to add as Admin text. Perhaps this is already documented in another ticket - just thought I would also record it here.

![image](https://user-images.githubusercontent.com/11753634/111795186-deea6880-88be-11eb-8641-e67b27b662b2.png)
