### ISSUE TITLE
Functional test in host 

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#26]
'Functional test in host" seems more of an experimental set up (condition) rather than the method (evidence).

This fits with the way we included "tobacco host assay" as a condition to demonstrate that the host was not used. 

So if PHIbase need the info "functional test in host"  this should be added as a condition term.

**Comment by CuzickA** [comment]
This ticket seems to have been overlooked.

@jseager7 please could you pull out any sessions using 'Functional test in host' as evidence? Thank you.

**Comment by jseager7** [comment]
@CuzickA Here's the publications using 'Functional test in host':

- [PMID:24073880](https://canto.phi-base.org/curs/84fc0e5867452a4a)
- [PMID:30220500](https://canto.phi-base.org/curs/3b2c44b436098af1)

**Comment by CuzickA** [comment]
'Functional test in host' now removed from PMID:30220500

Still to look at PMID:24073880 https://github.com/PHI-base/curation/issues/38

**Comment by CuzickA** [comment]
Also removed from PMID:24073880 #38

@jseager7 Please could you remove 'Functional test in host' from the evidence codes

**Comment by jseager7** [comment]
> Please could you remove 'Functional test in host' from the evidence codes

Sure, but I'll just have make sure it's not used in any test sessions first.

**Comment by jseager7** [comment]
I can't find this evidence code in any sessions, so I've removed it from our config file. The change will be applied when I next update PHI-Canto's servers tomorrow.

**Comment by CuzickA** [comment]
Seems to have been successfully removed thanks
Closing ticket
