### ISSUE TITLE
terms under filamentous growth

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#27]
we want to ask @mah11 about these terms when she is back.
I am getting confused but these seem as though they are about colony morphology and size rather than growth. We would like to run through them with you at some point.

![population](https://user-images.githubusercontent.com/7359272/58046870-73a6a280-7b3e-11e9-9097-5bef4f43179a.jpg)

**Comment by CuzickA** [comment]
Closing this ticket as now outdated
see 
https://github.com/PHI-base/phipo/issues/206
https://github.com/PHI-base/phipo/issues/288
https://github.com/PHI-base/phipo/issues/290
