### ISSUE TITLE
Additional papers for Val to trial curate using PHI-Canto

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#28]
@valwood You mentioned that you would like a few papers to curate from scratch in PHI-Canto that are similar to the papers we have gone through together. 

I will start collecting a few together and add them to this ticket (possibly through future ticket edits)

**Pathogen chitin-binding to mask itself from host**
PMID: 31076860 A LysM effector protein from the basidiomycete Rhizoctonia solani contributes to virulence through suppression of chitin-triggered immunity.
https://github.com/PHI-base/curation/issues/44

PMID: 30610168 Binding of the Magnaporthe oryzae Chitinase MoChia1 by a Rice Tetratricopeptide Repeat Protein Allows Free Chitin to Trigger Immune Responses.
https://github.com/PHI-base/curation/issues/42

**Biotrophic effectors**

**Necrotrophic effectors**

**Comment by ValWood** [comment]
I'm stuck at the first hurdle. I can't find the sequence. There appears to be no accession number in this paper. I tried blasting the primers against the Rhizoctonia solani genome at Ensembl and got no hits!
I don't understand how this got through review without an accession number or sequence. Am I missing something?

**Comment by CuzickA** [comment]
RSOLAG22IIIB_4067 id is in the paper results paper. I think it should be RSOLAG22IIIB_04067 which gives UniProt A0A0K6FU48 which mentions a LysM domain.

I looked up 'lysm rhizoctonia solani' in uniprot and noticed most of the genes names had 5 numberical digits instead of 4 so tried putting the missing zero in 04067 and found the above uniprot. A lot of guesswork!

**Comment by ValWood** [comment]
Ah thanks. I did not get as far as  the results. I was looking in methods and then grepping for accession, and checked the supp.
Thanks!

**Comment by ValWood** [comment]
I would never have found this.
