### ISSUE TITLE
PMID: 30044782 Small GTPase Rab7-mediated FgAtg9 trafficking is essential for autophagy-dependent development and pathogenicity in Fusarium graminearum.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#29]
curation link
https://canto.phi-base.org/curs/9133cb6f3978f78d
started curating this Journal Club paper with MU in Jan 2019

Plan to run through it again and re-curate with new terms as required

**Comment by CuzickA** [comment]
@ValWood Please could you review this session when you have time.

I still need to add 2 NTR (transport) to phipo but this may take some time.

**Comment by ValWood** [comment]
I am deleting 

GO:0030050 | vesicle transport along actin filament
(ATG9 isn't involved in transport along actin cables- it is itself transported along actin cables, so it is a target of actin mediated-transport)
We have no way top capture this....

I am removing "late endosome membrane" and "trans-Golgi network" membrane, because I think these are just "transit" locations, rather than location of the role.
I kept autosome and cacuolar membrane.

I added a bit of GO annotation, including for the GTPAse
I am also removing the 

PHIPO:0001009 | abnormal vesicle-mediated transport during vegetative growth
and

PHIPO:0001010 | normal vesicle-mediated transport during vegetative growth

(subcellular location text)

for the same reason as above,

**Comment by ValWood** [comment]
OK this one is good to go...

**Comment by CuzickA** [comment]
Still required for this session
1) AC to request UniProt gene names to be added for
![image](https://user-images.githubusercontent.com/11753634/71173808-92e3ea80-225b-11ea-869e-820f55289e62.png)
_requested gene name update for Rab7, found alternative reviewed entry for ATG8_
2) Follow up interspecies complementation progress for 
![image](https://user-images.githubusercontent.com/11753634/71173935-e6563880-225b-11ea-8057-b8de93b8789b.png)
3) reduce number of conditions? _still need to update media in PHI-ECO_

**Comment by CuzickA** [comment]
Repeat UniProt search for 'fusarium graminearum atg8' 
![image](https://user-images.githubusercontent.com/11753634/71249219-8f606a00-2314-11ea-9b2f-8a5fbd127dc6.png)
reviewed entry available -will replace previously entered UniProt B7SMQ7 / FGRA07_07972 with reviewed I1S1W5


Done, now have 
![image](https://user-images.githubusercontent.com/11753634/71250035-92f4f080-2316-11ea-8511-c818eb987b62.png)

**Comment by CuzickA** [comment]
Requested gene name update for Rab7  FGRA07_01288 / A0A2H3HA93

Subject:
"[uuw] UniProtKB/TrEMBL A0A2H3HA93 entry update request"

Message:
Please add Rab7 as the gene name.

Please see literature PMID:30044782
 
Thank you,
  
The PHI-base curation team (email: curation@phi-base.org)

(The PHI-base/PHI-Canto curation team)

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/84263053-aee38d00-ab16-11ea-8124-89131bf1dcfc.png)
In this annotation I am trying to record that the ATG9delta pathogen produces the same amount of DON as the WT pathogen when both are grown in DON inducing media.

@ValWood we obsoleted the 'synthesis' term here. 
Do you think it would be reasonable to have a single species NTR: 'normal level of deoxynivalenol'   under parent 'normal cellular toxin level' ? 
I would also need to make a new condition term such as '+ toxin inducer' as deoxynivanenol is only made in vitro with a DON inducing media (normally requires host infection to trigger pathogen DON production).

Once this is resolved I can approve this session.

**Comment by ValWood** [comment]
that "normal level of blah" sounds correct

**Comment by CuzickA** [comment]
Session approved closing ticket for now. 
Still requires interspecies complementation in the future.

**Comment by CuzickA** [comment]
I am reannotating this session. 

I have just added the 'Disease'
![image](https://user-images.githubusercontent.com/11753634/111988607-9a520d80-8b08-11eb-96c9-ae125cc85e74.png)


@jseager7 @ValWood do you think this should remain as two annotations or be combined into one annotation with two tissue types listed in the AE? eg

![image](https://user-images.githubusercontent.com/11753634/111988531-84444d00-8b08-11eb-9cb9-6ed5ecb442d9.png)

How will the future disease name mapping deal with 'fusarium ear blight' on a 'coleoptile' (The first leaf of a monocotyledon forming a protective sheath about the plumule.) rather than the wheat ear/head/inflorescence??


Perhaps, it would be best not to include the 'coleoptile' annotation at all and just record the 'inflorescence' disease for Figure 7.

**Comment by jseager7** [comment]
> do you think this should remain as two annotations or be combined into one annotation with two tissue types listed in the AE?

I think this is exactly the same issue that I raised in https://github.com/PHI-base/canto-docs/pull/13:

> The phenotype documentation has some caveats relating to the temporal aspects of extensions: specifically, that multiple extensions on the same annotation are taken to occur simultaneously, as opposed to occurring at separate times. Is this distinction worth preserving for diseases? For example, in the hypothetical case of a pathogen that can cause the same disease at two (or more) separate anatomical locations (tissue types), should each location have its own disease annotation, or should we curate every possible anatomical location in one disease annotation? Basically, do we need to distinguish simultaneous (systemic) infection of multiple anatomical locations from individual infection of multiple possible infection sites?

I have no clear idea what PSO are planning to do about this problem. Personally I think the advantage of two annotations in this _specific_ case it that it makes it easier to relate the figure numbers to the relevant tissue. However I'm aware that making one annotation per tissue type is a lot of extra effort that curators (particularly community curators) might not want to deal with.

The situation might change if these control metagenotypes exist in the session anyway: for example, if the different tissue sites represent two separate experiments that were performed in the paper. Then it's not much effort to just apply the disease annotation (or copy and edit) onto the existing control metagenotypes.

**Comment by jseager7** [comment]
To clarify, I think we should be careful about the semantic implications of merging the tissue extensions into one annotation. The precedent that PomBase has set would mean this annotation would have the effect of saying the disease occurs in _both_ tissue types _at the same time_. By merging the tissue types, we no longer have a clear way to state that the pathogen _may_ infect the inflorescence in some cases, and the coleoptile in other cases.

**Comment by CuzickA** [comment]
Okay, thanks @jseager7 . Not had a chance to look at ticket above yet.

I think in this session I will stick with the two separate annotations as they represent two separate experiments.

**Comment by jseager7** [comment]
Thanks. In that case I'll update the work-in-progress documentation to reflect the fact that we view multiple tissue type extensions as stating that the disease occurs simultaneously in multiple tissues.

**Comment by ValWood** [comment]
Yes, separate annotation is clearer unless they only co-occur.

The syntax for extensions is that a comma indicates a compound extension and a pipe indicates separate annotations (using the precedent set by GO).  So, although it is possible to use the text interface to  change a comma to a pipe 
to indicate 2 separate annotations, I prefer to make independent annotations.

**Comment by CuzickA** [comment]
Thanks. Session updated and approved. Closing ticket.

**Comment by CuzickA** [comment]
Recently in the chemistry curation project we decided that we cannot curate interspecies complementation at this time. We can curate inter strain expts using the allele type 'transformant'. Because of these more recent decisions I am deleting the following older entries as they will be misleading for PHI-base users.

![image](https://github.com/PHI-base/curation/assets/11753634/2e59a2ac-4375-4a20-b76c-d164d865f0ec)
![image](https://github.com/PHI-base/curation/assets/11753634/3ea8dca6-b92e-4802-bed1-73509d5be31e)
