### ISSUE TITLE
PMID: 29567712 A single fungal MAP kinase controls plant cell-to-cell invasion by the rice blast fungus.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#31]
Curation link: https://canto.phi-base.org/curs/0d2bc8d23a8667f4

Not straight forward to find pathogen uniprot id for _Magnaporthe oryzae_ strain Guy 11 gene pmk1

No gene id in current paper, cited in past paper from year 1996

Uniprot searches for 'pmk1' or 'pmk1 Magnaporthe oryzae' no good

Looked up pmk1 in past 1996 paper 'pmid:8946911' and found in Fig 2 legend 'The GenBank accession no. for the PMK1 sequence is U70134.'

Search uniprot with U70134 and find unreviewed uniprot Q92246
![image](https://user-images.githubusercontent.com/11753634/62055027-b6f25100-b212-11e9-8f56-eb671c12d172.png)

Note: name change of pathogen from _M. grisea_ (in past 1996 paper) to _M. oryzae_ (current 2018 paper curating). It looks like this change has not been reflected in the uniprot entry.
![image](https://user-images.githubusercontent.com/11753634/62057256-371ab580-b217-11e9-8495-cc138fbbbbfd.png)
This will cause a problem in PHI-Canto as the wrong name is being displayed (and there was no list of strains)

The reference proteome for M. oryzae is strain 70-15 (https://www.uniprot.org/proteomes/UP000009058)

Ideally, I would like to find the equivalent 'pmk1' uniprot in this reference strain 70-15. However, the Uniprot blast of above Guy11 strain uniprot Q92246 does NOT find a hit in the 70-15 proteome.

@martin2urban I think you are familiar with this gene -do you know of a pmk1 gene id for the reference strain 70-15? or alternative synonymous gene names to search this reference strain 70-15 proteome in uniprot?

**Comment by martin2urban** [comment]
Using above Q92246 sequence from Uniprot and BLAST search at fungi.ensembl.org against 70-15 identifies G4N0Z0 for pmk1.

**Comment by CuzickA** [comment]
Thanks @martin2urban . Good idea to BLAST against Ensembl.

G4N0Z0 is also an unreviewed entry but at least it uses the correct current name M. oryzae so will be fine for PHI-Canto.

It would be nice to have the latest manually reviewed reference proteome id but perhaps uniprot are still working on annotating these entries.

**Comment by CuzickA** [comment]
Just to note: the layout of Science papers is rather difficult to curate as the main text is not in sections and much of the information is in the numerous supplementary files.

@ValWood could we run through my current curation session for this paper on our next call please?

**Comment by CuzickA** [comment]
@valwood please could you check curation through when you have time. Thanks.

**Comment by ValWood** [comment]
I'm confused by this term:


PHIPO:0000990 | absent expression of a pathogen gene product involved in host interaction

especially compared to

PHIPO:0000995 | decreased level of pathogen RNA involved in a host interaction


should it be "level of RNA" too?

**Comment by ValWood** [comment]
Ah I see. figure b is protein level.

I changed to
absent expression of a pathogen gene product involved in host interaction

but, this has the child term
absent expression of a pathogen gene product involved in host interaction
Do we need this? I will open a ticket on the FYPO tracker. Can it merge into the parent?

**Comment by ValWood** [comment]
note there are 2 tickets for this paper.
https://github.com/PHI-base/curation/issues/40

**Comment by ValWood** [comment]
my comments are in the other ticket so you might be able to close thisd

**Comment by CuzickA** [comment]
Whoops! Closing this ticket in favor of #40
