### ISSUE TITLE
PMID: 31250536 The farnesyltransferase β-subunit RAM1 regulates localization of RAS proteins and appressorium-mediated infection in Magnaporthe oryzae.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#33]
Curation link https://canto.phi-base.org/curs/ab02789a62331ecf

**Comment by CuzickA** [comment]
@ValWood please could you add this to your list for checking though. Thanks.

**Comment by ValWood** [comment]
I don't think I would do multiple annotations the same with different hpi?

Magnaporthe oryzae | P131 | G4MY67_MAGO7 | ram1Δ | PHIPO:0000028 | normal formation of pathogen penetration structure | Microscopy | hydrophobic coverslip, 12hpi, cAMP |   | Fig 5A,B increased cAMP |   | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk> | EditCopy and editDeleteChecked
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Magnaporthe oryzae | P131 | G4MY67_MAGO7 | ram1Δ | PHIPO:0000028 | normal formation of pathogen penetration structure | Microscopy | hydrophobic coverslip, cAMP, 24hpi |   | Fig 5A,B increased cAMP |   | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk>


I  did not do anything with these though, we can discuss

**Comment by ValWood** [comment]
This one all looks good to me.

 I made small changes to the GO annotations.

I am removing

GO:0075053 | formation of symbiont penetration peg for entry into host
GO:0043949 | regulation of cAMP-mediated signaling
GO:0075021 | cAMP-mediated activation of appressorium formation
from the protein farnesyltransferase activity
because this isn't really doing the "regulating"

It localizes the ras to the cell surface, but the Ras is subsequently regulated by other signals. The farnesylation is just "upstream".

The ras1/2 will end up annotated to these terms, but there are not enough experiments here to make these annotations for the ras's 

People often do make these annotations using GO but it isn't so useful to do (I can explain in more detail on a call) I have put "discuss" to elaborate on this.

**Comment by CuzickA** [comment]
For MGG_01287 / G4MY67

Subject:
"[uuw] UniProtKB/TrEMBL G4MY67 entry update request"

Message:
Please add Ram1 as the gene name.

Please see literature PMID:31250536
 
Thank you,
  
The PHI-base curation team (email: curation@phi-base.org)

(The PHI-base/PHI-Canto curation team)

**Comment by CuzickA** [comment]
UniProts tricky (#35) for 
'ras1 magnaporthe oryzae'
![image](https://user-images.githubusercontent.com/11753634/71254252-49120780-2322-11ea-9ed6-3824f7afd967.png)
neither are for reference strain 70-15

'ras2 magnaporthe oryzae'
![image](https://user-images.githubusercontent.com/11753634/71254464-eec57680-2322-11ea-9dbd-874357dc07f4.png)
The top entry here is for the reference strain 70-15.
However, the expt in the paper used strain P131 so these are the uniprots we have used in the curation session for both ras1 and ras2. Is this correct? 
Note, ram1 uniprot above is from strain 70-15.
Ideally all the UniProts would come from strain 70-15 but there is no entry for ras1 strain 70-15.

I need to request addition of gene names to the ras1 and ras2 entries but first need clarification as to which UniProt entries to request updates for.

**Comment by CuzickA** [comment]
Still to do
1) wait for ram1, _ras1 and ras2_ gene name to be added to uniprot entry.
2) _DONE_ decide which uniprot entries for ras1 and ras2 to request gene name updates
3) _DONE for media_ review and reduce conditions where possible _still to update media in PHI-ECO_
4) waiting for inter species complementation for MoRam1 function in yeast Fig 6a
5) _DONE_ create phipo NTRs and edits on phipo tracker _awaiting feedback on_  https://github.com/PHI-base/phipo/issues/192

**Comment by CuzickA** [comment]
@ValWood what do you think about point 2 above?

> decide which uniprot entries for ras1 and ras2 to request gene name updates

UniProts tricky (#35) for
'ras1 magnaporthe oryzae'
image _above_
neither are for reference strain 70-15

'ras2 magnaporthe oryzae'
image _above_
The top entry here is for the reference strain 70-15.
However, the expt in the paper used strain P131 so these are the uniprots we have used in the curation session for both ras1 and ras2. Is this correct?
Note, ram1 uniprot above is from strain 70-15.
Ideally all the UniProts would come from strain 70-15 but there is no entry for ras1 strain 70-15.

I need to request addition of gene names to the ras1 and ras2 entries but first need clarification as to which UniProt entries to request updates for.

**Comment by CuzickA** [comment]
https://www.uniprot.org/uniprot/G4MZY8 ras1 strain 70-15, uniprot blast of ras1 P131 strain seq gives 100% match to this.
we want this one as we are using the refernce strain as our default entry,
Therefore request gene name updates for this and ras2 70-15 strain entry.

Add to help doc that may need to perform blast search to reference strain.

**Comment by CuzickA** [comment]
help #178864

Subject:
"[uuw] UniProtKB/TrEMBL G4N1S3 entry update request"

Message:
Please add RAS2 as the gene name.

Please see literature PMID:31250536
 
Thank you,
  
The PHI-base curation team (email: curation@phi-base.org)

(The PHI-base/PHI-Canto curation team)

From UniProt

Dear PHI-base team,

seems to me that in all publications so far I could find, this gene is named RAS1

PMID:17056708 and PMID:24835254 both name the genes Ras1 (MG09499) and
Ras2 (MG06154), which also corresponds to the sequences found in
PMID:31250536

I will add the gene names accordingly RAS1 to UniProtKB:G4N1S3 and RAS2 to UniProtKB:G4MZY8. Either your request was a mixup, or you may want to update the corresponding entries in PHI-base as well. Please correct me if I'm wrong

Best wishes

-ivo

**Comment by CuzickA** [comment]
help #178865

Subject:
"[uuw] UniProtKB/TrEMBL G4MZY8 entry update request"

Message:
Please add RAS1 as the gene name.

Please see literature PMID:31250536
 
Thank you,
  
The PHI-base curation team (email: curation@phi-base.org)

(The PHI-base/PHI-Canto curation team)

From UniProt

Dear PHI-base team,

seems to me that in all publications so far I could find, this gene is named RAS2

PMID:17056708 and PMID:24835254 both name the genes Ras1 (MG09499) and
Ras2 (MG06154), which also corresponds to the sequences found in
PMID:31250536

I will add the gene names accordingly RAS1 to UniProtKB:G4N1S3 and RAS2 to UniProtKB:G4MZY8. Either your request was a mixup, or you may want to update the corresponding entries in PHI-base as well. Please correct me if I'm wrong

Best wishes

-ivo

**Comment by CuzickA** [comment]
Still to continue checking conditions for this session

**Comment by CuzickA** [comment]
Waiting for 4 new conditions to be added, then session is ready for approval.

**Comment by CuzickA** [comment]
Condition terms now added. Waiting for interspecies complementation in the future.
Approving session and closing ticket.

**Comment by CuzickA** [comment]
Reannotating this session.

Should the AE expressivity be available for this term?
![image](https://user-images.githubusercontent.com/11753634/112144971-afdf3a00-8bd1-11eb-85c6-e1eacac9dfab.png)

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/config/issues/53

**Comment by ValWood** [comment]
Yes.

**Comment by CuzickA** [comment]
This session is waiting for AE severity, a quick double check and ready for approval.
I have added disease, controls, compared to, disease interaction where relevant.

**Comment by CuzickA** [comment]
Just waiting for AE severity and ready to approve

**Comment by CuzickA** [comment]
AE severity annotation added.

Session approved, closing ticket

**Comment by CuzickA** [comment]
Edit ScRAM1 to MoRAM1
![image](https://user-images.githubusercontent.com/11753634/204549620-b815941d-af05-4031-a466-ddd0d6d78102.png)

to

![image](https://user-images.githubusercontent.com/11753634/204550176-72c99fc6-3e4c-47b1-9062-a9460f3e9c41.png)

**Comment by CuzickA** [comment]
Checking UniProt entry update status
https://www.uniprot.org/uniprotkb/G4MY67/entry RAM1 DONE and displayed in PHI-Canto
https://www.uniprot.org/uniprotkb/G4N1S3/entry RAS1 DONE, but NOT displayed in PHI-Canto, due to a different strain level UniProt being used.
https://www.uniprot.org/uniprotkb/G4MZY8/entry RAS2 DONE, but NOT displayed in PHI-Canto, due to a different strain level UniProt being used.

According to the notes above I want to change the Mo RAS1 and Mo RAS2 UniProt IDs in the session to those for the reference strain 70-15 (instead of strain P131).
Therefore, 
OOW_P131scaffold00321g25 UniProt L7JGN0 (ras-2) changes to G4MZY8
OOW_P131scaffold00455g13 UniProt L7JC49 (ras-1) changes to G4N1S3

**Comment by CuzickA** [comment]
Tagging @jseager7, these are the UniProts I want to change. Lets discuss further how these changes will affect the PHIG ids in PHI5.

**Comment by CuzickA** [comment]
Here is a record of the current PHIG ids associated with the ras-1 and ras-2 entries
![image](https://user-images.githubusercontent.com/11753634/204777156-084f8f72-f4c0-49ad-a2b8-4c712f4e2cb8.png)

![image](https://user-images.githubusercontent.com/11753634/204776985-9aaf1c7f-e0bd-431d-8814-2568a672f89a.png)

Further discussion is required about what will happen to these PHIG id once I change the UniProt Ids.

**Comment by CuzickA** [comment]
Note: This publication is not included in the 10 example papers described in the PHI-Canto manuscript.

**Comment by CuzickA** [comment]
Added new UniProt ids
Created new genotypes with these new UniProt ids
Transferred annotations over to these new genotypes
Deleted old UniProt id genotypes
Updated GO annotations/AEs
Updated all phenotype AEs
Updated Protein modification
and Physical interaction
Deleted old UniProt ids 

This is all a bit fiddly, time-consuming and could introduce curation errors. It would be nice to have an automated way of changing a UniProt id which would filter down through the genotypes, annotations and AEs.

Now done for this session so reapproving session and closing ticket.

**Comment by CuzickA** [comment]
Recently in the chemistry curation project we decided that we cannot curate interspecies complementation at this time. We can curate inter strain expts using the allele type 'transformant'. Because of these more recent decisions I am deleting the following older entry as it will be misleading for PHI-base users.

![image](https://github.com/PHI-base/curation/assets/11753634/d0350ec5-3666-4e57-8143-33ea1824a3a4)
