### ISSUE TITLE
PMID:28715477 The RhlR quorum-sensing receptor controls Pseudomonas aeruginosa pathogenesis and biofilm development independently of its canonical homoserine lactone autoinducer.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#34]
Link to curation session
https://canto.phi-base.org/curs/11fa7733063e791c

**Comment by CuzickA** [comment]
@ValWood I have a couple of questions about the alleles for this paper
1) I have some nonsense alleles with early STOP codons. I have not entered these before in PHI-Canto. Does below look reasonable? The allele name is what the authors use but is it repeated in the allele description so may not be necessary.
![image](https://user-images.githubusercontent.com/11753634/64694084-be06b300-d490-11e9-9dc6-933285789292.png)
_This is correct._

2) In this bacterial pathogen two operons are deleted phz1 and phz2 each consisting of 7 genes. The authors then make a 'double mutant' of phz1 and phz2 called deltaphz. 
To make these three genotypes in PHI-Canto I think I will have to capture all the individual genes assuming they are all available in UniProt?? What are your thoughts on how to create these genotypes?
deltaphz1 =7 genes
deltaphz2 =7 genes
deltaphz =14 genes
![image](https://user-images.githubusercontent.com/11753634/64695184-76cdf180-d493-11e9-8a1e-56d24f24d0a3.png)

_Need to add all the UniProt ids here._ _Note: phzc1/2 , phze1/2 and phzf1/2 have the same uniprot id. eg O69754 has gene name phzf1 and phzf2_

also see #10

**Comment by CuzickA** [comment]
Query relating to future results display and phenotype hierarchy

![image](https://user-images.githubusercontent.com/11753634/64855556-0ac8c600-d618-11e9-803a-78b99a5ecc6d.png)

In above, the 1st and 2nd annotation are 'abnormal colony morphology' and the 3rd annotation is a 'normal colony morphology'. This may not be clear to some when looking at just the 'child term' in the results display. We may need to consider this when designing the future 'gene display results'.

_Change to 'hyper smooth colony morphology' and 'normal rugose colony morphology'_ b38a37d done

**Comment by CuzickA** [comment]
Need 'assayed_with' config for RNA level phenotypes for this paper. Lost track of the GitHub ticket for this.

**Comment by CuzickA** [comment]
@ValWood This is ready for checking through. As discussed I haven't curated Fig 4 and 5 as I kinda ran out of steam and wasn't quite sure how to curate them -see what you think?

**Comment by ValWood** [comment]
Looks good.

I tweaked the GO, and requested some specific regulation terms.

The rest looked fine.

I want to check the QS terms in a few days because GO have been working on them, but I don't think the changes are through yet.....

**Comment by CuzickA** [comment]
@ValWood do the GO terms still need updating for this session (as per last comment above)?

I have updated the media and timing conditions.
Still need to make a condition for below
![image](https://user-images.githubusercontent.com/11753634/80803556-8c229800-8baa-11ea-9aae-7f369f7ef2b6.png)

**Comment by ValWood** [comment]
I think the GO annotastion is OK, so you can approve. I need to change a term to -ve regulation, have requested. I can add that later

**Comment by ValWood** [comment]
actually I think it's done. ignore the -ve reg

**Comment by CuzickA** [comment]
condition added

https://github.com/PHI-base/phi-eco/commit/305ec45885d281a8cf2320aea73540306fd2579b

**Comment by CuzickA** [comment]
Session approved, closing ticket

**Comment by CuzickA** [comment]
changed 'colony size' term annotations to population growth terms see https://github.com/PHI-base/phipo/issues/206

![image](https://user-images.githubusercontent.com/11753634/99072538-25942300-25ac-11eb-9033-9e633ecea55a.png)
to
![image](https://user-images.githubusercontent.com/11753634/99072604-4492b500-25ac-11eb-99d3-29011e3ecdd1.png)

![image](https://user-images.githubusercontent.com/11753634/99072640-53796780-25ac-11eb-8613-557413ebbd0d.png)
to
![image](https://user-images.githubusercontent.com/11753634/99072771-950a1280-25ac-11eb-9c22-7b202fa6fc9e.png)


_This is now correct 17_11_2020_

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/104929386-b7008680-599b-11eb-9e07-e2e70f848706.png)
 now looks like this

Added control annotations and AE compared to control genotype and AE disease interaction to session.
no disease caused AE used in session

Session approved, closing ticket

**Comment by CuzickA** [comment]
@jseager7 do you have a disease name associated with 'Pseudomonas aeruginosa' and 'Mus musculus'?

I have not entered anything under the 'Disease name' as I'm not sure what name to use here.

**Comment by jseager7** [comment]
@CuzickA Here's the diseases we have in PHI-base for _Pseudomonas aeruginosa_ and _Mus musculus_:

- corneal infection
- cystic fibrosis
- infection
- nosocomial infection
- nosocomial pneumonia
- opportunistic infection
- pneumonia
- septicemia
- soft rot (?)
- urinary tract infection

From the publication (Fig. 6) it looks like the mouse was subject to "intratracheal infection" and seems to have heavy bacterial load in the lungs; would 'pneumonia' be applicable?

**Comment by CuzickA** [comment]
Thanks @jseager7 

I agree 'pneumonia' is the best option. I'll add that to the session.

Interesting to see 'cystic fibrosis' in the list. I assume this will be removed in the future as discussed because this is not an infectious disease, it is a hereditary condition of the host.

**Comment by CuzickA** [comment]
Added
![image](https://user-images.githubusercontent.com/11753634/108708887-eca00e80-7509-11eb-8fa5-2a04c5214fd2.png)

Approving session and closing ticket
