### ISSUE TITLE
Examples where it is difficult or not possible to find UniProt ID

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#35]
https://github.com/pombase/canto/issues/1645

This ticket will collect examples where it is difficult or not possible to find a UniProt id following below instructions

> point people to UniProt
> 
> https://www.uniprot.org/uniprot/?query
> search with the locus ID, locate from species of interest.
> 
> Always choose the reviewed for the species entry. This might be a different strain than your
> experimental strain, but you will select the strain later.
> (Make it clear that this is only to ensure we are working with the correct 
> 
> species/gene).

Past ticket here, related to help instructions for finding UniProts #14

**Comment by CuzickA** [comment]
https://github.com/pombase/canto/issues/1632

Need to try following to select ref proteome uniprot ids

> Maria says:
> 
> Use the advanced search:
> 
> Select Gene name and enter your gene e.g. app
> 
> Add new filed and select 'Keyword' and enter Reference proteome
> 
> This will give you the reference proteins for app e.g.
> 
> https://www.uniprot.org/uniprot/?query=gene%3Aapp+keyword%3A%22Reference+proteome+%5BKW-1185%5D%22&sort=score
> 
> please test and let me know if this doesn't work

**Comment by CuzickA** [comment]
For https://github.com/PHI-base/curation/issues/23

 - Above method worked for 6 genes 
- ppt had to use full protein name instead of abbreviation).
- Did not work for StuA or full name stunted. No ID given in paper, had to go to cited reference PMID: 30154771 and found a protein ID 93828 in Table 2. Had to assume this needed pre-fixing with MYCGRDRAFT_93828. Entered this into uniprot with pathogen species name and keyword 'reference proteome' as suggested above and found F9XD62. No mention of 'StuA' in this Uniprot entry.

**Comment by ValWood** [comment]
This one was mistyped
RSOLAG22IIIB_4067 instead of RSOLAG22IIIB_04067

Maybe also there should be a link to the Uniprot search and some mouse over help. Did we discuss this already?

**Comment by CuzickA** [comment]
Following guidance of how to find a uniprot id above for paper #18
Mr Chi uniprot A0A0W0FPC8 is from a reference proteome strain MCA 2952
Mp Chi uniprot A0A385MIS5 is not -although searching uniprot proteomes for mp indicates a ref is available
![image](https://user-images.githubusercontent.com/11753634/65878532-37a20a80-e386-11e9-8d75-5bfb34958ac3.png)
How to find Mp Chi ref proteome uniprot?

**Comment by CuzickA** [comment]
For #36 
![image](https://user-images.githubusercontent.com/11753634/66305677-c0292980-e8f7-11e9-8e9d-f1555424066d.png)

very challenging to find uniprot ids
through trial and error discovered that the above gene ids without the 'A' on the end map to uniprot ids from a non-reference strain proteome
![image](https://user-images.githubusercontent.com/11753634/66306036-94f30a00-e8f8-11e9-8923-8558efd13977.png)
The reference proteome is
![image](https://user-images.githubusercontent.com/11753634/66306221-ff0baf00-e8f8-11e9-8910-169e329cdc73.png)

By searching gene name species and keyword Reference protein 

Ref proteome Uniprots were found for pptA, pksP and sidA (note: diff uniprots than found using above gene ids)

I was unable to find an obvious aarA id
This is from non-ref proteome using gene id look up (I will use this in PHI-Canto for now)
![image](https://user-images.githubusercontent.com/11753634/66306480-b274a380-e8f9-11e9-8a9c-cadd02928aa0.png)

This is using full gene name look up (also from ref strain, unreviewed and unclear which id?)
![image](https://user-images.githubusercontent.com/11753634/66306568-dfc15180-e8f9-11e9-8654-c2fbc26b6893.png)


ALso note for pksP Uniprot uses alb1 as main name and pksP as synonym
![image](https://user-images.githubusercontent.com/11753634/66309313-34b49600-e901-11e9-90d6-9994d570c6fb.png)

**Comment by ValWood** [comment]
This seems like information that needs feeding to UniPRot.

**Comment by CuzickA** [comment]
Closing ticket for now. 
Aim to use following draft text to find UniProt ids. (May need to re-open ticket if we find examples that cannot be resolved with below instructions).

Finding genes in UniProtKB
PHI-Canto uses UniProt Knowledgebase (UniProtKB) gene accession numbers to disambiguate genes/proteins.  This is to ensure that we are talking about the correct gene product, especially as the same names are sometimes used for different proteins, and to standardize entries because not all strains are in UniProt.
Identify the reference proteome (we use the designated reference proteome to integrate different strain information at the gene level in PHI-base). In PHI-Canto you will be able to specify the strain you used.
Look up the reference proteome for your organism using the species name (https://www.uniprot.org/help/reference_proteome).
If there is no reference proteome use the strain studied.

Identify the gene of interest in the reference proteome
Go to URL https://www.uniprot.org/
Search for  the author assigned gene name/primary name  (e.g. Tri5) or synonyms plus species name  (e.g xxx).
OR
If the gene does not have a ‘given name’ but a locus ID is provided, search using the locus_id  (e.g. xxxx ) plus species name (e.g. XXXX ). If the entry identifier used is not the reference strain, copy the protein sequence and go to the Blast step below.
OR
Search on a protein description (e.g. phosphotransferase)
OR
Obtain the protein sequence for your gene of interest and Blast against UniprotKB (https://www.uniprot.org/blast/) with your  protein sequence.
Note: If there are multiple entries for your gene product from the reference strain, please select the “Reviewed entry”. Use the left hand filter for “Reviewed entries”. 
							OR
           If the gene cannot be located in UniProt. Contact the Authors, Contact UniProt or PHI-base for help locating the canonical database entry.

[ add a screenshot of the results table with accession highlighted] 
Add the entry into PHI-Canto. Once the entry of interest is located, select the entry accession number (also called ‘Entry’)  from column 1 of the results table and use this to retrieve the entry into PHI-Canto on the gene entry page. Caution: Do not confuse the 'Entry' column with the 'Entry name' column. PHI-Canto uses the accession number to retrieve details (such as the gene name, gene product, organism). If PHI-Canto is unable to find your entry, check for typos (e.g. 0 for O), ensure you are using the ‘entry’ not ‘entry name’, and check that your accession is from UniProtKB, not UniParc.
