### ISSUE TITLE
PMID:28720735 A Nonredundant Phosphopantetheinyl Transferase, PptA, Is a Novel Antifungal Target That Directs Secondary Metabolite, Siderophore, and Lysine Biosynthesis in Aspergillus fumigatus and Is Critical for Pathogenicity.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#36]
curation link
https://canto.phi-base.org/curs/326646a152a66e68

**Comment by CuzickA** [comment]
Note: UniProt use teleomorph name Neosartorya fumigata (and anamorph synonym) whereas NCBI taxonomy use anamorph name Aspergillus fumigatus (most commonly used). 

![image](https://user-images.githubusercontent.com/11753634/66304527-50b23a80-e8f5-11e9-99cd-dc805fcbb916.png)

**Comment by ValWood** [comment]
DO UniProt  consistently use the telomorph name? (I forgot).

In this case, I suspect that  it will seem strange to curators to see the telomorph name. Could  we maintain a 'preferred species name" in the master species file?

**Comment by CuzickA** [comment]
> DO UniProt consistently use the telomorph name? (I forgot).

Me too! I just looked up Marc's email and UniProt use the teleomorph name.

The PHI-Canto config file for pathogen species already displays our preferred 'Aspergillus fumigatus' in PHI-Canto.

**Comment by ValWood** [comment]
So are we good here?

**Comment by CuzickA** [comment]
> So are we good here?

Yes this seems fine.

**Comment by CuzickA** [comment]
Another one here for you to check through when you have time @ValWood

**Comment by ValWood** [comment]
I checked this one.
I tweaked the GO annotation.It was correct but  using "author intent" I made some of the GO annotations IMP instead of TAS. The experiments support these MF & BP.

Everything else looked fine

 My only comment is that as we were discussing, the important points (loss of pathogeni
c .ity and unaffected pathogenicity) might get a bit lost in the detail.

**Comment by ValWood** [comment]
commented in wrong ticket

**Comment by ValWood** [comment]
I checked this one.
I tweaked the GO annotation. It was correct but using "author intent" I made some of the GO annotations IMP instead of TAS. The experiments support these MF & BP.

Everything else looked fine

My only comment is that as we were discussing, the important points (loss of pathogenicity and unaffected pathogenicity) might get a bit lost in the detail.

**Comment by CuzickA** [comment]
This session is waiting for 3 new condition terms prior to approval.

For longer term review these annotations need 'compared to X' and a review of the AE infective ability for these annotations
![image](https://user-images.githubusercontent.com/11753634/84768676-8bb05600-afcc-11ea-8060-cca64ad0825a.png)

**Comment by CuzickA** [comment]
Conditions added. 
Session approved for now so closing this ticket.
Still needs 'compared to X' and a review of the AE infective ability in the future.

**Comment by CuzickA** [comment]
Manually updated 'assayed_using' AE by hooking up to UniProts.

Added Figure#s to Figure Column.

Might need new condition for '+ TAFC siderophore' (triacetylfusarinine C). 
Maybe this could be '+ siderophore' with 'TAFC' as related synonym?
![image](https://user-images.githubusercontent.com/11753634/107249573-65dc3380-6a2b-11eb-9f12-5b48aefe3220.png)

**Comment by CuzickA** [comment]
@ValWood Another question about 'RNA level' curation

![image](https://user-images.githubusercontent.com/11753634/107518545-0c007880-6ba7-11eb-9567-d7da47870d35.png)

I need to re-annoate this session with all the WT metagenotype controls. Does it make sense to create control annotations here using a new term to indicate 'presence of host RNA involved in a pathogen interaction' or try and capture this control information like this instead?
![image](https://user-images.githubusercontent.com/11753634/107518984-8f21ce80-6ba7-11eb-98a7-5036e73fc2ac.png)

**Comment by CuzickA** [comment]
> 
> Might need new condition for '+ TAFC siderophore' (triacetylfusarinine C).
> Maybe this could be '+ siderophore' with 'TAFC' as related synonym?
> ![image](https://user-images.githubusercontent.com/11753634/107249573-65dc3380-6a2b-11eb-9f12-5b48aefe3220.png)

I think it is ok to use the existing condition term 'iron absent' here.
![image](https://user-images.githubusercontent.com/11753634/107519504-44548680-6ba8-11eb-8d36-6d305d8df441.png)

**Comment by CuzickA** [comment]
For this annotation
![image](https://user-images.githubusercontent.com/11753634/107522272-71566880-6bab-11eb-88ca-539fea952c5a.png)

The WT pathogen can inhibit the acidification of host phagolysosomes, whereas the mutants cannot

Therefore, would the control metagenotype be NTR: 'pathogen-induced pH increase in host phagolysome' or 'inhibition of pathogen-induced pH decrease in host phagolysome'? @ValWood 
and the mutant 'pathogen-induced pH decrease in host phagolysome'.

The structure may need to change here to remove normal/abnormal grouping
![image](https://user-images.githubusercontent.com/11753634/107523502-b333de80-6bac-11eb-9291-3aff14d41510.png)

**Comment by CuzickA** [comment]
Manually removed AE 'causes_disease' and used new Disease curation type (I did not record disease on moth host)
![image](https://user-images.githubusercontent.com/11753634/107633269-a15f4380-6c5f-11eb-8e52-913b534c6b87.png)

**Comment by CuzickA** [comment]
Also finished control metagenotype annotations, AE compare to and AE disease interaction.

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/phipo/issues/206

Changed
![image](https://user-images.githubusercontent.com/11753634/107634729-e84e3880-6c61-11eb-9c5e-0d942afc4db6.png)
to
![image](https://user-images.githubusercontent.com/11753634/107634812-09168e00-6c62-11eb-97c0-64a170f1195d.png)

as this is a filamentous fungus

**Comment by CuzickA** [comment]
Two queries to resolve with @ValWood before I can approve this session

1) RNA level
2) pH phenotype query

**Comment by CuzickA** [comment]
This session still needs
1) new GO BP term 
'dihydroxy naphthalene (DHN)-melanin'
@ValWood have you requested this?

2) new PHI-ECO term '+ iron' _Now added_

3) NTR for PHIPO
'pathogen inhibition of host defense induced acidification in phagolysome'

4) edit PHIPO term from 'pathogen-induced pH decrease in host phagolysome' to 'host defense induced acidification in phagolysome'

5) NTR for PHIPO 
'host RNA involved in a pathogen interaction, present' _Now added_

**Comment by ValWood** [comment]
We are trying to decide if it is appropriate to add every siderophore to GO, there are 100s/1000s?
https://github.com/geneontology/go-ontology/issues/20974

but if not broad classes will be added.

**Comment by ValWood** [comment]
term added to go, so should be available in a few days.

**Comment by CuzickA** [comment]
Updated RNA annotations, now have

![image](https://user-images.githubusercontent.com/11753634/110140340-e6444900-7dcb-11eb-8822-b855fb9cb4b5.png)
![image](https://user-images.githubusercontent.com/11753634/110140449-0411ae00-7dcc-11eb-8923-bcd447a55f22.png)
![image](https://user-images.githubusercontent.com/11753634/110140609-2dcad500-7dcc-11eb-8248-910eb27c26de.png)

**Comment by CuzickA** [comment]
Still to do
Check on new GO term next week
Make PHIPO changes in https://github.com/PHI-base/phipo/issues/317

**Comment by CuzickA** [comment]
GO term updated
NTR PHIPO terms added
Approving session and closing ticket

**Comment by CuzickA** [comment]
This annotation has been flagged up in a search for pathogen phenotype WT allele with WT level expression. 

![image](https://github.com/PHI-base/curation/assets/11753634/a5a1698a-d496-4636-a66f-44497b018ee3)

In this case the annotation is for a WT allele with WT level expression but with a chemical treatment added that alters the phenotype.
I will leave it for now as I cannot think of another way to make this annotation.
