### ISSUE TITLE
PMID: 21467214 Analysis of two in planta expressed LysM effector homologs from the fungus Mycosphaerella graminicola reveals novel functional properties and varying contributions to virulence on wheat.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#37]
Another chitin-masking paper.
 
Curation link https://canto.phi-base.org/curs/509bac7bf7f4f334

**Comment by CuzickA** [comment]
Please check when you have time @ValWood

**Comment by ValWood** [comment]
I'm . confused by


3LysMΔZymoseptoria tritici (IPO323) | TaCEBip silenced(silenced)[Knockdown]Triticum aestivum (Riband) | PHIPO:0000480 | presence of host necrotic cell death by pathogen | Macroscopic observation (qualitative observation) | 21 dpi | Fig2E. Riband is a susceptible wheat cultivar | infects_tissue leaf , infective_ability gain of pathogenicity | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk> | EditCopy and editDelete Clear
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
3LysMΔZymoseptoria tritici (IPO323) | TaCERK1silenced(silenced)[Knockdown]Triticum aestivum (Riband) | PHIPO:0000480 | presence of host necrotic cell death by pathogen | Macroscopic observation (qualitative observation) | 21 dpi | Fig2E. Riband is a susceptible wheat cultivar | infects_tissue leaf , infective_ability gain of pathogenicity | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk>


becasue 
2e shows no cell death?

**Comment by ValWood** [comment]
I changed to 2F.

So this is "gain" of pathogenicity compared to WT  wheat, BUT I thought pathogenicity  was a property of the pathogen so how can a change to the host be "gain of pathogenicity"

(maybe I misunderstood that). But I would like to be reminded about this so adding discuss.

Otherwise, this session is done.

**Comment by CuzickA** [comment]
Above comments meant for paper #38 I will copy them over

**Comment by CuzickA** [comment]
Approving session and closing ticket for now.
Added label 'check GO' as may need additional GO terms to describe 'pathogen chitin-binding to mask chitin from host'

**Comment by CuzickA** [comment]
Reannotating this session

Updated Figure Col info

Added RNA level
![image](https://user-images.githubusercontent.com/11753634/114556530-b60c8780-9c60-11eb-9760-2d91308d7fa8.png)

**Comment by CuzickA** [comment]
Added fig 3 annotations (in addition to GO curation)
![image](https://user-images.githubusercontent.com/11753634/114559828-0afdcd00-9c64-11eb-8fb3-ead2876d6761.png)

Not sure whether Fig 4 also needs PHIPO annotations Expt  'To test whether Mg1LysM and Mg3LysM were able to protect T. viride against hydrolytic activity'. I need to look up example where we have curated this type of expt before.

**Comment by CuzickA** [comment]
Added 
Disease name
Control metagenotypes
AE disease interaction
AE compared to control

Ready for checking please @ValWood 

I will couldn't remember how to curate Figure 4 perhaps we could discuss next time

**Comment by ValWood** [comment]
quick question:

any reason why 
GO
Z. tritici | MYCGRDRAFT_111221 | GO:0052562 | suppression by symbiont of host immune response | IMP | pathogen mutant results in increased host defense gene expression | Figure 7 |   |

isn't 'effector-mediated'

**Comment by ValWood** [comment]
1LysM+[WT level]Z. tritici(IPO323)bkg: Ku70Delta | wild typeS. lycopersicum(cell line Msk8) | PHIPO:0001240 | host defense induced alkalization
-- | -- | -- | --

should this be 
host defense induced alkalization present?

The other gene is annotated to

PHIPO:0001239 | pathogen inhibition of host defense induced alkalization

**Comment by CuzickA** [comment]
> quick question:
> 
> any reason why
> GO
> Z. tritici | MYCGRDRAFT_111221 | GO:0052562 | suppression by symbiont of host immune response | IMP | pathogen mutant results in increased host defense gene expression | Figure 7 |   |
> 
> isn't 'effector-mediated'

Yes, I think this should be changed to 'effector-mediated'

**Comment by CuzickA** [comment]
> 1LysM+[WT level]Z. tritici(IPO323)bkg: Ku70Delta	wild typeS. lycopersicum(cell line Msk8)	PHIPO:0001240	host defense induced alkalization
> should this be
> host defense induced alkalization present?
> 
> The other gene is annotated to
> 
> PHIPO:0001239 | pathogen inhibition of host defense induced alkalization

![image](https://user-images.githubusercontent.com/11753634/116061799-31b3fe80-a67b-11eb-8bf3-07558d5f8f3e.png)


HI @ValWood, do you mean you think the annotation is incorrect or that the PHIPO term name should include 'present'? Above is the current contents of the branch.

**Comment by ValWood** [comment]
Curating controls
Although It is necessary (useful and interesting) to recorded the pathogenic outcome of the controls. I don't think it is necessary to say "compared to.....control" in an extension unless a change is reported (in which case you need something to compare to?)

<img width="1040" alt="Screenshot 2021-04-26 at 14 14 15" src="https://user-images.githubusercontent.com/7359272/116088346-b01f9900-a699-11eb-85fb-21adc5828cdb.png">

These stand alone as independent annotations. They can be compared but the comparitor isn't necessary?

**Comment by ValWood** [comment]
Controls for increased expression

These aren't compared to the  WT pathogen control are they? I think they are  just increased compared to uninfec ted host?

<img width="1057" alt="Screenshot 2021-04-26 at 14 16 24" src="https://user-images.githubusercontent.com/7359272/116088677-fd9c0600-a699-11eb-86c4-54439c3219d5.png">

**Comment by CuzickA** [comment]
> Controls for increased expression
> 
> These aren't compared to the WT pathogen control are they? I think they are just increased compared to uninfec ted host?
> 
> <img alt="Screenshot 2021-04-26 at 14 16 24" width="1057" src="https://user-images.githubusercontent.com/7359272/116088677-fd9c0600-a699-11eb-86c4-54439c3219d5.png">

These are compare to WT pathogen control - Did I forget to annotate the controls?


![image](https://user-images.githubusercontent.com/11753634/116089263-92066880-a69a-11eb-94b6-4f287de4ae06.png)

**Comment by ValWood** [comment]
I just looked at the Supp data, ignore this one!

**Comment by CuzickA** [comment]
Looks like the above couple of comments are on the wrong ticket -they belong to Mochia1 not LysM. The session link at the top was not taking me to the place that I expected!

**Comment by CuzickA** [comment]
> > 1LysM+[WT level]Z. tritici(IPO323)bkg: Ku70Delta	wild typeS. lycopersicum(cell line Msk8)	PHIPO:0001240	host defense induced alkalization
> > should this be
> > host defense induced alkalization present?
> > The other gene is annotated to
> > PHIPO:0001239 | pathogen inhibition of host defense induced alkalization
> 
> ![image](https://user-images.githubusercontent.com/11753634/116061799-31b3fe80-a67b-11eb-8bf3-07558d5f8f3e.png)
> 
> HI @ValWood, do you mean you think the annotation is incorrect or that the PHIPO term name should include 'present'? Above is the current contents of the branch.

Yes, add 'present' to the top 2 terms in this branch

**Comment by CuzickA** [comment]
Fig 4 model on annotations form https://github.com/PHI-base/curation/issues/62

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/116225833-3398c300-a74a-11eb-8448-141b5ba46619.png)
 change both to present instead of normal

**Comment by CuzickA** [comment]
I have curated Fig 4 like this

![image](https://user-images.githubusercontent.com/11753634/116248215-93e82e80-a763-11eb-91c1-444d917aa225.png)

In this paper a pathogen protein Lysm and tomato host crude extract (containing chitinase) were incubated with Trichoderma viride conidia, therefore it is relevant to curate a metagenotype ( in the avr4 expt #62, there was no host, a purchased chitinase was added instead, therefore we curated this as a single species phenotype)
![image](https://user-images.githubusercontent.com/11753634/116248432-c72abd80-a763-11eb-95f9-15d3d74184fa.png)

**Comment by CuzickA** [comment]
Session just waiting on new PHIPO term

**Comment by CuzickA** [comment]
Terms added, approving session and closing ticket

**Comment by CuzickA** [comment]
Edit GO CC 'apoplast' terms see #98 

![image](https://user-images.githubusercontent.com/11753634/146185759-64da1476-c292-408b-9a54-9ee63045d24f.png)

to
![image](https://user-images.githubusercontent.com/11753634/146186111-c360b590-c40b-433d-9391-69f91d962bbd.png)
