### ISSUE TITLE
PMID:24073880 Mycosphaerella graminicola LysM effector-mediated stealth pathogenesis subverts recognition through both CERK1 and CEBiP homologues in wheat.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#38]
link to curation session https://canto.phi-base.org/curs/84fc0e5867452a4a

Paper with pathogen chitin binding effector mutants and host chitin binding receptor mutants.

@ValWood please review when time.

**Comment by CuzickA** [comment]
Note: Tricky to know what to use as a control when both pathogen and host genes are being mutated.

**Comment by CuzickA** [comment]
comments copied over from #37 
![image](https://user-images.githubusercontent.com/11753634/69870393-a0830180-12a7-11ea-9c92-4c4f40939697.png)

**Comment by CuzickA** [comment]
I think the cell death phenotypes are Fig 2E and the pycnidia are Fig 2F.

Instead of 'presence of host necrotic death' we might need 'gain of host necrotic cell death with pathogen' for
![image](https://user-images.githubusercontent.com/11753634/69871099-cad5be80-12a9-11ea-897d-36e21c191a0b.png)


The Infective ability AE is tricky...

![image](https://user-images.githubusercontent.com/11753634/69871328-69621f80-12aa-11ea-9168-d45cf466c839.png)
Is borderline for reduced virulence/loss of pathogenicity (there is some necrosis/discolouration and 2F for the no virus/asGFP controls have some leaves with low (1-20%) pycnidial coverage.

Therefore, silencing the host gene results in 'gain of pathogenicity of reduced virulence mutant' Which does not fit with our definitions of pathogenicity and virulence. 
'gain of pathogenicity of loss of pathogenicity mutant' or
'increased virulence of reduced virulence mutant' are alternative suggestions but tricky to use.

It is difficult to know what the control is when both the pathogen and host genes are being altered- I think we have had this difficulty before.

It would be got to discuss further.

**Comment by CuzickA** [comment]
Likewise for 
![image](https://user-images.githubusercontent.com/11753634/69872093-71bb5a00-12ac-11ea-97af-bf2eba98271e.png)

The pathogen asexual sporulation structures are decreased compared to WT pathogen Mg3LysM and WT host but are increased compared to mutant pathogen deltaMg3LysM and WT host.

**Comment by ValWood** [comment]
This one also needs the correct GO process terms

**Comment by CuzickA** [comment]
There a few tricky decisions to make here about AE 'infective ability' and 'compared to control', also need to check GO terms @ValWood

**Comment by CuzickA** [comment]
Reannotating this session

Added figure col info

Added RNA level
![image](https://user-images.githubusercontent.com/11753634/114400759-32886300-9b9a-11eb-9207-98795f122f49.png)


Removed outdated 'functional test in host' from one annotation (probably over looked in the past) see https://github.com/PHI-base/curation/issues/26

**Comment by CuzickA** [comment]
Next 
add WT controls for Fig 2A and resistant host in Supplementary Fig. S6

**Comment by CuzickA** [comment]
Added diseas name
![image](https://user-images.githubusercontent.com/11753634/114523867-a1b69380-9c3c-11eb-8fd4-6189548f6c3a.png)

**Comment by CuzickA** [comment]
Added control metagenotypes, AE compared to control, AE disease outcome

Session now ready for checking please @ValWood 

There is query in session about whether using AE 'increased virulence' is correct for a couple of the annotations, please see if it makes sense!

Just to note: I had to make a lot of extra control annotations for this session. This is primarily because 2 pathogen genes and 2 host genes were being manipulated (NOT gene-for-gene). Control combinations needed to be made for each WT pathogen and WT host metagenotype. There were also metagenotypes with a mutant pathogen and WT host (compared to a mutant pathogen and mutant host). In these cases I removed the old metagenotype comprising of mutant pathogen WT host (with no specified gene) and created 2 new metagenotypes with mutant pathogen and each WT specified gene. By hooking up the correct AE compared to control the annotated data is far more informative.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/114552121-2664da00-9c5c-11eb-834f-5e25d9793623.png)

Also needs NTR:increased number of pathogen asexual sporulation structures within host lesion for both annotations above. Pycnidia are the sporulation structure not the actual spores

**Comment by CuzickA** [comment]
NTR added

Session now waiting for checking

**Comment by CuzickA** [comment]
@ValWood

**Comment by ValWood** [comment]
Hi @CuzickA 

I looked through this session- it looks good.

Query AE infective ability 'increased virulence'
what is the query here? 

v

**Comment by CuzickA** [comment]
Thanks @ValWood 

I think my Query AE infective ability 'increased virulence' was just checking that this made sense compared to the selected controls pathogen mutant/ WT host
![image](https://user-images.githubusercontent.com/11753634/129573605-06c9ad13-349b-4fe6-aa3a-b1bf41b6c1d8.png)
![image](https://user-images.githubusercontent.com/11753634/129573767-853bf2a6-f5c4-4436-8890-eec58026b848.png)
![image](https://user-images.githubusercontent.com/11753634/129574168-a9fbdd92-2984-4997-9046-7d8defe41c6f.png)


Were you happy with the GO terms?

**Comment by ValWood** [comment]
>Were you happy with the GO terms?

yup, looks good.

**Comment by CuzickA** [comment]
Thanks. Session approved, closing ticket.
