### ISSUE TITLE
How to curate WT pathogen antifungal target?

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#39]
Needed for https://github.com/PHI-base/curation/issues/36

In this paper they are using an enzyme assay to screen a small molecule-library for inhibitors of pathogen PptA activity.

They found 3 compounds that were potent inhibitors of PptA and calculated the half-maximal inhibitory concentrations (IC50).

This is really useful info to capture as it provides the baseline information of WT sensitivity to these drugs. If these drugs are used in the future, there may eventually be studies to identify Pathogen PptA mutations that lead to increased resistance or increased sensitivity to these drugs. For curation the alleles could be recorded and a phenotype annotated. 

In this paper they have NOT assessed a PptA mutant with the chemistry, so there is no shift in R/S to chemical compared to WT to annotate with a phenotype.

I have had a try at curating this, see below. The parent 'increased sensitivity to chemical' does not seem right as this is the WT. (In the lower annotations they add the chemical to see if pathogen growth is inhibited).
![image](https://user-images.githubusercontent.com/11753634/66476217-ef24d400-ea8c-11e9-91ea-b7e8f6797b55.png)

@ValWood what do you think?

**Comment by ValWood** [comment]
I agree this is useful to capture and it is important.

We haven't  been able to capture this so far for PomBase. What is the publication and I'll take a look.

I'm sure we can come up with something, even if not immediatly.

**Comment by ValWood** [comment]
PMID: 28720735?

probably 
WT gene 
phosphopantetheinyl transferase inhibitor activity 
with chemical in condition if this is what the assay is showing?

We have not been able to do this for PomBase because we  don't curate wild type features, and these types of papers haven''t been a priority for us,  but  in PHI-Canto this is allowed...

and also the decreased population growth terms  in the way you have done them.

**Comment by CuzickA** [comment]
Yes this could work thanks @ValWood .

It may need to be 
phosphopantetheinyl transferase inhibitor activity present

Where would I put this is PHIPO?
Maybe it would be a child of 'decreased catalytic activity' in the single species branch ??

**Comment by ValWood** [comment]
Actually my suggestion isn't quite right. I'll have a think how we should do this. Hold on for this one.

**Comment by ValWood** [comment]
My original suggestion was incorrect. It should  have  been: 

decreased phosphopantetheinyl transferase activity

with the chemical as a condition

**Comment by CuzickA** [comment]
09734b1 done
