### ISSUE TITLE
Prepare a modified "condition ontology" for pathogen phenotypes 

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#4]
@CuzickA

The "conditions ontology" used with individual phenotype ontologies is configurable 
as soon as this is available  (even a mini-version) use at import to test

**Comment by ValWood** [comment]
from https://github.com/pombase/canto/issues/1349

**Comment by CuzickA** [comment]
link to FYPO peco
https://github.com/pombase/fypo/blob/master/peco.obo
Also consider plant expt conditions ontology
http://purl.bioontology.org/ontology/PECO

**Comment by CuzickA** [comment]
URLS to open in protege
https://raw.githubusercontent.com/pombase/fypo/master/peco.obo  (not registered with OBOfoundry)
http://purl.obolibrary.org/obo/peco.owl

A few queries after a quick look through of FYPOpeco

- no logical definitions -do we need these?
- possible name for our conditions PHIECO, open to suggestions here
- if we reused terms from FYPOpeco would we use existing PECO:0000XXX ID or change pre-fix to PHIECO:0000XXX?
- does this involve re-typing all required info into Protege?
- is the fastest way to generate our PHIECO file to slurp up all FYPOpeco and add/remove conditions as needed once we find out what the curators will need OR select a few FYPOpeco conditions and add to as required? (may depend upon re-typing/editing options in Protege)
- we will need to add 'light' and 'dark' treatments to the conditions
- in FYPOpeco CHEBI terms not used for chemical names (no logical definitions)

Thoughts after a quick look through of PECO

- they use logical definitions
- they have 8 ontology imports (incl 3 from chebi) -may be worth looking at to help clarify our decisions on OSK/Travis import lists vs ontology import
- some very nice terms but NOT all are species neutral, does this matter for conditions? (eg some have plant/bacteria in term name, some have similar in the text definition, i think all have 'plant' in logical definition)
- have some good terms for 'light and dark exposure' but text and logical definitions related to plants so these may need to be adapted for us to be species neutral. 
- raises an interesting thought- at any point are we going to give a 'description' of the type of pathogen eg 'fungi' or host eg 'plant' or keep annotation completely species neutral and let the organism NCBI taxon id info provide this information?

**Comment by ValWood** [comment]
Some thoughts, should discuss on next call.

You don't need logical definitions here.  There isn't a lot of maintenance required (our PECO is largely a flat list).

We discussed this briefly on our call today , whether to rename  but decided not to in the short term. We intend in the longer term to maybe migrate these into  an existing condition ontology.

Because of the nature of your annotation (annotating both  pathogens and host), I suspect you may always need multiple condition ontologies, or different ontologies in different aspect.
Maybe change PHI-Canto  to use multiple condition ontologies (or ontology subsets) simultaneousty.

We have no browsing capability for condition selection in Canto (it's just a look up)

You might want to just plug in the existing ontologies rather than maintaining another ontology.  You could request terms not covered in ours or the plant one.

We could also tell the plant-PECO that we intend to use the ontology and ask if they could consider adding subsets or taxon restrictions.

**Comment by ValWood** [comment]
* raises an interesting thought- at any point are we going to give a 'description' of the type of pathogen eg 'fungi' or host eg 'plant' or keep annotation completely species neutral and let the organism NCBI taxon id info provide this information?

Could you give an example here. Do you mean in the phenotype ontology?

**Comment by CuzickA** [comment]
This may be a bit hard to explain...
When making a phenotype annotation (and also GO annotations etc) will the curator run through the whole curation process in a species-neutral manner without specifying the 'type' of pathogen (and host) organism eg bacterial/fungal other than in the NCBI taxon ID species name or uniprot species name information. Will all of our phenotype terms/ expt evidence and condition terms be species neutral?

**Comment by ValWood** [comment]
Hopefully.

Do you have a specific example?

If the phenotype is applicable to all species  it is best.
If you have phenotypes which are not applicable to all species, we can add taxon restrictions. This means, for example if you  would annotate to

stem cancer
not wheat stem cancer

Some terms may apply to both pathogens and hosts  (abnormal membrane morphology). Probably these will just need  ancestry to both  host phenotype and pathogen phenotype.

Is this what you mean?

**Comment by CuzickA** [comment]
In the Plant experimental conditions ontology some of the condition terms have 'plant' in the text

eg
term: biotic plant exposure  def: 'A plant exposure involving the application of a biotic or biological factor such as a microbe, insect, animal, or plant or a combination thereof'

If we wanted to use this conditions term we may modify it to 'biotic host exposure'. This may be a condition assigned to the expt evidence 'functional test in host'.

It just got me thinking that we will probably want to make each curation step species neutral the phenotypes, the evidence and the conditions.

**Comment by ValWood** [comment]
so in this case why can't you use "biotic plant exposure"?  would it be ambiguous in some cases?

Although I'm not sure why they include 'plant' if all of the terms in this ontology are plant conditions, it's probably because this is how a human would expect to see it written). I would have expected "exposure to biotic". Maybe they include plant in terms which *could * apply to non-plants....
You  probably don't need to worry too much about this, if it works/is unambiguous  in the context that you are using it, it will be fine.

**Comment by CuzickA** [comment]
this condition wouldn't be species neutral....the host may be an animal instead of a plant.

Yes it does seem odd that they include 'plant' so frequently within the plant conditions ontology.

**Comment by ValWood** [comment]
ah ok, I see....we might need a mechanism to  select the appropriate condition ontologies behind the scenes depending on the pathogen and host species selected.

Let's begin using PECO-plant.
It's not a show stopper if the appropriate  terms are not present for other host types because any condition can be typed for fixing up later. This way we will see what people actually require.

**Comment by CuzickA** [comment]
Current decisions

1. Logical definitions not required
2. Fastest way to generate 'conditions file' is to snapshot FYPOpeco (18-06-2018) and add new PHI-condition terms as required.
3. If FYPOpeco terms are updated these changes will be made manually to 'PHI_FYPOpeco' file as required.
4. Aim to keep all conditions species neutral, rather than needing specific condition ontologies for plant, animal etc.
5. Newly added terms will use same PECO prefix as FYPOpeco starting from PECO:0005001 to avoid confusion within file. These terms will be 'created_by alaynecuzick'.

Progress
1. 18 'new' terms have been added to the 'PHI_FYPOpeco' file (available as .owl and .obo)
2. adapted from PlantECO to be 'species neutral'
3. includes 'study type', light/dark/intermittent terms within 'grouping experimental environment' and plant hormones within 'chemical added or excluded 'grouping excess''.
4. obo file currently available at link
https://drive.google.com/open?id=1vKyRcfRTyuOBeHtaCGOYv-g7YjyIpYlP
for loading into PHI-canto
5. not currently loaded onto GitHub until further naming and structure decisions have been made

**Comment by CuzickA** [comment]
Removed above file from google drive, updated it and added to PHI-base/config repo

https://raw.githubusercontent.com/PHI-base/config/master/PHI_FYPOpeco.obo?token=ALNYotH8FGA44Yea5pzsfpsRaQbpK49Fks5bOiF5wA%3D%3D

**Comment by ValWood** [comment]
I had a note to say, I always find this useful  to refer to:

- Conditions are the aspects of the experimental setup that are independent of what cells (strain, genotype, constructs, etc.) are used

**Comment by CuzickA** [comment]
I'm closing this issue for now as have a draft version at above link.
