### ISSUE TITLE
PMID:29567712 A single fungal MAP kinase controls plant cell-to-cell invasion by the rice blast fungus.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#40]
curation link
https://canto.phi-base.org/curs/0d2bc8d23a8667f4

A past session to look over and check through

**Comment by CuzickA** [comment]
For checking please @ValWood

**Comment by ValWood** [comment]
GO terms
I removed
GO:0044001 | migration in host
because this term is for directed movement (like along actin cables)
It isn't totally wrong but I think pentration covers what we are looking at.

also removing 
GO:0075053 | formation of symbiont penetration peg for entry into host
in favour of the appressorium term

**Comment by ValWood** [comment]
Also removing

GO:0052542 | defense response by callose deposition
from the pathogen MAPK (this is a host process, but we don't have a gene to attach the annotation to)

**Comment by ValWood** [comment]
I will put migration in host back, but I think GO should have a term "cell to cell migration"

**Comment by ValWood** [comment]
QUESTION

I'm confused by these 2 annotations.
I looked at the supp data and I could not figure out which strains I was looking at, but
other  similar metagenotypes/conditions  are  reduced pathogenicity so I can't figure out what it is here that  makes the "pathogenicity unaffected"


pmk1-AS(aaQ104G)[Not assayed]Magnaporthe oryzae (Guy11) | wild typeOryza sativa (CO-39) | PHIPO:0001003 | normal formation of extra-invasive hyphal membrane | Microscopy | + 1-Na-PP1, 26hpi |   | Fig S6a | infects_tissue leaf , infective_ability unaffected pathogenicity | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk> | EditCopy and editDelete Clear
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
pmk1-AS(aaQ104G)[Not assayed]Magnaporthe oryzae (Guy11) | wild typeOryza sativa (CO-39) | PHIPO:0001004 | normal pathogen morphology during colonization of host | Microscopy | + 1-Na-PP1, 26hpi | Normal morphology of invasive hyphae View definition | Fig S6a | infects_tissue leaf , infective_ability unaffected pathogenicity | Alayne Cuzick <alayne.cuzick@rothamsted.ac.uk>

**Comment by ValWood** [comment]
PHIPO:0000990 | absent expression of a pathogen gene product involved in host interaction


I changed to
absent expression of a pathogen gene product involved in host interaction

but, this has the child term
absent expression of a pathogen gene product involved in host interaction
Do we need this? I will open a ticket on the FYPO tracker. Can it merge into the parent?

**Comment by CuzickA** [comment]
> QUESTION

> I'm confused by these 2 annotations.

I was a bit unsure how to annotate these. The difference is in the timing of the mutation activation.
For Fig 2ab the mutant is activated by +1NA-PP1 after pathogen has made appressorium and invaded the first epidermal cell. Therefore the pathogen penetration prior to addition of 1NA-PP1 was present. 
_Actually maybe this annotation is not correct? To discuss._ The main phenotype is the abolished cell to cell movement. (although it is important to document that the pathogen was able to get inside the host, otherwise it would not be present for the cell to cell movement!)
![image](https://user-images.githubusercontent.com/11753634/68294308-b70eb200-0087-11ea-8bef-a36f996945a0.png)

In this annotation
![image](https://user-images.githubusercontent.com/11753634/68294865-05708080-0089-11ea-9c22-78538cc3bf53.png)
Text from paper 'Pmk1 inactivation did not affect the structure of BICs or the morphology of invasive hyphae (fig. S6A).'
Again the main phenotype here is the lack of cell to cell movement
![image](https://user-images.githubusercontent.com/11753634/68295601-a3187f80-008a-11ea-9813-3daa846500cf.png)

I think I was trying to capture 'unaffected pathogencitiy' at the earlier time points and 'loss of pathogenicity/reduced virulence' at the later stage of infection due to the lack of pathogen cell to cell movement. We can discuss this further.

**Comment by ValWood** [comment]
Yes let's discuss. I thought titwas related to the timing. We can think about how best to make this clear.

**Comment by CuzickA** [comment]
> I will put migration in host back, but I think GO should have a term "cell to cell migration"

@ValWood Do you still think we need this GO term? Has it been requested?

**Comment by CuzickA** [comment]
I have added the 'cell-to-cell migration in host' GO term

A couple of things here still to discuss before this session can be approved @ValWood

**Comment by CuzickA** [comment]
I have moved a few queries out of the term suggestion column into the comments. I have done this so that the session can be approved and exported as a batch of data for MC to visualise. We can go back into the session and make edits in the future if required.
Also closing ticket for now.

**Comment by CuzickA** [comment]
Have added Figure info.
Will continue updating this session after half term.

**Comment by CuzickA** [comment]
Tricky to add AE disease present/absent in some annotations.

RNA level query to discuss

Added Disease curation type.

Still working though and adding in control metagenotypes (next Figure S12 in order of sorted Figures)

**Comment by CuzickA** [comment]
Finished adding control metagenotypes.

Queries left for this session

1) Tricky to add AE disease present/absent in some annotations.
2) RNA level query to discuss
![image](https://user-images.githubusercontent.com/11753634/109001334-b8108c00-769c-11eb-9a64-0fc513186c6a.png)

3) Timing query as reported above

Below annotations not very clear why phenotypes are so different
![image](https://user-images.githubusercontent.com/11753634/109001252-a29b6200-769c-11eb-8a72-2abe191b4c89.png)

![image](https://user-images.githubusercontent.com/11753634/109001442-dd9d9580-769c-11eb-889a-fb39cca2266d.png)

**Comment by CuzickA** [comment]
RNA levels not look like this
![image](https://user-images.githubusercontent.com/11753634/110945095-2c9e2880-8335-11eb-848b-d50ff2c08fbf.png)
![image](https://user-images.githubusercontent.com/11753634/110945225-55beb900-8335-11eb-93c7-9378bd923692.png)

**Comment by CuzickA** [comment]
Deleting these annotations
(They are not very helpful and rather confusing. The inactive mutant can penetrate host prior to addition of + 1-Na-PP1).

![image](https://user-images.githubusercontent.com/11753634/110948938-e4353980-8339-11eb-98ad-8d14f5219617.png)

**Comment by CuzickA** [comment]
Still need to continue checking this one

**Comment by CuzickA** [comment]
I have removed condition '+ 1-Na-PP1' from the controls.
I have noted noted in the comment that WT control is equivalent to 'pmk1-AS(aaQ104G) without 1-Na-PP1'
The main comparisons are therefore
WT vs activated pmk1 mutant

@ValWood please could you have a quick check through of this session to make sure it all looks reasonable!

**Comment by CuzickA** [comment]
I am trying to add additional pathogen alleles with the background Sep5-GFP but am unable to in PHI-Canto, as the non-GFP alleles already exist. Is this correct or a bug?
![image](https://user-images.githubusercontent.com/11753634/111137488-c0126c00-8576-11eb-85ec-cf864e3f71de.png)

**Comment by mah11** [comment]
Hi @CuzickA, 

 > I am trying to add additional pathogen alleles with the background Sep5-GFP but am unable to in PHI-Canto, as the non-GFP alleles already exist. Is this correct or a bug?

It's likely that you've run into the known issue described [here](https://github.com/pombase/canto/issues/1519#issuecomment-400260464).

Could you try the workaround described in the second part of that comment? If it doesn't work, that's a bug. If it does work, it's not exactly a bug because everything is behaving as it has for ages; it's a shortcoming of the Canto interface that we know about but haven't figured out how to improve yet.

**Comment by CuzickA** [comment]
Thanks @mah11 

Used the workaround
![image](https://user-images.githubusercontent.com/11753634/111140791-a70bba00-857a-11eb-80dd-77d84b9972a4.png)

**Comment by ValWood** [comment]
I checked this one too. There are a couple of comments about the GO terms (in the session).
Also, I still don't fully understand the difference between the hyphal and pseudohyphal terms and when they should be used/.

**Comment by CuzickA** [comment]
Yes, its not always clear. Here is what Google says

![image](https://user-images.githubusercontent.com/11753634/111462704-a60f8f80-8716-11eb-8383-144f4ee2c93b.png)
![image](https://user-images.githubusercontent.com/11753634/111462861-d1927a00-8716-11eb-836b-4a4113946046.png)

**Comment by CuzickA** [comment]
Hmmm this was an old annotation. Good spot @ValWood !

It wasn't a pmk1 localization study, I think I was trying to capture that the whole WT pathogen was present in the host cell plasmodesma and hyphal membrane (biotrophic interfacial complex (BIC)). 

I'll delete these annotations.

![image](https://user-images.githubusercontent.com/11753634/111466166-da854a80-871a-11eb-8fdb-62627a6becdf.png)

**Comment by CuzickA** [comment]
I think this session is just waiting for the new GO term https://github.com/geneontology/go-ontology/issues/21125

I will approve it for now and the term can be updated when available.

**Comment by ValWood** [comment]
I just made another note  in the appressorium annotation . It occurred to me overnight! Could you check this too?

**Comment by CuzickA** [comment]
Just seen this comment, I think it is correct 
![image](https://user-images.githubusercontent.com/11753634/111469231-59c84d80-871e-11eb-886a-aeef78b66bc9.png)

The text in the introduction states the following
"To study regulatory mechanisms controlling
invasive growth, we characterized Pmk1, a fungal
mitogen-activated protein kinase (MAPK) essential for appressorium development and pathogenicity that is conserved in many plant-pathogenic
fungi (15). Pmk1 null mutants of M. oryzae cannot
infect rice plants even when mutants are inoculated onto wounded leaves (15). We decided to
conditionally inactivate the Pmk1 MAPK using
a chemical genetic approach"

"Addition of 1NA-PP1 selectively
inhibited the function of Pmk1AS mutants, preventing appressorium development (fig. S4),"

**Comment by ValWood** [comment]
Yes I forgot that part. Last night I was  wondering how it got  into the first cell if it could not make the appressorium. OK ignore!

**Comment by CuzickA** [comment]
No problem, always worth checking.

Session now approved.

**Comment by CuzickA** [comment]
GO term now updated, closing ticket
![image](https://user-images.githubusercontent.com/11753634/124451877-c1fa7800-dd7d-11eb-9744-d9adc33b368f.png)

**Comment by jseager7** [comment]
@CuzickA I think there's an unused gene in this session: I can't find MPS1 (G4N374) in any annotations.

**Comment by CuzickA** [comment]
Deleting MPS1 (G4N374) as I don't think its required for this session. _(Looks like this didn't happen. I have now deleted MPS1 16_12_2022)_

Updating the second annotation to a metagenotype with a different host strain/cultivar
![image](https://user-images.githubusercontent.com/11753634/205315347-931b2dcf-39c2-4b2d-a61d-994d9e5fc2fd.png)

Now looks like this

![image](https://user-images.githubusercontent.com/11753634/205316059-a2b6777d-de50-4cfa-a622-4fd886e66879.png)

Re-approving session.
