### ISSUE TITLE
PMID:15096512 A Kazal-like extracellular serine protease inhibitor from Phytophthora infestans targets the tomato pathogenesis-related protease P69B.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#41]
Link to curation session
https://canto.phi-base.org/curs/babb18b437174938

Older session re-curating.

Changing pathogen EPI1 uniprot so that it is no longer Q6PQH2 obtained using author gene id AY586273
to D0MVC9 obtained by searching uniprot for 'epi1 phytophthora infestans keyword:"Reference proteome [KW-1185]"'

This id is from the uniprot reference proteome 'Phytophthora infestans (strain T30-4) (Potato late blight fungus)'

**Comment by CuzickA** [comment]
Ready for checking @ValWood

**Comment by ValWood** [comment]
both the pathogen and the host had

suggested "extracellular defense response"
but the pathogen should be something else 
(A child of ) GO:0052200   response to host defenses

I will put this for now but we can probably be more specific.
Q Is  the "secretion of protease"  process a type/part of  of innate immunity?

**Comment by ValWood** [comment]
I'm not sure about the pathogen host interaction phenotypes here.
We are hooking the expression level onto the presence of EPI1,
but  it isn't likely that the EPI1 is responsible for the expression increase.

It's just a feature of the species interacting, but it isn't gene-specific...
We can discuss these next week)

**Comment by ValWood** [comment]
Please add a "discuss" label. I will use this for the ones with follow-up questions

**Comment by CuzickA** [comment]
I have just seen this ticket
https://github.com/geneontology/go-ontology/issues/18111#event-2996618998

@ValWood Should I update the GO terms in this session now? If the newly merged GO term 'cellular defense response' is used should I annotate both the pathogen and the host gene to GO cellular component GO:0048046 'apoplast'? Is there an AE to link this location to MF?

**Comment by ValWood** [comment]
> Should I update the GO terms in this session now? If the newly merged GO term 'cellular defense response' is used 

Yes

> should I annotate both the pathogen and the host gene to GO cellular component GO:0048046 'apoplast'? Is there an AE to link this location to MF?

Yes. This does  not exist yet. We  need to add it. We were not really doing this but it's compliant with the prefered GO-CAM modelling way to do this:
MF occurs_in CC

**Comment by CuzickA** [comment]
Hi @ValWood please could we finish off this short session next time we chat.
We need to 
1) check and update GO terms _DONE_
2) create a good condition term for the synthetic elicitor 'BTH' _DONE_
3) create a phipo term for 'inhibition of host defence proteases' or similar _DONE_
4) discuss _DONE remove annotations for now and add to #74 _

> I'm not sure about the pathogen host interaction phenotypes here.
We are hooking the expression level onto the presence of EPI1,
but it isn't likely that the EPI1 is responsible for the expression increase.

> It's just a feature of the species interacting, but it isn't gene-specific...
We can discuss these next week)

I guess this would also be normal level of RNA rather than increased as this is a wild type interaction. Is there another way to capture that these genes are concurrently expressed during this wild type interaction?

**Comment by CuzickA** [comment]
searching uniprot for 'epi1 phytophthora' now gives 2 reviewed uniprot entries referring to this same publication.
![image](https://user-images.githubusercontent.com/11753634/80353391-36c64e00-886d-11ea-9c55-7a5adffc2e12.png)
Looks like we have used  Q6PQH2 in PHI-base and D0MVC9 in this current PHI-Canto session.

**Comment by CuzickA** [comment]
> Looks like we have used Q6PQH2 in PHI-base and D0MVC9 in this current PHI-Canto session.

https://www.uniprot.org/uniprot/Q6PQH2
https://www.uniprot.org/uniprot/D0MVC9

Looking further at these UniProt entries it looks like D0MVC9 is the correct UniProt ID to use. It comes from the reference proteome strain T30-4
![image](https://user-images.githubusercontent.com/11753634/80601027-26f16a00-8a25-11ea-8e82-dd8ad67617d6.png)

whereas Q6PQH2 does not it comes from strain 90128

In conclusion, I will use D0MVC9 for this PHI-Canto entry.
PHI-base uses Q6PQH2 which was identified using a gene id from the paper. This will need updating in the future as part of a larger project updating the UniProt Ids in PHI-base to those from reference proteomes.

**Comment by CuzickA** [comment]
Session now approved so closing this ticket.

**Comment by ValWood** [comment]
But I wonder why UniProt have created a strain specific entry in Uniprot. I thought this would be a single species level entry....

**Comment by CuzickA** [comment]
Just emailed UniProt about this
[help #184983] EPI1 from Phytophthora infestans

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/74

Just add gene expression data 
![image](https://user-images.githubusercontent.com/11753634/98353251-f8c59600-2016-11eb-85b1-cab68dc94afb.png)

@ValWood should this also have an AE 'during'? 
Could we have a quick look at this soon.

**Comment by CuzickA** [comment]
Just to note: it may be difficult to add a metagenotype control and AE disease present/absent for this paper.

**Comment by ValWood** [comment]
Lets look tomorrow.
Re the expression extensions, yes lets add as much context as possible.

**Comment by CuzickA** [comment]
Added 'disease name' to this session as I think it is informative for users even though this information comes from the Intro and methods text rather than a figure showing the disease.

![image](https://user-images.githubusercontent.com/11753634/107769721-4ea18c80-6d30-11eb-8f77-15cbacb4ac9c.png)

**Comment by ValWood** [comment]
For this one, the expression just needed the context provided by the extension 


"during defense response to other organism"

I added this. So I think this one can be approved? and classed as complete?

**Comment by CuzickA** [comment]
Closing ticket

**Comment by CuzickA** [comment]
See #98 

Need to update GO apoplast to host apoplast where appropriate

Current
![image](https://user-images.githubusercontent.com/11753634/145997416-3605aa3b-65c1-4f43-9896-42aa0ed7ede5.png)
![image](https://user-images.githubusercontent.com/11753634/145997465-a577ee81-e035-42d3-aef5-e8c0b9178088.png)

**Comment by CuzickA** [comment]
A couple of questions @ValWood 
1) do you think all uses of 'apoplast' should change to 'host apoplast' here as we are looking at a pathogen host interaction? Or just the pathogen EPI annotations?
2) will the 'existing annotations' automatically update to the new terms?

**Comment by ValWood** [comment]
> do you think all uses of 'apoplast' should change to 'host apoplast' here as we are looking at a pathogen host interaction? Or just the pathogen EPI annotations?

We need to always use "host CC" term when annotating pathogen gene product localization in a host.  
If you are annotating a host gene you always use "apoplast"

Any term preceded by "host" is only for use by pathogens.
We should not be able to annotate  yeast or bacteria  to the "apoplast"  it has
Only in Taxon | 33090 | Viridiplantae

Currently host apoplast only has
GO:0033643 | host cell part | Never in Taxon | 7742 | Vertebrata
but it should probably also have "never  in Taxon | 33090 | Viridiplantae

It might be useful if the "host blah" terms had annotation comments for clarification (i.e these terms should only be used for the annotation of symbiont gene products) if this is confusing.
@pgaudet


2. will the 'existing annotations' automatically update to the new terms?

I don't understand the question?

**Comment by ValWood** [comment]
if you need annotation to "apoplast" to move to "host apoplast" you will need to migrate them (apologies I might have annotated pathogen gene products to this term in error)

**Comment by CuzickA** [comment]
Thanks @ValWood 
Session now looks like this
![image](https://user-images.githubusercontent.com/11753634/146183568-9f848cb6-c91f-4672-8e65-12303bbccc94.png)
![image](https://user-images.githubusercontent.com/11753634/146183645-24aec90c-44b9-494f-bc69-edf75b2d435f.png)


> will the 'existing annotations' automatically update to the new terms?
I don't understand the question?

What I meant here was will this be updated automatically now I have made a change?
![image](https://user-images.githubusercontent.com/11753634/146183992-d89f56db-51cd-4594-8367-b3271058a1d6.png)

**Comment by ValWood** [comment]
If you edited the annotations the "existing annotations" will update in a day or so.
