### ISSUE TITLE
PMID:30610168 Binding of the Magnaporthe oryzae Chitinase MoChia1 by a Rice Tetratricopeptide Repeat Protein Allows Free Chitin to Trigger Immune Responses (MoChia1 -PAMP)

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#42]
link to curation session
https://canto.phi-base.org/curs/79c56f92435923ab

I needed to disambiguate some rice genes for use in extensions.
The reply from UniProt is attached.
[RiceRboh.pdf](https://github.com/PHI-base/curation/files/3725026/RiceRboh.pdf)

This raises the question if the naming convention is different for plants than for fungi because this spreadsheet has suffix 'Os'.
I have asked UniProt about this.

**Comment by ValWood** [comment]
I don't understand the staement 
MoChai1 is a PAMP.
PAMP= pathogen associated molecular pattern.

This is a protein/chitinase. I though teh PAMPS were the chitin fragments?

@CuzickA

**Comment by ValWood** [comment]
This is deduced from
"MoChai induced callose deposition in the rice cell walls , similar to chitin treatment". We therefore  that MoChai is an active  PMAP for rice plants.

I don't get this. Based on this experiment any protein which induces immune events would be a PMAP? ~This means that all effectors are PAMPS is that correct. A PAMP can be anything?~


@CuzickA

**Comment by CuzickA** [comment]
> I don't understand the staement
MoChai1 is a PAMP.
PAMP= pathogen associated molecular pattern.

> This is a protein/chitinase. I though teh PAMPS were the chitin fragments?

Yes this is confusing. I've had a quick look through the paper and spoken to @KEHammond.
You are correct with chitin fragments being PAMPs.

These authors are also calling the MoChia a PAMP.

Past literature has called these pathogen chitin-binding proteins 'effectors' but this very recent paper appears to be moving towards PAMP. This field is evolving over time. There is a 2011 paper PMID: 21278123 'Of PAMPs and Effectors: The Blurred PTI-ETI Dichotomy' where they state that 'The LysM effectors are not the only group of effectors that qualify to be designated as PAMPs based on their widespread occurrence.  The intro line to the abstract states that "Typically, pathogen-associated molecular patterns (PAMPs) are considered to be conserved throughout classes of microbes and to contribute to general microbial fitness, whereas effectors are species, race, or strain specific and contribute to pathogen virulence."

We think that a useful term for MoChia could be 'effector acting like a PAMP'.

**Comment by ValWood** [comment]
> We think that a useful term for MoChia could be 'effector acting like a PAMP'.

Unfortunately we won't be able to do this in GO. GO defines activities and processes. We can't define and activity as being "like" another activity. However, we only need to define terms precisely and in a way that follows the majority use. We shouldn't bend the rules  for individual idiosyncracies. 

However, if this is the general opionion of the community we should define PAMPs more broadly  (note that GO does not have a term for PAMP because this is not a BP or MF, but we do use the phrase PAMP in other terms, like PAMP receptor, so it is important that we know exacty what is considered to be a PAMP). 

We might need to canvas opinion on this.

**Comment by CuzickA** [comment]
In Fig 8 of this paper the authors propose that MoChia1 plays dual roles in rice immunity
1) It binds fungal chitin fragments and suppresses the chitin-triggered ROS burst. (Suppresses host defence). _(Host OsTPR can bind MoChia, freeing chitin and re-establishing defence)._
2) It is perceived by an unknown host PRR which triggers the ROS burst. (acts like a PAMP and Activates PTI host defence)

Q: is chitin-triggered immunity the same thing as PTI? (Why not call it PTI, I have noticed in other papers authors also say 'chitin-triggered immunity'.)

**Comment by ValWood** [comment]
OK I went through this paper again and it all seems clear to me now. MoChai is a PAMP, and a PAMP receptor decoy.
I think the annotation is OK but  @CuzickA  please check carefully, especially the pathogen host interaction phenotypes

Summary:
pathogen/ symbiont
MoChai shelters chitin from chitin-activated immunity ->surpasses plant immunity
Rice immune system could be switched on by chitin AND by MOChai  alone so
Mochai protein also acts as a PAMP 

plants 
 TPR1 frees chitin from MOchai   (to positively regulate PRR signalling)

**Comment by ValWood** [comment]
To do.
I need some slightly more specific GO terms.

**Comment by ValWood** [comment]
To do.
 
- [ ]  need some slightly more specific GO terms.

- [ ]  need to have a way to specify transgenic or ectopically expressed alleles

- [ ] . @CuzickA  please check carefully the differences between the annotations for these two allele constructs. My understanding is that the transgenic is transiently expresssed, but the ectopic is more constitutive.  I called this "overexpressed" but I am not quite sure that would be correct? We can discuss how we should capture thse different types of construct.

**Comment by CuzickA** [comment]
@ValWood have you requested UniProt add gene names to these where required?

![image](https://user-images.githubusercontent.com/11753634/73266148-3cf55180-41ce-11ea-83c0-ddfa34379ad3.png)

**Comment by ValWood** [comment]
I can't find a record of these requests.
However, if we are going to have a "user friendly name" and export in batches to submit to UniProt  we probably don't need to send these on a case by case basis.

I will do this one anyway...

**Comment by CuzickA** [comment]
Reannotating this session

We have an open query about the PHIPO terms for PTI activation (assumed by readouts eg callose) vs actual PTI signaling expt (looking at phosphorylation of MAPK3 and MAPK6) https://github.com/PHI-base/phipo/issues/251

Regarding the use of term 'host PAMP-triggered immunity signaling activated by pathogen' for Fig 1B
![image](https://user-images.githubusercontent.com/11753634/115218241-3f5b0880-a0fe-11eb-80ad-47d3a5a0eff8.png)
![image](https://user-images.githubusercontent.com/11753634/115218327-5b5eaa00-a0fe-11eb-970a-33767b2837fc.png)
Main text
![image](https://user-images.githubusercontent.com/11753634/115218405-6f0a1080-a0fe-11eb-99ac-1a6bb79b2b4a.png)

Would it be better here to use a 'NTR: host defense MAPK signaling present' with AE assayed_using MAPK3 and MAPK6
or something similar? What do you think @ValWood or even 'NTR: host defense MAPK phosphorylation present' and AE.

We could then take the 'signaling' out of the  'host PAMP-triggered immunity signaling activated by pathogen' term and make it more general for observsing PTI read outs eg ROS, callose

Current PHIPO terms in this branch
![image](https://user-images.githubusercontent.com/11753634/115219631-9e6d4d00-a0ff-11eb-8c6d-30a90ffded14.png)

**Comment by CuzickA** [comment]
What is the best way of annotating that MoChia is a PAMP? GO or PHIPO
From main text 
'When MoChia1 was exogenously applied to rice cells,
we found that the MAPK pathway was significantly activated,
whereas the mock treatment did not activate this pathway
(Figure 1B). In addition, MoChia1 induced callose deposition in the
rice cell walls, similar to the chitin treatment (Figure 1C). We
therefore concluded that MoChia1 is an active PAMP for rice
plants'

**Comment by ValWood** [comment]
>What is the best way of annotating that MoChia is a PAMP? GO or PHIPO


We can't say specifically that something is a PAMP using GO because this isn't the evolved role.
We could need to add a new curation type of "immune epitopes" to capture this.
I think we have only captured this previously if we have known the plant receptor and we have been able to capture as an 'input' (i.e the ligand of a plant receptor), but in this case there is no plant entity to attach it to.

**Comment by CuzickA** [comment]
Removed host 'strain unknown' and added 'cv Nipponbare' to all genotypes/metagenotypes

**Comment by CuzickA** [comment]
Added RNA annotations

![image](https://user-images.githubusercontent.com/11753634/115240220-6d991200-a117-11eb-9e43-a4e9c622ac07.png)
![image](https://user-images.githubusercontent.com/11753634/115240219-6d991200-a117-11eb-81e8-fa0f2835605c.png)


_28_04_2021 removed Figure 2B RNA annotation as information already captured in the WT RNA level below._

**Comment by CuzickA** [comment]
see https://github.com/PHI-base/phipo/issues/332 for PTI PHIPO term revision

**Comment by CuzickA** [comment]
The reannotation of this session has been a lot of work but the new additions to PHI-Canto (eg conditions delivery mechanisms, have made these types of expt easier to curate.

I have changed the genotypes so that the 4 types of WT Chia1 are represented as follows
![image](https://user-images.githubusercontent.com/11753634/115863576-911ccf00-a42d-11eb-9a7c-1b6b87e7562a.png)

(within metagenotypes)
Chia1+ [WT level] represents WT pathogen delivery mechanism: pathogen spore inoculation
Chia1+ [not assayed] represents purified protein
Ubi::Chia1-OE+[Overexpression] represents constitutive promoter delivery mechanism: pathogen gene expressed by transgenic host
Dex::Chia1+[Not assayed]  represents inducible promoter delivery mechanism: pathogen gene expressed by transgenic host, + dexamethasone

**Comment by CuzickA** [comment]
Unable to add metagenotype controls in many cases as would have either been equivalent to empty vector/ no pathogen protein added. 

Also unable to add AE Disease interaction in expt where the pathogen was not inoculated onto the host. eg purified pathogen protein added or transgenic host expressing pathogen protein.

Not relevant to add AE infective ability in many expt.

Also to note regarding metagenotypes
used WT host no specified gene until identification of host TRP1 in Figure 5 (interacting with pathogen Chia1). Then Figure 5 onwards specified TRP1 within host genotype either as WT or altered.

Still a query for Fig 6D to discuss PHIPO terms and usage (note detail in host metagenotype of TPR1+ [WT level] vs [not assayed])

This one is ready for checking please @ValWood

**Comment by ValWood** [comment]
Curating controls
Although It is necessary (useful and interesting) to recorded the pathogenic outcome of the controls. I don't think it is necessary to say "compared to.....control" in an extension unless a change is reported (in which case you need something to compare to?)

<img width="1040" alt="Screenshot 2021-04-26 at 14 14 15" src="https://user-images.githubusercontent.com/7359272/116088346-b01f9900-a699-11eb-85fb-21adc5828cdb.png">

These stand alone as independent annotations. They can be compared but the comparitor isn't necessary?

**Comment by ValWood** [comment]
According to the summary, Im not sure about this:
<img width="900" alt="Screenshot 2021-04-26 at 15 20 02" src="https://user-images.githubusercontent.com/7359272/116098386-f0374980-a6a2-11eb-89c4-68b2de0d7b33.png">

This is about TPR1 role in sequestering, but that would be odd, as it would suppress the plant immunity?
(according to the summary)

**Comment by CuzickA** [comment]
Session approved, closing ticket

**Comment by CuzickA** [comment]
change 'apoplast' to 'host apoplast see #98 
![image](https://user-images.githubusercontent.com/11753634/146188696-9b690650-3050-4f5b-ba0c-563596679e3f.png)

![image](https://user-images.githubusercontent.com/11753634/146188831-70b0b5fc-da63-4efd-b06c-255d779a8008.png)

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/curation/issues/114

![image](https://user-images.githubusercontent.com/11753634/205600395-34d66ac9-b0e5-424e-bd38-679c53264bc4.png)


1)
MPK3 is Q6Z437
MPK6 is Q336X9
Looks like these were added manually as there is no AE option for 'assayed_using' available for this PHIPO term
![image](https://user-images.githubusercontent.com/11753634/205601829-068956d1-445e-41b3-bfaf-c232027024d0.png)

2)

![image](https://user-images.githubusercontent.com/11753634/205600925-fbfdf91a-516f-4aee-adac-7cbcb4191e39.png)
G4MXR2_MAGOG7 is MGG_08054

manually changing this to
![image](https://user-images.githubusercontent.com/11753634/205601338-22abbf1f-6ae4-45c3-b5f3-cbdb8eba9bbf.png)


3)
![image](https://user-images.githubusercontent.com/11753634/205602262-45f47a11-3861-45fa-b9c7-2e3ba8954aa5.png)
Q0DHH6_ORYSJ is OSNPB_050465800
OJ1328_D07.24-1 should be OSNPB_090438000 ERROR in UniProt added here to AE should be Q69LJ7

Now changed to 

![image](https://user-images.githubusercontent.com/11753634/205604702-fd631384-dff1-4f4a-a9be-789c907ace36.png)

Hi @jseager7, just looking at this session to correct/edit unused genes from ticket #114.

It looks like there are several problems. it would be nice if there were some checks for these.

1) The PHIPO term is missing an AE and so the info was added as text.
2) The UniProt id was added as text (?) and did not automatically show the gene name.
3) Same as 2) and a different UniProt id had been added.

I think we need a way of flagging up the AEs 'added as text' prior to approval so that these edits can be made.

**Comment by jseager7** [comment]
> I think we need a way of flagging up the AEs 'added as text' prior to approval so that these edits can be made.

See https://github.com/PHI-base/curation/issues/114#issuecomment-1337115264.

**Comment by CuzickA** [comment]
I think this should be 2 annotations, one for MPK3 and one for MPK6
![image](https://user-images.githubusercontent.com/11753634/205663227-5992e8eb-40f7-4cc7-8224-ed44aa9167b9.png)

Make change when AE available

**Comment by CuzickA** [comment]
Note to self
Check use of '::' double colons in genotypes. In these cases I think they have been used to indicate promoters used within a construct. This may cause confusion as similar to allele name structure for disruption mutants. eg GT2-23-170::T-DNA(disruption)[Not assayed] in https://canto.phi-base.org/curs/8149debd202f2e6e/ro/

eg Ubi::Chia1-OE+[Overexpression]
Dex::Chia1+[Not assayed]

**Comment by CuzickA** [comment]
Session is approved
