### ISSUE TITLE
Questions to resolve GO issues

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#43]
Hi @CuzickA 

~- [ ] 1.  In my global figure I have Pamp -triggered immunity (PTI) 'annotated' as "FIRST DEFENSE"
However, when I look around I get the impression HR, hypersensitive cell death response  'annotated'  is 'FIRST DEFNSE"?
https://en.wikipedia.org/wiki/Hypersensitive_response
(precedes the whole plant response)
Can you confirm?~
answered below

**Comment by ValWood** [comment]
~- [ ] 2. https://en.wikipedia.org/wiki/Hypersensitive_response
The hypersensitive response (HR) is a mechanism, used by plants, to prevent the spread of infection by microbial pathogens. The HR is characterized by the rapid death of cells in the local region surrounding an infection. The HR serves to restrict the growth and spread of pathogens to other parts of the plant. The HR is analogous to the innate immune system found in animals, and commonly precedes a slower systemic (whole plant) response, which ultimately leads to systemic acquired resistance (SAR).[1]
makes me  assume that 
a slower systemic (whole plant) response, which ultimately leads to systemic acquired resistance (SAR).[1]
refers to PAMP triggered immunity?
BUT, if this is the case is PAMP -triggered immunity innate?~

answered below

**Comment by ValWood** [comment]
- [x] 3. Are HR and PTI are types of innate immunity?
This is a follow on from Question 2

**Comment by ValWood** [comment]
- [ ] 4. 

based on
https://www.nature.com/articles/cdd201137
<img width="758" alt="Screenshot 2019-10-14 at 19 01 02" src="https://user-images.githubusercontent.com/7359272/66772620-057bc700-eeb5-11e9-92e4-45a7d70e01a7.png">


~I now think my figure separating HRR and PTI is wrong. They appear to be the same thing?
If this is not the case how can I separate them?~

i) both activated by [P/M]AMPS
ii) both are targets of pathogen 'effectors'
ii) both result in local responses including
a) ROS accumulation
b) cell wall toughening/callose deposition

If there is a difference we need to establish what it is...

**Comment by ValWood** [comment]
OK so this paper does not mention the caspase part
https://www.sciencedirect.com/science/article/pii/S1674205215000878\

<img width="711" alt="PTI" src="https://user-images.githubusercontent.com/7359272/66773983-4f19e100-eeb8-11e9-8d74-4ab9da24463f.png">


and implies they are different
Pathogens are perceived by two different recog- nition systems that initiate the so-called pattern-triggered immunity (PTI) and effector-triggered immunity (ETI), both of which are accompanied by a set of induced defenses that usually repel pathogen attacks. Here we discuss the complex network of signaling pathways occurring during PTI, focusing on the involvement of mitogen-activated protein kinases.

**Comment by ValWood** [comment]
So in the same article

Plants that are not able to detect these effectors are susceptible to a pathogen, resulting in effector-triggered susceptibility, while plants that can recognize the effectors via disease resistance proteins (R proteins) can implement an immune response called effector-triggered immunity (ETI

My understanding it
PAMPs are  a type of effector.
If PAMP effectors are recognised by  a PAMP receptors  they initiate PAMP tirggrered immunity vai the MAPK cascade to trigger PTI

If these are not recognised,  they can be recoginised by a second defence of disease resistance proteins. I don't know how these can be distinguished from PAMP receptors (because sometimes they appear to regicnise PAMPS (@CuzickA )?


ETI characteristics
a) phase 1 ion influx (hydrogen and calcium in)
a) ROs burst (influences membranes- > deposition of lignin and callose)
b) cell death (caspase dependent )
c) expression on of resistance  genes (what does this mean?)
d) which pathway does this signal through?
e) also requires presence of salycylic acid, active protein synthesis

 PAMP triggered immunity characteristics
a) Ros burst
b) cell wall toughening
c) expression of xxx genes
b) MAPK signalling

So we need to identify  the characteristics that distinguish these 2 pathways either via the mechanism,  (recognition and signalling) or by the responses
@CuzickA  can you help?
Ia any of this incorrect?

**Comment by ValWood** [comment]
https://en.wikipedia.org/wiki/Hypersensitive_response
adding more differentia above.

PArt of this descriptipn is genetic (gene for gene) dating to 1940s and predates modern knowledge, we should stick . to mechanism to differentiate

**Comment by ValWood** [comment]
Which pathway does this refer to?
https://en.wikipedia.org/wiki/Systemic_acquired_resistance

**Comment by CuzickA** [comment]
~>  1. In my global figure I have Pamp -triggered immunity (PTI) 'annotated' as "FIRST DEFENSE"
However, when I look around I get the impression HR, hypersensitive cell death response 'annotated' is 'FIRST DEFNSE"?
PTI is the first layer of defence and ETI is the second layer. HR can be induced by ETI.~


>  2. https://en.wikipedia.org/wiki/Hypersensitive_response
The hypersensitive response (HR) is a mechanism, used by plants, to prevent the spread of infection by microbial pathogens. The HR is characterized by the rapid death of cells in the local region surrounding an infection. The HR serves to restrict the growth and spread of pathogens to other parts of the plant. The HR is analogous to the innate immune system found in animals, and commonly precedes a slower systemic (whole plant) response, which ultimately leads to systemic acquired resistance (SAR).[1]


> makes me assume that

> a slower systemic (whole plant) response, which ultimately leads to systemic acquired resistance (SAR).[1]

> refers to PAMP triggered immunity?

PTI and ETI are local defence responses.
Systemic acquired resistance (SAR)  is a "whole-plant" resistance response that occurs following an earlier localized exposure to a pathogen. 

>  3. Are HR and PTI are types of innate immunity?

I think both PTI and ETI are types of innate immunity. I will double check with @KEHammond
