### ISSUE TITLE
PMID: 31076860 A LysM effector protein from the basidiomycete Rhizoctonia solani contributes to virulence through suppression of chitin-triggered immunity.

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#44]
This sounds like the same mechansim as the one I just did so I will do it 'blind' and then compare the terms used

**Comment by ValWood** [comment]
This sounds like the same mechansim as the one I just did so I will do it 'blind' and then compare the terms used

**Comment by CuzickA** [comment]
curation link
https://canto.phi-base.org/curs/baeff7a059e5f6c4

**Comment by ValWood** [comment]
- [x] Need sugar beet  for host . 
 - [x] Need a way to capture heterologus expression https://github.com/pombase/canto/issues/2049

 - [x] then increased virulence when expressed (I don't really know how to capture this, it won't make sense within our current set up because its a WT pathogen gene causing  increased virulence when expressed in a different species).

- [x] Also needs terms for .  #44
effector-mediated supression of host PTI fig 4

That's it for this paper, so will be quick once we know how to do it.

**Comment by ValWood** [comment]
Also needs terms for 
https://github.com/PHI-base/curation/issues/44

effector-mediated supression of host PTI

**Comment by ValWood** [comment]
I removed myself so  I know I have done what I can. 
Waiting on a few things to complete.
W could discuss how to move forward with the  different species transformants. Tricky...

**Comment by ValWood** [comment]
I could not easily find the pathogen gene in UniProt, so I mailed the author who told me

"You can find the R. solani RsLysM effector (RSOLAG22IIIB_04067) with the accession number CUA69815.1 at NCBI database"

and I found the UniProt entry from the RSOLAG22IIIB_04067 identifier

**Comment by ValWood** [comment]
I should be able to continue with this one

**Comment by CuzickA** [comment]
@ValWood

**Comment by CuzickA** [comment]
>  Also needs terms for . #44
effector-mediated supression of host PTI fig 4

This term is now available PHIPO:0001128

**Comment by ValWood** [comment]
I have finished this session but I have a  question about the MF and the  direction od immune activation, it's a bit confusing!
If we could discuss this one tomorrow too.

**Comment by CuzickA** [comment]
Should this also be curated as a WT metagenotype? With term 'increased level of pathogen RNA within host' assayed using RSOLAG22IIIB_04067  or maybe NTR: presence of pathogen RNA within host??

I'm still not clear on our rules for RNA levels. I am trying to group my session queries with label 'RNA level query'

![image](https://user-images.githubusercontent.com/11753634/107776423-747f5f00-6d39-11eb-81e7-75d781ec5ebe.png)

**Comment by CuzickA** [comment]
Changed this annotation from
![image](https://user-images.githubusercontent.com/11753634/107778642-3899c900-6d3c-11eb-9845-49ad577d81c6.png)

to

![image](https://user-images.githubusercontent.com/11753634/107779737-b01c2800-6d3d-11eb-97a7-438436bc2363.png)



Note: It might be worth adding 'chitin' as synonym to 'PTI inducer' condition.

**Comment by CuzickA** [comment]
How to curate Fig 4 Hyphal protection assay of the RsLysM efector uisng Tricoderma viride

See session https://github.com/PHI-base/curation/issues/62 where @ValWood has curated this under single species.

Although in this case the pathogen gene is WT.

**Comment by CuzickA** [comment]
Added 'disease name'. Not sure if this the correct thing to do, but could be useful to data users.
No AE 'causes_disease'

![image](https://user-images.githubusercontent.com/11753634/107782115-94665100-6d40-11eb-9c3e-937da0ace39d.png)

**Comment by CuzickA** [comment]
Can't really curate control metagenotypes for this paper.
To discuss further

**Comment by CuzickA** [comment]
Need to add 'NTR pathogen RNA within host present' to this annotation
![image](https://user-images.githubusercontent.com/11753634/110143444-2d800900-7dcf-11eb-9966-8d9d3ffffd15.png)

**Comment by CuzickA** [comment]
Val and I discussed this ticket today

1) Can't curate controls as WT pathogen gene (delivered by infiltration or heterologous organism) on WT host with no specified gene
The control for the ROS annotation (decreased level of pathogen-induced host reactive oxygen species) would be host only WT no specified gene +PTI = ROS present and we currently can't curate host genotype no specified gene.

Start a ticket collecting examples of where we cannot curate a metagenotype control
https://github.com/PHI-base/curation/issues/96

2) Figure 4 can't be curated (in comparison to https://github.com/PHI-base/curation/issues/62). Add a note to final comments prior to submission that the WT pathogen gene could have a GO MF annotation of 'chitin inhibition NOT' (but term not currently available in GO, and probably not worth requesting). 
From paper ''The RsLysM effector suppresses chitin-triggered immunity but does not protect hyphae from degradation''. ''Our result showed that RsLysM was unable to protect fungal hyphae against degradation from bacterial chitinases and zymolyases''.

3) add new RNA term when available

Then approve session.

**Comment by CuzickA** [comment]
Added NTR
![image](https://user-images.githubusercontent.com/11753634/110449753-6f080100-80ba-11eb-9019-49b2e2230a3f.png)

Added comment about Figure 4

Session approved

Closing this ticket
