### ISSUE TITLE
PMID:30584105 Conserved fungal effector suppresses PAMP-triggered immunity by targeting plant immune kinases.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#45]
Curation link
https://canto.phi-base.org/curs/dc027c00e7ceab6f#

https://github.com/pombase/canto/issues/2080

Not clear which ubiprot to use for Nb SERK3
![image](https://user-images.githubusercontent.com/11753634/67095640-5427aa80-f1ae-11e9-840a-69fa48b9e6b5.png)

**Comment by ValWood** [comment]
I would ask the authors if they don't provide an accession number linking to one of these entries

**Comment by CuzickA** [comment]
Closing in favour of #60
