### ISSUE TITLE
additional "allele types"

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#5]
from
https://github.com/pombase/canto/issues/1361

The standard allele types are
amino_acid_mutation
 deletion
 disruption
 nonsense_mutation
 nucleotide_mutation
 other
 partial_amino_acid_deletion
 partial_nucleotide_deletion
 unknown
 unrecorded
 wild_type

During the PomBase load we create a log file of all of the allele types described as "other"

The file is here
https://curation.pombase.org/dumps/builds/pombase-build-2017-11-12/logs/log.2017-11-12-21-23-09.alleles_of_type_other

The plan is to create new "types" for those which are frequently used

We have some new proposed allele types (and merges  where we split unecessarily):
https://github.com/pombase/canto/issues/1275

https://github.com/pombase/canto/issues/976 (diploids we plan to handle this more robustly, most of our experiments are in haploids, so it hasn't become urgent yet, may need  for PHI-Canto?)

Please add  any "new types required for PHI BAse to this ticket"

@CuzickA @Hammond-Kosack

**Comment by ValWood** [comment]
we made some changes locally to  improve "types"
https://github.com/pombase/canto/issues/1275
but we still need to handle  diploids better. that might be a priority for PHI-base

**Comment by CuzickA** [comment]
Kim Hammond-Kosack has suggested adding the following Allele types
-	HIS tagged WT allele
-	Fluorescent protein tagged allele
@martin2urban  @KEHammond

**Comment by ValWood** [comment]
We would normally capture these as background rather than as an allele type. The rationale for this is you want to be able to easily group or list all of the same alleles.

We assume/check that there are controls that the GFP tag behaves normally, but the tag isn't causing the phenotype (ho[efully!)

For instance you GFP tag gene A so you can see it.
You mutate gene B  (allele geneB) and see what happens to the localization of gene A

The phenotype  we capture as 
allele Gene B phenotype assayed using geneA
You *can* add the GFP-gene A to the background but we often don't bother since it isn't the allele of interest.

if you added GFP as a separate an allele type  you will be making a multi gene genotype 

so here for example

![wee1](https://user-images.githubusercontent.com/7359272/43404705-067687d6-9410-11e8-944d-228b7d07ffa3.jpg)

the localizations are phenotypes of  wee1-50, not of 

wee1-50 / nod1-GFP 

https://www.pombase.org/genotype/wee1-50-G850E-amino_acid_mutation-expression-not_assayed

**Comment by ValWood** [comment]
i.e they are  only used  to see the localization, they don't (or shouldn't affect the phenotype).

If they might you can put  them in background so the information is there.

We would only move them into the foreground if they had an obvious effect on the phenotypic outcome.

We have curated  many 1000's of these and so have our users. Sometimes users supply the GFP info (they tend to put it in the conditions), but this is quite rare and they understand why we don't include them.

**Comment by CuzickA** [comment]
New alleles types required for curating #22 
select 'other' and then add
'transformant'
'genomic deletion including X' (where X is the gene name)
'presence unknown'

In the future the 'transformant' alleles may be migrated over to a new type of complementation allele

tagging @ValWood

**Comment by CuzickA** [comment]
closing ticket as moved to https://github.com/pombase/canto/issues/1862
