### ISSUE TITLE
PMID: 22314539 The T788G mutation in the cyp51C gene confers voriconazole resistance in Aspergillus flavus causing aspergillosis.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#51]
Chemistry paper curating with @martin2urban 

curation link
https://canto.phi-base.org/curs/92ed9bf55f48e444

**Comment by CuzickA** [comment]
Fortunately the Af uniprot ref proteome is the same the control used in this paper. (NRRL3357).

Uniprot help #175342 to add correct gene name to B8NUK6 CYP51c.

**Comment by CuzickA** [comment]
Also requested uniprot gene names for 
B8NFL5 CYP51b
B8N2C8 CYP51a
used email address curation@phi-base.org

**Comment by CuzickA** [comment]
@ValWood Please could you check this short chemistry paper once you have finished with Tox1/Snn1.
Thanks.

**Comment by ValWood** [comment]
I checked this one.
This is exactly as I would have curated it. Just the resistance and the normal growth.
These types of papers will be easy.

Only one comment. I think amino acid mutation was selected for the genotytp[es, nut nucleotide mutations were reported ?

I did not fix this because I don't  know what you want to do. Even though there is a little more information in the nucleotide description, we always report the amino acids because biologist think in protein sequence alterations (and our users often only report the amino acid change). However, if the nucleotide alteration was reported we add this as a genotype note.

**Comment by CuzickA** [comment]
Old
![image](https://user-images.githubusercontent.com/11753634/68200969-d38fe900-ffb8-11e9-810d-50e1f613f050.png)

New
![image](https://user-images.githubusercontent.com/11753634/68201353-8c562800-ffb9-11e9-8ca9-adb72e65c1d1.png)

Well spotted!
Does the above genotype chnage look reasonable?? I have added the amino acid change to the allele description but left the nucleotide change in the allele name as this corresponds more to the name used in Table 3.

**Comment by CuzickA** [comment]
The paper title also uses 'T788G mutation'

**Comment by ValWood** [comment]
Yes keep the names but describe as proteins seems good! Best of both worlds.

**Comment by CuzickA** [comment]
Dear Alayne and Martin,

Moreover, I've completed annotations for cyp51A and cyp51B from /Aspergillus fumigatus/, as well as for cyp51A, cyp51B and cyp51C from /Aspergillus flavus/. The modifications will be publicly available at the UniProt release around the 29-JAN-2019 (Release 2020_01).
If you have any further comments, suggestions or questions regarding the annotation, please do not hesitate to contact me. Once again, we would like to sincerely thank you for having taken the time to help us improve our database.
Best regards,
Marc Feuermann

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/71169235-64144700-2250-11ea-832e-fc6984419a57.png)

Note- edited these genotypes from expression 'unknown' to 'wild type' as described in text p2602

**Comment by CuzickA** [comment]
This session is just waiting for
1) UniProt release with updated names DONE
2) key expt for training video Tier1 - plan to make a GO MF annotation and a single pathogen phenotype annotation
![image](https://user-images.githubusercontent.com/11753634/71170109-5e1f6580-2252-11ea-9594-18be7780f1b3.png)

![image](https://user-images.githubusercontent.com/11753634/71170094-5233a380-2252-11ea-934c-1c38b76d1966.png)
do we want to include the AE 'has_expressivity' in training video (Tier 1 curation) or does this complicate annotation too much?

_also need to add minimal media to the conditions_ DONE

**Comment by ValWood** [comment]
I don't think it matters, but if the example you include has it, then include it. Sometimes  the "expressivity"  is the only difference between similar alleles.

On a related note, we  changed "expressivity"  to "severity". The community understood the meaning of "severity" better. Odd that this isn't in PHI-Canto. I will open a ticket for this. _This has now been DONE and is visble in PHI-Canto_

**Comment by ValWood** [comment]
This one can be approved after the gene name is updated

**Comment by CuzickA** [comment]
Gene names have been updated. I have approved the session :-)

I will close the ticket for now and it can always be retrieved if required for making the training video.

**Comment by CuzickA** [comment]
Check new 'chemistry phenotype' terms. may need NTR: normal growth chemical X

**Comment by CuzickA** [comment]
Several annotations in this session need updating in the same manner
![image](https://user-images.githubusercontent.com/11753634/101504593-4eb99080-396b-11eb-9c21-1c1fdf7a2312.png)
The unicellular term is incorrect as this is a filamentous fungus
We decided to create new precomposed 'normal growth on chemical' terms and remove the chemical from the condition
(waiting for NTR to load up, before reannotating)

**Comment by CuzickA** [comment]
Updated terms
![image](https://user-images.githubusercontent.com/11753634/102607815-dac47880-4120-11eb-864c-7772cd899f39.png)

closing ticket for now

**Comment by CuzickA** [comment]
Quick question @ValWood 
I just wanted to confirm in both of the annotations below whether I should add '+ voriconazole' to the conditions or not? Thanks

This will be the main example for 'chemistry' annotations.

![image](https://user-images.githubusercontent.com/11753634/106743360-32a63880-6616-11eb-8514-a6243a6e64d7.png)

**Comment by ValWood** [comment]
Because we have som many of these I don't think we routinely duplicate the chemical in the conditions field because it's a given. So it's your call. I'm a bit inconsistent. I sometimes add the condition if it is already in the conditions ontology. I have definitely added sometimes for MMS and HU, but as a rule we don't seem to add it.

**Comment by CuzickA** [comment]
We have most of the chemicals in the condition ontology from our old method of annotating 'normal growth' and adding chemical to conditions.

I'm not sure what the best option is here??

**Comment by ValWood** [comment]
Well it  does no harm to add them, so why not do it. If you think you might want them best to capture. You can always stop ;)

**Comment by CuzickA** [comment]
Thanks. Decision made - we will add the chemical to the conditions.

I will update the 2 chemistry sessions

**Comment by CuzickA** [comment]
Added +chemical to conditions for this session 
Now looks like this
![image](https://user-images.githubusercontent.com/11753634/106759462-b23e0280-662a-11eb-97c9-0a580a7a8117.png)

and this session
https://canto.phi-base.org/curs/b06680e815f64df0
https://github.com/PHI-base/curation/issues/53

**Comment by CuzickA** [comment]
Reviewing this session for #115 and have noticed that an incorrect strain had been used

changing (and deleting strain BMU29791), and reapproving session
![image](https://user-images.githubusercontent.com/11753634/205287696-f1d6337b-2096-4bcc-bb23-3914168fb252.png)

to

![image](https://user-images.githubusercontent.com/11753634/205288109-d1f49c05-6967-4d98-8e8c-d7b06377a222.png)


I have also added text from publication to the comments section relating to these observations.

Comparing cyp51c between VTC-sensitive strain NRRL 3357 and VTC-resistant strain BMU29791 identified 4 mutations in strain BMU29791. Each of these mutations were then applied separately to cyp51c strain NRRL 3357 and a shift from sensitive to resistance to VTC was seen with one of these mutations T788G.

Note: This paper contains gene modifications, aa substitution and overexpression constructs. Natural variation between strains eg the sensitivity/resistance to VTC for WT cyp51c from either NRRL 3357, BMU29791 has not been curated. This may help answer question in #115

**Comment by CuzickA** [comment]
I think I need to add new AE alteration in archetype to this session.

**Comment by CuzickA** [comment]
**AE alteration_in _archetype**

**Questions for Nichola**

I need to follow up with Nichola if I can add an AE_alteration in archetype here. I remember some past discussions that cyp51c may have been misnamed.?? The archetype genes are Cyp51A and Cyp51B.

**Comment by CuzickA** [comment]
I need to update the 'transformant' genotypes following the new guidance in #157

**Comment by CuzickA** [comment]
Transformant genotypes updated
![image](https://github.com/PHI-base/curation/assets/11753634/bb56c1d0-b501-493c-adeb-7b35034069cd)

**Comment by CuzickA** [comment]
After further thought I don't think these should be 'transformants'

![image](https://github.com/PHI-base/curation/assets/11753634/1a74cda0-54e3-4f74-b9f1-200a31e9521c)

NRRL3357 is the standard strain whilst 3357-5 has pyrG as a selection marker.

![image](https://github.com/PHI-base/curation/assets/11753634/477a309f-0b62-40b4-a1b3-7f42c12a7da0)


Therefore I believe these genotypes should just be overexpression genotypes in strain NRRL3357 with background pyrG-

**Comment by CuzickA** [comment]
![image](https://github.com/PHI-base/curation/assets/11753634/2857f231-13fb-4c9a-8d5c-91a593513396)

**Comment by CuzickA** [comment]
Nichola said there are is only Cyp51A and Cyp51B. Therefore the naming of Cyp51C in this paper is an error. To determine whether Cyp51C should be considered as Cyp51A or Cyp51B for the AE alteration in archetype we decided to use FRAST https://www.frast.com.au/. 
Publication provides 'cyp51C (NCBI accession number XM_002383890.1)'
This can be looked up in Genbank but only the nucleotide sequence is downloadable in FASTA. **AC: see update below 22_09_2023** https://www.ncbi.nlm.nih.gov/nuccore/XM_002383890.1?report=genbank

For FRAST  we need the amino acid sequence in FASTA format.
Therefore search UniProt for 'XM_002383890.1' provides https://www.uniprot.org/uniprotkb/B8NUK6/entry#sequences
![image](https://github.com/PHI-base/curation/assets/11753634/75b717fd-8ef5-44b5-a539-6bb3017cf9fb)
The amino acid sequence in FASTA format can be downloaded here
![image](https://github.com/PHI-base/curation/assets/11753634/3bbf1f42-edb4-4625-ae4f-b6e39a005530)
![image](https://github.com/PHI-base/curation/assets/11753634/64f6ff74-1ab4-44fd-ba93-04c837b54acf)

**Comment by CuzickA** [comment]
Copy and paste into FRAST with the Input 'automatic' selected
![image](https://github.com/PHI-base/curation/assets/11753634/a3402eb4-ada9-4664-b57f-4247edbcb62b)

Select 'search'

![image](https://github.com/PHI-base/curation/assets/11753634/539202d8-d6da-4be0-95bd-ce11050b2d63)

Sequence has highest similarity to Cyp51A

**Comment by CuzickA** [comment]
Aspergillus flavus 
cyp51C-T788G(aaS240A)[WT level]
cyp51C-T161C(aaM54T)[WT level]
cyp51C-C1325A(aaP419T)[WT level]
cyp51C-A1337G(aaN423D)[WT level]

Now, I will look to see if I can add **AE alteration in archetype** for Cyp51A (assuming this is the cyp51C named by authors)

**Comment by CuzickA** [comment]
FRAST searches done on 19_09_2023

In FRAST, select 'reference' and 'Cyp51A' than 'next
![image](https://github.com/PHI-base/curation/assets/11753634/960a0c9b-0f01-4102-8b80-f341247444af)

Enter the AA FASTA file from above and select 'next'
![image](https://github.com/PHI-base/curation/assets/11753634/6e5d6061-485d-4e88-8228-06b20b6a1aec)
![image](https://github.com/PHI-base/curation/assets/11753634/24e5b59c-57a0-4eb0-a97c-652da25a70a1)

Select 'alignment' 
![image](https://github.com/PHI-base/curation/assets/11753634/6e3e39ae-1bdc-4677-8d0f-dc44f772b19d)

For Aspergillus flavus cyp51C-T788G(aaS240A)[WT level]

Codon 240 in the sequence index is 'S' which aligns with codon 241 'S' in the Cyp51A archetype sequence.
Maybe we could use 'S241A; Cyp51C (Cyp51A); ASPEFU
(Note Cyp51A archetype species is Aspergillus fumigatus)

**Comment by CuzickA** [comment]
For Aspergillus flavus cyp51C-T161C(aaM54T)[WT level]

![image](https://github.com/PHI-base/curation/assets/11753634/8f4d8ebb-791f-47bc-be6a-95cfb0ad16e5)

Codon 54 in the sequence index is 'M' which aligns with with archetype index codon 55 but a different wildtype AA 'I' in the Cyp51A archetype sequence.
Maybe we could use '55T; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different.

**Comment by CuzickA** [comment]
For Aspergillus flavus cyp51C-C1325A(aaP419T)[WT level]

![image](https://github.com/PHI-base/curation/assets/11753634/5b77fa69-62b6-47c2-9e45-4a4f9e2d971a)

Codon 419 in the sequence index is 'P' which aligns with with archetype index codon 420 but a different wildtype AA 'T' in the Cyp51A archetype sequence.
Maybe we could use '420T; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different. The second AA (mutation) is the same in the Af primary genotype as the archetype - does it make sense to have this AE?

**Comment by CuzickA** [comment]
For Aspergillus flavus cyp51C-A1337G(aaN423D)[WT level]

![image](https://github.com/PHI-base/curation/assets/11753634/dca160e9-39eb-410a-a290-aa043a9b3328)

Codon 423 in the sequence index is 'N' which aligns with archetype index codon 424 but a different wildtype AA 'E' in the Cyp51A archetype sequence.
Maybe we could use '424D; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different.

**Comment by CuzickA** [comment]
logged in with Google
Saved session
![image](https://github.com/PHI-base/curation/assets/11753634/b40bc3d6-7524-4547-9c5a-7cfd82faea58)
![image](https://github.com/PHI-base/curation/assets/11753634/f661dec5-f0ae-438c-aeeb-e595eb6cef8a)

**Comment by CuzickA** [comment]
Nichola says these AEs' look ok.

**Comment by CuzickA** [comment]
After discussion with Nichola, she recommended not using the UniProt download option to obtain an AA FASTA file. this is because there may be cases where the appropriate UniProt Id is not available. Instead use the following method
1) Look up author provided gene id in Genbank
Publication provides 'cyp51C (NCBI accession number XM_002383890.1)'
https://www.ncbi.nlm.nih.gov/nuccore/XM_002383890.1?report=genbank
2) Copy and paste the AA sequence into 'notepad'. Delete unwanted tabs. Insert a FASTA header eg '>XM_002383890.1 Aspergillus flavus NRRL3357 cytochrome P450|Cyp51C (Cyp51A)|PMID 22314539'
3) Save a copy of this AA FASTA file 
![image](https://github.com/PHI-base/curation/assets/11753634/c8f990c6-f931-44cb-8541-8fb778853eff)
4) Now enter this AA sequence into FRAST in the same way as above.

**Comment by CuzickA** [comment]
22_09_2023
![image](https://github.com/PHI-base/curation/assets/11753634/024070ee-0e58-4e0f-bb12-8143782ab62f)
![image](https://github.com/PHI-base/curation/assets/11753634/571cac80-c942-4512-8025-b39284be796c)

**Comment by CuzickA** [comment]
'Reference'
'Archetype input Cyp51A'
Copy and paste
![image](https://github.com/PHI-base/curation/assets/11753634/60f8dcf7-bce1-4a9f-833a-80b37ed657ac)

View output provides info in images above. (Also see below for double check)

Download MAFFT file into Notepad and save a copy. To view alignments this file would need to be opened using appropriate sequence alignment software (not sure which).
![image](https://github.com/PHI-base/curation/assets/11753634/86f90773-7047-4624-94be-5a2c7d09036b)
![image](https://github.com/PHI-base/curation/assets/11753634/4b528e14-34ed-4cab-a0fd-3f0a2465823d)

Session saved in FRAST
![image](https://github.com/PHI-base/curation/assets/11753634/c2872521-3478-41c4-bd94-65993af968cf)

**Comment by CuzickA** [comment]
Double check (uniprot vs genbank generated AA FASTA file)

1) Looks the same

For Aspergillus flavus cyp51C-T788G(aaS240A)[WT level]

Codon 240 in the sequence index is 'S' which aligns with ~codon~ **residue** 241 'S' in the Cyp51A archetype sequence.
Maybe we could use 'S241A; Cyp51C (Cyp51A); ASPEFU
(Note Cyp51A archetype species is Aspergillus fumigatus)

![image](https://github.com/PHI-base/curation/assets/11753634/71a10b42-2307-4288-80e4-bc9e89dd8479)

2)  Looks the same
For Aspergillus flavus cyp51C-T161C(aaM54T)[WT level]

Codon 54 in the sequence index is 'M' which aligns with  archetype index ~codon~ residue 55 but a different wildtype AA 'I' in the Cyp51A archetype sequence.
Maybe we could use '55T; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different.
![image](https://github.com/PHI-base/curation/assets/11753634/7b974058-9223-45ce-ba28-d16edb8f5637)

3) Looks the same
For Aspergillus flavus cyp51C-C1325A(aaP419T)[WT level]

Codon 419 in the sequence index is 'P' which aligns with archetype index ~codon~ residue 420 but a different wildtype AA 'T' in the Cyp51A archetype sequence.
Maybe we could use '420T; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different. The second AA (mutation) is the same in the Af primary genotype as the archetype - does it make sense to have this AE?

![image](https://github.com/PHI-base/curation/assets/11753634/0cae498f-f73a-4d9a-8bec-685f2dc7a37b)

4) Looks the same
For Aspergillus flavus cyp51C-A1337G(aaN423D)[WT level]

Codon 423 in the sequence index is 'N' which aligns with archetype index ~codon~ residue 424 but a different wildtype AA 'E' in the Cyp51A archetype sequence.
Maybe we could use '424D; Cyp51C (Cyp51A); ASPEFU', no first AA listed as Wts different.

![image](https://github.com/PHI-base/curation/assets/11753634/5e187e67-1f8d-43d1-aee6-33419e30a894)

**Comment by CuzickA** [comment]
AEs now added

![image](https://github.com/PHI-base/curation/assets/11753634/6fd9c467-7896-487d-9c66-837d0b4b0746)

Session approved, closing ticket.

**Comment by CuzickA** [comment]
Just to note: I can open the MAFFT output from FRAST using the Geneious software.
