### ISSUE TITLE
PMID:31501141 Trichophyton rubrum Azole Resistance Mediated by a New ABC Transporter, TruMDR3.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#53]
Link to curation session
https://canto.phi-base.org/curs/b06680e815f64df0

Suggest by author 'Marc Feuermann' from Swiss-prot

**Comment by CuzickA** [comment]
help #175908] [uuw] UniProtKB/TrEMBL F2SG60 entry update request
requested MDR3 added as the gene name.
used email address curation@phi-base.org

Now done by Marc Feuermann 18/11/2019

**Comment by CuzickA** [comment]
Hi @ValWood Please could you check this very short chemistry curation session.

I'm not sure the best way of capturing the phenotype here as its not clear what to use as the control
- the clinical isolate TIMM20092 shows increased resistance to VRC and ITC compared to other clinical isolates (CHUV1845) 
-  In the paper I can't see a comparison between TIMM20092 with the isolate used by UniProt as the reference proteome. 
- When MDR3 is disrupted in TIMM20092 authors report increased sensitivity to VRC and ITC 
would the phenotype be 'sensitive to VRC'? 
OR a new type of term such as 'increased sensitivity of a VRC resistant strain?

What should we use as the control?
The last chemistry paper we curated was simpler as the resistant strain was compared to the reference strain. 


Also to note: UniProt appears to have 2 refernce strains here but I assume we focus on the top entry strain as this matches the UniProt id obtained from the gene id provided in the paper (TERG_02186).
![image](https://user-images.githubusercontent.com/11753634/68213226-0d6de900-ffd3-11e9-8de8-40f53ddf7301.png)

**Comment by ValWood** [comment]
my assumption is that any mutant is compared to WT of the same strsain.

So here I think  "sensitive to x" is OK.
I don't think it matters that they don't show the WT for the strain because  we *kown* that it is resistant from the history

I guess more annotation could be made for this paper if we had a better way to do the ectopic expression ....

**Comment by ValWood** [comment]
+id: GO:0140394
+name: ATPase-coupled azole transmembrane transporter activity
should be available tomorrow

**Comment by CuzickA** [comment]
I have used the new above term to replace the previously used GO term in the session.

**Comment by CuzickA** [comment]
Looks like this basic Tier 1 level curation session is complete.
The gene name has been added by UniProt.

**Comment by CuzickA** [comment]
Session approved, closing ticket.

**Comment by CuzickA** [comment]
Check new 'chemistry phenotype' terms. may need NTR: normal growth chemical X

**Comment by CuzickA** [comment]
> Check new 'chemistry phenotype' terms. may need NTR: normal growth chemical X

No need. Closing ticket.

**Comment by CuzickA** [comment]
Title of publication calls gene TruMDR3
![image](https://github.com/PHI-base/curation/assets/11753634/d89d1b17-3333-4e5a-b6bb-feb3d416e41e)

UniProt gene name MDR3 and so the GO annotations use MDR3
![image](https://github.com/PHI-base/curation/assets/11753634/a3e90e05-6a09-4023-935f-e9bb6f569fee)

Genotype named as TruMDR3
![image](https://github.com/PHI-base/curation/assets/11753634/13adb2d5-97f9-465e-ad29-96aec8b19d27)

Hi @ValWood, do you think we need the species prefix at the beginning of the gene name in the genotype? Should the genotype also just be MDR3::nptII+(disruption) in stead of TruMDR3::nptII+(disruption)?

**Comment by ValWood** [comment]
It is OK to put the genotype name as the authors named it, as long as the description is standardized (i.e disruption), and it is linked  to the official gene name.

**Comment by CuzickA** [comment]
Thanks for confirming this :-).

**Comment by CuzickA** [comment]
no archetype information found
