### ISSUE TITLE
PMID:31484736 MoGT2 Is Essential for Morphogenesis and Pathogenicity of Magnaporthe oryzae.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#54]
Link to curation session
https://canto.phi-base.org/curs/a16f44010111a5c4

"[uuw] UniProtKB/TrEMBL G4MWY1 entry update request"
requested adding GT2 as the gene name

G4MWY1 obtained from gene id in paper. (Note search for 'gt2 magnaporthe oryzae keyword:"Reference proteome [KW-1185]"' does NOT come back with this uniprot id).

**Comment by CuzickA** [comment]
Hi Alayne,

Thank you for your request. Entry G4MWY1 is still found in the TrEMBL section of UniProtKB. TrEMBL is the automatically annotated section that is not reviewed, and the information found in this entry stems from the original submission to the EMBL database. Following your suggestions, I've annotated this entry with data from PMID:31484736. The modifications will be publicly available at the UniProt release around the 29-JAN-2019 (Release 2020_01).
Once again, we would like to sincerely thank you for having taken the time to help us improve our database.
Best regards,
Marc Feuermann

**Comment by CuzickA** [comment]
This one is ready for checking please @ValWood

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/71166604-00d3e600-224b-11ea-905e-bb94f0935507.png)
@ValWood Please could you remind me....when the phenotype includes 'potassium chloride' do I still need to add 'potassium chloride' to the conditions?

**Comment by ValWood** [comment]
You don't need to but I occasionally do if the condition is available (HU for eg).

But it isn't really required to interpret the experiment because it's a given. To do this would require we add a lot of conditions over time (100s)

**Comment by CuzickA** [comment]
Still to do
1. _DONE Val_ check session
2. wait for GT2 gene name to be added to uniprot entry
3. _DONE_ review and reduce conditions where possible - perhaps make a rule that condition is not added when part of phenotype (eg above)? This will need to be made clear for help documentation.
4. _DONE answer_ query as to whether this should be 'asexual spores absent' or 'abolished'?
![image](https://user-images.githubusercontent.com/11753634/71901773-8535cc80-3158-11ea-99d2-651da39a32e4.png)
Added ext as text in admin mode
![image](https://user-images.githubusercontent.com/11753634/73069335-5e400000-3ea5-11ea-885e-f1f66947e4d0.png)

5. _DONE unable_ to add AE 'has_expressivity' here. If we want to do this may need to open a ticket.
![image](https://user-images.githubusercontent.com/11753634/71902607-57518780-315a-11ea-92dc-7a82e68a4dda.png)
Added ext as text in admin mode
![image](https://user-images.githubusercontent.com/11753634/73069552-e7efcd80-3ea5-11ea-982f-ee789ba81d7a.png)

6. Query using AE causes_disease 'rice blast' when phenotype indicates abolished disease in this interaction 'abolished pathogen-associated host lesions' / loss of pathogenicity. 
7. Query using AE causes_disease 'rice blast' when the host is not rice but is Barley.

**Comment by ValWood** [comment]
Looks good!

asexual spores absent sounds correct (although this can be "output_of"
sporulation abolished, this is a relation Midori uses so we can make inferences between the absence of components and absence of processes. We can look into this later.

I didn't understand comments 6&7

**Comment by CuzickA** [comment]
Thanks @ValWood 
_I didn't understand comments 6&7_
This query really relates to when to use this AE. 
It seems odd to use a disease name when there is no disease present in the interaction eg
![image](https://user-images.githubusercontent.com/11753634/73069703-4f0d8200-3ea6-11ea-8923-7f86052e1dba.png)

and the issue of causing a disease specifying a given host when the expt is using an alternative host eg is this 'rice blast on barley?'
![image](https://user-images.githubusercontent.com/11753634/73069799-985dd180-3ea6-11ea-81e6-095d69e73105.png)

**Comment by CuzickA** [comment]
Possible Tier 1 single most important annotation

![image](https://user-images.githubusercontent.com/11753634/73071449-a7df1980-3eaa-11ea-9520-3b6f55070430.png)

It would be tricky to choose a pathogen only phenotype as there are several. Is Tier 1 going to concentrate on 1 annotation if a metagenotype is present and 1 annotation from chemistry papers for pathogen only where there are no metagenotypes (to open a ticket on content of Tier 1 curation level?).

**Comment by CuzickA** [comment]
Still query on use of disease name in AE for this session.
Lets discuss soon @ValWood and then I can approve this session.

**Comment by CuzickA** [comment]
See https://github.com/PHI-base/curation/issues/49

Removed disease name 'rice blast' where host is barley and where there are no disease symptons.
Only 1/9 metagenotype annotations have 'rice blast' as an AE.

**Comment by CuzickA** [comment]
Session approved closing ticket

**Comment by CuzickA** [comment]
Corrected weird error of 'unicellular' to 'hyphal' phenotypes
Added Figure column
Added WT control metagenotype and annotations
Added AE disease outcome
Added AE compared to
removed AE causes_disease
Added 'disease name' curation type
Session approved
