### ISSUE TITLE
PMID:16965554 The C-terminal half of Phytophthora infestans RXLR effector AVR3a is sufficient to trigger R3a-mediated hypersensitivity and suppress INF1-induced cell death in Nicotiana benthamiana.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#55]
Link to curation session
https://canto.phi-base.org/curs/87e386b652573063

I have started curating this older effector paper as suggested by Kim H-K

There are some complex experiments involving 3-way interactions which are a bit tricky to capture in PHI-Canto

eg 
Fig 3.
Pathogen effector gene (from P. infestans) construct and host resistance gene (from potato) construct expressed in heterologous species tobacco to obtain cell death readouts. 
Authors then silence the tobacco defence signaling genes SGT1 and HSP90 and express the pathogen and host constructs in these leaves to look for alteration in cell death readout.
I have temporarily added the tobacco silenced gene into the conditions but i'm sure this is not correct.
![image](https://user-images.githubusercontent.com/11753634/69730921-df3a7f80-1120-11ea-8a3f-7375054389a9.png)

eg 
Fig 4
Assay to see if AVR3aKI or AVR3aEM could suppress the cell death triggered by P. infestans INF1 effector.
In tobacco, AVR3aKI or AVR3aEM were infiltrated first and 1 day later an INF1 construct was infiltrated. I have made this into a multi-allele pathogen genotype and subsequent metagenotype with tobacco-not sure if this is correct?

![image](https://user-images.githubusercontent.com/11753634/69732246-317ca000-1123-11ea-8435-dd9777a93cfa.png)

(there may be an issue with displaying strains in multi-alleles here-to follow up)

It is also tricky to add the infective ability annotations- particularly when there is no pathogen organism present and the experiment involves transient expression of pathogen protein in host.

@ValWood perhaps we can run through this paper when we next chat about effectors.

**Comment by CuzickA** [comment]
I have just changed 
'abolished effector-mediated host hypersensitive response during biotrophy'
to 
'absence of effector-mediated host hypersensitive response during biotrophy'

https://github.com/PHI-base/phipo/issues/265

Note: I need to make some changes to the evidence and conditions as the evidence 'Macroscopic observation in heterologous species' no longer exists

**Comment by CuzickA** [comment]
Quickly changed 'Macroscopic observation in heterologous species' to 'Macroscopic observation (qualitative observation)'

Note to self: when reviewing this session, double check figs to see if any of these evidence codes should be Macroscopic observation (quantitative observation) instead.

**Comment by CuzickA** [comment]
Going back to this older session to re-annotate.

This now needs to follow the new gene-for-gene curation type.

**Comment by CuzickA** [comment]
I have now curated figure 1 under the GfG section, currently looks like this
![image](https://user-images.githubusercontent.com/11753634/124477212-a9995600-dd9b-11eb-9fc8-8eb137f0d9f8.png)
![image](https://user-images.githubusercontent.com/11753634/124477310-cdf53280-dd9b-11eb-9bf3-4fb1f44241a6.png)



A few queries/ comments
1) tricky as no names of pathogen strains, just called avirulent or virulent. I have made up strain names.
2) should these natural variant (NV) AA differences be recorded within genotype?
Text from paper "P. infestans isolates
that are avirulent on R3a potato carry the avirulence allele
Avr3a, which encodes AVR3aKI (containing amino acids C19,
K80 and I103), whereas virulent isolates carry only the
virulence allele avr3a, encoding AVR3aEM (S19, E80 and
M103). "

**Comment by ValWood** [comment]
Maybe we can discuss this on the end of a future group call?

**Comment by CuzickA** [comment]
For Fig 3, I have now tried moving the silenced tobacco SGT1 and HSP90 into the background rather than the conditions (as mentioned in top comment). Although this still isn't quite right. The difficulty is dealing with the genotypes of two host organisms firstly the S. tuberosum R3a construct infiltrated into tobacco and secondly the tobacco SGT1-silencing. 
Author conclusion of expt is "R3a signaling is dependent on SGT1 and HSP90".

![image](https://user-images.githubusercontent.com/11753634/124751620-c14d1780-df1e-11eb-8930-bb91ac885f1a.png)

**Comment by CuzickA** [comment]
For comment above

> 1. tricky as no names of pathogen strains, just called avirulent or virulent. I have made up strain names.

I have changed my mind and think these should both just be 'unknown strain'. This follows the host genotypes with the R3a paralogues. The GfG AE should pick up the detail about whether pathogen avirulent or virulent on given host genotype.

we still need to decide on

>2. should these natural variant (NV) AA differences be recorded within genotype?

And add the NV tag to these genotypes when available.

**Comment by CuzickA** [comment]
Just finished Fig 4

**Comment by ValWood** [comment]
I think "unknown strain" makes sense.

**Comment by CuzickA** [comment]
Just finished curating Figure 5 and 6.

Please can you check this one @ValWood. Some of the genotypes in this one were quite tricky!

**Comment by CuzickA** [comment]
Just started looking at #60 

I'm not sure whether 'inf1' should have been made into the multi-allele genotypes like I've done or whether it should be a new condition '+ ETI inducer inf1'.  Text from paper in #60 'Transient
expression of INF1 by agroinfiltration induces rapid HR cell death in Nb'.

It might still be okay as part of genotype I  just wanted to make a note.

It can be tricky to capture assays where an effector is tested to see if it can suppresses INF1-
Induced Cell Death.

**Comment by ValWood** [comment]
Agreed. Although the role of inf1 should be curated somewhere, it seems odd to have these as multi-gene genotypes. Here is is used as the assay system.

**Comment by CuzickA** [comment]
Note to self 
re-curate INF1 expts with INF1 as a condition

**Comment by CuzickA** [comment]
I've had another go at curating Fig 4, 5 and 6 using + INF1 as a condition

@ValWood please could you check through session and see what you think

**Comment by ValWood** [comment]
are these disease outcomes correct for the phenotypes?

<img width="1018" alt="Screenshot 2021-09-13 at 08 30 06" src="https://user-images.githubusercontent.com/7359272/133042081-ad48ad77-14f9-4703-80b8-ef304c6c1819.png">

**Comment by CuzickA** [comment]
I've annotated
presence of HR (resistance) = disease absent
absence of HR (susceptible) = disease present

In these expts we don't actually 'see' disease, so I've assumed absence of HR is disease absent. Its difficult to know whether we should include these AE disease absent / present or not. Is it useful for our data consumers to have this information? 
Some further discussion in #81  

The AE infective ability 'gain of pathogenicity' is also tricky, what do you think?

**Comment by ValWood** [comment]
It looks the wrong way around though?

presence of lesions-  disease absent
absence of lesions- diseasepresent ?

**Comment by CuzickA** [comment]
In this case the presence of HR lesions indicates host resistance therefore disease absent.

Maybe the PHIPO term label is unclear?

**Comment by ValWood** [comment]
Yes, I'm sure this will be obvious to the community but maybe "host defense-induced lesions" would be a better label?

**Comment by CuzickA** [comment]
I'm trying to get sessions finished up and approved for MC to test loading into PHI5.

1) I have created NTR: stunted growth. This term needs loading into PHI-Canto before approval.
2) I curated this session but it has not been checked. I don't think Val with have time to do the checking now. @smvelasquez, when you have time please can you check through this session and provide me with any feedback? Any further changes can be made in the future to the approved session by reactivating it and making the updates.

**Comment by ValWood** [comment]
Correct- I am not funded on this project at present. I won't be able to do any annotation review.

**Comment by CuzickA** [comment]
I have now added the NTR to the session.

I have approved this session to increase the amount of data available for MC.

I can reactive and make any changes in the future if @smvelasquez has any feedback after looking through the session.

**Comment by smvelasquez** [comment]
@CuzickA I am not so sure about the “severity high” term. To me, it’s just the description of the phenolic compounds which can be associated with cell death, but it is not symptoms per se. They don’t even quantify the compounds directly but use the autofluorescence as an indirect indicator. Plus, the authors don’t talk about severity either when discussing this result.

![image](https://user-images.githubusercontent.com/100948503/188457075-5e2d1c45-3873-417b-b6ad-77c95b700fdd.png)

There is no mention of figure 2f where they look a the confluence of infiltration sites and cell death. Here it is where it could be added the differences in severity.

**Comment by smvelasquez** [comment]
@CuzickA  
![image](https://user-images.githubusercontent.com/100948503/188457270-2cc0ef6e-17c2-4a10-8900-047435aca7f2.png)

Why wasn’t fig 3b curated?

**Comment by smvelasquez** [comment]
![image](https://user-images.githubusercontent.com/100948503/188457336-af41d015-28ee-4ce1-b450-f5256f312511.png)

![image](https://user-images.githubusercontent.com/100948503/188457360-c5b7f1ca-b45b-45a2-b725-11ba3a3eec48.png)

I guess you didn’t curate fig s3 because it is pretty similar to fig4?

**Comment by smvelasquez** [comment]
@CuzickA 
![image](https://user-images.githubusercontent.com/100948503/188457436-f9608ccd-229e-4156-a240-0a10a35f975a.png)

I would no describe this interaction as GfG. HSP90 and STG1 are common to other NBS-LRR R activation pathways. Therefore, they would not follow the GfG theory themselves.

**Comment by smvelasquez** [comment]
@CuzickA 
![image](https://user-images.githubusercontent.com/100948503/188457593-6c78b7f8-2c80-4d5c-9271-0a63ff4a89a1.png)

This is not a CONTROL

**Comment by smvelasquez** [comment]
@CuzickA I am done reviewing this curation :)
