### ISSUE TITLE
PMID:16517760 Reactive oxygen species play a role in regulating a fungus-perennial ryegrass mutualistic interaction.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#57]
curation link
https://canto.phi-base.org/curs/599959346d766435

loss of mutualism (enhanced antagonism) phenotype paper

**Comment by CuzickA** [comment]
The main mutant is noxA but the authors also look at noxB

Query: The noxBdelta mutant on the host is the same as the WT interaction. What should the AE for infective ability be here?
'normal mutualism' /'unaffected mutualism' 
or 'mutualism present'? _We decided _mutualism present.__

![image](https://user-images.githubusercontent.com/11753634/70521913-012bfd00-1b38-11ea-9632-3538c83ada9e.png)


 current PHIPO terms are
![image](https://user-images.githubusercontent.com/11753634/70521673-84008800-1b37-11ea-898b-7694bc02a927.png)

**Comment by CuzickA** [comment]
@ValWood This one is ready for checking thanks.

**Comment by CuzickA** [comment]
It would be worth checking this one at the same time as #58 as they are similar.

**Comment by ValWood** [comment]
I checked this. I have a question about the final experiment curated (which I probably didn't understand). Otherwise looks good.

**Comment by CuzickA** [comment]
Just need to add AE 'mutualism present' and then this session is complete

**Comment by CuzickA** [comment]
Session complete and approved. Closing ticket.

**Comment by CuzickA** [comment]
changing annotations using colony size terms see https://github.com/PHI-base/phipo/issues/206

![image](https://user-images.githubusercontent.com/11753634/99080917-e240b100-25b9-11eb-9357-ed796b709f7f.png)
to
![image](https://user-images.githubusercontent.com/11753634/99081885-57f94c80-25bb-11eb-87f3-a3fd539a7c12.png)
![image](https://user-images.githubusercontent.com/11753634/99081916-634c7800-25bb-11eb-9a70-c10bfee9ceec.png)

This is a tricky one @ValWood 
NoxA mutant has normal radial growth BUT fewer aerial hyphae
We may not be able to merge the aerial hyphae and filament length into one term

**Comment by ValWood** [comment]
I think we can work around this ...can look on Monday

**Comment by CuzickA** [comment]
With updated colony terms, annotations currently look like this
![image](https://user-images.githubusercontent.com/11753634/104450747-7ae2b580-5598-11eb-94c2-ca01cad6dbb0.png)

@ValWood I may just delete the top annotation with the NTR and leave the comment in the second annotation- what do you think?
It seems a bit confusing saying 'normal hyphal growth' and 'decreased quantity of aerial filaments'.

**Comment by CuzickA** [comment]
Doesn't make sense to use new AE 'disease outcome' disease absent/present for this publication as this is a mutualistic interaction.

**Comment by ValWood** [comment]
> It seems a bit confusing saying 'normal hyphal growth' and 'decreased quantity of aerial filaments'.

I agree.  It's that distinction between size increase and morphology again.

**Comment by CuzickA** [comment]
Session now updated with metagenotype CONTROL annotations, compared to genotype AE and colony term checked.

For now I will delete this top annotation, approve session and close ticket. There is a note in the comment that 'In axenic culture, the radial growth of FR2 (deltanoxA) was the same as that of Fl1 (WT), but there were fewer aerial hyphae'
![image](https://user-images.githubusercontent.com/11753634/104726253-3b000780-572b-11eb-8590-38b71d824b45.png)
