### ISSUE TITLE
PMID: 17041146 A p67Phox-like regulator is recruited to control hyphal branching in a fungal-grass mutualistic symbiosis.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#58]
This is the second paper on 'mutualism' entered in PHI-base. (The other paper is #57).

**Comment by ValWood** [comment]
https://canto.phi-base.org/curs/415197e711544890

**Comment by ValWood** [comment]
This one is complete pending a  few new terms
https://github.com/PHI-base/phipo/issues/202

I enjoyed curating this! Even though I still need quite a few new terms, everything I looked at in PHIPO seems pretty good. I found all the existing terms I required by (deliberately)  going a bit broader and drilling down.  I tried different input points and still came to the same terms. All the terms I looked at  seemed to be correctly positioned and have sensible text definitions. Even if we need changes in future   it should not be so disruptive. As the annotations are attached to the terms and the terms are well defined we can easily make changes. So it's all looking good!

**Comment by ValWood** [comment]
@CuzickA 
- [ ]  I could not be any more specific about the GO process than "interaction with host". if you have any ides when checking?

- [ ] Need to look at Tanaka 2006 for a description of the nox1-? mutant

**Comment by ValWood** [comment]
- [ ] Also the big thing I have not captured is the "mutualism" aspect. This does not really fit into GO. I think it might need to be one of this "high-level term derived from extensions". What are your thoughts?

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/2795
is to figure out the correct GO terms.

This one is ready for checking (pending ontology updates)

**Comment by ValWood** [comment]
Oh cool, Tanaka 2006 is the one I am checking tomorrow!
https://canto.phi-base.org/curs/599959346d766435

**Comment by CuzickA** [comment]
see https://github.com/PHI-base/phipo/issues/202

**Comment by CuzickA** [comment]
I have checked this one - looks good.
1) I updated the nox1 mutant to the allele I used in the Tanaka 2006 paper 'noxA::pAN7-1(disruption)'
2) Added AE for 'infects_tissue' and 'loss of mutualism' for 'infective ability'.
3) Corrected a metagenotyp typo for noxR+/grass selecting the OE genotype rather than Wt
4) updated phipo terms (still a couple to load into PHI-Canto)__DONE_
5) added a couple of queries to discuss__DONE_
6) I couldnt find anything better than GO 'interaction with host'. For the Tanaka 2006 paper i used 'symbiotic process' which is a parent term. Maybe I should change these. s_ee shift in mutualism/ enhanced antagonism PHI-base/phipo#5_

_7) add 9 wpi to PHI-ECO_DONE

**Comment by ValWood** [comment]
ah OK, I annotated this one and you checked. we can go through the questions next week

**Comment by CuzickA** [comment]
Just need to edit 1 PHIPO term and then ready for approval

_done, now waiting for loading into PHI-Canto_

**Comment by CuzickA** [comment]
Session approved. Closing ticket.

**Comment by ValWood** [comment]
DO we have enough info here to answer the outstanding question about the appropriate GO term?
https://github.com/geneontology/go-ontology/issues/18767

**Comment by CuzickA** [comment]
Edit 'colony size term' see https://github.com/PHI-base/phipo/issues/206
![image](https://user-images.githubusercontent.com/11753634/99076115-89b9e580-25b2-11eb-8da1-e562285ffaaf.png)
to
![image](https://user-images.githubusercontent.com/11753634/99076415-ffbe4c80-25b2-11eb-9654-ea25e2b4e5e9.png)

**Comment by CuzickA** [comment]
Correction should be
![image](https://user-images.githubusercontent.com/11753634/99077015-fed9ea80-25b3-11eb-8f71-ced5724fb850.png)

**Comment by CuzickA** [comment]
This needs updating as 'abnormal shape of hyphal colony' does not indicate that the colony size is smaller

**Comment by ValWood** [comment]
So we do need the "hyphal growth" term also, to describe   increase in colony size == increased size of individual?

**Comment by CuzickA** [comment]
Now looks like this
![image](https://user-images.githubusercontent.com/11753634/104742338-35fa8280-5742-11eb-85b5-13acacd0c3be.png)


I have added 
controls and compared to AE for metagenotype
cannot add AE disease interaction or disease name as mutualistic interaction
added Fig info
update hyphal terms to the latest available

Approving session and closing ticket
