### ISSUE TITLE
PMID:30651637 A kiwellin disarms the metabolic activity of a secreted fungal virulence factor.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#61]
Curation link https://canto.phi-base.org/curs/7f79fa45d157bd97

This was started and also needs finishing

**Comment by CuzickA** [comment]
Hi @ValWood this one needs checking please.

There are a few queries within the comments sections of the annotations.

One of the queries relates to this mornings discussion about WT pathogen and WT host control metagenotype
![image](https://user-images.githubusercontent.com/11753634/87948952-4684b580-ca9d-11ea-863b-3641abe519a7.png)

In this case I am only curating one pathogen gene and one host gene (rather than 7 pathogen genes as in other example), so should these be specified as WT within the metagenotype or as WT pathogen and WT host?

**Comment by ValWood** [comment]
Session looks good.

I requested a GO term.
https://github.com/geneontology/go-ontology/issues/19848

I can also see that we will have many problems with these additional "layers of defense". I suspect Go will have many more changes around here but we can annotate the best we can and then migrate as approriate.

I see uniprot has apoplast IDA but we have TAS, is there no assay? (I could not see one but I did not check the SUPP data). If not this should be removed by Uniprot. If Uniprot is correct we do not need to duplicate from the same source

**Comment by CuzickA** [comment]
Hi @ValWood thanks for checking.

![image](https://user-images.githubusercontent.com/11753634/89048028-24195480-d347-11ea-87a1-dbf69412d47d.png)

> I see uniprot has apoplast IDA but we have TAS, is there no assay? (I could not see one but I did not check the SUPP data). If not this should be removed by Uniprot. If Uniprot is correct we do not need to duplicate from the same source

The UniProt annotation of IDA apoplast is for KWL1 not CMU1 here -is that ok?

**Comment by ValWood** [comment]
Oh yes sorry !

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/89049240-daca0480-d348-11ea-9da2-952fad6baa1a.png)

Answer to above query is that, yes, we will capture both the pathogen and host genes in the metagenotype.

I will now delete this query from the session

**Comment by CuzickA** [comment]
Added new GO term 'effector-mediated suppression of host salicylic acid-mediated innate immune signalling'
Added new PHIPO terms

Note in comments section there are notes about when possible new AE would be used 'AE Disease outcome' Disease present/absent

Approving session and closing ticket

**Comment by CuzickA** [comment]
Added disease curation

@ValWood Should the genotypes in this session be changed from 'overexpression' to 'not assayed'? The authors describe 'overexpression' in the methods but the expts do not compare WT vs overexpression genotypes?

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/112326999-f6ee2d80-8cac-11eb-899e-ad176a00b577.png)
![image](https://user-images.githubusercontent.com/11753634/112327110-0d948480-8cad-11eb-8895-8a93eb78bc6a.png)


@ValWood do you think the term labels should change here?
'abolished inhibition of pathogen chorismate mutase by host' -> inhibition of pathogen chorismate mutase by host absent
'inhibition of pathogen chorismate mutase by host' -> inhibition of pathogen chorismate mutase by host present

I thought we were trying not to use 'abolished' for the PHI branch terms anymore.

**Comment by CuzickA** [comment]
Couple of queries above to follow up then should be ready to approve.

**Comment by ValWood** [comment]
The label change sounds correct.

The overexpression should be "not assayed"  this is a bit like the 2-hybrid. The  expression level isn't really relevant

**Comment by CuzickA** [comment]
Thanks.

I have updated overexpression to not assayed.

May need to add a note to 'Help' about when to use 'overexpression'.

**Comment by CuzickA** [comment]
Just waiting for term label edits to load. 

Approving session for now and closing ticket

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/114373199-43c17780-9b7a-11eb-996e-0369b5229a61.png)

Terms labels correctly loaded

**Comment by CuzickA** [comment]
see #98 change GO CC 'apoplast' to 'host apoplast'
![image](https://user-images.githubusercontent.com/11753634/146189492-2329fbe6-7a23-47ab-9444-42bc5759ed8f.png)
![image](https://user-images.githubusercontent.com/11753634/146189621-b0dc47fa-f3ee-44b2-9e5e-0db07d74e9b8.png)

**Comment by CuzickA** [comment]
Hi @jseager7, whilst @smvelasquez was looking through this session and trying to recreate it herself, she found that she was unable to add the GO MF AE 'has_input'. When I looked at the session, I can see that it was added manually in Admin mode.
![image](https://user-images.githubusercontent.com/11753634/161241975-a345fe6d-b4dc-4ce7-a1fb-1013537999ee.png)

![image](https://user-images.githubusercontent.com/11753634/161241855-ee6d7ba6-2c74-4488-ad35-d8824ef0dc01.png)

Please could you make this AE available for curators?

**Comment by CuzickA** [comment]
@smvelasquez also noticed that the 'compared to control' AE metagenotype contains 'overexpression' instead of 'not assayed'. 
@jseager7 this is caused by the bug that means the metagenotypes in the AE are not automatically updated with the main metagenotype. 

In this case I will edit them manually. I don't know how may other sessions this has affected.

![image](https://user-images.githubusercontent.com/11753634/161245341-84866144-5a38-422c-af29-536d0553349b.png)

to
![image](https://user-images.githubusercontent.com/11753634/161245562-b8bf3783-eda7-4d98-803f-3f8327aba15b.png)

![image](https://user-images.githubusercontent.com/11753634/161245667-1c187be8-9019-497f-9268-e1578b0e2e51.png)

to
![image](https://user-images.githubusercontent.com/11753634/161245993-9d2c8cd8-1d2f-4483-8d36-253306574a18.png)

also changing the WT product to WT level whilst making these edits
![image](https://user-images.githubusercontent.com/11753634/161246144-6a1cebfc-b25f-46ad-b69c-baeb164efa64.png)

to
![image](https://user-images.githubusercontent.com/11753634/161246485-e6e77d42-5dbb-48b5-a7a1-bb69a565b89c.png)

**Comment by jseager7** [comment]
> she found that she was unable to add the GO MF AE 'has_input'. When I looked at the session, I can see that it was added manually in Admin mode [...] Please could you make this AE available for curators?

Looks like this is because the annotation extension configuration that we share with PomBase doesn't have 'enzyme inhibitor activity' (GO:0004857) in the range of the has_input extension. I'll have to add this to our own configuration instead.

**Comment by jseager7** [comment]
@CuzickA If you can think of any higher level term in GO (above GO:0004857) that might cover more terms that would need has_input on in future, please let me know. Here's the terms that are currently used by PomBase:

* cytoskeletal anchor activity (GO:0008093)
* protein-macromolecule adaptor activity (GO:0030674)
* pattern recognition receptor activity (GO:0038187)

**Comment by jseager7** [comment]
@smvelasquez The has_input extension is now available on GO:0004857 'enzyme inhibitor activity' and all its child terms. The extension appears as 'inhibits' in the annotation extension list.

![image](https://user-images.githubusercontent.com/37659591/163357031-970cf2eb-daf4-4829-ad5e-6bb2dbaeb0b5.png)

Sorry about the delay.

**Comment by CuzickA** [comment]
Thanks @jseager7. I'll check the session in Admin mode to see if this change has been made automatically or whether I need to make a manual transfer to the 'inhibits' extension.

**Comment by CuzickA** [comment]
Change was made automatically. Closing ticket.
