### ISSUE TITLE
PMID: 30148881 Structure of the Cladosporium fulvum Avr4 effector in complex with (GlcNAc)6 reveals the ligand-binding mechanism and uncouples its intrinsic function from recognition by the Cf-4 resistance protein.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#62]
https://canto.phi-base.org/curs/6dd9062354648dc7

**Comment by ValWood** [comment]
Reminder, I'm up to here

To determine if the reduced affinity for (GlcNAc)6 of the W100A, D102A, Q69N and K84A mutants was biologically meaningful, we evaluated whether they were able to protect germl- ings of Trichoderma viride against hydrolysis from chitinases and compared their protective potency to that of the WT-CfAvr4 (S7 Fig)

Can't add host
https://github.com/PHI-base/config/issues/34

**Comment by CuzickA** [comment]
Can curation of this session continue now the above query has been resolved @ValWood ?

**Comment by CuzickA** [comment]
@ValWood

**Comment by ValWood** [comment]
DOh, Trichoderma viride isn't the host. Its another fungus used in the assay...this might be tricky...

**Comment by ValWood** [comment]
Hi Alayne,
In this session, I am not sure  if I only need "pathogenicty present" or something more specific  under the virulence descendant. I can't remember the criteria. I think this probably needs some explanation...
Please advise.

**Comment by CuzickA** [comment]
Hi Val,
I started writing up some rough guide notes for curating gene-for-gene interactions at the bottom of this google doc on phenotype tips https://docs.google.com/document/d/1Nm5yAHMwFYfhjRWuatlGA4_X2aSK9l12QQI1ffQXFqs/edit

For easy viewing here is a copy of my rough/incomplete guide notes


_

> _AE Gene-for-gene interaction

> Aim and rough ‘how to curate’ notes
> To curate biotrophic and necrotrophic pathogens exhibiting gene-for-gene interactions with plant hosts

> 1)Select Annotation Extension (AE) ‘Gene-for-gene interaction’ and pick either ‘compatible interaction’ or ‘incompatible interaction’ dependent on the outcome of the gene-for-gene interaction within the metagenotype. Please aim to curate the ‘compatible interaction’ first as this provides a useful starting place to add the AE ‘disease caused’ where possible.
> (The raw ingredients of the pathogen genotype and the host genotype components of the metagenotype are captured in 2 and 3 below. The combination of these and the actual output is captured using ‘compatible interaction’ or ‘incompatible interaction’).

> 2)Select AE ‘infective ability’ and add details regarding the (raw ingredients of the) host genotype. These could be
> -host resistance present (exact synonym: host susceptibility absent)
> -host resistance absent (exact synonym: host susceptibility present)
> -loss of host resistance
> -gain of host resistance

> 3)Select AE ‘infective ability’ and add details regarding the (raw ingredients of the) pathogen genotype. These could be
> -pathogenicity present
> -pathogenicity absent
> -loss of pathogenicity
> -gain of pathogenicity
> 
> Use of AE ‘compared to control’ in ‘Gene-for-gene interactions’
> Explain…
> (note: this AE can also be used in non-gene-for-gene interactions)
> 
> Add further info and figures for ‘gene-for-gene’ and ‘inverse gene-for-gene’ punnett square relationships
> 
> ALso to note: Gene-for-gene AE to be used for both natural and non-natural delivery systems - information is extrapolated from the model expt being used._

_

Please let me know if anything is unclear as they notes still need some work.

**Comment by ValWood** [comment]
The piece of information I need is when I need to proceed to the "virulence" terms from "pathogenicity present"

These explanations aren't very clear to me. Perhaps we can discuss next time we speak

**Comment by CuzickA** [comment]
We were trying not to use the virulence terms for gene-for-gene interactions.

**Comment by ValWood** [comment]
> We were trying not to use the virulence terms for gene-for-gene interactions.

I had forgotten this.

This is what I have so far for 4a

<img width="902" alt="Screenshot 2020-07-20 at 16 01 52" src="https://user-images.githubusercontent.com/7359272/87953099-8732fd80-caa2-11ea-8d60-d61882bf1a57.png">

Woud this be correct?
I don't  seem to have a way to say that the effect is decreased without putting that into the phenotype. Is that what we decided to do?

**Comment by CuzickA** [comment]
I will have a go at making the control annotation for Fig 4a. We need to add the host resistance gene Cf4 to the metagenotype.

**Comment by CuzickA** [comment]
I wish it was easier to find UniProt ids... struggling with cf-4 tomato

**Comment by ValWood** [comment]
BUt they don't manipulate cf-4 so doesn't host WT cover it?
I did try to look earlier though and could not find it. I found cf4-a. But then I thought, its not relevant because they don't manipulate it.
Am I confused?

**Comment by ValWood** [comment]
Also I realised I am still confusing HR response with pathogenicity  when I haven't curated for a while. I removed the pathogenicity extensions....

**Comment by ValWood** [comment]
This is what I have now:
<img width="904" alt="Screenshot 2020-07-20 at 16 17 21" src="https://user-images.githubusercontent.com/7359272/87954631-88652a00-caa4-11ea-9bc4-8f46f54f5750.png">

**Comment by ValWood** [comment]
There must be earlier papers to  explicitly connect ACR4 to Cf-4?

**Comment by CuzickA** [comment]
To maximise the data here and let people know that this is a gene-for-gene interaction I think we should capture Cf-4.
on page 16 there is info that the plant strain/cv 'moneymaker' does not carry cf-4, whilst strain/cv 'purdue 135 does carry functional cf-4.

**Comment by ValWood** [comment]
>We were trying not to use the virulence terms for gene-for-gene interactions.

I had forgotten this. But I think also it will be a problem for users. How will they know? There needs to be a way of preventing users from doing both... Or maybe they will not try to do infective ability, since  that was just wrong here?

**Comment by CuzickA** [comment]
For the top annotation I would have 
WT avr4 Wt Cf-4,  HR present,  incompatible, pathogenic ability present, host resistance present

**Comment by CuzickA** [comment]
We will need to have clear instructions for curators. I started making the above notes regarding 'gene-for-gene interactions' as it follows a different structure to other types of annotations.

**Comment by ValWood** [comment]
> To maximise the data here and let people know that this is a gene-for-gene interaction I think we should capture Cf-4.
on page 16 there is info that the plant strain/cv 'moneymaker' does not carry cf-4, whilst strain/cv 'purdue 135 does carry functional cf-4.

This is a good point. However, I wonder if users will do this automatically. It's a weird one. Its bringing in knowledge from a previous paper, which is not included in the experiment.  I don't have a problem with this per. se. if this is what the authors are intending to demonstrate,   but  from this paper who is to say that  cf4 presence-absence in these strains is responsible for the difference. This could be correlation, not causation?

**Comment by ValWood** [comment]
> We will need to have clear instructions for curators. I started making the above notes regarding 'gene-for-gene interactions' as it follows a different structure to other types of annotations.

yes the problem was that I went straight for the infective ability because I forgot about the 'gene for gene 'option.

Maybe there could be a way to make infective ability unavailable if gene-for-gene has been used?

**Comment by CuzickA** [comment]
We will need both AE gene-for-gene AND AE infective ability for these annotations.

**Comment by CuzickA** [comment]
Perhaps we could have a user prompt asking whether the annotation is for a gene-for-gene interaction -maybe when they are making the metagenotype??

**Comment by CuzickA** [comment]
We would also like to capture the host gene information/UniProt so that we can display host gene-centric pages.

**Comment by ValWood** [comment]
I'm happy to capture the host gene information from the following experiment in exogenous host:


To discriminate between these two possibilities, we next transiently co-expressed Cf-4 with WT-CfAvr4 or its individual mutant alleles into leaves of Nicotiana benthamiana, using an Agrobacterium tumefaciens-mediated transformation assay (ATTA) [20]. Cf-4:effector co-infiltrations at cell densities of A6000.5:A6001.0 (0.5:1 ratio), A6000.5:A6000.5 (1:1 ratio), and A6000.5: A6000.25 (2:1 ratio) all induced an HR in the infiltrated leaf sectors thus resolving that none of our mutants can effectively escape recognition by Cf-4 when present in sufficient amounts in the leaf apoplast (Fig 4B, S9B Fig and S2 Table).

We can decide in checking if it should also be inserted into he 4a curation

**Comment by ValWood** [comment]
> We will need both AE gene-for-gene AND AE infective ability for these annotations.
OK in this case I'm not sure which "infective ability" to use for the "decreased"

**Comment by ValWood** [comment]
Anyway I am stuck because I don't know which protein tomato cf-4 is.
I'm going to mail the authors and continue once they provide the accession number.

**Comment by CuzickA** [comment]
> Anyway I am stuck because I don't know which protein tomato cf-4 is.
I'm going to mail the authors and continue once they provide the accession number.
 
Ok, I may go ahead using the Cf-4a uniprot as a holding id to mock up some of fig 4

**Comment by ValWood** [comment]
> For the top annotation I would have
WT avr4 Wt Cf-4, HR present, incompatible, pathogenic ability present, host resistance present

OK that makes sense. We would not capture that host resistance was reduced though. Is that OK?

**Comment by ValWood** [comment]
Summarizing the thread. I will document the issues here because I felt like a novice user today. These could be places where people will struggle.

1.  I forgot that I needed to do "gene for gene" and "infective ability"
@CuzickA suggested  a user prompt asking whether the annotation is for a gene-for-gene interaction -maybe when they are making the metagenotype??
(VW This might not be an issue it could be just me)

2. I am still struggling with which infective ability terms to use when
virulence terms should not be used with the gene-for-gene. I'm not sure that currently, this will be clear to the users

3. I could not capture a reduction in host resistance

4. @CuzickA  suggested  WT avr4 Wt Cf-4, HR present, incompatible, pathogenic ability present, host resistance present for figure 4a, this information is required for the  host centric gene pages

5. @ValWood  questions whether we  should be including the WT gene in the gene for gene from these particular experiments  (My main issue is that other genes could be responsible  ) (also there should be earlier papers to curate which demonstrate the gene for gene interaction)

6. This session might be a useful one to discuss where or if we have redundant information from the extensions on a future call...

**Comment by CuzickA** [comment]
> OK that makes sense. We would not capture that host resistance was reduced though. Is that OK?

Following the rough rules for gene-for-gene curation that Kim and I ran through we would still capture that 'host resistance was present' as in Fig 4a there were no changes to the host genotype (raw ingredient). The outcome of the metagenotype interaction is captured by compatible/incompatible (susceptibility/resistance).

**Comment by CuzickA** [comment]
The draft modelling of the 'gene-for-gene interactions' worked well for 3/4 of the previous gene-for-gene sessions examples. It did not fit so well for the atr1/rpp1 paper and there are still some issues to resolve. I approved these 4 sessions to generate the JSON exports for MC although some future changes may still need to be made.
Here are the session links
https://canto.phi-base.org/curs/f41d30e250b8f9b0/ro/
https://canto.phi-base.org/curs/bd02fdb6831712ca/ro/
https://canto.phi-base.org/curs/69e99b22bfebf3b0/ro/
https://canto.phi-base.org/curs/59484877a87d5786/ro/

It would be good to run through these when we chat on Monday

**Comment by ValWood** [comment]
OK that makes sense. We would not capture that host resistance was reduced though. Is that OK?

> Following the rough rules for gene-for-gene curation that Kim and I ran through we would still capture that 'host resistance was present' as in Fig 4a there were no changes to the host genotype (raw ingredient). The outcome of the metagenotype interaction is captured by compatible/incompatible (susceptibility/resistance).


what I mean was that virulence was reduced in the mutants. I can't remem ber if we said we were not bothered about reporting that...

**Comment by CuzickA** [comment]
This is what I mocked up

![image](https://user-images.githubusercontent.com/11753634/88389248-016ac700-cdae-11ea-9469-f77ceda0e88b.png)

In the second row we need a new PHIPO term to indicate decreased HR, as the HR is still present and the interaction incompatible/resistant (? as HR is still present).
In the third row the HR is abolished and the gene-for-gene interaction has shifted from incompatible/resistance to compatible/susceptible.

Capturing the 'virulence' was one of the tricky issues I also encountered in the other 'gene-for-gene interactions' in the links above. To make the curation guidelines clear for users I was hoping not to need to record 'virulence' for the 'gene-for-gene interactions'and to make some clear work flows for different annotation types. This may need to be re-visited.

**Comment by CuzickA** [comment]
This session needs revisiting and updating with latest thoughts on 'gene-for-gene' curation and recording of 'NV' or 'EV'.

**Comment by CuzickA** [comment]
See #82 
1) Removing Val's old AEs related to GfG (all data above in screenshots), so that old AE options can be deleted.
2) Replacing the GfG I added with new compound terms. (still need reviewing when finish curating this session)
3) In future these annotations will be switched to the GfG phenotype workflow instead of the PHI phenotype workflow.

**Comment by ValWood** [comment]
Hi @CuzickA  

I was going through this session as it is one of those still assigned to me.
I got stuck at the "gene-for-gene'. 

It wasn't immediately obvious to me how we could do gene for gene here as the  R-gene inferences were indirect. After a while, I realised that it could be annotated as gene-for-gene because they did a side by side comparison of this host with a strain known not to have this effector. Maybe there can be a list of "requirements" for making a gene for gene annotation in the docs?
a) direct (physical) interaction between effector and R gene
b) Comparison of phenotypic effect of effector on known host R gene +/Rgene - strains
c) others

I think you might need to talk me through the current  'split' of the annotations between multigene and gene-for-gene and how I make that call? Could we do that tomorrow?

Also, could you close any comments   above that  aren't  relevant to  this curation session directly or are  otherwise out of date (I think some of it is now obsolete, so I'm finding it difficult to follow what I should be doing)

Finally, is the document "phenotype tips" the most current document for curation guidelines? If so I have bookmarked this and will add to it as I go along.

**Comment by ValWood** [comment]
I think you have already migrated the annotations and we just need to get rid of the old ones./ I will check on this basis and hopefully a quick discussion tomorrow...

**Comment by CuzickA** [comment]
'Finally, is the document "phenotype tips" the most current document for curation guidelines? If so I have bookmarked this and will add to it as I go along.'

Yes and its already out of date with our new AE GfG

**Comment by CuzickA** [comment]
> I think you have already migrated the annotations and we just need to get rid of the old ones./ I will check on this basis and hopefully a quick discussion tomorrow...

Your first 3 old annotations under the PHI-branch can be deleted, the lower ones need to be migrated to the GfG branch. 

A while a go I just made the first couple of GfG annotations as a bit of a template to follow for Fig 4a. The rest of Fig 4 still needs curating if you would like to have a go?

I can chat first thing tomorrow morning if that helps

**Comment by ValWood** [comment]
Yes I think I figured. Would still like a quick run-through when done. I switched to another one now.

**Comment by ValWood** [comment]
I finished this session. The gene-for gene was OK (easier than I expected).
I agree with Chris that it would be nicer if these  extensions were selected hierarchically instead of precomposed, but that would require major work and is out of scope right now.

I wonder if we can somehow do anything here so that the extensions are presented in a slightly different order that would  make people more likely to select the right one (if we could put any which might be most likely to be selected incorrectly near to the bottom of the list for example), but really they need to read them all before they make a selection.

For this session there is only one task to add the  phenotypes added to PHIPO today.

**Comment by ValWood** [comment]
I'll unassign myself from this one.

**Comment by CuzickA** [comment]
Hi @ValWood is this session ready for me to check?

**Comment by ValWood** [comment]
yes I think so.

**Comment by CuzickA** [comment]
Interesting to see how you annotated these expts 'To determine if the reduced affinity for (GlcNAc)6 of the W100A, D102A, Q69N and K84A mutants was biologically meaningful, we evaluated whether they were able to protect germlings of Trichoderma viride against hydrolysis from chitinases and compared their protective potency to that of the WT-CfAvr4 (S7 Fig)'

I have come across similar and was unsure how to annotate

![image](https://user-images.githubusercontent.com/11753634/107385125-87e8bb00-6aea-11eb-8672-90ea49c6bfb8.png)

_We discussed this 08_03_2021 and this seems correct within the single species, as there is no host to create a metagenotype. The Trichoderma is just a tool in an enzyme assay_

**Comment by CuzickA** [comment]
1) I have added a few annotations including 
host -Cf4 as a control metagenotype
and tobaccco assay expts. in Fig 4b

2) @ValWood  Do you think we can annotate Fig 4c about mutants being vulnerable to proteolytic degradation?

![image](https://user-images.githubusercontent.com/11753634/107385641-fcbbf500-6aea-11eb-95b0-96fa162255f7.png)


3) I also have a query about the GfG AE used _(see below for updated annotations AC 26_02_2021)_
![image](https://user-images.githubusercontent.com/11753634/107386348-ad29f900-6aeb-11eb-9d5a-3227bb639b37.png)
Do they look correct? 
In the 3rd annotation here perhaps it  should be 'compatible interaction, compromised recognizable pathogen effector, functional host resistance gene present' instead of 'compatible interaction, recognizable pathogen effector absent, functional host resistance gene present' as the pathogen effector has been altered (engineered variant).

4) We need to identify a consistent set of rules for using the GfG (and inverse GfG) AE.

**Comment by CuzickA** [comment]
No AE causes_disease
Added
![image](https://user-images.githubusercontent.com/11753634/107774397-d7232b80-6d36-11eb-8eaa-a70bb5662527.png)

**Comment by CuzickA** [comment]
> 3. I also have a query about the GfG AE used
image _see above_
Do they look correct?
In the 3rd annotation here perhaps it should be 'compatible interaction, compromised recognizable pathogen effector, functional host resistance gene present' instead of 'compatible interaction, recognizable pathogen effector absent, functional host resistance gene present' as the pathogen effector has been altered (engineered variant).


I have now updated to below
![image](https://user-images.githubusercontent.com/11753634/109311903-4c662480-783e-11eb-964d-ca9db0705dfc.png)

**Comment by CuzickA** [comment]
This session still needs 

1) NTR: compatible interaction, compromised recognizable pathogen effector, functional host resistance gene present

2) Discuss query on which GfG AE to use when an alteration to a gene causes a partial phenotype shift. eg 
![image](https://user-images.githubusercontent.com/11753634/109312783-59cfde80-783f-11eb-90b5-96ad2c37b63b.png)
or no phenotype shift eg
![image](https://user-images.githubusercontent.com/11753634/109313668-5be66d00-7840-11eb-9e45-608c7420bf86.png)
Are we happy with the GfG AE that I have used in both of these cases?

**Comment by CuzickA** [comment]
See notes at bottom of this document
section subheading 'Draft GfG Rules (10_02_2021)'
https://docs.google.com/document/d/1Nm5yAHMwFYfhjRWuatlGA4_X2aSK9l12QQI1ffQXFqs/edit

**Comment by CuzickA** [comment]
waiting for 
1) NTR: compatible interaction, compromised recognizable pathogen effector, functional host resistance gene present
2) Emailed Kim H-K about first part of  query above ( partial shift in phenotype) (may need to follow up with no shift query)

**Comment by CuzickA** [comment]
Added NTR: compatible interaction, compromised recognizable pathogen effector, functional host resistance gene present

Waiting for response from Kim H-K to email about above.

Approving session for now but will keep ticket open with tag 'AE 'GeneforGene' query'
regarding 'partial shift in phenotype'

**Comment by CuzickA** [comment]
_Copy to email sent to Kim 03_03_2021 for reference_

Question on partial phenotype shift in GfG avr4/Cf4

Dear Kim,
I have now finished my part in the PHI-base 4.11 spreadsheet clean-up and have passed the spreadsheet over to James to work on the strains and diseases for the latest 6 months of data.

I have been reviewing the Biotrophic Gene-for-Gene interaction curation sessions.
I have a good understanding of curating the control interactions, starting with the incompatible and then moving onto the compatible interactions. 
In the papers where the altered metagenotypes phenotypes are clear shifts from incompatible to compatible or vice versa the GfG AE is straightforward. 
In the cases where the altered metagenotypes results in a phenotype that is the same as the control or there is a slight shift in phenotype but no alteration to the compatibility / incompatibility compared to the WT control it can be more tricky to choose the correct GfG AE and therefore develop a set of rules for users.  
For example
 
![image](https://user-images.githubusercontent.com/11753634/110116058-dff3a400-7dae-11eb-9115-ecfbe812f184.png)

The 1st annotation is the incompatible control with HR
The 2nd annotation has altered avr4 which could be classed as either ‘recognizable pathogen effector present’ or ‘compromised recognizable pathogen effector’. In this case I have chosen ‘recognizable pathogen effector present’ as there is an HR. (unlike the 3rd annotation).
The 3rd annotation has altered avr4 which results in a shift from incompatible to compatible and it is clear that ‘compromised recognizable pathogen effector’ is the correct option.

Please let me know if you agree with this or would you do something different here?

I have another query for the ATR1 / RPP1 paper which I will send in another email so that the emails are specific to each question and don’t get too long.

Best wishes,
Alayne

**Comment by CuzickA** [comment]
After discussion with Kim H-K on 25March2021 regarding my email query above we decided that my suggested annotations were correct.
Closing this ticket.

**Comment by CuzickA** [comment]
> Interesting to see how you annotated these expts 'To determine if the reduced affinity for (GlcNAc)6 of the W100A, D102A, Q69N and K84A mutants was biologically meaningful, we evaluated whether they were able to protect germlings of Trichoderma viride against hydrolysis from chitinases and compared their protective potency to that of the WT-CfAvr4 (S7 Fig)'
> 
> I have come across similar and was unsure how to annotate
> 
> ![image](https://user-images.githubusercontent.com/11753634/107385125-87e8bb00-6aea-11eb-8672-90ea49c6bfb8.png)
> 
> _We discussed this 08_03_2021 and this seems correct within the single species, as there is no host to create a metagenotype. The Trichoderma is just a tool in an enzyme assay_

This needs to move into metagenotype section with Tomato cells as host

**Comment by CuzickA** [comment]
and update PHIPO terms -see google doc for notes

**Comment by CuzickA** [comment]
Hi @ValWood I've just seen this and it looks like there is no host involved in this paper so we probably need to leave the Trichoderma annotations where they are in the singles species section. Maybe we should add '+ chitinase' to the conditions. These single species PHIPO terms will also still need some work.

I am still going to make the NTRs we have just discussed for the chitin hydrolysis for the LysM1 paper as this DOES mention a host and needs to be annotated as a metagenotype.

![image](https://user-images.githubusercontent.com/11753634/116235252-87f57000-a755-11eb-8c7c-98ce7ba6c3bd.png)

**Comment by CuzickA** [comment]
@jseager7 please could you check which sessions these terms have been used in 

PHIPO:0001225 abolished PAMP receptor decoy activity
PHIPO:0001224 decreased PAMP receptor decoy activity

**Comment by jseager7** [comment]
@CuzickA Here's the sessions:

- PHIPO:0001225 'abolished PAMP receptor decoy activity'
  - [PMID:30148881](https://canto.phi-base.org/curs/6dd9062354648dc7)
- PHIPO:0001224 'decreased PAMP receptor decoy activity'
  - [PMID:30148881](https://canto.phi-base.org/curs/6dd9062354648dc7)

**Comment by CuzickA** [comment]
Great, thanks

**Comment by CuzickA** [comment]
Fig S7
![image](https://user-images.githubusercontent.com/11753634/116408767-1982e180-a82b-11eb-9fe1-1a628ca12e64.png)

![image](https://user-images.githubusercontent.com/11753634/116408689-05d77b00-a82b-11eb-9c67-dbd590944575.png)


abolished PAMP receptor decoy activity -> chitin hydrolysis present
![image](https://user-images.githubusercontent.com/11753634/116409181-80a09600-a82b-11eb-8829-19ee8cf9352a.png)

decreased PAMP receptor decoy activity -> increased chitin hydrolysis present @ValWood is this correct? (increased compared to 'chitin hydrolysis absent' WT but we don't curate controls for single species genotypes)
![image](https://user-images.githubusercontent.com/11753634/116410248-7cc14380-a82c-11eb-811b-e9d6940292b2.png)

**Comment by ValWood** [comment]
I guess we could add a WT genotype, and then add compared to WT here, without specifically making the control annotation? I think the control annotation would be overkill.

**Comment by CuzickA** [comment]
I have added this WT control annotation (look at term suggestion) to make thinks clearer for this expt. There is no AE compared to control option for the single species annotations but I think this is okay.

![image](https://user-images.githubusercontent.com/11753634/116676271-b023df80-a99e-11eb-8b36-af8ff761e386.png)


I will now go ahead and make/edit the single species PHIPO terms https://github.com/PHI-base/phipo/issues/336

**Comment by CuzickA** [comment]
Terms added
![image](https://user-images.githubusercontent.com/11753634/117137537-c3212000-ada1-11eb-953c-62fb15b8094a.png)


session approved, closing ticket
