### ISSUE TITLE
Simplify 'media' in conditions (PHI-ECO) for PHI-Canto curations

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#63]
@ValWood has suggested that we have been capturing more information on the types of experimental media used in the conditions than that of PomBase curators. This may be because with 250+ pathogen species there are a lot of different types of media. 

The concern is that it takes more time for the curators to add this level detail and for us to add the requested terms into PHI-ECO.

Talking with @martin2urban today we thought it would be a good idea to reduced the media conditions options down to
Minimal medium
Rich medium
Water medium

and still use 'agar plates' and 'liquid culture' condition terms when relevant to observed phenotype.

Specific types of media could be added as related synonyms or as text comments to the annotation.

Initial notes on media definitions are as follows

Minimal medium
Text def: Experiments were performed in defined minimal medium which has just enough ingredients to support growth. (The number of ingredients that must be added to a minimal medium varies enormously depending on which microorganism is being grown). Typically contains a simple carbon source, salts and water.
Synonyms: Sucrose nutrient deficient agar (SNA), NO WATER AGAR (keep separate), M9 minimal medium,  
Wiki https://en.wikipedia.org/wiki/Growth_medium#Minimal_media

Rich medium:
Rich media contain the nutrients required to support the growth of a wide variety of organisms containing complex carbon sources (Sugars, peptides etc).  It is an undefined medium that has some complex ingredients, such as yeast extract, which consists of a mixture of many chemicals in unknown proportions. 
Synonym: complex medium, complete medium,  Blood agar, Chocolate agar, Potato dextrose agar (PDA), carboxymethylcellulose medium (CMC) , MacConkey agar, Lowenstein-Jensen medium, trichotoxine induction medium, starch yeast medium, carrot agar, oat meal medium, mung bean medium, yeast extract peptone agar, plant extract agar, potato slice,

**Comment by CuzickA** [comment]
Current screenshots of PHI-ECO 'grouping growth medium'
![image](https://user-images.githubusercontent.com/11753634/72348080-79568700-36d1-11ea-8d89-a3c459c05fa6.png)
![image](https://user-images.githubusercontent.com/11753634/72348106-88d5d000-36d1-11ea-9ee7-5fc8bc9b5f40.png)

**Comment by CuzickA** [comment]
Add to 'minimal medium' PECO:0005020
text def: Experiments were performed in defined minimal medium which has just enough ingredients to support growth. (The number of ingredients that must be added to a minimal medium varies enormously depending on which microorganism is being grown). Typically contains a simple carbon source, salts and water.
exact synonyms: M9 minimal medium, synthetic nutrient-poor agar (SNA)

3a2da30

**Comment by CuzickA** [comment]
NTR: rich medium PECO:0005031
text def: Rich media contain the nutrients required to support the growth of a wide variety of organisms containing complex carbon sources (Sugars, peptides etc). It is an undefined medium that has some complex ingredients, such as yeast extract, which consists of a mixture of many chemicals in unknown proportions.
exact synonyms: numerous as suggested above

16a65e1

**Comment by CuzickA** [comment]
Next step:
to merge and obsolete terms so that only have
rich medium
minimal medium
water medium
agar plate
liquid culture

**Comment by CuzickA** [comment]
merge 'carrot medium' PECO:0005026   into 'rich medium' PECO:0005031 143fd41
merge 'complete medium' PECO:0005022   into 'rich medium' PECO:0005031 501260c
merge 'potato dextrose medium' PECO:0005021   into 'rich medium' PECO:0005031 ab83e08
merge 'trichothecene biosynthesis medium' PECO:0005025   into 'rich medium' PECO:0005031  8231bd1
merge 'starch yeast medium' PECO:0005023   into 'rich medium' PECO:0005031 f3a0a72
move 'rich medium' PECO:0005031 23a811e
merge 'YES' PECO:0000137 into 'rich medium' PECO:0005031 NOT WORKING
merge 'YPD' PECO:0000201 into 'rich medium' PECO:0005031 NOT WORKING
looks like I cannot merge terms created by Antonia into terms that I have created.

**Comment by CuzickA** [comment]
@jseager7 please look into IRI changes for PECO to enable merging

**Comment by jseager7** [comment]
I've fixed this in PHI-ECO now by correcting a lot of absent or incorrect IRI prefixes. From now on, the terms should merge correctly as long as they follow this pattern:

`http://purl.obolibrary.org/obo/PECO_0000000`

**Comment by CuzickA** [comment]
'rich medium' has a new id
it was PECO:0005031 and is now PECO:0005224 as part of the IRI renaming fix above.

**Comment by CuzickA** [comment]
merge 'YES' PECO:0000137 into 'rich medium' PECO:0005224 5b687a2
merge 'YPD' PECO:0000201 into 'rich medium' PECO:0005224 d3b7845

merging now working but pay attention to delete duplicate ids, namespaces and creation dates

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/72617445-e0be4200-3930-11ea-83e8-6201809242f4.png)

@martin2urban @ValWood 
I have merged some of the media terms into 'rich medium' as discussed. In the screenshot there are still 8 additional media terms used by the PomBase team but I am pretty sure we have not used them in PHI-Canto yet. The aim is to only have 'rich medium' in this branch. It would be easier for me to obsolete these terms rather than merge them into 'rich medium'. Please could you let me know whether you think it would be ok to obsolete them or if it would be preferable to merge them. The following comment is looking at the 'minimal medium' branch.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/72618177-73abac00-3932-11ea-8c84-1af492a73254.png)
In this branch we are aiming to have 2 terms 'minimal medium' and 'water medium'.
@martin2urban and @ValWood please advise as to whether the remaining terms in this branch could be obsoleted or require merging into 'minimal medium'. Again, I don't think they have been used in PHI-Canto curation sessions so it would be possible to obsolete them (and much quicker).

**Comment by ValWood** [comment]
@martin2urban  will be able to advise better

**Comment by martin2urban** [comment]
Obsoleting the remaining terms will be fine.

**Comment by CuzickA** [comment]
obsolete
PECO:0000144
PECO:0000136
PECO:0000236
PECO:0000081
PECO:0000162
PECO:0000138
PECO:0000139
PECO:0000148

e58d8a2

**Comment by CuzickA** [comment]
obsolete
PECO:0000073
PECO:0000289
PECO:0000262
PECO:0000126
PECO:0000274
PECO:0000254
PECO:0000331
PECO:0000263
PECO:0000278
PECO:0000286
PECO:0000273
PECO:0000272
PECO:0000264
PECO:0000296
PECO:0000246
PECO:0000276
PECO:0000196
PECO:0000266
PECO:0000054
PECO:0000256
PECO:0000072
PECO:0000016
PECO:0000328
PECO:0000104
PECO:0000230
PECO:0000145
PECO:0000015
PECO:0000147
PECO:0000146

d7834dd


obsolete
non-fermentable carbon sources medium PECO:0000213  051ceb3

**Comment by CuzickA** [comment]
Now looks like this

![image](https://user-images.githubusercontent.com/11753634/72717315-b2787680-3b6b-11ea-8783-ff58680c9bf0.png)
