### ISSUE TITLE
PMID:31246152 The Synchytrium endobioticum AvrSen1 Triggers a Hypersensitive Response in Sen1 Potatoes While Natural Variants Evade Detection.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#65]
curation link 
https://canto.phi-base.org/curs/59484877a87d5786

Author contacted PHI-base and requested article to be curated.
I have had a go at curating this paper into PHI-Canto and added queries into the comment section of the annotations.

The pathogen 'mutant' genotypes have been identified as natural strain variants (and grouped into pathotypes). 
This has caused difficulties in the past for PHI-base curation and a temporary evidence code for 'natural variation was created' rather than deletion etc.
In PHI-Canto do we need to specify whether the genotype arose from natural strain variation or was created within the lab?

Just to note:
Pathogen AvrSen1 triggers an HR in the presence of host Resistance gene Sen1. 
Sen1 has not yet been isolated so there is no uniprot. Presence or absence of the Sen1 locus in the host strain is determined by markers generated from mapping populations.

@ValWood please check this session when you have time.

**Comment by ValWood** [comment]
The phenotypes all looked fine.

I was confused by the "loss of pathogenicity" here.
AvrSen1ΔSP(1-30)[Unknown]S. endobioticum(MB42) | wild typeS. tuberosum(Desiree) | PHIPO:0000192 | presence of host HR induced by pathogen during biotrophic lifestyle | Macroscopic observation (quantitative observation) | | infects_tissue leaf , infective_ability loss of pathogenicity |

Can you talk me through this and your comment above on the next call?

I  added "discuss" label

**Comment by CuzickA** [comment]
Notes from curation session
1. disease caused is potato wart which is not currently an option. _requested on phido tracker__DONE_

2. potato avantra is a susceptible strain, it does not contain resistance gene Sen1 (not yet cloned, therefore no uniprot) as verified by markers. Whereas potato desiree is a resistant strain and contains Sen1. This is an example where we want to capture (as a genotype comment?) that a host strain is susceptible or resistant, as this also depends on the pathogen genotype it may be better to record this comment as part of the metagenotype using 'compatible (susceptible interaction) / incompatible (resistant interaction)' as briefly discussed with @ValWood. 
https://github.com/PHI-base/curation/issues/78

3. is it absence or abolished HR (see metagenotype below)? naturally no Resistance gene in this case so no HR possible. (I have used abolished for the avrsen1 variants genotypes later in the session.)
![image](https://user-images.githubusercontent.com/11753634/76619106-0a0ae100-6522-11ea-863a-99004a02d746.png)
(Note: sometimes i find that when the alteration is on the host side it is not so straight forward to select the correct terms.)

4. needs AE for effector. _Now added_ 

5. Can we capture genetic interaction between avr-R? There were no physical interaction assays as host gene not cloned yet. _No as R gene not cloned, no UniPort_

6. can AE infective ability be added to any of the annotations? 
Below is a bit tricky
![image](https://user-images.githubusercontent.com/11753634/76619287-65d56a00-6522-11ea-804b-bbd9a31d856f.png)
The host R (Sen1) gene is naturally present (but not cloned so no uniprot) therefore can recognise pathogen avrSen1 and trigger ETI/HR. This means that the pathogen has 'lost pathogenicity' on this host but NOT on a susceptible host lacking functional R gene (Sen1).
Perhaps it would be better to use 'pathogenicity present' or 'pathogenicity absent' for these WT CONTROL interactions. However, we defined pathogenicity as a property of the pathogen and not the metagenotype. This is an example of where a new term for 'avirulence' could be useful (but has its own complications).


@ValWood lets discuss during one of our meetings.
I have made edits and added new annotations to this session.

**Comment by CuzickA** [comment]
@ValWood we still need to discuss a few queries for this session

**Comment by CuzickA** [comment]
@ValWood Adding AE 'infective ability' is still tricky. For now I have added
'Pathogenicity absent'
'Pathogenicity present'
for the 2 controls (Susceptible host and resistant host)
![image](https://user-images.githubusercontent.com/11753634/84759806-20ac5280-afbf-11ea-9071-dfa9c3e22390.png)

and 'gain of pathogenicity' for below 
![image](https://user-images.githubusercontent.com/11753634/84760832-7fbe9700-afc0-11ea-9041-2559b3deb979.png)


This still does not seem quite right so I have added a 'review AE 'infective ability' ' label to this ticket so that we can come back to it in the future after more sessions have been curated.

Approving and closing ticket for now.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/85406140-45716e80-b559-11ea-9e74-cb8d457503c0.png)

@ValWood After our recent discussion about 'natural variants' this session seems incorrect.

Following our recent thoughts the pathogen variant 1 and variant 2 (annotation 3 and 4) information does not belong in the genotype. The genotypes should just be partial aa deletion for delta signal peptide for the different strains and the variant detail recorded in the comments.

Do these proposed changes seem reasonable?

The phenotypes and AE may also need to change from 'abolished ....' to 'absence of ...' and 'gain of pathogenicity' to 'pathogenicity absent'.

We could also make use of the new AE for host resistance absence/present and Gene-for-gene interaction compatible/incompatible

**Comment by ValWood** [comment]
Yes you are right. If these are natural variations they should be in the comment.

It would be nice if we  had a standard way to record this
 something like (WT,natural variation A256 ->stop)
and a synonym could be added AvrSenΔSP WT,natural variation A256 ->stop

(ANother complication! it isn't absolutely necessary but it might be useful on your pages if the natural variation is known. I'm not sure it would be sustainable for those with many variations though. The sequence itself should be the reference point.

Maybe this is a question for the call?

**Comment by CuzickA** [comment]
I have update the genotypes as suggested above. 
I have also added new information for AEs
gene-for-gene interaction compatible or incompatible (even though host SEN1 gene not cloned yet)
infective ability for pathogen (pathogenicity present/absent etc) and host (resistance present/absent etc)

There is still a query for the 3rd and 4th annotataion noted here
Query.. pathogenicity present, host resistant gene present = compatible is this clear enough that host unable to recognise pathogen variant? -YES OK FOR NOW

Approving session and closing ticket for now

**Comment by ValWood** [comment]
Is this correct?

<img width="916" alt="Screen Shot 2020-07-31 at 17 33 44" src="https://user-images.githubusercontent.com/7359272/89056551-18805a80-d354-11ea-86b1-80e9cd7a4bfe.png">



should it be "host resistance absent"

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/89160952-cc0e6800-d569-11ea-8b75-fa24cdb04bf2.png)

I used "host resistance present" as the SEN1 gene is present in the potato strain 'desiree'.
In the comment section I have noted that this is a tricky one. The host is unable to recognise the pathogen strain LEV6574 to mount HR.

**Comment by ValWood** [comment]
There seems to be a logic issue here?
Is host resistance is present is shouldn't be diseased?

I don't fully understand the comment though. We should look at this.

**Comment by ValWood** [comment]
I'm still a bit confused about the qualifiers, but I'm more certain about one thing. We shouldn't be describing these natural variants as WT.

see for example

<img width="948" alt="Screenshot 2020-08-10 at 13 56 06" src="https://user-images.githubusercontent.com/7359272/89785057-af49d580-db11-11ea-8b50-41b2bde7100d.png">

and

<img width="967" alt="Screenshot 2020-08-10 at 13 55 40" src="https://user-images.githubusercontent.com/7359272/89785074-b2dd5c80-db11-11ea-857c-0dd836029e77.png">


Thes are natural variants, but they  don't appear to be the WT alleles for the strain, they are  non-functional variants in some isolates. Maybe we need to move away from calling any strain "WT" and just calling it "reference" in these situations. Apparently there are 39 'pathotypes' identified D1 the original, 2G1 identified in 1941 and  37 others ( 6(01) and 18(T1) being most prevalent.

In this case I think the changes should be described, and compared to some reference WT species. Presumably, even some of these strains will also harbour the WT allele so maybe it is safe just to describe them as the non-WT allele for this gene and name them according to this schema? (I.e varant 5, etc)

**Comment by ValWood** [comment]
If we did this how would the pathogenic ability change ?

**Comment by ValWood** [comment]
I think I understand the problem.....

Virulence factors do something to contribute to the disease causing process
Some potatoes have a resistance gene that causes HR, and mitigates disease.
However in the case of the isolate S. endobioticum
(LEV6574) in this assay, we know that  LEV6574  has a natural variant  that can not initiate HR

BUT we don't know if this particular  isolate causes disease ( it might not be able to cause disease because AVrSen1 is non functional? - it depends how necessary a functioning and non-recognisable sen1 is necessary for pathogenicity)

So it seems that we can't say  "pathogenic ability present" from these assays because this is something which applies to the pathogen, not to this particular variant. We would need to see that the diseased potato  all we are seeing is a presence or absence of HR (i.e compatibility/ incompatibility). 

Is it  really  safe assumption that this lack of HR will lead to pathogenicity?


If so:
The pathogen variant ( the actual variant )
pathogenic ability present (an assumption based on this variant, not the organism because that was not tested)
host resistance present
incompatible interaction.

The curation seems  odd It seems odd because it is a   "compatible interaction" but it's 
"resistance gene-independent"

I assume you can only get this particular combination if the pathogenicity is resistance gene-independent. Do you think that database users will understand that combination? Maybe they will  (It took me a while!)

If  this is all correct,  and you agree that we need to record the variant could you:

1) change the genotypes accordingly for the natural isolates (more like what you had on 23rd June). We thought these represented WT variants for the strain but apparently not. Even if they did represent the "WT" for a reference strain, I think it will be OK to describe the variation with  respect to some fixed reference point in a reference strain (which may or may not be the same strain). 
It would  also be useful to include in the name which of the known 39 pathotypes this is (D1, 2G1 etc) in the brackets with the variant number if there is a correspondence between these....it is something people may search on in the database and it will make it easier to locate genotypes in Canto.
2) close off and hide any out of date parts of this ticket
3) Discuss with Martin and Kim if users will understand this combination without explicitly stating that it is ""resistance gene-independent" (if this is the only  outcome of this combination you could infer this additional information on your gene pages?)

**Comment by CuzickA** [comment]
I have
altered the genotype
added the 'Fig' column
absence/presence terms are used rather than abolished
removed 'compared to control'
edited pathogen infective ability

It now looks like this 
@ValWood can we review this when we chat on Monday

![image](https://user-images.githubusercontent.com/11753634/94271082-075d5f80-ff39-11ea-8b75-afe838514cd3.png)


Note: UniProt uses strain MB42 as its reference proteome
![image](https://user-images.githubusercontent.com/11753634/94270558-21e30900-ff38-11ea-8c77-77eee7ec8109.png)

The UniProt id for avr1sen1 from MB42 was used in curation
![image](https://user-images.githubusercontent.com/11753634/94270800-8f8f3500-ff38-11ea-951f-a838869ab1fb.png)

**Comment by CuzickA** [comment]
The lower two metagenotypes above with also need the 'NV' tag when it is available.
https://github.com/pombase/canto/issues/2346

**Comment by CuzickA** [comment]
I have updated this session with the altered AE infective ability options see https://github.com/PHI-base/phipo/issues/272 I have also added possible usage of nv/ev wt-ref/wt-other tags to comment section
![image](https://user-images.githubusercontent.com/11753634/94544274-f1a2af80-0242-11eb-93ab-483e9a9d8cc5.png)

I have a few queries
1) Use of nv/ev etc
a) For the 1st and 2nd annotation do we need to use 'nv' or just 'WT-reference'? Will it be compulsory to select either 'nv' or 'ev'? The strain MB42 is the reference strain. 
b) All of the pathogen genotypes contain a partial deletion of the SP(1-30) which would be 'ev'. However, we want to use the 'nv' option to indicate the truncated protein is due to natural variation. Is it correct having the deltaSP in the main genotype or is this really background (we may have discussed this in the past)?

2) The updated AE infective ability _RESOLVED in comment below_
a) works well on the host side in this case but is still confusing on the pathogen side. We have defined 
'functional pathogen effector present' as 'A phenotype where the ability of a pathogen effector to produce an infectious disease is present'.
'functional pathogen effector absent' as 'A phenotype where the ability of a pathogen effector to produce an infectious disease is absent.'
In the 3rd and 4th annotation is 'functional pathogen effector absent' correct? The effector is truncated and therefore not recognised by the R gene to trigger the HR. It seems strange to say the effector is not functional to cause disease when we are assuming that this is a compatible (disease present) interaction as there is no HR.

@ValWood any thoughts on the above?

**Comment by CuzickA** [comment]
Adding new compound AE for gene-for-gene annotation
Here is a query
![image](https://user-images.githubusercontent.com/11753634/99539734-82c21700-29a6-11eb-94c2-593d051bf596.png)
I am changing this from 
**gene_for_gene_interaction** compatible interaction, functional pathogen effector absent, functional host resistance gene present
to 
**gene_for_gene_interaction** compatible interaction, functional pathogen effector present, functional host resistance gene present

as the function of the effector is to cause disease, not be recognised by R gene (biotroph)

Now updated 3th and 4th annotation
![image](https://user-images.githubusercontent.com/11753634/99541230-78088180-29a8-11eb-8619-7c0b66100060.png)

NEXT
1) transfer annotation type to 'gene-for-gene annotation'. This example may be tricky as the host resistance gene SEN1 has not yet been cloned, therefore no UniProt.
2) follow up on use of nv/ev


Note: no use of AE 'compared to X' as all annotations to WTs, not clear what the control would be (part of discussion on nv,ev, WT-ref, WT-other)

**Comment by CuzickA** [comment]
After discussion today with @ValWood  and Kim H-K we decided to remove AE disease_caused Potato wart

It is misleading as the potato wart disease is observed on tubers and there are no expts in the paper showing disease. The Expt are based on leaves exhibiting an HR or not.

![image](https://user-images.githubusercontent.com/11753634/101648189-7b37e000-3a31-11eb-9b71-61fe577c4c88.png)
![image](https://user-images.githubusercontent.com/11753634/101648910-3a8c9680-3a32-11eb-95b9-27ade52fe366.png)

As discussed in https://github.com/pombase/canto/issues/2206 we would prefer another curation type for capturing 'disease'. Therefore I will remove these AE from this session and document in record in 
https://docs.google.com/spreadsheets/d/1806Vhv58ngmql-Z5fIEl7k0BxGx4CQoqamlOYvNwYSk/edit?usp=sharing

Also NTR: compatible interaction, functional host resistance gene present
Def: A pathogen host interaction phenotype where the gene-for-gene relationship between the pathogen and plant host results in disease susceptibility. The ability of a host to be resistant to a pathogen, via the recognition of a pathogen effector by a specific host resistance gene, is present. (The presence of a function pathogen effector is unknown due to a lack of data showing whether it is able to cause disease).

**Comment by CuzickA** [comment]
From https://github.com/PHI-base/phipo/issues/299


The term below, developed for the avrSen1/Sen1 paper will now need further review. We have changed the function of an effector from 'to cause disease' to 'be recognised by host R gene'.

PHIPO_EXT:0000029 compatible interaction, functional host resistance gene present

A pathogen host interaction phenotype where the gene-for-gene relationship between the pathogen and plant host results in disease susceptibility. The ability of a host to be resistant to a pathogen, via the recognition of a pathogen effector by a specific host resistance gene, is present. (The presence of a functional pathogen effector is unknown due to a lack of data showing whether it is able to cause disease).

I think we could obsolete this 2-component term and use the newly updated 3-component terms - to discuss in the next Gene-for-gene curation meeting.

New PHIPO_EXT already mocked up within the curation session comments

**Comment by CuzickA** [comment]
Screen shot of annotations as a record prior to next set of edits
![image](https://user-images.githubusercontent.com/11753634/107363799-93c88300-6ad2-11eb-85d5-225b17a01081.png)
![image](https://user-images.githubusercontent.com/11753634/107363898-b35fab80-6ad2-11eb-80db-d920e7e0e5e7.png)


Updates below with PHIPO_EXT terms edited to record 'effector recognition by host R gene' rather than 'effector ability to cause disease'

![image](https://user-images.githubusercontent.com/11753634/107365987-7d6ff680-6ad5-11eb-9887-de8dc0cc8a8f.png)


@ValWood another one to look at whilst reviewing the biotrophic GfG AE

We need the 'natural variant' description tag for this session.

**Comment by CuzickA** [comment]
Just used new Disease name curation type to add the general disease info on potato tubers that seemed to be missing from this session.
![image](https://user-images.githubusercontent.com/11753634/107659395-04ac9e00-6c7f-11eb-89c9-cb107a3a7cc3.png)

**Comment by CuzickA** [comment]
Should these WT metagenotype also be annotated under disease? 
Rules
WT metagenotype with a compatible/disease outcome for all strain combinations and for each gene (to hang off PHI5 gene page)

![image](https://user-images.githubusercontent.com/11753634/107660622-5f92c500-6c80-11eb-818f-c3c73d20898c.png)

**Comment by CuzickA** [comment]
I think I will leave out the additional disease curation annotations above and just leave it at one metagenotype disease annotation for now.

This session still needs a review for capturing the GfG AE and the NV tag.

Approving session for now but leaving ticket open.

**Comment by CuzickA** [comment]
Can't curate control metagenotypes as all metagenotypes are WT with natural variation. See #96
