### ISSUE TITLE
PMID:31804478 An effector protein of the wheat stripe rust fungus targets chloroplasts and suppresses chloroplast function.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#66]
curation link https://canto.phi-base.org/curs/cc6cf06675cc6e13

**Comment by CuzickA** [comment]
@ValWood Please can you check this one next thanks.

**Comment by ValWood** [comment]
I did this. I have a few questions for tomorrow.

**Comment by CuzickA** [comment]
After today's discussion
controls useful for this type of paper
AC new term to make
Future to discuss conditions/delivery mechanism
please continue checking unchecked annotations @ValWood

**Comment by ValWood** [comment]
checked this.All looks fine to me.

**Comment by ValWood** [comment]
I removed the discuss label because I think you can do everything else for this one at your end. Let me know if there is any outstanding question.

**Comment by ValWood** [comment]
I wanted to add  occurs_in host chloroplast for MF term in :
curs/cc6cf06675cc6e13
Maybe this isn't allowed yet in the PomBase configuration?

**Comment by CuzickA** [comment]
> I wanted to add occurs_in host chloroplast for MF term in :
curs/cc6cf06675cc6e13

I have added this now.

**Comment by CuzickA** [comment]
@ValWood we still need to talk through the conditions required for this paper. I will not be able to approve the session until the appropriate conditions have been added to PHI-ECO and hooked up in PHI-Canto.
https://github.com/PHI-base/curation/issues/69

**Comment by CuzickA** [comment]
Note to self- have added updated conditions. few queries and a final check through to do before approval.

**Comment by CuzickA** [comment]
Session approved. Closing ticket.

**Comment by CuzickA** [comment]
This session may need looking at again with reference to the recent reorganisation of the PHI-branch terms eg effector-mediated....

**Comment by CuzickA** [comment]
Added GFP backgrounds and compared to control AE
![image](https://user-images.githubusercontent.com/11753634/111167112-aeda5700-8598-11eb-89a3-2438d715edf0.png)


Also added RNA level
![image](https://user-images.githubusercontent.com/11753634/111165745-4ccd2200-8597-11eb-8396-a60b9858d2ab.png)

**Comment by CuzickA** [comment]
Several cases where control metagenotypes cannot be curated, mainly due to being expts with an 'empty vector'.

Only able to add AE disease interaction to a couple of annotations.

Other queries to follow later in this ticket.

**Comment by CuzickA** [comment]
Hi @ValWood, I have some queries for this session
1) In the past we had a discussion about using 'overexpression' vs 'not assayed' (I think for the atr1/ rpp1 paper). I couldn't quite remember what was decided. This session currently uses 'overexpression' a lot and I'm not sure if it is correct eg for constructs within a Y2H
![image](https://user-images.githubusercontent.com/11753634/111336932-90925b00-866d-11eb-874c-e51afe57e030.png)
or constructs delivered via agrobacterium
![image](https://user-images.githubusercontent.com/11753634/111338099-8fadf900-866e-11eb-8a2e-1d45b2a3ee2c.png)
In these cases the point of the expt is not comparing phenotypes between WT expression vs overexpression, but are methods of producing and delivering the protein within the given assay.

2) 
![image](https://user-images.githubusercontent.com/11753634/111339375-9db04980-866f-11eb-87b2-8764e490e1cb.png)
a) are we still happy with making 2 annotations to capture this information eg
![image](https://user-images.githubusercontent.com/11753634/111340236-5d050000-8670-11eb-96ed-7da66b0dffbf.png)
![image](https://user-images.githubusercontent.com/11753634/111340304-6a21ef00-8670-11eb-976b-9149bda44931.png)
b) would it be clearer to add present / absent to term?
effector-mediated suppression of host effector triggered immunity _present_
effector-mediated suppression of host effector triggered immunity _absent_

Then the following annotation could also have the second part
![image](https://user-images.githubusercontent.com/11753634/111340830-e3214680-8670-11eb-9d25-1365c67a05c7.png)

3) It is a bit confusing that the host gene is called PetC by UniProt and TaISP in the paper. Currently the genotypes have been renamed with 'TaISP' but the other annotations including the AE assayed_using use 'PetC'. is there a way to make it clear that they are synonyms?

4) 
![image](https://user-images.githubusercontent.com/11753634/111342123-0e586580-8672-11eb-943b-c65bc0fdc543.png)
This HIGS metagenotype was a bit tricky to follow and I have made a note in the comments. However, I now think that it is fine as it is so I will delete the note. The end result is a pathogen with a silenced gene. I think it would be good to add this to our Additional tips documentation (renamed from Phenotype tips https://docs.google.com/document/d/1Nm5yAHMwFYfhjRWuatlGA4_X2aSK9l12QQI1ffQXFqs/edit).

**Comment by ValWood** [comment]
I changed the GO annotation here to

GO:0140590 | effector-mediated suppression of host defenses by symbiont
from
effector-mediated suppression of host PTI signalling

because this seems to be acting downstream of signalling.
Maybe we need  a more generic 'immune responses" term that does not specify PTI signalling?

**Comment by ValWood** [comment]
Correction 
I changed to 
GO:0140403 | effector-mediated suppression of host innate immune response by symbiont
(because this doesn't seem to be affecting the PTI signalling, more the response?)

**Comment by ValWood** [comment]
I did not underrstand this comment
"Should this have output annotation for 'effector-mediated blah... absent'??"

Skype me if you have time to explain.
v

**Comment by ValWood** [comment]
Yes, I think it should be
" effector-mediated suppression of host PAMP-triggered immunity present"
so I assume the label should change here?

Also with  the 2 hybid, because it isn't an in vivo the expression level is not really relevant. The experiment  is only checking if the interaction occurs or not with a specific allele, so yes-  it would be  not assayed

**Comment by CuzickA** [comment]
Responses to queries above

1) changed overexpression to not assayed
2) term edits NTRs created
![image](https://user-images.githubusercontent.com/11753634/112022018-c9c54200-8b29-11eb-8c7b-92da43a11261.png)
3) pre-fixed allele names with PetC-TaISPblah to make clear
4) fine as is, needs documenting in Additional tips 

Waiting for release and loading of PHIPO terms, connect them up and then session ready for approval

**Comment by CuzickA** [comment]
Updated PHIPO terms. Session approved. Closing ticket.

**Comment by CuzickA** [comment]
Hi @ValWood 
I'm working up some examples for the PHI-Canto manuscript. In this annotation I was wondering whether the GO BP term should be 'GO:0052034 effector-mediated suppression of host pattern-triggered immunity' as the effector is suppressing the host callose defense triggered by the addition of a PTI inducer

![image](https://user-images.githubusercontent.com/11753634/145584165-a0046556-4733-4381-9e73-63c0d83f64f5.png)
![image](https://user-images.githubusercontent.com/11753634/145584320-91ce5377-9861-4fce-8c9c-7c219d81bff1.png)

**Comment by CuzickA** [comment]
As a follow up question

Is it okay to have different 'effector-mediated' terms as 'part_of' AE for the GO MF? Perhaps we did this as the PTI inducer was not added to these expt.

![image](https://user-images.githubusercontent.com/11753634/145584682-d59c2d13-ac75-4b70-82a0-d5b26ff62dc6.png)

**Comment by ValWood** [comment]
> I was wondering whether the GO BP term should be 'GO:0052034 effector-mediated suppression of host pattern-triggered immunity' as the effector is suppressing the host callose defense triggered by the addition of a PTI inducer

It seems so. It should be a descendant of the term used currently, but this would be more specific.

**Comment by ValWood** [comment]
> I was wondering whether the GO BP term should be 'GO:0052034 effector-mediated suppression of host pattern-triggered immunity' as the effector is suppressing the host callose defense triggered by the addition of a PTI inducer

Maybe this term could be more specific too? I think part of the problem might be that some terms did not exist when we began (but also we can only go as specific as the paper provides evidence for).

This is why in PomBase we only show the most specific annotation by default. But uses can see experimental annotations to less specific parents in the 'detailed view'.

**Comment by CuzickA** [comment]
I have changed this annotation to the more specific child term, as a PTI inducer was used in the Fig 3a expt
![image](https://user-images.githubusercontent.com/11753634/146206033-4cc75668-4738-4873-b52f-c552e5e070b2.png)


Should these MF 'part_of' BP terms also be made more specific to be the same as the initial BP annotation? Or should they be left as they are? Do the MF AE BP terms 'have' to be the same as the original BP annotation term?
![image](https://user-images.githubusercontent.com/11753634/146207008-8f0b71f0-be33-4e61-be4b-a0f7c08a28d4.png)

**Comment by CuzickA** [comment]
Multiple annotations have the bug where the compared to control AE is not automatically updated with the edit to the metagenotype. The 'overexpression' needs changing to 'not assayed'. I have manually done this for 7 annotations and changed 'WT product' to 'WT level' for 4 annotations
![image](https://user-images.githubusercontent.com/11753634/161252100-bcf8fdf5-0e96-461a-94dc-e10cf2664767.png)
to
![image](https://user-images.githubusercontent.com/11753634/161252543-cfe7dee7-bf32-494d-aa50-bd6bcfaabe9f.png)

**Comment by CuzickA** [comment]
Updated to

![image](https://user-images.githubusercontent.com/11753634/225316334-530a1710-a3e6-4b00-9d05-0dd360b61044.png)

The BP annotation in the MF part_of BP should be to the same term
