### ISSUE TITLE
new expression types

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#68]
not expression level

need 
expression type

transgenic 
- host expressing pathogen gene
- host expressing pathogen gene constitutively
- host expressing pathogen gene inducibly

**Comment by jseager7** [comment]
@CuzickA Is this supposed to be an extra set of options in addition to the expression level when creating an allele? For example:

![image](https://user-images.githubusercontent.com/37659591/73460173-f4759980-436f-11ea-83fd-209d1bb9946f.png)

If so, which allele types should it apply to, and should the options be named as above?

**Comment by ValWood** [comment]
@CuzickA  need to think about  if we can combine this with "delivery method"
I think this will be easier when you have collated the different types of information to capture. 
So  evaluate  the "transgenic expression" and "delivery method" together so we can see what the overlap is.

@jseager7  this  is what we had in mind but it depends how many things we need to capture and if we can lump them.

**Comment by CuzickA** [comment]
also see #69

**Comment by CuzickA** [comment]
We have a PHI-ECO term for 'delivery mechanism: pathogen gene expressed by transgenic host'.
Closing ticket for now
