### ISSUE TITLE
How to represent "delivery mechanism"

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#69]
I might need 2 new conditions, or they might exist with another nameand I didn't locate them.

~"transgenic host expression" (or similar)~
https://github.com/pombase/canto/issues/2049

where the pathogen gene is transfected into the host

"host cell suspension" where the assay is done in  a host cell suspension, not actually in vivo

**Comment by ValWood** [comment]
delivery mechanism required for
https://github.com/PHI-base/curation/issues/44

@CuzickA  we should prioritise to discuss this  ticket next week

**Comment by CuzickA** [comment]
https://docs.google.com/spreadsheets/d/1D39pqcpO5mxr_wVCgYWtVGEujqV3Pq1LJZTug3WF4TI/edit#gid=0

Started spreadsheet. Required for #19

**Comment by CuzickA** [comment]
See #91 want to annotate expts with i)purified pathogen effector infiltrated into host and ii) effector delivered naturally by pathogen inoculation.

and #89 transient and stable transgenic hosts containing pathogen gene (and then inoculated with wild type pathogen)

**Comment by CuzickA** [comment]
This is what we currently have in PHI-ECO
![image](https://user-images.githubusercontent.com/11753634/105705829-a48ccc80-5f08-11eb-8580-9e8c7ddda02f.png)

**Comment by CuzickA** [comment]
Also have these terms under 'grouping excess'
![image](https://user-images.githubusercontent.com/11753634/105706766-e2d6bb80-5f09-11eb-8e37-3562dea1a3a7.png)

**Comment by CuzickA** [comment]
Would it be clearer for the 'delivery mechanism terms' to have this as a term prefix? @ValWood 

eg
delivery mechanism: agrobacterium
delivery mechanism: culture infiltration

I think this would be helpful whilst terms still listed under 'conditions' but may not be necessary once we have a new selector option for 'delivery mechanism'.

**Comment by CuzickA** [comment]
I think we need this NTR condition for #89 
'pathogen gene expressed by transgenic host'

**Comment by ValWood** [comment]
That would probably help. The mechanisms might be a bit 'obscure' but it the text can indicate the  help test can indicate start typing "delivery mechanism" that would help and  could be removed  from term names later.

**Comment by CuzickA** [comment]
Now looks like this

![image](https://user-images.githubusercontent.com/11753634/105722896-0c014700-5f1e-11eb-8817-e2856fa7477f.png)

**Comment by CuzickA** [comment]
Closing ticket for now as we have decided to keep the 'delivery mechanism' within the 'conditions' option. The term prefix 'delivery mechanism:' makes searches for these terms much easier. We will add some help text.
