### ISSUE TITLE
complementation

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#7]
Can you give me a couple of examples of your complementation experiments?

I.e are they always 
complement pathogen  gene x with related pathogen gene x'
for a pathogen specific phenotype.

I think you mentioned some other type, but I can't remember what it was.....

**Comment by CuzickA** [comment]
The majority of our complementation experiments are 
**mutant pathogen allele x WT pathogen gene** = WT phenotype
to demonstrate that the pathogen gene of interest is responsible for the phenotype
eg
allele phenotype -> reduced virulence
allele x WT gene -> restored WT virulence
In PHI-base we have not actually captured detail of these 'complementation expt'. Instead we have added 'gene complementation' to the expt evidence used for the upper nine phenotype terms annotations eg 'Gene deletion: full; gene complementation'
(our expt evidence needs work as discussed previously).

Therefore we don't actually have a list of phenotypes that have been used just to curate complementation expts. In theory they could be pathogen specific or pathogen host disease formation phenotypes depending on what has been observed.

Other types of complementation expt would include
**mutant pathogen allele x altered WT pathogen gene**
**mutant pathogen allele x gene from another organism**

('Effector' gene for gene relationship examples where the pathogen gene is naturally absent in a particular strain and present in another. The present WT pathogen gene may be added to the strain where it is absent and shift the disease phenotype).

@martin2urban has pulled out some examples for us
[ComplementationExamplesMu01.xlsx](https://github.com/PHI-base/curation/files/1702809/ComplementationExamplesMu01.xlsx)

**Comment by ValWood** [comment]
Ah OK, I was thinking of our use of complementation when an endogenous gene from a different organism is used. We can't do this in Canto yet, but we want to in the future.

However, you can already curate the above (at PomBase we don't bother because  we don't curate the control experiments).

e.g.
[demo.pdf](https://github.com/PHI-base/curation/files/1703746/demo.pdf)

We could  add a separate  allele type category  "complementation" in the PSU version
which would require a mutant allele and a WT allele to ensure the  necessary components are included if you need it.

**Comment by ValWood** [comment]
Oh I see you have other examples. I think we will need to work through these individually.

**Comment by CuzickA** [comment]
Thanks for the demo file. So it looks like Canto can already deal with
**mutant pathogen allele x WT pathogen gene 
mutant pathogen allele x altered pathogen gene**
which is a good start. The other examples may be something to think about in the future.

It is useful to know that you don't curate the control experiments. This is something for us to think about moving forward. We haven't fully curated them as we've  just added 'gene complementation' to our expt evidence as described above.

**Comment by CuzickA** [comment]
see https://github.com/pombase/canto/issues/826

**Comment by CuzickA** [comment]
closing issue for now as also on the Pombase/Canto tracker, see link above
