### ISSUE TITLE
Sessions with 'Unknown' expression levels

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#70]
Required for https://github.com/pombase/canto/issues/2215

@ValWood @CuzickA Here is a list of curation sessions on the main PHI-Canto server that use the 'Unknown' expression level.

I was wrong before when I claimed there were no sessions using this expression level: I must have been getting confused with a search I did for experimental conditions. You may want to check these sessions before we commit to disabling the 'Unknown' expression type.

Alayne mentioned that the genotypes in the following sessions could be good test cases for the new expression types mentioned in issue #68.

- [`79c56f92435923ab`](https://canto.phi-base.org/curs/79c56f92435923ab)  _unknown expression no longer used in this session_
- [`87e386b652573063`](https://canto.phi-base.org/curs/87e386b652573063) _unknown expression no longer used in this session_
- [`59484877a87d5786`](https://canto.phi-base.org/curs/59484877a87d5786) _unknown expression no longer used in this session_
- [`cc6cf06675cc6e13`](https://canto.phi-base.org/curs/cc6cf06675cc6e13)  _unknown expression no longer used in this session_
- [`599959346d766435`](https://canto.phi-base.org/curs/599959346d766435) _unknown expression no longer used in this session_
- [`a16f44010111a5c4`](https://canto.phi-base.org/curs/a16f44010111a5c4) _unknown expression no longer used in this session_
- [`dc027c00e7ceab6f`](https://canto.phi-base.org/curs/dc027c00e7ceab6f) _unknown expression no longer used in this session_
- [`f41d30e250b8f9b0`](https://canto.phi-base.org/curs/f41d30e250b8f9b0) _unknown expression no longer used in this session_
- [`3b2c44b436098af1`](https://canto.phi-base.org/curs/3b2c44b436098af1) _unknown expression no longer used in this session_
- [`bd02fdb6831712ca`](https://canto.phi-base.org/curs/bd02fdb6831712ca) _unknown expression no longer used in this session_
- [`b06680e815f64df0`](https://canto.phi-base.org/curs/b06680e815f64df0) _unknown expression no longer used in this session_

**Comment by CuzickA** [comment]
79c56f92435923ab   https://github.com/PHI-base/curation/issues/42

It looks like there is an error in the pathogen genotype (deletion and overexpression??)
![image](https://user-images.githubusercontent.com/11753634/77311892-e2253580-6cf8-11ea-82f1-8f364e111356.png)

I have corrected this to 

![image](https://user-images.githubusercontent.com/11753634/77312777-8d82ba00-6cfa-11ea-8083-2b43a58c5977.png)


_Note: have also now corrected genotype name from MGG_08054 to chia1delta (autocomplete had removed this earlier)_
![image](https://user-images.githubusercontent.com/11753634/80401876-f4c0fa80-88b4-11ea-8c02-fc6097d8f46a.png)





Therefore removing the use of 'unknown' expression level from this session.

**Comment by CuzickA** [comment]
https://canto.phi-base.org/curs/cc6cf06675cc6e13 https://github.com/PHI-base/curation/issues/66

Looked again at paper and below 'unknown' should be 'not assayed' 
![image](https://user-images.githubusercontent.com/11753634/77460774-7c6ca280-6df9-11ea-9121-33dbace9c925.png)

Now updated to this (conditions still need updating when PHI-ECO loaded)
![image](https://user-images.githubusercontent.com/11753634/77461277-3cf28600-6dfa-11ea-81be-1039ee1d14e1.png)

__Just noticed host alleles also use 'unknown' assume this should be 'overexpression' as Y2H_expt._
![image](https://user-images.githubusercontent.com/11753634/77553447-b9de3800-6eac-11ea-934d-91661eb3dc57.png)

![image](https://user-images.githubusercontent.com/11753634/77553759-20635600-6ead-11ea-92d9-445fcfc6245f.png)

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/57

changed 'unknown' to 'not assayed'

![image](https://user-images.githubusercontent.com/11753634/77907792-2f1d8480-7282-11ea-80af-89a16142732c.png)
![image](https://user-images.githubusercontent.com/11753634/77907875-583e1500-7282-11ea-8a5c-e0cff9e6c92f.png)

**Comment by CuzickA** [comment]
For https://canto.phi-base.org/curs/87e386b652573063 #55 
changed pathogen 'unknown' expr to either 'overexpression' as in Fig 2 or 'not assayed'
![image](https://user-images.githubusercontent.com/11753634/80008286-754fb780-84bf-11ea-92a0-0b77f52149a1.png)

Now looks like
![image](https://user-images.githubusercontent.com/11753634/80011064-391e5600-84c3-11ea-98b7-a8837e7a25e7.png)

**Comment by CuzickA** [comment]
For https://canto.phi-base.org/curs/59484877a87d5786  #65 
![image](https://user-images.githubusercontent.com/11753634/80016532-2576ed80-84cb-11ea-810c-b9898dceca80.png)

changing pathogen genotypes 'unknown' expr to 'not assayed'
now looks like this
![image](https://user-images.githubusercontent.com/11753634/80017032-d67d8800-84cb-11ea-97e7-0632e0b6e8c4.png)

**Comment by CuzickA** [comment]
For https://canto.phi-base.org/curs/a16f44010111a5c4 #54 
![image](https://user-images.githubusercontent.com/11753634/80017752-f6fa1200-84cc-11ea-8aab-229894fd6e66.png)

changed pathogen genotypes 'unknown' exp to 'not assayed'
![image](https://user-images.githubusercontent.com/11753634/80018169-8acbde00-84cd-11ea-8e97-d9d9d94d0195.png)

**Comment by CuzickA** [comment]
For https://canto.phi-base.org/curs/dc027c00e7ceab6f #60 
![image](https://user-images.githubusercontent.com/11753634/80020138-763d1500-84d0-11ea-8b6b-4c0f7155b2a2.png)

changed pathogen and host genotypes from 'unknown' expr to 'overexpression'
![image](https://user-images.githubusercontent.com/11753634/80020736-65d96a00-84d1-11ea-9894-e2b89ffad7dc.png)

**Comment by CuzickA** [comment]
For http://canto.phi-base.org/curs/f41d30e250b8f9b0 #19 

Unused metagenotypes (also unused pathogen and host genotype) with 'unknown' expr level.
![image](https://user-images.githubusercontent.com/11753634/80209751-8832cb00-862a-11ea-997b-5460b718ede9.png)
Genotypes now deleted.

**Comment by CuzickA** [comment]
For http://canto.phi-base.org/curs/3b2c44b436098af1 #18 
![image](https://user-images.githubusercontent.com/11753634/80210689-1491bd80-862c-11ea-9b00-705e32812a7a.png)
Allele name still needs some attention when checking. I have changed unknown expr to not assayed.

**Comment by CuzickA** [comment]
For http://canto.phi-base.org/curs/bd02fdb6831712ca #22 

![image](https://user-images.githubusercontent.com/11753634/80216168-8e7a7480-8635-11ea-932c-37a3cb1a49bf.png)


changed 'unknown' expr to 'not assayed'

**Comment by CuzickA** [comment]
For https://canto.phi-base.org/curs/b06680e815f64df0 #53 
![image](https://user-images.githubusercontent.com/11753634/80217632-edd98400-8637-11ea-9dcc-1449a7476fdb.png)
Changed 'unknown' expr to 'not assayed'

**Comment by CuzickA** [comment]
Hi @jseager7 I think I have removed 'unknown' expression types from the genotypes in the above sessions. Please could you re-run your search on a new JSON output to check that I haven't missed any uses of 'unknown' expression.
If they have all successfully been removed please go ahead and disable the 'unknown' expression type.

Tagging @martin2urban FYI the JSON output files you previously sent MC for both 'approved' and 'all' sessions will contain 'unknown' expression type in some of the genotypes prior to my corrections. This may not be a problem but I thought I would draw your attention to it.

**Comment by jseager7** [comment]
@CuzickA Many thanks for all your hard work on this. I've checked the export, and there's just one reference to 'Unknown' expression remaining: it's in PMID:30610168 (session [`79c56f92435923ab`](https://canto.phi-base.org/curs/79c56f92435923ab)), annotated on the MGG_08054+ allele.

![image](https://user-images.githubusercontent.com/37659591/80358650-ad1a7e80-8874-11ea-8fc3-73ddfe90f354.png)

**Comment by CuzickA** [comment]
Thanks @jseager7 I have now deleted the above unused genotype.

**Comment by jseager7** [comment]
Thanks. I've double checked the export and there are no more uses of Unknown expression. Closing now.
