### ISSUE TITLE
PMID:18179606 Fusarium graminearum gene deletion mutants map1 and tri5 reveal similarities and differences in the pathogenicity requirements to cause disease on Arabidopsis and wheat floral tissue.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#72]
curation link https://canto.phi-base.org/curs/d7b3170ded99924f

Whilst curating this very important paper ;-) I have the following notes/queries

@ValWood whilst checking this session could you let me know what you think about the following please?

1) There are a lot of conditions which are important to record.
2) It may be necessary to capture some 'aerial growth' phenotypes in addition to necrosis. In PHIPO we currently have the below, but I'm not sure if these capture the information we are after.
![image](https://user-images.githubusercontent.com/11753634/75342208-d8d9b200-588d-11ea-8ae4-e0a925484536.png)
3) It can be tricky to make the call between 'loss of pathogenicity' and 'reduced virulence' for the map1 deletion mutant. This is because of the superficial surface growth (see Fig 1 legend).
4) there are a few new term suggestions -do these seem reasonable?

**Comment by ValWood** [comment]
Looks good. Only needs new terms and conditions resolving

**Comment by ValWood** [comment]
I just saw this e-mail in my inbox and realised I did not answer the specific questions.

I didn't feel any annotations were particularly missing and I commented in the session if I had any input.

I'm still struggling with 3!

**Comment by CuzickA** [comment]
Waiting for PHIPO NTRs and PHI-ECO NTRs to load into PHI-Canto _now done and hooked up to session_

Need following NTRs for PHI-ECO conditions for this session  _now added to PHI-Eco 0a1c289_

10 dpi
5 dpi
20 dpi
11 dpi
6 dpi

how best to capture types of inoculation?
point inoculation
spray inoculation

_For now have added as below 5a32e02_
![image](https://user-images.githubusercontent.com/11753634/77935817-dcf05980-72a9-11ea-9587-a22e4755aaef.png)

**Comment by CuzickA** [comment]
Conditions now added. Waiting for @martin2urban to provide any feedback on this session before I approve it.

**Comment by martin2urban** [comment]
(1) @CuzickA:  Overall  I confirm this curation.   However, I would remove from comment "Tricky to make a call whether this is 'loss of pathogenicity' or 'reduced virulence'.  Our previous paper reported that it is 'loss of pathogenicity' (TAS). 
(2) @ValWood    I see that there is a 'checked' button in the curation interface. Could you please explain what this is used for? Perhaps I should have used it?

**Comment by CuzickA** [comment]
Hi @martin2urban thanks for your comments above. There is a really nice admin option when reviewing a session to highlight and check/uncheck boxes whilst looking through the curations. I can show you this via share screen on Teams sometime.

**Comment by ValWood** [comment]
It's very useful if you are checking a session with lots of annotations. Often the order in the paper is not the curated order so it can get very confusing without a mechanism to know which ones you have checked. When checking we usually "check all" and then uncheck as we work through. At the end we are hopefully left with none checked ;)

**Comment by CuzickA** [comment]
Session finished and approved. Closing ticket.

**Comment by CuzickA** [comment]
Updated this session with
Figure column
Control metagenotype and annotations
AE compared to control
AE disease interaction (where relevant)
removed AE causes_disease
added Disease name curation type

Waiting for two NTRs before session can be approved

**Comment by CuzickA** [comment]
Added two NTRs and approved session. Closing ticket.
