### ISSUE TITLE
PMID:29434355 Wheat receptor-kinase-like protein Stb6 controls gene-for-gene resistance to fungal pathogen Zymoseptoria tritici.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#73]
curation link https://canto.phi-base.org/curs/69e99b22bfebf3b0

This paper was chosen for curation based on having no standard HR phenotype in the resistance (gene for gene) interaction. J. Rudd queried whether it would be possible to curate this effector paper so I thought i'd have a go.

Another difficulty is that the pathogen gene 'AvrStb6' is not mutated in this paper, it is the corresponding host R gene Stb6 that is altered. Therefore AvrStb6 will need to be captured as a WT pathogen genotype which is not standard protocol for PHI-base entries.

Tricky to find AvrStb6 UniProt Id. Reference proteome for Zt is IPO323 but no AvrStb6 uniprot entries for this strain.
search uniprot for 'avrStb6' get 30 unreviewed entries from different haplotypes but no strain information.

Went to paper https://nph.onlinelibrary.wiley.com/doi/epdf/10.1111/nph.14434
and typed out IPO323 AA seq from Fig4a (see below in case of needing to re-use). This is the Avirulent allele sequence.
Blasted this against uniprot and got 100% hit for 2 entries
![image](https://user-images.githubusercontent.com/11753634/75350650-cc118a00-589e-11ea-85f6-b9d56506640a.png)

I have chosen to use the second entry A0A2K9YVY7 as the protein name has been annotated, the source of this sequence is from haplotype 1, the strain is not mentioned.

MRSILQGLLAFALAVGVQARVSCGGIGDLCKAGDSCCNYPGTDCFQDGQYPRCHTACGHFQFGFCHDGKQCNCQVILGCGCV

**Comment by ValWood** [comment]
We need to look at the GO annotation for this one. We haven't really captured how te kinase is cancelling the effector

**Comment by CuzickA** [comment]
AC to add protein-protein non-interaction data from FigS12 and then session ready for checking

**Comment by CuzickA** [comment]
This one is ready for checking please @ValWood 

There is a query on the best way to capture an infective ability AE as the pathogen is WT, the host has changed from resistant to susceptible

![image](https://user-images.githubusercontent.com/11753634/84522496-a3d35d00-acce-11ea-9783-6d2516d5addd.png)

**Comment by CuzickA** [comment]
This session is a lot clearer now with the additional AE infective ability terms for 'host resistance etc' and the new AE gene-for-gene for compatible/incompatible interaction.

Still the following queries
1) whether to use 'increased' or 'gain of' here. Lesions were absent in WT host and now present in stb6 knockdown
![image](https://user-images.githubusercontent.com/11753634/85554712-16243580-b61d-11ea-920a-39906582b86e.png)

2) 'absent' or 'abolished' here
![image](https://user-images.githubusercontent.com/11753634/85555172-8b900600-b61d-11ea-8ddb-c3b3448cc270.png)


@ValWood what do you think?

**Comment by CuzickA** [comment]
This session will be ready for approval once above is resolved.

**Comment by CuzickA** [comment]
Added new information for AEs
gene-for-gene interaction compatible or incompatible
infective ability for pathogen (pathogenicity present/absent etc) and host (resistance present/absent etc)

For query 1 above we decided to use 'presence...' as the 'loss of host resistance' and 'compatible interaction' provide the required information.
![image](https://user-images.githubusercontent.com/11753634/86031252-7fe17c80-ba2d-11ea-966d-a4487ea6e0ab.png)

For query 2 above we decided to use 'absence...'
![image](https://user-images.githubusercontent.com/11753634/86031457-bddea080-ba2d-11ea-9bc4-8705d188d115.png)
as the AE 'gain of host resistance' and 'incompatible interaction' are now recorded

Closing ticket and approving session for now.

**Comment by CuzickA** [comment]
updating session by
-add fig info to Fig column
-add 'nv' or 'ev', 'WT-ref' or 'WT-other' for both pathogen and host genotypes to comment box
-check new gene-for-gene AE infective ability term usage
-decide on usage of AE compared to
-edit below genotype to record the known natural variation
![image](https://user-images.githubusercontent.com/11753634/95322575-a288fa00-0894-11eb-879c-39b1c24d1487.png)
changed to
![image](https://user-images.githubusercontent.com/11753634/95324767-242e5700-0898-11eb-884d-11dfed65939a.png)

Not that clear at the moment that courtot is WT, this requires the proposed 'NV' tag

reference strains
![image](https://user-images.githubusercontent.com/11753634/95323918-d49b5b80-0896-11eb-8893-e55cabe91eb4.png)

![image](https://user-images.githubusercontent.com/11753634/95324028-04e2fa00-0897-11eb-933a-81d5699a0087.png)
We will use IPO323

**Comment by CuzickA** [comment]
updated this session with new compound AE gene for gene phenotype

A few queries have been documented within the curation session.

**Comment by CuzickA** [comment]
https://github.com/PHI-base/phipo/issues/299

New PHIPO_EXT terms work well for this session. (Term definitions still need to be check and refined)

Outstanding query still on use of 'NV' see above for Wheat Cv Courtot

**Comment by CuzickA** [comment]
Biotroph GfG session to double check @ValWood 

I am getting confused with the usage of the GfG AE. In https://github.com/PHI-base/curation/issues/19 we decided to record the information from within the metagenotype in the annotation, however this appears to be in contrast with all of other GfG and inverse GfG sessions. This needs further review.

**Comment by CuzickA** [comment]
Added 'disease name ' curation type - see query in comment
![image](https://user-images.githubusercontent.com/11753634/107661382-260e8980-6c81-11eb-830a-1e38536630ab.png)

removed AE causes_disease

**Comment by CuzickA** [comment]
Disease name query above should be ok once we have added NV tag
https://github.com/PHI-base/curation/issues/95

Needs an overall review to check GfG AEs

And a quick check to see if this RNA annotation is adequate - I have just made a 'WT RNA level' annotation in addition to the PHIPO annotation. Does this seem reasonable @ValWood ?

![image](https://user-images.githubusercontent.com/11753634/109810214-2b784780-7c21-11eb-81da-d4eec0679fce.png)


Approving session for now but will leave ticket open until complete.

**Comment by ValWood** [comment]
I'm not sure that "increased level of host RNA involved in yada..." makes sense. That would only  be increased compared to uninfected host.....shouldn't it be 'presence'?

**Comment by CuzickA** [comment]
> I'm not sure that "increased level of host RNA involved in yada..." makes sense. That would only be increased compared to uninfected host.....shouldn't it be 'presence'?

Yes, this is tricky as we can't curate a metagenotype control for uninfected host. Maybe I should use the new term 'host RNA involved in a pathogen interaction present' instead?

**Comment by ValWood** [comment]
that makes sense

**Comment by CuzickA** [comment]
RNA annotations now look this this
![image](https://user-images.githubusercontent.com/11753634/110093756-fb50b600-7d92-11eb-8b3a-aafa71fd0e4f.png)

**Comment by ValWood** [comment]
Were there any outstanding questions here? I think this one looks OK.

**Comment by CuzickA** [comment]
I think this one is done, I'll close the ticket.

**Comment by ValWood** [comment]
Actually I hadn't checked this one.  I thought it was a different one. Doing it now.

**Comment by ValWood** [comment]
Looks good. Was easy to check too.
