### ISSUE TITLE
Enable capturing of ‘Qualitative Gene Expression Data’ with interacting species adaptations in PHI-Canto.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#74]
Wild-type Expression annotations could be made to the gene (not genotype/phenotype)

Discussed yesterday with @ValWood 
https://curation.pombase.org/pombase-trac/wiki/CapturingGeneExpression
https://www.pombase.org/gene/SPBC11B10.09  look at section 'qualititive expression'

Eg in a WT pathogen-host interaction, recording that a pathogen and host gene are concurrently expressed eg EPI1 and P69B in PMID:15096512

Use this ticket to collect this data during curation. In the future the data can then be added back to the sessions once this function has been enabled. 

Val suggested recording
Syntax /controlled_curation="term=gene expression, RNA level; annotation_extension=during(GO:xxxxxxx); qualifier=increased; evidence=ECO:xxxx; db_xref=PMID:xxxxxxx; date=YYYYMMDD"

Will also need to adapt this for pathogen AND host interaction to document concurrent gene expression.

(There is also a bulk upload template PomBase use to capture gene expression data.)

**Comment by CuzickA** [comment]
For https://github.com/PHI-base/curation/issues/41
https://canto.phi-base.org/curs/babb18b437174938
The epi1 and p69B gene are concurrently expressed during infection of tomato by P. infestans.
![image](https://user-images.githubusercontent.com/11753634/80501557-796c5100-8967-11ea-8bac-92692210951e.png)
Removed above from session and recorded in this ticket for the future.

**Comment by CuzickA** [comment]
https://github.com/pombase/canto/issues/1491

**Comment by ValWood** [comment]
I will chat with Kim about this next time I speak with him

**Comment by jseager7** [comment]
The 'RNA level' annotation type should be enabled for genes on the main PHI-Canto server by tomorrow. It's already available on the demo server. Is that all you needed for this issue?

**Comment by CuzickA** [comment]
This works nicely thanks.

I have update the session https://canto.phi-base.org/curs/babb18b437174938

![image](https://user-images.githubusercontent.com/11753634/98350359-20b2fa80-2013-11eb-9088-7b97be7e72f7.png)

@jseager7 we will need to update the 'Help documentation'. I will also discuss with @martin2urban incorporating these new data types into the MC PHI5 display pages.

Closing ticket for now.

**Comment by CuzickA** [comment]
I was just looking at the AE options and when I select 'in presence of' see this error message

![image](https://user-images.githubusercontent.com/11753634/98353559-58bc3c80-2017-11eb-9ac9-6567da57d081.png)

**Comment by jseager7** [comment]
This is because we weren't loading the subset of the ChEBI ontology that PomBase uses for this annotation extension. I'm testing loading the ontology subset on the demo server now, and I'll close this issue once the ontology is available on the main server (probably tomorrow).

**Comment by jseager7** [comment]
This is now fixed on the production server too. Closing.

![image](https://user-images.githubusercontent.com/37659591/98656359-7ac7fe80-2338-11eb-9d06-928c1a958e89.png)
