### ISSUE TITLE
How to record whether a WT host strain/cultivar is susceptible or resistant to a given pathogen

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#78]
This information is currently being recorded in the comment section which won't be visible in our future results display pages.

Using this ticket to collect examples

https://github.com/PHI-base/curation/issues/23
![image](https://user-images.githubusercontent.com/11753634/84491364-56d69300-ac9c-11ea-9b2a-21329945480b.png)
![image](https://user-images.githubusercontent.com/11753634/84491441-75d52500-ac9c-11ea-9a6d-b42486f798a6.png)

WT pathogen on susceptible WT host &rarr; necrotic disease (This control has not been curated)
&Delta;ppt pathogen &rarr; absence of disease  (maybe this should be 'abolished....') (abnormal?)
&Delta;pks1 pathogen &rarr; presence of disease (normal?)

If a host was resistant there would be no/reduced disease

How do we link that the 'Riband' host strain/cultivar is susceptible to the given WT pathogen?

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/65
This session also has details of WT host cultivar being R or S in the comments section.

**Comment by jseager7** [comment]
@CuzickA How do you determine that a host strain or cultivar is susceptible to a wild-type pathogen? Is this simply copied from findings from the publication, or is it inferred from the fact that a wild-type pathogen on wild-type Riband causes disease symptoms (e.g. necrosis)?

**Comment by CuzickA** [comment]
see https://github.com/pombase/canto/issues/2312 Allow wild-type pathogens in metagenotypes

For #23 I have 
- added one control metagenotype to get started 
'pptWT/Riband' with 'presence of necrotic cell death..' and AE 'disease caused'
- added the AE 'compared to control' 'pptWT/Riband' to the annotation for 'pptdelta/Riband'

These annotations look like this
![image](https://user-images.githubusercontent.com/11753634/87157833-bed9c280-c2b6-11ea-95c7-2634f508e198.png)

![image](https://user-images.githubusercontent.com/11753634/87157730-94880500-c2b6-11ea-92c2-8b9571036a37.png)

I am not sure how practical/sustainable this new method is?
1) Does a WT metagenotype need to be made for each of the 7 tested pathogen genes in this session?
2) Do we need to record the WT for each type of the metagenotype phenotype annotations eg necrotic cell death/spores/melanin?
3) If we want to move forward using this method perhaps we will only capture WT metagenotypes for mutant metagenotypes where the phenotype has changes and results in 'loss of pathogenicity' etc and NOT create WT metagenotypes for annotations with 'unaffected pathogenicity'/ normal ...blah

I won't add any further WT metagenotype's until this has been discussed further.

**Comment by CuzickA** [comment]
I have tried this again now that the WT pathogen/ no gene attached option is available.

After todays discussion we decided to make WT control annotations for each phenotype eg necrotic cell death/spores/melanin.
Compared to control AE have been added.
There was also discussion about creating a new AE for 'Disease outcome' disease present/disease absent (note this is separate from AE gene-for-gene interactions compatible/incompatible). These have been mocked up under the comments section for future review.

WT controls for this session now look like this (one NTR pending)
![image](https://user-images.githubusercontent.com/11753634/87935370-e421ba00-ca88-11ea-8645-5060caee2af3.png)
![image](https://user-images.githubusercontent.com/11753634/87935469-159a8580-ca89-11ea-92f0-862aeee17d2f.png)

And usage of AE 'compared to control'
![image](https://user-images.githubusercontent.com/11753634/87935573-4084d980-ca89-11ea-8adf-06de72af624e.png)
![image](https://user-images.githubusercontent.com/11753634/87935665-6b6f2d80-ca89-11ea-99ff-3473bad340aa.png)

**Comment by CuzickA** [comment]
After discussion with @ValWood and @KEHammond (8 September 2020) we decided on below:

1. Keep the option of curating wild-type pathogen and wild-type host metagenotype controls. _Note: we are no longer using WTpathogen WThost metagenotype as decided in PHI-Canto group meeting 28_09_2020._
2. Do **not** use wild-type controls for single-species annotations; only for metagenotype annotations.
3. Control annotations will be made for _all_ non-gene-for-gene annotations (and retroactively applied to existing curation sessions). There will probably be more terms related to controls added to PHIPO.
4. The 'compared to control' annotation extension will link the mutant annotation to the wild-type annotation. For now this may be the only visible mention of the wild-type metagenotype in the new gene-centric pages (which need a gene or UniProtKB ID). 
5. Future plans include a wild-type pathogen&ndash;host combination page with strain details, linking to disease name (once PHIDO is mapped to the [Plant Stress Ontology](https://github.com/Planteome/plant-stress-ontology)), tissue tested, linkouts to CABI [Plantwise](https://www.plantwise.org/) (nice descriptive info on plant pathogens) etc. (This is not planned for the PHI-Canto manuscript.)
6. New annotation extension for pathogen-host interactions, describing the outcome of the interaction and whether disease was absent or present. This would be for non-gene-for-gene annotations. Ideally, this new annotation extension would be listed under infective ability non-gene-for-gene, in a similar manner to the infective ability/gene-for-gene compatible/incompatible option.

**Comment by CuzickA** [comment]
Also to consider

When to use 
i) 'WT pathogen and WT host metagenotype' 
vs 
ii) 'WT specified pathogen gene and/or WT specified host gene'?

i) seems most suitable for above example where paper contains data on 7 genes from the pathogen, observing 3  phenotypes 'necrosis', 'melanin' and 'spores' within the interaction with host.

ii) seems most suitable for looking at a single gene in a pathogen/host interaction which may or may not have several phenotypes.

**Comment by ValWood** [comment]
Can you talk us through this on the call? It seems odd to change the genotype based on the number of phenotypes (but I also don't know what you mean exactly by WT-specified)

**Comment by CuzickA** [comment]
Eg of scenario ii) above where there is one altered gene (deltaGT2) rather than 7 genes
![image](https://user-images.githubusercontent.com/11753634/94408256-71aa1600-016c-11eb-9064-07f542aae1ff.png)
WT control annotation not made yet but would it be
WTFg(PH1) WTTa(bobwhite)
or
GT2+(PH1) WTTa(bobwhite) 

There is also the Fg map1 and Tri5 paper. Which method would be used to curate the WT controls of two tested genes in pathogen?

We need a clear rule here. 

Also to think about whether these would use new options for 'nv' 'WT-reference'. (DeltaGT2 would be 'ev' deletion).

**Comment by CuzickA** [comment]
> We are no longer using WTpathogen WThost metagenotype as decided in PHI-Canto group meeting 28_09_2020.

Instead, each metagenotype control will be annotated following the option above 
> GT2+(PH1) WTTa(bobwhite)

The new disease outcome AE will be added to the non-gene-for-gene annotations.

I will work through adding these controls to the 10 example papers planned for inclusion in the manuscript first.
#81

**Comment by CuzickA** [comment]
Completed updating https://canto.phi-base.org/curs/cee7f6d8bab0bafd with 
1) disease interaction AE
2) Figure info
3) specified pathogen gene WT control annotations
4) compared to control AE 
5) removed WTpathogen WThost metagenotypes and annotations (need to make a ticket to disable this option)

closing this ticket for now
