### ISSUE TITLE
Decide how to curate the 'gene-for-gene interactions' and create help documentation

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#79]
Currently under discussion with @ValWood 
Also see #62 
It would be good to create some clear guidance for curators about which AE to use for which types of metagenotype annotations eg 'gene-for-gene', reduced virulence etc Draft google sheet document available.

**Comment by ValWood** [comment]
I made this as a summary. After I did it I realised it was kind of obvious but it helped me when checking

![WhatsApp Image 2020-07-31 at 18 16 52](https://user-images.githubusercontent.com/7359272/89060478-02c26380-d35b-11ea-972c-e97245a4af58.jpeg)

we can also use it. to decide whether to change the workflow or  not.
Options  we could consider:

1) do not have the gene for gene extension (it should be inferable)
Problems: ???

2) precompose all of the  gene-for-gene options for compatible/incompatible and have them as ' selectable options'
Problems:  how would we distinguish from non gene-for-gene (I'm assuming these pairs are compatible with non-gene for gene, but I'm not sure)

3) Select "type" upfront 
Problem: difficult to describe available 'types'
Problem: More work to code

4) Other?
I'm not sure that any of the above are the right solution.
In some ways I think  the "extensions types" might  have been be better first with the  detailed curation as the extension.
This would fit better with the  light  high-level curation vs detailed curation model
This would be a massive change though.....it just feels intuitively a bit better as this work has evolved.

**Comment by ValWood** [comment]
Note that the empty boxes are just the ones I did not yet observe when checking

**Comment by CuzickA** [comment]
Currently checking through sessions with Val and Kim H-K. Once this has been completed and queries resolved we can move forward with developing the help documentation.

**Comment by CuzickA** [comment]
Still finding this difficult for some sessions see tickets with 'gene for gene' label.

**Comment by CuzickA** [comment]
I have added an initial draft set of rules of when to use each component of the GfG AE
available at the bottom of this Doc
https://docs.google.com/document/d/1Nm5yAHMwFYfhjRWuatlGA4_X2aSK9l12QQI1ffQXFqs/edit
@ValWood please have a look though when you are thinking about the GfG sessions

I plan to look though the current GfG and inverse GfG sessions to evaluate these rules.

**Comment by CuzickA** [comment]
Covered in PHI-Canto publication
