### ISSUE TITLE
evidence codes

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#8]
You can see all of the evidence codes PomBase has used for phenotypes, and their frequencies in this log file:

https://curation.pombase.org/dumps/latest_build/logs/log.2018-05-24-22-57-12.annotation_counts_by_cv

**Comment by CuzickA** [comment]
Thanks. So looking at this file am I right in thinking that I'm just interested in the 'fission_yeast_phenotype' evidence codes? And all the GO evidence codes will automatically be loaded into PHI-Canto under the GO curation types?

Also just to confirm -- we don't provide an evidence code for how the 'allele' was actually created. The Evidence is for the expt done in which the phenotype is observed.

**Comment by ValWood** [comment]
Both correct!

**Comment by CuzickA** [comment]
Draft version started here
https://docs.google.com/spreadsheets/d/1Uv_Zhdk3GvVXjlEUq3-nUycbR1TO-l0xpx9p40nhP18/edit#gid=164313892

**Comment by CuzickA** [comment]
Available at
https://github.com/PHI-base/config/blob/5da8ce26cc09c94747834ad1e3e6e88b2b2fa2ee/vagrant.canto_deploy.yaml

linked to issue 
https://github.com/PHI-base/phipo/issues/11
