### ISSUE TITLE
Update 'gene-for-gene' curation sessions with new GfG AE 

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#82]
https://github.com/PHI-base/phipo/issues/272

https://github.com/PHI-base/curation/issues/65 DONE

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/19 DONE

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/73 DONE

**Comment by CuzickA** [comment]
This gene-for-gene curation session is incomplete and needs work 
https://canto.phi-base.org/curs/6dd9062354648dc7
https://github.com/PHI-base/curation/issues/62

**Comment by CuzickA** [comment]
https://github.com/PHI-base/curation/issues/22 DONE

Next check with @ValWood and Kim H-K whether we are happy with changes to these four gene-for-gene sessions.

**Comment by CuzickA** [comment]
New AE for Gene-for-Gene now enabled
Need to update all sessions again and remove old AEs. Once this is done, curation type can be switched from PHI phenotype to Gene for gene phenotype and sessions can be reviewed with Val and Kim H-K.
#65 Avr1/Sen1 DONE
#73 Avrstb6/Stb6 DONE
#19 Atr1/RPP1 DONE
#62 Avr4/Cf4 incomplete session to review DONE
#22 Tox1/Snn1 DONE

**Comment by CuzickA** [comment]
I believe I have removed all the old gene-for-gene AE and replaced with the new compound terms.

@jseager7 please go ahead and check if I have got them all and then switch the sessions over to the Gene-for-Gene Phenotype work flow. Thanks.
PMID:31246152
PMID:29434355
PMID:20601497
PMID: 30148881
PMID:22241993

Next: Review the usage of the new compound AEs with Val and Kim H-K.

**Comment by jseager7** [comment]
@CuzickA the only remaining annotations with the old gene-for-gene extensions are in the two test sessions (PMID:100900 and PMID:1). I don't think it will be a problem to leave these as they are since I'm going to be testing this change locally first. We should still be able to delete the old extensions even after the annotations are transferred to gene-for-gene phenotypes.

**Comment by CuzickA** [comment]
Thanks @jseager7 I forgot about the two test sessions! 
let me know how the local changes go

**Comment by jseager7** [comment]
@CuzickA The local changes were fine, so I'll start applying the changes to the demo server first, then the main server. With regards to the old extensions that will be left over in the test sessions, I've confirmed that we can still remove them from annotations even after the annotations are transferred to the new type.

**Comment by CuzickA** [comment]
Currently reviewing sessions with Val and Kim H-K.

Closing ticket for now.
