### ISSUE TITLE
Update sessions still using old evidence code 'Macroscopic observation in heterologous species'

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#83]
https://github.com/PHI-base/curation/issues/55 session https://canto.phi-base.org/curs/87e386b652573063

@jseager7 please could you have a look and see if any other curation sessions are still using this old evidence code? Thanks

**Comment by jseager7** [comment]
As of 13 October 2020, the only publication with this evidence code, besides the one you already found, is PMID:26822079 (session `d52c749472d716e5`).

**Comment by CuzickA** [comment]
Thanks @jseager7

**Comment by CuzickA** [comment]
I have removed the old evidence code from both of the above sessions.
