### ISSUE TITLE
Typo in 'has_input' extension in PMID:30459352

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#84]
References https://github.com/pombase/canto/issues/2255

@CuzickA I've noticed that one of the annotations in [PMID:30459352](https://canto.phi-base.org/curs/cee7f6d8bab0bafd/ro/) has an incorrect name for the has_input extension: it appears as **'has_inptu'**, probably because it's been edited as text:

![image](https://user-images.githubusercontent.com/37659591/98547611-59133c80-2290-11eb-91e8-37cac830b8d0.png)

Does this GO term support the real has_input annotation extension? If so, can the extension be corrected?

**Comment by CuzickA** [comment]
Thanks. Just corrected this typo.
