### ISSUE TITLE
Restricted 'do not annotate' terms used in some sessions

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#85]
(References https://github.com/pombase/canto/issues/2255)

Not sure if this has already been discussed, but according to the syntax errors in our GAF file, two curation sessions have annotations that use a GO term tagged with 'gocheck_do_not_annotate'. They are:

- 'transcription regulator activity' (GO:0140110) in [PMID:30459352](https://canto.phi-base.org/curs/cee7f6d8bab0bafd/ro), and
- 'intracellular anatomical structure' (GO:0005622) in [PMID:21467214](https://canto.phi-base.org/curs/509bac7bf7f4f334/ro).

**Comment by ValWood** [comment]
'transcription regulator activity
If we don't  know the mechanism of transcription regulation, (i.e corepressor, GTF, DNA-binding TF), we should change this annotation to "+/- regulation of transcription"

intracellular anatomical structure
Presumably it should be possible to make this one more precise.

**Comment by jseager7** [comment]
> we should change this annotation to "+/- regulation of transcription"

There doesn't seem to be an exact match for 'positive regulation of transcription' (or negative) in GO. Instead there are qualified versions like 'viral transcription', 'reverse transcription', 'mitochondrial transcription', etc. Here's the OLS search results for 'positive regulation of transcription': 

https://www.ebi.ac.uk/ols/search?q=positive+regulation+of+transcription&groupField=iri&start=0&ontology=go

Did you have a particular term in mind?

**Comment by mah11** [comment]
> There doesn't seem to be an exact match for 'positive regulation of transcription' (or negative) in GO.

The relevant terms have slightly more complicated names:
GO:0045892 ! negative regulation of transcription, DNA-templated
GO:0045893 ! positive regulation of transcription, DNA-templated

The "DNA-templated" is one of the ways GO distinguishes "forward" transcription from reverse transcription.

**Comment by ValWood** [comment]
This might also be able to be more specific (polymerase II?)  @CuzickA

**Comment by CuzickA** [comment]
@ValWood can we have a quick look at these when we chat on Monday

Why is PHI-Canto letting us annotate with GO 'do not annotate' terms?

**Comment by ValWood** [comment]
I'm not sure if we have a hard check for this (I thought we did, but it seems not)

@mah11 do you remember? I thought at one point if a "do not annotate" restriction was present you  had to select a child term?


I tested "cell cycle" which has this comment:
Restrictions
This term should not be used for direct manual annotation; it may, however, be used for mapping to external vocabularies in order to create electronic annotations. 

(maybe thre are different tyoe of commet?)

**Comment by kimrutherford** [comment]
@jseager7 here is the PomBase config:
https://github.com/pombase/pombase-config/blob/master/canto/pombase/production_canto_deploy.yaml#L95

**Comment by jseager7** [comment]
Turns out this was due to 'gocheck_do_not_annotate' and 'gocheck_do_not_manually_annotate' being missing from the PHI-Canto configuration file, so the GO terms weren't being ignored when they should've been. I'll fix the config file then close this issue when I've confirmed that the fix has worked.

**Comment by jseager7** [comment]
The change is active on the demo server now and should be active on the main server tomorrow, but I'll leave this issue open until the GO terms above have been replaced with valid terms.

**Comment by ValWood** [comment]
- [x] 'transcription regulator activity' (GO:0140110) in PMID:30459352, and
I fixed this one

- [x] 'intracellular anatomical structure' (GO:0005622) in PMID:21467214
I removed this annotation


~this is confusing,  when I enter the PMID I get:
Welcome to Canto at PomBase
You are about to start curating data from this paper. You can either curate this paper yourself, or send it to a member of your lab to curate.
which implies that it isn't curated?~

I'll open a ticket about this.
