### ISSUE TITLE
'Secondary GO ID' errors in some sessions

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#86]
(References https://github.com/pombase/canto/issues/2255)

The PHI-Canto GAF export has errors related to usage of a 'Secondary GO ID' in two curation sessions:

- 'innate immune response-activating signal transduction' (GO:0009870) in [PMID:20601497](https://canto.phi-base.org/curs/f41d30e250b8f9b0/ro), and
- 'hyphal growth' (GO:0075061) in [PMID:29567712](https://canto.phi-base.org/curs/0d2bc8d23a8667f4/ro).

According to the [OLS](https://www.ebi.ac.uk/ols/), both the above terms are obsolete, and replaced by the following:

- GO:0009870 replaced by **GO:0002758** 'innate immune response-activating signal transduction';
- GO:0075061 replaced by **GO:0030448** 'hyphal growth'.

@ValWood @CuzickA I haven't assigned this issue to anyone, because I'm not sure who wants to fix it.

- - -

On a related note, I think this error provides evidence that GO don't want annotations made to alternative GO IDs, since GO:0075061 is an alternative ID for its successor, GO:0030448.

**Comment by kimrutherford** [comment]
> On a related note, I think this error provides evidence that GO don't want annotations made to alternative GO IDs, since GO:0075061 is an alternative ID for its successor, GO:0030448.

Sounds like if we fix https://github.com/pombase/canto/issues/2362 then these GAF errors will go away.

**Comment by jseager7** [comment]
I've checked the sessions again: for the primary terms, [PMID:20601497](https://canto.phi-base.org/curs/f41d30e250b8f9b0/ro) now has GO:0002758 'innate immune response-activating signal transduction', and [PMID:29567712](https://canto.phi-base.org/curs/0d2bc8d23a8667f4/ro) now has GO:0030448 'hyphal growth'.

However, there is a **part_of** annotation extension in [PMID:20601497](https://canto.phi-base.org/curs/f41d30e250b8f9b0/ro) that still has the (merged) GO:0009870 term ID, presumably because Canto doesn't check annotation extension terms in the same way.

![image](https://user-images.githubusercontent.com/37659591/99956621-39930e00-2d7e-11eb-9455-66ade48e0ae4.png)

@CuzickA could you fix this one remaining extension by deleting and re-adding it with the same term, or by amending the term ID to **GO:0002758** using edit as text? I can try doing it if you're happy for the change to be made.

**Comment by CuzickA** [comment]
I've made the change. Closing ticket.
