### ISSUE TITLE
Missing UniProtKB prefixes on some manually edited extensions

### ISSUE THREAD

**Issue by jseager7** [PHI-base/curation#87]
(References https://github.com/pombase/canto/issues/2255)

One of the syntax errors in our GAF export was due to the fact that UniProtKB accession numbers were not prefixed with 'UniProtKB:' when used in annotation extensions. This has since been fixed in https://github.com/pombase/canto/issues/2363, but there are a few remaining annotations to which this change has not applied, presumably since they were edited as text.

Both annotations are in [PMID:30459352](https://canto.phi-base.org/curs/cee7f6d8bab0bafd/ro). The UniProtKB identifier F9X6V3_ZYMTI is invalid, and should instead be UniProtKB:F9X6V3.

UniProtKB | Gene name | Term ID | Annotation Extension
-- | -- | -- | --
F9X6V3 | MYCGRDRAFT_91615 | GO:0008897 | has_direct_input(F9X6V3_ZYMTI)
F9XD62 | MYCGRDRAFT_93828 | GO:0140110 | has_input(F9X6V3_ZYMTI),part_of(GO:0048023)

@CuzickA If the **has_input** and **has_direct_input** extensions are not available on these GO terms, you can probably fix this by editing as text and prefixing each accession number with 'UniProtKB:'. So the extensions would change as follows:

invalid | valid
-- | --
has_direct_input(F9X6V3_ZYMTI) | has_direct_input(**UniProtKB:F9X6V3**)
has_input(F9X6V3_ZYMTI),part_of(GO:0048023) | has_input(**UniProtKB:F9X6V3**),part_of(GO:0048023)

If you'd prefer to have the extensions enabled, let me know and I can look at changing the relevant extension configuration.

**Comment by kimrutherford** [comment]
The code currently will only add the database prefix to identifiers of proteins that have been added to the session and it only checks the accession number.  I suspect the accession number is required in extensions for GAF submission.

In this case:
> has_direct_input(F9X6V3_ZYMTI)
I think the ID should be "F9X6V3"

**Comment by ValWood** [comment]
That'r right. F9X6V3_ZYMTI is an identifier not an accession.

**Comment by jseager7** [comment]
> That's right. F9X6V3_ZYMTI is an identifier not an accession.

Thanks for catching that. I'll update my previous comment.

**Comment by CuzickA** [comment]
I've made the change to
![image](https://user-images.githubusercontent.com/11753634/99800223-ed508f80-2b2b-11eb-9128-d88a8e0e3e22.png)
