### ISSUE TITLE
Discuss use of AE 'assayed using' for PHIPO Protein-protein binding annotations to metagenotypes

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#88]
There is an option with this AE to add both of the binding proteins.
However, 
1) this information duplicates the pathogen and host genes within the metagenotype
2) it may be okay for control metagenotypes, but when the gene has been altered it is not possible to select this altered genotype, only the wild type UniProt can be selected. This could be misleading.
3) when there is a protein-protein binding between the wild-type pathogen protein and host protein this is annotated as a physical interaction.

@ValWood Do we need this AE 'assayed using' or am I missing something here??

I have been looking at GfG sessions 
atr1/rpp1 https://canto.phi-base.org/curs/f41d30e250b8f9b0
avrstb6/stb6 https://canto.phi-base.org/curs/69e99b22bfebf3b0

![image](https://user-images.githubusercontent.com/11753634/100260812-cb974400-2f41-11eb-8380-7bd87f5340d8.png)

**Comment by ValWood** [comment]
I', not following all of this. I see that pathogen host interactions are different from single species because you are pretty much  always dealing  with the genotypes of the interaction molecules, so we might be able to shortcut this somewhat. I did not fully understand the rest though so we should look at this on Monday.

**Comment by CuzickA** [comment]
It looks like we have used the assayed_using for avrstb6/stb6 https://canto.phi-base.org/curs/69e99b22bfebf3b0
so I will also add to atr1/rpp1 https://canto.phi-base.org/curs/f41d30e250b8f9b0

**Comment by CuzickA** [comment]
I guess we will still record the two proteins being assayed as they may be different proteins than those specified within the metagenotype in some cases.

Closing ticket for now.
