### ISSUE TITLE
PMID:32883427 Functional evaluation of a homologue of plant rapid alkalinisation factor (RALF) peptides in Fusarium graminearum

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#89]
https://canto.phi-base.org/curs/925be40b9263f9e8/ro/

Trial curation by Ana of her own paper into PHI-Canto.

Here are a few screen shots of her annotations
![image](https://user-images.githubusercontent.com/11753634/104897337-29f40800-5970-11eb-9707-9ea0052e89dd.png)
![image](https://user-images.githubusercontent.com/11753634/104897396-3c6e4180-5970-11eb-9b31-d22bc24a8552.png)

I need to read the publication and look at the annotations that have been made.
Initial thoughts - should there be a metagenotype with annotations in this session??

**Comment by CuzickA** [comment]
I have changed names of alleles to 'RALF'
overexpression allele was made incorrectly. Author had selected allele type 'other' and overexpression, I have updated this to allele type 'wild type' with overexpression.

**Comment by CuzickA** [comment]
No mention of 'peptidase' in paper Fig 3 and 5

Continue checking from Fig 6 next

**Comment by CuzickA** [comment]
Tricky issues in curating this paper
1) no obvious disease phenotype for Fig 3 Fg on wheat 
text uses language like 'diseased' and 'FHB disease'
I have decided to record this phenotype as 'host lesions'
2) transgenic hosts have been created with a pathogen gene
I have made these into metagenotypes.
It is not possible to curate WT controls in some cases as we cannot create a metagenotype with an empty vector (EV) control
3) conditions
recording the 'age' of the transgenic plant is not straight forward with the conditions. 
eg '2 weeks post inoculation', would it be better to have '2 weeks old?' Here we are looking at a metagenotype of transgenic host carrying pathogen gene. Follow on expts then inoculate with a WT pathogen so we can use condition '+ wild type pathogen inoculation' but it is still tricky to capture the age of transgenic plant vs timing after inoculation that observation was made.
_Need NTR for PHI-ECO 'pathogen gene expressed by transgenic host'_

**Comment by CuzickA** [comment]
author created allele
![image](https://user-images.githubusercontent.com/11753634/105052251-930a7700-5a67-11eb-8d1a-086af8f9bc8c.png)

I have changed to
![image](https://user-images.githubusercontent.com/11753634/105052410-c3521580-5a67-11eb-916e-d328e196ad5b.png)

Similar author error as above in not using allele type 'wild type' and adding the gene/uniprot name to the description section

**Comment by CuzickA** [comment]
Fig 8 wheat gene silencing
![image](https://user-images.githubusercontent.com/11753634/105053160-8f2b2480-5a68-11eb-814b-d9f2807d2df8.png)
![image](https://user-images.githubusercontent.com/11753634/105053610-0e205d00-5a69-11eb-9f28-b8fd9779514e.png)

I think WT genotypes need to be made for each wheat homeologue and then combined as a multi-allele to indicate FER1 silencing and FER2 silencing

Note all of these wheat UniProt ids are in UniParc

![image](https://user-images.githubusercontent.com/11753634/105055610-28f3d100-5a6b-11eb-9066-223edb380568.png)

**Comment by CuzickA** [comment]
Following are current screenshots of session
![image](https://user-images.githubusercontent.com/11753634/105057777-783b0100-5a6d-11eb-9563-72cb5d37dcb7.png)
![image](https://user-images.githubusercontent.com/11753634/105057894-956fcf80-5a6d-11eb-9fd6-4a5556778655.png)
![image](https://user-images.githubusercontent.com/11753634/105058128-cea83f80-5a6d-11eb-8f3f-573d34a72626.png)
![image](https://user-images.githubusercontent.com/11753634/105058230-e4b60000-5a6d-11eb-9121-2fad6146bf6e.png)
![image](https://user-images.githubusercontent.com/11753634/105058315-fe574780-5a6d-11eb-91ea-656ae330ef6c.png)
![image](https://user-images.githubusercontent.com/11753634/105058353-0a430980-5a6e-11eb-9175-24bd0122e9ad.png)

Just to note I have not yet deleted orginal annotations by author.

**Comment by ValWood** [comment]
Yes, might be useful to see why they were confused if anything can be tweaked.

**Comment by CuzickA** [comment]
Need NTR for PHI-ECO 'pathogen gene expressed by transgenic host'

**Comment by CuzickA** [comment]
I have 

i) Deleted the incorrect old annotations recorded above.

ii) Noted that it is difficult to annotate many of the metagenotype controls in this session

iii) still have a query on whether we need PHI-ECO terms for age of plants rather than time after inoculation

@ValWood please could you have a check through of this session and let me know what you think about point iii) thanks.

**Comment by CuzickA** [comment]
Removed AE causes_disease
Added Disease name curation type

Synonyms see https://github.com/PHI-base/phido/issues/4

![image](https://user-images.githubusercontent.com/11753634/107767312-b229bb00-6d2c-11eb-881d-c2e8cc7982c6.png)

**Comment by CuzickA** [comment]
Hi @ValWood, please could you check this session. looks like I just have a query about the conditions (text from above)

> iii) still have a query on whether we need PHI-ECO terms for age of plants rather than time after inoculation

and then this should be ready to approve thanks.

**Comment by ValWood** [comment]
I checked this session and it looks fine to me. I agree it is tricky about the conditions for 'age' as it will be another bunch of conditions. However, if this is something you think you need to capture I guess you will need to add them? Otherwise this one looks complete to me.
v

**Comment by CuzickA** [comment]
Thanks @ValWood 
For the conditions do you think I should add 'host' to the label? Otherwise it may not be clear if we are referring to the age of the pathogen or the host.
eg 'host: one week old'
Definition: Host organisms were observed or treated at one week old.

**Comment by ValWood** [comment]
I guess so...

**Comment by CuzickA** [comment]
PHI-ECO terms created - just waiting for loading into PHI-Canto.

**Comment by CuzickA** [comment]
PHI-ECO terms now added, session approved, closing ticket.
