### ISSUE TITLE
examples of abolished binding and modifiacation

### ISSUE THREAD

**Issue by ValWood** [PHI-base/curation#9]
I have a note that I would circulate examples of 
loss of binding and
loss of modification type phenotypes. This is from a while ago and I cannot remember the exact context but i thinkit arose from discussion of which phenotype evidence codes you might use.

Anyway here are the  annotations to
abolished protein-protein interaction (FYPO:0000705)
https://www.pombase.org/term/FYPO:0000705

decreased protein-protein interaction (FYPO:0001645)
https://www.pombase.org/term/FYPO:0001645

abolished protein modification (FYPO:0002497)
https://www.pombase.org/term/FYPO:0002497

decreased protein modification (FYPO:0002498)
https://www.pombase.org/term/FYPO:0002498

Use "show details" to display evidence codes used.

This may also be related to another item to discuss "protein binding in another species"

I think for this you will be able to use the same terms, just with different species in the extension.

We can test such curation types one  you have some terms.

**Comment by CuzickA** [comment]
Thanks for these terms. 
I'm not sure if I am remembering the same conversation but in the past we were talking about the curation type 'Physical Interaction' needing "protein binding in another species". (Do we also want protein binding within an organism?).

A few questions
1) Is the 'Physical Interaction' curation type just for WT Physical Interactions (similar to the GO curation types)? 
2) To curate physical interactions between altered gene products (genotypes) would they be entered as a meta-genotype and annotated with a phenotype such as 'abolished protein-protein interaction'?
3) Would a curator be expected to enter information for 1) and 2) above with 1) essentially being the WT control?
4) Would it be better to combine this somehow?

**Comment by ValWood** [comment]
1.  Short answer yes. Long answer:

Currently we curate physical interactions in one of 2 ways.

BioGrid use a 'spoke" type model for some evidence types where they capture all interacting species in a pull-down (after the removal of known common contaminants). This means that this curation includes for example all members of a complex, not only the direct binding partners. 

We also capture  protein-binding using GO, but we reserve this for  direct -protein protein interactions (this is important because it is part of our pathway building pipeline)
http://www.esyn.org//builder.php?type=Graph&term=GO:0006281&interactionType=physical&source=pombase&includeInteractors=false

2. yes. We capture abolished binding as phenotypes. This would also work for abolished interaction phenotypes between species.

3. Yes, normally we would annotate the normal protein binding in BioGRId, also in GO if direct.
Then we capture any altered binding experiments for specific genotypes using FYPO.

4. It would be difficult to combine because one is describing a 'normal'  physical interaction, and one is capturing changes in observed interaction. In this respect it is the same as other curation. FOr example we capture a 'normal' location, or activity, using GO, and then an altered  (or unaltered) localization or activity using phenotypes.  So how we capture binding mirrors this.
In some ways the workflow might be  more intuitive if they were all handled together but this would be a big change to many procedures  (not only in Canto but in how terms were described using the underlying ontologies used to describe things).

Because of this, we might need better prompts   to describe users that additional curation types might be required ( I.e you curated this datatype,  therefore you might also want to curate this datatype) type things.....These would be good things to think about when we start testing.

**Comment by CuzickA** [comment]
Thanks for answering my questions :-). 

It sounds like I will need to incorporate the above binding phenotypes into phipo.

**Comment by CuzickA** [comment]
After today's call we considered whether we would split the 'Physical interaction curation type' into 2 options in PHI-Canto

-endogenous physical interaction (within organism)
-heterologous physical interaction (between different organisms)

**Comment by CuzickA** [comment]
closing for now. binding phenotypes covered on phipo tracker
