### ISSUE TITLE
PMID: 32794614 The Brassica napus wall-associated kinase-like (WAKL) gene Rlm9 provides race-specific blackleg resistance

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#90]
Cannot find an active UniProt id for host gene Rlm9 Brassica nappus (rape)

publication provides BnaA07g20220D

However, no results found when search in UniProt or UniParc

NCBI have removed record
![image](https://user-images.githubusercontent.com/11753634/105156466-cac6fc80-5b03-11eb-856d-cfad6e2d26e7.png)

Using the locus id provided by NCBI CDX67982 I searched UniProt and found UniParc entry
![image](https://user-images.githubusercontent.com/11753634/105156684-11b4f200-5b04-11eb-82f1-e07bc7366d4c.png)

The UniProt Id is obsolete and will not load into PHI-Canto
A0A078BUT7.1 (obsolete)
![image](https://user-images.githubusercontent.com/11753634/105157024-78d2a680-5b04-11eb-8fa1-aa827a05d58c.png)

![image](https://user-images.githubusercontent.com/11753634/105156812-3b6e1900-5b04-11eb-8a78-716c02f60e8d.png)

**Comment by ValWood** [comment]
Hi @marcfeuermann,

At PHI-base we are coming across instances like this one where we cannot locate specific sequence entries in Uniprot . I will be documenting some of these  issues shortly as  our  downstream partners at Knetminer are having difficulties  identifying a lot of entries that have been curated historically at PHI-base.

 For instance, in the past, I reported  some cases  where a specific strain  was obsoleted and it became difficult to trace the existing entry.

However, this case seems slightly different. First do you have any tips how to locate these entries? Who would be the best person at UniProt to speak with about this type of problem of entries  not being archived in a way that makes them findable (and therefore FAIR)?

**Comment by CuzickA** [comment]
Closing ticket as not possible to curate this paper due to lack of host uniprot id
