### ISSUE TITLE
PMID:27819043 The hijacking of a receptor kinase-driven pathway by a wheat fungal pathogen leads to disease.

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#91]
Trial curation of this paper into main PHI-Canto tool by Chris Stephens (final year PhD student)

https://canto.phi-base.org/curs/6ddeb3a009b5a0e5

We talked through the curation of Fig 2B and 2D and did this together online. Chris will work though some more annotations and we will meet again in a couple of days.

![image](https://user-images.githubusercontent.com/11753634/105187636-e8f42300-5b2a-11eb-8774-8590a1f35af7.png)
![image](https://user-images.githubusercontent.com/11753634/105187700-fad5c600-5b2a-11eb-994a-a0692a02a06a.png)

### 1) Gene-for-gene interaction annotation extension

* List is too long and hard to read (nearly missed required term by choosing one higher up the list)
* Would be better if the 3 components could be selected individually rather than hard to read compound term (or maybe first select 'compatible' or 'incompatible' and then have compound term contain pathogen effector and host R gene info)
* For necrotrophic effectors we have mocked up equivalent GfG AE terms in session using clearer language such as necrotrophic effector and susceptibility locus. This may be clearer for curators and data users wanting to search PHI-base for a 'susceptibility locus' rather than a host R gene.
* If we use these new terms the AE list will be even longer. Could this be separated somehow? Maybe two gene-for-gene curation link options i) standard GfG (biotrophs avr-R) ii) inverse GfG (necrotrophs NE-SL)
* _(29Jan 2021) I have created and reannotated with inverse GfG term, a new AE is planned https://github.com/PHI-base/config/issues/50_
_(05_02_2021 new AE inverse GfG now used in session)_
### 2) Editing annotation extensions

* 'Edit' button not very clear to see, maybe make button darker grey colour
* Not easy to tell which AE have been used  or need to be used
* It is odd here that the used AE have not turned to grey?? 
  ![image](https://user-images.githubusercontent.com/11753634/105188125-78013b00-5b2b-11eb-9923-be89949d1d08.png)

### 3) Overall curation workflow

* Overall layout good and clear
* Not a linear process, not always clear where to go for each step. Particularly on the first summary landing page – for a new curator it is hard to know where to start.
* More help prompts within tool would help with direct links to the relevant help section documentation

### 4) Training materials

* Chris has not yet read the text help documentation but has watched my old YouTube tutorial and the recently recorded lab meeting demo. He thought the YouTube video (now outdated) was very useful and the lab meeting demo very easy to follow and that something similar should be linked to the PHI-Canto landing page. He prefers videos than text. The benefit of the video is that the user can be listening to it whilst following though the instructions within the curation session.
* On the front page it is good to have the heading 'first time curator' and in addition to the help text if would be good to have video links here as well.
* Perhaps have short video snips, or section link tos, for each step on the contents page e.g. adding genes, adding strains etc.

### 5) Initial curation email

* may be useful to ask curators to check their junk email folders for this email.

FYI @ValWood @jseager7

**Comment by jseager7** [comment]
> List is too long and hard to read (nearly missed required term by choosing one higher up the list)
> Would be better if the 3 components could be selected individually rather than hard to read compound term (or maybe first select 'compatible' or 'incompatible' and then have compound term contain pathogen effector and host R gene info)

I suspected this would happen once we tested the system on community curators. The simplest fix I can think of is to add individual annotation extensions for each part of the compound terms, even though that removes the efficiency benefit of the original solution. Individual extensions might not be suitable if the options need to depend on each other (as suggested above). Implementing the feature any other way is going to be a lot of work and will need careful discussion.

> If we use these new terms the AE list will be even longer. Could this be separated somehow? Maybe two gene-for-gene curation link options i) standard GfG (biotrophs avr-R) ii) inverse GfG (necrotrophs NE-SL)

We maybe want to be careful that we don't make the list of options longer than the metagenotype rows, but really these rows should be using a pop-up list (like the Genotype Management page) instead of having the list always visible. If we can fix that then we can add an arbitrary number of curation types (albeit at the cost of some redundancy in the configuration).

On the other hand if the annotation extension list is broken up into multiple fields, this might be less of a problem.

> 'Edit' button not very clear to see, maybe make button darker grey colour

There was some discussion of this problem at https://github.com/pombase/canto/issues/2339#issuecomment-725382391, but the issue was closed before deciding on any solutions.

**Comment by jseager7** [comment]
> It is odd here that the used AE have not turned to grey??

@CuzickA Which annotation extensions were you expecting to be disabled? We may just need to tweak the cardinality settings.

**Comment by jseager7** [comment]
> Not a linear process, not always clear where to go for each step. Particularly on the first summary landing page – for a new curator it is hard to know where to start.

> On the front page it is good to have the heading 'first time curator' and in addition to the help text if would be good to have video links here as well.

We could explore adding an intro page or some extra guidance for first-time curators. If the introduction was tied to a curation session being started, then we probably wouldn't need to set browser cookies to keep track of things. I definitely think we should hide the feature for admin curators. Hiding the feature for community curators who are starting a second new curation session could be a bit tricky, but maybe if Canto could do this by tracking the first time a curator email or ORCID was used.

**Comment by jseager7** [comment]
> Perhaps have short video snips, or section link tos, for each step on the contents page e.g. adding genes, adding strains etc.

We could look at embedding video clips or animated GIFs into the documentation if we think that the effort is justified. It would take quite a bit of work, and it wouldn't really work with the current documentation setup, because all our documentation is stored in the pombase/canto repository (once it's published anyway; before then it's stored in PHI-base/docs). We definitely don't want to add video clips or animated GIFs to the repository itself, because most version control software (particularly Git) really isn't designed for that.

If we had somewhere external that we could store this media (maybe just as simple as a folder on the Canto server), and we could link to the files in the documentation, then it would be feasible.

**Comment by ValWood** [comment]
- I also think the gene-for-gene is difficult (although I have not yet tested the current implementation, it  feels cumbersome.
- I agree about extensions, I'm thinking a lot about this for PomBase. Community curators often miss extensions. One task on my list currently is to find out if they are using the copy edit option or the 'full' workflow, and then to  figure out what improvements we could make. I would like to see the "desirable"  extensions available by default, without over-complicating the pop-up.

**Comment by jseager7** [comment]
> Community curators often miss extensions. One task on my list currently is to find out if they are using the copy edit option or the 'full' workflow

I'm guessing that in PHI-Canto's case, the initial pathogen-host interaction annotation is done using the standard workflow, then curators use that annotation as a template for subsequent interactions that are created using Copy and edit. Presumably this is because the burden of our annotation extensions is higher than it is for PomBase. If that's the method Alayne uses, then it's likely to be passed on to community curators during initial training. So maybe the usability issues of the Copy and edit pop-up will be more noticeable with PHI-base.

**Comment by ValWood** [comment]
> I'm guessing that in PHI-Canto's case, the initial pathogen-host 
> interaction annotation is done using the standard workflow, then 
> curators use that annotation as a template for subsequent interactions 
> that are created using Copy and edit. Presumably this is because the 
> burden of our annotation extensions is higher than it is for PomBase. 
> If that's the method Alayne uses, then it's likely to be passed on to 
> community curators during initial training. So maybe the usability 
> issues of the Copy and edit pop-up will be more noticeable with PHI-base.
>

I suspect it is the same for PomBase, but I was asked by Kim and Midori 
to confirm which workflow people are using. I *hope* most people use 
copy edit,  but I'm speculating.....

**Comment by CuzickA** [comment]
Chris made a couple more annotations on his own, I read through the paper and made a couple of edits/ new annotations. We met again this morning to talk through the annotations we have.

A few further points of note

6) Chris made the 'infiltration' annotations (Fig 2B,C) in the PHI curation type instead of the GfG. He is going to manually re-enter these 4 annotations into the GfG section. I foresee that we will have this problem in the future as it is not always clear which workflow to use (see https://canto.phi-base.org/curs/69e99b22bfebf3b0/ro/ where both the PHI and GfG sections are used within the session). Could we have a 'quick' mechanism for switching annotations between these two type? Perhaps for Admin?
_(29Jan 2021) see https://github.com/PHI-base/curation/issues/94 for ticket tracking examples of this issue_

7) It was not very clear how to deal with the different delivery methods of delivering the pathogen effector into the plant. We wanted to annotate expts with i)purified pathogen effector infiltrated into host and ii) effector delivered naturally by pathogen inoculation.  Following a similar curation session #22 we remembered that the metagenotypes were created in the same way and that the conditions indicated the different delivery mechanisms.  #69 is an open ticket on delivery mechanisms which needs further discussion. Once resolved we will need to make this clearer for curators - perhaps with text or curation example.
_(29Jan2021) I have prefixed relevant PHI-ECO terms with 'delivery mechanism:' this should make searching clearer. Help text will be added to the conditions section. Plan to create a new selection box after conditions to add the delivery mechanism_

8) Choosing the correct phenotype observation. Chris looked at 'infiltration' images in Figure 2B, C and saw 'chlorosis' however the authors of the paper did not use this language instead they used 'necrosis'. We switched these annotations to 'pathogen-associated host lesion' terms instead.

9) The 'RNA level' curation type vs using a PHIPO term annotated to meta/genotype. This is still fairly new to me as I have not made many of these annotations. So far
![image](https://user-images.githubusercontent.com/11753634/105502469-60f25280-5cbd-11eb-9811-7a3970d95648.png)
![image](https://user-images.githubusercontent.com/11753634/105503981-25588800-5cbf-11eb-8c93-b38c7d266878.png)
@ValWood can we talk this through to make a set of 'rules' to follow
_(29Jan 2021) This is still being resolved. Additional help text and popups should make this clearer. Suggest rough guide is to only curate single species WT RNA level, and to curate both WT and altered metagenotype using PHIPO annotations. Now looks like this_
![image](https://user-images.githubusercontent.com/11753634/106288354-d6bb6880-623f-11eb-8a13-9aa413611c8d.png)
![image](https://user-images.githubusercontent.com/11753634/106288463-feaacc00-623f-11eb-9349-f2e26d6d1b0d.png)



10) Similar issue as 9) for using 'physical interaction' vs PHIPO term annotation
Chris added below - the first annotation shows NOT binding (but this detail is lost in the comment), the second shows binding but only to fragment (again detail lost in the comment)
![image](https://user-images.githubusercontent.com/11753634/105504301-81bba780-5cbf-11eb-86f8-e3ecd5b143b9.png)
I thought this may be better under the PHI section (constructs not tested in GfG expt in planta)
![image](https://user-images.githubusercontent.com/11753634/105504681-f5f64b00-5cbf-11eb-9fdd-305d88996b4d.png)
Again I think we need clear guidance on which curation type to use.
__(29Jan 2021) only curate 'physical interaction' if it is biologically relevant, curate controls and shifts in binding as PHIPO annotations _
Now looks like this_
![image](https://user-images.githubusercontent.com/11753634/106287828-2d747280-623f-11eb-9dd2-1fb476d1bb8b.png)
![image](https://user-images.githubusercontent.com/11753634/106287907-4846e700-623f-11eb-89d5-4d1fde4654dc.png)



11) Hard to know which is the best term to use here (signaling vs level)-see comments
![image](https://user-images.githubusercontent.com/11753634/105505738-399d8480-5cc1-11eb-8a81-7a603632e073.png)
_(29Jan 2021) Correct to use level here. Now looks like this_
![image](https://user-images.githubusercontent.com/11753634/106288078-7debd000-623f-11eb-9625-8b4ddc4ef38f.png)


12) alleles
- looked a other session #22 to create these alleles 
![image](https://user-images.githubusercontent.com/11753634/105506526-10312880-5cc2-11eb-94e0-92cf0904d0b5.png)
-top line- initially host genotype was selected as 'WT wheat bobwhite', changed to 'Tox1- (no endogenous copy)'
-bottom line- not easy to know how to name the 'transformed allele'

![image](https://user-images.githubusercontent.com/11753634/105507024-98afc900-5cc2-11eb-8bad-eaaec53937c2.png)
-in this case for the host mutant the start and end of gene were deleted, Chris thought the way this was displayed looked like these 2 fragments were the ones remaining in the expt rather than being removed. We renamed the allele 'Snn1:158-297' to indicate that it was this middle fragment that was used within the expt.

It would be good to have examples of these 'tricky' alleles in the help doc or videos.

 





13) Feedback on initial curation email
-Seems like all key info is there and clear enough to follow.
-Don't want any more info at this stage as it could be overwhelming, better to have the linkouts to further info for user to follow up as required.

**Comment by jseager7** [comment]
> Could we have a 'quick' mechanism for switching annotations between these two type? Perhaps for Admin?

For now I think we've decided to try and prevent this from happening in the first place with extra curator guidance (ideally at the first screen of the step-based curation interface), but I'm not sure that will be sufficient, especially since including help text in the step-based workflow won't help curators that prefer the pop-up-based workflow.

It might not be so bad to add this feature if it was admin-only, but making it available to all users will need some careful thought about how to handle creating invalid annotations. Different annotation types can have different ontology namespaces, and even those in the same ontology namespace can have different annotation extensions. The transfer feature will either have to clear these incompatible properties or prompt the curator to change them.

**Comment by CuzickA** [comment]
Hi @ValWood do you think these 'physical interaction ' annotations should be deleted in favour of keeping the PHI phenotype annotations below?

![image](https://user-images.githubusercontent.com/11753634/105839676-c26e3600-5fc9-11eb-9add-2b5a2278482a.png)

![image](https://user-images.githubusercontent.com/11753634/105839781-e5004f00-5fc9-11eb-9ec3-051426242024.png)

**Comment by ValWood** [comment]
I  would keep one "physical interaction annotation" to show  that the interaction exists and they expect it occurs in vivo. Make the comment more explicitly that  these constructs were made to get around some membrane issue.

**Comment by CuzickA** [comment]
> I would keep one "physical interaction annotation" to show that the interaction exists and they expect it occurs in vivo. Make the comment more explicitly that these constructs were made to get around some membrane issue.

and keep both of the PHIPO term annotations?

**Comment by ValWood** [comment]
Actually i'm not sure about those. There is presence and loss of binding but it is more in the realm of a control, and not representing what is thought to occur in vivo. I  would be inclined not to capture these differences as phenotypes in this particular case. 

We really use the phenotype loss of binding to establish when mutants create a "functionally relevant loss of binding". 
I would not worry about trying to explain this to users. It's an edge case and probably not   a type of experiment that is used often?

**Comment by ValWood** [comment]
can discuss tomorrow?

**Comment by CuzickA** [comment]
I have now added the new (inverse) GfG AE terms to this session to cover the pathogen Necrotophic Effectors and host Susc locus. (Note: still a few typos to resolve in these new PHIPO_EXT terms).
These new terms work well and are clearer than using original terms created for the biotrophs.

I will apply these new (inverse) GfG AE terms to the other relevant session https://github.com/PHI-base/curation/issues/22

It is possible that this will leave some 'unused' GfG terms that can then be obsoleted to keep the number of choices down.

It may also be worth considering have two options for the AE in the GfG work flow
i) GfG (for biotrophs)
ii) inverse GfG (for necrotrophs)
This would further reduce the number of available terms in the dropdown for each option

@ValWood I would still like to discuss the 'RNA level' and 'Protein interaction' annotations with you. _Discussed 29Jan 2021, notes above and session updated_

**Comment by CuzickA** [comment]
Just waiting for a NTR from PHI-ECO then session is complete and ready for approval

**Comment by CuzickA** [comment]
Added new PHI-ECO term
Switched GfG AE to inverse GfG AE

Session now approved

**Comment by CuzickA** [comment]
Added disease curation type and removed AE causes_disease
![image](https://user-images.githubusercontent.com/11753634/107654772-dfb62c00-6c7a-11eb-8530-0ef1d628b608.png)
