### ISSUE TITLE
PMID: 31575748 Xanthomonas translucens commandeers the host rate-limiting step in ABA biosynthesis for disease susceptibility

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#97]
First host target paper suggested by Kim Hammond-Kosack for curation

**Comment by CuzickA** [comment]
Current link https://canto.phi-base.org/curs/2c927ce951d0944f

Note: session currently contains dummy entry UniProt for Fg TRI5 as I was testing out the PHI-Canto email templates.

**Comment by CuzickA** [comment]
Hi @smvelasquez, I started entering the PMID for this publication into PHI-Canto but have now just reassigned this session to you. You should have an email with the session link. Please let me know if there are any issues.

**Comment by smvelasquez** [comment]
I'll let you know (this is also my trial putting a comment)

**Comment by CuzickA** [comment]
Thanks. Your trial comment has worked :-)

**Comment by smvelasquez** [comment]
I am having issues finding the Uniprot code for TAL8 from Xanthomonas translucens pv. undulosa. I have the protein sequence and I've blasted in Uniprot and I get matches to Xanthomonas oryzae pv. oryzae. However, when I go to BLAST itself, it does find the correct protein (NCBI Accession AKK68514). Any clues how should I go about it?

**Comment by ValWood** [comment]
@jseager7  it might be worth mailing UniProt helpdesk to see e why this isn't available (NCBI should exchange data with ENA/EMBL and from here it should get into UniPRot Trembl).

**Comment by ValWood** [comment]
@smvelasquez  first which UniProt blast option did you use?

**Comment by smvelasquez** [comment]
@ValWood On the main page, the BLAST symbol on the top left corner

**Comment by jseager7** [comment]
I found this entry in UniParc, which seems to match the accession number from NCBI GenBank:

https://www.uniprot.org/uniparc/UPI000641D658

Based on the [history](https://www.uniprot.org/uniprot/A0A0G3LPK9?version=*) for the accession, it seems it was deleted from UniProtKB on 16 January 2019.

**Comment by jseager7** [comment]
I'm just running BLAST on this accession now to see what the closest active entry in UniProtKB is.

**Comment by jseager7** [comment]
@smvelasquez Here's a link to the query results:

https://www.uniprot.org/blast/uniprot/B20220411F248CABF64506F29A91F8037F07B67D10387A5F

The closest match based on identity is [A0A1C3TJJ8](https://www.uniprot.org/uniprot/A0A1C3TJJ8). You can see the sequence alignment [here](https://www.uniprot.org/blast/uniprot/B20220411F248CABF64506F29A91F8037F07B67D10387A5F?alignment=4).

Unfortunately, the above accession is on pv. translucens, not pv. undulosa, and UniProtKB seems to refer to the gene as talCU1 instead of TAL8.

**Comment by ValWood** [comment]
Hi Alex, Can you put is in contact with the person in the UniProt software team who can tell us why this entry has been deleted from UniProt?
@alexsign

Thanks!
Val

**Comment by alexsign** [comment]
@ValWood Hi Val, I've sent the message to UniProt production team, hopefully they can comment on it soon.

**Comment by alexsign** [comment]
UniProt production needs to know which accession is deleted

**Comment by jseager7** [comment]
@alexsign The deleted accession is A0A0G3LPK9 (https://www.uniprot.org/uniprot/A0A0G3LPK9)

Here's the corresponding entry in UniParc: https://www.uniprot.org/uniparc/UPI000641D658

**Comment by CuzickA** [comment]
Has there been any progress on identifying an active UniProt ID for TAL8 from Xanthomonas translucens pv. undulosa?
