### ISSUE TITLE
Check usage of 'GO:0048046 apoplast' in curated sessions

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#98]
It may need updating to 'GO:0140593 host apoplast' in cases where the pathogen gene product is functioning within host apoplast, rather than a host gene product functioning within apoplast.

https://www.ebi.ac.uk/QuickGO/term/GO:0140593
https://www.ebi.ac.uk/QuickGO/term/GO:0048046

@jseager7 please could you pull out any sessions annotated with 'GO:0048046 apoplast'

**Comment by jseager7** [comment]
@CuzickA I'll have to make a new export before I can check this because the current one is pretty outdated.

**Comment by jseager7** [comment]
@CuzickA Sorry about the delay. Here's the list of publications.

- [x] [PMID:15096512](https://canto.phi-base.org/curs/babb18b437174938)
- [x] [PMID:21467214](https://canto.phi-base.org/curs/509bac7bf7f4f334)
- [x] [PMID:26163574](https://canto.phi-base.org/curs/14a019de155e0d8d)
- [x] [PMID:30610168](https://canto.phi-base.org/curs/79c56f92435923ab)
- [x] [PMID:30651637](https://canto.phi-base.org/curs/7f79fa45d157bd97)

You can use the checkbox next to each PMID to track which ones you've reviewed, if you like.

Note that I searched for any session where 'apoplast' (GO:0048046) was annotated as a primary term or an extension.

**Comment by CuzickA** [comment]
Thanks @jseager7

**Comment by CuzickA** [comment]
All now checked and changed, closing ticket
